### ISSUE TITLE
Support library watching in core

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1039]
Original [issue 1039](https://code.google.com/p/quodlibet/issues/detail?id=1039) created by nick.boultbee on 2012-10-11T21:37:16.000Z:

This is a placeholder for something that's been discussed for a while now - the integration of the Auto Library Update code (or at least the concept), with some kind of support or at least fail-proof mechanism for Windows / other OSes without inotify.

This may be a long-term goal, of course, but it would enable or help a few other features, e.g. Issue #961, and it feels deep enough into the library to warrant this.

**Comment by declension** [comment]
The development for this, whilst long stalled now, is in the [watched-library](https://github.com/quodlibet/quodlibet/tree/watched-library) branch.

**Comment by lazka** [comment]
Two things that should be investigated:

* If a user renames a file and a moved event is triggered we should just emit a changed signal
* If a file is renamed in QL the resulting event (create/delete or move, depending on the monitor backend) should be ignored/handled somehow.

**Comment by declension** [comment]
Thanks. Also, a few "obvious" ones I forgot:

* Actually remove the old plugin.
* Consider a migration step: if the plugin was enabled, enable (new) auto-watching of library.

**Comment by lazka** [comment]
There is a C impl using glib: https://blogs.gnome.org/chergert/2017/12/19/builder-3-27-progress-again/

**Comment by vestingz** [comment]
I am not sure about the current status of that feature, but shouldn't this be easy to implement through incrond? The entry in incrontab would be something along the lines like this:

`<PATH_TO_MONITOR>  IN_CREATE,IN_DELETE,IN_MOVE,IN_NO_LOOP -c quodlibet --add-location=$@$# `
