### ISSUE TITLE
Simplify use of secondary browsers

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1046]
Original [issue 1046](https://code.google.com/p/quodlibet/issues/detail?id=1046) created by nick.boultbee on 2012-10-28T15:15:29.000Z:

Currently using secondary browsers is perhaps a lesser-known feature, which considering its power is a shame.

One problem is them living under Music-&gt;Browse Library-&gt;(Browser) whereas changing the primary browser is done from View-&gt;(Browser) - which seems to make more sense. Either way there is inconsistency here.

At the very least this could move menus, and be better documented / explained.

At the other extreme, tabbed browsers could be a contemporary (though not _necessarily_ appropriate) solution to this. Needs some thought.

**Comment by declension** [comment]
This is all done now really. Closing.
