### ISSUE TITLE
Reduce hidden options (right click menus)

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1047]
Original [issue 1047](https://code.google.com/p/quodlibet/issues/detail?id=1047) created by reiter.christoph on 2012-10-28T15:47:07.000Z:

We can think about moving some useful ones in the main menu or copy into the prefs to make them better accessible.

What is there:
- play button: stop after
- volume: relaygain
- song pos: bookmark management
- song info: current song actions, display pattern
- search browser: limit results

My suggestions:
- bookmark can be mirrored into controls (it's still nice to have it near the position)
- stop after can be moved to controls
- search browser: change to a prefs toggle button
- song info: maybe copy to prefs?
- current song actions: We could add a &quot;Current song&quot; menu to controls (moving tags, info into it.. but that adds one click)
- replaygain: I don't think it's much used... so leave it hidden.

**Comment by CreamyCookie** [comment]
Closing as these have been addressed or are mentioned in other issues. 

(Of course, feel free to reopen if I'm mistaken.)
