### ISSUE TITLE
Add plugin to tweak inaccessible config settings

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1050]
Original [issue 1050](https://code.google.com/p/quodlibet/issues/detail?id=1050) created by nick.boultbee on 2012-11-01T21:18:44.000Z:

After Issue #892, it seems a shame not to allow some common options to be selectable without manually editing config.

Some potentials to be included:
 ♪ (eighth note U+266A)
 ☆ (white star, U+2606)
 ★ (black star, U+2605)
 ✶ (six-pointed black star, U+2736)
 ♥ (black heart, U+2665)

**Comment by brunob** [comment]
I can give it a try, think it's a good way to try to make a plugin :)

What would be the list of settings to put in this ?

**Comment by lazka** [comment]
From a quick look into config.py the following aren't exposed: id3encoding, search_tags, disable_hints, rating_symbol_blank, rating_symbol_full, backend
