### ISSUE TITLE
QL user website

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1060]
Original [issue 1060](https://code.google.com/p/quodlibet/issues/detail?id=1060) created by nick.boultbee on 2012-11-16T23:18:54.000Z:

Most of the big open-source music players have their own websites aimed at users separate, or in addition to, their developer ones.

QL would benefit from this: to attract, retain, and help users, especially less technical ones.

Obviously hosting and domain names attract some problems of their owns, but they are not insurmountable, so gathering ideas and discussion here.

Some other examples:
http://banshee.fm/
http://www.exaile.org/
http://audacious-media-player.org/
http://clementine-player.org/
http://projects.gnome.org/rhythmbox/
http://www.xmms.org/

(also of course: http://www.apple.com/uk/itunes/)

**Comment by J5lx** [comment]
Now that QL moved to GitHub, maybe [GitHub Pages could be used with Jekyll](https://help.github.com/articles/using-jekyll-with-pages/) to create a basic Blog for it.

**Comment by declension** [comment]
Note that since I posted this the RTD site (https://quodlibet.readthedocs.org/en/latest/) has become the main source of documentation anyway, and fulfils quite a few (but not all) of the original criteria

**Comment by brunob** [comment]
So, we maybe we can close this issue ?

**Comment by lazka** [comment]
Sure, first a few questions though:

I did write some changelogs with images for the previous releases (maybe I do one for 3.4+5): https://lazka.github.io/posts/2014-07_ql32/index.html Are they useful and should these be linked from the QL page?

The screenshots are a bit out of date atm. Updating them regularly might increase the git repo size quite a bit, so maybe host them externally (on quodlibet.github.io for example)?

**Comment by brunob** [comment]
> Are they useful and should these be linked from the QL page?

Sure, it's always nice to show images to users.

> so maybe host them externally (on quodlibet.github.io for example)?

:+1:

**Comment by lazka** [comment]
I've updated the screenshots in git now, as it turned out they were also used in the user guide.
