### ISSUE TITLE
vcomment: Don't show non parsable rating tags

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1075]
Original [issue 1075](https://code.google.com/p/quodlibet/issues/detail?id=1075) created by reiter.christoph on 2012-12-04T20:43:08.000Z:

Example: rating:foobar=notanint

Will show and isn't changeable..

**Comment by bassstorm** [comment]
@lazka not reproducible on QL 4.4. File with invalid rating imported well, default rating displayed, I was able to set new rating and save it to file. Issue could be closed.

**Comment by bassstorm** [comment]
Same applies to OGG Audio files as well. Closing the ticket.
