### ISSUE TITLE
Add new browser: album grid showing album covers with title

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1101]
Original [issue 1101](https://code.google.com/p/quodlibet/issues/detail?id=1101) created by francesco.fumanti@gmx.net on 2013-01-12T12:29:38.000Z:

Hi, 

I am using quodlibet version 2.4 on Ubuntu and would like to ask you whether you could implement the following enhancement: 

The paned view has a pane showing the list of albums remaining available after a search. Could you please add an option to show the albums as a grid, where each cell shows the album cover/thumbnail with its title written below? 

You might have a look at the album pane of the following screenshot of banshee to get an idea of what I mean. Banshee also shows the name of the artist, but I don't think it to be necessary.
http://banshee.fm/theme/images/slides/scaled/music-450.png

Thanks in advance for looking at this request. 

Cheers

**Comment by brunob** [comment]
See #241 ;)

**Comment by nodiscc** [comment]
Duplicate or related to https://github.com/quodlibet/quodlibet/issues/241

**Comment by brunob** [comment]
This issue can be closed now ;)
