### ISSUE TITLE
APEv2 tag mapping incomplete

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1142]
Original [issue 1142](https://code.google.com/p/quodlibet/issues/detail?id=1142) created by reiter.christoph on 2013-04-14T23:48:11.000Z:

Many things are missing: http://wiki.musicbrainz.org/MusicBrainz_Picard/Tags/Mapping

Most important: disc &lt;-&gt; discnumber

**Comment by CreamyCookie** [comment]
Closing as old, disc mapping fixed and not enough info what else is missing / needed.
