### ISSUE TITLE
Ratings not written to APEv2 files

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1143]
Original [issue 1143](https://code.google.com/p/quodlibet/issues/detail?id=1143) created by BearcatSandor on 2013-04-15T00:41:23.000Z:

According to devleloper Christoph Reiter &quot;QL doesn't write rating tags for APEv2, but should for Ogg Vorbis if
enabled in the preferences.&quot;

See here for reference: https://groups.google.com/forum/?fromgroups=#!topic/quod-libet-development/CE1itBwPxjE

I would love for quodlibet to support writing ratings to APE files.  If no one picks it up after a month or two,
 i'll learn the programming language and do it myself.

**Comment by CreamyCookie** [comment]
Closing as very old and APEv2 has no mapping for ratings: https://picard-docs.musicbrainz.org/en/appendices/tag_mapping.html#id28 (and I think there's a issue somewhere about somehow storing ratings in custom tags)
