### ISSUE TITLE
Error during library refresh

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1157]
Original [issue 1157](https://code.google.com/p/quodlibet/issues/detail?id=1157) created by baldwin.elizabeth on 2013-05-13T14:16:35.000Z:

Had significantly updated my library after updating tags etc on a different computer, so wiped it on this computer and copied it over afresh.  Then opened quod libet and left the library to refresh.

It actually seems to be still working fine without a restart, but the dialogue told me to post the following:

=== SYSTEM INFORMATION:
Quod Libet 2.4
Mutagen 1.20
Python 2.7.3 (default, Sep 26 2012, 21:51:14) 
[GCC 4.7.2] linux2

=== STACK TRACE
Traceback (most recent call last):

  File &quot;/usr/lib/python2.7/dist-packages/quodlibet/library/songs.py&quot;, line 155, in __removed
    album.songs.remove(song)

KeyError: {'album': u'Run Lola Run', '~#bitrate': 128, 'artist': u'Run Lola Run', '~#length': 292, '~#added': 1362606552, '~filename': '/home/elizabeth/audio/music/indie_etc/run_lola_run/Potente &amp; Bleibtreu - Believe.mp3', '~#mtime': 1363555696.7557726, 'genre': u'Indie Etc', '~mountpoint': '/home/elizabeth', '~#filesize': 4673536}

=== LOG: u'Debug'
D: 310.70: SongFileLibrary._load: Loading '/home/elizabeth/audio/music/musicals/sondheim-sweeney_todd/07 Wait.mp3'.
D: 310.71: SongFileLibrary._load: Reloaded '/home/elizabeth/audio/music/musicals/sondheim-sweeney_todd/07 Wait.mp3'.
D: 310.72: SongFileLibrary._load: Loading '/home/elizabeth/audio/music/musicals/sondheim-sweeney_todd/08 Kiss Me.mp3'.
D: 310.72: SongFileLibrary._load: Reloaded '/home/elizabeth/audio/music/musicals/sondheim-sweeney_todd/08 Kiss Me.mp3'.
D: 310.75: SongFileLibrary._load: Loading '/home/elizabeth/audio/music/musicals/sondheim-sweeney_todd/09 Ladies In Their Sensitivities.mp3'.
D: 310.76: SongFileLibrary._load: Reloaded '/home/elizabeth/audio/music/musicals/sondheim-sweeney_todd/09 Ladies In Their Sensitivities.mp3'.
D: 310.78: SongFileLibrary._load: Loading '/home/elizabeth/audio/music/musicals/sondheim-sweeney_todd/10 Pretty Women.mp3'.
D: 310.79: SongFileLibrary._load: Reloaded '/home/elizabeth/audio/music/musicals/sondheim-sweeney_todd/10 Pretty Women.mp3'.
D: 310.80: SongFileLibrary._load: Loading '/home/elizabeth/audio/music/musicals/sondheim-sweeney_todd/11 Epiphany.mp3'.
D: 310.81: SongFileLibrary._load: Reloaded '/home/elizabeth/audio/music/musicals/sondheim-sweeney_todd/11 Epiphany.mp3'.
D: 310.83: SongFileLibrary._load: Loading '/home/elizabeth/audio/music/musicals/sondheim-sweeney_todd/12 A Little Priest.mp3'.
D: 310.84: SongFileLibrary._load: Reloaded '/home/elizabeth/audio/music/musicals/sondheim-sweeney_todd/12 A Little Priest.mp3'.
D: 310.88: SongFileLibrary._load: Loading &quot;/home/elizabeth/audio/music/musicals/sondheim-sweeney_todd/13 God, That's Good!.mp3&quot;.
D: 310.88: SongFileLibrary._load: Reloaded &quot;/home/elizabeth/audio/music/musicals/sondheim-sweeney_todd/13 God, That's Good!.mp3&quot;.
D: 310.89: SongFileLibrary._load: Loading '/home/elizabeth/audio/music/musicals/sondheim-sweeney_todd/14 Johanna (Reprise).mp3'.
D: 310.90: SongFileLibrary._load: Reloaded '/home/elizabeth/audio/music/musicals/sondheim-sweeney_todd/14 Johanna (Reprise).mp3'.
D: 310.92: SongFileLibrary._load: Loading '/home/elizabeth/audio/music/musicals/sondheim-sweeney_todd/15 By The Sea.mp3'.
D: 310.92: SongFileLibrary._load: Reloaded '/home/elizabeth/audio/music/musicals/sondheim-sweeney_todd/15 By The Sea.mp3'.
D: 310.95: SongFileLibrary._load: Loading &quot;/home/elizabeth/audio/music/musicals/sondheim-sweeney_todd/16 Not While I'm Around.mp3&quot;.
D: 310.95: SongFileLibrary._load: Reloaded &quot;/home/elizabeth/audio/music/musicals/sondheim-sweeney_todd/16 Not While I'm Around.mp3&quot;.
D: 310.98: SongFileLibrary._load: Loading '/home/elizabeth/audio/music/musicals/sondheim-sweeney_todd/17 Searching.mp3'.
D: 310.98: SongFileLibrary._load: Reloaded '/home/elizabeth/audio/music/musicals/sondheim-sweeney_todd/17 Searching.mp3'.
D: 310.99: SongFileLibrary._load: Loading &quot;/home/elizabeth/audio/music/musicals/sondheim-sweeney_todd/18 The Judge's Return.mp3&quot;.
D: 311.00: SongFileLibrary._load: Reloaded &quot;/home/elizabeth/audio/music/musicals/sondheim-sweeney_todd/18 The Judge's Return.mp3&quot;.
D: 311.03: SongFileLibrary._load: Loading '/home/elizabeth/audio/music/musicals/sondheim-sweeney_todd/19 Final Scene.mp3'.
D: 311.03: SongFileLibrary._load: Reloaded '/home/elizabeth/audio/music/musicals/sondheim-sweeney_todd/19 Final Scene.mp3'.
D: 311.06: SongFileLibrary._load: Loading '/home/elizabeth/audio/music/musicals/sondheim-sweeney_todd/20 The Ballad of Sweeney Todd.mp3'.
D: 311.06: SongFileLibrary._load: Reloaded '/home/elizabeth/audio/music/musicals/sondheim-sweeney_todd/20 The Ballad of Sweeney Todd.mp3'.
D: 311.09: SongFileLibrary._load: Loading '/home/elizabeth/audio/music/panic-joy/01 Bis - Eurodisco.mp3'.
D: 311.10: SongFileLibrary._load: Reloaded '/home/elizabeth/audio/music/panic-joy/01 Bis - Eurodisco.mp3'.
D: 311.13: SongFileLibrary._load: Loading '/home/elizabeth/audio/music/panic-joy/01 Catatonia - Mulder and Scully.mp3'.
D: 311.13: SongFileLibrary._load: Reloaded '/home/elizabeth/audio/music/panic-joy/01 Catatonia - Mulder and Scully.mp3'.
D: 311.14: SongFileLibrary._load: Loading '/home/elizabeth/audio/music/panic-joy/01 Hole - Celebrity Skin.mp3'.
D: 311.15: SongFileLibrary._load: Reloaded '/home/elizabeth/audio/music/panic-joy/01 Hole - Celebrity Skin.mp3'.
D: 311.16: SongFileLibrary._load: Loading '/home/elizabeth/audio/music/panic-joy/01 Joy Division - Love Will Tear Us Apart.ogg'.
D: 311.17: SongFileLibrary._load: Reloaded '/home/elizabeth/audio/music/panic-joy/01 Joy Division - Love Will Tear Us Apart.ogg'.
D: 311.19: SongFileLibrary._load: Loading '/home/elizabeth/audio/music/panic-joy/01 Pulp - Babies.ogg'.
D: 311.21: SongFileLibrary._load: Reloaded '/home/elizabeth/audio/music/panic-joy/01 Pulp - Babies.ogg'.
D: 311.23: SongFileLibrary._load: Loading '/home/elizabeth/audio/music/panic-joy/01-ladykillers.mp3'.
D: 311.24: SongFileLibrary._load: Reloaded '/home/elizabeth/audio/music/panic-joy/01-ladykillers.mp3'.
D: 311.25: SongFileLibrary._load: Loading '/home/elizabeth/audio/music/panic-joy/01_Hey_Porter.mp3'.
D: 311.26: SongFileLibrary._load: Reloaded '/home/elizabeth/audio/music/panic-joy/01_Hey_Porter.mp3'.
D: 311.28: SongFileLibrary._load: Loading '/home/elizabeth/audio/music/panic-joy/02 Blur - Song 2.mp3'.
D: 311.28: SongFileLibrary._load: Reloaded '/home/elizabeth/audio/music/panic-joy/02 Blur - Song 2.mp3'.
D: 311.29: SongFileLibrary._load: Loading '/home/elizabeth/audio/music/panic-joy/04 Idlewild - Roseability.mp3'.
D: 311.29: SongFileLibrary._load: Reloaded '/home/elizabeth/audio/music/panic-joy/04 Idlewild - Roseability.mp3'.
D: 311.29: SongFileLibrary._load: Loading '/home/elizabeth/audio/music/panic-joy/04 Supergrass - Alright.mp3'.
D: 311.29: SongFileLibrary._load: Ignoring (so removing) '/home/elizabeth/audio/music/panic-joy/04 Supergrass - Alright.mp3'.
D: 311.29: qltk.completion.__update_song: Updating tag model for 101 songs
D: 311.29: qltk.completion.__update_song: Done updating tag model for 101 songs

=== LOG: u'Warnings'
W: Couldn't connect to a device backend.
W: No device backend, Media Devices browser disabled.

**Comment by CreamyCookie** [comment]
Since this is 6 years old and there has been no new information (and it might already be fixed), I'm closing this one.
