### ISSUE TITLE
Windows: Impossible to use accents while typing OUTSIDE of Quod Libet

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1168]
Original [issue 1168](https://code.google.com/p/quodlibet/issues/detail?id=1168) created by unix.timestamp@gmx.com on 2013-05-26T10:21:17.000Z:

I ran into this problem and don't know if it's GTK related, it seems very weird: when QuodLibet is running (on Windows 7, I didn't check if it happened on Linux) stroking accents keys in any application produce immediatly a double accent, instead of letting type the letter that should take the accent.

To get &quot;ê&quot; I normally type &quot;^&quot; and then &quot;e&quot;, if I do so when QuodLibet is running I get: &quot;^^e&quot;

**Comment by tiangolo** [comment]
Hmm, sad not being able to use multimedia keys, but the workaround worked!

**Comment by obskyr** [comment]
I've been running into this problem a lot, and didn't realize it was Quod Libet for several months. Welp, that's a few months of copy-pasting accented characters wasted.

Is there no way to actually fix this? An alternative to pyHook, or a fix to pyHook, perhaps? Anything? Anything at all? :disappointed:

**Comment by lazka** [comment]
No idea how to fix this... any info on alternatives/fixes welcome.

**Comment by tiangolo** [comment]
Maybe PyHooked could work? https://github.com/IronManMark20/pyhooked

**Comment by lazka** [comment]
Interesting, thanks!

**Comment by Jerome-github** [comment]
This issue has been opened for one year in pyHook's bugtracker: http://sourceforge.net/p/pyhook/bugs/2/

From a quick look on Pypi, pyHooked seems much more "alive" than pyHook, so it could be a smart move. Not sure how much work this involves, though.

**Comment by lazka** [comment]
Fixed in master

**Comment by lazka** [comment]
If someone wants to test:

https://bitbucket.org/lazka/quodlibet/downloads/quodlibet-3.7.-1-rev8048-186f272-installer.exe
https://bitbucket.org/lazka/quodlibet/downloads/quodlibet-3.7.-1-rev8048-186f272-portable.exe

I've only tested with AutoHotkey emulating keys as I don't have multimedia keys on my keyboard.

**Comment by tiangolo** [comment]
Excellent @lazka. I just tested it. 
I have a laptop with multimedia keys. Actually it has a combination of the Fn key with F* keys (F8, F9, F10, etc) for play, pause, etc. The accents are working perfect, outside and even inside Quod Libet.
I'm using Windows 7 x64.

As example: áëîò. 

Thanks!

**Comment by lazka** [comment]
Thanks for testing!

**Comment by lafrech** [comment]
MM keys work and accents work. (Windows 7 x64 as well.)

Danke schön, @lazka.

**Comment by fmv1992** [comment]
I had the same issue.

Used your binaries above and it worked. Double accents are fixed.

Keep up the good work!
