### ISSUE TITLE
Conditional Tags in Album Collection

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1183]
Original [issue 1183](https://code.google.com/p/quodlibet/issues/detail?id=1183) created by Dies.Funus on 2013-06-19T16:27:47.000Z:

Currently the Album Collection view doesn't allow conditional tag, in my opinion this this would greatly improve the flexibility of this view and thus allow it to be a viable &quot;modern&quot; alternative to the paned view.

Thanks in advance.

**Comment by bassstorm** [comment]
I'm not quite sure what's meant here. If it is about Album Display, then conditional tags are supported.
Cc @lazka @CreamyCookie @declension

**Comment by bassstorm** [comment]
Closing as per above. Actual QL default setup of Album Browser display is based on conditional tags.

**Comment by CreamyCookie** [comment]
@bassstorm Yeah, closing this makes sense. I actually still don't understand what they wanted.

Maybe adding conditional tags here.. but why? :sweat_smile: 

![screenshot of Album Collection Pref](https://user-images.githubusercontent.com/3063858/116012090-baee1580-a628-11eb-8512-67ae791e5c7d.png)

**Comment by bassstorm** [comment]
@CreamyCookie well, it was 2013 when the ticket was submitted, QL was not alike :)
