### ISSUE TITLE
Versioned tag mapping

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1215]
Original [issue 1215](https://code.google.com/p/quodlibet/issues/detail?id=1215) created by reiter.christoph on 2013-07-10T13:57:45.000Z:

Related: Issue #1179, Issue #48

Problem:
- Changing the tag mapping changes the tags after a reload or results in mixed mappings with new files.
- Opening the TXXX namespace will delete all TXXX frames after tag editing.

Possible solution:
- Add a ~version field which contains an integer of the tag mapping version which was used to load the file.
- Somehow use it to fix the above :)

**Comment by CreamyCookie** [comment]
Closing this as duplicate of #1590.
