### ISSUE TITLE
Markup erroneously inserted into tag when editing multiple tag names

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1245]
Original [issue 1245](https://code.google.com/p/quodlibet/issues/detail?id=1245) created by  aurelien...@laposte.net on 2013-10-03T10:58:23.000Z:

As I didn't find this issue here, I report.

While selecting several tracks at once and clicking on &quot;edit tags&quot;, the tag edit panel displays. If a tag is not equally filled for all the tracks, there is an italic comment beside its value, such as &quot;missing in xxx songs&quot;. If I opt no to edit the value, but the name of the tag, this very comment becomes part of the value (for example, I get &quot;Paul Romero&lt;i&gt; (manquant dans 15 chansons)&lt;/i&gt;&quot; as artist name).

My version is 2.6.2.

**Comment by declension** [comment]
I think this is solved ages ago. Reopen if not
