### ISSUE TITLE
GUI locks up when starting to play a song while using Gajim Status Message plugin

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1251]
Original [issue 1251](https://code.google.com/p/quodlibet/issues/detail?id=1251) created by UnduTheGun on 2013-10-05T13:58:05.000Z:

<b>Please describe the problem thoroughly and accurately. If possible paste</b>
<b>the contents of the ~/.quodlibet Dump or MiniDump file associated with the</b>
<b>problem; otherwise, you must at a minimum report the version of Quod Libet</b>
<b>and the operating system you are using.</b>

<b>\- What did you try to do?</b>
Open Quod Libet, double-click a song to start playing it.

<b>\- What did you expect to happen?</b>
The song starts playing, the program's GUI doesn't lock so I can keep browsing songs, change volume, etc.

<b>\- What did happen instead?</b>
The song starts playing, but the GUI locks up for about 23 seconds.
- More info
  Not only Quod Libet locks up, but Gajim does too.

My guess is that it's something related with the way the two programs communicate. Maybe both programs lock up because they're both waiting for the other to send a message? A timeout would explain why both of them unlock after a given time.

I'm using gajim 0.15.4 and quod libet 3.0.2 with Audio device GStreamer (autoaudiosink), Mutagen: 1.22, GTK+: 3.8.4, PyGObject 3.8.3, GStreamer 1.0.10.0 and Python 3.3.2 in archlinux

**Comment by CreamyCookie** [comment]
Closing this one, as it's very old, no similar reports have been made and it sounds unrelated to QL.
