### ISSUE TITLE
Add tests for the new cover art infrastructure

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1278]
Original [issue 1278](https://code.google.com/p/quodlibet/issues/detail?id=1278) created by s@kazlauskas.me on 2013-11-03T09:53:35.000Z:

Add tests for the new cover art infrastructure and all utilities (http) that were created as a part of the project.

**Comment by lazka** [comment]
No update in years, so closing.

**Comment by declension** [comment]
I think I might have added a few around this a while back anyway
