### ISSUE TITLE
Make Album Art plugin use cover sources

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1279]
Original [issue 1279](https://code.google.com/p/quodlibet/issues/detail?id=1279) created by s@kazlauskas.me on 2013-11-03T10:35:22.000Z:

This is issue for mostly personal bookkeeping.

As Album Art plugin requires some search functionality, cover sources should make it possible to make a search instead of fetching cover outright. That could be solved by simple optional `search` function in each of cover sources.

Then all existing parsers in album art plugin should be ported to being CoverSource (currently Amazon, CoverParadise (ugh)) and create a new DiscoGS source.

Finally, PreferredSource (priority=1) could be implemented which would provide the covers chosen by the user through Album Art plugin. This one should be either built_in or bundled inside albumart.py.

**Comment by JoseBarakat** [comment]
Passing by just to remind including Discogs API as an option (better than Amazon) and changing the name of the plugin to "Cover Art Scrapper" or something more accurately.
 Can be started as a query (depending of the API docs) with filters, so more UI elements could be added in the future.

**Comment by knockoutMice** [comment]
I'm working on the Discogs cover source.

**Comment by knockoutMice** [comment]
#2136

**Comment by knockoutMice** [comment]
https://github.com/knockoutMice/quodlibet/blob/4ce8cd00cc897b54690467d0eafd369952a68b01/quodlibet/quodlibet/ext/songsmenu/albumart.py#L205

Ok, so the Album Art plugin now supports Discogs.

**Comment by JoseBarakat** [comment]
I'm haven't been able to test it yet on Quod Libet 3.8 (development, a05cfcb) in Ubuntu 16.10, and I'm seeing that pull #2136 is closed and merged.

Using "Album Art Downloader" plugin at the moment with results from Amazon.

![captura de pantalla de 2016-12-08 17-18-36](https://cloud.githubusercontent.com/assets/15618933/21030037/723c457e-bd6a-11e6-8bb4-3d9c12d25437.png)
![captura de pantalla de 2016-12-08 17-14-41](https://cloud.githubusercontent.com/assets/15618933/21029912/f1b4ba3a-bd69-11e6-9b75-59a1e487123b.png)
![captura de pantalla de 2016-12-08 17-06-54](https://cloud.githubusercontent.com/assets/15618933/21029925/ffecb1a2-bd69-11e6-9c31-de7e51efffb0.png)

**Comment by knockoutMice** [comment]
You should fetch the latest dev version, the merge happened 4 days ago.  https://github.com/quodlibet/quodlibet/commit/d74a5b694e38b4d5fc4a78cda4847041ec811207

**Comment by JoseBarakat** [comment]
@knockoutMice Thanks. Great idea, by the way!

**Comment by CreamyCookie** [comment]
@declension This was fixed with #2812, right? 

Please re-open if I'm mistaken.

**Comment by declension** [comment]
@CreamyCookie yes... sorry should have closed this ages ago I guess (good work on all the tickets BTW!)

**Comment by CreamyCookie** [comment]
> good work on all the tickets BTW!)


@declension Thanks a lot! :)
