### ISSUE TITLE
Tooltips for multiple selected tracks

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1297]
Original [issue 1297](https://code.google.com/p/quodlibet/issues/detail?id=1297) created by spxxxk on 2013-11-24T11:02:16.000Z:

Select track1 &amp; track2
Hover column1 of track1 or hover column 1 of track2
-&gt; Shows a tooltip with track1 AND track2 infos

Goal: Easier comparison of truncated tracks, beats having to hover one after the other.

Always display tooltip when hovering selected tracks even when tags aren't truncated. 
Goal: Easier comparison of tracks far from each others.

Limit number of lines of tooltip if number of tracks greater than X tracks.

Instead of tooltips: live info area on selected tracks, info window (similar to ctrl+i) that displays one tag per line..

**Comment by declension** [comment]
Could this be solved with a new widget that respons to _selection_ (not currently playing)? This is something I'm playing with at the momennt (as part of #940)

**Comment by spxxxk** [comment]
Definitely. You can close this one. Excited about #940 !

**Comment by CreamyCookie** [comment]
Closing this for #940.
