### ISSUE TITLE
Automatic Library Update plugin is broken

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1315]
Original [issue 1315](https://code.google.com/p/quodlibet/issues/detail?id=1315) created by nick.boultbee on 2013-12-28T21:34:38.000Z:

<b>- What did you try to do?</b>
Delete or move a file or folder in using latest QL on Ubuntu 13.10 with python-pyinotify and Automatic Library plugin enabled.

<b>- What did you expect to happen?</b>
Songlists instantaneously updated where appropriate, future results will not show deleted files, debug output happens, etc.

<b>- What did happen instead?</b>
Nothing at all.

**Comment by declension** [comment]
I've updated the [feature branch](https://github.com/quodlibet/quodlibet/tree/watched-library) with tye many, many merges from master.

Working roughly as before, including all the things that haven't been addressed from before. It'd be good to see if we can get a viable working version of this merged into master and the plugin withdrawn, even if it's hidden behind prefs.
