### ISSUE TITLE
Keep a cache of device content for as long as it is plugged in

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1316]
Original [issue 1316](https://code.google.com/p/quodlibet/issues/detail?id=1316) created by alex.fellows on 2014-01-04T16:00:15.000Z:

I've noticed that every time you copy files to a device QL scans the device/library so you have to wait for the scan for finish until it is able to copy the files across. This seems completely unnecessary, QL should scan the device once and keep the file list/tag information in a cache so it doesn't need to update it each time an operation is performed. 

It also seems to take an unusually long time to do an initial scan of a device as well, Clementine can do this almost instantaneously but QL takes several minutes for the first scan.

**Comment by declension** [comment]
Closing, device support gone.
