### ISSUE TITLE
Apostrophes, tilde (~) and hat (^) accents doubled

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1341]
Original [issue 1341](https://code.google.com/p/quodlibet/issues/detail?id=1341) created by CharlesOBlack on 2014-03-05T12:41:56.000Z:

Whenever Quod Libet is running, my accents all get displayed doubly.

This means that whenever I type apostrophe once, two of it get typed on whatever program I'm using.

I've tried disabling all plugins and the bug persists. I've also tried switching software keyboard layouts, and the accents get fixed when I do that.

Relevant information:

Quod Libet v. 2.6.3
Windows 7 Professional SP1
Software Keyboard United States-International

I'm not sure exactly what causes this. If I close Quod Libet, accents get back to normal; if I run the program again, accents go back to being doubled.

Any suggestions? I can also provide more info if required.

**Comment by kress95** [comment]
Just a note here: This bug still happens in the current version (3.6.1)

**Comment by lazka** [comment]
This will be fixed in the next release, see #1168
