### ISSUE TITLE
Support for remote interfaces on devices e.g. Android

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1377]
Original [issue 1377](https://code.google.com/p/quodlibet/issues/detail?id=1377) created by reiter.christoph on 2014-04-25T08:37:46.000Z:

Some other players provide a network interface and a corresponding Android app for remote control. We could re-implement (parts) of their interfaces in a plugin.

https://play.google.com/store/apps/details?id=org.nstamato.bansheeremote
https://play.google.com/store/apps/details?id=de.qspool.clementineremote
https://play.google.com/store/apps/details?id=org.peterbaldwin.client.android.vlcremote

We already have a the upnp + mpris plugins, which should in theory work as well if rygel is installed. Testing this and listing some working clients in the docs would be nice.

**Comment by nodiscc** [comment]
Hi @lazka , maybe this should be documented a bit more? A search for "control quodlibet from android" led me here but it was not obvious at first.

I can confirm that MPD server plugin + MPDroid works fine for me (play/pause/next/previous/shuffle/volume control/coverart). As mentioned there are a few limitations (the playlist only shows the current playing song, no library search, no support for ratings ... but I can live with these).

Should I send a patch for https://quodlibet.readthedocs.io/en/latest/guide/interacting.html#integration-with-third-party-tools ?
