### ISSUE TITLE
Settings label "Bayesian averaging amount:" not translated to German

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1379]
Original [issue 1379](https://code.google.com/p/quodlibet/issues/detail?id=1379) created by quassy7 on 2014-04-25T17:19:55.000Z:

Translation missing in the German version: In the settings (&quot;Einstellungen&quot;) screen, under tab tags (&quot;Tags&quot;), the string &quot;Bayesian averaging amount: [spin-field]&quot; is not translated to German.

Version: Quod Libet 3.1.0 for Windows, Portable
Language: German

**Comment by CreamyCookie** [comment]
This was implemented: https://github.com/quodlibet/quodlibet/blob/91a88efa844b91f6e4faf967ae1c6cd607717bd7/quodlibet/po/de.po#L5615
