### ISSUE TITLE
Quod Libet doesn't match FreeDesktop directories specs

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#138]
Original [issue 138](https://code.google.com/p/quodlibet/issues/detail?id=138) created by thibaut.bethune on 2009-02-24T23:52:29.000Z:

I've tried Quod Libet 2.0 on Ubuntu 9.04 alpha 4
and it seems that Quod Libet places its configuration files in
/home/.quodlibet directory which doesn't match FreeDesktop directories specs :

The default for $XDG_CONFIG_HOME is $HOME/.config, the default for
$XDG_DATA_HOME is $HOME/.local/share. So all applications should look for
those environment variables and use those default values if the variables
are not set.

This is quite important since it's not possible to easily backup config
&amp; data files if these files are not stored at the right place

See http://www.freedesktop.org/wiki/Specifications/basedir-spec
See also
http://ploum.frimouvy.org/?184-cleaning-user-preferences-keeping-user-data
(main post and comment#8)

**Comment by jrobeson** [comment]
seems like it should be like so:

covers: `$XDG_CACHE_DIR/quodlibet`
control: `$XDG_RUNTIME_DIR/quodlibet`
playlist: `$XDG_DATA_DIR/quodlibet`
lists: `$XDG_DATA_DIR/quodlibet`
config: `$XDG_CONFIG_DIR/quodlibet`

**Comment by jcrben** [comment]
Any movement around this? Would you be happy to take a pull request?

**Comment by lazka** [comment]
No.

I'm for simply moving "~/.quodlibet" to "~/.config/quodlibet" and adding a symlink.
And if possible do that as atomically as possible. We'd need similar functionality for osx, see #1950.

And for cache stuff we can just switch to "~/.cache/quodlibet" without migrating data; we already use that for some cover caching atm.

**Comment by jcrben** [comment]
I guess setting QUODLIBET_USERDIR functions as a workaround, right?

**Comment by lazka** [comment]
> I guess setting QUODLIBET_USERDIR functions as a workaround for now, right?

yeah

**Comment by ptitjes** [comment]
@jcrben Are you working on this ?

**Comment by jcrben** [comment]
No, not using quod libet right now

**Comment by Socialdarwinist** [comment]
Don’t have fixes in the Python standard library or elsewhere to be considered? For elucidation, [os.environ](https://docs.python.org/3/library/os.html#os.environ) does not support XDG directories, and as for additional libraries, there is just the abandonware pyxdg for Python 2. Right now, the access practice to the XDG variables is ugly, like [reading the specifying files directly or starting subprocesses of programs](https://stackoverflow.com/questions/13741873/how-to-get-users-desktop-path-in-python-independent-of-language-install-linux) that ought to be installed.

**Comment by lazka** [comment]
This was fixed by #2466

**Comment by mclark-newvistas** [comment]
This is _not_ fixed by #2466. While I appreciate taking `.quodlibet` out of `~`, I keep `.config` on a different filesystem which doesn't expect very many writes. Keeping state files in `.config` is not okay. Above you comment that some files - ie, thumbnails - are maybe more appropriate for `.cache` and maybe for `.local/var`. Either way they aren't appropriate for `.config`. If you must pick a single directory, I would rather lose my config file for quodlibet in a disaster than lose the storage for all of my config files due to the medium being used as a cache directory. Data classification matters.

**Comment by CreamyCookie** [comment]
This is now tracked in #2202.
