### ISSUE TITLE
Produce roadmap in documentation

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1397]
Original [issue 1397](https://code.google.com/p/quodlibet/issues/detail?id=1397) created by lstrout on 2014-05-08T03:05:51.000Z:

Do you guys have some sort of plan as to where QL is headed?  I recently came across QL in my search for something better and the one thing that it stumbles on for me is a feature request from 2010 that has gone no where since.

It would be nice to see what you plan on doing and some indication of when in order to kindle more interest.  For now it's back to a filesystem view of my collection regardless of which player I'm using.

**Comment by lazka** [comment]
Nothing came of this..

**Comment by declension** [comment]
Also, Github's release checklists are probably good enough anyway
