### ISSUE TITLE
ValueError: Pointer arguments are restricted to integers, capsules, and None

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1414]
Original [issue 1414](https://code.google.com/p/quodlibet/issues/detail?id=1414) created by reiter.christoph on 2014-06-09T20:31:05.000Z:

https://groups.google.com/forum/#!topic/quod-libet-development/4I9YbsV44UU

**Comment by CreamyCookie** [comment]
Could be wrong, but this seems very outdated. Closing for now.
