### ISSUE TITLE
Batch renaming year tag to date fails

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1419]
Original [issue 1419](https://code.google.com/p/quodlibet/issues/detail?id=1419) created by Batman.XX on 2014-07-05T22:02:56.000Z:

Problem:
Renaming the &quot;year&quot; tag to &quot;date&quot; on multiple selected tracks displays an error dialog complaining of invalid date format.  It appears to validating against the dummy string &quot;(different across X songs)&quot; rather than each song's value for that tag.

To reproduce:

Select multiple songs with &quot;year&quot; tags having different but valid (in YYYY format) values.

UI should show &quot;year     (different across X songs)&quot;

Double click &quot;year&quot;

Enter &quot;date&quot; and click outside of the box to execute the change

An error dialog appears saying:
&quot;Invalid value

Invalid value: (different across 16 songs)

The date must be entered in 'YYYY', 'YYYY-MM-DD' or 'YYYY-MM-DD HH:MM:SS' format.&quot;

**Comment by ohel** [comment]
This seems to be fixed in the latest master, issue should be closed.

**Comment by frestr** [comment]
Can confirm that this works now.
