### ISSUE TITLE
Jump to playing song should change playlists when possible

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1425]
Original [issue 1425](https://code.google.com/p/quodlibet/issues/detail?id=1425) created by solitaire@centurylink.net on 2014-07-15T04:19:09.000Z:

Quod Libet 3.0.2, Linux Mint 17

Problem two of three: (with 1424)

When playing a song in a playlist, if I click on a different playlist there is no indication which list has the current track, 'Jump to Playing Song' doesn't jump across playlists, and, when the track ends, control switches to the first track in the second playlist.

'Jump to Playing Song' should actually jump to playing song, regardless of which playlist it's on.

**Comment by declension** [comment]
:+1: 
This shouldn't be too hard I think

**Comment by declension** [comment]
Hmm, though of course it suffers from the same gotcha as #1424 and #1426 - the playing song can be in multiple playlists.

It could just select the first one, maybe, or it could just check there's only one occurrence (the majority of cases I suspect), in which case go there.

**Comment by declension** [comment]
Can this be closed now (thanks to @lazka  in 0f57b08a107c40c6b0493e1254b7b939dc8bdc06)?

**Comment by lazka** [comment]
Yeah, thanks. #1424 is still open for the indication part.. which I'm not sure about..
