### ISSUE TITLE
Forwarding within audiofeeds causes screen freeze

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1449]
Original [issue 1449](https://code.google.com/p/quodlibet/issues/detail?id=1449) created by sp4zzpp2 on 2014-08-19T08:49:16.000Z:

I tried to seek forward in an audiofeed.

It is clear, that the skipped part has to be downloaded before it could actually skip it. But instead, the screen simply froze (probably because the download takes too long and blocks any input)

I could move my mouse, but no GUI could handle button press events. 

QuodLibet 3.1.-1
Linux peter-Lenovo-G580 3.11.0-26-generic #45-Ubuntu SMP Tue Jul 15 04:02:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by declension** [comment]
No updates in > 7 years... closing
