### ISSUE TITLE
Add more plugin groups in Plugin Window

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1460]
Original [issue 1460](https://code.google.com/p/quodlibet/issues/detail?id=1460) created by engored on 2014-08-28T17:09:11.000Z:

Right now when browsing for plugins there's a combobox with only 3 choices: All, Enabled, Disabled. Supposedly it supports more plugin groups, but there aren't any.

It would be nice to see more choices there, such as Covers, Editing, Effects, Playlists, Play Order (pretty much all of those are taken from ls -l of quodlibet/ext/ directory).

**Comment by declension** [comment]
:+1:
