### ISSUE TITLE
Ratings are not stored in tags (tested with mp3 and FLAC)

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1461]
Original [issue 1461](https://code.google.com/p/quodlibet/issues/detail?id=1461) created by joschuaga@yahoo.de on 2014-08-30T14:19:07.000Z:

The plugin &quot;Force Write&quot; and &quot;saving rating and play count&quot; are enabled. I use &quot;Banshee&quot; as the email, because I hoped that I could get my old ratings (made by Banshee) this way, but it doesn't seem to work.

<b>- What did you try to do?</b>
I rated something and then checked with mutagenx if the tags for rating are correctly set.

<b>- What did you expect to happen?</b>
I expect it to set the rating tag.

<b>- What did happen instead?</b>
It didn't set the rating tag. (On one mp3 file the rating and the play count was set, but it was 0 instead of the expected 255, because I voted it 4 of 4 stars.)

<b>- Which version of Quod Libet?</b>
3.2.1

<b>- Which operating system including version (Ubuntu 14.04, Win7, Debian</b>
<b>sid)?</b>
Ubuntu 14.04 / 64bit

**Comment by pdesanex** [comment]
I'm having the same issue. QL doesn't store ratings / playcounts, neither in MP3s, nor in FLACs. My rating scale is set to 5, default rating to 0. The Email field is set to a non-standard address, but it doesn't seem to work with a proper email address either. Ratings / playcounts from banshee are displayed in the QL tag editor, but, as far as I remember, they are not picked up as such in QL.

**Comment by CreamyCookie** [comment]
@lazka In my original bug report I didn't realize that you have to execute Force Write on each song for which the ratings should be stored. If I use the plugin this way, the ratings seem to be stored.

So the question is: Is there a way to run a plugin whenever ratings or playcount change (I need both)? 

And slightly related: Can a plugin be executed whenever albums are added? I'd like to automatically add ReplayGain tags.

**Comment by CreamyCookie** [comment]
@lazka My question above still stands, but this bug report can be closed.

**Comment by declension** [comment]
> And slightly related: Can a plugin be executed whenever albums are added? I'd like to automatically add ReplayGain tags to any new albums.

@CreamyCookie we talked about this ages ago actually. Short version: currently: no, but it's definitely a feature I'd like (especially when combined with the work in the [watched-library branch](https://github.com/quodlibet/quodlibet/tree/watched-library]) (see #1315)

On further digging, see #275 for that exact use case.

**Comment by CreamyCookie** [comment]
Okay, this is weird. When I rate a song `0.5` = 2 stars, and then use the Force Write plugin on a FLAC file (haven't tried a mp3 yet), the rating isn't stored. However, as soon as I set it to any other rating, it's stored. Do you have any idea what is going here?

I really need to get the storing of ratings (and playcounts) sorted out, because they're one of the most important metadata for me. I use them for making playlists, which I then export to my USB stick.

**Comment by CreamyCookie** [comment]
@lazka What would it take to fix this bug?

Could I just replace:

    if rating != RATINGS.default:

with 

    if rating is not None:

**Comment by CreamyCookie** [comment]
Any feedback on this?

**Comment by lazka** [comment]
> Any feedback on this?

I've added some API in ca53d77b27d11b for this

**Comment by CreamyCookie** [comment]
@lazka 

Thanks!

I wonder, what's the purpose of the [Force Write plugin](https://github.com/quodlibet/quodlibet/blob/6bd54a9a081fecbf8d5ae0e910c66981739444ab/quodlibet/quodlibet/ext/songsmenu/forcewrite.py). All it does,  is to set `song._needs_write = True`. Shouldn't that happen automatically when "Save ratings and playcounts" is enabled (and playcount / rating have changed)?
