### ISSUE TITLE
Playback stops regularly just like that

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1466]
Original [issue 1466](https://code.google.com/p/quodlibet/issues/detail?id=1466) created by bubakpatrik on 2014-09-11T08:47:24.000Z:

As outlined above, I put songs to play in normal order, or random, doesn't matter and often the player pauses itself for no reason, then after a few minutes (sometimes) resumes playback.

<b>\- What did you try to do?</b>

Just resume playback.

<b>\- What did you expect to happen?</b>

After manually resuming playback all went well.

<b>\- Which version of Quod Libet?</b>

3.2.1-1

<b>\- Which operating system including version (Ubuntu 14.04, Win7, Debian</b>
<b>sid)?</b>

Win7 Ult. x64, but it happened to me also on Ubuntu.

**Comment by bassstorm** [comment]
Never personally experienced that on 4.x (I mean playing literally HOURS of music).

**Comment by declension** [comment]
Probably safe to close this ~7 year old issue then
