### ISSUE TITLE
Grouping albums should also consider the "album artist" tag or if it isn't set, the "artist" itself

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1474]
Original [issue 1474](https://code.google.com/p/quodlibet/issues/detail?id=1474) created by joschuaga@yahoo.de on 2014-09-26T20:56:40.000Z:

I have several albums with the name 'Mix' (they're not official), but each one of those albums has a different artist. Still, they're put together as a single album in the album view.

Here are some methods to get distinct albums: https://quodlibet.readthedocs.org/en/latest/guide/browse/album.html

I wonder though, shouldn't the &quot;album artist&quot; also be something that distinguishes albums (with same names)? And if the &quot;album artist&quot; tag isn't set, the &quot;artist&quot; tag itself. This tag also seems to be widely supported by other applications.

**Comment by ambergrant** [comment]
My 2 cents... I have one "Greatest Hits" album (QL 3.8.1) which contains the Greatest Hits albums of 11 artists. There's got to be a better way to manage this. I suggest looking at the physical directory in which the music files are stored. It's a good indicator that the songs are indeed part of separate albums.

**Comment by pschwede** [comment]
I know, there's an internal albumartistsort tag. Browsers should use that one in general.. no?

**Comment by ambergrant** [comment]
sorry, I don't understand your comment. But it's more important that the developers involved understand so I give way... all I ask is to solve the bug since from a user's standpoint it's super annoying. cheers.

**Comment by ambergrant** [comment]
I see now that this issue has already been addressed by the tags album_grouping_key, labelid, and musicbrainz_albumid. Yet I still argue that it's not obvious to a new user (me!) that this is how to fix it, and it is annoying to have to edit the tags of the music files. Ah, well.

**Comment by lazka** [comment]
@ambergrant see #2193 for a proposed improvement.

**Comment by bassstorm** [comment]
> I suggest looking at the physical directory in which the music files are stored. It's a good indicator that the songs are indeed part of separate albums.

That's not always true. Some people don't care about folders, but just download tracks from random places to single folder. So folder distinction would still be not enough for other "lazy" users.
IMO, the original problem statement appears resolved. And #2193 adds much sense on how to improve further.

**Comment by bassstorm** [comment]
Close as original issue is fixed a while ago.
