### ISSUE TITLE
Needed features for covergrid

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1489]
Original [issue 1489](https://code.google.com/p/quodlibet/issues/detail?id=1489) created by reiter.christoph on 2014-11-10T15:10:25.000Z:

status quo: http://f.666kb.com/i/cteyx5pzo7vnvpaxd.png
- [ ] We currently request thumbnail size so it fits in a boundary. So we can will the tiles we need to request by min(width, height).
- [x] Thumbnails loading happens in the main loop, gdk-pixbuf is thread safe since some time. We should use a threadpool for this (with cancelable tasks ideally).
- [x] Size should be variable, so we need a central LRU pixbuf cache and not cache them in the album.

**Comment by lazka** [comment]
Threaded loading is implemented since 3.4

**Comment by brunob** [comment]
Small hint @lazka you should use tasks list in the first comment, like that : 

- [x] @mentions, #refs, [links](), **formatting**, and <del>tags</del> supported
- [x] list syntax required (any unordered or ordered list supported)
- [x] this is a complete item
- [ ] this is an incomplete item

https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown

**Comment by CreamyCookie** [comment]
>  We currently request thumbnail size so it fits in a boundary. So we can will the tiles we need to request by min(width, height).

I'm not quite sure what this means, but is this still open?

**Comment by declension** [comment]
Yep think we can close this with #4101  etc
