### ISSUE TITLE
Allow (numeric) tags in RHS of numeric binary operator expressions

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1492]
Original [issue 1492](https://code.google.com/p/quodlibet/issues/detail?id=1492) created by joshua@paddle.com on 2014-11-14T08:08:45.000Z:

My request: Allow comparison operators to apply between two numeric fields.

For example: #(skipcount &lt; playcount)

My reasoning:
I have a lot of music, some songs of which I like more than others. Usually I just leave it on random play, with the result that I hit the &quot;skip&quot; key a couple of times an hour. I recently looked at the stats, and discovered that there some songs I usually skip, and am rarely in the mood for. Rather than trying to manually categorize my music into &quot;songs I always like&quot; and &quot;songs I rarely want to hear&quot;, it would be simpler if I could just filter them by whether I skip them more often than I play them.

So I was astonished to discover that although I can filter by e.g. #(playcount &gt; 10), I can't filter by #(playcount &gt; skipcount). It would make a lot more sense to allow any number in a comparison to be substituted by a numeric attribute.

**Comment by CreamyCookie** [comment]
This was implemented with #1799. (I just tested `#(skipcount < playcount)` and it works.)
