### ISSUE TITLE
Enable MPRIS plugin by default if running under unity

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1493]
Original [issue 1493](https://code.google.com/p/quodlibet/issues/detail?id=1493) created by dseaward925 on 2014-11-14T12:12:51.000Z:

Would it be possible to offer (via a plugin?) support for the Unity sound indicator. This would provide unobtrusive access to play/pause/prev/next commands.

These functions are already available via the Unity launcher, so this is definitely an optional enhancement. Some media players (frex, Rhythmbox, VLC) provide the sound indicator interface as an alternative. Specifically, when you &quot;close&quot; the main application window it disappears from the launcher, but the application remains running, and is accessible from the sound indicator.

I believe this means using the https://launchpad.net/libunity library.

**Comment by david-libremone** [comment]
@lazka Suggest closing this since Unity no longer exists.

**Comment by lazka** [comment]
thanks
