### ISSUE TITLE
Support reading RG when ID3 tag key is in uppercase

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1502]
Original [issue 1502](https://code.google.com/p/quodlibet/issues/detail?id=1502) created by li.davidm96 on 2014-12-12T17:21:02.000Z:

Quodlibet only reads the gain if the key is in lowercase. However, the spec (http://wiki.hydrogenaud.io/index.php?title=ReplayGain_2.0_specification#ID3v2) as well as programs like R128gain write the tag with the key in uppercase.

The attached patch makes Quodlibet check both forms.

**Comment by lidavidm** [comment]
Hey, just wanted to follow up on this bug report. I can update the aforementioned patch for the latest version of QL.

* What did you try to do?

Add music to the library that had been tagged by [r128gain](http://r128gain.sourceforge.net/) (now [bs1770gain](http://bs1770gain.sourceforge.net/))

* What did you expect to happen?

QuodLibet would read the ReplayGain2-compatible tags and apply the gain.

* What did happen instead?

The tags were ignored.

* Which version of Quod Libet?

3.4.1

* Which operating system including version (Ubuntu 14.04, Win7, Debian sid, ...)?

Arch Linux (rolling)
