### ISSUE TITLE
Add default accels for browsers/views

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1540]
Original [issue 1540](https://code.google.com/p/quodlibet/issues/detail?id=1540) created by marcelpaulo on 2015-02-16T12:24:46.000Z:

Even though my XFCE environment is configured to allow editable accelerators (see screenshot attached), QL is not allowing me to change them via GUI. In order to change them, I stop QL and edit ~/.quodlibet/accels directly.

I could change menu accelerators on xfce4-terminal, for instance, so the mechanism itself seems to be working.

I can't remember what was the last QL version that allowed this, but I do recall I could change them in the past.

I'm running QL version 3.3.1-0~ppa0~utopic over stock Xubuntu 14.10.

**Comment by CreamyCookie** [comment]
Hmm, I can't really get this to work. I've added these to the `accels` file:

```
(gtk_accel_path "/QuodLibetWindowActions/ViewAlbumList" "F9")
(gtk_accel_path "/QuodLibetWindowActions/ViewInternetRadio" "F10")
(gtk_accel_path "/QuodLibetWindowActions/ViewPlaylistsBrowser" "F11")
```
or this
```
(gtk_accel_path "<Actions>/QuodLibetWindowActions/ViewAlbumList" "<Primary><Shift>6")
(gtk_accel_path "<Actions>/QuodLibetWindowActions/ViewInternetRadio" "<Primary><Shift>7")
(gtk_accel_path "<Actions>/QuodLibetWindowActions/ViewPlaylistsBrowser" "<Primary><Shift>8")
```

But neither seems to work.

**Comment by CreamyCookie** [comment]
@lazka Thanks for the change! Could we keep some way to rate via keyboard shortcuts though?

As long as one could set their own Keyboard shortcuts, there doesn't even have to be a default. I, for example, would like something like the following (which I'd prefer over the current setting, as this follows the order of the keys):

Action | Keyboard shortcut
:--- | ---
| Rate 0 stars | <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>1</kbd> |
| Rate 1 stars | <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>2</kbd> |
| ... | ... |
| Rate 4 stars | <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>4</kbd> |

If no line in the songlist is selected, it would be great if QL rated the currently playing song.
