### ISSUE TITLE
"Prefer embedded art" doesn't work

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1544]
Original [issue 1544](https://code.google.com/p/quodlibet/issues/detail?id=1544) created by elBoulangero on 2015-02-18T15:54:20.000Z:

<b>Please describe the problem thoroughly and accurately. If possible paste</b>
<b>the contents of the ~/.quodlibet Dump or MiniDump file associated with the</b>
<b>problem.</b>

<b>\- What did you try to do?</b>
Take an audio file which contains embedded cover art.
Checked the preference &quot;Browsers -&gt; Album Art -&gt; Prefer embedded art&quot; in Quodlibet.
Paste a random picture in the same directory, with name folder.jpg for example.

<b>\- What did you expect to happen?</b>
See the cover embedded in the audio file

<b>\- What did happen instead?</b>
I see the picture from the file &quot;folder.jpg&quot;

<b>\- Which version of Quod Libet?</b>
Mercurial

<b>\- Which operating system including version (Ubuntu 14.04, Win7, Debian</b>
<b>sid, ...)?</b>

**Comment by declension** [comment]
I can confirm this bug is still happening
