### ISSUE TITLE
OSX: .m4a files will not play

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1550]
Original [issue 1550](https://code.google.com/p/quodlibet/issues/detail?id=1550) created by team@turnkeypropertyinvestment.com on 2015-02-22T23:57:12.000Z:

<b>Please describe the problem thoroughly and accurately. If possible paste</b>
<b>the contents of the ~/.quodlibet Dump or MiniDump file associated with the</b>
<b>problem.</b>

- What did you try to do? Installed latest quodlibet to try and get .m4a to play.  I am not a tech so asked on  forums about how to check if gstreamer plugins were installed. i was told to install latest quodlibet should fix it.

<b>- What did you expect to happen?</b>
Expected it to play .m4a files

<b>- What did happen instead?</b>
Error No GStreamer element found to handle media format. Media format: MPEG-4 AAC decoder.

<b>- Which version of Quod Libet?</b>
3.31

<b>- Which operating system including version (Ubuntu 14.04, Win7, Debian</b>
<b>sid, ...)?</b>
osx 10.9.5

**Comment by lazka** [comment]
See https://github.com/elelay/quodlibet-osx-bundle/issues/11

**Comment by MikeiLL** [comment]
I''m using the binary bundle Quod Libet Version 3.2.2 on OS X Mavericks (10.9.5) and also getting this issue. Audio device.

GStreamer (autoaudiosink) 
Mutagen: 1.25
GTK+: 3.14.0
PyGObject: 3.14.0
GStreamer: 1.4.3.0

Looked at the link above, but not seeing a fix.

**Comment by lazka** [comment]
It will be in the 3.4 bundle, which according to elelay [0] should be available end of this week.

[0] https://github.com/elelay/quodlibet-osx-bundle/issues/16#issuecomment-96766455

**Comment by MikeiLL** [comment]
wonderful! And I see that this can be downloaded from https://quodlibet.readthedocs.org/en/latest/downloads.html, correct? 

Also - I hope you don't mind me spamming the issue, but I tried to install after cloning the git repo using setup.py, but seem to be missing dependencies. The would either need to be compiled from source or installed via a package manager like pip for the python packages (Mutagen) and fink, macports or homebrew on OSX or apt-get on Debian, for the non python ones, correct?

**Comment by lazka** [comment]
New builds are up: https://quodlibet.readthedocs.org/en/latest/downloads.html#macosx

For building see https://github.com/elelay/quodlibet-osx-bundle

**Comment by elelay** [comment]
Hey @lazka, sorry but I botched the 3.4.0_0 release (everything was updated except quodlibet, still at 3.3.1) . Please update the links to 3.4.0_1

**Comment by MikeiLL** [comment]
Thank you!
