### ISSUE TITLE
DnD is broken at startup until browser is changed for some setups

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1551]
Original [issue 1551](https://code.google.com/p/quodlibet/issues/detail?id=1551) created by joshua@paddle.com on 2015-02-24T10:27:40.000Z:

Currently, if I add a bunch of songs to the play queue and then realize I want then in a different order, the only way I can change it is by removing them all and adding them again, which is a real pain. It would be much better if it was possible to move songs up and down the queue.

**Comment by CreamyCookie** [comment]
I'm closing this, since it's over 4 years old, seems to work fine (even without browser change) and I'm not aware of any similar reports.
