### ISSUE TITLE
quodlibet jumps to the wrong song

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1553]
Original [issue 1553](https://code.google.com/p/quodlibet/issues/detail?id=1553) created by kreykrey on 2015-03-07T14:36:27.000Z:

When I hit the prev or next buttons, usually the browser will jump (shuffle is on) to the song currently playing. However, sometimes (say 10-20% of the time) it will jump to the wrong position in the library.

How can I provide more info on this bug?

**Comment by krey** [comment]
It's not an issue of updating the window.

I did some further testing:
I narrowed my library down to a folder of 38 songs. To force jumping, I shortened the window down where it could only display 4-5 songs.
Based on my testing, most jumps are correct, but jumping to/from one particular song "Chameleon" is when mistakes occur.

**Comment by krey** [comment]
Please advise me on how I can provide more information on this issue.

**Comment by lazka** [comment]
Sorry for not responding earlier.

Is this still a problem?

**Comment by krey** [comment]
Hey, I think it was actually an issue with GTK, and it stopped happening.

**Comment by lazka** [comment]
Cool, thanks.
