### ISSUE TITLE
Moving away from google code

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1557]
Original [issue 1557](https://code.google.com/p/quodlibet/issues/detail?id=1557) created by reiter.christoph on 2015-03-13T14:41:12.000Z:

The preliminary plan:

* Wait until the github exporter works again and give it a try
* From a manual hg to git conversion the following issues need to be considered:

 * The git repo is 100 MB vs hg 35 MB. Figure out why?
 * Try to convert the &quot;issue #42&quot; in commit messages to &quot;issue #42&quot; or something github recognizes.
 * tags didn't get transfered, reapply them if needed
 * while we are at it maybe change the naming of release tags from quodlibet-X.Y.Z to something like release-X.Y.Z so there is no confusion with branches. (branches get used on readthedocs, so changing them would break links in older QL releases)
 * Delete merged branches?

github org: https://github.com/quod-libet
git repo test: https://github.com/quod-libet/test

**Comment by towolf** [comment]
Nice that they automated it. Back when we moved our project from GC to GH we had to cobble it together.

Also, shame about the stale taken username quodlibet/quodlibet would’ve been better.

**Comment by lkraider** [comment]
Hi, I asked Github and they freed the quodlibet name. I registered it just to reserve the name, but will transfer to @lazka to be used for the community.

**Comment by towolf** [comment]
Cool. Dunno about you, but I would move while it’s not settled down.

**Comment by lazka** [comment]
Thanks @lkraider, moved :)

**Comment by lazka** [comment]
Bitbucket mirror/downloads, readthedocs, ppa builds, drone.io and the buildbot server should work as before now and the documentation is updated, so I think we are done here.

@towolf there was still a bit of manual work needed for transferring (replacing commit hashes, making github issue references work, make sure the issue numbers align, request an exception from the github spam filter..), but yeah, the transfer tools provided by google are much better from what was available before.
