### ISSUE TITLE
Add "comment" field to information window.

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1558]
Original [issue 1558](https://code.google.com/p/quodlibet/issues/detail?id=1558) created by hehn@phys.ethz.ch on 2015-03-13T22:19:47.000Z:

In the information window of a single song I would like to have a display showing the content of the &quot;comment&quot; tag of the file.
In many podcasts the comment field contains useful information about its content and I am missing a convenient way of accessing this field.

I wrote a tiny patch which would add this feature to the information window. I would be very happy if you considered applying the patch or adding this feature in another way.

**Comment by declension** [comment]
Related #1068 (also #940 in a way)
