### ISSUE TITLE
AttributeError: 'MPDServerPlugin' object has no attribute '_server'

### ISSUE THREAD

**Issue by janot** [quodlibet/quodlibet#1559]
Error probably occurred shortly after I've changed "port" setting in MPDServerPlugin. 
Plugin wasn't enabled before or after changing this setting.

=== SYSTEM INFORMATION:
Quod Libet 3.3.1
Mutagen 1.27
Python 2.7.8 (default, Oct 20 2014, 15:05:19) 
[GCC 4.9.1] linux2
Platform Linux-3.19.0-031900-generic-x86_64-with-Ubuntu-14.10-utopic

=== STACK TRACE
Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/quodlibet/ext/events/mpdserver/__init__.py", line 95, in port_activate
    self._refresh()

  File "/usr/lib/python2.7/dist-packages/quodlibet/ext/events/mpdserver/__init__.py", line 147, in _refresh
    if self._server:

AttributeError: 'MPDServerPlugin' object has no attribute '_server'

=== LOG: 'Debug'
D: 221.86: QLScrobbler.enabled: Plugin enabled - accepting new songs.
D: 221.86: PluginManager.enable: Enable 'mediaserver'
D: 221.87: AlbumLibrary.__init__: Initializing Album Library to watch 'main'
D: 224.68: PluginManager.enable: Enable 'mpris'
D: 224.68: PluginManager.enable: Enable 'Animated On-Screen Display'
D: 224.68: AnimOsd.__init__: Error parsing config for text (could not convert string to float: (0.9,) - defaulting to (0.9, 0.9, 0.9, 0.0)
D: 224.68: AnimOsd.__init__: Error parsing config for fill (could not convert string to float: (0.25,) - defaulting to (0.25, 0.25, 0.25, 0.5)
D: 224.68: AnimOsd.__init__: Error parsing config for bcolor (could not convert string to float: (0.0,) - defaulting to (0.0, 0.0, 0.0, 0.2)
D: 224.69: mmkeys.find_active_backend: Trying to find a mmkeys backend
D: 224.69: mmkeys.find_active_backend: Found 'GnomeBackend'
D: 224.70: qltk.session.init: Connected with gnome session manager: /org/gnome/SessionManager/Client15
D: 224.70: CoPool.add: Added copool function <function periodic_config_save at 0x7fa80089de60> with id <function periodic_config_save at 0x7fa80089de60>
D: 224.70: CoPool.add: Added copool function <function periodic_library_save at 0x7fa80089ded8> with id <function periodic_library_save at 0x7fa80089ded8>
D: 224.70: quodlibet.main: Entering quodlibet.main
D: 224.75: quodlibet._override_exceptions: Enabling custom exception handler.
D: 230.87: PlaylistModel.set: Clearing model.
D: 230.87: PlaylistModel.set: Setting 71326 songs.
D: 231.69: PlaylistModel.set: Done filling model.
D: 231.71: GStreamerPlayer.go_to: Going to '/mnt/TOSHIBA/_music/The Cranberries/The Cranberries/1994 - No Need To Arque/04. Zombie.mp3'
D: 231.71: PlaylistMux.go_to: Told to go to '/mnt/TOSHIBA/_music/The Cranberries/The Cranberries/1994 - No Need To Arque/04. Zombie.mp3'
D: 231.71: QueueModel.go_to: Told to go to None
D: 231.71: PlaylistModel.go_to: Told to go to '/mnt/TOSHIBA/_music/The Cranberries/The Cranberries/1994 - No Need To Arque/04. Zombie.mp3'
D: 232.01: GStreamerPlayer._end: End song
D: 232.09: util.cover.manager.failure: Didn't get cover from FilesystemCover: This source is incapable of fetching covers
D: 232.09: util.cover.manager.failure: Didn't get cover from EmbedCover: This source is incapable of fetching covers
D: 232.12: GStreamerPlayer._end: Next song
D: 232.31: SongFileLibrary._changed: Changing 1 items.
D: 232.32: library.libraries.__changed: Updating affected albums for 1 items
D: 237.94: QLSubmitQueue.send_handshake: Sending handshake to service.
D: 238.26: QLSubmitQueue.send_handshake: Handshake status: OK
D: 238.26: QLSubmitQueue.send_handshake: Session ID: 379bf8e80f8140388024debb9fbb7db9, NP URL: http://post.audioscrobbler.com:80/np_1.2, Submit URL: http://post2.audioscrobbler.com:80/protocol_1.2
D: 238.26: QLSubmitQueue.send_nowplaying: Now playing song: The Cranberries - Zombie
D: 238.59: QLSubmitQueue._check_submit: Submission status: OK
D: 524.70: config.save: Writing config...
D: 524.71: library.save: Saving all libraries...
D: 524.71: SongFileLibrary.save: Saving contents to '/home/janot/.quodlibet/songs'.
D: 543.26: player.gstbe.player.__about_to_finish: About to finish
D: 543.26: player.gstbe.player.change_in_main_loop: Select next song in mainloop..
D: 543.29: player.gstbe.player.change_in_main_loop: ..done.
D: 544.31: player.gstbe.player.__message: Stream changed
D: 544.31: GStreamerPlayer._end: End song
D: 544.31: QLScrobbler.plugin_on_song_ended: Checking against filter 
D: 544.31: QLSubmitQueue.send_submission: Submitting song(s): The Cranberries - Zombie
D: 544.31: util.cover.manager.run: Found local cover from FilesystemCover
D: 544.37: GStreamerPlayer._end: Next song
D: 544.43: SongFileLibrary._changed: Changing 2 items.
D: 544.43: library.libraries.__changed: Updating affected albums for 2 items
D: 546.02: QLSubmitQueue._check_submit: Submission status: OK
D: 546.02: QLSubmitQueue.send_nowplaying: Now playing song: Ladytron - Tender Talons
D: 547.03: QLSubmitQueue._check_submit: Submission status: OK

**Comment by lazka** [comment]
Thanks
