### ISSUE TITLE
Moving a song to the top of the queue, doesn't change which song is played next 

### ISSUE THREAD

**Issue by CreamyCookie** [quodlibet/quodlibet#1560]
**What did you try to do?**
I moved another song to the top of the play queue.

**What did you expect to happen?**
I expected Quod Libet to play the new first, uppermost item.

**What did happen instead?**
It did play what was previously the first, uppermost item.

**Which version of Quod Libet?**
3.3.1

**Which operating system including version (Ubuntu 14.04, Win7, Debian sid, ...)?**
Ubuntu 14.04 / 64bit

**Comment by lazka** [comment]
Thanks. This was recently fixed and will be part of 3.4. See issue #1496
