### ISSUE TITLE
Album key: prioritze IDs before albumartist

### ISSUE THREAD

**Issue by ghost** [quodlibet/quodlibet#1561]
There used to be more options for sorting the album list, I believe a custom sort was there. Why on earth was this removed? I depended on "ArtistSort" for this heavily!  Or was it a plugin or something? I cannot remember ... is there a way around this, perhaps by editing `~/.quodlibet/config` ?

**Comment by lazka** [comment]
I don't remember any changes in that area. There is a feature request for custom sort orders, see issue #1486

Which sort order do you want? Maybe it's a new bug..

**Comment by tkelley65** [comment]
Well, my memory could be faulty, and keep in mind I went from 2.8 -> 3.3.

Tim Kelley

**Comment by tkelley65** [comment]
I think I see what happened; it seems QL is splitting albums on "albumartist" - was that the case before? I think I'd have noticed, since many of my CD's have several artists. I just tested and it was splitting an album on that. I'm wondering what the reason is. The performer doesn't have a lot to do with the album itself, technically. This is pretty common in all types of music.

**Comment by lazka** [comment]
Yes, this was changed with 3.1. See issue #1214

**Comment by tkelley65** [comment]
I don't understand splitting on anything but <labelid>, or
<organization>+<labelid>; everything else is just a guess. Albumartist was
the only available tag (without resorting to a custom one, which I at least
try to avoid) that could be used in the pane browser to show a particular
artist for a particular track or grouping on an album ... I can easily move
it all to a different tag, though.

Tim Kelley

**Comment by tkelley65** [comment]
What if <labelid> were to override any other splitting? I think that would be a nice solution. Probably not that many people use it ... Is anyone willing to accept this as a feature request?

**Comment by lazka** [comment]
> What if labelid were to override any other splitting? I think that would be a nice solution. Probably not that many people use it ... Is anyone willing to accept this as a feature request?

Sounds good afaics
