### ISSUE TITLE
Making searching more flexible: display results from all tags and file/pathname by default

### ISSUE THREAD

**Issue by Negirno** [quodlibet/quodlibet#1563]
When typing in the search bar without anything special it's limited to a few basic tags, for example Artist, Album Artist. If one wants to search based on less used or custom tags, one has to type `'tagname='` first, which is good when you explicitly want to narrow down to that tag, but most of the time it's inconvenient for those who just want to type ordinary text and want results based on their custom tags, too.

Also, it would be also good if one can narrow displayed results based on file names or folder path (like d:\music\pop), which comes handy with untagged files (Of course, QL can't display those, but that's another issue).

**Comment by declension** [comment]
The freetext search is not actually limited to a few basic tags: whilst fundamentally [a QL query defaults to searching `album`, `artist` and `title`](https://github.com/quodlibet/quodlibet/blob/master/quodlibet/quodlibet/query/_query.py#L23), in the application itself, queries are based on your songlist's visible columns, so if you're displaying the tags, you can free-text search them.

Thus you can search any of these if they're visible, and I've always found this reasonable UI behaviour. If you want to propose an alternative that works in the general case, please do (but it wouldn't be an easy change, and would probably affect performance). A potential compromise, though, would be a preferences entry that allows a set of tags to always be added to (_unioned with_, really) the current set that are searched.

To your second issue, you can already narrow searches by `~filename` or `~dirname`:
`&(~dirname="d:/music/pop/", artist=Rihanna)`

See the [internal tag documentation](https://quodlibet.readthedocs.org/en/latest/guide/tags/internal_tags.html#internaltags) for more details.

**Comment by Negirno** [comment]
I've put my custom tags in the playing column, and the free text search became much better. It works even with filenames and directories, too. Thanks.

**Comment by declension** [comment]
Closing
