### ISSUE TITLE
When clicking on a song right after another one finished, the following (wrong) song is played, but the one clicked on is displayed

### ISSUE THREAD

**Issue by CreamyCookie** [quodlibet/quodlibet#1566]
**What did you try to do?**
I clicked on another title while the current song had just finished.

**What did you expect to happen?**
I expected Quod Libet to play the song on which I had just clicked.

**What did happen instead?**
Instead, the song following the current song was played, while the song information (and lyrics via the lyrics window plugin) of the song I had clicked on, was displayed.

*Example*: Song 3 had just finished. In that moment I click on song 1. Song 4 is played, but the title of song 1 is displayed.

**Which version of Quod Libet?**
3.3.1

**Which operating system including version (Ubuntu 14.04, Win7, Debian sid, ...)?**
Ubuntu 14.04 / 64bit

**Comment by lazka** [comment]
See issue #837

**Comment by CreamyCookie** [comment]
@lazka Sorry, didn't found that bug when searching.
