### ISSUE TITLE
Process running, but no UI

### ISSUE THREAD

**Issue by PhilHudson** [quodlibet/quodlibet#1571]
When creating a new issue please try to answer the following questions:

    What did you try to do?

Launch Quodlibet from the MATE system menu, Sound & Video category

    What did you expect to happen?

Quodlibet to display its window, maximized as per previous use.

    What did happen instead?

Nothing. ```pgrep -l quod``` shows a running quodlibet process.

Choosing the same menu item again causes some strange flicker across all open windows and then a strange QL window appears, less than half the screen width and most but not all of the screen height, with a solid blank background, and none of the expected panels and music listings.

    Which version of Quod Libet?

Quod Libet 3.3.-1
<quod-libet-development@googlegroups.com>
Copyright © 2004-2015 Joe Wreschnig, Michael Urman, Iñigo Serna, Steven Robertson, Christoph Reiter, Nick Boultbee...

    Which operating system including version (Ubuntu 14.04, Win7, Debian sid, ...)?

Linux Mint Debian Edition running the MATE desktop environment
Linux lily 3.11-2-amd64 #1 SMP Debian 3.11.8-1 (2013-11-13) x86_64 GNU/Linux

**Comment by lazka** [comment]
Does this happen every time?

**Comment by PhilHudson** [comment]
On Tue, 07 Apr 2015 at  4:04:21 pm BST, Christoph Reiter <notifications@github.com> wrote:

> Does this happen every time?

Just started today, happened twice so far. I *think* it was the first
time I restarted Quodlibet since a recent apt-get upgrade; I usually
leave QL running full-time, so long uptimes are the norm. 

I use the quodlibet-unstable repo at:

deb http://www.student.tugraz.at/christoph.reiter/debian/ quodlibet-unstable/

Having said that, I'm not 100% *sure* that this was the first restart
since upgrading.

-- 
Phil Hudson                   http://hudson-it.ddns.net
@UWascalWabbit                 PGP/GnuPG ID: 0x887DCA63

**Comment by lazka** [comment]
I can reproduce something similar with `quodlibet --run --hide --no-plugins` followed by a `quodlibet --show` where, at least under mutter, the window is fully transparent but I can still interact with it (open menus etc.) --> weird

**Comment by PhilHudson** [comment]
I can't reproduce, since I'm not running mutter. 

A data point to add though: problem persists as described even after a full system reboot.

Another: I have recently changed my GTK 2 theme; could that possibly have caused such an effect?

Here's what ```pstree``` showed during the last run:

```
  ├─quodlibet,27448,phil /usr/bin/quodlibet --run --play-file
```

(plus lots of ```quodlibet``` subprocesses).

**Comment by PhilHudson** [comment]
Running from the command line as ```/usr/bin/quodlibet```, I got this:

```
(quodlibet:5179): Gtk-CRITICAL **: gtk_widget_get_preferred_height_for_width: assertion `width >= 0' failed

(quodlibet:5179): Gtk-WARNING **: quodlibet+qltk+cover+CoverImage 0x7d40480 reported min size 2053498628 and natural size 32517 in get_preferred_height_for_width(); natural size must be >= min size
W: Error loading '/path/to/network/share/containing/SomeSong.mp3'
```
Ah-ha! The erroring file is visible to ```ls``` but fails to play in both VLC and mplayer. VLC says it has no codec for 'undf'. Neighboring tracks in the same album directory do play successfully in both VLC and mplayer. I'm going to remove the offending track (keeping a copy for forensics) and see if QL starts OK.

**Comment by PhilHudson** [comment]
And QL is back!

Just shout if you want a copy of the toxic file to test against.

**Comment by lazka** [comment]
Thanks for debugging this. Please send the file to reiter.christoph@gmail.com
