### ISSUE TITLE
Use of pango links

### ISSUE THREAD

**Issue by tkelley65** [quodlibet/quodlibet#1574]
Although I am aware that workarounds are involved regarding pango and GtkLabel, it would be super nice if one could display arbitrary links  throughout QL; it could be implemented simply as a tag value that displayed the link. External (web) links being the main concern here, although local links would be nice as well, possibly for displaying lyrics conveniently from the display window or other browser.

Some of the plugins provide similar functionality but they don't work very well. It would be nice if one could define the link instead of searching for it, and the data (I feel) really belongs in the audio file with the other audio file metadata.

**Comment by lazka** [comment]
This works now ``[a href='http://www.example.com']example[/a]`` or using the ``website`` tag as a source: ``<website|[a href='<website>']Website[/a]>``

**Comment by tkelley65** [comment]
Thanks!!!!!

By the example, do you mean that <website> is the only tag it recognizes,
or was that just an example? The code looks to me like one can use any tag
you like, but I'm not sure ...

Tim Kelley


On Tue, Apr 14, 2015 at 12:55 PM, Christoph Reiter <notifications@github.com

**Comment by lazka** [comment]
I works with every tag, but the value needs to be an URL for it to work.

Another usecase is building URLs from tag values, but we lack a way to escape tag values here.
e.g. ``[a href="https://en.wikipedia.org/wiki/<artist>"]Artist on Wikipedia[/a]`` works most of the time, as long as the artist doesn't contain reserved characters.
