### ISSUE TITLE
Installation script does not respect --install-data

### ISSUE THREAD

**Issue by pyromaniac2k** [quodlibet/quodlibet#1575]
The setup.py script has a parameter called "--install-data" to specify the installation directory for data files. Instead of using that directory, the datafiles all end up intalled in prefix/share, which is bad when you use a prefix different from /usr.

**Comment by lazka** [comment]
Thanks. Which files for example, and why do you need them at a different path?

**Comment by pyromaniac2k** [comment]
we use /usr/x86_64-pc-linux-gnu/ as prefix instead of just /usr, but all the arch-independent files should still be in /usr/share.

This concerns all desktop files, man pages, locale, pixmaps, dbus-service file and appdata xml files.

**Comment by lazka** [comment]
Thanks, I'll have a look. (Everything in QL is arch-independent btw)

**Comment by lazka** [comment]
Would you like this to be backported for 3.4.1?

**Comment by pyromaniac2k** [comment]
Thank you for that fix. Yes, having that patch in 3.4 would be nice.

**Comment by lazka** [comment]
Ok, will do. And any feedback on the packaging guide [0] is welcome.

[0] https://quodlibet.readthedocs.org/en/latest/packaging.html
