### ISSUE TITLE
mp3 playback freezes when sampling frequency changes

### ISSUE THREAD

**Issue by marcelpaulo** [quodlibet/quodlibet#1579]
Most likely this isn't a QL problem, but `GStreamer`. I would like to discuss it and ask your advice.

Playing an mp3 album, I observed that after finishing certain songs, playback froze. I searched for similar previous issues here, found a few, in one of them you recommended `Disable gapless playback` for mp3 files. But my collection is made up entirely of mp3 files, `Disable gapless playback` has always been unticked, and I never had problems with any albums before, including this one which is giving me grief right now.

So I wrote down the songs that caused freezing, and started to investigate why that might happen:

1. Playback also froze on `clementine` but not on `smplayer` (loading the songs as a playlist). clementine also uses `GStreamer`, but `smplayer` uses `mplayer`
2. Installed Ubuntu package `mp3check` and checked the songs with `mp3check -l <file>`. Found out that some songs had sampling frequency **44.1KHz**, and others **48.0KHz**, and playback froze when the next song had a different sampling frequency than the current one.

Found alternative workarounds:

1. `Disable gapless playback` on QL
2. Resample all 48.0KHz songs to 44.1KHz with `lame --preset insane --resample 44.1KHz <oldname> <newname>`

I'm not sure about the repercussions of **1**, if it won't break something further ahead. **2** is downright not practical, since it would entail scanning the whole library in search of 48.0KHz songs (my library has 8823 albums, 134931 songs). 

So my doubt is: can `GStreamer` be configured from QL in such a way that these changes in sampling frequency don't cause freezing ?

I have seen QL config parameter `Output pipeline`, so I imagined something perhaps might be put there to tell GStreamer not to freeze when sampling frequency changes. If I'm speaking nonsense, please forgive me.

**Comment by lazka** [comment]
As GStreamer still doesn't support gapless playback for MP3, workaround (1) should be fine (that's what it's there for)

Which version of GStreamer are you using? See the about dialog in QL for the version info.

Can you send me two affected files to reiter.christoph@gmail.com so I can give it a try?

**Comment by marcelpaulo** [comment]
Thanks for the amazingly speedy reply, Christoph !

Oh, sorry, forgot about the versions:
![about quod libet_003](https://cloud.githubusercontent.com/assets/10074769/7187834/e2d6e20e-e449-11e4-83a8-0998814d9328.jpg)

I uploaded 2 files:
- [0101 Peavine Blues.mp3](https://docs.google.com/file/d/0B6eQjhXV-AquZ1V0WVg3VFVwYkU/edit?usp=drivesdk) has sampling frequency 48.0KHz:
```
0101 Peavine Blues.mp3: mpeg 1.0 layer 3 48.0kHz 320kbps joint stereo no emph crc orig ----     3:30.63
```
- [0102 It's a Curse.mp3](https://docs.google.com/file/d/0B6eQjhXV-AquVlJ0bl96YlRzZHc/edit?usp=drivesdk) has 44.1KHz:
```
0102 It's a Curse.mp3: mpeg 1.0 layer 3 44.1kHz 320kbps joint stereo no emph crc orig ----     3:52.99
```

So, if gapless playback is not disabled, playback should freeze when jumping from 0101 to 0102.

**PS:** I'm running Xubuntu 14.10

**Comment by marcelpaulo** [comment]
Forgot to mention: ran QL debugging GStreamer, `GST_DEBUG='*:3' quodlibet`, and provoked the playback freezing. Couldn't decypher most messages, but these caught my eye:
```
0:04:34.252584948  7213     0x1639b720 WARN          mpegaudioparse gstmpegaudioparse.c:480:gst_mpeg_audio_parse_head_check:<mpegaudioparse10> invalid samplerate: 0x3
0:03:30.677112869  7213      0x2cdd940 WARN          mpegaudioparse gstmpegaudioparse.c:474:gst_mpeg_audio_parse_head_check:<mpegaudioparse8> invalid bitrate: 0xf
```
One or both appeared whenever playback froze. Should I report a bug to GStreamer ?

**Comment by marcelpaulo** [comment]
If GStreamer doesn't support mp3 gapless playback, then it shouldn't make any difference whether QL disables or enables it: QL would be requesting gapless playback from GStreamer, but GStreamer would reply that it can't do it.

Perhaps I'm missing something.

**Comment by marcelpaulo** [comment]
Found this [thread](http://ubuntuforums.org/showthread.php?t=2069709) discussing gapless playback. Although outdated, it seems useful. This catches the eye:

> MP3 is very much gapless whn encoded properly. Even in Quod Libet.

> Since there's nothing in the MP3 standard to provide for this there are encoder specific standards. If > encoded with LAME your MP3 play back gaplessly because of the LAME header. IF the same holds > true for the iTunes header I'm not sure.

And it has extensive (and well deserved !) compliments to QL. I second them !

**Comment by lazka** [comment]
I can't reproduce on 14.10 with pulseaudio at least. With alsasink I get a short hang, but that's still with active pulseaudio. Are you using something other than pulseaudio by any chance?

This seems like a similar problem to all the other hang on song change problems with GStreamer.

Regarding the effect of disabling gapless as QL names it: Disabling will force QL to throw away all GStreamer stuff and recreate it on a song change. If gapless is enabled the GStreamer pipeline will be reused for the following song. So it's not a small change to tell GStreamer to disable gapless, but a different way to use GStreamer. We needed this option as reusing the pipeline triggers bugs like this.

**Comment by lazka** [comment]
That is incorrect. While gapless is possible with MP3 if encoded with lame and maybe others, GStreamer hasn't implemented it until now. There is some recent work/patches to fix this if you want to follow the progress: https://bugzilla.gnome.org/show_bug.cgi?id=620323

**Comment by marcelpaulo** [comment]
> I can't reproduce on 14.10 with pulseaudio at least

Did you incorporate the mp3 files in the library ? I noticed that playing them from the File System browser not always reproduced the error, but from the Album List browser, it always happened.

> Are you using something other than pulseaudio by any chance?

Just pulseaudio.

> If gapless is enabled the GStreamer pipeline will be reused for the following song

This might explain why GStreamer chokes when the sampling frequency changes. Somehow (I'm ignorant about GStreamer) a pipeline seems to be tied to a particular sampling frequency.

Thanks for the correction about GStreamer mp3 gapless support. I trust, value and admire all your comments: you're always thoughtful and precise. Paraphrasing (Jorge Luis) Borges: my ignorance of GStreamer is almost perfect ! So I'm bound to be wrong.

**Comment by marcelpaulo** [comment]
Christoph, did a quick experiment: 

1. Didn't disable gapless playback on QL, and played Pink Floyd's *Dark Side of the Moon* (in mp3): the transition from, say, *Time* to *The Great Gig in the Sky* was spotlessly gapless. If GStreamer doesn't implement gapless, how could that happen ? If you don't have the album (in mp3) and wanna try it out, here they are: [Time](https://docs.google.com/file/d/0B6eQjhXV-AqucDQ0NDRPX1pqZ2c/edit?usp=drivesdk) and [The Great Gig in the Sky](https://docs.google.com/file/d/0B6eQjhXV-AquTkJuNVF0Nm9RLVE/edit?usp=drivesdk). As expected, both are 44.1KHz.
2. Disabling gapless playback, there was a slight hiccup between them, of course as expected

**Comment by lazka** [comment]
This is probably again #1177. I guess the frequency change is just changing the timing triggering the bug.

For gapless: Might be that the gap for those files is just short.. rebuilding the pipeline takes more time in addition to the gap.

**Comment by marcelpaulo** [comment]
You might add those 2 songs with different sampling frequencies as a test case for the [upstream bug](https://bugzilla.gnome.org/show_bug.cgi?id=702856).
