### ISSUE TITLE
Show playback progress bar

### ISSUE THREAD

**Issue by ochosi** [quodlibet/quodlibet#1586]
Hey,
first of all, congrats on the nice player that quodlibet is. I've started using it during the last few days and it's really amazingly flexible and feature-rich, while still feeling lean and fast.

However – and this is mostly intended as feedback, I reckon that you have very consciously decided to keep things as they are – one thing that isn't really working for me is the hidden playback progress scale. Having to click a button and then clicking into the popup to scroll back/forward within a song feels very fiddly and if you don't wanna count the seconds it's also hard to know where in the song you currently are without that GtkScale being visible.
So yeah, if it were up to me I would switch that around a bit and make the scale visible.

**Comment by lazka** [comment]
Related: #204, #1530

You can scroll on the button btw.

**Comment by declension** [comment]
Shall we mark this as a duplicate (and useful reminder) of #204 then?
