### ISSUE TITLE
Switch tag keys to unicode

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1589]
To allow freeform mp4 and id3 txxx support it would be nice to have non-ascii keys.

So either use utf-8 str or unicode/ascii-str. I'd say move to unicode/ascii-str, and see what breaks.

**Comment by lazka** [comment]
Related: #935

**Comment by lazka** [comment]
Some stats on the memory usage difference when using unicode:

py2+str: 113MB
py2+unicode: 142MB
py3+str: 98MB

**Comment by zsau** [comment]
What size library are those stats from?

**Comment by lazka** [comment]
15k

**Comment by zsau** [comment]
Oh, that's not bad at all. Are your songs heavily tagged? For comparison, with my ~20k library the expression below evaluates to about 4.2m.

```
sum(len(k) for s in songs for k in s.keys() if not k.startswith('~'))
```

**Comment by lazka** [comment]
~1.8m

**Comment by lazka** [comment]
The difference in memory usage is quite large and it's unclear when we will be ready to switch to py3, so ascii str/unicode it is.
