### ISSUE TITLE
Error with Animated On-Screen Display-plugin.

### ISSUE THREAD

**Issue by StephanWeinhold** [quodlibet/quodlibet#1591]
When I try to change or preview the Animated On-Screen Display-plugin I receive an error. Yesterday it was working fine...
The version is 3.4.0 on a Windows 7-6.1.7601-SP1.

The error-file says:

=== SYSTEM INFORMATION:
Quod Libet 3.4.0
Mutagen 1.27
Python 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)] win32
Platform Windows-7-6.1.7601-SP1

=== STACK TRACE
Traceback (most recent call last):

  File "quodlibet\ext\events\animosd.pyc", line 332, in on_button_pressed

  File "quodlibet\ext\events\animosd.pyc", line 329, in show_preview

  File "quodlibet\ext\events\animosd.pyc", line 661, in plugin_on_song_started

  File "quodlibet\ext\events\animosd.pyc", line 81, in **init**

  File "tempfile.pyc", line 391, in **getattr**

AttributeError: 'file' object has no attribute 'get_height'

=== LOG:
D: 524.80: PlaylistModel.set: Done filling model.
D: 528.21: config.save: Writing config...
D: 528.22: library.save: Saving all libraries...
D: 528.22: SongFileLibrary.save: Saving contents to u'C:\Users\weinhold\AppData\Roaming\Quod Libet\songs'.
D: 529.48: PlaylistModel.set: Clearing model.
D: 529.48: PlaylistModel.set: Setting 36 songs.
D: 529.48: PlaylistModel.set: Done filling model.
D: 531.70: PlaylistModel.set: Clearing model.
D: 531.70: PlaylistModel.set: Setting 37 songs.
D: 531.70: PlaylistModel.set: Done filling model.
D: 534.27: PlaylistModel.set: Clearing model.
D: 534.27: PlaylistModel.set: Setting 38 songs.
D: 534.27: PlaylistModel.set: Done filling model.
D: 534.73: PlaylistModel.set: Clearing model.
D: 534.74: PlaylistModel.set: Setting 39 songs.
D: 534.74: PlaylistModel.set: Done filling model.
D: 536.74: PlaylistModel.set: Clearing model.
D: 536.74: PlaylistModel.set: Setting 40 songs.
D: 536.74: PlaylistModel.set: Done filling model.
D: 543.25: PlaylistModel.set: Clearing model.
D: 543.25: PlaylistModel.set: Setting 41 songs.
D: 543.25: PlaylistModel.set: Done filling model.
D: 545.19: PlaylistModel.set: Clearing model.
D: 545.19: PlaylistModel.set: Setting 42 songs.
D: 545.19: PlaylistModel.set: Done filling model.
D: 560.56: PlaylistModel.set: Clearing model.
D: 560.56: PlaylistModel.set: Setting 132 songs.
D: 560.56: PlaylistModel.set: Done filling model.
D: 561.98: PlaylistModel.set: Clearing model.
D: 561.98: PlaylistModel.set: Setting 42 songs.
D: 561.99: PlaylistModel.set: Done filling model.
D: 569.87: PlaylistModel.set: Clearing model.
D: 569.88: PlaylistModel.set: Setting 42 songs.
D: 569.88: PlaylistModel.set: Done filling model.
D: 583.77: PlaylistModel.set: Clearing model.
D: 583.77: PlaylistModel.set: Setting 3 songs.
D: 583.77: PlaylistModel.set: Done filling model.
D: 594.35: PlaylistModel.set: Clearing model.
D: 594.35: PlaylistModel.set: Setting 45 songs.
D: 594.35: PlaylistModel.set: Done filling model.
D: 828.22: config.save: Writing config...
D: 828.23: library.save: Saving all libraries...
D: 020.20: GStreamerPlayer.go_to: Going to <GtkTreeIter at 0x5a31170>
D: 020.20: PlaylistMux.go_to: Told to go to <GtkTreeIter at 0x5a31170>
D: 020.20: QueueModel.go_to: Told to go to None
D: 020.20: PlaylistModel.go_to: Told to go to <GtkTreeIter at 0x5a31170>
D: 020.20: GStreamerPlayer._end: End song
D: 020.20: util.cover.manager.failure: Didn't get cover from FilesystemCover: This source is incapable of fetching covers
D: 020.21: util.cover.manager.run: Found local cover from EmbedCover
W: GDK error while loading cover image: Datei »c:\users\weinhold\appdata\local\temp\tmphewg5y« konnte nicht geöffnet werden: Permission denied
D: 020.21: GStreamerPlayer._end: Next song
D: 020.30: SongFileLibrary._changed: Changing 2 items.
D: 020.31: qltk.completion.__update_song: Updating tag model for 2 songs
D: 020.31: qltk.completion.__update_song: Done updating tag model for 2 songs
D: 020.31: library.libraries.__changed: Updating affected albums for 2 items
D: 022.18: GStreamerPlayer._end: End song
D: 022.18: util.cover.manager.failure: Didn't get cover from FilesystemCover: This source is incapable of fetching covers
D: 022.19: util.cover.manager.run: Found local cover from EmbedCover
W: GDK error while loading cover image: Datei »c:\users\weinhold\appdata\local\temp\tmpxnyf_t« konnte nicht geöffnet werden: Permission denied
D: 022.20: GStreamerPlayer._end: Next song
D: 022.38: SongFileLibrary._changed: Changing 2 items.
D: 022.38: qltk.completion.__update_song: Updating tag model for 2 songs
D: 022.38: qltk.completion.__update_song: Done updating tag model for 2 songs
D: 022.38: library.libraries.__changed: Updating affected albums for 2 items
D: 029.85: qltk.window.__restore_state: Restore state
D: 029.85: qltk.window.__restore_position: Restore position
D: 029.85: qltk.window.__restore_size: Restore size
W: GDK error while loading cover image: Datei »c:\users\weinhold\appdata\local\temp\tmptw1tp8« konnte nicht geöffnet werden: Permission denied
W: GDK error while loading cover image: Datei »c:\users\weinhold\appdata\local\temp\tmpxzl0mj« konnte nicht geöffnet werden: Permission denied
W: GDK error while loading cover image: Datei »c:\users\weinhold\appdata\local\temp\tmpsgty8o« konnte nicht geöffnet werden: Permission denied
W: GDK error while loading cover image: Datei »c:\users\weinhold\appdata\local\temp\tmphrrvp9« konnte nicht geöffnet werden: Permission denied
W: GDK error while loading cover image: Datei »c:\users\weinhold\appdata\local\temp\tmp0jhup5« konnte nicht geöffnet werden: Permission denied
W: GDK error while loading cover image: Datei »c:\users\weinhold\appdata\local\temp\tmpcafigf« konnte nicht geöffnet werden: Permission denied
W: GDK error while loading cover image: Datei »c:\users\weinhold\appdata\local\temp\tmptvwhrw« konnte nicht geöffnet werden: Permission denied
W: GDK error while loading cover image: Datei »c:\users\weinhold\appdata\local\temp\tmptsdmfa« konnte nicht geöffnet werden: Permission denied

**Comment by StephanWeinhold** [comment]
Update: during the last days it is sometimes working - didn't change anything. So maybe it has something to do with the songs.

**Comment by lazka** [comment]
Sorry for the late response. I remember having a look at this but I couldn't figure out what could be the cause of the error.

The code where the error occurred was moved and rewritten some time ago, so I hope that this got fixed along the way.

Thanks for the report.
