### ISSUE TITLE
Make tests independent of setup.py

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1592]
We currently do some global setup, change env vars, create temporary directories and create a private dbus.

Maybe we can do this on import and register an atexit handler for cleanup.

To make the tests work without a custom test discovery abstract test classes need to be split in setup base classes and mixins for shared tests (as those abstract classes will be run and fail atm.)

**Comment by declension** [comment]
:+1:

**Comment by lazka** [comment]
More things should work now.. to fix the rest all AbstractTestCase need to be removed.

**Comment by lazka** [comment]
should work now

e.g. `py.test tests`
