### ISSUE TITLE
crash while starting quodlibet on ubuntu 14.04

### ISSUE THREAD

**Issue by idlethread** [quodlibet/quodlibet#1594]
Starting quodlibet producted a crash. Log file attached.

=== SYSTEM INFORMATION:
Quod Libet 3.4.-1
Mutagen 1.28
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] linux2
Platform Linux-3.18.0-031800rc7-generic-x86_64-with-Ubuntu-14.04-trusty

=== STACK TRACE
Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/quodlibet/ext/events/animosd.py", line 148, in do_draw
    self.draw_title_info(fg_cr)

  File "/usr/lib/python2.7/dist-packages/quodlibet/ext/events/animosd.py", line 241, in draw_title_info
    transmat.scale(pbuf.get_width() / float(rect.width),

ZeroDivisionError: float division by zero

**Comment by brunob** [comment]
I think this one is due to 1df209de7febd78e624be1e2f841ac4cde513b1d @lazka 

See also #1591 which may be due to the same commit.

**Comment by lazka** [comment]
#1591 is before the commit

**Comment by declension** [comment]
No longer supported - closing
