### ISSUE TITLE
Skipping 10-20 tracks instead of 1 on "Next track" bluetooth headset's button

### ISSUE THREAD

**Issue by janot** [quodlibet/quodlibet#1596]
_What did you try to do?_
Skip 1 song using "Next track" bluetooth headset's button

_What did you expect to happen?_
To hear next song

_What did happen instead?_
Qudlibet quickly skips a lot of songs (like 10 or 20) and I even hear parts of them while it skips

_Which version of Quod Libet?_
3.4.0.-1

_Which operating system including version (Ubuntu 14.04, Win7, Debian sid, ...)?_
Ubuntu 15.04 (it happens since 14.04)

It doesn't always happen, just sometimes (e.g. it may skip 10 times normally and next 10 times). I'm not sure, maybe it's not Quodlibet's bug.

**Comment by lazka** [comment]
Thanks. After a quick search, it seems these go through uinput translating them to keyboard events and if you use Unity/Gnome through the gnome mmkeys dbus interface to QL.

* Maybe the repeat rate of bluetooth buttons is wrong. Does pressing shorter/longer have an effect?
* Maybe the (hardware) button gets stuck somehow.
* ...?

Can you test with a different media player (totem for example) and see if the same problem exists there?

**Comment by janot** [comment]
- Button also has long press, but it has no effect in Quodlibet.
- I don't think hardware button is stuck because I haven't noticed such behaviour when using this headset with other devices.
- I'll try to check in other player, but this behaviour happens quite unpredictably and not often, so it will take some time

**Comment by lazka** [comment]
I also remember a GStreamer bug where it got in an error loop sending us EOS after it starts playing which results in each song playing for a short moment and then skipping to the next one. But I haven't seen that in a while.

Maybe it depends on the song you skip or the one you skip to?

**Comment by janot** [comment]
Hm.. I can't say about specific song because I'm listening to a lot of songs in random order. I don't think it depends on song because when bug starts to occur, it affects all songs. Now I've remembered that when this bug starts to happen, it disappears after I reconnect headset. If it's not Quodlibet's bug maybe you can help me to decide where should I report it properly?

**Comment by lazka** [comment]
No idea atm, sorry.

**Comment by lazka** [comment]
@janot Is this still a problem?

**Comment by janot** [comment]
@lazka can't check it, I'm not using linux anymore

**Comment by lazka** [comment]
@janot ok, thanks for the quick reply. I'll close this for now then.
