### ISSUE TITLE
Tidy up application menu

### ISSUE THREAD

**Issue by CreamyCookie** [quodlibet/quodlibet#1598]
The current application menu has some redundancies and some items that aren't ordered semantically. Here's my suggestion:

* **Quod Libet**
  * Preferences
  * Plugins
  * ------------------
  * Online Help
  * Search Help
  * About
  * ------------------
  * Quit

* **View** # no change

* **Library**
  * Add a file
  * Add a folder
  * Add a location
  * ------------------
  * Refresh Library
  * Search Library

* **Filters** # no change

* **Control**
  * Previous
  * Play
  * Next
  * Stop after this song

* **Current song**
  * Jump to playing song
  * Add bookmark
  * Edit bookmark
  * ------------------
  * Edit Tags
  * Information

----

**Related enhancements / bugs:**
* #1527 - Add the context menu of the current song under "Control" in the menu bar
* #1601 - "Filter on genre" is missing in the context menu of the current song
* #1602 - Add all "saved searches" to the "Filters" submenu in the menu bar

**Comment by declension** [comment]
Some good points there (having a _Library_ top-level menu makes a lot of sense), and a few that don't work for me.

@CreamyCookie, do you think you could split this ticket into logically distinct tasks, as there are too many things to implement for this to get done any time soon.

**Comment by CreamyCookie** [comment]
@declension Thanks!

1. I would leave this bug report here and extract / create the following 2 additional ones. Is that okay with you?
  * insert saved searches have (including the current 4 default ones: all, recently played, recently added, top40)
  * "Filter on genre" seems to be missing in the context menu of the current song.
2. Which are the ones you don't like? Maybe I can win convince you (or you me).. :smile:

**Comment by declension** [comment]
@CreamyCookie that sounds great. Perhaps reduce this ticket to being about a Library top-level menu and add others as necessary.

@lazka and I agreed recently that _extra_ top-level menus should probably be avoided if possible (there are already enough), especially with Ubuntu (15) adding its own (currently).

**Comment by lazka** [comment]
The Ubuntu menu is gone now #1599. For a plugin menu we have #152

Here is the Gnome HIG btw: https://developer.gnome.org/hig/stable/menu-bars.html.en
(but given that Gnome is moving away from menu bars, ignoring it shouldn't do much harm)

**Comment by CreamyCookie** [comment]
@declension I have extracted the two bug posts and cleaned up this one a bit. (Is that wording correct, or should it be "cleaned this one up a bit"?)

@lazka @declension Regarding too many top-level menus: Are 6, as in the [above suggestion](https://github.com/quodlibet/quodlibet/issues/1598#issue-71852217) too many? If so, maybe we could merge **Control** and **Current song**, .. and call it "Music"?

**Comment by CreamyCookie** [comment]
@declension I have extracted the two issue posts, as mentioned, and cleaned up this one a bit. (Is that wording correct, or should it be "cleaned this one up a bit"?)

@lazka Regarding too many top-level menus: Are 6, as in the [above suggestion](https://github.com/quodlibet/quodlibet/issues/1598#issue-71852217) too many? If so, maybe Control should stay the way it is?

**Comment by CreamyCookie** [comment]
@declension Is the report okay the way it's now?

**Comment by declension** [comment]
Continuing on from here and points raised in #1716, #1943, and to a lesser extent #1931, #1046...

With some fresh perspective I realised more than ever how confusing some of the QL menus are, and am currently experimenting with a more standard setup, with similarities to the above from @CreamyCookie :

#### Revised structure
_File_, _Edit_, _View_, _Browse_, _Control_, _Help_.

* _File_ is essentially _Music_ minus the secondary browser item
* _Edit_ has Edit Tags, Bookmarks (one day maybe: Lyrics..)
* _View_ has Queue checkbox, and Information (TODO: clean-up / split / improvement of this anyway)
* _Browse_ has just the browser-related items
* _Control_ is as before, with Filters as a sub-menu
* _Help_ is as before


This is only one more menu than previously, so not too much horizontal bloat as feared, and conforms more with the Gnome HIG @lazka mentioned above.

#### Benefits
 * Editing of tags is no longer under the _view_ menu
 * Filters merged into control, as to me browser selection (etc) feels much more important
 * Add bookmark gone - I'd venture it was rarely used (try it...)
 * Changing the primary browser and launching a new browser are now in the same place (browsing..)
 * Launching the secondary is at the top, for UX improvement.
 * Disable browser gone (see other ticket)
 * View options are simpler - the songlist is always visible as it's too confusing for new (and old) users when it disappears, IMO, but can reinstate it if anyone really misses it.

**Comment by CreamyCookie** [comment]
Great ideas! Just a few points:

>  Control is as before, with Filters as a sub-menu

I think putting *Filters* into *View* would fit better since it affects what's displayed in the current browser.

> Editing of tags is no longer under the view menu

*Edit tags* is in *Control* for me. Am I missing something?

>  Browse has just the browser-related items

Maybe it could look similar to this:

* Browse
  * Individual Songs (still not a perfect name)
  * Paned Browser (would be cool if there was a name without "Browser")
  * Album List
  * Album Collection
  * Playlists
  * ---------------- (separator here because the browsers below have nothing to do with the library)
  * File System
  * Internet Radio
  * Audio Feeds
  * Media Devices

**Comment by declension** [comment]
> I think putting Filters into View would fit better since it affects what's displayed in the current browser.

Agree it doesn't belong in _Control_ - I'd actually already moved it to _Browse_, since as you say it's a browser concern (and in the code too actually). Let's try it there for now

> Edit tags is in Control for me. Am I missing something?

Thanks, yes you're right - I've already forgotten what it used to look like! Anyway, in _no_ way does it control (the player).

> Paned Browser (would be cool if there was a name without "Browser")

Yes - I was actually considering renaming this _Hierarchies_. Crazy, at first, but I think it's most appropriate name (panes are a UI concern, and browser, well they're _all_ browsers..)

> ---------------- (separator here because the browsers below have nothing to do with the library)

Great idea, I'll add that now.

**Comment by CreamyCookie** [comment]
> Yes - I was actually considering renaming this Hierarchies. Crazy, at first, but I think it's most appropriate name (panes are a UI concern, and browser, well they're all browsers..)

I like that.

**Comment by declension** [comment]
From discussion on IRC:
* [iTunes screenshots](https://imgur.com/a/gu1Dy)
* [Foobar screenshots](https://imgur.com/a/Q3QNJ)

**Comment by CreamyCookie** [comment]
@declension Great work! I really like the new menu. Closing this.
