### ISSUE TITLE
ID3 v2.4 upgrade optional

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#160]
Original [issue 160](https://code.google.com/p/quodlibet/issues/detail?id=160) created by DuchessOfKvetch on 2009-03-23T00:45:53.000Z:

Users should be made more aware that the Mutagen library's Save function 
will upgrade any MP3 files to ID3 version 2.4 (though the conversion 
appears to actually happen during loading of the file). While one could 
certainly comment out the call to this upgrade method, it can cause 
problems with music libraries as read by certain common applications, 
which only work with 2.3. At least in the WIndows world, 2.4 is still 
considered &quot;controversial&quot; or experimental. I know MediaMonkey does NOT 
natively work with 2.4, and I believe Itunes even defaults to 2.3 for 
maximum compatibility.

**Comment by lazka** [comment]
This should now be possible with newer mutagen. We could add a plugin which simply does "Save as ID3v2.3" on the selected songs, so it's possible but we don't really have to care about it.

**Comment by lazka** [comment]
Merge with #403

**Comment by svnpenn** [comment]
https://github.com/quodlibet/quodlibet/issues/2041

**Comment by svnpenn** [comment]
https://github.com/quodlibet/mutagen/issues/82

**Comment by svnpenn** [comment]
https://github.com/quodlibet/mutagen/issues/85
