### ISSUE TITLE
Track Repeat plugin is broken

### ISSUE THREAD

**Issue by declension** [quodlibet/quodlibet#1600]
### Steps to replicate
* Enable plugin
* Set a value of 2 or more

### Expected
* Current song to repeat
* Value to be saved on re-examining the plugin prefs

### Actual
* Value does not appear to be saved
* Next song in queue comes immediatey

**Comment by declension** [comment]
Hmm, can no longer replicate this.

**Comment by lazka** [comment]
Me neither.

**Comment by declension** [comment]
Thanks; closing for now then
