### ISSUE TITLE
Add "Filter on genre" to songsmenu (always) 

### ISSUE THREAD

**Issue by CreamyCookie** [quodlibet/quodlibet#1601]
In the menu bar there's an option to filter albums according to the genre of the current song. This option is missing in the context menu of any song (within the browser).

**Comment by declension** [comment]
Thanks.

Assuming you meant the context (right-click) menu of _any_ song within the songlist, as unless I'm very mistaken the _playing_ song (info area) context menu doesn't have any filter options (because that doesn't make sense, especially in a multi-browser setup).

**Comment by CreamyCookie** [comment]
@declension Yeah.. you're right. I updated it.

**Comment by declension** [comment]
Only through debugging do I now see how this works (and it does)

If you click on a row on the songlist, but *within a filterable column* (other than `artist`, `album`), it will appear in the context menu for you.

@CreamyCookie options for closing this:
 * update some docs, probably, as it took me years to notice this, and it's not obvious
 * Add genre as one of the hard-coded ones; obviously not everyone wants this, and it takes up space, but genre feels quite important.

**Comment by CreamyCookie** [comment]
Hmm.. I've clicked on a row, but for me "Filter on Genre" is grayed out. Maybe it has to do with the browser. This is the "Search Library" browser.

![screenshot from 2016-07-05 13-35-27](https://cloud.githubusercontent.com/assets/3063858/16583390/73344d08-42b5-11e6-8a68-546bfe9c0f85.png)

> Add genre as one of the hard-coded ones; obviously not everyone wants this, and it takes up space, but genre feels quite important.

True. I think that would be solved if we implement #1797.

**Comment by declension** [comment]
@CreamyCookie that looks like the main menu, not the context menu (right-click)

**Comment by CreamyCookie** [comment]
Ah, now I see. Cool find! That's actually not a bad feature. Yeah, I'd be in favor of updating the docs, given that we implement #1797. The question is how to combine that with this feature. Maybe it could look like this:

* Filter Rating (this is the column the user right clicked on)
* Filter on..
  * artist
  * album
  * genre
  * ..

That way, one still can filter according to the genre, but we don't have to waste space for those who rarely use it.

**Comment by declension** [comment]
Docs updated in #1975

**Comment by CreamyCookie** [comment]
@declension Very nice!

I'm closing this in favor of #1797 which I now modified slightly to mention the inconsistency of having `Filter on genre` in the main, but not in the song menu.

**Comment by declension** [comment]
Thanks
