### ISSUE TITLE
Does not start from a random track when the play order is "shuffle."

### ISSUE THREAD

**Issue by khatamnejad** [quodlibet/quodlibet#1603]
I have put the play order to "Shuffle" in order to listen to my playlist in random order, but when I select a Playlist - specifically when the application has just started - to listen the player always plays the first track of the playlist; The rest of the playlist plays in random order but the first played track is always the first track of the playlist.

**Comment by lazka** [comment]
Which version of Quod Libet?

**Comment by khatamnejad** [comment]
3.0.2

**Comment by lazka** [comment]
This should be fixed in a newer version. I guess you are on Ubuntu 14.04, give the PPA a try: https://quodlibet.readthedocs.org/en/latest/downloads.html#ubuntu

**Comment by khatamnejad** [comment]
Thanks!
