### ISSUE TITLE
Support value conditions for conditional tags

### ISSUE THREAD

**Issue by am4c130d** [quodlibet/quodlibet#1604]
I have multiple types of audio file: classical music, popular/rock music, audiobooks etc., and have tried to add as complete a set of tags as I can, such as Composer, Conductor, Artist and Author, as well as Genre.  I'd like to display the "album" differently depending on the genre of the audio file.  For example

    Classical Music = <Composer>\: <Album> conducted by <Conductor>
    Rock Music = <AlbumArtistSort> <OriginalDate> <Album>
    Audiobooks = <Album> by <Author>

Currently I use the presence of tags such as Author to denote books, and Conductor to denote Classical music, but this is not perfect, as not all Classical Music (in the broadest sense of Classical) has a conductor.

My thinking was to allow a test condition (like a case statement) - i.e. 

     [genre=Classical]<Composer>\: <album> conducted by <conductor> [genre=Rock]....{genre=*]<artist> <date> <album>

Thanks

UPDATED to correctly show the "code"

**Comment by declension** [comment]
This would be a significant change to how conditional tags works globally (not per browser), which would need careful thought and testing not to disrupt current behaviour.

Note that, AIUI, _most_ of your use-case is covered by the current [conditional tag support](http://quodlibet.readthedocs.org/en/latest/guide/tags/patterns.html?highlight=conditional#conditional-tags) (which has been enabled in the Paned Browser for a while), and this is arguably a more reliable way of providing the information anyway (not all classical music has a conductor tag, as you say) - c.f. [Duck Typing](https://en.wikipedia.org/wiki/Duck_typing) in programming.

For example, for your display you could try something like this:

    <conductor| conducted by <conductor>|><author| by <author>|>

**Comment by am4c130d** [comment]
Thanks - agreed, most of what I want is there already - and in reviewing I can see that a lot of my original post is missing, my ignorance of Github - apologies.

What I started with was this

    <genre>
    <albumartistsort|<albumartistsort> \<small\>\<i\><originaldate|<originaldate>|<date>>\<\/i\>\<\/small\> <album>|<albumartist|<albumartist> \<small\>\<i\><originaldate|<originaldate>|<date>>\<\/i\>\<\/small\> <album>|<author|<album> \<small\>\<i\>by\<\/i\>\<\/small\> <author>|<composer|<album><conductor|  \<small\>\<i\>conducted by\<\/i\>\<\/small\> <conductor>>|<artistsort|<artistsort> \<small\>\<i\><originaldate|<originaldate>|<date>>\<\/i\>\<\/small\> <album>|<artist|<artist> \<small\>\<i\><originaldate|<originaldate>|<date>>\<\/i\>\<\/small\> <album>>>>>>>
    <album>\: <discsubtitle|<discsubtitle>\: |<discnumber>\:><tracknumber> <title>:(<~length>)

Which is three pane approach, but the middle line is unwieldy - basically it looks for albumartistsort and uses that as the artist name if present, if not it uses albumartist, if that is not present, author, then conductor, and just to clean up, then artistsort and finally artist.  This worked, because I only used albumartistsort and albumartist on popular music.

Each now show as follows
Popular music: Artist Release-date Album
Classical (if conductor): Album conducted by Conductor (this is a cheat, as i have the composer name at the start of all Classical album names due to lesser players not recognising composer - I'd prefer to use Composer Piece conducted by Conductor)
Audiobooks: Album by Author

I cleaned this up to the following (only showing the middle row now)

    <author|<album> \<small\>\<i\>by\<\/i\>\<\/small\> <author>|<conductor|<album> \<small\>\<i\>conducted by\<\/i\>\<\/small\> <conductor>|<albumartistsort|<albumartistsort> \<small\>\<i\><originaldate|<originaldate>|<date>>\<\/i\>\<\/small\> <album>>>>

Which was fine, but the header in the pane now showed Album by Author - which is OK, but a bit non-sensical.  However, this allows me to add albumartistsort/albumartist tags on all audio files for lesser players.

So now I've cheated and created some made up tags that solely tell quodlibet how to "construct" the album name format and use this line

    <spokenword|<albumartistsort> \<small\>\<i\><originaldate|<originaldate>|<date>>\<\/i\><\/small\> <album>|<story|<album> \<small\>\<i\>by\<\/i\>\<\/small\> <author>|<songs|<album>|<classical|<conductor|<album> \<small\>\<i\>conducted by\<\/i\>\<\/small\> <conductor>>|<albumartistsort> \<small\>\<i\><originaldate|<originaldate>|<date>>\<\/i\>\<\/small\> <album>>>>>>

Its getting a bit unwieldly again, but its OK.  Basically, the first section is to force the header of the pane to be correct. the second formats audiobooks, the third songs (for my kids) the fourth classical music when there is a conductor present and the last does everything that wasn't previously captured.

So, I have a workaround, and I'd be very open to suggestions on how to improve my attempt at meeting my goals without changing the product.  Thanks for such a great product.

Thanks

Alan

**Comment by declension** [comment]
@am4c130d - another minor note - you can (and probably would want to) use [square-bracket style pango markup](http://quodlibet.readthedocs.org/en/latest/guide/tags/patterns.html?highlight=conditional#text-markup), which will save you from backslash hell there (one day we'll add a better / more WYSIWYG tag editor...)

Also just noticed this issue is probably now a superset of #536

**Comment by am4c130d** [comment]
Thanks - the aquare brackets will help with readability - not least of which is it should make the tag strings much shorter.

Re #536, agreed, I have done what it sounds like the OP did, and created multiple rename profiles - an automated way would be excellent.  The rename capability is one of the many features I really grew to appreciate with Quodlibet/ExFalso.

I personally would rank conditional over WYSIWYG for my uses...

Thanks

**Comment by declension** [comment]
OK I've closed that one, to allow a more general discussion of the feature / solution here

**Comment by am4c130d** [comment]
In terms of generic solution, supporting something like a case statement would appear to meet both my goals and #536.

Conceptually

    case <genre> "classical") <conductor|<composer> <album> [small][i] conducted by [/i][/small] <conductor>|<composer> <album> [small][i] performed by [/i][/small] <albumartistsort>>;;"audiobook") <author>: <album>;;*) <albumartistsort> [small][i]<originaldate>[/i][/small] <album>;;esac

Its still long, but more readable and flexible, without lots of nested if/then/else statements.  Obivously the free text "case" would need to be delimited in someway.

Thanks

**Comment by lazka** [comment]
I'm in favor of just using the query language or a subset (tag matches) of it. e.g. ```<foo=bar|then|else>```, and ```<foo|then|else>``` is shorthand for ```<foo=!""|then|else>```

**Comment by declension** [comment]
Me too; in fact the current implementation I tried mostly achieves (some escaping / unicode gotchas right now) the first of those, being the simplest and the one I'd favour.

Full(er) query syntax support is going to be much harder given the custom parser / lexer in use there (`|` is a special character in both patterns and regex, for example), and I don't think represents a good (risk+effort):reward ratio here.

Already, making the `=` a reserved character (like `|`, `<`, `>`) has knock-on problems: Pango markup, being based on XML, uses `=` for attribute specification (e.g. `<p class="bold">` or `[i style="blah"]`). So there are _some_ (not many, I'd say) users who will have their display patterns made invalid by this change.  We could possibly auto-escape these as a one-off upgrade task (I think?).

It would almost certainly _not_ affect patterns as used elsewhere (e.g. renaming files, paned browser, duplicates browser plugin) as I can't see any use for the `=` sign in non-markup contexts.

**Comment by lazka** [comment]
Shouldn't it be possible to have tokenize until ```|``` and require escaping ```\|``` in the query? Might need a new lexer..

**Comment by am4c130d** [comment]
Extending the if|then|else concept to include if match|then|else still meets the goals I have, and if its relatively easy, then I am all for it.

**Comment by declension** [comment]
@lazka yes, that could work I guess. I'll have a look.

Would need to escape any `<` and `>`s too but people with those values in their tags are already asking for trouble I suppose...

**Comment by declension** [comment]
So, having tried this out (and broken most of the tests):

The biggest problem I've found so far is distinguishing between an existing "if tag not-null" condition, represented as `<tag|tag-exists-value|default-value>`, and a new form of free-text query for the _word_ "tag" also represented as `<tag|tag-exists-value|default-value>`, especially given how this is often used for custom tags

For example, how can we now distinguish a (freetext) query for the word _release_ (matching things like [this album](http://musicbrainz.org/release/2101348a-3f77-3719-974f-5a10b1d802d8) fully or [this one](http://musicbrainz.org/release/588825e3-4757-4ccd-bc94-f2abb6fe7a63) partially), and queries about the tag `~release`, when the `~` is not mandatory?

I suppose either we migrate old queries, or require a literal format for all freetext searches (`"release"`)... or some other ideas I haven't thought of yet.

Or, we could demand that a form of `tag=_expr_` is used, where expr could also be a regex, but this has then lost the flexibility of freetext _and_ the flexibility of boolean queries. Hmmm

**Comment by lazka** [comment]
I was thinking something like this:

```
if Query.get_type(query) in (QueryType.INVALID, QueryType.TEXT):
    result = bool(song(query))
else:
    result = Query(query).search(song)
```

i.e. everything that isn't a special query syntax gets treated as tag name as before.
