### ISSUE TITLE
Enable QL to be set as the default audio player in Windows

### ISSUE THREAD

**Issue by heri0nd3** [quodlibet/quodlibet#1607]
Is there possible to add ability to make quodlibet as a default audio player for Windows? When I installed on the system back then, it doesn't appear to be set a default from the Default Programs Control Panel applet in order to associate audio files with quodlibet when I double-clicked from the File Explorer.

**Comment by lazka** [comment]
Thanks. Haven't looked into that, but should be possible.

**Comment by lazka** [comment]
This works in Windows 7 now, not sure about Windows 10

**Comment by lazka** [comment]
Works with Windows 10 as well now :)

**Comment by heri0nd3** [comment]
Thanks.
