### ISSUE TITLE
Programmatically getting library statistics

### ISSUE THREAD

**Issue by ghostwords** [quodlibet/quodlibet#1610]
If I wanted to group songs by year in the UI, I could open the Paned Browser and add a year filter. What if I wanted to export this data (song counts by year) to make a histogram, let's say?

Here's what I got so far messing around in the Python Console plugin:

```python
from collections import Counter, OrderedDict
import json
years = [song.get('date', None) for song in app.library.values()]
print(json.dumps(OrderedDict(sorted(Counter(years).items())), indent=4))
```

This produces output like:

```json
{
    "null": 1172, 
    "1950": 1, 
    "1956": 1, 
    "1959-1964": 28, 
    "1959-1971": 76, 
    "1960": 4, 
    "2004": 508, 
    "2005": 833, 
    "2005-02-15": 1
}
```

Am I on the right track? Can I clean up the dates using the ~year tag somehow? Can I graph the data directly in the console plugin?

Using Quod Libet 3.4.0.-1 on Ubuntu 14.04.

**Comment by declension** [comment]
That looks fine to me, and yes you can use the `~year` tag. Note you can also use the callable nature of `Song` objects, and you can iterate over the library directly too,. so that line becomes just:

```python
years = [song('~year') for song in app.library]
```

Meanwhile if there are any feature requests here let us know; assuming not, I'll mark this issue as closed.

**Comment by ghostwords** [comment]
Cool, thank you! I dumped the years to a text file and fed that to [histogram.py](https://github.com/bitly/data_hacks), setting the number of histogram buckets equal to the number of years.
