### ISSUE TITLE
Tag editor inconsistencies

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1611]
So this doesn't get lost.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=784934

And another one I noticed:
- Two songs, one has a tag (shows missing from one)
- Click write icon (missing gets removed)
- Revert. Missing still no there.

One question I had during rewriting the tag editor code recently. Is the write icon used by anyone? And if yes, what are the use cases?

**Comment by declension** [comment]
Lol, _another_ UI feature I didn't know about it. I never use it, that's for sure.

**Comment by lazka** [comment]
Good to know. So maybe remove it and revert back the part mentioned in the debian bug report.

**Comment by davidSchlosser** [comment]
I use the write icon to indicate if an edit can/can't be made depending on
file permissions.

**Comment by frestr** [comment]
With 5ea9f19acbe159487ee3ef551a90345a02580766 both this case (which was already fixed in 1983af31f4161325f6c6432494eb97507e2fa804) and the case mentioned in #2686 should work, so I think we can close this now.
