### ISSUE TITLE
Files removed from library when volume was not mounted

### ISSUE THREAD

**Issue by Konzertheld** [quodlibet/quodlibet#1615]
Original discussion: https://groups.google.com/forum/#!topic/quod-libet-development/dXGOPSuE2sw

I recently killed half of my library by accidentally starting Quod Libet when the drive my music is on was not mounted. Apparently files that are not found are interpreted as deleted songs - and therefore all metadata is killed.

I read those files should be hidden, but the list of hidden files is empty.

QuodLibet 3.4.-1 on Linux Mint 17.1

**Comment by urielz** [comment]
I think this can be closed now. At least it is not an issue on QL 3.9.1 OS X 10.11.6.

**Comment by Konzertheld** [comment]
I can indeed confirm this issue has been fixed.
