### ISSUE TITLE
record radio stream in mp3 file

### ISSUE THREAD

**Issue by fontealpina** [quodlibet/quodlibet#1617]
Is possible to record the radio stream as mp3 file? 
Actually I don't find plugins to do that. 
If this feature isn't already implemented, I could write a plugin myself, so I was wondering how to catch the radio stream with a plugin and if there is a plugin that I can take as example?

**Comment by lazka** [comment]
There isn't. And there is no easy way to implement it as a plugin.

The easiest is probably to write a plugin which downloads them separately (independent of what QL is playing)

You can save the active (MP3) stream using GStreamer (hit ctrl+c to stop recording):

gst-launch-1.0 -e souphttpsrc location="$(quodlibet --print-playing '<~uri>')" ! icydemux ! mpegaudioparse ! filesink location=stream.mp3

**Comment by lazka** [comment]
You can also have a look at streamripper.

[0] http://streamripper.sourceforge.net/

**Comment by CreamyCookie** [comment]
And then you could start it with the custom commands plugin. 

Works on Linux (add to list in `.quodlibet/lists/customcommands.json` :

```json
    "Record Stream": {
        "name": "Record Stream",
        "command": "x-terminal-emulator -e wget",
        "parameter": "",
        "pattern": "<~filename>",
        "unique": false,
        "max_args": 1
    }
```
