### ISSUE TITLE
ZIP Export Plugin

### ISSUE THREAD

**Issue by marcelpaulo** [quodlibet/quodlibet#1619]
Is there a tag that expands to the name of the playlist currently playing ? I search the docs as well as this issue tracker quite carefully but couldn't find it.

Why do I need it ? I have a script, [m3uz](http://paste.ubuntu.com/11344552/), that zips an M3U playlist. I would like to use it within plugin `Custom Commands` to zip the playlist currently playing (of course, I would have to adapt `m3uz` to parse QL playlists). To implement that, I would need a tag that expands to the current playlist name.

**Comment by lazka** [comment]
The only thing playlist related we have is:

* under ~/.quodlibet/playlists you find the files lists
* there is a playlist export plugin, exporting to m3u (you could adjust it to zip?)
* there is a "~playlists" tag which gives you the lists the song is part of (0 or more)

Why do you want to zip an m3u?

**Comment by marcelpaulo** [comment]
> Why do you want to zip an m3u?

To send the playlist files to someone. I do that all the time. I wanted to automate the process of creating the zip file. I already do that, for instance, to zip an album, also to send to people: I created a very simple script that, given an album directory name, it zips it with the artist name as containing directory; I created a command under `Custom Commands` that calls it, so that I can zip any album I'm currently listening to. 

Thanks for summarizing everything that QL exposes about playlists: it confirms what I had already discovered myself.

**Comment by lazka** [comment]
Ah, you mean zip the songs. I guess we can create a plugin which creates an archive of selected songs with a tag based hierarchy +  maybe cover art. Would that help you?

**Comment by marcelpaulo** [comment]
This reminds me: I **must** learn Python. 

But if there's no tag exposing the current playlist, I still wouldn't be able to archive the songs. 

Regardless, a plugin as you outlined would be extremely useful.

The core need behind all this is: some kind of mechanism to select songs and export the corresponding sound files to the filesystem. I could do that with Amarok 1.4, by manually creating a device which mapped to a particular subdirectory. I haven't found a straightforward way of doing that with **any** player since then. QL is the one that comes nearest, thanks to the `Custom Commands` plugin.

**Comment by lazka** [comment]
You'd have to select a playlist or any set of songs and select a plugin doing the export through the GUI.  Do you prefer the songs being rearrange based on some pattern, or based on their actual paths, or both?

Btw. you can also DnD a playlist (or any set of songs) to your file manager and it will copy them there (losing the directory hierarchy)

**Comment by marcelpaulo** [comment]
> Do you prefer the songs being rearrange based on some pattern, or based on their actual paths, or both?

For playlists, it would make sense to respect the physical order of the songs within it. I do that in my script, numbering the songs not according to their track numbers from their albums, but relative to their position within the playlist.

For anything not playlists, for me it would make sense to order on (discnumber, track).

QL is fabulous in the sense that it caters both for disorganized people, that most likely will always ever use the `Search library` view, all the way to obsessively organized people like myself who keep a very strict and adstringent order on the tags. And it's interesting how each each of QL's views has its inner logic, very orthogonal and clean. I can say I have tried all available audio players/organizers for Linux, and QL is hands down the only one where you can clearly see a logical guiding principle stitching together all its interface elements — there's rigorous logic behind all QL interface decisions, and this glows.

> you can also DnD a playlist (or any set of songs) to your file manager and it will copy them there 

Super ! I didn't know that. It works beautifully ! I'll sure be using this ! Thanks for the precious tip !

**Comment by lazka** [comment]
> For playlists, it would make sense to respect the physical order of the songs within it. I do that in my script, numbering the songs not according to their track numbers from their albums, but relative to their position within the playlist.
> 
> For anything not playlists, for me it would make sense to order on (discnumber, track).

OK, so something like two menu items with each a configurable pattern:

"ZIP Export  -> Ordered Playlist"
 ```. <artist> - <title>``` resulting in ```42. Artist - Title.ext``` (disallowing directories)

If we manage to make it work together with the playlist plugin system we can suggest a filename based on the playlist name.

"Zip Export -> Song Tree"
```<albumartist|<albumartist> - ><album>/<discnumber|<discnumber>.><tracknumber>. <title>```
resulting in ```Artist - Album/01. Title.ext```

**Comment by declension** [comment]
I'm a bit confused by what this issue (_HOWTO get the name of the playlist currently playing_) is now about.

The use-case (compressing selections of songs for sending, etc) sounds very similar to the one I had when writing the custom commands plugin, so I guess naturally to me this sounds closer to potential improvements there, e.g. a few virtual tags for the patterns, stdout redirection (with `>file` in the command maybe), or file output support, possibly including using it with some external scripts for this particular request.

(But maybe I've misunderstood the current idea)

**Comment by marcelpaulo** [comment]
@lazka, I'm speechless: you read my mind, and made it much much better: that covers everything I had in mind.

**Comment by lazka** [comment]
@declension there are some advantages to a standalone plugin like easier config and error/progress reporting. Improvements to the custom command plugin or predefined examples are of course welcome.

**Comment by declension** [comment]
Yeah, fair enough. I guess it brings back my concerns over plugin bloat - by numbers (>60 currently), not average size... but perhaps the solution to _that_ is the issue somewhere (can't seem to find it) about organising plugins by category in the various UI widgets.

**Comment by declension** [comment]
@marcelpaulo FYI playlist meta-tags and `PLAYLIST` substitution variable are all now (as of d86c13803ff24a45acec20d1a5793c5e9c42594c) supported in Custom Commands - see details in #1685

**Comment by marcelpaulo** [comment]
Hey, fabulous, thank you so much, @declension !

**Comment by CreamyCookie** [comment]
@marcelpaulo There's also now an "Export Playlist to Folder" plugin.

**Comment by marcelpaulo** [comment]
I've used it quite extensively, @creamycookie

**Comment by CreamyCookie** [comment]
Great to hear =)
