### ISSUE TITLE
OSX: Unable to play Musepack files

### ISSUE THREAD

**Issue by mdio** [quodlibet/quodlibet#1621]
Using Quodlibet 3.4.0_1 to play a Musepack file (stream version 7) on Mac OS X 10.10.3 leads to this error message:
```
Playback Error
No GStreamer element found to handle media format. Media format: Musepack (MPC) decoder.
```

Since the About dialog as well as the Quodlibet homepage lists Musepack as supported I think that this is a bug.

**Comment by lazka** [comment]
The newest bundle should be able to play mpc sv7 files.
sv8 support is missing due to https://bugzilla.gnome.org/show_bug.cgi?id=732682

**Comment by lazka** [comment]
upstream bug got fixed, so sv8 will be supported when gstreamer 1.6 is out, which shouldn't take long I guess. Since this bug report is about sv7 and that should work now -> closing.

Thanks.

**Comment by mdio** [comment]
Sorry for the late reply but for further reference I can confirm that Quod Libet 3.5.1 with GStreamer 1.6.0.0 plays Musepack SV7 and SV8 just fine.
Thanks a lot!
