### ISSUE TITLE
Sync MTP device 

### ISSUE THREAD

**Issue by CParatschek** [quodlibet/quodlibet#1622]
Hi!

I want to see my Nexus 5 in Quodlibet and sync complete playlists to the device.

For transferring a lot of songs it is a hassle to move folders, would be way more convenient to make a playlist in Quodlibet, connect the phone and move the complete playlist over. Rhythmbox and others can do that too.

This might be a feature request or I just missed something but I was not able to find it on the internet.

Kind regards,
Christian

**Comment by lazka** [comment]
Our device support is gone now. It's unclear atm if and in which form it will come back. Sorry :/

**Comment by chomskysfavefive** [comment]
Any current plans to bring it back? That's currently the only feature that's keeping me on Rhythmbox. I like the look and feel of Quod Libet much more.
