### ISSUE TITLE
Check tag internal categorisations

### ISSUE THREAD

**Issue by declension** [quodlibet/quodlibet#1631]
Looking at [`_TAGS`](https://github.com/quodlibet/quodlibet/blob/master/quodlibet/quodlibet/util/tags.py#L59), it seems to me that a few tags are mis-categorised, perhaps, or the docs are outdated, or I'm just confused (or, most likely, some combination of these)

We can add / remove from this list, but it's a good discussion focus.

### Not marked as `internal`
 * `filesize`. The [docs](http://quodlibet.readthedocs.org/en/latest/guide/tags/internal_tags.html)  even have this as internal
 * `bitrate` (docs have it under [numeric](http://quodlibet.readthedocs.org/en/latest/guide/tags/internal_tags.html#numeric-tags), which is under internal - the first confusion perhaps?)
 * `length` (not sure about this - it's computed at file load; does that not make it internal?)

### Marked as `internal` but perhaps shouldn't be
* `rating` (though some layers of translation have to happen here). It's definitely editable though. I guess the problem is there are both `~#rating` and `~rating` (which is much more like an internal tag perhaps, but then `filesize` gets translated to a human-readable format before viewing)

**Comment by lazka** [comment]
I did rewrite that code last year adding more categories with the goal to remove all hardcoded tag lists in the code, but never finished, so it's probably just wrong or the category description/semantics need to be refined.

**Comment by lazka** [comment]
Some docs improvements were made in c6ec6226db37d647e61a172ec597aed00f201ab4

This was more of a naming confusion: internal here just means ~foo, numeric means ~#foo while internal in the docs describes both.

**Comment by declension** [comment]
Thanks
