### ISSUE TITLE
New logo(s)

### ISSUE THREAD

**Issue by Inoki** [quodlibet/quodlibet#1633]
Hi,

I wanted to contact the devs of QuodLibet in order to show them a logo design I've been working on (and am still improving), but there's no email or other form of getting in touch.

I was re-directed here to open an issue regarding this.

**Comment by declension** [comment]
Thanks, always good to have people keen to help out.

If you have something to upload please do so - I've updated the title of this issue accordingly. If you want to PM me do so, but as a community-driven project with many contributors past and present (mainly past), we prefer open discussions. This is either on the mailing list (though as you saw it doesn't get much traffic), on IRC, but easiest probably here on Github.

**Comment by Inoki** [comment]
This is a rough draft of what I had in mind. I didn't want to divert from the original icon too much as I consider it an established brand but at the same time I felt it needed more love.

If it's not OK with the shaded look I could always go for something much more simpler, 2D w/ or w/o shading, similar to Material Design.

![1_001](https://cloud.githubusercontent.com/assets/3719869/8024276/299ae20a-0d2e-11e5-9be7-0b592736f48c.png)

**Comment by pschwede** [comment]
Sorry but this looks like a 2000s tribe tattoo. Not very iconic for flat designs, too.

**Comment by Inoki** [comment]
Well, since as it was said, this is a community project and as such there is no obvious "chain of command" I don't know who to interview sort of about what would be the good way to go, so I was just shooting out in the dark to get feedback, but calling it a "tribe tattoo" is very much misplaced.

**Comment by pschwede** [comment]
It's not that hard. Here, I've started the most simple version of a consensus tool (etherpad): https://etherpad.mozilla.org/6b3XqTCfK0

We could use it to gather opinions and "demands" of the "client".

**Comment by Inoki** [comment]
Thanks for that on-line questionnaire. I will add my own questions that would help me, or anyone else who would like to contribute to the project.

**Comment by pschwede** [comment]
I'm very thankful for your afford. I thought about the logo design quite some time but didn't want to start this on my own.

**Comment by plsng** [comment]
I like the current icon, it's timeless. Your proposed design doesn't look too bad, but it rides on a trend that will disappear in a few years (from the moment people realize long dropshadows are actually really ugly; remember when making everything look as 'real' as possible was the hype?), and then what? Quod Libet / Ex Falso will be stuck with an icon that doesn't fit with whatever trend is the next big thing at that point, and will need a new icon again, or revert to the currect icon, in which case there was never a reason to switch.

Besides, people who don't like the icon can always change it in many ways, by simply replacing the relevant icon files on their system, by using different iconsets (which is what I assume most people looking for similar icons everywhere use) or even by forking this project. I don't think an icon change is necessary, or even a good idea.

**Comment by Inoki** [comment]
The "logo attempt" was really just a shot in the dark. I didn't have any info to begin with. There's a partial questionnaire set up with the link in the thread, but you guys need to consider first if you want a re-design or no.

To me, it was painful to look at the same icon, as I don't consider it enough, so I came up with the suggestion.

**Comment by pdesanex** [comment]
I think the old logo is quite iconic. IMHO, only the drop shadow, the shading and the slightly undefined shape are a bit problematic. Here's my attempt:

![ql](https://cloud.githubusercontent.com/assets/6173038/8263288/77baebce-16d9-11e5-984c-e7cdebd0c049.png)

**Comment by Inoki** [comment]
That's very much the same with slight, from the first look invisible changes.

My point was to bring it somehow to life with a visible change that can be noticed immediately.

**Comment by pdesanex** [comment]
Yes, I was aiming for subtle changes only, in order to keep things recognizable. Personally, I like the musical note analogy very much - its a clever and simple idea. To emphasize the concept, I tried to clean it up and push it a bit closer to actual musical typography.

Perhaps some color could help to bring it to life? Just some random picks:
![ql3_64](https://cloud.githubusercontent.com/assets/6173038/8266549/3a4de416-1734-11e5-840d-7896d66b9f48.png)  ![ql4_64](https://cloud.githubusercontent.com/assets/6173038/8266602/8ae07710-1737-11e5-8d70-f83505159daa.png)  ![ql5_64](https://cloud.githubusercontent.com/assets/6173038/8266604/b7d6463c-1737-11e5-87ef-1756a11bdf2e.png)  ![ql6_64](https://cloud.githubusercontent.com/assets/6173038/8266605/bd6e0706-1737-11e5-9785-324bdccc5489.png)

I think it would make sense to stick to the current 'brand identity', to keep things recognizable. But, of course, I'd also be interested in new concepts. I'll have a look at your questionnaire.

Keep in mind, since Quod Libet and Ex Falso are so closely related we would probably need matching logos for both of them.

**Comment by inversesandwich** [comment]
I don't think we need a new logo really.

@Inoki I really don't like your design, it hearkens back to the Windows XP theme.

@pdesanex I would personally move away from any specific colour, there are many different themes and operating systems the QL supports and no matter what colour you choose there will be a theme it doesn't go with.

**Comment by Inoki** [comment]
Since more people say it's not needed or do not want a change I decided not to take part on this any more.
