### ISSUE TITLE
Option to get current searchbar query from command line

### ISSUE THREAD

**Issue by joshua-paddle** [quodlibet/quodlibet#1634]
The argument --query= can set the query, but there is no way to get it from the command line.

There should be, a) because it would be useful and b) because it is logical that every setter should have an associated getter.

**Comment by declension** [comment]
The first question is: _which_ query? I'm assuming you're referring to the _primary_ browser's search query, _if such a thing exists_. 

Remember browsers like _Disable Browser_, _File System_, _Audio Feeds_ and _Media Devices_ don't (currently) have a notion of a text query, so this proposed command would have to either error or return an empty response.

What about if there are several browsers open, and one of the secondary ones _does_ have support querying? My gut feeling would be to ignore all secondary browsers, but it's not the only choice.

**Comment by joshua-paddle** [comment]
I'm referring to the query that gets set, when you call "quodlibet --query=<str>", whichever query that may be. This commands puts <str> into quodlibet from the command line; but there is no command to get <str> from quodlibet to the command line.

Ask: what is it that gets set when you run --query? Whatever that is, that is being set, is what should be returned by the getter.

**Comment by declension** [comment]
Thanks. 

### Current `--query` behaviour
I've checked the code.  `--query` pushes command `query` to the processor, whose registered handler sets the query text, _if supported_ in the _primary_ (main) browser. 

### Potential Implementation
A bit harder - quick look indicates there is no current general purpose support for (IIRC the filtering interface has always been forms of write-only, and "is x supported"). It probably wouldn't be too hard to add a read "interface" (method, really) into the Browser object hierarchy and implement where relevant (Search, Album browsers, Playlist Browser etc).

#### Background filter
The other problem here is: what to do about the global (aka background) filter. Two options come to mind
* Blindly ignore it, as many people don't use / understand it.
* The command output could reconstruct the syntax of the QL query of the conjunction (`and`) of this with the returned browser query, e.g. `&(~format=!wav, artist=James Brown)`

**Comment by lazka** [comment]
@joshua-paddle: Why do you think it would be useful?

**Comment by joshua-paddle** [comment]
@lazka Three reasons. Firstly, because if it is not too hard to do, it just seems weird to have a setter without a getter. Second, it allows contingent automation of alterations to the search queue, and finally because it allows the search to be interactively modified remotely (the main one).

I use quodlibet because of the sophistication of the search, that essentially allows on-the-fly definition of dynamic playlists (i.e. "all of artist X except song Y, plus songs A, B, C, and any of genre Z by artist W"). The problem is, if I have a big search query defined, and I want to make a small change, I have to either type out the whole query again, or open up the graphical window, which means using my mouse. I would much rather be able to do something like "quodlibet --query=$(quodlibet --show-query | sed 's/artist/otherartist/')", which is easy to do, and a lot faster and less likely to break my chain of thought then using my mouse is.

Allowing the search bar to be extracted, also makes it easy to adjust remotely - for instance, if I have quodlibet running on my desktop, and I'm working in the other room on my laptop - if I want to change the search, it is much easier to send a quick ssh command then it is to manually change it, but I currently don't have a quick way to check what the search currently is. Or if I wanted to make a plugin to add the search bar to another window, e.g. firefox, or to make it available to access through a webpage on my lan.

Come to think of it, I actually can't think of any case where I would want this ability, that cannot be solved equally well by storing the current search in local memory. So strictly speaking, I guess it's not actually necessary - it only becomes an issue if you might have two processes both modifying the search bar, or if you want to make a tool that monitors the search state in the background, which might be interesting but to be fair is not that useful.
