### ISSUE TITLE
Tumbleweed repository

### ISSUE THREAD

**Issue by plsng** [quodlibet/quodlibet#1635]
Was the openSUSE Tumbleweed repository for QL/EF recently removed? Could it be reinstated? I assume it offers the same files as the 13.2 repository anyway, but still. If not, it should probably be removed from the readthedocs website: https://quodlibet.readthedocs.org/en/latest/downloads.html#opensuse

**Comment by lazka** [comment]
The build is failing currently: https://build.opensuse.org/package/live_build_log/home:lazka0:ql-unstable/quodlibet/openSUSE_Tumbleweed/x86_64

Thanks, I'll have a look

**Comment by lazka** [comment]
Please try now

**Comment by plsng** [comment]
Thanks, seems to work now!

**Comment by lazka** [comment]
Thanks for reporting.
