### ISSUE TITLE
Support MusicBrainz Picard Last.fm.plus extra tags (MP3/ID3, Ogg, FLAC)

### ISSUE THREAD

**Issue by Moonbase59** [quodlibet/quodlibet#1638]
I'm running QuodLibet 3.4.1 (stable) on Ubuntu Studio 14.04.2 LTS and miss the possibility to show/edit any ID3v2.3 comment fields as stored by MusicBrainz Picard's "Last.fm.plus" plugin.

In QL Search, I'm trying as follows (example):

```
comment::Songs-DB_Occasion = Work
comment:Songs-DB_Occasion = Work
```

I DO have songs with these tagged, and they're shown just fine in Mp3tag, for instance.

Picard mainly sets the following, but it'd be nice to access _all_ COMM fields by description:

```
COMM Songs-DB_Custom1
COMM Songs-DB_Custom2
COMM Songs-DB_Custom3
COMM Songs-DB_Custom4
COMM Songs-DB_Occasion
```

The song's mood seems to be okay, at least for ID3v2.3 and FLAC: With ID3v2.3, I use a TXXX:Mood for that, which is MOOD in FLAC. Hopefully (didn't test yet) QL will use TMOO for ID3v2.4.

I think many of us are using MB Picard nowadays, so it'd be great to be able to use these. Or maybe I'm just doing something wrong?

**Comment by lazka** [comment]
This is tracked in #48
