### ISSUE TITLE
Not all MusicBrainz/Picard tags shown/editable – What happens on save?

### ISSUE THREAD

**Issue by Moonbase59** [quodlibet/quodlibet#1639]
I just realized that apparently not all tags are shown and/or editable in QL/EF. Using Ubuntu Studio 14.04.2 LTS and QL 3.4.1.

I'd much like to have *all* tags shown, and (well, most of them) editable.
Being quite new to QL/EF, I didn't dare to save … except from having everything converted to ID3v2.4 (which I cannot use), **what will happen with the tags not shown? Will they be deleted?**

Here is a fresh sample from yesterday, tagged using MusicBrainz Picard v1.3.2 (plugin Last.fm.plus enabled), and what QL and Mp3tag show (I trust Mp3tag a lot, that's why I have it running under Wine still):

![screenshot - 24 06 2015 - 11 23 11 - mp3tag tags shown](https://cloud.githubusercontent.com/assets/3706922/8326930/e8eca8ee-1a64-11e5-989e-fd128e0d440a.png)
Mp3tag result

![screenshot - 24 06 2015 - 11 22 36 - quodlibet tags shown](https://cloud.githubusercontent.com/assets/3706922/8326936/f81be0be-1a64-11e5-9b75-0b879ad44434.png)
QuodLibet result

As you can see, I even still use the old *MusicIP Mixer* … even have a (virtual) Windows box set up for that … one of the reasons why ID3v2.4 ist, unfortunately, still out of reach for me.

Edit: Oops, *can't see*, wrong screenshot. MusicIP introduces two very long TXXX frames "MusicMagic Data" and "MusicMagic Fingerprint" in ID3, corresponding values in Vorbis Comments (FLAC). Here's another screenshot (from MP3 Diags) that shows a MusicIP'ed file:

![screenshot - 24 06 2015 - 11 49 46 - mp3 diags tags shown](https://cloud.githubusercontent.com/assets/3706922/8327269/5a649fde-1a67-11e5-9e6a-f633545d69f8.png)

**Comment by lazka** [comment]
The tags not shown will not be deleted. We ignore them during reading/updating the file. Everything will be updated to id3v2.4.

For everything else see https://github.com/quodlibet/quodlibet/issues/48#issuecomment-80725764
