### ISSUE TITLE
Crash when applying ReplayGain to many songs

### ISSUE THREAD

**Issue by Screwtapello** [quodlibet/quodlibet#1644]
Steps to reproduce:

1. Have many songs in your library (I have nearly 15,000)
1. Select all
1. Right-click → plugins → ReplayGain

Expected results:

* Some kind of confirmation dialog

Actual results:

* "An exception has occured in Quod Libet."

The dialog mentions the phrase "format requires a mapping", and has a traceback that points to `quodlibet/qltk/songsmenu.py` line 63, which looks like this:

        title = ngettext("Run the plugin \"%(name)s\" on %(count)d album?",     
                         "Run the plugin \"%(name)s\" on %(count)d albums?",    
                         count) % (plugin_name, count)                          

Like the message says, the text here uses named parameters but the code tries to substitute in a tuple. I'm guessing it should look something like this:

        title = ngettext("Run the plugin \"%(name)s\" on %(count)d album?",     
                         "Run the plugin \"%(name)s\" on %(count)d albums?",    
                         count) % {"name": plugin_name, "count": count}

**Comment by declension** [comment]
Thanks for the report.

This was fixed in April with revision ccf8a9de283054aedd353281c6cec542125d624d as part of #1578.

Please update to a newer version of QL (see [downloads](https://quodlibet.readthedocs.org/en/latest/downloads.html)).
