### ISSUE TITLE
Make Playlist Browser persist the user-defined order of its playlists

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1645]
> If I create a few playlists, they appear in the playlist browser in
> the order they are created. If I close QL and restart it, the
> playlists appear in alphabetical order in the browser.

See https://groups.google.com/forum/#!topic/quod-libet-development/i9tzsT8U0Lo

**Comment by will-ca** [comment]
They are reorderable and the order does persist though?

Click-and-drag on the items reorders them, and the new order is reflected instantly in `~/.quodlibet/playlists`.

**Comment by declension** [comment]
@will-ca this is a confusing title / issue. I've edited the original to include the quote and will find a better title

**Comment by declension** [comment]
Can't reproduce the original bug, and the bigger issues are tracked elsewhere, so closing
