### ISSUE TITLE
Asked me to let y'all know, but kept on playin'

### ISSUE THREAD

**Issue by charlespugh** [quodlibet/quodlibet#1647]
I had the Equalizer plugin open.

=== SYSTEM INFORMATION:
Quod Libet 3.4.1
Mutagen 1.29
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] linux2
Platform Linux-3.13.0-55-generic-x86_64-with-Ubuntu-14.04-trusty

=== STACK TRACE
Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/quodlibet/qltk/quodlibetwindow.py", line 976, in __song_ended
    if song and active_filter and not active_filter(song):

  File "/usr/lib/python2.7/dist-packages/quodlibet/browsers/media.py", line 334, in active_filter
    device = model[iter][0]

  File "/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py", line 764, in __getitem__
    aiter = self._getiter(key)

  File "/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py", line 752, in _getiter
    aiter = self.get_iter(key)

  File "/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py", line 786, in get_iter
    path = self._coerce_path(path)

  File "/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py", line 761, in _coerce_path
    return TreePath(path)

  File "/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py", line 1109, in __new__
    path = ":".join(str(val) for val in path)

TypeError: 'NoneType' object is not iterable

=== LOG:
D: 593.22: PlaylistModel.set: Done filling model.
D: 707.41: PlaylistModel.set: Clearing model.
D: 707.41: PlaylistModel.set: Setting 2622 songs.
D: 707.44: PlaylistModel.set: Done filling model.
D: 708.17: PlaylistModel.set: Clearing model.
D: 708.18: PlaylistModel.set: Setting 90 songs.
D: 708.18: PlaylistModel.set: Done filling model.
D: 708.79: PlaylistModel.set: Clearing model.
D: 708.79: PlaylistModel.set: Setting 84 songs.
D: 708.79: PlaylistModel.set: Done filling model.
D: 709.44: PlaylistModel.set: Clearing model.
D: 709.44: PlaylistModel.set: Setting 84 songs.
D: 709.44: PlaylistModel.set: Done filling model.
D: 711.93: PlaylistModel.set: Clearing model.
D: 711.93: PlaylistModel.set: Setting 84 songs.
D: 711.93: PlaylistModel.set: Done filling model.
D: 712.60: PlaylistModel.set: Clearing model.
D: 712.60: PlaylistModel.set: Setting 82 songs.
D: 712.60: PlaylistModel.set: Done filling model.
D: 713.34: PlaylistModel.set: Clearing model.
D: 713.34: PlaylistModel.set: Setting 82 songs.
D: 713.34: PlaylistModel.set: Done filling model.
D: 729.78: GStreamerPlayer.go_to: Going to <GtkTreeIter at 0x69d4980>
D: 729.78: PlaylistMux.go_to: Told to go to <GtkTreeIter at 0x69d4980>
D: 729.78: PlaylistModel.go_to: Told to go to None
D: 729.78: QueueModel.go_to: Told to go to <GtkTreeIter at 0x69d4980>
D: 729.78: GStreamerPlayer._end: End song
D: 729.79: util.cover.manager.run: Found local cover from FilesystemCover
D: 729.79: GStreamerPlayer._end: Next song
D: 729.88: SongFileLibrary._changed: Changing 2 items.
D: 729.88: qltk.completion.__update_song: Updating tag model for 2 songs
D: 729.88: qltk.completion.__update_song: Done updating tag model for 2 songs
D: 871.77: config.save: Writing config...
D: 871.87: library.save: Saving all libraries...
D: 871.87: SongFileLibrary.save: Saving contents to '/home/chas/.quodlibet/songs'.
D: 087.04: player.gstbe.player.__about_to_finish: About to finish (async)
D: 087.04: player.gstbe.player.__about_to_finish_sync: About to finish (sync)
D: 087.04: player.gstbe.player.__about_to_finish_sync: Select next song in mainloop..
D: 087.04: player.gstbe.player.__about_to_finish_sync: ..done.
D: 087.04: player.gstbe.player.__about_to_finish: About to finish (async): setting uri
D: 087.04: player.gstbe.player.__about_to_finish: About to finish (async): done
D: 088.06: player.gstbe.player.__message: Stream changed
D: 088.06: GStreamerPlayer._end: End song
D: 088.06: util.cover.manager.run: Found local cover from FilesystemCover
D: 088.07: GStreamerPlayer._end: Next song
D: 088.11: SongFileLibrary._changed: Changing 2 items.
D: 088.11: qltk.completion.__update_song: Updating tag model for 2 songs
D: 088.11: qltk.completion.__update_song: Done updating tag model for 2 songs
D: 171.77: config.save: Writing config...
D: 171.86: library.save: Saving all libraries...
D: 348.57: player.gstbe.player.__about_to_finish: About to finish (async)
D: 348.57: player.gstbe.player.__about_to_finish_sync: About to finish (sync)
D: 348.57: player.gstbe.player.__about_to_finish_sync: Select next song in mainloop..
D: 348.57: player.gstbe.player.__about_to_finish_sync: ..done.
D: 348.57: player.gstbe.player.__about_to_finish: About to finish (async): setting uri
D: 348.57: player.gstbe.player.__about_to_finish: About to finish (async): done
D: 349.62: player.gstbe.player.__message: Stream changed
D: 349.62: GStreamerPlayer._end: End song
D: 349.67: util.cover.manager.run: Found local cover from FilesystemCover
D: 349.67: GStreamerPlayer._end: Next song
D: 349.77: SongFileLibrary._changed: Changing 2 items.
D: 349.77: qltk.completion.__update_song: Updating tag model for 2 songs
D: 349.77: qltk.completion.__update_song: Done updating tag model for 2 songs
D: 471.77: config.save: Writing config...
D: 471.85: library.save: Saving all libraries...
D: 771.77: config.save: Writing config...
D: 771.85: library.save: Saving all libraries...
D: 772.59: player.gstbe.player.__about_to_finish: About to finish (async)
D: 772.59: player.gstbe.player.__about_to_finish_sync: About to finish (sync)
D: 772.59: player.gstbe.player.__about_to_finish_sync: Select next song in mainloop..
D: 772.59: player.gstbe.player.__about_to_finish_sync: ..done.
D: 772.59: player.gstbe.player.__about_to_finish: About to finish (async): setting uri
D: 772.59: player.gstbe.player.__about_to_finish: About to finish (async): done
D: 773.61: player.gstbe.player.__message: Stream changed
D: 773.61: GStreamerPlayer._end: End song

**Comment by lazka** [comment]
Thanks
