### ISSUE TITLE
Add a keyboard shortcut to add tracks to a default playlist

### ISSUE THREAD

**Issue by spxxxk** [quodlibet/quodlibet#1651]
or custom playlists in general defined by user, like ctrl+p, ctrl+1, ctrl+2 ... 

Displaying that playlist in the main browser and using secondary browsers to populate it would allow users to play tracks from secondary browsers without using the queue, see issue #676.

**Comment by lazka** [comment]
ctrl+1/2 is currently used for ratings

ctrl+p sounds good, question is what is the default playlist? We could use the first one or the one last shown... but that seems a bit confusing/too much magic to me.

**Comment by spxxxk** [comment]
(I doubt it but) would it be possible to add the whole "right-click on selection" floating window to a sub-menu in the "Control" menu ? That way we could set our own keybindings with menu accelerators. Add to playlist, but also plugins, delete tracks ...

As for a single shortcut, I'm good with anything. Could even create a default one called 'queued' or 'current' .. if it doesn't exist.

**Comment by CreamyCookie** [comment]
Maybe users could select a default playlist in the playlist browser where it would be displayed like this:

> listen later
> 57 tracks (1.3 GB / 4:10:58) **(default)**

**Comment by spxxxk** [comment]
Speaking for myself but I now use the queue for that purpose since #676 has been done.

**Comment by declension** [comment]
@spxxxk no real progress and there's an alternative solution now - are you happy to close this one?
