### ISSUE TITLE
-bash: /Applications/QuodLibet.app/Contents/MacOS/run: No such file or directory

### ISSUE THREAD

**Issue by MikeiLL** [quodlibet/quodlibet#1659]
Hi. I'm sure 'm doing something wrong here. The binary version is running on my OSX Mavericks system, but I'd like to get a dev environment working as well.

`./QuodLibet.app/` doesn't exist.
`/Applications/QuodLibet.app/Contents/MacOS` does! However running `/Applications/QuodLibet.app/Contents/MacOS/run quodlibet/quodlibet.py` from the directory above `quodlibet` returns "No such file or directory".

Contents of the directory are: Quodlibet, 	python

Can anyone see what I'm missing?

**Comment by lazka** [comment]
Do you have the latest bundle installed? I added that file in 3.4.1

**Comment by lazka** [comment]
Also the ``./QuodLibet.app/`` assumes you unpack the bundle in the current directory and don't install it. If you want to work with the installed version you can use ``/Applications/QuodLibet.app/...``

**Comment by MikeiLL** [comment]
So I would just download the 3.4.1 version from http://quodlibet.readthedocs.org/en/latest/downloads.html#macosx and install it over my Quodlibet-3.4.0_1.zip version?

**Comment by MikeiLL** [comment]
Yes. Just overwrote the quodlibet in my Applications folder with the most recent and it's running now. There was some output in the terminal when running the setup script:

`2015-08-07 18:01:37.848 python[45278:507] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead. 
W: Could not import dbus-python, which is needed for device support.
W: Could not find libgpod, iPod support disabled.
W: No device backend, Media Devices browser disabled.
/Users/mikekilmer/Documents/Clients/PythonApps/quodlibet/quodlibet/quodlibet/qltk/quodlibetwindow.py:59: Warning: The property GtkCellRendererPixbuf:follow-state is deprecated and shouldn't be used anymore. It will be removed in a future version.
  self._render = Gtk.CellRendererPixbuf(follow_state=True)
(quodlibet:45278): Gtk-DEBUG: Failed to create D-Bus proxy: Could not connect: No such file or directory
Deallocating GtkQuartzStatusIcon`

**Comment by lazka** [comment]
The output is not critical and mostly expected. The "W:" warnings should be fixed by not trying to do those things under OS X. The depreciation warning is fixed in master. The gtk+ warnings need investigating in gtk+ itself.

**Comment by MikeiLL** [comment]
Thanks, Lazka. What do you mean by "not trying to do things under OS X"?

**Comment by lazka** [comment]
I mean we don't need dbus-python, libgpod and udisks under OSX, so the warnings should not be printed there either by just not printing them or not doing the thing resulting in printing them

**Comment by MikeiLL** [comment]
I see, so their only being used in other environments anyway. I don't really understand the relationship between gtk+, quodlibet and my system, but I guess I'll figure it out over time  - sooner if problems arise.

**Comment by lazka** [comment]
Most of the warning should be gone now.

**Comment by Nienkeeijsvogel** [comment]
Hi I have the same issue: 
QuodLibet.app/Contents/MacOS/Contents/MacOS/python*: No such file or directory 
i run:
./Volumes/Quod Libet 4.4.0/QuodLibet.app/Contents/MacOS/run
not the application
