### ISSUE TITLE
Display custom tags in custom headers

### ISSUE THREAD

**Issue by MikeiLL** [quodlibet/quodlibet#1660]
It took me a few minutes (a bunch of times) to (finally) figure out how to get my custom tag ("description") to display in my custom header ("Description"). Finally realized that it was the non-matching *case* of the word that was preventing them getting linked.

Is it likely that folks would want to have multiple tags with the same word capitalized differently or would it make sense to use `if (tag.upper() == header.upper())` or similar to avoid this issue? Looks like the header is displayed using `str.capitalize()`.

**Comment by declension** [comment]
Can you describe what you did exactly? 

I'm assuming it involved editing the visible columns, then adding `Description` under the  _Others_ list, but finding whilst this _looked_ correct in the songlist headers, it didn't show your `description` tag values for songs.

The important thing to remember is that you are adding _tags_ to the headers, not their (looked up, localised, and title-cased) descriptions (try `albumartist`). I see the confusion though here and thanks for the feedback.

### Potential mitigations
1. This should be documented more clearly,  perhaps even in-app (tooltips / labels etc) *and/or*
2. We could perhaps warn when entering non-lowercase tags to this list as well, but I *don't* think we should make all tag handling case insensitive, and I don't see an efficient way of checking for all combinations of tag value capitalisations (especially across locales)

**Comment by lazka** [comment]
Another thing might be to show all colums in the "edit others" window. So it's obvious that the current column names and the tags behind them don't match.

**Comment by declension** [comment]
Yes, so it could become more of an "advanced edit" feature, rather than just editing the "additional" (typically non-standard) ones.

Alternatively (or: as well) the widget could had another (read-only) column for _Column Heading_, naming the current single column as _Tag Name_.

Adding a tag would still be the same user experience, but even clearer what you'll get before you exit the dialog.

**Comment by MikeiLL** [comment]
Thanks for your consideration. I agree that it doesn't make sense to force case insensitivity. Just sent  pr with a new FAQ that would probably clarify the process.

**Comment by lazka** [comment]
@declension adding a second column sounds good

**Comment by lazka** [comment]
some more changes: 2b8f20e8773b9589
