### ISSUE TITLE
Create new people-focused cover-art based Browser

### ISSUE THREAD

**Issue by Lalopx** [quodlibet/quodlibet#1665]
Is there a way to change the album view, or add the option to the right clivk menu?? i would love to help with some coding. I`m in OSX Yosemite using python 3 and PyCharm CE Also, hello to evryone.
Something like this, i would love to help or if anyone would guide me were to start.
Thanks, and hope to start soon.
![musicbee_1567](https://cloud.githubusercontent.com/assets/13641349/9158715/f608062a-3ef1-11e5-89be-44d3f3acac66.jpg)

**Comment by declension** [comment]
Can you be more specific about your feature request? "Artist"  and "Album Artist" are not options, they're tags.

If you mean: can you modify the display in the Album List browser, then yes, click the settings button to the right of the search bar, and choose _Preferences_. Then edit the _Album Display_ to a [tag pattern](http://quodlibet.readthedocs.org/en/latest/guide/tags/patterns.html) that includes any tags you want, including `albumartist` etc.

For work on a cover-grid-style of Browser, see #241 (among others)

For

**Comment by Lalopx** [comment]
Sorry about that, i didnt made myself clear, what I was talking about is to change the atribute, insted of Album list, Album Artist list and insted of the album art maybe get an artist photo. Upon clicking on the artist you get all the albums from that artist, displaying the album art, when clicked you get the songs in that album. Ordered by year for example.

**Comment by CreamyCookie** [comment]
Closing as this is a unclear, noisy feature request and there's the Paned Browser essentially solving the "first artist, then his releases" part.

Also, the Cover Grid Browser (added October 2016) provides a similar view to the screenshot at the top, and you can then search `artist=Paul`.

If anyone stumbling on this, still wants a new browser, please create a new, more specific enhancement request (preferably with mockups).
