### ISSUE TITLE
Editing Unity quicklist for Quod Libet

### ISSUE THREAD

**Issue by CreamyCookie** [quodlibet/quodlibet#1669]
I'd like to edit the Unity quicklist of Quod Libet, preferably via a configuration file in `.quodlibet` or at least in a way that survives updates. I tried editing the `.desktop` file in `~/.local/share/applications`, but this didn't work.

I want to add the following, because these three are my most used browsers (and this way I could, for example, start right with the radio browser opened):

``` ini

[divider1 Shortcut Group]
Name=.....................................
TargetEnvironment=Unity

[PlaylistsBrowser Shortcut Group]
Name=PlaylistsBrowser
Exec=quodlibet --set-browser=2
TargetEnvironment=Unity

[AlbumList Shortcut Group]
Name=AlbumList
Exec=quodlibet --set-browser=4
TargetEnvironment=Unity

[InternetRadio Shortcut Group]
Name=InternetRadio
Exec=quodlibet --set-browser=7
TargetEnvironment=Unity
```

**Comment by lazka** [comment]
We used the quick list in the desktop file before: https://github.com/quodlibet/quodlibet/commit/419db7e46393753bf7782bae7df91c060cfc27cf

Some guesses:

* We use the unity API for the quicklist, so maybe that is replacing your list when QL starts up.
* Asking google suggests that you need to log out and in again to make unity recognize the file changes.
* You should use "quodlibet --run --set-browser=2" which makes QL start if it isn't already.

**Comment by CreamyCookie** [comment]
Thank you! It works now. It seems that you only need to restart Quod Libet for the modifications to show up.

One problem I had, was that they apparently changed the format:

|Old | New|
| ------------- | ----------- |
|X-Ayatana-Desktop-Shortcuts=ELEMENTNAME| 	Actions=ELEMENTNAME;
|[ELEMENTNAME Shortcut Group]| 	[Desktop Action ELEMENTNAME]
|TargetEnvironment=Unity| 	OnlyShowIn=Unity;GNOME; 

I don't know if this would fit in the doc, but I'll leave this here anyway, for everybody who's interested. You have to put the following in a file named `quodlibet.desktop` in `~/.local/share/applications`:

```ini
[Desktop Entry]
Name=Quod Libet
GenericName=Music Player
Comment=Listen to, browse, or edit your audio collection
Exec=quodlibet --run --play-file %u
MimeType=application/x-flac;audio/aac;audio/midi;audio/mp3;audio/mp4;audio/mpeg;audio/mpeg4;audio/mpg;audio/ogg;audio/vorbis;audio/wav;audio/wave;audio/x-aac;audio/x-flac;audio/x-m4a;audio/x-midi;audio/x-mp3;audio/x-mpc;audio/x-mpeg;audio/x-ms-wma;audio/x-ms-wmv;audio/x-musepack;audio/x-oggflac;audio/x-speex;audio/x-tta;audio/x-wav;audio/x-wavpack;audio/x-wma;video/ogg;video/x-ms-asf;video/x-theora;video/x-wmv;
Terminal=false
StartupNotify=true
Type=Application
Icon=quodlibet
Categories=AudioVideo;Audio;Player;GTK;

#http://live.gnome.org/GnomeGoals/NotificationSource
X-GNOME-UsesNotifications=true

Actions=divider1;PlaylistsBrowser;AlbumList;InternetRadio;

[Desktop Action divider1]
Name=----- Browsers -----
OnlyShowIn=Unity;GNOME;

[Desktop Action PlaylistsBrowser]
Name=Playlists
Name[de]=Wiedergabelisten
Exec=quodlibet --run --set-browser=PlaylistsBrowser
OnlyShowIn=Unity;GNOME;

[Desktop Action AlbumList]
Name=Album List
Name[de]=Album Liste
Exec=quodlibet --run --set-browser=AlbumList
OnlyShowIn=Unity;GNOME;

[Desktop Action InternetRadio]
Name=Internet Radio
Exec=quodlibet --run --set-browser=InternetRadio
OnlyShowIn=Unity;GNOME;
```

**Comment by lazka** [comment]
Thanks for documenting this.

I'm wondering what the user case is here as for these actions to be useful the window has to be visible anyway and those things are two clicks away there with the menu bar (especially in newer Ubuntu which switched back to putting menu bars in the application window)?

**Comment by CreamyCookie** [comment]
@lazka It's just easier to reach, and no, the window doesn't have to be visible. And thanks to your suggestion of adding ` --run`, Quod Libet doesn't even have to be started. For example, you may want to start listening to a radio, although you usually use the album list view. (I do, that is.)

Although I guess, if there would be keyboard shortcuts like in Nautilus (or Nemo) to switch between views (<kbd>CTRL</kbd> + <kbd>1</kbd>, <kbd>CTRL</kbd> + <kbd>2</kbd>, ..), it would be unnecessary. Wasn't there somewhere a page in the documentation to add such keys? Can't find it right now.
