### ISSUE TITLE
Doesn't load 500x500 cover, even if using "reload cover"

### ISSUE THREAD

**Issue by CreamyCookie** [quodlibet/quodlibet#1670]
This probably doesn't help, but here's the image anyway.

https://mega.co.nz/#!qUAyWKyL!cyww_-y8rGzxTn5mVZVrv7Pq7JDHCKYVfWYA2rtkXjk

I used mega, because github might change the image which might lead to making the problem not be reproducible. Interestingly, when I put the image in another album folder that had no image and pressed "reload cover" the cover would still not load. Even restarting Quod Libet doesn't work. Other albums covers update just fine.

This is the file structure (via the `tree` command):

```
(2013) Master Of Confusion [Japanese EP]

├── 01 - Empire of the Undead.flac
├── 02 - Master of Confusion.flac
├── 03 - Death or Glory.flac
├── 04 - Lost Angels.flac
├── 05 - The Spirit (live).flac
├── 06 - Wings of Destiny (live).flac
├── 07 - Gamma Ray (live).flac
├── 08 - Farewell (live).flac
├── 09 - Time to Break Free (live).flac
├── 10 - Insurrection (live).flac
├── 11 - Sag Mir Bescheid (Bonus Track).flac
├── folder.jpg
└── Scans
    ├── Back.jpg
    ├── Booklet 01.jpg
    ├── Booklet 02.jpg
    ├── Booklet 03.jpg
    ├── Booklet 04.jpg
    ├── Booklet 05.jpg
    ├── Booklet 06.jpg
    ├── Booklet 07.jpg
    ├── CD.jpg
    ├── front.jpg
    ├── Inlay.jpg
    └── Inside.jpg
```

Need anything else?

**Comment by declension** [comment]
Presumably `folder.jpg` is what you're expecting to be loaded, but isn't?

What is getting loaded instead, if anything?

**Comment by lazka** [comment]
Reported upstream: https://bugzilla.gnome.org/show_bug.cgi?id=753605

**Comment by lazka** [comment]
(Was just fixed upstream)
