### ISSUE TITLE
rating iconography

### ISSUE THREAD

**Issue by urielz** [quodlibet/quodlibet#1674]
I know this is nip-picking but visually the rating of songs/albums is not as clear as it could be in my opinion. I would suggest to replace the 'empty stars' by nothing at all or something less similar to a 'full star' (if loosing the maximum number of stars is an issue), perhaps dots?

**Comment by kaffeeundsalz** [comment]
+1. This is a screenshot of how the current iTunes version does it in OS X Yosemite. Pretty obvious in my opinion.

<img width="1440" alt="bildschirmfoto 2015-08-27 um 13 33 47" src="https://cloud.githubusercontent.com/assets/4942960/9519605/4ea35588-4cc0-11e5-9206-4c24a7ccb787.png">

**Comment by lazka** [comment]
The main reason why things are that way currently:

* We use stars as they are in unicode, fonts have usually glyphs for them. This allows us to just include the rating in text/patterns.
* We use stars for both set/unset state as that makes sure that both glyphs have the same width and text doesn't shift if the rating changes.

The iTunes example isn't doable with what we have I think as the unicode dot glyphs don't align vertically with the stars and as mentioned above the width is different.
We could add some special representation in the song list and menus by drawing things ourself.

The characters used can be changed in the ~/.quodlibet/config file btw. for example to : ⬤ / ◯

**Comment by urielz** [comment]
Thanks for clarification, makes sense.

Using circles now, definitely more clear with the dark theme!

**Comment by brunob** [comment]
Since this can now be changed with advanced preferences plugin, maybe we can close this issue ?

**Comment by declension** [comment]
Sure.
