### ISSUE TITLE
osx: Default Modifier Key should be Cmd instead of Ctrl

### ISSUE THREAD

**Issue by kaffeeundsalz** [quodlibet/quodlibet#1677]
As documented [here](https://quodlibet.readthedocs.org/en/latest/guide/shortcuts.html), Quod Libet uses the `Ctrl` key for most of its keyboard shortcuts, which is totally fine on Linux and Windows. On OS X however, the default modifier key is `Cmd`, as is also documented in Apple's [OS X Human Interface Guidelines](https://developer.apple.com/library/mac/documentation/UserExperience/Conceptual/OSXHIGuidelines/Keyboard.html#//apple_ref/doc/uid/20000957-CH84-SW4).

This means that e.g. for a copy/paste action, OS X users would use `Cmd+C`/`Cmd+V` instead of `Ctrl+C`/`Ctrl+V`. I suggest changing the default key bindings from `Ctrl` to `Cmd`for the Mac build, as this would greatly improve user experience of Quod Libet on OS X.

**Comment by lazka** [comment]
some gtk+ related info: https://unix.stackexchange.com/questions/168505/what-is-primary-for-a-key

**Comment by lazka** [comment]
I haven't looked at the HIG etc so if there are any shortcuts which have a more common alternative on OSX, please post here or open another issue.
