### ISSUE TITLE
iTunes cover provider

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1678]
From what I see iTunes saves covers under ~/Music/iTunes/Album Artwork/Cache/F525F6A6A4A26519

The format used:

https://apple.stackexchange.com/questions/104209/what-can-itc-files-contain-when-not-png-or-jpg

iTunes/iTunes Music Library.xml contains the library. (https://support.apple.com/en-us/HT201610)

The location of the cover is:

Given a "Persistent ID" of a track e.g. "32AD52B669C5BEFF" and a library persistant ID of "F525F6A6A4A26519" the location is

Cache/F525F6A6A4A26519/15/15/14/F525F6A6A4A26519-32AD52B669C5BEFF.itc

15/15/14 are the last three characters of the track ID in reverse converted to decimal.

**Comment by lazka** [comment]
The cover cache only contained covers for things with embedded images. The downloaded ones use IDs which aren't in the exported iTunes library, so no way to find the right one.

Giving up...  https://gist.github.com/lazka/3c3c991fa9031dab89d9

**Comment by kaffeeundsalz** [comment]
This is sad.
