### ISSUE TITLE
playcount/rating bug?

### ISSUE THREAD

**Issue by urielz** [quodlibet/quodlibet#1680]
I have QL installed on a macbook laptop. I plan to migrate my music to an external hard drive so I can also use QL at work (Linux) and at home on a desktop machine (Windows).

My understanding is that as long as the sub key is the same on each QL then the play count and rating is updated automatically. However when I set the same sub key (that I've been using on my macbook) on the Windows machine only a few (around ~10% of the library) songs are updated with the play count and rating. Is the play count / rating stored in the actual files or somewhere else, like the Python dict file?

I would appreciate any feedback on this...

**Comment by declension** [comment]
You have to enable the _Preferences_->_Tags_->_Save Ratings and Play Counts_ (and enter the same email address) otherwise yes they're stored in the pickle (the songs file).

There are  /were occasionally issues about writing the dirty files (though not generally to that extent).

**Comment by urielz** [comment]
Yes, that's exactly what I'm doing. "Save Ratings and Play Counts" is enabled and same email address in used in both QL for OS X and Windows. My collection is in FLAC and I'm using latest build (3.4.1).

I'm happy to do further testings to help pinpoint what it looks like a bug to me. Surprised no one else has encountered this yet though.

**Comment by declension** [comment]
It's definitely felt flakey to me before too in honesty.

**Comment by CreamyCookie** [comment]
@urielz Yep, I have the same problem. At the moment I always use the "Force Write" plugin after having heard an album. It does the job, but it's certainly a hassle.

**Comment by urielz** [comment]
@CreamyCookie Thanks for the suggestion. I'll try it.

**Comment by CreamyCookie** [comment]
@urielz Cool, just tell me if it doesn't work. btw. You have to select the albums or songs for which you want to store ratings / playcounts in the tags, then right click and click on Plugins > Force Write.

**Comment by urielz** [comment]
@CreamyCookie It seems that the Force Write plugin is creating additional tags, in my case was playcount:key & ratings:key (key = the email or whatever you used to save the ratings/playcounts). So it is not really an ideal solution...

I'm curious: do you have your music library on an external HD? Are you loading it on different versions of QL?

**Comment by CreamyCookie** [comment]
Yes, but that's the correct standard for storing ratings in ID3: http://id3.org/id3v2.4.0-frames (search for `POPM` or `4.17.`)

https://picard.musicbrainz.org/docs/mappings/

Yes, I have my music library on an external HDD? No, I'm just using one version.

**Comment by CreamyCookie** [comment]
@urielz I've created a bug report describing what I think needs to happen (saving ratings and playcounts to the tags whenever they change): #1852 

You may close this bug report, if fixing this would cover your problem.

**Comment by urielz** [comment]
@CreamyCookie Yes. Thanks for the bug report, that would fix the issue. I'll close this now.
