### ISSUE TITLE
Double accent ^^ on Win 7 text editor, when QuodLibet launched

### ISSUE THREAD

**Issue by hidebysun** [quodlibet/quodlibet#1681]
Hi

Sorry, 
i'm french, 
and i will try to explain as much as possible, the problem i  met,
even, if i translate with success...
In fact, "all" is in the subject : 
when i writing a mail, for example...or, 
when i enter some informations into field, on a forum, with internet browser, firefox.. 
or again, if i write something into text editor >
a) If QuodLibet is not running, all is quiet well, and i can write for example, this word "bâteau" without any problem. And i can write this word
b) while i write this same word "bâteau", 
if Quodlibet is open, i obten that result : b^^ateau, instead of 'bâteau'...
In fact,
Without QL turning, the word "château", will be wrote : château, ....all is OK
...as it is normal to write this word like this.....with wordpad, or notepad++, or any other program, in one mail with thunderbird ..etc
But if now, i decide to listen music, and then i run QuodLibet, if i try again to write 'chateau', i will obten 'ch^^ateau' 

This was on Windows 7 SP1...
I have a dual boot Win/Mint 17, when i do exactely the same things on Linux, nothing happening, all work well.

Now, you know, for me it was important to make this transmission on this little problem.
Perhaps it will be interesting for you, or important to have that information in your possession, for some reason, 'coding', future programmation..........................

**Comment by lazka** [comment]
See #1168

**Comment by lazka** [comment]
Thanks for the report. As this issue is already known and filed under #1168, I'm closing this.
If you have any further information post them in #1168.
