### ISSUE TITLE
updated greek translation

### ISSUE THREAD

**Issue by vrasidas** [quodlibet/quodlibet#1684]
Finally got around to it.

po file is here:

https://drive.google.com/file/d/0B0gwsg1la8UCcjlYMGJfSWZSSDQ/view?usp=sharing

**Comment by lazka** [comment]
Thanks. Did you have any contact with the previous translator?

**Comment by vrasidas** [comment]
I'm the previous translator >.>

I'll make a new github with my real name. This was a throwaway from years ago...
