### ISSUE TITLE
Custom Commands plugin - add support for playlist name

### ISSUE THREAD

**Issue by Piscium** [quodlibet/quodlibet#1685]
There exists a Custom Commands plugin that enables configuration of commands that act on songs, however that plugin does not support a <~playlistname> tag. Such a tag would be useful to a user that wants to process the '~/.quodlibet/playlists/playlistname' file for whatever reason.

If the  <~playlistname> tag cannot be added to the Custom Commands plugin for architectural and design reasons, I wonder if a new simple plugin that also enables configuration of commands could be created that supports the  <~playlistname> tag. 

Reported for QL 3.4.-1 running on Linux (Fedora 21).

**Comment by declension** [comment]
For clarity, tags are independent of plugins, so adding a tag is universal. There is already the `~playlists` tag that reports what playlists (_plural_ - and comma separated) a song is part of. A singular version doesn't really make sense, but you can of course add a new custom tag.

The only way I see this making sense is adding a [playlist plugin](http://quodlibet.readthedocs.org/en/latest/development/plugins.html#plugin-types) version of the Custom Commands plugin. This could then have access to the name of the plugin, ideally added somehow as a fake tag (e.g. `~playlistname` as suggested), or maybe as another substitution parameter (similar to the `parameter` input field).

**Comment by Piscium** [comment]
A playlist plugin seems a good idea. What would help my use case is that the name of the playlist selected with the mouse gets automatically passed as parameter to my script. For example, while experimenting with the Custom Commands plugin I defined the following command that calls my script:
*konsole --workdir ~/tango/playlists/ --hold -e create-playlist-folder*

If the pattern is <~filename> what gets passed to my script is all the file names of all the songs in the playlist. Instead what I would wish to be passed is the name of the selected playlist like for example with a fake <~playlistname> tag.

I have to say that I really like the idea behind the the Custom Commands plugin, because this plugin is in effect an easy to use gateway to other plugins. Each of the defined commands is in effect another plugin that crucially can be written in any programming language and can be a simple script or a big application. The result is that the capabilities of QL get extended without limit. For example I could define a custom command written in Fortran that fires a rocket to Neptune that carries in its payload all the songs in my playlist!

Also I wonder if as an alternative to another playlist plugin, a generic introspection plugin could not be created, so that for example if the [playlistname] ID was passed to it it would return the name of the currently selected playlist, but in the future could be extended with other IDs. For example the [version] ID could return the QL version. Maybe I am talking nonsense as I don't know the architecture of QL!

**Comment by Piscium** [comment]
Thanks, Nick.
