### ISSUE TITLE
Sample Rate, Bit Depth and Channels

### ISSUE THREAD

**Issue by urielz** [quodlibet/quodlibet#1686]
I haven't found a way to access the sample rate, bit depth and channels of a song in QL. Is there a way to do that? It would be useful to add these variables as internal numeric tags.

**Comment by lazka** [comment]
currently not, but mutagen reads/parses that information in most cases.

Why do you need it?

**Comment by urielz** [comment]
No real need. My collection is in FLAC with various sampling rates/bit-depths. It would just be nice to have that information at hand and be able to filter/search it.

Potentially audiophiles would find it useful as sometimes they have the same album in different formats (CD, SACD, etc) and the best way to differentiate them would be by looking at the sample rate and bit-depth.

**Comment by declension** [comment]
FWIW I find that `~#bitrate` is a good enough substitute (for me), even though it conflates all these variables (arguably in a useful way)

**Comment by lazka** [comment]
While I don't find it that useful either the only downside is memory usage, and that's not that big of a problem nowadays.

Somewhat related: Latest mutagen also can read the lame version and guess if it is VBR/ABR/CBR, maybe add a "~codec" for that?

**Comment by Hunter16g** [comment]
It would be great to have this, bitrate isn't very relevant for lossless files.
IMO the best would be to have ~channels, ~bitdepth and ~samplerate or something like that, instead of one internal tag for all. However I don't know if it's difficult to implement.

**Comment by lazka** [comment]
720b339c306 added `~#channels`

**Comment by lazka** [comment]
#2872 added `~#bitdepth` and `~#samplerate`

**Comment by urielz** [comment]
Thanks @lazka for making this happen! This is awesome :)

**Comment by Hunter16g** [comment]
Thank you !
I've tried adding <~#samplerate> and <~#bitdepth> in the display, but it doesn't return anything. Am I doing something wrong ? The files are in FLAC, quodlibet version is 4.2 development 6ba95ed82
