### ISSUE TITLE
[Plugin][Win7] QLScrobbler not setting offline mode

### ISSUE THREAD

**Issue by TooManyAccounts** [quodlibet/quodlibet#1688]
* What did you try to do?

Attempt to set QLScrobbler to offline mode using the "Offline mode (don't submit anything" checkbox in the plugins interface

* What did you expect to happen?

That the qlscrobbler plugin would be set to offline mode

* What did happen instead?

When I check the plugin agan the "Offline mode (don't submit anything)" checkbox is now unchecked and qlscrobbler is still submitting scrobbles

I checked in the config file and there is a "scrobbler_scrobbler_offline" set to false but I also checked the source for the plugin (and somehow managed to fork qodlibet in the process, sorry) and noticed that the variable for setting the offline state seems to be "scrobbler_offline".

I experimented a bit by editing the config file and first setting "scrobbler_scrobbler_offline = true". This didn't seem to work, or rather it doesn't persist and gets reset when you check the pugin interface.

so I inserted the line "scrobbler_offline = true" and this seems to work, scrobbles are not submitted and the "Offline mode (don't submit anything)" checkbox remains ticked in the interface.

* Which version of Quod Libet?

3.4.1, Windows installer version, installed to hard disc

* Which operating system including version (Ubuntu 14.04, Win7, Debian sid, ...)?

Windows 7 x64 SP1,  all security updates

EDIT: clarified behaviour of variables, more detail on version

**Comment by lazka** [comment]
Thanks
