### ISSUE TITLE
Scrolling problems in Album List mode

### ISSUE THREAD

**Issue by ghost** [quodlibet/quodlibet#1691]
Hi,

The problem is that if the mouse is moving while scrolling through the albums in Album List mode, then the scrolling stops. This gets pretty annoying since you can't scroll without moving the mouse a millimeter. As long as the mouse continues to move then absolutely no scrolling will be done.

Sometimes you need to move the mouse a bit in case scrolling has locked up or press the middle mouse key and try moving again. Overall scrolling is pretty hopelessly broken in Album List mode.

This happens only in Album List mode. Is definitely not a regression, just a bug I encountered since last December but never actually reported and just lived with it. I always compile and install quodlibet from source.
Also bug hasn't been fixed in GTK as every time Debian has updated it it's still present. I can't find if the bug is in GTK or not since I've been unable to find some similar bug elsewhere.

I can't verify if the bug happens in Windows or OSX, I can only confirm it's present under Debian unstable.

**Comment by lazka** [comment]
Is this with a mouse + scroll wheel? I can't move the pointer and scroll at the same time with a touchpad, and can't reproduce with trackpoint+touchpad.

**Comment by atomnuker** [comment]
Yes, this happens with a mouse.
Other GTK3 programs like Transmission do not have that bug, this only happens in QL.

**Comment by lazka** [comment]
OK, thanks. That's probably a side effect of our list tooltips for long rows.

/me has to find a mouse..

**Comment by kaffeeundsalz** [comment]
Just for the record, this doesn't happen in OS X. I tested scrolling through album list with a mouse + scroll wheel while simultaneously moving the pointer. Everything works fine here.

**Comment by lazka** [comment]
I can reproduce with a mouse on linux

**Comment by Hunter16g** [comment]
I have the same problem in album collection, only when an artist (in my case) is expanded to see the albums.

**Comment by lazka** [comment]
You can work around the issue by disabling the tooltips by going to the "Advanced Preferences" plugin and set "Disable Hints" to "true" and restart QL.

**Comment by Hunter16g** [comment]
Thanks for the tip, however it seems that I can't activate the plugin (I can't check the box).

**Comment by lazka** [comment]
See #1700
