### ISSUE TITLE
crossfeed plugin not loading

### ISSUE THREAD

**Issue by kenden** [quodlibet/quodlibet#1693]
I get the message in the plugin errors page:
Couldn't find GStreamer element 'bs2b'.

Quod Libet 3.4.1
Linux Mint 17.2
Linux 3.16.0-38-generic #52~14.04.1-Ubuntu SMP  x86_64 x86_64 x86_64 GNU/Linux

I tried:
sudo apt-get install libbs2b0
sudo apt-get install bs2b-ladspa

possibly related to:
https://github.com/quodlibet/quodlibet/issues/1266

**Comment by lazka** [comment]
The "bs2b" element is part of GStreamer 1.6 which was released 4 days ago and as far as I can see will be part of the new Ubuntu release next month.
