### ISSUE TITLE
Quodlibet crashes on startup.

### ISSUE THREAD

**Issue by TedTed** [quodlibet/quodlibet#1694]
Hello,

Quodlibet 3.4.1 crashes on startup on my Debian sid¹ after a system update, with what looks like a GtK error:

    File "/usr/lib/python2.7/dist-packages/quodlibet/qltk/x.py", line 355, in do_size_allocate
      ret = Gtk.HPaned.do_size_allocate(self, *args)
    TypeError: argument allocation: Expected Gdk.Rectangle, but got gi.repository.cairo.RectangleInt

it opens a window that tells me to file a bug here², and if I try to discard said window, it immediately reappears. Meanwhile, quodlibet is basically unusable, since the list of songs doesn't appear. The player still works (if I hit play, it start the music as usual).

If there's a quick workaround before this bug is solved, I'm very interested. Have a nice day!

¹Linux K3PO 4.0.0-2-amd64 #1 SMP Debian 4.0.8-2 (2015-07-22) x86_64 GNU/Linux
²dump: http://paste.fulltxt.net/q4l2OVIaD

**Comment by lazka** [comment]
Downgrade gir1.2-gtk-3.0 to 3.16 until python-gi 3.18 is available

**Comment by lazka** [comment]
Debian bugs:

* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=800795
* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=800798

**Comment by lazka** [comment]
This was just fixed in debian sid -> apt update/upgrade
