### ISSUE TITLE
do_size_allocate (line 355) crashes quodlibet

### ISSUE THREAD

**Issue by laurbede** [quodlibet/quodlibet#1695]
=== SYSTEM INFORMATION:
Quod Libet 3.4.1
Mutagen 1.31
Python 2.7.10 (default, Sep 13 2015, 20:30:50) 
[GCC 5.2.1 20150911] linux2
Platform Linux-4.1-2.semplice.1-desktop-amd64-x86_64-with-Semplice-7.0.1-numb

=== STACK TRACE
Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/quodlibet/qltk/x.py", line 355, in do_size_allocate
    ret = Gtk.HPaned.do_size_allocate(self, *args)

TypeError: argument allocation: Expected Gdk.Rectangle, but got gi.repository.cairo.RectangleInt

=== LOG:
D: 821.87: quodlibet.init_backend: Initializing audio backend (gstbe)
D: 822.14: devices.init: Initializing device backend.
D: 822.14: devices.init: Trying 'UDisks2'
W: UDisks2: Could not find 'media-player-info'.
D: 822.14: devices.init: Trying 'UDisks1'
W: UDisks: Could not find 'media-player-info'.
W: Couldn't connect to a device backend.
W: No device backend, Media Devices browser disabled.
W: Could not import python-feedparser. Audio Feeds browser disabled.
D: 822.37: SongFileLibrary.__init__: Initializing SongFileLibrary "filesystem".
D: 822.37: SongFileLibrary.__init__: Using pickling persistence for library "filesystem"
D: 822.37: quodlibet.init_plugins: Starting plugin manager
D: 822.37: quodlibet.init_plugins: Scanning folders: ['/usr/lib/python2.7/dist-packages/quodlibet/ext/editing', '/usr/lib/python2.7/dist-packages/quodlibet/ext/events', '/usr/lib/python2.7/dist-packages/quodlibet/ext/playorder', '/usr/lib/python2.7/dist-packages/quodlibet/ext/songsmenu', '/usr/lib/python2.7/dist-packages/quodlibet/ext/playlist', '/usr/lib/python2.7/dist-packages/quodlibet/ext/gstreamer', '/usr/lib/python2.7/dist-packages/quodlibet/ext/covers', '/home/laurento/.quodlibet/plugins']
D: 822.37: plugins.__restore: Restoring plugins: 5
D: 822.37: PluginManager.rescan: Rescanning..
D: 822.37: ModuleScanner.rescan: Rescanning..
D: 822.88: ModuleScanner.rescan: Rescanning done: 63 added, 0 removed, 11 error(s)
D: 822.88: PluginManager.rescan: Rescanning done.
D: 822.88: PluginManager.register_handler: Registering handler: 'EditTagsPluginHandler'
D: 822.88: PluginManager.register_handler: Registering handler: 'RenameFilesPluginHandler'
D: 822.88: PluginManager.register_handler: Registering handler: 'TagsFromPathPluginHandler'
D: 822.88: PluginManager.register_handler: Registering handler: 'GStreamerPlayer'
D: 822.88: PluginManager.register_handler: Registering handler: 'SongsMenuPluginHandler'
D: 822.88: PluginManager.enable: Enable 'Browse Folders'
D: 822.94: PluginManager.register_handler: Registering handler: 'CoverPluginHandler'
D: 822.94: PluginManager.register_handler: Registering handler: 'PlaylistPluginHandler'
D: 823.24: PluginManager.register_handler: Registering handler: 'PlayOrder'
D: 823.24: GStreamerPlayer.go_to: Going to None
D: 823.24: PlaylistMux.go_to: Told to go to None
D: 823.24: QueueModel.go_to: Told to go to None
D: 823.24: PlaylistModel.go_to: Told to go to None
D: 823.24: CoPool.add: Added copool function <bound method GObjectMeta.__build_model of <class 'quodlibet.qltk.completion.LibraryTagCompletion'>> with id <bound method GObjectMeta.__build_model of <class 'quodlibet.qltk.completion.LibraryTagCompletion'>>
D: 823.86: CoPool.add: Added copool function <bound method SongFileLibrary.rebuild of <SongFileLibrary object at 0x7fb39a624be0 (quodlibet+library+libraries+SongFileLibrary at 0x1973340)>> with id 'library'
D: 823.86: qltk.window.__restore_state: Restore state
D: 823.86: qltk.window.__restore_position: Restore position
D: 823.86: qltk.window.__restore_size: Restore size
D: 823.86: PluginManager.register_handler: Registering handler: 'EventPluginHandler'
D: 823.86: PluginManager.enable: Enable 'Tray Icon'
D: 823.86: PluginManager.enable: Enable 'Notify'
D: 823.90: mmkeys.find_active_backend: Trying to find a mmkeys backend
D: 823.94: qltk.session.init: Connecting with the gnome session manager failed
D: 823.94: CoPool.add: Added copool function <function periodic_config_save at 0x7fb3799d7230> with id <function periodic_config_save at 0x7fb3799d7230>
D: 823.94: CoPool.add: Added copool function <function periodic_library_save at 0x7fb3799d7320> with id <function periodic_library_save at 0x7fb3799d7320>
D: 823.94: quodlibet.main: Entering quodlibet.main
D: 824.19: quodlibet._override_exceptions: Enabling custom exception handler.
D: 825.01: PlaylistModel.set: Clearing model.
D: 825.01: PlaylistModel.set: Setting 23351 songs.
D: 825.10: PlaylistModel.set: Done filling model.
D: 825.11: GStreamerPlayer.go_to: Going to '/home/laurento/media/mp3/_compilations/(various artists) - 13 - experiments in haste (gruppo di pawlowski) (gruppo di pawlowski).mp3'
D: 825.11: PlaylistMux.go_to: Told to go to '/home/laurento/media/mp3/_compilations/(various artists) - 13 - experiments in haste (gruppo di pawlowski) (gruppo di pawlowski).mp3'
D: 825.11: QueueModel.go_to: Told to go to None
D: 825.11: PlaylistModel.go_to: Told to go to '/home/laurento/media/mp3/_compilations/(various artists) - 13 - experiments in haste (gruppo di pawlowski) (gruppo di pawlowski).mp3'
D: 825.19: GStreamerPlayer._end: End song
D: 825.25: util.cover.manager.run: Found local cover from FilesystemCover
D: 825.25: GStreamerPlayer._end: Next song
D: 825.71: qltk.completion.__build_model: Updating tag model for whole library
D: 825.71: SongFileLibrary.rebuild: Rebuilding, force is False.
D: 825.81: SongFileLibrary._changed: Changing 1 items.
D: 825.81: qltk.completion.__update_song: Updating tag model for 1 songs
D: 825.81: qltk.completion.__update_song: Done updating tag model for 1 songs
D: 826.88: qltk.completion.__build_model: Done updating tag model for whole library
D: 826.88: CoPool.remove: Removed copool function id <bound method GObjectMeta.__build_model of <class 'quodlibet.qltk.completion.LibraryTagCompletion'>>
D: 829.51: SongFileLibrary.rebuild: Removing 0, changing 0.
D: 829.51: SongFileLibrary.scan: Scanning '/home/laurento/media/mp3'.
D: 829.82: CoPool.remove: Removed copool function id 'library'
D: 880.84: qltk.window.__restore_state: Restore state
D: 880.84: qltk.window.__restore_position: Restore position
D: 880.85: qltk.window.__restore_size: Restore size
D: 123.95: config.save: Writing config...
D: 123.99: library.save: Saving all libraries...
D: 123.99: SongFileLibrary.save: Saving contents to '/home/laurento/.quodlibet/songs'.
D: 423.95: config.save: Writing config...
D: 423.99: library.save: Saving all libraries...
D: 581.11: CommandRegistry.handle_line: command: focus(*[])
D: 581.11: CommandRegistry.run: Running <function _focus at 0x7fb3799cd050> with params ()

**Comment by laurbede** [comment]
Sorry Lazka,
Apparently same issue as #1694
Gr.

**Comment by lazka** [comment]
Yeah, thanks!
