### ISSUE TITLE
QL 3.4.1 and El Capitan

### ISSUE THREAD

**Issue by urielz** [quodlibet/quodlibet#1697]
QL 3.4.1 does not work on OS X 10.11 (El Capitan). It simply fails to launch.

Could this be related to the new SIP feature?
https://en.wikipedia.org/wiki/System_Integrity_Protection

It seems it's bringing some issues to a number of python applications: https://forums.developer.apple.com/thread/13161

**Comment by lazka** [comment]
Weird. I've tested it a week ago after a fresh update. Will check again..

**Comment by urielz** [comment]
mmm.. ok thanks. I tried this on a new macbook, no additional software except the operating system.

**Comment by lazka** [comment]
Can you run it in a terminal and see if there are any error messages?

```
/Applications/QuodLibet.app/Contents/MacOS/quodlibet
```

**Comment by urielz** [comment]
yes, I was about to report that, here's what I found:

running it from:
QuodLibet.app/Contents/MacOS/quodlibet

returns:
./quodlibet: line 61: ./Contents/MacOS/python: No such file or directory

running it from:
./QuodLibet.app/Contents/Resources/bin/quodlibet
returns 
env: python2: No such file or directory

content of /usr/bin is

pydoc
pydoc2.6 -> ../../System/Library/Frameworks/Python.framework/Versions/2.6/bin/pydoc2.6
pydoc2.7 -> ../../System/Library/Frameworks/Python.framework/Versions/2.7/bin/pydoc2.7
python
python-config
python2.6 -> ../../System/Library/Frameworks/Python.framework/Versions/2.6/bin/python2.6
python2.6-config -> ../../System/Library/Frameworks/Python.framework/Versions/2.6/bin/python2.6-config
python2.7 -> ../../System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7
python2.7-config -> ../../System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7-config
pythonw
pythonw2.6 -> ../../System/Library/Frameworks/Python.framework/Versions/2.6/bin/pythonw2.6
pythonw2.7 -> ../../System/Library/Frameworks/Python.framework/Versions/2.7/bin/pythonw2.7

executing QL by changing #!/usr/bin/env python2 to #!/usr/bin/env python in quodlibet.py returns:

Traceback (most recent call last):
  File "./quodlibet", line 17, in <module>
    from quodlibet.cli import process_arguments, exit_
ImportError: No module named quodlibet.cli

**Comment by lazka** [comment]
Hm.. no clue.

"./Contents/MacOS/python" is wrong if you started it from QuodLibet.app/.. (also weird that it reports an error in line 61 for a 60 line file..)

If you want to play around check out " QuodLibet.app/Contents/MacOS/_launcher" which contains all the startup magic.

Running ./QuodLibet.app/Contents/Resources/bin/quodlibet directly will never work btw.

**Comment by urielz** [comment]
line 61 is this one from what I can see, so it makes sense on my end:
$EXEC "$PYTHON" "$bundle_contents/Resources/bin/$APP" $*

Thanks for the tip. I'll look into _launcher later today. Will report back if I make progress.

**Comment by kaffeeundsalz** [comment]
Doesn't seem to be a general issue; QL 3.4.1 just runs and plays music as usual on my machine. OS X 10.11 El Capitan with System Integrity Protection turned on.

**Comment by urielz** [comment]
Thanks for the info. It's weird since this is a brand new machine.

**Comment by urielz** [comment]
@lazka sorry you asked me run it from /Applications/QuodLibet.app/Contents/MacOS/quodlibet
and the info I posted was from within the bundle. The output of /Applications/QuodLibet.app/Contents/MacOS/quodlibet is:

dyld: Library not loaded: @executable_path/../Resources/lib/libgstreamer-1.0.0.dylib
  Referenced from: /Applications/QuodLibet.app/Contents/Resources/libexec/gstreamer-1.0/gst-plugin-scanner
  Reason: image not found

**Comment by urielz** [comment]
Keep in mind that I know nothing about this, so this could be totally irrelevant. But just in case I'll put it out here:

otool -l /Applications/QuodLibet.app/Contents/Resources/lib/libgstreamer-1.0.0.dylib 

returns this (I just find odd the "/Users/lazka/...." part and I wonder if it's related to the "image not found" see post above):

	/Users/lazka/quodlibet/osx_bundle/_home/jhbuild_prefix/lib/libgstreamer-1.0.0.dylib (compatibility version 503.0.0, current version 503.0.0)
	@executable_path/../Resources/lib/libgobject-2.0.0.dylib (compatibility version 4401.0.0, current version 4401.1.0)
	@executable_path/../Resources/lib/libgmodule-2.0.0.dylib (compatibility version 4401.0.0, current version 4401.1.0)
	@executable_path/../Resources/lib/libglib-2.0.0.dylib (compatibility version 4401.0.0, current version 4401.1.0)
	@executable_path/../Resources/lib/libintl.8.dylib (compatibility version 10.0.0, current version 10.3.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 855.17.0)

**Comment by urielz** [comment]
Update: 
I disabled System Integrity Protection and QL launches. So this issue is definitely related to SIP.

**Comment by kaffeeundsalz** [comment]
That's strange because it probably means QL or its dependencies are demanding write access to one of the protected locations listed in `/System/Library/Sandbox/rootless.conf`. If that were the case with all QL installations, it should never run on El Cap, at least not when SIP is enabled (which it is by default); with SIP turned off (or in previous OS X versions), QL should prompt for administrator privileges (which it never did on my machine). SIP's other restrictions include code injection prevention and enforced kernel extension signing, but I find it unlikely that any of these apply to Quod Libet.

**Comment by lazka** [comment]
I suspect it's due to the new restrictions on DYLD_LIBRARY_PATH.

@urielz: I don't think you are using the latest bundle (3.4.1-v2).

**Comment by urielz** [comment]
I actually tried with both versions (and 3.3 as well) and all of them failed to launch.

So I enabled SIP again and QL works. Would it make sense that it needs SIP disabled on the first time it launches? That would explain why both of you didn't encounter any issues and I did (I'm assuming you upgraded to 10.11 from a previous installation with QL)...

**Comment by kaffeeundsalz** [comment]
Not sure about first-launch requirements, but yes: I had previously installed Quod Libet on 10.10.4 Yosemite and then upgraded to 10.11.0 El Capitan.

**Comment by urielz** [comment]
Update: same behavior in QL 3.5. I had to disable SIP, execute QL one time and enable SIP after that.

I also discovered this: If I change the name of the bundle (i.e., QuodLibet.App) to something else then QL fails to launch again. This is something that perhaps one of you can test on El Capitan?

**Comment by kaffeeundsalz** [comment]
You're right. Arbitrarily rename QuodLibet.app (It's actually sufficient to change capitalization) and it fails to start. Rename it back to its original filename and everything is fine again. However, a different version of the app with the same name won't start either, which means that I couldn't get the new version 3.5 running on El Cap. Disabling SIP, running QL once and then re-enabling SIP solves the issue.

**Comment by urielz** [comment]
Thanks for checking that. Perhaps a note should be added to the downloads section until the issue is resolved?

**Comment by lazka** [comment]
The problem is that GStreamer tries to update its plugin registry on first start and uses an external helper program for it which due to SIP doesn't get passed DYLD_LIBRARY_PATH and fails.

Three possible solutions:

1) Set Gstreamer to update the registry in process. The documentation states that that will increase memory usage (only on the first start?)
2) Disable registry updates and ship a prebuild registry 
3) Update the registry in the launcher before starting QL and disable registry updates for QL.

**Comment by urielz** [comment]
Cons of 1 and 2 are clear, not sure I understand 3. As of right now the plugin pool is rather stagnant so I don't see much of a problem in opting for 2...

**Comment by lazka** [comment]
Went with (4) wrap the GStreamer helper with our launcher, so things are the same as before.
Ideally (2) would be best as the GStreamer plugin count doesn't change but the cache contains absolute paths and no idea how to fix that atm.

New builds are up. Thanks for the pointers on how to reproduce and testing.

**Comment by urielz** [comment]
Great. Thanks for fixing this so fast. Just tried the new build, working as intended.
