### ISSUE TITLE
QL 3.5 not starting on openSUSE 13.2 / openSUSE Leap 42.1

### ISSUE THREAD

**Issue by d9h02f** [quodlibet/quodlibet#1699]
Since QL now requires python-mutagen >= 1.27, I updated that manually as a higher version isn't available in the default repositories of 13.2 / 42.1. However, QL/EF don't start. Terminal output for quodlibet:

>Traceback (most recent call last):
>  File "/usr/bin/quodlibet", line 225, in <module>
>    main(util.argv)
>  File "/usr/bin/quodlibet", line 105, in main
>    Kind.init(library)
>  File "/usr/lib/python2.7/site-packages/quodlibet/browsers/playlists/main.py", line 65, in init
>    library=library)
>  File "/usr/lib/python2.7/site-packages/quodlibet/util/collection.py", line 440, in __init__
>    with open(self.filename, "rb") as h:
>  File "/usr/lib/python2.7/site-packages/quodlibet/util/collection.py", line 458, in filename
>    basename = self.quote(self.name)
>  File "/usr/lib/python2.7/site-packages/quodlibet/util/path.py", line 239, in escape_filename
>    return fsnative(urllib.quote(s, safe="").decode("utf-8"))
>  File "/usr/lib/python2.7/site-packages/quodlibet/util/path.py", line 128, in fsnative
>    return path.encode(_FSCODING, 'replace')
>TypeError: encode() argument 1 must be string, not None

And for exfalso:

>Traceback (most recent call last):
>  File "/usr/bin/exfalso", line 74, in <module>
>    main(util.argv)
>  File "/usr/bin/exfalso", line 32, in main
>    argv.append(os.path.abspath(fsnative(u".")))
>  File "/usr/lib/python2.7/site-packages/quodlibet/util/path.py", line 128, in fsnative
>    return path.encode(_FSCODING, 'replace')
>TypeError: encode() argument 1 must be string, not None

**Comment by lazka** [comment]
Is G_FILENAME_ENCODING or G_BROKEN_FILENAMES set in your environ?

**Comment by lazka** [comment]
Unrelated: If you know how to best file a bug report about outdated packages in openSUSE please file one for mutagen.

**Comment by d9h02f** [comment]
How do I check? And sure, will do.

**Comment by lazka** [comment]
> How do I check? And sure, will do.

Check the the output of ```printenv G_FILENAME_ENCODING G_BROKEN_FILENAMES```

**Comment by d9h02f** [comment]
>@locale,UTF-8,ISO-8859-1,CP1252
>1

**Comment by lazka** [comment]
Oops. Thanks. Will be fixed in 3.5.1 (next week). 

For now:
```
unset G_FILENAME_ENCODING
quodlibet
```

**Comment by d9h02f** [comment]
Thanks!

**Comment by lazka** [comment]
the new version in the repo should work now
