### ISSUE TITLE
Can't enable Advanced preferences plugin

### ISSUE THREAD

**Issue by spxxxk** [quodlibet/quodlibet#1700]
Clicking the checkbox to enable the plugin does nothing.

Just found out about it so I don't know if this used to work on my machine.

QL version : 3.5.99+7553~10d9c31-0~ppa0~trusty

**Comment by lazka** [comment]
That's on purpose as it just exposes an interface for some config values and can't be enabled/disabled.

**Comment by spxxxk** [comment]
*awkward*
Checkbox's icon should be in "checked state" then, else stupid people as myself will get confused ;)

Sorry.

**Comment by lazka** [comment]
Yeah, it's confusing.. The checkbox has "non-sensitive" state, but at least with Adwaita this isn't very obvious (just a slightly brighter grey) 

An alternative to the plugin might be to move it into the preferences and add a "Advanced Prefs" button... but I'm worried users try to play around with it more easily then and break things.

Having it in a checked state sounds like an improvement, thanks.
