### ISSUE TITLE
Volume resets to 100% when starting new song

### ISSUE THREAD

**Issue by keiter** [quodlibet/quodlibet#1703]
I noticed a new bug when trying 3.5 on Windows 7. When you start a new song, QL's volume will reset to 100% from whatever it was before. This is annoying me a bit because I usually leave it at 50% to keep it normalized with other media on my computer.

This bug was introduced on 3.5 I think because I didn't notice anything like that on 3.4.1.

**Comment by lazka** [comment]
Thanks

**Comment by lazka** [comment]
hm, still broken, reopening for now
