### ISSUE TITLE
Crash when adding libraries in OpenSUSE Tumbleweed

### ISSUE THREAD

**Issue by bkilpat01** [quodlibet/quodlibet#1710]
I get this error when attempting to add folders to the library via Music -> Add a folder:
=== SYSTEM INFORMATION:
Quod Libet 3.5.0
Mutagen 1.28
Python 2.7.10 (default, May 24 2015, 14:46:10) [GCC] linux2
Platform Linux-4.2.1-1-desktop-x86_64-with-SuSE-20151002-x86_64
=== STACK TRACE
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/quodlibet/util/copool.py", line 22, in wrap
    for value in func(*args, **kwargs):
  File "/usr/lib/python2.7/site-packages/quodlibet/library/libraries.py", line 722, in scan
    desc = _("Scanning %s") % (unexpand(fsdecode(fullpath)))
  File "/usr/lib/python2.7/site-packages/quodlibet/util/path.py", line 66, in fsdecode
    return decode(s, _FSCODING)
  File "/usr/lib/python2.7/site-packages/quodlibet/util/string/__init__.py", line 29, in decode
    return s.decode(charset)
TypeError: decode() argument 1 must be string, not None

And I get this error when attempting to add folders to the library via Music -> Preferences -> Library - Scan Directories -> Add:

=== SYSTEM INFORMATION:
Quod Libet 3.5.0
Mutagen 1.28
Python 2.7.10 (default, May 24 2015, 14:46:10) [GCC] linux2
Platform Linux-4.2.1-1-desktop-x86_64-with-SuSE-20151002-x86_64
=== STACK TRACE
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/quodlibet/qltk/scanbox.py", line 113, in __add
    self.__save()
  File "/usr/lib/python2.7/site-packages/quodlibet/qltk/scanbox.py", line 100, in __save
    set_scan_dirs([r[0] for r in self.model])
  File "/usr/lib/python2.7/site-packages/quodlibet/util/library.py", line 53, in set_scan_dirs
    joined = join_escape(dirs, fsnative(u":"))
  File "/usr/lib/python2.7/site-packages/quodlibet/util/path.py", line 128, in fsnative
    return path.encode(_FSCODING, 'replace')
TypeError: encode() argument 1 must be string, not None

**Comment by lazka** [comment]
If you're using the repo on the download page, please try to update. I've updated it to 3.5.1 today which should fix this problem.

**Comment by bkilpat01** [comment]
It did. However, now all of my files are listed twice! Lol

On October 14, 2015 6:08:36 PM CDT, Christoph Reiter <notifications@github.com> wrote:
>If you're using the repo on the download page, please try to update.
>I've updated it to 3.5.1 today which should fix this problem.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/quodlibet/quodlibet/issues/1710#issuecomment-148229094

-- 
Sent from Kaiten Mail. Please excuse my brevity.
-- 
Sent from Kaiten Mail. Please excuse my brevity.

**Comment by bkilpat01** [comment]
It did. However, now all of my files are listed twice! Lol

On October 14, 2015 6:08:36 PM CDT, Christoph Reiter <notifications@github.com> wrote:
>If you're using the repo on the download page, please try to update.
>I've updated it to 3.5.1 today which should fix this problem.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/quodlibet/quodlibet/issues/1710#issuecomment-148229094

-- 
Sent from Kaiten Mail. Please excuse my brevity.
