### ISSUE TITLE
A grid-layout album-art browser ?

### ISSUE THREAD

**Issue by ricflomag** [quodlibet/quodlibet#1712]
This is a proposal for an enhancement.

Quodlibet has been my music player of choice for some months now. It is rock solid, efficient and fast. But... I would love to have it with an album-art centric, grid-layout browser.

Why ?

The album list browser is sub-optimal for displaying albums on the screen. [Much part of the display is blank] (http://imgur.com/CgOMxIC). A grid layout would fill almost all the space and show many more albums. See for example [Flavio Tordini's "Musique" player] (http://flavio.tordini.org/musique). Ideally, text information would be configurable, like in the album list browser, but not aside : as an overlay on the album art.

Well, and it would look so prettier !

**Comment by urielz** [comment]
If I recall correctly this is not the first time this has been proposed. I like the idea a lot. In my opinion there's nothing out there as good as QL. But yes, the only aspect where it's outshined is on the visual style...

**Comment by declension** [comment]
Yes, #1101 and #241 to an extent. 

Suggest we close at least one of these, though this has good description and "inspiration" screenshots...

**Comment by declension** [comment]
It's essentially the Album List view, with a (heavily) modified view layer...

**Comment by brunob** [comment]
Thx for pointing #241 @declension :) I think we can close this issue, since work is on and can be tested as i describe it in #241. The implementation i propose is not super fast, and code should certainly be enhanced since i'm totally new to python coding, but it works :p

**Comment by declension** [comment]
Closing. Please continue discussion as needed on #1101 and #241
