### ISSUE TITLE
Drag and drop folders into playlist

### ISSUE THREAD

**Issue by Piscium** [quodlibet/quodlibet#1713]
Enhancement suggestion: 
With Audacious it is possible to drag a folder with a file manager and drop into an Audacious playlist and all the songs in the folder tree are inserted in the playlist at the position of the mouse where the folder is dropped.
Could it be done in QL?

**Comment by urielz** [comment]
Issue https://github.com/quodlibet/quodlibet/issues/1704 address this. It has been tagged as an enhancement.

**Comment by Piscium** [comment]
Thanks, was not aware of that. I will close this one.
