### ISSUE TITLE
Windows: switch to msys2

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1718]
There is more support for it and it's easier to compile/patch stuff there.

Only downside compared to msvc compatible builds is that we have to build python extensions (could be tricky on Windows, not sure)

**Comment by lazka** [comment]
Current blocker: https://bugzilla.gnome.org/show_bug.cgi?id=738106

gdk_pixbuf_savev_utf8 has a wrong annotation... imo this should just be removed. 
It gets patched away in msys2 as well: https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-gdk-pixbuf2/PKGBUILD#L65

**Comment by lazka** [comment]
One remaining upstream fix: https://bugzilla.gnome.org/show_bug.cgi?id=773760

All QL tests pass now.

**Comment by lazka** [comment]
Another blocker: https://bugzilla.gnome.org/show_bug.cgi?id=773681

**Comment by lazka** [comment]
fix for the last one: https://github.com/Alexpux/MINGW-packages/pull/1902

**Comment by lazka** [comment]
First test installer: https://bitbucket.org/lazka/quodlibet/downloads/quodlibet-msys2-test1.exe

some known issues, but basics work

**Comment by RoestVrijStaal** [comment]
(Notified from the referrenced topic)

Beat me what the known issues are. 

The first test installer works like a charm ATM. 

I've completely rebuild  my music library which has tags encoded in various formats and using various signs without any hassle.

Quot Libet doesn't crash during startup with and without the "Scan the library at startup".  No problem here. 

A small remark is that I've MSYS2 installed which likely installed some Python packages which could have some positive side-effects for Quot Libet. Not sure though. 

I'm still confused why deploying an application written in Python needs a C++ compiler. Does Quot Libet has it's own Python interpreter or something?

**Comment by lazka** [comment]
Cool, thanks for testing. DnD is broken for example, fingerprinting plugin is still missing, anything using TLS through libsoup wont work (cover source plugins), and I haven't tested much..

> A small remark is that I've MSYS2 installed which likely installed some Python packages which could have some positive side-effects for Quot Libet. Not sure though. 

Unlikely, but who knows. Might be that TLS works if that uses hardcoded paths (haven't looked into that)

> I'm still confused why deploying an application written in Python needs a C++ compiler. Does Quot Libet has it's own Python interpreter or something?

Is has its own everything. Have a look at `%PROGRAMFILES(X86)%\Quod Libet\`.

**Comment by keiter** [comment]
Also tested the new installer. I can second that it fixes #1696. Will keep using it and see if I have anything else to report.

**Comment by lazka** [comment]
@keiter thanks for testing

I'll open new bug reports for the remaining issues.
