### ISSUE TITLE
error quodlibet windows 7 permission

### ISSUE THREAD

**Issue by laleche** [quodlibet/quodlibet#1722]
Sorry, i do not speak english
I use a translator
I'm not sure this goes here
Sorry the deshorden
Thank you

http://i.imgur.com/Lc8JN88.png
![image] (http://i.imgur.com/Lc8JN88.png)

tilde_el_error_virus_de_las_2_tildes_2_acentos_doble_tilde_doble_acento

virus de la doble tilde
virus del doble acento
virus de las dobles comillas

problema de la doble tilde
problema del doble acento
problema de las dobles comillas

virus de las dos tildes
virus de los dos acentos
virus de las dos comillas

doble tilde
doble acento
dobles comillas
DT-Kill.exe
coj´´on
dos acentos

tilde en ingles lo llaman a las virgtulillas
~

double tilde
double accent
double quotes

doble tilde
doble acento
comillas dobles

El malware conocido popularmente como virus del Doble Tilde , Doble Acento o Doble Comillas

DT-Kill by InfoSpyware (Doble Tilde Kill)
¿?
http://www.forospyware.com/t304317.html
http://www.forospyware.com/t304317.html
¿?

david
quodlibet keyboard error
se soluciona el error renombrando el directorio pyHook

Windows: Impossible to use accents while typing OUTSIDE of Quod Libet #1168

https://code.google.com/p/quodlibet/issues/detail?id=1168
https://code.google.com/p/quodlibet/issues/detail?id=1168

https://github.com/quodlibet/quodlibet/issues/1168
https://github.com/quodlibet/quodlibet/issues/1168

ruta
C:\Program Files (x86)\Quod Libet\bin\pyHook

renombro
pyHook
pyHook_old

Acceso denegado a la carpeta
Warning
!
Necesitará proporcionar permisos de administrador para cambiar el nombre de esta carpeta
pyHook
Fecha de creación:15/07/2015 12:39
<continuar> <omitir> <aceptar>

https://github.com/quodlibet/quodlibet/issues/1381
https://github.com/quodlibet/quodlibet/issues/1381

"keyboard error" "quodlibet"

error

http://i.imgur.com/CxZd3HW.png
![image] (http://i.imgur.com/CxZd3HW.png)

quodlibet_windows_7_errror_exe

01
Panel de control\Sistema y seguridad\Centro de actividades
Panel de control > Sistema y seguridad > Centro de actividades
Mantenimiento
Buscar soluciones para problemas no notificados
Hay problemas en el equipo que no se han notificado a Microsoft. Puede que haya soluciones disponibles para algunos de ellos.

Ver problemas de los quehay que informar.

http://i.imgur.com/UQK257b.png
![image] (http://i.imgur.com/UQK257b.png)

02
Panel de control\Sistema y seguridad\Centro de actividades\Buscar soluciones
Panel de control > Sistema y seguridad > Centro de actividades > Buscar soluciones

Buscar soluciones para estos problemas
Windows enviará una descripción de cada problema a Microsoft y buscará los pasos que puede seguir para solucionarlos. El envío de información sobre los problemas también ayuda a crear soluciones.

origen:
a music library, tagger and player (15)
resumen:
dejó de funcionar
ver detalles técnicos:
18/09/2015 13:00
Origen
a music library, tagger, and player

http://i.imgur.com/Ilorf1i.png
![image] (http://i.imgur.com/Ilorf1i.png)

03
Panel de control\Sistema y seguridad\Centro de actividades\Detalles del problema
Panel de control > Sistema y seguridad > Centro de actividades > Detalles del problema

Resumen
Dejó de funcionar

Fecha
18/09/2015 13:00

Estado
No reportado

Descripción
Ruta de acceso de la aplicación con errores:    C:\Program Files (x86)\Quod Libet\bin\quodlibet.exe

Firma del problema
Nombre de evento de problema:    APPCRASH
Nombre de la aplicación:    quodlibet.exe
Versión de la aplicación:    3.4.1.0
Marca de tiempo de la aplicación:    49180193
Nombre del módulo con errores:    libglib-2.0-0.dll
Versión del módulo con errores:    2.42.2.0
Marca de tiempo del módulo con errores:    54f072fd
Código de excepción:    40000015
Desplazamiento de excepción:    0005bb9a
Versión del sistema operativo:    6.1.7601.2.1.0.256.48
Id. de configuración regional:    3082
Información adicional 1:    3c4d
Información adicional 2:    3c4d8fa727077cc94c2cf2c959959d3b
Información adicional 3:    2956
Información adicional 4:    29566a3f2b864818a4eb8c7f7e0254b2

http://i.imgur.com/AKpHRQ4.png
![image] (http://i.imgur.com/AKpHRQ4.png)

Por si les sirve de ayuda:
https://galileoeo.wordpress.com/equivalencias_quodlibet_id3v2_seres_humanos
https://galileoeo.wordpress.com/equivalencias_quodlibet_id3v2_seres_humanos

https://galileoeo.wordpress.com/00_10_id3v2_teamviewer__quodlibet__quod_libet
https://galileoeo.wordpress.com/00_10_id3v2_teamviewer__quodlibet__quod_libet

https://galileoeo.wordpress.com/00_12_id3v2_quodlibet_amarok_vlc_android
https://galileoeo.wordpress.com/00_12_id3v2_quodlibet_amarok_vlc_android

;)

**Comment by lazka** [comment]
(translated) Yo no te puedo ayudar. Lo siento.

**Comment by laleche** [comment]
Gracias de todas maneras

**Comment by laleche** [comment]
thanks anyway
