### ISSUE TITLE
Quodlibet GtkAccelMap rc-file no longer support switching browsers

### ISSUE THREAD

**Issue by spxxxk** [quodlibet/quodlibet#1726]
On ubuntu 12.04, `~/.quodlibet/accels` included 
```
    (gtk_accel_path "<Actions>/QuodLibetWindowActions/ViewSearchBar" "")
    (gtk_accel_path "<Actions>/QuodLibetWindowActions/ViewPlaylists" "")
    (gtk_accel_path "<Actions>/QuodLibetWindowActions/ViewFileSystem" "")
```

It looks like they're no longer added in the default `accels` file on Ubuntu 14.04, and supported if I add them.

Workaround: use Alt+keys ... but not as convenient

**Comment by lazka** [comment]
Not sure. Maybe it's broken in gtk+ as nothing there uses that feature any more.

**Comment by spxxxk** [comment]
In ubuntu 14.04, the files is
```
; quodlibet GtkAccelMap rc-file         -*- scheme -*-
; this file is an automated accelerator map dump
;
; (gtk_accel_path "<Actions>/QuodLibetWindowActions/BrowserPanedBrowser" "")
; (gtk_accel_path "<Actions>/QuodLibetFilterActions/RandomArtist" "<Primary>t")
; (gtk_accel_path "<Actions>/QuodLibetWindowActions/BrowserFileSystem" "")
; (gtk_accel_path "<Actions>/QuodLibetWindowActions/BrowserCollectionBrowser" "")
; (gtk_accel_path "<Actions>/QuodLibetFilterActions/RandomGenre" "<Primary>g")
; (gtk_accel_path "<Actions>/QuodLibetWindowActions/BrowserMediaDevices" "")
; (gtk_accel_path "<Actions>/QuodLibetWindowActions/Previous" "<Primary>comma")
; (gtk_accel_path "<Actions>/QuodLibetWindowActions/Jump" "<Primary>j")
; (gtk_accel_path "<Actions>/QuodLibetWindowActions/About" "")
; (gtk_accel_path "<Actions>/QuodLibetWindowActions/BrowserAlbumList" "")
; (gtk_accel_path "<Actions>/QuodLibetWindowActions/EditBookmarks" "<Primary>b")
; (gtk_accel_path "<Actions>/QuodLibetWindowActions/PlayPause" "<Primary>space")
; (gtk_accel_path "<Actions>/QuodLibetWindowActions/Next" "<Primary>period")
; (gtk_accel_path "<Actions>/QuodLibetWindowActions/BrowserAudioFeeds" "")
; (gtk_accel_path "<Actions>/QuodLibetFilterActions/RandomAlbum" "<Primary>m")
; (gtk_accel_path "<Actions>/QuodLibetWindowActions/BrowserSearchBar" "")
; (gtk_accel_path "<Actions>/QuodLibetWindowActions/Quit" "<Primary>q")
; (gtk_accel_path "<Actions>/QuodLibetWindowActions/StopAfter" "<Shift>space")
; (gtk_accel_path "<Actions>/QuodLibetWindowActions/BrowserPlaylistsBrowser" "")
; (gtk_accel_path "<Actions>/QuodLibetWindowActions/BrowserInternetRadio" "")
; (gtk_accel_path "<Actions>/QuodLibetWindowActions/AddBookmark" "<Primary>d")
; (gtk_accel_path "<Actions>/QuodLibetWindowActions/OnlineHelp" "F1")
; (gtk_accel_path "<Actions>/QuodLibetWindowActions/AddFolders" "<Primary>o")
; (gtk_accel_path "<Actions>/QuodLibetWindowActions/SearchHelp" "")
```

Editing (uncomment+set shortcut)  still works for those actions. But no "ViewSearchBar" ...  actions.

No idea what generates that `accels` file though.

**Comment by CreamyCookie** [comment]
Yep, [doesn't work for me either](https://github.com/quodlibet/quodlibet/issues/1540#issuecomment-152748398). Although this might be Ubuntu's fault: https://bugs.launchpad.net/ubuntu/+source/indicator-appmenu/+bug/610234

I can only hope that they improve keyboard support (and customization of these) with Unity 8.

**Comment by spxxxk** [comment]
Broke again since last update. 

(Not sure if I should open a new issue)

**Comment by lazka** [comment]
Seems to work here. Which update are you referring to?

btw, what would you think about setting them to "ctrl+1/2/3/.." be default?

**Comment by spxxxk** [comment]
Not sure it's the last update actually, maybe I used the same browser for a while.. But since the menus changed I thought it could be related.
QL version : `3.6.99+8220~02e672a-0~ppa0~xenial

Like before, the default `accels` file no longer includes `view` actions.

Ctrl+1/2... could work, although there are already 9 browsers.

**Comment by lazka** [comment]
It got renamed to Browse instead of view, renamed it back now and pushed to the ppa.
