### ISSUE TITLE
Always display seconds in QL songlist

### ISSUE THREAD

**Issue by Piscium** [quodlibet/quodlibet#1727]
https://groups.google.com/forum/#!topic/quod-libet-development/98T9miCOXAs

**Comment by lazka** [comment]
Just wondering, why do you care about seconds in a one hour+ playlist?

**Comment by Piscium** [comment]
I don't care about 1 second, but I care about 59 seconds as that is nearly one minute! :)

I was a tango dj last Thursday, and I had a slot of 3 hours, so my playlist was 2:59 plus a few seconds.

A seconds display is also good to cross check things, to make sure that the duration of songs is being calculated well by the software. It is probably useful also for those that dj in radio (not my case).

I agree that I can live without seconds display, I thought I would ask for this feature because it is likely not too difficult to implement.

**Comment by lazka** [comment]
OK, thanks.

**Comment by CreamyCookie** [comment]
I agree. One minor thing that bugs me is that the number of songs and time is displayed differently in various places:

**Album list view:**
![1 - albumlist](https://cloud.githubusercontent.com/assets/3063858/11181276/2c7f4788-8c61-11e5-8397-b6e2cfdc4c43.png)

**Album:**
![2 - album](https://cloud.githubusercontent.com/assets/3063858/11181278/2cd2095a-8c61-11e5-862b-74c5fa1aa98c.png)

**Play queue:**
![3 - queue](https://cloud.githubusercontent.com/assets/3063858/11181277/2c87f446-8c61-11e5-9862-caf293027b1a.png)

**Playlist view:**
![4 - playlist view](https://cloud.githubusercontent.com/assets/3063858/11181279/2cd5a470-8c61-11e5-8bd1-9d9ae9603cdd.png)

It would be cool, if we could configure how it's displayed, like we can with the "current song display". This would then be used in all these places shown in the pictures above.

So, if we were to use the way it's displayed in the **Album list view**, the formatting code would be something like this: `<totaltracknumber> tracks - <h> hours, <m> minutes, <s> seconds`. Although that would mean that you will see lines like "8 tracks - 0 hours, 55 minutes, 03 seconds", some might actually want that. I think I'd prefer to use `<totaltracknumber> tracks - <hh>:<mm>:<ss>`. Another way might be to allow to choose from two or more formats, and then use that everywhere.

**Comment by Piscium** [comment]
Quick (unrelated) comment: for some unknown reason Audacious and QL disagree about the duration of some songs, the difference can be 3 seconds. I have not yet found out who is right and who is wrong.

**Comment by declension** [comment]
Sounds like the quick win for consistency here is moving Playlists browser to use human (long) format e.g. _18 minutes, 20 seconds_

Longer term perhaps yes a configurable format for times everywhere

**Comment by declension** [comment]
I've only just worked out that this isn't about the Playlist Browser at all ( @CreamyCookie's comments aside), but the songlist (which is shared across browsers).

**Comment by declension** [comment]
Commited pre-emptive tidy-up refactoring in revision bbc862e

**Comment by lazka** [comment]
(master branch is open for 3.8)
