### ISSUE TITLE
operon image-set returns a warning

### ISSUE THREAD

**Issue by gui-don** [quodlibet/quodlibet#1728]
`operon image-set myimage.jpg myfile.mp3` returns the following warning:

*/usr/lib/python2.7/site-packages/quodlibet/formats/_image.py:183: PyGIWarning: GdkPixbuf was imported without specifying a version first. Use gi.require_version('GdkPixbuf', '2.0') before import to ensure that the right version gets loaded. from gi.repository import GdkPixbuf, GLib*

However, the command still seems to work with individual files (e.g. `operon image-set myimage.jpg *` don’t work, but I don’t think it’s related).

On Archlinux, operon 3.5.1

**Comment by lazka** [comment]
Thanks. The warning can be ignored.

I filed a bug for the multiple file problem: #1729

**Comment by lazka** [comment]
fyi, #1729 is fixed now
