### ISSUE TITLE
QL generates multiple identical albumartistsort tags

### ISSUE THREAD

**Issue by davidSchlosser** [quodlibet/quodlibet#1732]
I've used the  albumartistsort tag on a small proportion of my albums, all have the tag set to 'Various artists' on all tracks. I created the tags in Quodlibet using 'Edit Tags'. After saving and playing I've had to adjust other tags in the album's tracks and notice that the tracks now all have 2 albumartistsort tags, both set to 'Various artists'. When I removed one tag & saved, refreshed the songs using the refresh plug-in, then do 'edit Tags', there are 2 identical instances of the albumartistsort tag again. Repeating this doesn't cause additional duplicates, though on occasions I've found 4 identical instances of the tag. I haven't been able to determine just what steps are needed to replicate that.
Quodlibet 3.2.-1 on Lubuntu, Ubuntu 14.04.3 LTS

**Comment by pschwede** [comment]
I can second this issue.

**Comment by lazka** [comment]
Thank, can reproduce. (select album, add albumartistsort="foo", refresh songs, now there are two "foo")
