### ISSUE TITLE
Setting to disable album cover art

### ISSUE THREAD

**Issue by reddit-is-fun** [quodlibet/quodlibet#1734]
As far as I'm aware, album cover picture can't be disabled. I know that the cover can be expanded by clicking, but I prefer a more minimalistic view. 
I've also noticed that the program saves images to "tmp" folder on Linux and thumbnails aren't removed when I delete an album from my hard drive.

In my opinion this is the only thing preventing Quod Libet for achieving true perfection, extremely satisfied otherwise.

![screenshot_2015-11-05_18-00-28](https://cloud.githubusercontent.com/assets/14923168/10973690/20589bbc-83e7-11e5-934b-038747c52dc2.png)

**Comment by lazka** [comment]
> As far as I'm aware, album cover picture can't be disabled. I know that the cover can be expanded by clicking, but I prefer a more minimalistic view. 

Why exactly? In the picture you posted it doesn't take away any space for example. 

>  I've also noticed that the program saves images to "tmp" folder on Linux and thumbnails aren't removed when I delete an album from my hard drive.

These should only persist as long as the file is played. We use the to pass embedded images to external services so they can display cover art. But, we should only create them when they are really needed, so that could be improved.

**Comment by reddit-is-fun** [comment]
@lazka Yes it doesn't any GUI space, but I'm not a fan of cover art in music players. I can look at my vinyl records instead. 

* Quod Libet can download a cover of a "special edition" or similar when I'd rather see the original picture
* there can be compression artifacts in JPEG files 
* numerous album covers are NSFW!
* the images take a tiny bit of space

**Comment by reddit-is-fun** [comment]
Because this won't probably be implemented, I decided to block Quod Libet in my firewall. Should be good enough solution.

**Comment by lazka** [comment]
If you go to the plugin window and search for "cover source" and disable those, then QL will not download covers if there are none locally.

**Comment by lazka** [comment]
I've opened #1752 for making it easier to disable/enable automatic cover download.

**Comment by declension** [comment]
I suggest we can close this now as superseded by #1752
