### ISSUE TITLE
Freeze while editing tags: tag may not be accurate

### ISSUE THREAD

**Issue by lorenrogers** [quodlibet/quodlibet#1736]
In trying to update a lot of tags on an smb share, and I keep getting this issue. I'm not sure if the issue is the smb share, but I'm unable to dismiss this message. See screenshot: https://imgur.com/D0BfRsS (Not sure why I can't attach to this issue...)

Music still plays, and I can click stop and pause, but they don't do anything. I can also still move all the windows around, except for the "Saving the songs" dialog. The only way I can get out of this state is to kill the program...

I'm running version 3.5.1 on Debian 8 with XFCE.

I'm not seeing any clues in my debug log:
D: 114.51: CoPool.remove: Removed copool function id <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f1c984fefa0 (quodlibet+qltk+completion+LibraryValueCompletion at 0x5e83260)>>
D: 122.91: SongFileLibrary._changed: Changing 6 items.
D: 122.91: qltk.completion.__update_song: Updating tag model for 6 songs
D: 122.91: qltk.completion.__update_song: Done updating tag model for 6 songs
D: 124.13: qltk.window.__restore_state: Restore state
D: 124.13: qltk.window.__restore_position: Restore position
D: 124.14: qltk.window.__restore_size: Restore size
D: 125.80: PlaylistModel.set: Clearing model.
D: 125.80: PlaylistModel.set: Setting 11 songs.
D: 125.80: PlaylistModel.set: Done filling model.
D: 127.90: PlaylistModel.set: Clearing model.
D: 127.90: PlaylistModel.set: Setting 25 songs.
D: 127.90: PlaylistModel.set: Done filling model.
D: 131.35: PlaylistModel.set: Clearing model.
D: 131.35: PlaylistModel.set: Setting 12 songs.
D: 131.35: PlaylistModel.set: Done filling model.
D: 132.17: PlaylistModel.set: Clearing model.
D: 132.17: PlaylistModel.set: Setting 55 songs.
D: 132.18: PlaylistModel.set: Done filling model.
D: 133.87: config.save: Writing config...
D: 133.88: library.save: Saving all libraries...
D: 133.88: SongFileLibrary.save: Saving contents to '/home/lorentrogers/.quodlibet/songs'.
D: 135.30: qltk.window.__restore_state: Restore state
D: 135.30: qltk.window.__restore_position: Restore position
D: 135.30: qltk.window.__restore_size: Restore size
D: 140.18: CoPool.add: Added copool function <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f1ca01554b0 (quodlibet+qltk+completion+LibraryValueCompletion at 0x7f1c94077340)>> with id <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f1ca01554b0 (quodlibet+qltk+completion+LibraryValueCompletion at 0x7f1c94077340)>>
D: 140.73: CoPool.remove: Removed copool function id <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x7f1ca01554b0 (quodlibet+qltk+completion+LibraryValueCompletion at 0x7f1c94077340)>>

**Comment by davidSchlosser** [comment]
I'm getting the same behaviour following an update to QL 3.5.1. It happens every time I attempt to edit songs with changed tags that I haven't refreshed. Below I've pasted the terminal output with --debug. This was from a fresh start of QL, player paused: 
david@david-DS437T:~$ quodlibet --debug > qlDebug.txt
D: 497.80: quodlibet._init_gettext: LANGUAGE: 'en_AU:C:en:C'
D: 497.80: quodlibet._init_gettext: LANG: 'en_AU.UTF-8'
D: 497.80: quodlibet._init_gettext: No translation found in '/usr/share/locale'
D: 497.84: formats.init: MimeType=application/x-flac;audio/aac;audio/midi;audio/mp3;audio/mp4;audio/mpeg;audio/mpeg4;audio/mpg;audio/ogg;audio/vorbis;audio/wav;audio/wave;audio/x-aac;audio/x-flac;audio/x-m4a;audio/x-midi;audio/x-mp3;audio/x-mpc;audio/x-mpeg;audio/x-ms-wma;audio/x-ms-wmv;audio/x-musepack;audio/x-oggflac;audio/x-speex;audio/x-tta;audio/x-wav;audio/x-wavpack;audio/x-wma;video/ogg;video/x-ms-asf;video/x-theora;video/x-wmv;
D: 497.96: quodlibet._init_gtk_debug: Initializing debugging extensions
D: 498.00: qltk.add_signal_watch: Register Python signal handler: 'SIGHUP'
D: 498.00: qltk.add_signal_watch: Register Python signal handler: 'SIGINT'
D: 498.00: qltk.add_signal_watch: Register Python signal handler: 'SIGTERM'
D: 498.00: qltk.add_signal_watch: Register GLib signal handler: 'SIGHUP'
D: 498.00: qltk.add_signal_watch: Register GLib signal handler: 'SIGINT'
D: 498.00: qltk.add_signal_watch: Register GLib signal handler: 'SIGTERM'
D: 498.08: __main__.main: Initializing main library (~/.quodlibet/songs)
D: 498.08: library.init: Supported formats: aac, midi, mod, monkeysaudio, mp3, mp4, mpc, spc, trueaudio, vgm, wav, wavpack, wma, xiph
D: 498.08: SongFileLibrary.__init__: Initializing SongFileLibrary "main".
D: 498.08: SongFileLibrary.__init__: Using pickling persistence for library "main"
D: 498.08: SongFileLibrary.load: Loading contents of '/home/david/.quodlibet/songs'.
D: 498.92: SongFileLibrary.load: Done loading contents of '/home/david/.quodlibet/songs'.
D: 498.95: devices.init: Initializing device backend.
D: 498.95: devices.init: Trying 'UDisks2'
D: 498.96: devices.init: Device backend initialized.
D: 499.09: SongFileLibrary.__init__: Initializing SongFileLibrary "filesystem".
D: 499.09: SongFileLibrary.__init__: Using pickling persistence for library "filesystem"
D: 499.11: UDisks2Manager._try_build_device: Found device: '/dev/sda1'
D: 499.14: UDisks2Manager._try_build_device: '/dev/sda1' not a media player
D: 499.14: UDisks2Manager._try_build_device: Found device: '/dev/sdb1'
D: 499.18: UDisks2Manager._try_build_device: '/dev/sdb1' not a media player
D: 499.18: quodlibet.init_plugins: Starting plugin manager
D: 499.18: quodlibet.init_plugins: Scanning folders: ['/usr/lib/python2.7/dist-packages/quodlibet/ext/editing', '/usr/lib/python2.7/dist-packages/quodlibet/ext/events', '/usr/lib/python2.7/dist-packages/quodlibet/ext/playorder', '/usr/lib/python2.7/dist-packages/quodlibet/ext/songsmenu', '/usr/lib/python2.7/dist-packages/quodlibet/ext/playlist', '/usr/lib/python2.7/dist-packages/quodlibet/ext/gstreamer', '/usr/lib/python2.7/dist-packages/quodlibet/ext/covers', '/home/david/.quodlibet/plugins']
D: 499.18: plugins.__restore: Restoring plugins: 15
D: 499.18: PluginManager.rescan: Rescanning..
D: 499.18: ModuleScanner.rescan: Rescanning..
D: 499.35: ModuleScanner.rescan: Rescanning done: 75 added, 0 removed, 2 error(s)
D: 499.36: PluginManager.rescan: Rescanning done.
D: 499.36: PluginManager.register_handler: Registering handler: 'EditTagsPluginHandler'
D: 499.36: PluginManager.register_handler: Registering handler: 'RenameFilesPluginHandler'
D: 499.36: PluginManager.enable: Enable 'Regex Substitution'
D: 499.36: PluginManager.register_handler: Registering handler: 'TagsFromPathPluginHandler'
D: 499.36: PluginManager.register_handler: Registering handler: 'GStreamerPlayer'
D: 499.37: PluginManager.register_handler: Registering handler: 'SongsMenuPluginHandler'
D: 499.37: PluginManager.enable: Enable 'Duplicates'
D: 499.37: PluginManager.enable: Enable 'Search album in Wikipedia'
D: 499.37: PluginManager.enable: Enable 'ExportMeta'
D: 499.37: PluginManager.enable: Enable 'ImportMeta'
D: 499.37: PluginManager.enable: Enable 'Browse Folders'
D: 499.37: PluginManager.enable: Enable 'refresh-songs'
D: 499.37: PluginManager.enable: Enable 'embedded_edit'
D: 499.37: PluginManager.register_handler: Registering handler: 'CoverPluginHandler'
D: 499.37: PluginManager.register_handler: Registering handler: 'PlaylistPluginHandler'
D: 499.37: PluginManager.enable: Enable 'Export to Squeezebox Playlist'
D: 499.37: PluginManager.enable: Enable 'Remove Playlist Duplicates'
D: 499.54: PluginManager.register_handler: Registering handler: 'PlayOrder'
D: 499.54: GStreamerPlayer.go_to: Going to None
D: 499.54: PlaylistMux.go_to: Told to go to None
D: 499.54: QueueModel.go_to: Told to go to None
D: 499.54: PlaylistModel.go_to: Told to go to None
D: 499.55: AlbumLibrary.__init__: Initializing Album Library to watch 'main'
D: 505.71: qltk.window.__restore_state: Restore state
D: 505.71: qltk.window.__restore_position: Restore position
D: 505.71: qltk.window.__restore_size: Restore size
D: 505.71: PluginManager.register_handler: Registering handler: 'EventPluginHandler'
D: 505.71: PluginManager.enable: Enable 'Tray Icon'
D: 505.72: PluginManager.enable: Enable 'Random Album Playback'
D: 505.72: PluginManager.enable: Enable 'Squeezebox Output'
D: 505.72: SqueezeboxSyncPlugin.enabled: Debug is set to False
D: 505.72: SqueezeboxServer.__init__: Connected to Squeezebox Server! Squeezebox server at localhost:9090
D: 505.73: SqueezeboxSyncPlugin.init_server: Couldn't get player info (list index out of range).
D: 505.73: PluginManager.enable: Enable 'Automatic library update'
D: 505.74: AutoLibraryUpdate.enabled: Using threaded notifier
D: 505.75: AutoLibraryUpdate.enabled: Watching directory /media/u2nas/Music Library for ['IN_DELETE', 'IN_CLOSE_WRITE', 'IN_MOVED_FROM', 'IN_MOVED_TO', 'IN_CREATE']
D: 581.77: AutoLibraryUpdate.enabled: Watching directory /home/david/Music for ['IN_DELETE', 'IN_CLOSE_WRITE', 'IN_MOVED_FROM', 'IN_MOVED_TO', 'IN_CREATE']
D: 581.80: PluginManager.enable: Enable 'Picture Saver'
D: 581.80: mmkeys.find_active_backend: Trying to find a mmkeys backend
D: 581.81: mmkeys.find_active_backend: Found 'KeybinderBackend'
D: 581.81: qltk.session.init: Connecting with the gnome session manager failed
D: 581.81: CoPool.add: Added copool function <function periodic_config_save at 0x9b70be64> with id <function periodic_config_save at 0x9b70be64>
D: 581.81: CoPool.add: Added copool function <function periodic_library_save at 0x9b70bed4> with id <function periodic_library_save at 0x9b70bed4>
D: 581.81: quodlibet.main: Entering quodlibet.main
D: 581.93: PlaylistModel.set: Clearing model.
D: 581.93: PlaylistModel.set: Setting 6 songs.
D: 581.93: PlaylistModel.set: Done filling model.
D: 581.93: GStreamerPlayer.go_to: Going to '/media/u2nas/Music Library/Jazz - Fusion (Rock)/Chick Corea - 1982, Touchstone/05 - Estancia.mp3'
D: 581.93: PlaylistMux.go_to: Told to go to '/media/u2nas/Music Library/Jazz - Fusion (Rock)/Chick Corea - 1982, Touchstone/05 - Estancia.mp3'
D: 581.93: QueueModel.go_to: Told to go to None
D: 581.93: PlaylistModel.go_to: Told to go to '/media/u2nas/Music Library/Jazz - Fusion (Rock)/Chick Corea - 1982, Touchstone/05 - Estancia.mp3'
D: 581.93: GStreamerPlayer._end: End song
D: 581.94: util.cover.manager.run: Found local cover from FilesystemCover
D: 581.95: SqueezeboxSyncPlugin.plugin_on_song_started: Requesting to play /media/u2nas/Music Library/Jazz - Fusion (Rock)/Chick Corea - 1982, Touchstone/05 - Estancia.mp3...
D: 581.96: GStreamerPlayer._end: Next song
D: 582.14: CoPool.add: Added copool function <bound method AlbumList.__scan_paths of <AlbumList object at 0xa2e1266c (quodlibet+browsers+albums+main+AlbumList at 0xcf99e60)>> with id <bound method AlbumList.__scan_paths of <AlbumList object at 0xa2e1266c (quodlibet+browsers+albums+main+AlbumList at 0xcf99e60)>>
D: 583.08: quodlibet._override_exceptions: Enabling custom exception handler.
D: 583.11: SongFileLibrary._changed: Changing 1 items.
D: 583.11: library.libraries.__changed: Updating affected albums for 1 items
D: 583.16: CoPool.remove: Removed copool function id <bound method AlbumList.__scan_paths of <AlbumList object at 0xa2e1266c (quodlibet+browsers+albums+main+AlbumList at 0xcf99e60)>>
D: 583.16: CoPool.add: Added copool function <bound method AlbumList.__scan_paths of <AlbumList object at 0xa2e1266c (quodlibet+browsers+albums+main+AlbumList at 0xcf99e60)>> with id <bound method AlbumList.__scan_paths of <AlbumList object at 0xa2e1266c (quodlibet+browsers+albums+main+AlbumList at 0xcf99e60)>>
D: 584.68: CoPool.remove: Removed copool function id <bound method AlbumList.__scan_paths of <AlbumList object at 0xa2e1266c (quodlibet+browsers+albums+main+AlbumList at 0xcf99e60)>>
D: 604.17: qltk.window.__restore_state: Restore state
D: 604.17: qltk.window.__restore_position: Restore position
D: 604.17: qltk.window.__restore_size: Restore size
D: 607.59: CoPool.add: Added copool function <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x9249f0f4 (quodlibet+qltk+completion+LibraryValueCompletion at 0x8ef74e8)>> with id <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x9249f0f4 (quodlibet+qltk+completion+LibraryValueCompletion at 0x8ef74e8)>>
D: 607.68: CoPool.remove: Removed copool function id <bound method LibraryValueCompletion.__fill_tag of <LibraryValueCompletion object at 0x9249f0f4 (quodlibet+qltk+completion+LibraryValueCompletion at 0x8ef74e8)>>

**Comment by davidSchlosser** [comment]
I've updated my Lubuntu Quodlibet to 3.5.3 - freeze problem still exists. 

I also installed a OS X Quodlibet instance to 3.5.2 and created a library on a separate directory structure on the same shared SMB NAS disk - it doesn't exhibit the freeze problem and handles the 'Tags may not be accurate' dialogue 'gracefully'.

Could the problem be due to an incompatibility with LXDE desktop environment?

**Comment by declension** [comment]
Out of interest, have you tried disabling the auto library update plugin?

**Comment by davidSchlosser** [comment]
Same behaviour after I disable the auto library plugin. Also same behaviour after I disabled all other plugins except Refresh Songs.

**Comment by lbt** [comment]
I hit this bug and found this report when coming to report it.

Actually it's not a "true" freeze :)

What's happening is that quodlibet is grabbing focus to the "Saving the songs you changed" popup.

Then when an error occurs, another popup appears saying "Tag may not be accurate"
The second popup has a Cancel/Save option that cannot be selected because the main popup has focus.

The cause is https://github.com/quodlibet/quodlibet/blob/master/quodlibet/qltk/wlw.py#L146
```
self.set_modal(True)
```
https://docs.gtk.org/gtk4/method.Window.set_modal.html says "Modal windows prevent interaction with other windows in the same application"

This then results in a deadlock as you can't press Cancel/Save and the loop never comes back to handle the main stop/pause clicks.
I'm a Qt man myself so I don't know how this should be resolved; commenting out the set_modal(True) and then not attempting to "do other stuff" whilst the save is in progress works for me.
