### ISSUE TITLE
quodlibet language spanish? 

### ISSUE THREAD

**Issue by simonbcn** [quodlibet/quodlibet#1738]
Quod Libet 3.4.1 installed from sources 
When I open it all labels are in english.
My locales:
```
LANG=es_ES.UTF-8
LANGUAGE=es_ES:en
LC_CTYPE="es_ES.UTF-8"
LC_NUMERIC=es_ES.UTF-8
LC_TIME=es_ES.UTF-8
LC_COLLATE=C
LC_MONETARY=es_ES.UTF-8
LC_MESSAGES=POSIX
LC_PAPER=es_ES.UTF-8
LC_NAME=es_ES.UTF-8
LC_ADDRESS=es_ES.UTF-8
LC_TELEPHONE=es_ES.UTF-8
LC_MEASUREMENT=es_ES.UTF-8
LC_IDENTIFICATION=es_ES.UTF-8
LC_ALL=
```

**Comment by lazka** [comment]
Weird.

When you run `quodlibet --debug` the first three lines should show some messages related to translations.

There should be a /usr/share/locale/es/LC_MESSAGES/quodlibet.mo on your system.

Why did you install from source btw?

**Comment by simonbcn** [comment]
```
D: 840.65: quodlibet._init_gettext: LANGUAGE: 'es_ES:en:C'
D: 840.65: quodlibet._init_gettext: LANG: 'es_ES.UTF-8'
D: 840.65: quodlibet._init_gettext: No translation found in '/usr/share/locale'
```
The problem is that it searches in `/usr/share`.

**Comment by lazka** [comment]
> The problem is that it searches in /usr/share.

The translations should be in /usr/share/locale so why do you think that?

**Comment by simonbcn** [comment]
By default in Linux the installations from sources are installed in `/usr/local/...`. In this case the locales are in `/usr/local/share/locale/...`.

**Comment by lazka** [comment]
OK, I see, thanks. Which distro are you on?

On debian based distros you need to pass "--install-layout=deb" to setup.py install to get it install to the right paths ("/usr" instead of "/usr/local")

**Comment by simonbcn** [comment]
Ubuntu 14.04 64 bits

Ok, now it works.

**Comment by lazka** [comment]
I'd recommend to use one of the PPAs for day to day usage and if you want to change something you can run QL directly from the git source checkout.

https://quodlibet.readthedocs.org/en/latest/downloads.html#ubuntu
https://quodlibet.readthedocs.org/en/latest/development/devenv.html#linux-logo-linux
