### ISSUE TITLE
quodlibet --print-playing on radio stations returns station info and not song info

### ISSUE THREAD

**Issue by TiZ-EX1** [quodlibet/quodlibet#1742]
Version 3.5.1, on Xubuntu 15.10.

My initial impression when encountering this was that it reminded me of #1158. I reported that one way back when. But this is different. Whereas that issue at least made the title of the playing song available, now I can't get even that. Now I just get information about the station.

    TiZLappy:~$ quodlibet --print-playing
    http://www.181.fm - 181.fm - Rock 181 (Active Rock)

Expected output:

    TiZLappy:~$ quodlibet --print-playing
    Nirvana - In Bloom

If you need any more information, I'm glad to help; QL has been my music player of choice since I made the switch to Linux in 2008 and you guys always come through when things break. I really appreciate your hard work. :)

**Comment by lazka** [comment]
Thanks. Will be in 3.5.2

**Comment by TiZ-EX1** [comment]
Thanks for the fast fix!
