### ISSUE TITLE
Synchronized lyrics plugin doesn't display anything

### ISSUE THREAD

**Issue by declension** [quodlibet/quodlibet#1743]
Whilst it does seem to be working under the hood (I've debugged it, and added logging), the Synchronised Lyrics plugin fails to expose any (visible) area as 
### Expected:

Visible lyrics in the main UI when an appropriate `.lrc` file is found
### Actual

None visible
### Test System

Ubuntu 15.10
Python: 2.7.10
Mutagen: 1.31
GTK+: 3.16.7 (X11)
PyGObject: 3.16.2
### Potential fix

Hard to say without seeing the intended functionality, but on this setup, setting `expand=True` on https://github.com/quodlibet/quodlibet/blob/master/quodlibet/quodlibet/ext/events/synchronizedlyrics.py#L138 shows it is working at least.

(separate problem, but there are a lot of warnings generated in the logs of the type:
`/home/nick/workspace/quodlibet/quodlibet/quodlibet/ext/events/synchronizedlyrics.py:261: Warning: Source ID 5001 was not found when attempting to remove it
  GLib.source_remove(self._timers[curIndex][1])`)

**Comment by elfalem** [comment]
I'm attempting to work on this. I'm able to observe the issue on my regular quodlibet installation (3.7.1) on Linux Mint. However, when attempting to run quodlibet from the master branch, I get:
````
Traceback (most recent call last):
  File "./quodlibet.py", line 14, in <module>
    sys.exit(main())
  File "/mnt/Projects/quodlibet/quodlibet/quodlibet/main.py", line 26, in main
    quodlibet.init_cli(config_file=config_file)
  File "/mnt/Projects/quodlibet/quodlibet/quodlibet/_init.py", line 144, in init_cli
    _init_formats()
  File "/mnt/Projects/quodlibet/quodlibet/quodlibet/_init.py", line 123, in _init_formats
    from quodlibet.formats import init
  File "/mnt/Projects/quodlibet/quodlibet/quodlibet/formats/__init__.py", line 9, in <module>
    from ._audio import PEOPLE, AudioFile, DUMMY_SONG, decode_value, \
  File "/mnt/Projects/quodlibet/quodlibet/quodlibet/formats/_audio.py", line 33, in <module>
    from ._image import ImageContainer
  File "/mnt/Projects/quodlibet/quodlibet/quodlibet/formats/_image.py", line 8, in <module>
    from ._misc import AudioFileError
  File "/mnt/Projects/quodlibet/quodlibet/quodlibet/formats/_misc.py", line 12, in <module>
    import mutagen
ImportError: No module named 'mutagen'
````

Mutagen is already installed (otherwise the regular installation wouldn't work, right?). `apt-cache policy python-mutagen` returns:
````
python-mutagen:
  Installed: 1.34.1-0~ppa0~trusty
  Candidate: 1.34.1-0~ppa0~trusty
  Version table:
 *** 1.34.1-0~ppa0~trusty 100
        100 /var/lib/dpkg/status
     1.31-1ubuntu1 500
        500 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
        500 http://archive.ubuntu.com/ubuntu xenial/universe i386 Packages
````

I've tried this on Ubuntu 16 as well and I get the same error.

**Comment by elfalem** [comment]
After testing recent releases (greater than 3.7.1) one by one, I've discovered that typing `./quodlibet.py` on version 3.9.0 or later attempts to use python3 and fails. Instead, typing `python quodlibet.py` (to use python2) works. I'm not exactly sure what's going on but I'm now able to run the code from the master branch.

**Comment by lazka** [comment]
We default to Python 3 now to get more testing by default. You can use both, but Python 2 is likely more stable.

**Comment by declension** [comment]
Good work, thanks @elfalem
