### ISSUE TITLE
Ratings are not preserved when music directory is moved

### ISSUE THREAD

**Issue by nodiscc** [quodlibet/quodlibet#1747]
Hi, I recently renamed my root music directory (previously `~/Music`, now `~/MUSIC`);

When starting Quod Libet, I got an expected error message (couldn't locate file) and a blank music library, set my new directory as library path in `Preferences > Library`, then press `Re-scan library`.  Quod Libet correctly displays all the files at the new location, but all song ratings are gone.

Is it possible to recover/apply the old rating information to the renamed directory?

I guess songs are indexed by path? Would another indexing method be possible (hash? filesize?)

I tried enabling storage of tags in file ID3 tags, which works around this problem (apparently not for all filetypes), but I can't rely on it since I have albums shared over bittorrent (bittorrent clients expect the file to never be modified).

Possibly related to issues at https://github.com/quodlibet/quodlibet/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+rating

Thanks in advance, and thank you everyone for your work on quodlibet/exfalso!

**Comment by urielz** [comment]
Yes I've been fighting with this as well. Playcount is not preserved as well. You could try CreamyCookie suggestion:
https://github.com/quodlibet/quodlibet/issues/1680

**Comment by nodiscc** [comment]
Thank you, 

> You have to enable the Preferences->Tags->Save Ratings and Play Counts (and enter the same email address) otherwise yes they're stored in the pickle (the songs file).

> At the moment I always use the "Force Write" plugin

this solution involves writing the data directly to the file, unfortunately I can't touch them:

> I can't rely on it since I have albums shared over bittorrent (bittorrent clients expect the file to never be modified). 

Clients will throw errors or redownload/overwrite the file.

 * Ideally I'm looking for a tool/plugin to read/write the rating data to a file in the same directory as the files (`.ratings` or `.tags`?)
 * or edit the pickle/song file to notify QL of the path change
 * or QL could recognize the files on something else than their path (checksum/filesize...)

The first solution would be great if it can be implemented (I can't help there). The _Export metadata_ plugin could provide a base.

I'm still looking for a solution. I will decrease my use of ratings if they can't be preserved, since the files will likely move again.

**Comment by declension** [comment]
Understood. Some notes:

1. There is one coming around, see #1627 (note to self/us - we should follow that PR up actually) and IIRC another from _way_ back too?
2. Hmm, trickier, though to an extent this is exactly what file watching ("Auto Library Update" etc) is for - see #1315 for some background - and I really want to get that one nailed some time.
3. Ugh - that's a fundamental re-think of libraries really. But then, there are a few fundamental-rethink type of issues (e.g. #518)

**Comment by nodiscc** [comment]
1. Requires the export to be done manually between _2 copies_ of the files, (will not work when moving the files) though I agree it would be a nice addition to the presented use case:
>This is useful when you have an existing collection of music files encoded in one format that you want to replace with files encoded in another format, such as migrating an old MP3 collection to newly-ripped FLACs

2. Seems the way to go. I don't know how tricky it would be to implement. Just a note that the files before/after only have in common: 1. a part of their path (`Artist - Album/filename.ext`); 2. They are the same file (identical checksums, length, tags...)

3. Maybe a full rethink is not appropriate, indexing by checksums/hashes would bring other problems (touching a single byte of the file alters the hash, need to re-index, etc.)

Another solution that would fit my (edge) case is a `Move Library...` feature, that takes care of moving the files and altering their path in the song store.

As a side note, there's another case where ratings are lost: Pre-listen to a new album (outside the library; eg. using the filesystem view), assign some ratings while listening; then you decide to finally add this album to your library by moving it there. After moving the files ratings are gone.

**Comment by nodiscc** [comment]
I have currently worked around this problem by enabling saving of metadata directly to the audio file. As previously mentioned it breaks simultaneous sharing of those files over bittorrent.

I made this trade-off because it also allows me to access my library over the network (SFTP server) on multiple machines and synchronize the rating information on all of them.
