### ISSUE TITLE
[docs] How to add a browser pane with songs grouped by rating?

### ISSUE THREAD

**Issue by nodiscc** [quodlibet/quodlibet#1749]
Hi, I've been trying to add a left-side browser pane grouping the tracks by rating and have failed :/

    artist
    <genre> - <album>
    rating

In the pane browser preferences, I set these 3 panes. First two are working fine, and the third doesn't, just displaying a pane whose title is `Notation` (Rating in french), and a single entry `Inconnu` (Unknown) is displayed, which regroups _all_ tracks, regardless of their rating.

Is this normal and how do I get this working? (I want a "playlist" excluding all but 1 and 2-stars rated tracks)

Thanks

**Comment by urielz** [comment]
try this:
~rating

**Comment by nodiscc** [comment]
@urielz Thanks a lot, it works.

Is there any documentation on the filter syntax, or a full list of search operators/fields? I was expecting to find it in the dialog itself (there's no help button), or in quod libet docs (couldn't find it, or is it related to https://github.com/quodlibet/quodlibet/blob/master/quodlibet/docs/guide/searching.rst?).

**Comment by declension** [comment]
Yeah, we should probably add some tooltips somewhere in the Paned Browser prefs.

However [Tag Patterns in general are documented](https://quodlibet.readthedocs.org/en/latest/guide/tags/patterns.html), but then there was nothing to say that's what they are, I guess

**Comment by nodiscc** [comment]
Yep, a tooltip or simple help links/buttons to https://quodlibet.readthedocs.org/en/latest/guide/tags/internal_tags.html and https://quodlibet.readthedocs.org/en/latest/guide/tags/patterns.html in the prefs dialog would be nice.

I guess this is in https://github.com/quodlibet/quodlibet/blob/master/quodlibet/quodlibet/browsers/paned/prefs.py but don't know how to add it.

Thanks for the help

**Comment by declension** [comment]
Note that pressing `F1` generally now takes you to help (the [RTD user guide](https://quodlibet.readthedocs.org/en/latest/guide/index.html) for us).

**Comment by nodiscc** [comment]
Thank you @declension
