### ISSUE TITLE
mpris on Plasma5 (KDE)

### ISSUE THREAD

**Issue by ochurlaud** [quodlibet/quodlibet#1755]
Is quodlibet using mpris?

On Plasma5 there is a multimedia centralizer, and quolibet doesn't appear in it.

It would be great to have it integrated with the desktop (Almost certain that it's just a freedesktop norm to follow on qdbus)

**Comment by lazka** [comment]
Quod Libet includes a MPRIS plugin implementing MPRIS 1 and 2.

**Comment by ochurlaud** [comment]
Ok, then it's strange: Plasma should then work... I'll ask the KDE guys when I have some time.

Thx for your answer anyway :)

**Comment by lazka** [comment]
Maybe it's a bug on our side... are there any errors when starting QL in the terminal with the mpris plugin enabled and the "multimedia centralizer" open?

What distro are you using? (so i can give it a try..)

**Comment by ochurlaud** [comment]
Error (in french sorry)
W: Impossible d importer python-feedparser. Désactivation de navigateur de flux audio.

It says roughly: impossible to import python-feedparser Desactivate the browser of audio stream
I'm on Archlinux with Plasma 5

**Comment by lazka** [comment]
Thanks. That message is not related to this problem. I'll give Plasma5 on Arch a spin when I find the time.

**Comment by ochurlaud** [comment]
I'll ask on kde what is needed in a few secs.. I'm currently starting IRC

**Comment by ochurlaud** [comment]
They use mpris2.

**Comment by ochurlaud** [comment]
It works now. So it's either plasma5.5 or me having being stupid before.
