### ISSUE TITLE
Minimize to tray on Plasma5 (KDE)

### ISSUE THREAD

**Issue by ochurlaud** [quodlibet/quodlibet#1756]
Is there an option or a plugin to install to minimize to tray?

I'm using Plasma5 on Archlinux and when I quit QuodLibet, it quits for real...

Thx

**Comment by urielz** [comment]
Go to "Music", then "Plugins" and activate "Tray Icon", that should do it.

**Comment by ochurlaud** [comment]
Ok, the problem is that KDE doesn't show it in the tray bar...

**Comment by lazka** [comment]
Afaik plasma5 no longer supports tray icons. Might be related: #1343

**Comment by ochurlaud** [comment]
It does support, but it follows this spec: http://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/ which is (as I understood) the right one...

**Comment by lazka** [comment]
We don't support that atm (I didn't know that that was used outside of Ubuntu where mpris + the unity task bar integration is usually enough..)

See https://lazka.github.io/pgi-docs/#AppIndicator3-0.1

**Comment by ochurlaud** [comment]
Is it what is used?

**Comment by lazka** [comment]
> Is it what is used?

What are you referring to?

On Linux there are four things for exposing a menu of some sorts:

1) The old tray icon spec, which is X11 only, deprecated in most toolkits but still in use by things like Skype/VLC/dropbox etc. We do support that atm.
2) Ubuntu Unity provides an API for exposing a menu in the left taskbar. We support that atm.
3) Then there is MPRIS1/2 which some DEs use to build a mediaplayer widget (Ubuntu for example, or when using GNOME with an MPRIS extension). We do support that.
4) And then there is the spec you mentioned which we currently don't support, but I guess we should if KDE moved to it.

**Comment by ochurlaud** [comment]
Ok. I think KDE was using what you put in 1). But they movedto 4) and 3).

I was asking if your link (api) is what you currently use.

**Comment by lazka** [comment]
> Ok. I think KDE was using what you put in 1). But they movedto 4) and 3).

Possible. I remember that early Ubuntu versions only used MPRIS if (4) was implemented.. maybe that's the case here too

> I was asking if your link (api) is what you currently use.

This is the Python API for implementing https://wiki.freedesktop.org/www/Specifications/StatusNotifierItem/ (If I'm not mistaken..)

**Comment by ochurlaud** [comment]
So it means that it's *almost* solved isn't it?

**Comment by ArchangeGabriel** [comment]
Note that Plasma 5.5, which came out today, has a new change related to this:
>In response to feedback, we've rewritten support for legacy applications not using the StatusNotifier standard for system tray icons.

(From https://dot.kde.org/2015/12/08/plasma-55-beautiful-new-artwork)

**Comment by ochurlaud** [comment]
Yes I saw that too... Nevertheless they reimplement the 1) on lazka's list which is old and deprecated, so going to the new things (4) seems needed.

**Comment by lazka** [comment]
> Note that Plasma 5.5, which came out today, has a new change related to this:
>
    In response to feedback, we've rewritten support for legacy applications not using the StatusNotifier standard for system tray icons.
>
(From https://dot.kde.org/2015/12/08/plasma-55-beautiful-new-artwork)

Thanks for the info.

> Yes I saw that too... Nevertheless they reimplement the 1) on lazka's list which is old and deprecated, so going to the new things (4) seems needed.

Agreed, especially as (1) doesn't work with Wayland.

**Comment by lazka** [comment]
Basics are working now with master. But you need libappindicator-gtk3 (afaics this in only in AUR)

**Comment by ochurlaud** [comment]
I've got it. I'll check this. Thx a lot.

**Comment by lazka** [comment]
Things should work now in master, so I'm closing this. If there are any problems please report them here or in a new issue.

**Comment by ochurlaud** [comment]
@lazka: is this patched in 3.5.3?  thx

**Comment by lazka** [comment]
No, but as pointed out in https://github.com/quodlibet/quodlibet/issues/1756#issuecomment-163047883 the old tray icon should work again if you update to plasma 5.5.

This will be part of 3.6

I guess we should look into providing an unstable build for the AUR..

**Comment by lazka** [comment]
See #1805

**Comment by ochurlaud** [comment]
I can write one if you want.... With the upgrade of plasma 5.5 it doesn't *really* work. You have an icon, but most of the time black, never scaled.

**Comment by ochurlaud** [comment]
As you can see it's not perfect... http://postimg.org/image/56dhc05x5/

Sometimes (not often) it works

**Comment by ochurlaud** [comment]
The image is from master branch

**Comment by lazka** [comment]
What's your output for `python2 -Wignore -c "from gi.repository import AppIndicator3"`

**Comment by ochurlaud** [comment]
No output....

**Comment by lazka** [comment]
Weird.. Do you see the "Show Quod Libet" menu item on top of the menu?

Here is how it looks on an uptodate arch (plasma 5.5.4). I've installed quodlibet-git and libappindicator-gtk3 through yaourt

![screen](https://cloud.githubusercontent.com/assets/991986/12881436/1aa50022-ce4a-11e5-8c49-f8aacd851013.jpg)

**Comment by ochurlaud** [comment]
Ok... I'm on plasma 5.5.4 as well, libappindicator-gtk3 as well but it's still on the same....

Don't know why... I'll try to check if I'm missing something. Are you using the Tray Icon plugin? 

Very strange.

**Comment by ochurlaud** [comment]
I just completely uninstall quodlibet and check the config of plasma.. Still the same.
Next try: in virtualbox.

**Comment by ochurlaud** [comment]
D: 249.60: fake.plugins.trayicon.get_indicator_impl: use app indicator: False 

--- This might be the problem?

**Comment by lazka** [comment]
hm, It's plasma here.. maybe because I use gdm3, I'll have a look

(That's why I asked about the "Show Quod Libet" item, which is only there if AppIndicator3 is used..)

**Comment by CreamyCookie** [comment]
Okay, AFAICS this was fixed in #1813 (or followups). I've also just tested the Tray Icon plugin (Kubuntu 18.04) and it works flawlessly.
