### ISSUE TITLE
No "cover" key in query result with non-ASCII characters

### ISSUE THREAD

**Issue by fredele** [quodlibet/quodlibet#1759]
Consider the following code :
```python   
    from quodlibet import library
    lib = library.init("/home/user/.quodlibet/songs")
    qr_list = lib.query("artist=my_artist")
    for song in qr_list :
         print song
```

If I run the query with an american artist (supposed with no non-ascii characters in all the resulting files ...), everything works fine : I've got the value "cover" in the result set correctly.
But, if I query a french singer (obviously, with non-ascii characters like é, è, ç, à, etc....) the value from the key "cover" is None.

Obviously, in the GUI, there's no problem, the cover do appear and they exist all on my harddrive as "Folder.jpg".

I'm running Ubuntu 15.04 64 bits with the latest GNOME desktop.

I hope I do not miss something....    Thanks !

**Comment by lazka** [comment]
> But, if I query a french singer (obviously, with non-ascii characters like é, è, ç, à, etc....) the value from the key "cover" is None.

Which "cover" value do you mean?

**Comment by fredele** [comment]
As an example, when I run the code I gave, with non-ascii characters in the tags, I' ve got in the console windows something like that:

```

{'performer': u'Miles Davis', 'date': u'1955', '~format': u'MP3', 'composer': u'Andy Razaf/Paul Denniker',      'genre': u'Jazz', 'tracknumber': u'4', 'discnumber': u'1/1', '~mountpoint': u'/media/frederic/DATA', 'album': u'The New Miles Davis Quintet', '~#bitrate': 320, 'title': u"S'posin", '~#length': 320.0251, 'artist': u'Miles Davis', 'cover': u'/media/frederic/DATA/Medias/Musique/Jazz/Miles Davis/The New Miles Davis Quintet/Folder.jpg', '~#added': 1448803527, '~filename': "/media/frederic/DATA/Medias/Musique/Jazz/Miles Davis/The New Miles Davis Quintet/04 S'posin.mp3", '~#mtime': 1433261656.139536, '~#filesize': 12805356}

```
There's the key 'cover', with the jpeg corresponding to the cover of the album.
This key **does not** appear at all if I try with a french singer : no cover key in the dictionary at all.

**Comment by lazka** [comment]
I see. QL does not use/interpret this "cover" tag for finding images. I don't know what put it there, maybe some other application?

**Comment by fredele** [comment]
OK, so the ascii thing is just a coincidence ... I tried on 2 albums only ...

I think it's JRiver Media Center who wrote this tag in the files, as this software does not prefix the tags he wrote with everything to say he wrote it ..

I just tought  there's a problem by fiding the cover, finally there's not.

Sorry for the inconvenience !
