### ISSUE TITLE
Add a keyboard shortcut to fast-forward (and rewind) 10 seconds (configurable)

### ISSUE THREAD

**Issue by CreamyCookie** [quodlibet/quodlibet#1763]
Preferably it shouldn't change the current focus in the main window. I'd like this to check out if the current song is the one I'm looking for in a list of songs without having to use the mouse.

If they aren't used elsewhere, <kbd>LEFT</kbd> would be great for **rewind**, and <kbd>RIGHT</kbd> would work for **fast-forward**.

**Comment by timpulver** [comment]
>it shouldn't change the current focus in the main window

Good point. I’d vote for `cmd + shift + right` to skip and `cmd + right` to seek (working without changing the focus from everywhere).

**Comment by CreamyCookie** [comment]
Seems like has been added: https://quodlibet.readthedocs.io/en/quodlibet-3.6/guide/shortcuts.html#main-window
