### ISSUE TITLE
"Previous" item in tray icon menu does not jump to previous song

### ISSUE THREAD

**Issue by nodiscc** [quodlibet/quodlibet#1764]
The `Previous` menu item in the systay/notification area right-click menu works exactly as the `Previous` button in the main UI: when a song is playing, pressing that button sets the play position at the beginning of the current song.

It is almost impossible to actually jump to the previous song using this menu item: pressing it once jumps to the beginning of the song and closes the menu. Even with extra-fast mouse actions, you will not be able to reach that menu item again within the first second of the song. Therefore it does not work as a `Previous` button (only as a `Restart song`) button.

This menu item should not restart the song. Instead it should jump directly to the previous song (or the delay for the Previous track action has to be increased)

**Comment by lazka** [comment]
Sounds reasonable.

**Comment by declension** [comment]
+1
