### ISSUE TITLE
sorting of tag patterns in song lists

### ISSUE THREAD

**Issue by pfps** [quodlibet/quodlibet#1767]
Version: Quod Libet 3.5.-1
OS: Fedora 23

Several tags (artist, albumartist, ...) have associated sort tags.  However, these sort tags are not effective in tag patterns.  I have a column in my song list that is <artist|<artist>|<composer>> but when I sort on this column the sort values for artist are not used.  I think that the appropriate sort values should be used for sorting here.

**Comment by pfps** [comment]
This also happens in panes (in the paned browser).  Strange that I didn't notice it there first.

**Comment by lazka** [comment]
Yeah, not implemented yet for patterns. The paned browser doesn't do sorting tags in all cases.

**Comment by pfps** [comment]
The fix for sorting in song lists is very short!  (Determining the fix was much tougher.)  Sorting for tag patterns already modifies the pattern so all that was needed was to add in a modification that replaces a tag with an associated sort tag by the correct pattern.  Two lines do the trick in the get_sort_tag function

    if tag.startswith("<"):
        for key, value in replace_order.iteritems():
            tag = tag.replace("<%s>" % key, "<%s>" % value)
>        for key, value in TAG_TO_SORT.iteritems():
>            tag = tag.replace("<%s>" % key, "<{1}|<{1}>|<{0}>>".format(key,value))
        tag = Pattern(tag).format

If you want, I can put together a patch. for this.

Correct sorting in the paned browser would be more difficult.

**Comment by pfps** [comment]
I created a pull request with this patch as
https://github.com/quodlibet/quodlibet/pull/1783

**Comment by pfps** [comment]
I'll close this and add a new issue for sorting in the paned browser.
