### ISSUE TITLE
allow users to union tags (like ~performers does)

### ISSUE THREAD

**Issue by pfps** [quodlibet/quodlibet#1768]
In the paned browser I want to have a pane that shows artists (for popular music) and composers (for classical music).  I can create a tag pattern <artist|<artist>|<composer>> that gets close, but this doesn't work right for those classical albums that have a value for artist (as is useful for classical albums with a major performer).  What is missing is the ability to union the values from multiple tags, like ~performers does. 
Extending tied tags, perhaps with syntax like ~artist~+composer, would give users control over this useful feature.

**Comment by pfps** [comment]
As a partial step in this direction I put together a small change that unions together the values of tied tags in the paned browser instead of what currently happens.  That is, where ~artist~composer would have displayed an entry in a pane like
  The Smashing Pumpkins - Billy Corgan
now there are two entries
  Billy Corgan
  The Smashing Pumpkins
If this is considered a desirable change, I can provide the patch.

**Comment by pfps** [comment]
I'm creating a separate issue that is similar to this one, but does not use new syntax.

**Comment by lazka** [comment]
Maybe ``~foo+bar``?

@declension any thoughts on this?

**Comment by declension** [comment]
It's not a problem I've ever encountered myself... in fact I don't even use (or like much) "traditional" tied tags for that matter.

...but that said, yes I'd prefer `~foo+bar` too:
 * the plus feels like as near union as we can get
 * and `|` (as per Python sets) isn't an option here
 * either way, +1 to creating _real_ lists of values (which can be _rendered_ to comma-separated strings)

**Comment by pfps** [comment]
The next message is a long exposition of the situation and some arguments at the end as to why I prefer making a change.  Hopefully it will not be too mangled.

**Comment by pfps** [comment]
Displaying Tags with Multiple Values

Tags are displayed in two different kinds of places.  In one kind of place,
such as in song displays and song lists, all the values of a tag are shown,
concatenated together and separated by commas.  In the other kind of place,
such as in the paned browser, the values of a tag are splilt and shown
separately.

For the album Ella and Basie!, a collaboration between Ella Fitzgerald
and Count Basie, an artist column in the song list would show

  Ella Fitzgerald, Count Basie

and an artist column in the paned browser would show

  Count Basie
  Ella Fitzgerald

In concatenation situations the display of tag patterns and tied tags is
determined by taking the concatenation results of the tags and concatenating
with the rest of the pattern or with the results of the other tags separated
by " - ", respectively.  So the tied tag ~artist~composer for Them There
Eyes in Ella and Basie! would display as

  Ella Fitzgerald, Count Basie - Maceo Pinkard, Doris Tauber, William Tracey

Similarly the tag pattern <artist>/<composer> would display as

  Ella Fitzgerald, Count Basie/Maceo Pinkard, Doris Tauber, William Tracey

In the split situation tag patterns are displayed by taking the
concatenation display and splitting up the multiple values, producing for
<artist>/<composer> as above the following six values

  Count Basie/Doris Tauber
  Count Basie/Maceo Pinkard
  Count Basie/William Tracey
  Ella Fitzgerald/Doris Tauber
  Ella Fitzgerald/Maceo Pinkard
  Ella Fitzgerald/William Tracey

In the split situation tied tags are currently treated as if they were a tag
pattern of the form <tag1> - <tag2>.  I think that tied tags should be
instead treated as they were like the internal tags, e.g., ~people, that
union values from several other tags, so the tied tag ~artist~composer would
produce the following five values

  Count Basie
  Doris Tauber
  Ella Fitzgerald
  Maceo Pinkard
  William Tracey

I think that this is the natural interpretation for tied tags in split
situations, and is a change that should be made to Quodlibet.


Other options:
1/ Do nothing, there is no need for unioning tags in split situations.
2/ Add a new syntax for union tags, perhaps ~tag1+tag2

One advantage of option 2 is that there is no change to Quodlibet's
behaviour.  However, the current behaviour can be obtained by a simple
change from tied tags to tag patterns.

A disadvantage of option 2 is that it requires new syntax, which has to be
implemented, and the proposed change is quite easy to implement.  Another
disadvantage is that the natural interpretation of tied tags in split
situations is the union one, mirroring internal tags that behave similarly.

**Comment by pfps** [comment]
The effect of this is in my changes to sorting in the paned browser, so this can be closed.
