### ISSUE TITLE
Allow multiple entries for selecting artwork (cover) file 

### ISSUE THREAD

**Issue by fredele** [quodlibet/quodlibet#1769]
in util/cover/built_in at line around 75, if force_filame is set, QL picks up the exact name specified, but it seems obvious for me that "Folder" or "folder" is quiet the same thing.
Shouldn't QL understand this againts of letting the user manually correct the capital letter  ?

Just an idea.

Also, if force_filame is not set and if you have 2 jpg's, namely "cover" and "folder", folder wins (see around line 139 in the same file.) but both got the same number of points.
Now image that "cover" is the big picture and "folder" what it should be, a  thumbnail, you get the little picture.
What if QL would read the picture size and let the winner be the biggest picture ?

**Comment by lazka** [comment]
Sounds good.

I'd prefer if we'd have a fixed order for all the keywords and not depend on the image size since

1) knowing the image size requires loading parts of the image which slows things down
2) the naming is something the user controls while the image size is harder to change

**Comment by zsau** [comment]
What about allowing multiple space-separated filenames in the "force filename" field, to be used as a priority list? I like the feature, but can't use it since I have some cover.png and some cover.jpg.

Wouldn't require any UI changes, though we'd have to allow backslash-escaping of spaces in the fienames I guess.

**Comment by lazka** [comment]
> What about allowing multiple space-separated filenames in the "force filename" field, to be used as a priority list? I like the feature, but can't use it since I have some cover.png and some cover.jpg.

Yeah. Maybe use the platform path separator instead.
Also see #374 which adds some code do allow unix wildcards.

**Comment by declension** [comment]
Yep multiple files in order sounds good. 
I'd probably favour either comma separated or platform path separator (which would be a bit more complicated in terms of communicating to the user)

**Comment by Hunter16g** [comment]
Would it be possible to allow wildcards ? cover.* would work perfectly for me (and probably a lot of people, since a loarge library is very likely to have covers in different formats, even if you use a fixed filename).
