### ISSUE TITLE
Ogg stream stops playing when the current song information is updated

### ISSUE THREAD

**Issue by CreamyCookie** [quodlibet/quodlibet#1770]
I was listening to this Radio Stream: http://stream-dc1.radioparadise.com/rp_192m.ogg (from [here](https://www.radioparadise.com/rp_2.php#name=Listen)). Before the next song would have started, and thus when the song information was updated by the radio server, the player simply stopped playing. The title of the next song in the stream is displayed in QL.

This isn't the case for the AAC stream, but it doesn't seem to include song information.

I'm fairly certain this bug wasn't happening before. I'm on Ubuntu 15.10 / 64bit. QL from PPA: 3.5.1

btw. Happy Holidays! :snowman:  :smiley:

**Comment by lazka** [comment]
Related: #1454

Here it starts to endless re-buffer, is that also the case on your end?

We added a workaround to the GStreamer backend (15dbfb02251fd643b03a71ea) that no longer seems to work.

**Comment by CreamyCookie** [comment]
> Here it starts to endless re-buffer, is that also the case on your end?

I just tried again. You're somewhat right. It does buffer for quite some time, but it seems to have stopped now.

Also, something weird happened but only once in all my tries: After re-buffering for 10 seconds or so, it played the stream again. But maybe it was a coincidence that it happened exactly as the song was over.

**Comment by CreamyCookie** [comment]
@lazka I don't know if this is related, but I listened to the AAC stream of Radio Paradise earlier. Then maybe an hour later, I pressed the play button. Interestingly the song continued playing where I had left off. About before the song was over QL switched to the next available radio stream.

**Comment by CreamyCookie** [comment]
Nice, just tried again. This might to be fixed now. 

@lazka Could you test on your end if the endless buffering is gone there too?
