### ISSUE TITLE
ImportError: Mutagen 1.22 required. 1.20 found.

### ISSUE THREAD

**Issue by xzvf** [quodlibet/quodlibet#1771]
After upgrading Ubuntu, I'm getting this error when trying to start Quodlibet.  Here is the full message:
----------------------------------
Traceback (most recent call last):
  File "/usr/bin/quodlibet", line 203, in <module>
    main()
  File "/usr/bin/quodlibet", line 37, in main
    import quodlibet.library
  File "/usr/lib/python2.7/dist-packages/quodlibet/library/__init__.py", line 19, in <module>
    import quodlibet.formats as formats
  File "/usr/lib/python2.7/dist-packages/quodlibet/formats/__init__.py", line 71, in <module>
    init()
  File "/usr/lib/python2.7/dist-packages/quodlibet/formats/__init__.py", line 32, in init
    (MinVersions.MUTAGEN, mutagen.version_string))
ImportError: Mutagen 1.22 required. 1.20 found.
----------------------------------

I've tried re-installing, but no luck.  I guess this may be a Python or Ubuntu error, but I thought I'd see if anyone had experienced this.  Any ideas?

**Comment by lazka** [comment]
mutagen 1.22 was required in QL 3.4, so I guess you upgraded to Ubuntu 15.10, but mutagen 1.20 is part of Ubuntu 12.04.

So you upgraded from 12.04 to 14.04 to 15.10?

Anyway, it seems your upgrade failed somehow. Try running the "Software Updater"..

**Comment by xzvf** [comment]
Thanks for looking in.  Yes, I think I may have skipped the 2013 releases, but I upgraded to 14.04 a long time ago.  In the past few weeks, I moved to the 2015 releases, first trying 15.04, then going to 15.10.  Software Updater says everything is up to date.

If you think this would be more appropriate for the Ubuntu crowd, let me know and I'll try there.  I started here because I only encounter problems when starting QL.

**Comment by lazka** [comment]
python-mutagen1.30 is in Ubuntu main, so there should be one. Make sure you have the software repos enabled: https://help.ubuntu.com/community/Repositories/Ubuntu#Ubuntu_Software_Tab

If QL is the only thing broken on your system you can try using our PPA: https://quodlibet.readthedocs.org/en/latest/downloads.html#ubuntu

**Comment by xzvf** [comment]
Ah... success.  Poking around for python-mutagen, I found that I still had a mutagen-1.20 folder in my home directory.  I must've installed it "manually" a few years ago.  I removed all the files from that installation, reinstalled QL, and the music's playing...

Thanks for your help!

**Comment by lazka** [comment]
No problem.

If you want the newest version of QL please try our PPA.
