### ISSUE TITLE
Feature Request: Playlist sync to devices (specifically, an iPod Classic)

### ISSUE THREAD

**Issue by becatlibra-zz** [quodlibet/quodlibet#1772]
This is the only thing holding me back from using QL 100% of the time.  The ability to 'Copy to Device' from playlists is awesome, however it does not copy the actual playlist, which leaves me with a large amount of music on my device without my playlists to order them.

The ability to 'subscribe' to playlists, essentially a correlation of playlists to specific devices, would be ideal as well.  I find myself having to use rhythmbox for this when I would really prefer to use QL.

Thanks

Benjamin

**Comment by lazka** [comment]
Our device support hasn't improved much in the last 5 years.. so don't expect much. But I agree that it would be nice to have.

**Comment by CreamyCookie** [comment]
Device support was removed, so I'm closing this. (There are also plugins for exporting playlists and the files they contain.)
