### ISSUE TITLE
--enqueue-files fails for commas in filenames

### ISSUE THREAD

**Issue by Jimi-James** [quodlibet/quodlibet#1773]
Simple problem. I'm trying to enqueue filenames that have commas in an automated script, but since , is the delimiter, I have to somehow work around the filenames that have them. So, I tried escaping each comma with a \, but that doesn't seem to work. Then, I tried wrapping each filename in quotes. That has opened up a big nest of issues I don't understand that I'm trying to work through over at http://stackoverflow.com/questions/34498976/quodlibet-suddenly-wont-accept-file-list-unless-i-manually-type-it-in , but the basic summary is, quodlibet doesn't play nice when I have double quotes in a sed line. My question is, what am I supposed to do if I want to automatically (not by manually typing the filenames in) enqueue songs that have commas in their filenames? Is there an escape character I don't know about, and if so, why isn't it the obvious backslash?

**Comment by declension** [comment]
Thanks for the report

**Comment by declension** [comment]
Backslashed commas should now work, but for your use case you will probably get a cleaner solution using `enqueue` with [the control file](http://quodlibet.readthedocs.org/en/latest/guide/interacting.html), thus avoiding any comma-escaping and newline-conversion in the first place...

**Comment by Jimi-James** [comment]
Whoa. I've never heard of the control file before. That's pretty great.
