### ISSUE TITLE
What is View Lyrics plugin for?

### ISSUE THREAD

**Issue by felixsanz** [quodlibet/quodlibet#1778]
Searching for lyrics appear 2 plugins:

* **Lyrics Window**
Shows a window containing lyrics of the playing song.

* **View Lyrics**
Displays lyrics beneath the song list.

The first is the lyrics window. But what does "View Lyrics" do? I activate it and i can't spot the difference!

**Comment by declension** [comment]
Also, in newer versions, [Synchronized Lyrics](https://github.com/quodlibet/quodlibet/blob/master/quodlibet/quodlibet/ext/events/synchronizedlyrics.py) - a more real-time version (but with problems - see #1743).

There's also the "internal" support (little known I think) in the form of the Lyrics tab in the song information dialog. This at one point supported lyrics at http://lyricwiki.org but this now has become very limited in what it offers - see the long discussions at #273.

The _Lyrics Window_ plugin (a songsmenu plugin, so you need to right-click on the song(s)) sidesteps some of those problems by presenting as a webview in a seprate window.

Yes it needs a bit of tidying and documenting at the very least.

**Comment by felixsanz** [comment]
You explained all but "View Lyrics", hah

**Comment by declension** [comment]
Oh.. it displays the lyrics (file) beneath the songlist, in a collapsible pane. Once you have songs with lyrics (try searching with `~lyrics=/./`), it will display them automatically on play. 

![lyrics plugin screenshot](https://cloud.githubusercontent.com/assets/3322808/12179534/68785c16-b56f-11e5-9a17-add4adbbdad2.png)

Note there's also a PR for _another_ (better) [Lyrics Window plugin](https://github.com/quodlibet/quodlibet/pull/1709/files)

**Comment by felixsanz** [comment]
that makes sense. thank you!

**Comment by CreamyCookie** [comment]
I've made an enhancement request that, when implemented, would (likely) result in the View Lyrics and the Lyrics Window plugin being merged: #1628
