### ISSUE TITLE
Rating symbols are not shown properly in Windows 10

### ISSUE THREAD

**Issue by brachiel** [quodlibet/quodlibet#1779]
Since upgrading from Windows 8.1 to Windows 10, both the Windows ports of version 3.4 and 3.5.1 do not show the rating "stars" properly but show placeholder-symbols instead.

Copy-pasting the characters into other programs in windows works (they are shown as proper stars there).

![bugreport](https://cloud.githubusercontent.com/assets/303558/12213348/ca92525a-b676-11e5-9879-9a344e73c481.png)

Audio device: GStreamer (directsoundsink)
Python: 2.7.9
Mutagen: 1.31
GTK+: 3.14.9
PyGObject: 3.14.0
GStreamer: 1.4.5.0

**Comment by lazka** [comment]
This seems to work with the newest gtk windows build.. so should be fixed with the next release.
