### ISSUE TITLE
Get rid of pywin32

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1781]
msys2 currently doesn't include pywin32 [0] so we should look into getting rid of it and replace it with ctypes or cffi.

Needed for #1718

[0] https://github.com/Alexpux/MINGW-packages/issues/751

**Comment by mingwandroid** [comment]
Getting rid of platform specific modules for cross platform solutions is always a win in terms of maintainer. pywin32 should not, IMHO, exist.

**Comment by lazka** [comment]
Remaining:

* The named pipe code (haven't looked into it)
* The shortcut reading code: Afaics not possible though ctypes, if this is the only blocker we might drop that feature.

**Comment by MichaelUrman** [comment]
After way too many missteps I figured out the shortcut reading code using just ctypes on Python 3. Do you have a preference between shortest code and most complete? (About 20-25 lines vs up to about 75.) The key is in the funky prototypes (this omits a couple steps):
```
WINFUNCTYPE(HRESULT, LPGUID, LPVOID)(0, "QueryInterface")(pShellLinkW, byref(IID_IPersistFile), byref(pPersistFile))
WINFUNCTYPE(HRESULT, LPOLESTR, DWORD)(5, "Load")(pPersistFile, path, 0)
WINFUNCTYPE(HRESULT, LPWSTR, INT, LPWIN32_FIND_DATAW, DWORD)(3, "GetPath")(pShellLinkW, path, 260, LPWIN32_FIND_DATAW(), 0)
```

**Comment by lazka** [comment]
Awesome! I had already given up on that part and started working on parsing lnk files manually.

Not sure what the difference is between shortest and most complete, so I guess most complete sounds good.

**Comment by MichaelUrman** [comment]
The shortest comes down to lines like I pasted: ugly, but compact. The most complete declares classes that correspond to the interfaces and uses metaclass machinery to make methods (less ugly, but arguably wasteful when only three methods are called), so the equivalent lines read more like:
```
pShellLink.QueryInterface(byref(IPersistFile.IID), pointer(pPersistFile))
pPersistFile.Load(path, 0)
pShellLink.GetPath(path, 260, LPWIN32_FIND_DATAW(), 0)
```
There's some level of hardcoding the COM interfaces no matter what. Is QL on Python 3 these days, or do I need to check this against Python 2? I can attach a working example and let you sort it out, or figure out how to create a PR.

**Comment by lazka** [comment]
We are moving to a py2/py3 code base atm, but py2 is the default. You can just post the example and I'll take it from there. 

(You can of course also integrate it yourself, see https://quodlibet.readthedocs.org/en/latest/development/devenv.html for the details)

**Comment by MichaelUrman** [comment]
Alright. Here are the first three variants. The readlink1 is fairly straightforward, readlink2 tries to go metaclass, and readlink3 is simplified to the bare minimum. I suspect the metaclass is a little dodgy, and requires py3 syntax and OrderedDict anyway, so I'd suggest 1 or 3.
[readlink.zip](https://github.com/quodlibet/quodlibet/files/179626/readlink.zip)

**Comment by lazka** [comment]
Thanks

**Comment by lazka** [comment]
Pushed a metaclass variant which works on py2, thanks again!
