### ISSUE TITLE
change to tied tags in the paned browser (union values instead of concatenating them)

### ISSUE THREAD

**Issue by pfps** [quodlibet/quodlibet#1786]
I propose that tied tags work differently in the paned browser.  See below
for a particular example.

Right now tied tags work the same in the paned browser as they do in other
places.  A tied tag concatenates the two tags together and multiple values
produce multiple entries.  This is like a concatenation followed by a
multiplication operation, i.e., if there are three values for the first tag
and two for the second then there are six double entries.

I propose that tied tags in the paned browser instead be treated like
internal tags that combine several other tags, e.g., as ~performers works.
This turns tied tags into a union operation, i.e., five single entries for
the above case.

I think that this behaviour fits better into the philosophy of the paned
browser.

The current behaviour of tied tags could be obtained by the tag pattern
<tag1> - <tag2>.

I have a patch that implements this proposed change.  The documentation in 
https://quodlibet.readthedocs.org/en/latest/guide/browse/paned.html would
have to be changed as well.

Example

Tags	artist	Satyajit Ray
	artist	TEST
	artist	TEST1
	albumartist	Wes Anderson
	albumartist	WA

Pane		~artist~albumartist

Current		Satyajit Ray - WA
		Satyajit Ray - Wes Anderson
		TEST - WA
		TEST - Wes Anderson
		TEST1 - WA
		TEST1 - Wes Anderson
		
Proposed	Satyajit Ray
		TEST
		TEST1
		WA
		Wes Anderson

**Comment by pfps** [comment]
The following diff appears to implement this change.  Only one function was changed.  The extent of the change to quodlibet is illustrated in the changed tests.



idefix quodlibet> git diff
diff --git a/quodlibet/quodlibet/formats/_audio.py b/quodlibet/quodlibet/formats/_audio.py
index 5048fee..4849138 100644
--- a/quodlibet/quodlibet/formats/_audio.py
+++ b/quodlibet/quodlibet/formats/_audio.py
@@ -533,7 +533,7 @@ class AudioFile(dict, ImageContainer):
             return [] if v is None else v.split("\n")
 
     def list_separate(self, key, connector=" - "):
-        """Similar to list, but will return a list of all combinations
+        """Similar to list, but will return a list of all values
         for tied tags instead of one comma separated string.
 
         In case of tied tags the result will be unicode, otherwise
@@ -541,15 +541,14 @@ class AudioFile(dict, ImageContainer):
         """
 
         if key[:1] == "~" and "~" in key[1:]:
-            vals = []
-            for v in map(self.__call__, util.tagsplit(key)):
-                v = decode_value(key, v)
-                if v:
-                    vals.append(v.split("\n"))
-            r = [[]]
-            for x in vals:
-                r = [i + [y] for y in x for i in r]
-            return map(connector.join, r)
+            vals = \
+                filter(None,
+                map(lambda x: isinstance(x, basestring) and x or str(x),
+                map(lambda x: (isinstance(x, float) and "%.2f" % x) or x,
+                (self(tag) for tag in util.tagsplit(key)))))
+            vals = (val.split("\n") for val in vals)
+            r = [j for i in vals for j in i]
+            return r
         else:
             return self.list(key)
 
diff --git a/quodlibet/tests/test_browsers_paned.py b/quodlibet/tests/test_browsers_paned.py
index 2e48e3b..9b090cd 100644
--- a/quodlibet/tests/test_browsers_paned.py
+++ b/quodlibet/tests/test_browsers_paned.py
@@ -180,7 +180,7 @@ class TPaneConfig(TestCase):
         self.failUnlessEqual(p.title, "Title / Artist")
         self.failUnlessEqual(p.tags, {"title", "artist"})
 
-        self.failUnlessEqual(p.format(SONGS[0]), ["three - boris"])
+        self.failUnlessEqual(p.format(SONGS[0]), ["three", "boris"])
         self.failIf(p.has_markup)
 
     def test_pattern(self):
diff --git a/quodlibet/tests/test_formats__audio.py b/quodlibet/tests/test_formats__audio.py
index f7584db..e33494b 100644
--- a/quodlibet/tests/test_formats__audio.py
+++ b/quodlibet/tests/test_formats__audio.py
@@ -164,15 +164,15 @@ class TAudioFile(TestCase):
             self.failUnlessEqual(bar_1_1.list_separate(key), [bar_1_1(key)])
 
         self.failUnlessEqual(bar_2_1.list_separate("~artist~album"),
-                             ['Foo - Bar', 'I have two artists - Bar'])
+                             ['Foo', 'I have two artists', 'Bar'])
 
         self.failUnlessEqual(bar_2_1.list_separate("~artist~~#track"),
-                             ['Foo - 1', 'I have two artists - 1'])
+                             ['Foo', 'I have two artists', '1'])
 
     def test_list_list_separate_types(self):
         res = bar_2_1.list_separate("~~#track~artist~~filename")
-        self.assertEqual(res, [u'1 - Foo - does not/exist',
-                               u'1 - I have two artists - does not/exist'])
+        self.assertEqual(res, [u'1', u'Foo', 
+                               u'I have two artists', u'does not/exist'])
 
     def test_comma(self):
         for key in bar_1_1.realkeys():
diff --git a/quodlibet/tests/test_pattern.py b/quodlibet/tests/test_pattern.py
index b54c8b6..a6cf144 100644
--- a/quodlibet/tests/test_pattern.py
+++ b/quodlibet/tests/test_pattern.py
@@ -418,10 +418,10 @@ class TPatternFormatList(_TPattern):
                           {'aa', 'ab', 'ba', 'bb'})
         pat = Pattern('<~performer~artist>')
         s.failUnlessEqual(pat.format_list(s.d),
-                          {'a - foo', 'b - foo', 'a - bar', 'b - bar'})
+                          {'a', 'b', 'bar', 'foo'})
         pat = Pattern('<performer~artist>')
         s.failUnlessEqual(pat.format_list(s.d),
-                          {'a - foo', 'b - foo', 'a - bar', 'b - bar'})
+                          {'a', 'b', 'bar', 'foo'})
         pat = Pattern('<artist|<artist>.|<performer>>')
         s.failUnlessEqual(pat.format_list(s.d), {'foo.', 'bar.'})
         pat = Pattern('<artist|<artist|<artist>.|<performer>>>')

**Comment by lazka** [comment]
Interesting idea. I think I'd prefer adding a new union syntax as you proposed in #1768, as this makes it usable in multiple places.

**Comment by declension** [comment]
+1

**Comment by pfps** [comment]
On thinking more about this I am still of the opinion that changing the behaviour of tied tags is better than adding new syntax.  I think that the natural behaviour of tied tags should be like the internal tags that union together several other tags and not like tag patterns.  I'm putting together a longer description of the change that I'll drop into this (or another) discussion.

**Comment by lazka** [comment]
While replacing the existing behavior would be easier for us it would also break existing patterns.

**Comment by pfps** [comment]
My proposal would certainly change behaviour in one area.

Patterns are used in lots of places, but how many  of them use the separated way of formatting tags besides the paned browser?  The change in behaviour is only for this.

**Comment by pfps** [comment]
Addressed by recent changes to the paned browser
