### ISSUE TITLE
QL 3.5.2 and OS X SIP (El Capitan)

### ISSUE THREAD

**Issue by urielz** [quodlibet/quodlibet#1787]
Thanks for the update. QL 3.5.2 has the same issue with El Capitan as QL 3.4.1 had (see #1697), executing QL returns:

/Applications/QuodLibet.app/Contents/MacOS/quodlibet is:

dyld: Library not loaded: @executable_path/../Resources/lib/libgstreamer-1.0.0.dylib
Referenced from: /Applications/QuodLibet.app/Contents/Resources/libexec/gstreamer-1.0/gst-plugin-scanner
Reason: image not found

Disabling SIP, executing QL one time and re-enabling SIP solves the problem.

**Comment by lazka** [comment]
I build it from the wrong branch :(

**Comment by urielz** [comment]
oh that explains! :)

**Comment by lazka** [comment]
new builds are out

**Comment by urielz** [comment]
Thank you! Working fine now.
