### ISSUE TITLE
Album List doesn't filter tracks correctly on search

### ISSUE THREAD

**Issue by kaffeeundsalz** [quodlibet/quodlibet#1791]
I've been experimenting with the Album List view and noticed some odd behaviour when I tried to search my library. It seems to me that whenever two or more albums by the same artist have the same name, all tracks of them are included in the tracklist no matter what the search pattern should filter out. For example, take a look at this screenshot:

<img width="1067" alt="screen shot 2016-01-17 at 20 45 38" src="https://cloud.githubusercontent.com/assets/4942960/12379510/d755c566-bd5c-11e5-9e42-de829a542b2c.png">

As you can see from the search field, I've told Quod Libet to only show FLAC files and only from the directory named _Lossless. A specific album is selected in the Album List. In the tracklist however, Quod Libet still shows me the MP3 version of the album, which is located in a completely different directory and should also be filtered out by the ~format=FLAC string.

Am I doing something wrong? I did a search for this here, but couldn't find an existing issue that describes this behaviour. I'm running Quod Libet 3.5.2 under OS X 10.11.2 El Capitan.

**Comment by declension** [comment]
No, this is about right. Unfortunately it doesn't work quite how one would hope it does; the query syntax is not against the song library but _against the album library_.

In your case would your _duplicated_ albums (by QL's definition) are both matching against the filter (but: being aggregated in the Album Browser view itself - note the `20 tracks` for a [10-track album](https://en.wikipedia.org/wiki/Shallow_Grave_%28album%29).

When the songlist is populated, however, it's pulling all the matching songs from that album filter into the songlist, which matches _all_ the songs in the two duplicates, mp3 and FLAC versions.

This definitely feels kinda buggy... but also semi-known behaviour for duplicate albums. 

As for workarounds, I can only suggest either the excellent [mp3fs](https://khenriks.github.io/mp3fs/), or keeping one set of the albums out of QL, at least until maybe #202 is sorted (don't hold your breath though - it's over 6 years old).

**Comment by kaffeeundsalz** [comment]
Ah, I see – thank you for making this clear. I actually noticed that the duplicate albums are already collected in the Album list view, noticeable not only by the total track count you mentioned, but also the two different date formats.

I don't think this is a big issue at all. For now, I'll just stick with the Search Library view, since I can get the same filtering just right with something like `&(~dirname=_Lossless, ~format=FLAC, album=Shallow Grave)`. I was even thinking of ditching the MP3 version altogether. My new phone has plenty of space for lossless music ;)

So, just to make sure I didn't miss anything: What you're saying is that there is no viable way to change this behaviour on the code side of Quod Libet?

**Comment by declension** [comment]
Glad it helped. Don't think there's any easy way out of this, and I think the existing tickets probably cover the bases here so closing this one.
