### ISSUE TITLE
Let users customize the «now playing» infos

### ISSUE THREAD

**Issue by timpulver** [quodlibet/quodlibet#1803]
<img width="374" alt="bildschirmfoto 2016-02-01 um 22 46 49" src="https://cloud.githubusercontent.com/assets/1055819/12732410/b9d3b9be-c935-11e5-9a05-d5827c75dad3.png">

Would be nice if we could customize the information being displayed for the currently playing track as we can with the columns in list view right now.

When I have a lot of tracks enqueued and *random* enabled, there is no chance to access the information which is relevant to me while listening to tracks (the record label is the most important).

**Comment by kaffeeundsalz** [comment]
Right click the now playing info and click "Edit Display".

**Comment by timpulver** [comment]
Wohoo! Thanks so much! This is great!
