### ISSUE TITLE
How to add custom tag to «now playing» display?

### ISSUE THREAD

**Issue by timpulver** [quodlibet/quodlibet#1804]
I tag all of my MP3s / FLACs with a custom tag `CATALOGNUMBER`. Can you tell me how to add it to the «now playing» display? I already had a look at [Tag Formats & Spec Deviations](https://quodlibet.readthedocs.org/en/latest/development/formats.html), but could not figure it out…

Here is a short (silent) MP3-file which includes this tag: [Dropbox direct link](https://www.dropbox.com/s/5qhds3u971b6fys/Empty_Yate_Tagged.mp3?dl=1)

This is the display code I’m using:

```
[span size='large'][b]<artist>[/b][/span] – <title><~length| (<~length>)>
[b]<album>[/b]
[i]<organization> – <catalognumber>[/i]
```

And another question – can I escape `[` and `]`? I would like to display the catalognumber in square braces.

**Comment by declension** [comment]
You should just be able to use `[<catalognumber>]` - escaping won't be necessary here.

**Comment by kaffeeundsalz** [comment]
I actually can't find a <catalognumber> tag in the MP3 file you provided. When I add it manually, the now playing display works just as described by @declension: Adding `[catalognumber]` to the display code will show the info in the exact way you requested it. Escaping is indeed not needed here. If you do have to escape characters (e.g. the vertical bar `|`), use a backslash, as in `\|`.

**Comment by timpulver** [comment]
Hmm. This isn’t working for me.
I just dumped the id3-tags with [mutagen lib](http://code.google.com/p/mutagen). May it be a problem that `CATALOGNUMBER` is in uppercase?

Running `mid3v2 --list-raw sometrack.mp3 | grep TXXX` outputs:

```
…
TXXX(encoding=3, desc=u'CATALOGNUMBER', text=[u'AVN020']) 
…
```

**Comment by timpulver** [comment]
@kaffeeundsalz Could you do the same with the file which was working to compare it to my tag?

**Comment by lazka** [comment]
#48

**Comment by timpulver** [comment]
@lazka 
Ah okay, that’s it. So no custom tags for me right now in Quod Libet. But I’m happy the label is being displayed (as it’s a standard tag).

**Comment by kaffeeundsalz** [comment]
Right, that's it. I actually noticed this when I investigated the file provided by @timpulver with an external tag editor. The CATALOGNUMBER tag is present, but Quodlibet writes to something like QuodLibet::catalognumber. I didn't see this at first because I added the tag with QuodLibet.

**Comment by declension** [comment]
Sounds like we can close this now and leave #48 open (still..)?
