### ISSUE TITLE
Provide an Arch AUR unstable package

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1805]
https://aur.archlinux.org/

**Comment by lazka** [comment]
master is good, things rarely break. See the changes compared to the latest stable release: https://quodlibet.readthedocs.org/en/latest/packaging.html#changes

i just see that I forgot to add libappindicator-gtk3 there..

**Comment by ochurlaud** [comment]
https://aur4.archlinux.org/packages/quodlibet-git/

**Comment by lazka** [comment]
Thanks. https://quodlibet.readthedocs.org/en/latest/downloads.html#arch

Is there a "user friendly" way to install things from the AUR which we should include in the download page? Or a link explaining things?

**Comment by ochurlaud** [comment]
If people use the AUR they should already know it...  

The link you provide is the best one. There are some helpers, but it's not supported by Archlinux and it's not always a good idea for beginners.

**Comment by ochurlaud** [comment]
It could be good that in the About menu, it says master on master... (now it's 3.5.-1)

**Comment by lazka** [comment]
> If people use the AUR they should already know it...
>
> The link you provide is the best one. There are some helpers, but it's not supported by Archlinux and it's not always a good idea for beginners.

OK, thanks.

> It could be good that in the About menu, it says master on master... (now it's 3.5.-1)

I'll look into that.

**Comment by lazka** [comment]
>> It could be good that in the About menu, it says master on master... (now it's 3.5.-1)

>I'll look into that.

See 6bcac749aa286da528f9b59e
