### ISSUE TITLE
Look into flatpak

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1806]
https://wiki.gnome.org/Projects/SandboxedApps

**Comment by probonopd** [comment]
You might also be interested in http://www.appimage.org, a binary distribution format specifically geared toward upstream packaging. An AppImage is essentially a self-mounting ISO that contains an application and all dependencies it needs to run that cannot be assumed to be part of the base system (Linux distribution). The advantage is that it works already today on most not-too-outdated Linux distributions, and the user needs to download or install absolutely nothing besides the AppImage of the application in question. 

Projects like MuseScore, Krita, and Scribus are already using it for distribution of nightlies and/or releases to users of various distributions.

**Comment by lazka** [comment]
Thanks

**Comment by lazka** [comment]
lollypop has some code here: https://github.com/gnumdk/lollypop/tree/master/flatpak

**Comment by charlesjt** [comment]
Today Flatpak is an excellent way to distribute applications for Linux. It has a better [adoption](https://kamikazow.wordpress.com/2017/02/09/adoption-of-flatpak-vs-snap/) among distributions, offers advanced features and is easy to install.

**Comment by probonopd** [comment]
@charlesjt AppImage has the best "adoption" because it does not need special support (such as runtimes) from the distribution besides FUSE and common libraries that are "there" anyways.

**Comment by charlesjt** [comment]
@probonopd No, only one distro ([Nitrux OS](https://nxos.org/)) offers AppImages by default. On the other hand it is necessary to install additional stuff such as appimaged, firejail, etc. to have additional features (which offer other alternatives such as flatpak by default).

Although it is true that AppImages can be executed in most distributions, not all of them have a consistent behavior, such as adding a desktop access with icon or in some cases, 2 different files are offered (one for older distros). On the other hand, other projects require that your software be installable which rules out this alternative, not always adds a check sum to the file loaded (the user must add excecution permissions in addition to manually locate it somewhere so that it is not accidentally deleted}.

AppImages is an excellent method for **portable** applications, but not a better alternative to Flatpak (lower application weight, dependency deduplication, atomic updates, etc.) Before I was open to using Snap on my system, but it's really a problem It works out of Ubuntu or Solus OS out of the box, in addition to requiring use of AppArmor and external repos.

**Comment by probonopd** [comment]
> No, only one distro (Nitrux OS) offers AppImages by default. 

A distribution does not _need_ to offer AppImage. 

> Although it is true that AppImages can be executed in most distributions, not all of them have a consistent behavior

That is the whole point of the AppImage format - application authors are in full control and can do as they please.

> AppImages is an excellent method for portable applications

Then I guess my ask is that Quodlibet is (also) provided as a _portable_ application.

**Comment by charlesjt** [comment]
> A distribution does not need to offer AppImage.

On the contrary, it is very necessary. Without `appimaged` in the distro repos for better integration or some kind of integration in the most popular software stores is **not** user friendly.

> That is the whole point of the AppImage format - application authors are in full control and can do as they please.

Come on, it's quite a disadvantage. Although there are very different software distribution methods, there are certain _standards_ for the desktop. In some cases missing a icon, desktop icon, a descriptive name, etc. it is not a reflection of total control on the part of the developer, but an oversight or a problem in the distribution system.

> Then I guess my ask is that Quodlibet is (also) provided as a portable application.

In Linux I don't see the need for portable applications and less if they are a audio player IMO. Anyway, if it's your interest, open a new dedicated ticket for the topic, here at least my +1 for Flatpak...

**Comment by probonopd** [comment]
> some kind of integration in the most popular software stores

AppImage needs no software stores (although AppImages can be distributed by them). We have had Macs and PCs for decades without app stores. And to this day, you don't download Photoshop from the App Store.

> application authors are in full control

A matter of perspective. For me this is a great advantage. When I encounter "missing a icon, desktop icon, a descriptive name, etc." I know that _the application author_ either wants it this way, or should fix it. Google, for example, forbids third parties to redistribute Chrome. And I can see why. They want Chrome delivered 100% in the way they intend it, no icons changed, etc.

> In Linux I don't see the need for portable applications

I do. I hop between tens of distributions and many more distribution versions on a constant basis and if I had to download every application specifically for every distribution and version, this would not be fun.

**Comment by Meriipu** [comment]
does appimage mean you have to download all dependencies (in the image) even if you already have them installed?

**Comment by probonopd** [comment]
> does appimage mean you have to download all dependencies (in the image) even if you already have them installed?

It depends on what an author of an application has put inside the AppImage. Generally we recommend to only bundle such dependencies that cannot be expected to be already present on the target systems (which, again, the application author can define) in a recent enough version. So if the author compiles the software on a system with libfoo version n, and is targeting systems that have libfoo no lower than version n preinstalled as part of their default installation, then he does not need to bundle libfoo.

For specialized libraries that cannot be expected to be present in a recent enough version on all target systems, yes, these need to be bundled inside the AppImage, with the result that they have to be downloaded and stored more than once. This is not much different from how Windows, macOS, Android, and iOS apps work in most cases. It's the price to pay for having no dependencies other than the base system.

**Comment by charlesjt** [comment]
@probonopd I see what you get out of context some of my comments, but respond to yours respectfully.

> AppImage needs no software stores (although AppImages can be distributed by them). We have had Macs and PCs for decades without app stores. And to this day, you don't download Photoshop from the App Store.

Sure, I was relying on the current model that the distros are using for the user to install new software, but consider the following: a) Before the software stores on Linux, the user had the package manager, who automate the entire process via CLI or with dedicated GUIs eg Gdebi, yumex, synaptic, etc. _without app stores_ b) A Windows executable shows a wizard that automates the process and installs everything it owes where it should _without app stores_ and c) In macOS it appears a wizard where it says "copy X file in X folder", where everything is perfectly ordered _without app stores_.

No, it's not the same. With AppImages the user must first verify the download file (if a checksum is available), move the downloaded file to a well-known directory, mark the file as executable, [...], create a desktop file if it is not available, etc. (many times repeat the process just for an update).

> A matter of perspective. For me this is a great advantage. When I encounter "missing a icon, desktop icon, a descriptive name, etc." I know that the application author either wants it this way, or should fix it.

But it was not the case. With Snap or Flatpak an author could do the same if he wanted, but there is a greater concern to follow the desktop standards, something that helps a lot to the user experience.

> Google, for example, forbids third parties to redistribute Chrome. And I can see why. They want Chrome delivered 100% in the way they intend it, no icons changed, etc.

Yeah! It's a great disadvantage of AppImages, something that is possible using Flatpak. Eg Google Chrome, Spotify, etc.

> I do. I hop between tens of distributions and many more distribution versions on a constant basis and if I had to download every application specifically for every distribution and version, this would not be fun.

The concept of portable application is totally different from what you describe ... Are those applications that don't need to be installed in the system, can be used in live distros or from pendrives maybe ...

> You have a point here, does Linux really need the 1.001th audio player...

**Of course yes!** the variety of software available is something that the user always appreciates. What Linux doesn't need is another "universal" method to install applications (this does negatively affect the user experience)... But in the FLOSS world it is about freedom.

**Comment by probonopd** [comment]
> In macOS it appears a wizard where it says "copy X file in X folder", where everything is perfectly ordered without app stores.

With most (albeit not all) Mac apps it's literally just an `.app` bundle (a directory that the Finder treats as an opaque object) that you _may_ copy to `/Applications` - or _any other location that pleases you_.

> No, it's not the same. With AppImages the user must (...) move the downloaded file to a well-known directory

Like on the Mac, _can_, not _must_.  An AppImage will also run perfectly fine right from the Downloads directory, or, for that matter _anywhere_.

> mark the file as executable, [...], create a desktop file if it is not available, etc. (many times repeat the process just for an update)

...or use the optional `appimaged` daemon which automates this for you if you prefer that.

> Yeah! It's a great disadvantage of AppImages, something that is possible using Flatpak. Eg Google Chrome, Spotify, etc.

With AppImage the upstream application author (Google, Spotify, Chrome) can 100% decide what to put into the AppImage. So totally _not_ a disadvantage!

> The concept of portable application is totally different from what you describe ... Are those applications that don't need to be installed in the system, can be used in live distros or from pendrives maybe ...

Extactly: _All_ AppImages are "portable apps" in the sense that they do not have to be installed and are relocatedable. I run all my AppImages on multiple different systems like Ubuntu, Fedora, openSUSE etc. without installing or re-downloading them.

**Comment by charlesjt** [comment]
> With most (albeit not all) Mac apps it's literally just an .app bundle

Yes I know. The point is that the system offers an integration that makes it simple for user, something that AppImage doesn't offer and you deny that it is necessary and contradicts itself when mentioning `appimaged` as an optional module (it should be mandatory for things to work as they should)

> With AppImage the upstream application author (Google, Spotify, Chrome) can 100% decide what to put into the AppImage. So totally not a disadvantage!

Come on, if that were the case, there would not be the problem of distribution of third-party software that we have in the gnu/linux ecosystem. That third parties can package software like Google Chrome in a legal way is a **real advantage.**

@probonopd Actually I don't want to continue answering, because you omit many of my comments where I argue that AppImage is **not a good idea** and I only receive replies of the type "please see this from another point of view" that doesn't contribute much to the discussion. If you are still interested in talking about AppImage please open a new ticket for the topic, because here the topic is Flatpak.

**Comment by lazka** [comment]
> I included all Python dependencies for the plugins, as well as the binary for kakasi. Any remaining errors in the plugin dialog are missing GStreamer modules. (I'm don't know exactly how those work with Flatpak so I'm not sure if they could be bundled with the application.)

lollypop adds gst-libav and gst-plugins-ugly, seems like a good idea to do the same (at some point): https://github.com/flathub/org.gnome.Lollypop/blob/master/org.gnome.Lollypop.json#L39

**Comment by lazka** [comment]
Things should now work without patches with current master (I haven't tested it though)

**Comment by fkrull** [comment]
> For the remaining patches: Might be that we just have to use XDG_DATA_DIRS in those places

Good find. I'm gonna give it a go.

> lollypop adds gst-libav and gst-plugins-ugly, seems like a good idea to do the same (at some point)

I haven't really looked at how GStreamer plugins work, if there's an extension point or exactly what is included. I didn't have any issues playing MP3s, but I didn't try more exotic formats yet. It's worth investigating further, but I need to clean up my branches first.

**Comment by lazka** [comment]
> For the remaining patches: Might be that we just have to use XDG_DATA_DIRS in those places
> 
> Good find. I'm gonna give it a go.

(It should be fixed in master)

> lollypop adds gst-libav and gst-plugins-ugly, seems like a good idea to do the same (at some point)
> 
> I haven't really looked at how GStreamer plugins work, if there's an extension point or exactly what is included. I didn't have any issues playing MP3s, but I didn't try more exotic formats yet. It's worth investigating further, but I need to clean up my branches first.

It's just a bunch of extra .so files in a dir, I assume the dir gets merged with the dir from the base platform(?) and gstreamer will find them.

I think it's needed for wma and aac for example.

**Comment by lazka** [comment]
@fkrull do you have any plans for moving this to flathub in the end?

**Comment by fkrull** [comment]
I submitted the package to Flathub now: https://github.com/flathub/flathub/pull/400

**Comment by lazka** [comment]
Thanks!

**Comment by Peque** [comment]
Great news! :blush:

**Comment by lazka** [comment]
https://flathub.org/apps/details/io.github.quodlibet.QuodLibet
