### ISSUE TITLE
Album Browser is missing all text (regression)

### ISSUE THREAD

**Issue by ned2** [quodlibet/quodlibet#1811]
Since commit 754c23c0a1f5ceaca2558da922feee7f9f4dff0f, my Album Browser is not showing any text pertaining to album details. I'm running Ubuntu 15.04 and have attached screenshot and debug logs.

[quodlibet_2016-02-08.txt](https://github.com/quodlibet/quodlibet/files/120682/quodlibet_2016-02-08.txt)
![no_text_album_browser](https://cloud.githubusercontent.com/assets/2831640/12872518/0a398628-cdf9-11e5-921a-f1c61ee20948.png)

**Comment by declension** [comment]
What's your album display pattern set to?

**Comment by lazka** [comment]
Related #1807

**Comment by ned2** [comment]
Ah right, yes it's coming up as completely empty. When I switch to a commit that does not have the regression my pattern appears in the preferences box. 

When I put it back in there, everything is well. Maybe something like it's reading a different (and empty) attribute in my profile, with the old one still sitting in there.

**Comment by declension** [comment]
Thanks, I'll have a look

**Comment by declension** [comment]
I can't replicate locally, but am spinning up a virtual one instead.

@ned2 might be too late - but if you could retry this process somehow but updating to _current_ `HEAD` (includes extra logging) that would be helpful in investigating.
