### ISSUE TITLE
Use a two-state play/pause icon

### ISSUE THREAD

**Issue by timpulver** [quodlibet/quodlibet#1814]
When player is playing the icon of the button should switch to a pause icon.

![](https://cdn1.iconfinder.com/data/icons/material-audio-video/20/pause-circle-outline-128.png)

**Comment by kaffeeundsalz** [comment]
Please don't. This will open the door to confusing people because a common standard is missing for one of the fundamental UI issues: Will a button show **the current state of its function**, or will it show **the action to be performed when the button is used**? This is a mess across different applications, and the only solution to avoid this is to do without changing button icons altogether. I'm very happy with the pressed/not pressed button state QuodLibet uses now; after all, this _is_ a UI standard. Please don't change this.

**Comment by timpulver** [comment]
Check every other music player around. The current behavior *is not* standard!

**Comment by kaffeeundsalz** [comment]
Yes – I know how other players do it. And I hate it ;) That's why I actually use the progress bar on my iPhone to be sure about the current playing status. No offense; I was thinking that I'm not the only one with this problem. If everybody else thinks this is a good idea, go implement it :)

**Comment by timpulver** [comment]
I understand what you mean. I just think it’s in general a good idea to stick to the stuff people know and expect if it’s not *too* bad.

**Comment by lazka** [comment]
play/pause:
* more in line with other players
* less interface noise without a pressed button

toggle-play:
* imo easier to see the state (but this could be because I'm used to it)
* users are used to it

not sure..

**Comment by timpulver** [comment]
I’m sure it’s a bit confusing for most people switching over from other players to not have play/pause.

**Comment by declension** [comment]
I can see both arguments, but actually am marginally in favour of changing (i.e. to play/pause), or at least more prominent highlighting (theme dependent, I know).

Users being used to it is an issue; if it's bad enough we could make it a preference...

**Comment by urielz** [comment]
I could be persuaded either way. Both methods have their advantages. To add one more thing:

Right now the play icon (the little icon to the left of the song currently playing) changes to the pause icon when the song is paused. In this respect it would be more visually consistent to also change the main play icon to the pause icon as the OP suggested...

**Comment by CreamyCookie** [comment]
Maybe make it configurable. Sort of like you can change the symbol used for rating (e.g. `rating_symbol_blank`), there could be a `play_symbol` and a `pause_symbol`.

For those who like the current version, the config would include:

```
play_symbol = ⏯
pause_symbol = ⏯
```

For those who want it to change, the config would be:

```
play_symbol = ▶️
pause_symbol = ⏸
```

Of course, we still have to decide what becomes the default. :stuck_out_tongue_winking_eye:

**Comment by lazka** [comment]
I've changed it in master now.. let's give it a try...

**Comment by declension** [comment]
Great! Like it a lot on first usage..

**Comment by CreamyCookie** [comment]
Yeah, I agree. It feels better.

**Comment by lazka** [comment]
Ok, lets close this then - sorry @kaffeeundsalz :)
