### ISSUE TITLE
[Feature Request] Custom Filter-Lists

### ISSUE THREAD

**Issue by timpulver** [quodlibet/quodlibet#1815]
Currently there is the possibility to filter by year and artist. Would be great if there was the possibility to filter by other tags as well. For me `organization` would be interesting.

<img width="610" alt="bildschirmfoto 2016-02-09 um 22 24 18" src="https://cloud.githubusercontent.com/assets/1055819/12931075/389d4660-cf7c-11e5-8cb9-0528c2ec0492.png">

**Comment by declension** [comment]
Are you referring to the [paned browser](https://quodlibet.readthedocs.org/en/latest/guide/browse/paned.html)?

This is fully configurable for any tag (or even pattern) including `organization` - click the preferences icon as described in [Pane Configuration](https://quodlibet.readthedocs.org/en/latest/guide/browse/paned.html#pane-configuration).

If you're talking about _Filter on x_, there is the [Filter On Any Tag plugin](https://github.com/quodlibet/quodlibet/blob/master/quodlibet/quodlibet/ext/songsmenu/filterall.py) to do that

**Comment by timpulver** [comment]
Thanks @declension. Using the preference icon did what I wanted to do. I created a new issue because the icon position is misleading – [#1816](https://github.com/quodlibet/quodlibet/issues/1816).
