### ISSUE TITLE
OS X media keys not working

### ISSUE THREAD

**Issue by linkxvi** [quodlibet/quodlibet#1817]
In OS X, the system media keys (F7, F8, F9) won't control Quodlibet, while they work flawlessly with other players.

I'm running OS X 10.11.3 (15D21)

**Comment by lazka** [comment]
We have some experimental support build in, but disabled by default.

You can delete the line containing QUODLIBET_NO_MMKEYS in QuodLibet.app/Contents/MacOS/_launcher

I guess we should make it an option in the "advanced preferences" plugin at least.

**Comment by timpulver** [comment]
>You can delete the line containing QUODLIBET_NO_MMKEYS in QuodLibet.app/Contents/MacOS/_launcher

Does not work on OS X 10.11.3. When pressing one of the media keys iTunes is launched and Quod Libet does not react. Other music players like Spotify or Vox work fine with media keys on my system.

**Comment by lazka** [comment]
There was a plan [0] to add SPMediaKeyTap [0] which apparently other players are using, but I'm not sure how one would do that.

I've added an mmkeys switch in the advanced preferences plugin now so it can be tested without env vars. It used to kinda work at some point but something might have broken it since then.. I work in a VM, so no mmkeys :/

[0] https://github.com/elelay/quodlibet-osx-bundle/issues/8
[1] https://github.com/nevyn/SPMediaKeyTap

**Comment by lazka** [comment]
Good to know. I think there were some problems with it slowing down mouse events and the global menu because it has to inspect every user input event which is a problem if QL is busy.

**Comment by timpulver** [comment]
No problems so far, but I will let you know…

**Comment by ldexterldesign** [comment]
Hey all,

*First post*

Thanks for software - really excited to leave iTunes behind

OS X media keys would be great - can I ask what the situation is with activating them; if at all possible? They don't work out of the box for me 😕

Hope to hear back

Kind thanks

**Comment by urielz** [comment]
@ldexterldesign They're disabled by default. Go to Music, Plugins and then Advanced Preferences.  Change "OS X Multimedia Keys" from false to true.

**Comment by ldexterldesign** [comment]
Hey @urielz,

Awesome!

Hadn't seen these plugins - is there an official URL to browse plugins/documentation or is everything WYSIWYG inside the app'?

Hope to hear back

Kind thanks

**Comment by ldexterldesign** [comment]
BUMP

**Comment by urielz** [comment]
Not that I'm aware of. I haven't explored all the available plugins as well, but every now and then people mentioned here in the forums new things you can do with a plugin that I was not aware of. QL is amazing :)

**Comment by ldexterldesign** [comment]
@urielz got a forum URL or do you literally mean here [https://github.com/quodlibet/quodlibet/issues]?

Yours hopefully

**Comment by urielz** [comment]
Yes, I meant /quodlibet/issues. -cheers

**Comment by ldexterldesign** [comment]
@urielz hmm, since there's no easy way to subscribe (e.g. Atom/RSS) to new https://github.com/quodlibet/quodlibet/issues issues it's unlikely I'll check back here unless I have a bug/enhancement/featureRequest/help/idea/question/suggestion

Does anyone know a way of accessing the list of plugins outside the app'?

Yours hopefully

**Comment by declension** [comment]
@ldexterldesign this is not really something that can work reliably, as the enabled, relevant, non-erroring plugins can only be determined at runtime.

If you just want to have a look at a rough list of _all_ of them, you could try something like:

```shell
python -c 'import site; print "\n".join(site.getsitepackages())' | xargs -i@ find @/quodlibet/ext/ -mindepth 1 -maxdepth 2 -type d -exec basename {} \;  -o -regex '.*[a-z]\.py' -exec basename {} \; 2>/dev/null
```

**Comment by lazka** [comment]
Now enabled by default. Let's see...

**Comment by ldexterldesign** [comment]
Hey @declension,

Thanks for reply

Unfortunately the script failed:

```python
Apple-MacBook-Pro:Desktop ldexterldesign$ python -c 'import site; print "\n".join(site.getsitepackages())' | xargs -i@ find @/quodlibet/ext/ -mindepth 2 -maxdepth 2 -type d -exec basename {} \;  -o -regex '.*[a-z]\.py' -exec basename {} \; 2>/dev/null | sort 
close failed in file object destructor:
sys.excepthook is missing
lost sys.stderr
```

Hope to hear back, since I'd be interested in the output

Kind thanks

**Comment by ldexterldesign** [comment]
@lazka great!

IMO it makes more sense to have "Music > Plugins > Advanced Preferences" grouped with "Quod Libet > Preferences" - I would have never discovered the OS X multimedia keys option without asking 😕

Kind regards

**Comment by declension** [comment]
@ldexterldesign weird. Can't reproduce that (on Linux). Maybe it's the different `xargs`. Can you try:

```bash
python -c 'import site; print "\n".join(site.getsitepackages())' | xargs -I@ find @/quodlibet/ext/ -mindepth 2 -maxdepth 2 -type d -exec basename {} \;  -o -regex '.*[a-z]\.py' -exec basename {} \;  | sort 
```

**Comment by declension** [comment]
([Interesting background](http://stackoverflow.com/questions/12790328/how-to-silence-sys-excepthook-is-missing-error) to that error message)

**Comment by ldexterldesign** [comment]
@declension

```bash
Apple-MacBook-Pro:~ ldexterldesign$ cd ~/Desktop/
Apple-MacBook-Pro:Desktop ldexterldesign$ python -c 'import site; print "\n".join(site.getsitepackages())' | xargs -I@ find @/quodlibet/ext/ -mindepth 2 -maxdepth 2 -type d -exec basename {} \;  -o -regex '.*[a-z]\.py' -exec basename {} \;  | sort 
find: /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/quodlibet/ext/: No such file or directory
find: /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/site-python/quodlibet/ext/: No such file or directory
find: /Library/Python/2.7/site-packages/quodlibet/ext/: No such file or directory
```

Kind regards

**Comment by lazka** [comment]
> IMO it makes more sense to have "Music > Plugins > Advanced Preferences" grouped with "Quod Libet > Preferences" - I would have never discovered the OS X multimedia keys option without asking or going one-by-one through the plugins (I'm a completist, so I probably would have sooner or later anyway) :confused:

The advanced preferences (each separately) should either be rendered unnecessary or moved into the main preferences. In this case it was removed.

Regarding the python snippets: QL doesn't use the OSX provided Python, but ships its own.

**Comment by declension** [comment]
Raised #1994 for plugin list / docs

**Comment by ldexterldesign** [comment]
Hey,

Thanks for taking my feature request onboard

My two cents: three apps with very organised plugin support:

http://mozilla.org/en-US/thunderbird/
http://musicbrainz.org/
http://sublimetext.com/

Hope this is useful

Kind regards

**Comment by MKevin3** [comment]
Media keys don't work for me in the 4.x release. Using Mac / latest OS / Microsoft Natural 4000 keyboard. They work with other players. The advanced setting seems to be correct in a double negative sort of way "disable multimedia keys = false" which I think means they should be enabled. The alternate shortcut list in the menu to play is <cmd> + SPACE which on a Mac brings up spotlight so that is not a good key to use for music control.

Would be nice if there was a way to set what key or key sequence you wish to use to control the app.

**Comment by lazka** [comment]
@MKevin3 Did it work before for you?

**Comment by MKevin3** [comment]
I thought it worked once with a 3.x series but did not work with the last 3.x series I used and has not worked with 4.x which I just upgraded to today.

I think with the 3.x series it only worked if the app was in focus, not if I was in my code IDE. Now it does not appear to work at all.

**Comment by lazka** [comment]
Ok, thanks. Maybe it's due to some changes in macOS then.

**Comment by urielz** [comment]
@lazka most likely. It's working for me on QL4 & good old OS X 10.11.6

**Comment by lazka** [comment]
@urielz thanks, that rules out Python 3 changes.

I've opened #2692

**Comment by murillocjr** [comment]
I couldn't find the settings to try to get the media buttons to work, so in the end I got to work with a different set of keyboard shortcuts running "Applications/QuodLibet.app/Contents/MacOS/quodlibet --next”.

**Comment by ldexterldesign** [comment]
FYR using Jellyfin (macOS) & Manet (iOS) - very happy
