### ISSUE TITLE
QL plugin and Python newbie

### ISSUE THREAD

**Issue by urielz** [quodlibet/quodlibet#1819]
I was hoping to get some help with a plugin that I’m writing for QL. I wrote a script that given an audio file, it computes and displays the spectrogram and the audio waveform. It’s still a work in progress, but here’s an example of the output:

![pysepc_example](https://cloud.githubusercontent.com/assets/11670888/12988561/4ddbc5f2-d0cf-11e5-9e2e-afa4df2f66d6.png)

Looking at the documentation (and other plugins) I came up with this plugin header:

from quodlibet.qltk import Icons
from quodlibet.plugins.songsmenu import SongsMenuPlugin

import numpy as np
import matplotlib.pyplot as pet
import soundfile as sf

class AudioSpec(SongsMenuPlugin):
    PLUGIN_ID = "Spectrogram"
    PLUGIN_NAME = _("Spectrogram")
    PLUGIN_DESC = _(“Display spectrogram and waveform”)
    PLUGIN_ICON = Icons.MEDIA_PLAYBACK_START

The problem is that QL doesn’t recognize numpy, matplotlib and soundfile. Is this something that is not possible to write as a plugin? I’m new to Python so any help would be appreciated. Thanks!

**Comment by lazka** [comment]
I guess you are on OSX? numpy/matplotlib are massive dependencies and it's unlikely that we will ship them in the bundle.

Something like this should be possible with GStreamer as well:

http://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-good-plugins/html/gst-plugins-good-plugins-spectrum.html

https://github.com/fossfreedom/rhythmbox-spectrum

But I wonder why this should be included in QL and not be a separate application.

**Comment by urielz** [comment]
Yes, I’m testing the script on OS X. Would the dependency problem be solved if I was in a Linux environment?

As for why it should be included in QL, my vision was to be able to display the audio waveform with a moving slider showing the progress of the song. The spectrogram is more eye-candy than anything else, there are perfectly good stand-alone tools already (like Spek: http://spek.cc).

I guess overall I would like to see more eye-candy stuff in QL (like better display of album covers). Perhaps I’m alone in this? Do other users feel like adding this kind of stuff is not useful or nice to have? I'm curious about this, so please share your thoughts if you don't mind.

Thanks for the links lazka. I’ll see how far can I push this without using numpy and other libraries not included in the bundle. I'll share the results if I get something working.

**Comment by lazka** [comment]
New dependencies can only be added to the osx bundle at the time it is created (afaik). On linux you don't need a bundle and can use the libraries provided by the distribution.

For a waveform see #1530

**Comment by lazka** [comment]
> I guess overall I would like to see more eye-candy stuff in QL (like better display of album covers). Perhaps I’m alone in this? Do other users feel like adding this kind of stuff is not useful or nice to have? I'm curious about this, so please share your thoughts if you don't mind.

As long as it's optional and doesn't make QL a lot harder to maintain (like adding a bunch of new dependencies like numpy etc..) everything is fine with me. If you want to change some parts of the core application/interface best open an issue about it and get feedback first.

**Comment by urielz** [comment]
> New dependencies can only be added to the osx bundle at the time it is created (afaik). On linux you don't need a bundle and can use the libraries provided by the distribution.

I see. Didn't know about. Thanks.

> If you want to change some parts of the core application/interface best open an issue about it and get feedback first.

Sounds good. Still getting the hang of basic Python so I thought that starting with a plugin would be best.
