### ISSUE TITLE
Missing package 'py3cairo' building OSX Bundle

### ISSUE THREAD

**Issue by ealprr** [quodlibet/quodlibet#1820]
With the OSX Bundle build script during the build.sh step :
```bash
configure: error: Package requirements (py3cairo >= 1.10.0
        ) were not met:

No package 'py3cairo' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables PYCAIRO_CFLAGS
and PYCAIRO_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
*** Error during phase configure of pygobject3: ########## Error running ./configure --prefix /Users/ealprr/projects/quodlibet-osx/_home/jhbuild_prefix    *** [60/68]
```

Earlier : `** Installing pycairo-python2.6 *** [59/68]` built from `py2cairo-1.10.0` sources.

Somebody have an idea to fix the bundle build scripts/configuration? I am running El capitan 10.11.3 btw.
Thank you in advance.

**Comment by ealprr** [comment]
I forgot to mention that I am running El capitan 10.11.3.

**Comment by lazka** [comment]
Do you have a python3 in your PATH?

**Comment by lazka** [comment]
I've pushed a possible fix 1b1fcdda36da08

please try again

**Comment by ealprr** [comment]
Yes, python3 is available in my path.
I am currently trying the build phase with your changes, I will let you know.
Thank you.

**Comment by ealprr** [comment]
``*** success *** [68/68]`` :+1: 
Now, I am facing another issue with ``bundle.sh``: #1821

Thank you @lazka!
