### ISSUE TITLE
3.6.0 release

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1833]
With the many gtk+ changes in 3.20 it's probably a good idea to make a new release when 3.20 gets out.

https://wiki.gnome.org/ThreePointNineteen
Release is on 2016-03-23

- [x] Write NEWS
- [ ] Write release highlights
- [x] Update OSX package versions (especially GStreamer)
- [x] Blockers: #1880
- [x] add libsoup dep

**Comment by timpulver** [comment]
At some point it might also be good to do a new icon set, the current one is not consistent.

**Comment by lazka** [comment]
We just use standard icons atm. Are you referring to the Gtk+ icons not matching OS X ones?

**Comment by timpulver** [comment]
Not sure which ones are standard gtk+-icons and which are not. Just noticing that they look very different.

**Comment by lazka** [comment]
All are, except the QL logo. The standard theme icons come in two variants, symbolic (one color, recolorable by the theme) and non-symbolic (colored) and we decide which one to use.

**Comment by timpulver** [comment]
Can you point me to an online reference of all available icons?

**Comment by lazka** [comment]
If you are in `jhbuild shell` run `gtk3-icon-browser`

**Comment by lazka** [comment]
@declension OK if we create the stable branch?

**Comment by declension** [comment]
@lazka yes... though there were a few plugin (window) improvements I was hoping to finish soon. When were you thinking?

**Comment by lazka** [comment]
Just asking as I don't have anything left for 3.6. Feel free to create a branch if you want to work on risky master stuff again.. or I'll do it before the release.

**Comment by declension** [comment]
I see. Kinda forgotten how the release process works now.

Nope, don't have anything risky planned for `master`, it's all in branches anyway really. The Soundcloud stuff (#1828) won't be ready in time, the GIO file watching (#1315) I really want to get sorted but not production-ready, and playlists library is another one. Also I think I'll try to close #1065 some time soon (he says...)

**Comment by declension** [comment]
@lazka I think I've got everything "urgent" in now, so am good to go with any 3.6 branching, or will just push to branches for the rest, whichever you prefer
