### ISSUE TITLE
Button title change (Refresh Library & Reload Library)

### ISSUE THREAD

**Issue by timpulver** [quodlibet/quodlibet#1834]
It’s not clear what the buttons do without reading the tooltip text.

Better names would be:

`Refresh Library` —> `Scan`
`Reload Library` —> `Reload All`

The text on the left had to be changed then as well to `Scan on start`.

It’s also misleading that both have the same icon. No good suggestion on what to switch it to tho…

**Comment by lazka** [comment]
There is also a menu item in the main menu where "Scan" alone might be missing context? But "Scan" sounds better then what we have currently, even if does more than that.

What about ``Rebuild Library`` instead of ``Reload Library``?

**Comment by timpulver** [comment]
>What about Rebuild Library instead of Reload Library?

Yes, that’s better.

The difference between the two is just not clear right now.

**Comment by declension** [comment]
Yep... I've thought about that several times actually... but never remembered to raise a ticket.

_Rebuild library_ is a definite improvement. Not as sure about _Scan_ though, especially as @lazka says out of context.

**Comment by urielz** [comment]
My vote goes for keeping Refresh Library, but changing Reload to Rebuild Library. Much clear IMO.

**Comment by lazka** [comment]
On a second thought I like "Scan Library" better as it's probably the first thing a user wants to do when adding new music and that makes it clearer that it "scans" for new songs.
