### ISSUE TITLE
Add  a shortcut window 

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1837]
https://developer.gnome.org/gtk3/unstable/GtkShortcutsWindow.html

https://quodlibet.readthedocs.org/en/latest/guide/shortcuts.html

**Comment by CreamyCookie** [comment]
Interesting! Does this also allow to configure the shortcuts?

**Comment by declension** [comment]
+1

**Comment by lazka** [comment]
> Interesting! Does this also allow to configure the shortcuts?

No

----

Just copied the the online version for now... any improvements/suggestions welcome.
