### ISSUE TITLE
exfalso produces MP3 file which breaks gst playbin

### ISSUE THREAD

**Issue by mcepl** [quodlibet/quodlibet#1845]
1) Download http://download.proglas.cz/audio_47834.mp3'
2) Add some MP3 tags using Exfalso (``exfalso-3.2.2-1.el7.nux.noarch``)
3) Try to play the file with gst-launch-1.0 playbin uri=file:///..../file.mp3

Observed result:
Generated file (https://mcepl.fedorapeople.org/tmp/15%20Znamen%c3%ad%20doby.mp3) cannot be played. The error observed:
```
matej@mitmanek: Islám - znamení doby$ gst-launch-1.0 playbin uri=file:///home/matej/Hudba/Audiobooks/Islám\ -\ znamení\ doby/15\ Znamení\ doby.mp3 
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
Missing element: text/uri-list decoder
WARNING: from element /GstPlayBin:playbin0/GstURIDecodeBin:uridecodebin0: No decoder available for type 'text/uri-list'.
Additional debug info:
gsturidecodebin.c(939): unknown_type_cb (): /GstPlayBin:playbin0/GstURIDecodeBin:uridecodebin0
ERROR: from element /GstPlayBin:playbin0/GstURIDecodeBin:uridecodebin0: Your GStreamer installation is missing a plug-in.
Additional debug info:
gsturidecodebin.c(990): no_more_pads_full (): /GstPlayBin:playbin0/GstURIDecodeBin:uridecodebin0:
no suitable plugins found
ERROR: pipeline doesn't want to preroll.
Setting pipeline to NULL ...
Freeing pipeline ...
matej@mitmanek: Islám - znamení doby$ rpm -qa gstreamer1\*
gstreamer1-plugins-base-tools-1.4.5-2.el7.x86_64
gstreamer1-devel-1.4.5-1.el7.x86_64
gstreamer1-plugins-bad-freeworld-1.0.6-1.el7.nux.x86_64
gstreamer1-plugins-ugly-1.0.6-2.el7.nux.x86_64
gstreamer1-plugins-base-1.4.5-2.el7.x86_64
gstreamer1-plugins-good-1.4.5-2.el7.x86_64
gstreamer1-1.4.5-1.el7.x86_64
gstreamer1-libav-1.0.6-1.el7.nux.x86_64
gstreamer1-plugins-bad-free-1.4.5-3.el7.x86_64
gstreamer1-plugins-base-devel-1.4.5-2.el7.x86_64
matej@mitmanek: Islám - znamení doby$
```

Expected results:
Of course, the file should be just played.

When using another ID3 tagger (``picard``) works fine, and the result file could be played.

**Comment by lazka** [comment]
1) I can't reproduce here with the first file
2) The second file seems to have a invalid ID3 tag and I can reproduce that gstreamer can't play it

What's your output of `python -c "import mutagen; print mutagen.version"`

Note that ExFalso and picard use the same tagging library...

**Comment by mcepl** [comment]
```
$ python -c "import mutagen; print mutagen.version"
(1, 31)
$ 
```

**Comment by lazka** [comment]
huh, old exfalso and newest mutagen?

Which tags did you add to the first file? Maybe that makes a difference..

**Comment by mcepl** [comment]
title, track number, date (just year), author, album

But don't worry about it, if it doesn't make sense to you, just close this ticket.

**Comment by lazka** [comment]
I can't reproduce :(

If you have any more info feel free to post here or open a new issue.
