### ISSUE TITLE
Online crash reporting

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1853]
It would be nice to add a way to allow the user to submit a crash report to us in some way.

For Python exceptions we should display a short stacktrace and remove paths/usernames. In case the user has faulthandler installed we could write the C stacktrace to a file and suggest to report it on the next QL start.

Remaining questions:

1) Where to submit to?
2) How to prevent DOS? Captcha?

**Comment by lazka** [comment]
We could use sentry: https://sentry.io/welcome/

**Comment by declension** [comment]
Yes, Sentry would be cool actually. Didn't think of it (and didn't realise it had a fairly generous free tier) :)

**Comment by lazka** [comment]
They have recently revised their pricing, but the basic one is still free. I feel confident that they wont remove the free option or disappear and that we can depend on it to some extend. In the end most of the work required would also be useful for other services.

My current thinking:

* It would be nice to have this at the switch to Python 3. I assume that there will be quite a bit of fallout and catching that early would be nice.
* We can depend on faulthandler, write Python stack traces to disk on segfault and on the next start raise the error, pushing it to the crash reporter.
* Since python-raven (sentry client) isn't in debian we can make the crash reporting pluggable and put the python package at the right place for our Windows/macOS/PPA builds and not include it in the tarball.

One question remaining is how to present errors to the user. Just showing "submit error" will give us more tracebacks but makes it harder to reproduces some errors because we have no channel to ask questions. Providing both options with a short explanation might do the trick ([2] "Report error to us on github" [1] "Just send error log (better than nothing)")

**Comment by NoahAndrews** [comment]
Perhaps we should also have an in-app text box so they can at least say what they were doing when the app crashed.

**Comment by lazka** [comment]
@NoahAndrews good idea. sentry has a user feedback interface, but that is javascript only. Maybe we can reuse the API locally.

**Comment by lazka** [comment]
I've wrapped the whole thing to get the following API now:

```
sentry = Sentry(SENTRY_DSN)

def foo3():
    a = 6
    try:
        object.fooo5
    except Exception:
        try:
            err = sentry.capture()
            err.set_feedback("my python3 commentöäp")
            err.send(SENTRY_TIMEOUT)
        except SentryError:
            print("something broke, sorry")
```

Regarding how to ship python-raven: it just entered debian last week, so nothing in ubuntu for some time. An easy solution might be to just vendor the whole library and depend on its only dependency: contextlib2. If we then don't include it in the MANIFEST.in  it wont get included in the tarball but we will use it in all windows/osx/PPA builds because they use the git checkout directly.

**Comment by lazka** [comment]
For the UI I have the following in mind:

```
---------------------

Oops, an error occurred. You can ignore this error, but Quod Libet might be
unstable from here on out.

Error details (expander):

....Stack trace
....Stack trace
....


[Submit Error Report]/[Open a Bug Report] [Quit Program] [Ignore Error] <- Default

--------------


[Open a Bug Report] -> Opens github with a prefilled bug report

[Submit Error Report] -> Opens:

------------------

Various details regarding the error will be send to a third party online
service (sentry.io)

Report Details (expander):

.... The raw data we will send
.... The raw data we will send
....

(optional) Please give a short description of what you did when the error
occurred: [                                 ]


[Cancel] [Submit Report] --> makes window insensitive and adds a spinner.

If an error occurs shows an error message and makes window sensitive again. If
it succeeded: close the submit window. The user can then decide to ignore the
error or quit QL.

------------------

```

**Comment by urielz** [comment]
UI looks good to me. One question, from what you wrote I take that this doesn't handle CTDs? If so, can something similar be implemented for those cases? For example by asking the user to submit the bug report the next time QL is launched...

**Comment by lazka** [comment]
Thanks. Crash to desktop? If yes, we currently raise a Python exception containing a stacktrace on the next start: https://twitter.com/QuodLibetApp/status/836534027096109056 .

**Comment by lazka** [comment]
![screenshot from 2017-03-08 17-18-28](https://cloud.githubusercontent.com/assets/991986/23712462/489fb688-0423-11e7-9ecc-ee109b8c9f08.png)

![screenshot from 2017-03-08 17-14-53](https://cloud.githubusercontent.com/assets/991986/23712467/4afb3452-0423-11e7-96b4-e97bd4b12669.png)
