### ISSUE TITLE
Add Next/Previous buttons to Edit Tags Window

### ISSUE THREAD

**Issue by urielz** [quodlibet/quodlibet#1854]
It would be useful to add a “previous” and “next” buttons to the the >Control >Edit Tags window. There’s space in between “remove” and “revert” (see pic).

Having those buttons would make editing tag fields of single files faster. Right not the workflow is open the window, edit the tag, close the window go the next song in the album and repeat the process…

![ql_edit_window](https://cloud.githubusercontent.com/assets/11670888/13327120/97a01cc8-dbb6-11e5-917e-59ec8402d43e.jpg)

**Comment by declension** [comment]
You realise you can select multiple songs and edit the whole lot in one window? Whilst not perfect _that_ workflow is better than the one you describe there.

**Comment by urielz** [comment]
Yes. And I make use of that for common tags. But there are tags that sometimes cannot be edited that way (e.g., title, performer roles, track, composer etc...)

**Comment by declension** [comment]
I think I've misunderstood then - what stops you from editing them?

**Comment by declension** [comment]
e.g. here those are being edited.
![editing multiple files, one at a time](https://cloud.githubusercontent.com/assets/3322808/13329416/9f3c15ce-dbeb-11e5-89cb-4b73fcbe1ddd.png)

I agree there could be some accels and maybe up/down arrows on the left pane for easy navigation _within_ the set of songs you're editing - is that the kind of thing you're after @urielz ?

**Comment by urielz** [comment]
well.. yet I still have to discovered things about QL!

I never thought of just clicking on individual song from the left panel! I always prefer to use keyboard than mouse so hotkeys to navigate up and down will be useful, but that's not related to this issue. I'll close this one. Thanks you :)
