### ISSUE TITLE
quodlibet not of use for me as foobar2000 custom tags not recognized

### ISSUE THREAD

**Issue by ghost** [quodlibet/quodlibet#1856]
My music library is built on foobar2000.
I use a lot of custom tags like %RATING% or %CHARTLISTED%.
Is it somehow possible to read out and write such tags with your program?

**Comment by lazka** [comment]
Not with MP3/MP4 atm..

**Comment by CreamyCookie** [comment]
Closing this, since there is #893 which would allow changing these to standardized tags.

**Comment by CreamyCookie** [comment]
Closed because this is basically #48 AFAICS. (#893 could be useful for transforming non-standard tags into standard ones.)
