### ISSUE TITLE
Add «Open in Finder / Explorer / …» to context menu

### ISSUE THREAD

**Issue by timpulver** [quodlibet/quodlibet#1859]
I often need to access music files in Finder, e.g. to open them in another tagging application, copy them and so on. Right now I have to do: `Right Click` —> `Information` —> `Copy Path` —> `Paste in Finder` which is a long way.

**Comment by ned2** [comment]
There is a `Browse Folders` plugin, which I use for this all the time. This brings your operations down to `Right Click` --> `Plugins` --> `Browse Folders`. But given that it likely a commonly desired feature and apparently not as well known as it could be, perhaps there could be an argument to move this to the main context menu as a core feature?

**Comment by declension** [comment]
@ned2 I agree actually... I've long thought it belongs in the core.

@lazka we could move to a pluggable _provider_ style if we want to keep the flexibility... though really as long as it detects the "right" file manager I think most users won't care about configuring, (but will expect it to be there)

**Comment by timpulver** [comment]
Just tried `Browse Folders`, thanks for the tip @ned2! Much faster than my initial workflow. 
The plugin name `Browse Folders` is not fitting well imo, better would be `Open In File-Manager` or something like this. `Browse Folders` sounds like another pane to browse the music-collection by folder. When checking out the available plugins I thought of something completely different.

An improvement over the current `Browse Folders`-functionality would be if the file would be pre-selected in Finder / … . Currently only the folder is selected. As my DJ music-folder only contains single tracks this means I still have to manually search for the track I’m looking for.
Not sure if selecting files can be done in other file-browser other than *Finder*.

**Comment by lazka** [comment]
> @lazka we could move to a pluggable provider style if we want to keep the flexibility... though really as long as it detects the "right" file manager I think most users won't care about configuring, (but will expect it to be there)

yeah, I'd just have something like `show_uris(uris)`.

-----

Moving it into the core seems fine. I don't like that the menu is getting a bit long now... some alternatives/additional improvements to consider:

* The name change to "Open In File-Manager" seems like an improvement.
* We can add it to the default list of activated plugins.
* We could order the plugins in the context menu by "most recently used".

**Comment by timpulver** [comment]
>We could order the plugins in the context menu by "most recently used".

I think that’s a bad idea. It’s much faster and less confusing if you know where to find certain function. If the function you are looking for is moving, this is not longer possible.

**Comment by lazka** [comment]
>> We could order the plugins in the context menu by "most recently used".
>
>I think that’s a bad idea. It’s much faster and less confusing if you know where to find a certain function. If the function you are looking for is moving, it will take longer to find it in the list – if you have multiple plugins activated you likely use more than one of them.

I do have 15 plugins or so enabled where I don't really remember where to find one without scanning through, but yeah, for less plugins that might be more confusing. An compromise would be to show the top 7 recently used plugins in normal order and hide everything else in a "More Plugins.." sub-sub-menu. But that's another issue, so feel free to ignore for this.

**Comment by lazka** [comment]
For better finder integration: https://stackoverflow.com/questions/14178244/show-in-finder-not-working-in-10-8

Not sure how to call that from Python/pyobjc.

Here is the current code: https://github.com/quodlibet/quodlibet/blob/master/quodlibet/quodlibet/ext/songsmenu/browsefolders.py#L156

**Comment by timpulver** [comment]
Also it might be good to separate context-sensitive plugins from the others, e.g. `Browse Folders` can only be used when a track is selected, whereas other can be used all the time.

**Comment by timpulver** [comment]
>Not sure how to call that from Python/pyobjc.

Probably you have to call an automator script from python.

**Comment by timpulver** [comment]
>show the top 7 recently used plugins in normal order and hide everything else in a "More Plugins.." sub-sub-menu

This is a good idea!

**Comment by ned2** [comment]
>
>
>    - The name change to "Open In File-Manager" seems like an improvement.
>    - We can add it to the default list of activated plugins.
>    - We could order the plugins in the context menu by "most recently
>    used".
>
> —
>
I agree that the name change to "Open In File-Manager" is an improvement.

I get that cluttering the right click menu is a concern, but I also feel
that opening up songs in the file browser is a fairly fundamental activity,
and (maybe) especially for the Quod Libet user base, which I assume is
slightly more tech savvy. So I would argue that an exception should be made
in this situation. In which case, the changes to the Plugin menu might
become separate enhancements.

**Comment by lazka** [comment]
Sounds good (I think I prefer "Show in File-Manager" actually, as it will open the parent dir and highlight the file in the best case).

I've opened #1875 for the too many plugins issue.

**Comment by CreamyCookie** [comment]
I also think that "Show in File-Manager" should be part of the core, not just a plugin. (Maybe in the context menu above "Edit tags".) It's just such an essential thing that it seems a bit weird to have it as a plugin. 

Regarding the concerns about cluttering up the context menu. Maybe we could group all file related actions together: 

- Show in File-Manager
- Move to Trash
- Copy to Device

(btw. What's the reason for capitalising Device, Trash etc.?)

**Comment by declension** [comment]
Agreed - they're a bit iffy in places. But consistent > partially perfect, so I fixed up a bunch in e783b77901609b1ce3a276d24f2dfe618465df01.

**Comment by CreamyCookie** [comment]
Nice! :+1:

**Comment by declension** [comment]
Fixed in 546e9b5
