### ISSUE TITLE
Add Auto Playlists

### ISSUE THREAD

**Issue by timpulver** [quodlibet/quodlibet#1860]
Auto playlists are quite handy. E.g. when dealing with different collections (see [#1857](https://github.com/quodlibet/quodlibet/issues/1857)) having an auto-playlist which adds all the tracks from a certain directory makes life easier.
As the querying in search bar already is great and working, having an auto-playlist would basically mean storing a query and automatically refreshing it from time to time.

**Edit:**
Also some queries are quite long, e.g. if you always listen to music made in *2015* with the genre *Space Folk* on the label *Spacy Space*.

**Comment by nodiscc** [comment]
> which adds all the tracks from a certain directory makes life easier.

Beginning of an answer at https://github.com/quodlibet/quodlibet/issues/1857#issuecomment-190224918 (create a browser pane to filter by path)

**Comment by declension** [comment]
[Saved searches](http://quodlibet.readthedocs.org/en/latest/guide/browse/search.html) do just this (though are hard to find).

Anyway there's already a discussion on this in #205 - please comment there. Closing as duplicate

(See also #1602)
