### ISSUE TITLE
Folder Scan Unsuccessful

### ISSUE THREAD

**Issue by timpulver** [quodlibet/quodlibet#1862]
I just added a folder to the library (`Settings` —> `Library` —> `Add`), but when I press `Refresh Library` or `Rebuild Library` the tracks do not show up.

Added folder: `/Volumes/MYHD/Music/Releases`

This is my folder structure:

```
Releases/
    A_Made_Up_Sound/
        A_Made_Up_Sound-2012-Malfunctions-[50WEAPONS020]/
            01_A_Made_Up_Sound-Malfunction_(Adjust).mp3
            02_A_Made_Up_Sound-Malfunction_(Despair).mp3
    Andy_Stott/
        Andy_Stott-2011-Passed_Me_By-[Love069]
            01_Andy_Stott-Signature.flac
            02_Andy_Stott-New_Ground.flac
...
```

Does it fail because the music is in a subfolder?

**Comment by lazka** [comment]
> Does it fail because the music is in a subfolder?

No, this should work. No idea atm why it wouldn't.

**Comment by timpulver** [comment]
Oh sorry, I had a filter set in search bar… all good :)
