### ISSUE TITLE
Default theme —> Dark

### ISSUE THREAD

**Issue by timpulver** [quodlibet/quodlibet#1864]
I think the dark theme looks much better than the bright one. Maybe we could make it the default one!?
What do you guys think?

Also I would vote to set `Show album cover with rounded corners` to false per default.

**Comment by lazka** [comment]
I prefer the other option in both cases :)

**Comment by declension** [comment]
Me too...

**Comment by timpulver** [comment]
Okay, worth a try… :)

**Comment by lazka** [comment]
somewhat related, what about we use the border radius of buttons in the theme and get rid of the option?

**Comment by declension** [comment]
+1

**Comment by timpulver** [comment]
I dislike rounded corners, but I agree, I don’t think something like this belongs in the UI.

**Comment by lazka** [comment]
They are now half the radius as before using Adwaita.. so it's somewhat of a compromise :)

**Comment by JanClaeys** [comment]
So now I get big ugly rounded corners on all my album art when I use QuodLibet on Ubuntu with Unity...  :-(

I think it's wrong to use the border radius of *buttons* for something that isn't a button. In fact, I think that adding rounded corners to album art is always wrong, as album art is usually rectangular by nature (but if some people like it then of course I'm not against it being an option :) ).

**Comment by timpulver** [comment]
>In fact, I think that adding rounded corners to album art is wrong because album art is usually rectangular by nature, and sometimes contains "essential" details in the corners.

I totally agree. Cover-designers have a rectangular area to work with, if you cut off the corners, you are altering how it looks.

**Comment by kmf** [comment]
The rounded corners for Album art on Ubuntu look lame
