### ISSUE TITLE
[Paned Browser] Right-align number of entries

### ISSUE THREAD

**Issue by timpulver** [quodlibet/quodlibet#1866]
Currently there is a display bug which cuts off numbers if the number of decimals vary (I guess that’s it).
Would be better to right align all the elements, better readable as well.

<img width="460" alt="bildschirmfoto 2016-02-29 um 13 45 37" src="https://cloud.githubusercontent.com/assets/1055819/13395036/712ea40e-deec-11e5-923f-69a5f79595b3.png">

```
(1)
(123)
(1234)
```

vs.
```
   (1)
 (123)
(1234)
```

**Comment by lazka** [comment]
See #1750
