### ISSUE TITLE
Enqueue <—> Play Behavior

### ISSUE THREAD

**Issue by timpulver** [quodlibet/quodlibet#1868]
I think the enqueue / play-behavior is quite unintuitive right now.

_What I would expect:_ Double clicking an album in paned browser plays the album

_What happens instead:_ The first track from the album is being played, afterwards tracks from the queue

So in order to play an album, I have to:
- Open up the queue
- Delete all tracks from queue
- Right click album —> enqueue
- Press Play

This is very unintuitive and a long way.

What would be easy and intuitive would be that double click on an album / track / whatever would delete the queue, enqueue all of the tracks and play them.

Also a context menu entry `Play now` or `Play` next to `Enqueue` would be good.

**Comment by declension** [comment]
Or perhaps: inserts the entire album at the _top_ of the queue.

**Comment by CreamyCookie** [comment]
> What would be easy and intuitive would be that double click on an album / track / whatever would delete the queue, enqueue all of the tracks and play them.

(╯°□°)╯︵ ┻━┻      

**^** me, when I accidentally double click an album and my entire queue gets deleted :wink:

**Comment by timpulver** [comment]
>Or perhaps: inserts the entire album at the top of the queue.

That would be an alternative.

**Comment by bassstorm** [comment]
There's one more confusing case. When I have a playlist, I usually want to play it in background doing some library discovery work. But once current song is over, playback is switched to first one from current view (which is not my playlist obviously).
I know about Queue, but playlist wins when you want to get back to a few tracks back (especially if the content is generated randomly).

**Comment by frestr** [comment]
@bassstorm It might be a bit unintuitive, but this is usually done by opening a new browser window  (`Browse -> Open Browser`) and doing the library discovery there.
