### ISSUE TITLE
QL crash due to Tray Icon Plugin

### ISSUE THREAD

**Issue by urielz** [quodlibet/quodlibet#1870]
This is a very minor bug that doesn't affect QL functionality but I thought I should report it anyway:

QL crashes to desktop if the Tray Icon Plugin is selected/deselected twice.

Steps to reproduce:

1. Goto > Music > Plugins
2. Search for the Tray Icon Plugin
3. Click to activate it, the system tray icon appears as expected.
4. Click to deactivate it, the system tray icon disappears as expected.
5. Click it again, the system tray icon won’t appear as expected.
6. Click it again, QL crashes.

It doesn’t matters if steps above are followed with the Tray Icon Plugin initially activated, result is the same.

Tested on QL 3.5.2 and OS X 10.11.3

**Comment by lazka** [comment]
Thanks.

I think we could disable the tray icon on OSX now that we have a dock menu.

**Comment by lazka** [comment]
(The dock menu currently isn't as complete as the tray icon menu. This is tracked in #1766.)
