### ISSUE TITLE
Transfer from playlist to iPod segfaults

### ISSUE THREAD

**Issue by ochurlaud** [quodlibet/quodlibet#1872]
I'm on master.

When I try to transfer a playlist to my iPod, Quodlibet opens a dialog with/

```
  <NAME OF TRACK> could not be copied;
```

Closing the dialog crashes Quodlibet. Here the trace after initialization:

```
** (quodlibet:25635): CRITICAL **: itdb_splr_validate: assertion 'at != ITDB_SPLAT_UNKNOWN' failed
libitdbprep: itdb_sqlite_generate_itdbs called with file /run/media/olivier/LIL0'S ONE/iPod_Control/iTunes/iTunesCDB and uuid 000A27001EB5E509
itlp directory='/run/media/olivier/LIL0'S ONE/iPod_Control/iTunes/iTunes Library.itlp'
*.itdb files will be stored in '/run/media/olivier/LIL0'S ONE/iPod_Control/iTunes/iTunes Library.itlp'
[mk_Dynamic] Processing '/tmp/filejGwtzr/Dynamic.itdb'
[mk_Dynamic] creating table structure
[mk_Dynamic] - processing 1 tracks
[mk_Dynamic] - processing 1 playlists
[mk_Dynamic] done.
[mk_Extras] Processing '/tmp/filejGwtzr/Extras.itdb'
[mk_Extras] re-building table structure
[mk_Extras] done.
[mk_Genius] Processing '/tmp/filejGwtzr/Genius.itdb'
[mk_Genius] re-building table structure
[mk_Genius] done.
library_persistent_id = 0x2681c410e07e0c9d
[mk_Library] Processing '/tmp/filejGwtzr/Library.itdb'
[mk_Library] building table structure
[mk_Library] compiling SQL statements
[mk_Library] - inserting into "version_info"
[mk_Library] - inserting into "genre_map"
[mk_Library] - inserting songs into "item_to_container"
[mk_Library] - inserting playlist 'LIL0's One' into "container"
library_persistent_id = 0x2681c410e07e0c9d
device name = LIL0's One
[mk_Library] - inserting into "db_info"
[mk_Library] - processing 1 tracks
[mk_Library] done.
[mk_Locations] Processing '/tmp/filejGwtzr/Locations.itdb'
[mk_Locations] re-building table structure
[mk_Locations] Processing 1 tracks...
[mk_Locations] done.
[run_post_process_commands] Getting SQL post process commands
[run_post_process_commands] binding functions
[run_post_process_commands] Running 88 post process commands now
[run_post_process_commands] ERROR when executing 'CreateRentalExpiredColumn': duplicate column name: rental_expired
[run_post_process_commands] 87 out of 88 post process commands successfully executed
[run_post_process_commands] done.
itdbprep: copying 'Dynamic.itdb'
itdbprep: copying 'Extras.itdb'
itdbprep: copying 'Genius.itdb'
itdbprep: copying 'Library.itdb'
itdbprep: copying 'Locations.itdb'
itdbprep: copying 'Locations.itdb.cbk'
/usr/lib/python2.7/site-packages/quodlibet/devices/ipod.py:337: Warning: g_strdelimit: assertion 'string != NULL' failed
  gpod.itdb_shuffle_write(self.__itdb, None) == 1:

** (quodlibet:25635): CRITICAL **: put_string: assertion 'string' failed
zsh: segmentation fault (core dumped)  quodlibet --debug
```

**Comment by declension** [comment]
Ouch, segfaults.

Thanks for the report. Unfortunately iPod support it pretty flakey and doesn't get much testing currently.

For reference, which model is this?

**Comment by ochurlaud** [comment]
It's an ipod 5G. It's supported on most mediaplayers... But I don't know hat library they use...

**Comment by ochurlaud** [comment]
Reinitializing the ipod on a windows solved the segfault... Now I'm waiting to see if the transfered music will be recognized by the ipod.

**Comment by lazka** [comment]
I've only had an ipod for a day to port the old python-gpod code to libgpod and ctypes. Without someone owning an ipod and working on the code it's unlikely that it will improve. We should consider removing ipod support.

**Comment by ochurlaud** [comment]
Don't remove the support to soon... We still need that in the linux community, and I would be really sad to have to run iTunes in wine.... 

So I tracked my problem. Here are the different configurations

1: I was accessing my music remotely through wlan (I have a NFS server on my raspberry pi). It was very slow so maybe QuodLibet was failing to synchronize. So it's not 100% QuodLibet. ?
2: The iPod was on a usb hub, the hard drive as well. I don't know why, but it was failing on Amarok and QuodLibet (So it's definitely not a QuodLibet issue)
3: The iPod and the hard drive are directly connected to the computer: it synchronize quite fast but fails after a certain number of songs synchronized. "Song cannot be added". Like if QuodLibet was corrupting the database of the iPod. 

1 and 3 seems to have similar problem... I investigate further.

**Comment by ochurlaud** [comment]
Is all the code for the ipod in quodlibet/devices/ipod.py and quodlibet/devices/_gpod.py?

**Comment by lazka** [comment]
Yeah, and mostly untouched since 10 years :)

**Comment by ochurlaud** [comment]
Yes but if it works once, it should work twice :)

**Comment by ochurlaud** [comment]
It seems that the error occurs when the same song is synchronized twice. I was synchronizing a playlist where I put by mistake an album twice. I'm currently synchronizing the same tracks by smaller amounts and it worked. I'll try again later with everything at once.... Very strange

**Comment by lazka** [comment]
iPod support removed: c052c933e3f449a908cca4e0810139fd9f7640c8
