### ISSUE TITLE
Fix new warnings from pyflakes 1.1.0

### ISSUE THREAD

**Issue by declension** [quodlibet/quodlibet#1874]
On upgrading (it's set to auto-upgrade in Travis...) to [Pyflakes 1.1.0](https://github.com/pyflakes/pyflakes/releases/tag/1.1.0), lots of things are failing their new tests.

I guess we should either disable the tests, or fix (or both in that order, maybe)

**Comment by lazka** [comment]
Afaik these are already fixed in master

**Comment by declension** [comment]
Thanks, didn't see that one. I've merged from master
