### ISSUE TITLE
Removing a song from a playlist whilst a query is active removes all songs not matching the query

### ISSUE THREAD

**Issue by ochurlaud** [quodlibet/quodlibet#1876]
Sorry, I found something else...

To reproduce
===========
1. Create a playlist
2. Search content in the playlist browser
3. Delete a song from the remaining list

The playlist is now ONLY the remaining list without what was just deleted: all the content of the playlist which was not matching the search query has been removed.

**Comment by declension** [comment]
Thanks for the report @ochurlaud 

In 29af1f7, pushed a simple heuristic fix, that will fallback to standard playlist removal if a filter is active. This largely fixes this issue, but with a drawback that the incorrect playlist duplicates sometimes get removed when there is a filter active. But, better than losing most of your playlist...
