### ISSUE TITLE
Proposal: Second "wide" mode for paned browser

### ISSUE THREAD

**Issue by slckr** [quodlibet/quodlibet#1877]
It would be cool if the filters of the paned browser could be configured totally vertically instead of being stacked one on the other, in order to fully use the width of the screen!
See my rapid mockup attached!
![mockup](https://cloud.githubusercontent.com/assets/17674151/13548124/ae83606a-e2e8-11e5-8dca-2a66f1f3e9df.png)

Cheers,
Negativland.

**Comment by lazka** [comment]
Seems reasonable, thanks.

**Comment by declension** [comment]
Sounds good. If anything I'd say that's a _tall_  mode (though I prefer something more like drill-down mode, or _explorer mode_ perhaps... or maybe _columnar_) - but really all the names are confusing to me, including the current _wide mode_.

Once there are three or more options, the ideal UI might be a clickable mock-up (icon) in the preferences, almost like a "layout wizard" or something equally horrible sounding.

**Comment by Negativland** [comment]
In the same spirit, the queue could be displayed vertically on the far right of the window, instead of below the song list.

**[library filters x | y | z] [song list] [queue]**

_Tall_ mode sounds good! ;)

Anyway, thanks for this fine piece of software!

**Comment by declension** [comment]
> It would be awesome if there were a mode for the browser which allowed draging and dropping 'found' tracks into a playlist.

In the meantime you can open the Playlists Browser in a separate window and do exactly this.
