### ISSUE TITLE
ReplayGain plugin: Fatal behaviour on same-named albums.

### ISSUE THREAD

**Issue by pschwede** [quodlibet/quodlibet#1879]
We need a solution here. QL handles my "Greatest Hits" albums from different artists as one. You can imagine the consequences.

**Comment by urielz** [comment]
Besides the Album tag, other tags are used to identify different albums (with the same album title). "labelid" is one of those tags. Check the docs for further info:

https://quodlibet.readthedocs.org/en/latest/guide/browse/album.html

**Comment by declension** [comment]
Annoying: yes. Obvious solution: not so much. 

I'd strongly recommend using Musicbrainz tags, the problem just goes away then (and setting `albumartist` never hurts).

See discussion in related: #1871

**Comment by CreamyCookie** [comment]
Closing this as a duplicate of #1871
