### ISSUE TITLE
Latest build, Windows 7, volume resets to 100% when starting new song

### ISSUE THREAD

**Issue by keiter** [quodlibet/quodlibet#1880]
When testing for #1696 I installed this build of Quod Libet on Windows 7:
https://bitbucket.org/lazka/quodlibet/downloads/quodlibet-3.6.-1-rev7983-3f0fb55-installer.exe

I noticed that QL's volume will reset to 100% every time you start playback of a new song. The slider will not move to reflect this however, but will still show whatever you set it on previously. So for instance I usually leave the slider at 50% to keep it normalized with other media. When I start a new song on that build it will play at 100% volume, but the slider will still show 50%. If you adjust the slider it will work as you'd expect until you start another song when it resets again.

**Comment by lazka** [comment]
Thanks.

**Comment by lazka** [comment]
Might be a regression from this bug: https://bugzilla.gnome.org/show_bug.cgi?id=755106

**Comment by lazka** [comment]
New build:

https://bitbucket.org/lazka/quodlibet/downloads/quodlibet-3.6.-1-rev7990-a5c2801-installer.exe
https://bitbucket.org/lazka/quodlibet/downloads/quodlibet-3.6.-1-rev7990-a5c2801-portable.exe

**Comment by keiter** [comment]
Fixed, thank you.

**Comment by lazka** [comment]
Thanks for testing!
