### ISSUE TITLE
Consider Chocolatey as a Windows distribution channel

### ISSUE THREAD

**Issue by kwill** [quodlibet/quodlibet#1883]
Chocolatey is a distribution tool for Windows applications, including many free software applications (for example, https://chocolatey.org/packages/pidgin). It allows an end-user to get application updates somewhat like using `apt` or `yum` on GNU/Linux.

Please consider it as a distribution channel for your Windows builds.

https://github.com/chocolatey/choco/wiki/ChocolateyFAQs
https://github.com/chocolatey/choco/wiki/Moderation

**Comment by lazka** [comment]
Looks like this can use our NSIS installer directly(?). Feel free to create a package..

**Comment by 07416** [comment]
Is someone working with Chocolatey repository? https://chocolatey.org/packages?q=quodlibet
I'm not tech-savvy, but if anyone doesn't want to maintain Quod Libet I have to take matters into my own hands.

**Comment by lazka** [comment]
I guess someone handled it: https://chocolatey.org/packages?q=quodlibet

If there is anything we can change in the installer etc to improve integration please tell us.
