### ISSUE TITLE
Keyboard shortcut for switching between shuffle and inorder

### ISSUE THREAD

**Issue by scresante** [quodlibet/quodlibet#1884]
I have looked through the documentation and issue tracker and have not found anything mentioning this.

It would be nice to have a keyboard shortcut to toggle shuffle. Is this already implemented or could it be?

**Comment by lazka** [comment]
> Is this already implemented or could it be?

No, and yes.

**Comment by Najrim** [comment]
Would be awesome to have this. The keyboard shortcuts really makes using the application easier for us on laptops.

**Comment by scresante** [comment]
I was about to file this only to realize I had 4 years ago... well I guess I'll hack it in myself.

**Comment by Najrim** [comment]
Thanks, that's a useful tip! Any idea how that last step is done in KDE (or Linux in general)?

**Comment by scresante** [comment]
@Najrim Every window manager almost always has a straightforward method to implementing keyboard shortcuts, which can be found by reading the documentation. [Here it is for KDE](https://docs.kde.org/stable5/en/kde-workspace/kcontrol/keys/index.html)

**Comment by Najrim** [comment]
Thanks. A shortcut for running a text command was a bit harder to find though (the manual doesn't even mention the existence, as far as I can tell). For anyone else looking, they're under

settings > shortcuts > custom shortcuts > edit > new > global shortcut > Command/URL

and from there it's obvious.
