### ISSUE TITLE
Don't display "Disc 1/1" in the song info display

### ISSUE THREAD

**Issue by CreamyCookie** [quodlibet/quodlibet#1887]
This is minor issue about wasting screen space. "Disc 1/1" shouldn't be displayed, because the majority of albums will have just one disc and in the case that the number of disc isn't mentioned, it's obvious that there's just one disc.

Currently, the pattern for the display includes the following line:

```php
<discnumber| - Disc <discnumber>>
```

This makes sure that "Disc x/y" isn't displayed, if `discnumber` isn't set. The problem is that in many cases it is set to just `1/1`, for example, by MusicBrainz Picard.

**Comment by declension** [comment]
Having just tested this, I can confirm you can do it already.

    <#(discnumber=1)|| - Disc <discnumber>>

We could set this as the default pattern, perhaps, but not sure if everyone wants this.

**Comment by CreamyCookie** [comment]
> Having just tested this, I can confirm you can do it already.

Cool, didn't know this works! Although I should have, because it's even mentioned in the [docs](http://quodlibet.readthedocs.org/en/latest/guide/tags/patterns.html?highlight=conditional#conditional-tags-with-comparisons).

Your pattern doesn't quite function as I intended though. It still displays "Disc 1/1" and doesn't display "Disc 1" if the song is from a multi disc album. It should be

```php
<discnumber|<discnumber="1/1"|| - Disc <discnumber>>>
```

> Edit: it's not pretty though

Yeah! I think it might be a bit better if one could use `&` (AND) and `|` (OR), but I guess, that's problematic, because `|` is already used for conditionals.

> We could set this as the default pattern, perhaps, but not sure if everyone wants this.

True!

**Comment by declension** [comment]
OK seems like it works; @CreamyCookie are you happy for this to be closed?

**Comment by Negirno** [comment]
Is it possible to use  `~#disc` and `~#track` in the panes? I've tried to use them, but they've throwing an error if I click apply. I don't want total discs and tracks in my pane.

**Comment by CreamyCookie** [comment]
@declension Okay. I guess it could be useful, given that the tags are correctly set, to see that an album has 1/1 dics, if you are collecting albums of a band and want to immediately see if you have got all the discs of an album.
