### ISSUE TITLE
Add a keyboard shorcut for "move to trash"

### ISSUE THREAD

**Issue by declension** [quodlibet/quodlibet#1889]
It's a shame there's no shortcut for deleting a file (or set of files) now that this is safer - not only does it move to trash where possible, but it also confirms deletion first.

Perhaps `<delete>` is too easy to slip (or not?), but `<ctrl>-delete`, `<shift>-delete`, `<backspace>` or something?

**Comment by victoriahayes** [comment]
like ctrl-shift-d, and then just have a small command window asking to confirm the deletion? I'd like to give it a shot, but this would be my first PR, so it'll be a while.

**Comment by victoriahayes** [comment]
I'm assuming you'd like this for anything selectable that can be deleted (e.g. playlists, albums, songs). Is this right?

**Comment by victoriahayes** [comment]
Should I give remove a similar shortcut while I'm at it?

**Comment by lazka** [comment]
> like ctrl-shift-d?

I'd go with ctrl+Delete

> Should I give remove a similar shortcut while I'm at it?

Maybe as a separate change.

**Comment by declension** [comment]
Sorry, yes, I agree ctrl-del sounds best. Removing should always be "easier" than deleting of course. 

The accelerators are not universal though, so updating it throughout would be more changes but I was really referring to the songs [context] menu here

**Comment by victoriahayes** [comment]
Thank you for your input. So far I've only changed qltk/songsmenu.py so that it adds fake_accel for both remove and delete. To differentiate between remove and delete, I'm thinking of giving remove the accel of just delete and move to trash ctrl+delete. Now I just need to find where the accelerators would be called from.

**Comment by lazka** [comment]
See https://github.com/quodlibet/quodlibet/blob/master/quodlibet/quodlibet/qltk/songlist.py#L625

In this case we misuse the gtk accel stuff to just show a shortcut indicator in the menu and handle the event ourself in each widget. Both things are independent.

**Comment by victoriahayes** [comment]
So I've noticed. I've found one version in /browsers/albums/main.py, so I just need to keep playing hide-and-seek with files until I find it.

**Comment by victoriahayes** [comment]
Is this ok? I suppose I need to figure out how to make an actual pr, but here's the patch for it, as of the current version's master.
[del_shortcut_patch.txt](https://github.com/quodlibet/quodlibet/files/226747/del_shortcut_patch.txt)

**Comment by urielz** [comment]
For mac users, command+delete would be the standard option.
source: https://support.apple.com/en-us/HT201236

**Comment by lazka** [comment]
@urielz thanks, the patches uses command+delete on osx
@victoriahayes thanks for the pull request
