### ISSUE TITLE
Make the queue more like a timeline, with recently played songs visible

### ISSUE THREAD

**Issue by CreamyCookie** [quodlibet/quodlibet#1890]
There are some actions that I mainly do after I've listened to a song. Most of the time those are rating a song or adding it to a playlist. And because the songs are coming from all over the place, the only option AFAIK to find the last played songs, is to run the default search "Recently played".

I don't know how common that is, but having a menu that contains the names of the last 10 songs or so with their context menus would save a lot of time. Although one could open another browser with the last played songs, this would require much more space (and the window doesn't minimize and maximize with the main window).

**Comment by declension** [comment]
Yep, I would like this too. However: #152 (which I'm tempted to have another go out actually, it's semi-blocking a _lot_ of features - or worse, increasing numbers of UI hacks necessary)

FWIW this is almost a mirror of #894. For me, an ideal (if slightly unusual) UI would be a timeline that extends into the past and future

**Comment by CreamyCookie** [comment]
Huh.. how is this almost a mirror of #894 ? Isn't party shuffle about future (to be played) songs, while this is about past (already played) songs.

**Comment by declension** [comment]
Yes exactly that @CreamyCookie (mirror as in "inverse") - and I think the simplest UIs, that a few other players use, show both past and future songs without needing to switch context or look elsewhere too much.

In QL I'm imagining this as a rework / enhancements of the queue, but there are other solutions too no doubt.

**Comment by CreamyCookie** [comment]
Ahh, that makes sense. So your idea is that the queue also shows the previously played songs, if you scroll up. So, based on the scrolling more songs would be displayed. So it would like this, right?

(The first two elements would be slightly greyed out.)

- Everything Sucks — Descendents
- Forever Young — Alphaville
- ▶️ **Augenblick — Farin Urlaub**
- Technologic — Daft Punk
- Stressed Out — Twenty One Pilots
- [Harder, Better, Faster, Do it — Daft Labeouf](https://www.youtube.com/watch?v=hAEQvlaZgKY)
- Chandelier — Sia




That sounds like a good idea! :+1: 

It would also have the nice benefit of making it easy to re-add a song that you accidentally skipped, for example, by clicking on another song.

**Comment by urielz** [comment]
Yes. I still haven't get used to the queue in QL because of this. Being able to scroll forward and back in time would be a great feature to add.

**Comment by e-anima** [comment]
as far as i understand that, that mean to not remove items from the queue after they have been played.

**Comment by TheSachin** [comment]
@CreamyCookie  - I agree this is something i would want.
@e-anima - yes that would solve the trick. I think the way winamp handles it is perfect. Playing pane is something i would prefer

**Comment by frestr** [comment]
Implemented in #2865. May perhaps not work exactly as described in this thread, but suggestions for improvement are of course welcome. I'll close this issue for now though.

**Comment by CreamyCookie** [comment]
Wow, somehow I never got notified of this. (Or missed it.) Thanks @frestr
