### ISSUE TITLE
Highlight current rating in ratings context menu

### ISSUE THREAD

**Issue by CreamyCookie** [quodlibet/quodlibet#1891]
Similar to how there's a ✓ next to the playlists which contain this song, a circle would make it easy to spot what you have rated this song before, without having to check somewhere else beforehand. For example, when you listen to something in the queue, you don't always see the rating anywhere. (Of course, you could set `<~rating>`  to the song display. I still think this feature would makes sense.)

**Comment by lazka** [comment]
See #972, but let's continue here and close the old one.
