### ISSUE TITLE
Lyrics Window plugin browser freezes

### ISSUE THREAD

**Issue by CreamyCookie** [quodlibet/quodlibet#1892]
This started happening after I ported the plugin to WebKit2. It seems to happen relatively irregularly, and weirdly enough I've only seen it happening on LyricWiki pages, but that might just be selection bias. In that state one can't scroll and interestingly, changing the width of the window is like changing the dimensions of an image. It's compressed (or stretched):
![2016-03-12 22-32-59](https://cloud.githubusercontent.com/assets/3063858/13725466/39fbd0fe-e8a3-11e5-9af3-7c1534dc5a0b.png)

**Comment by lazka** [comment]
Looks like a WebKit2 problem. Maybe it's crashing and we could handle https://lazka.github.io/pgi-docs/#WebKit2-4.0/classes/WebView.html#WebKit2.WebView.signals.web_process_crashed ? Or something similar.

Of course hard without having a way to reproduce reliably..

**Comment by CreamyCookie** [comment]
@lazka Like this: #1923 ?

**Comment by CreamyCookie** [comment]
I'm closing this, as it's caused by WebKit and #1923 should take care of recovering from the crash.
