### ISSUE TITLE
Port away from urllib

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1893]
We should get rid of urllib/urllib2 and use requests/certifi instead.

* Easier to port to py3
* To fix TLS on OSX (newer OSX doesn't include openssl anymore) we need to ship our own CA list, and requests uses certifi if available.

**Comment by declension** [comment]
Sounds good. What do you think about libsoup / gi stuff?

**Comment by lazka** [comment]
Never really used it.

Should we look into using libsoup instead?

**Comment by declension** [comment]
Neither had I - just found it in the album art stuff already, and didn't want to pull in requests (when I was starting the soundcloud stuff).

It's definitely trickier / lower level IMO. My gut feeling is it might be faster / better for heavy networking (lots of async, protocol level) - but that doesn't seem in the spirit of QL as much?

Anyway I wasn't proposing it as an alternative, more as a question of do we want _one_ library to rule them all, or should we leave two...

**Comment by lazka** [comment]
Ok, thanks.. not enough info to decide I guess. requests + threadpool should also work compared to the gio async stuff. Let's just get rid of urlib first.

**Comment by wbiller** [comment]
The libsoup stuff does not work on Mac currently. QL terminates without any message, as soon as it tries to download a cover.

**Comment by lazka** [comment]
Just noticed that requests has the Apache license, so I guess we can't use it as it isn't GPLv2 compatible..

**Comment by declension** [comment]
Good catch :anguished: 

Guess we might need to deal with [these ones](https://github.com/quodlibet/quodlibet/search?utf8=%E2%9C%93&q=%22import+requests%22&type=Code) then (and probably a few more),,
