### ISSUE TITLE
The list of musicbrainz tags in tags.py does not seem complete

### ISSUE THREAD

**Issue by zuzzurro** [quodlibet/quodlibet#1896]
I just discovered the operon command and was checking if i could use it to copy tags from the flac master to the transcoded m4a. Seems a very nice tool, my compliments.
During my checking I found the list of tags in tags.py but by comparing it with the list in: https://picard.musicbrainz.org/docs/mappings/
it seems that some tags are missing, for instance musicbrainz_releasegroupid. Would it be possible to update the list?
I'm asking this question because if I try to run an operon copy --dry-run of a picard tagged flac file, the result does not seem to contain all musicbrainz tags, and I have the feeling that this might also be linked to the missing tags. It may also be connected to the categorization the of tag, though. Not sure.
But I will raise this second issue in a separate ticket.

**Comment by lazka** [comment]
We are probably missing support for musicbrainz_releasegroupid in the m4a code.

**Comment by zuzzurro** [comment]
Is there a way I can help here?
