### ISSUE TITLE
Allow changing the interface language

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#1899]
Seems common on Windows.. maybe as a plugin

**Comment by lazka** [comment]
a bit tricky as atm we read the config after initing gettext

**Comment by ysteina** [comment]
I was just searching for this feature, as I am not satisfied with the translation into my language and would like to switch back to English. But I can't seem to do this without changing my system language (or using the flatpak version).

**Comment by lazka** [comment]
Did you try the "Change Language" plugin?
