### ISSUE TITLE
Quodlibet throws an exception when going to Paned Browser

### ISSUE THREAD

**Issue by am4c130d** [quodlibet/quodlibet#1903]
[Dump_20160327_184028.txt](https://github.com/quodlibet/quodlibet/files/191178/Dump_20160327_184028.txt)

My paned view uses the recently added conditional sorting to display album info etc.  However, I cannot get in to it to disable this due to the exception and Quodlibet needing to be restarted.

Thanks

**Comment by lazka** [comment]
Open ``~/.quodlibet/config``. Please post the line starting with ``panes = `` and to make it work again delete it (all while QL is not running9

**Comment by lazka** [comment]
I can reproduce: ``<~#disc>``

**Comment by Negirno** [comment]
It also crashes with `<~#track>`. This issue also affect me.

My dump files:
[Dump_20160329_223740.txt](https://github.com/quodlibet/quodlibet/files/194296/Dump_20160329_223740.txt)
[MiniDump_20160329_223740.txt](https://github.com/quodlibet/quodlibet/files/194299/MiniDump_20160329_223740.txt)

**Comment by lazka** [comment]
Thanks.

**Comment by am4c130d** [comment]
Apologies for the slow response.  My panes section:

panes = genre	<genre=Audiobook|<author>\: <album>|<genre=Classical|<conductor|<composersort|<composersort>|<composer>>\: <album>[small][i] conducted by [/i][/small]<conductor>|<albumartistsort> [small][i]<originaldate|<originaldate>|<date>>[/i][/small] <album>>|<albumartistsort> [small][i]<originaldate|<originaldate>|<date>>[/i][/small] <album>>>	<discsubtitle|<discsubtitle>\: |><~#disc>\:<tracknumber> <title>:(<~length>)

I note I have ~#disc - I replaced <~#disc> with <discnumber> and I can get to the paned browser now.

Thanks!

**Comment by lazka** [comment]
Thanks. Will be fixed in 3.6.1

**Comment by lazka** [comment]
3.6.1 is out now
