### ISSUE TITLE
Tray icon updates in 3.6.0

### ISSUE THREAD

**Issue by ghostwords** [quodlibet/quodlibet#1904]
I recently upgraded Quod Libet to 3.6.0. I use Quod Libet on Ubuntu 14.04 with Gnome Classic Desktop. I would like to share a couple of issues regarding changes to the tray icon (from, I think, issue #1756):

- Before 3.6.0, I could toggle Quod Libet with a single click (right-click?) on its tray icon. This now takes two: once to open the menu, and once to click on the "Show Quod Libet" menu item. (Right-clicking the tray icon now shows a single, pretty useless "About" Indicator Applet Complete menu item, same as my other tray icons ...)

- Quod Libet now seems to remember its foreground/background position. When you hide QL using the tray icon while QL is behind some other window, restoring QL keeps it behind that other window, which I think is undesirable, since you presumably want to interact with QL at this point. Not entirely sure this behavior is new to 3.6.0.

- The current song tooltip no longer comes up when I hover over the tray icon.

Let me know if I should break any of these out into own issues. Thank you!

**Comment by lazka** [comment]
You're probably no longer seeing the tray icon but the Ubuntu "app indicator" we use for Unity/KDE.

Could you paste the output of ``echo $XDG_CURRENT_DESKTOP`` executed in a terminal ?

**Comment by lazka** [comment]
For the background/foreground position restore, this should be fixed, we currently don't "present" the window with the app indicator while we do with the tray icon.

**Comment by ghostwords** [comment]
```
$ echo $XDG_CURRENT_DESKTOP
Unity
```
Is there any way to get the tray icon back?

**Comment by lazka** [comment]
You can start QL like this ``XDG_CURRENT_DESKTOP="GNOME-Classic:GNOME" quodlibet``

Not sure why gnome identifies as Unity.. needs investigating.

**Comment by ghostwords** [comment]
Yes!! Thank you, that worked. Ah yes, left-click to toggle, right-click to get a useful menu. Tooltip is back, foreground/background behavior is good too.

**Comment by lazka** [comment]
Will be fixed with 3.6.1

**Comment by lazka** [comment]
3.6.1. is out now

**Comment by ghostwords** [comment]
Looks good, thank you!
