### ISSUE TITLE
ExFalso packaging

### ISSUE THREAD

**Issue by ArchangeGabriel** [quodlibet/quodlibet#1907]
I’ve been maintaining an [AUR PKGBUILD for ExFalso](https://aur.archlinux.org/packages/exfalso/) for quite some time, but ever wondered if I could do better.

Is there an easy way to package ExFalso only? What modules are relevant to ExFalso (e.g. MusicBrainz)? Can some files in `/usr/lib/python2.7/site-packages/quodlibet/` be discarded? What are the minimal dependencies, which modules depend on what?

Thanks a lot!

**Comment by lazka** [comment]
> Is there an easy way to package ExFalso only?

No, but you can ship desktop integration files separately (icons, .desktop files, manpage)

>  Can some files in /usr/lib/python2.7/site-packages/quodlibet/ be discarded?

Some plugins could be, but not sure if 300kb saved is worth the trouble.

> What are the minimal dependencies, which modules depend on what?

I'll try to improve the "Packaging Guide" to show the differences. 

----

For a general approach to splitting things up, debian for example has a exfalso package depending on all the basics and ef/ql plugin dependencies and quodlibet depends on exfalso and any extra plugin  dependencies.

**Comment by ArchangeGabriel** [comment]
Time passed and I’m now Arch Linux maintainer for both quodlibet and exfalso, for now I’ve just packed the two PKGBUILD together but in the future I’ll split the Debian way.

Thanks for your input.
