### ISSUE TITLE
Lyrics window issue on LM17.3

### ISSUE THREAD

**Issue by thob** [quodlibet/quodlibet#1908]
GObject Introspection: Namespace WebKit2 not available for version 4.0

Anythin I can do about it?

**Comment by lazka** [comment]
``sudo apt-get install gir1.2-webkit2-4.0``

**Comment by thob** [comment]
>Für Paket »gir1.2-webkit2-4.0« existiert kein Installationskandidat

**Comment by lazka** [comment]
Ok, maybe we can add support for webkit2-3.0

**Comment by lazka** [comment]
Should work again with gir1.2-webkit2-3.0 now. Will be in 3.6.1
