### ISSUE TITLE
"Stop after this song" via CLI or FIFO (~/.quodlibet/control)

### ISSUE THREAD

**Issue by Jimi-James** [quodlibet/quodlibet#1909]
I need to assign the "Stop after this song" feature to a keyboard shortcut in my desktop. Right now, I have a script that uses xdotool to make the quodlibet window show up for a second, press the Shift+Space hotkey, and hide it again, but for reasons I cannot figure out through extensive testing, this doesn't work almost half the time, which defeats the entire purpose of the hotkey, because I have to use the right-click menu to check that it worked anyway. It'd be simpler if there was just a direct command line option to do it that I could put in that script.

**Comment by Jimi-James** [comment]
This is great! But, it's not quite enough. --stop-after=0|1 cannot be easily scripted, because it's not a toggle. The best I can do is make a file that tries to match the --stop-after status, i.e. if the file exists, stop-after is turned on, and if not, it's turned off, and do things like delete the file when quodlibet starts or quits or when the song changes. It's proving just as finnicky as the xdotool method. I still don't have a reliable script to toggle --stop-after until there's a toggleable option or a way to "get" the current status of stop-after.

**Comment by lazka** [comment]
What about `--stop-after=0|1|t` like `--queue` ?

**Comment by Jimi-James** [comment]
That would work.
