### ISSUE TITLE
"Hidden songs" in Preferences > Library

### ISSUE THREAD

**Issue by ghostwords** [quodlibet/quodlibet#1910]
Could you please provide some pointers re the "hidden songs" feature found under Preferences > Library?

Every time I start Quod Libet, "hidden songs" lists some songs hidden in my home directory, and some more songs hidden one level up from my home directory, in `/home`. Next to that list are "Unhide" and "Remove" buttons. What are these songs and why do they get hidden?

**Comment by urielz** [comment]
Probably someone has a better explanation. But did you move some of your songs from one directory to another? If so, then I think QL shows those songs as hidden.

**Comment by lazka** [comment]
It means the mount point the files where part of when they were loaded is no longer there (e.g. when you add songs from an USB drive and remove the drive)

**Comment by ghostwords** [comment]
I feel like this is related to installing a second disk drive. Is there a quick way to find the offending songs?

Should clicking "Rebuild Library" on that same Preferences > Library screen take care of this issue? I just did it and it didn't seem to change anything. I guess there is no real issue, I'm just confused by this screen.

**Comment by ghostwords** [comment]
So I still don't know how these "hidden songs" came to be in my case, but I can share what I did to find them. I noticed a song that would suddenly appear after clicking the Unhide button in QL's preferences; according to the song's information screen it was 0 bytes in size. So then I added the File Size header (under File Headers) to the browser, and sorted by it. It seems like all the "hidden songs" were 0 bytes.

**Comment by mumeiyamibito** [comment]
I manage my music files and quodlibet config files on multiple PCs with a sync system like Dropbox. Finally, these music directories are referred to as symlinks in the home directory under the name Music. However, quodlibet treats the music files in this directory (symlink) as hidden songs.

From these facts, quodlibet seems to convert the path of the music file to the absolute path or the link source path once. What is the reason for this?
I want to manage files with symbolic links.

**Comment by Meriipu** [comment]
> I manage my music files and quodlibet config files on multiple PCs with a sync system like Dropbox. Finally, these music directories are referred to as symlinks in the home directory under the name Music. However, quodlibet treats the music files in this directory (symlink) as hidden songs.
> 
> From these facts, quodlibet seems to convert the path of the music file to the absolute path or the link source path once. What is the reason for this?
> I want to manage files with symbolic links.

I am not sure about the details but I believe dealing with symlinks is a known and fairly involved issue which has not had much if any satisfactory fixes
#2806 
#708 
#3105 
#1939
#176 (issue probably superseded by another issue by now)
#3337
