### ISSUE TITLE
[Request] Refresh library via command line

### ISSUE THREAD

**Issue by spxxxk** [quodlibet/quodlibet#1914]
Or "Scan library" now I believe.

**Comment by lazka** [comment]
There already seems to be `--refresh`. It was missing from the man page, added it now. Does that work for you?

**Comment by spxxxk** [comment]
Works great thanks.
It would be good to have `--print-query`, `--refresh` ... run without UI, but that will do fine.

**Comment by lazka** [comment]
That would be to complicated atm... but I'll keep it in mind for the next refactoring.
