### ISSUE TITLE
Queue almost invisible in GTK 3.20

### ISSUE THREAD

**Issue by Jimi-James** [quodlibet/quodlibet#1915]
Well, that was quite an update. On Arch Linux, x64. I was running 3.5.1 when the update hit, and the queue was invisible (among other problems). Upon upgrading to the newest git version, the other problems are fixed, but the queue is only slightly less invisible. Instead of not showing up at all, I can only see one song at a time. And it can't expand as far up as it used to; instead of being capable of completely eclipsing the song list, it now leaves one song visible at its maximum level of expansion.
![screenshot_2016-04-15_13-25-13](https://cloud.githubusercontent.com/assets/5751606/14573999/c1f23b5e-030d-11e6-8af2-0f5611a3973e.png)

**Comment by lazka** [comment]
Filed upstream: https://bugzilla.gnome.org/show_bug.cgi?id=765602

**Comment by Jimi-James** [comment]
Is there some sort of workaround that can be done while we wait for GNOME to notice this at all?

**Comment by lazka** [comment]
A new release with a workaround is now available.

**Comment by Jimi-James** [comment]
Since I updated to the new version with the workaround, suddenly I can no longer click+drag songs anywhere, resulting in not being able to put songs anywhere in the queue besides at the end.

**Comment by lazka** [comment]
Maybe you are using gtk+3.20.4? DnD was broken there.

**Comment by Jimi-James** [comment]
Oh, I am! Well, then I guess I'll just upgrade gtk3.

**Comment by lazka** [comment]
The horizontal packing is still broken in the queue label, but nothing we can do here, so closing.
