### ISSUE TITLE
An exception has occurred in Quod Libet

### ISSUE THREAD

**Issue by alan12345678** [quodlibet/quodlibet#1918]
the pop up message asked me to file a new issue, so I'm simply obliging
[Dump_20160417_123222.txt](https://github.com/quodlibet/quodlibet/files/222597/Dump_20160417_123222.txt)

**Comment by lazka** [comment]
Thanks. Could be that this is fixed with 3.6.1: https://quodlibet.readthedocs.org/en/latest/downloads.html#windows

**Comment by lazka** [comment]
Were you using the album list view when this error occurred?

**Comment by alan12345678** [comment]
Yes.

At present I tend to close QL with a second browser window open, such that when it restarts this second window also opens. The attached error occurred during startup

**Comment by alan12345678** [comment]
I notice that through the above link, Fedora 23 is still only packaging ver 3.5.3-1

After previous difficulties  in Fedora (being a newbie) with other apps, I've rather sworn off local compiling... but happy to give it a go with QL if you feel it worthwhile

**Comment by lazka** [comment]
OK, I've fixed something related in 3.6, so maybe that's fixed then. The error it self is harmless btw.

Thanks for the report.

**Comment by lazka** [comment]
Oh, I haven't added f23 repos, I'll look into that.

**Comment by lazka** [comment]
> After previous difficulties in Fedora (being a newbie) with other apps, I've rather sworn off local compiling... but happy to give it a go with QL if you feel it worthwhile

Yeah, it's not worth the trouble in most cases.

**Comment by lazka** [comment]
A Fedora 23 repo is now available
