### ISSUE TITLE
AssertionError when I add a custom browser

### ISSUE THREAD

**Issue by SnouF** [quodlibet/quodlibet#1919]
When I add my custom browser in ~/.quodlibet/browsers I have a AssertionError

```
Traceback (most recent call last):
  File "/usr/bin/quodlibet", line 231, in <module>
    main(util.argv)
  File "/usr/bin/quodlibet", line 79, in main
    browsers.init()
  File "/usr/lib/python2.7/dist-packages/quodlibet/browsers/__init__.py", line 47, in init
    load_compiled=load_pyc)
  File "/usr/lib/python2.7/dist-packages/quodlibet/util/importhelper.py", line 24, in load_dir_modules
    assert package in sys.modules
AssertionError
```

If I remove ("/usr/lib/python2.7/dist-packages/quodlibet/util/importhelper.py", line 24)
```
assert package in sys.modules
```
my browser work (it use cpickle)

Quod Libet 3.6.1 with officiel debian package quodlibet:all/sid 3.6.1-2

**Comment by lazka** [comment]
Indeed, seems like this is broken since at least 3.2 based on quick testing.  The interface for browsers in `~/.quodlibet/browsers` was changing quite often anyway and developing works just as well by placing it into the source tree, so I'm going to remove that "feature".

**Comment by lazka** [comment]
Check out https://quodlibet.readthedocs.org/en/latest/development/devenv.html#linux-logo-linux if you want to work on a browser.

**Comment by SnouF** [comment]
I regret this feature to be suppressed. But this choice seems justified;)

**Comment by lazka** [comment]
> I regret this feature to be suppressed.

Why? Just wondering...

**Comment by SnouF** [comment]
Can add a browser by copy paste without root permission is easy and convenient. Especially for users

**Comment by lazka** [comment]
OK, thanks. Maybe we'll add browser plugins in the future..

**Comment by SnouF** [comment]
Will be perfect !

I did not have long used the Quodlibet podcatcher did not suit me caril there was no "filter" listen / not listen.
This feature is still no but my little python knowledge allowed me to adapt to my audiofeed https://gitlab.com/snouf/quodlibet_podcasts_browser use.

Iam happy to see that the project is still very active.

Tank for your job !
