### ISSUE TITLE
Provide a snap package

### ISSUE THREAD

**Issue by CreamyCookie** [quodlibet/quodlibet#1922]
With Ubuntu 16.04 LTS there will be a [new packaging format, called snap](https://developer.ubuntu.com/en/desktop/). Compared to PPA's — which aren't going away in 16.04 — snap packages (or snaps, as they call them) will provide some [additional benefits](https://developer.ubuntu.com/en/desktop/get-started/) like sandboxing. Users can install them with a click and developers can provide (delta) updates. Of course one can also install snaps via the command line and, if submitted, from the Ubuntu store.

**Comment by lazka** [comment]
Any work on this welcome :)

**Comment by lazka** [comment]
worth checking out: https://github.com/mikix/deb2snap

**Comment by lazka** [comment]
Gave it a short spin and got stuck because it failed to install distutils python packages.
Imho we should wait for some larger apps to provide a package and look at their build scripts. Maybe it's easier to create packages manually instead of the automated way with the yaml file.

If anyone knows any, please share.

**Comment by CreamyCookie** [comment]
Yeah, there aren't many yet. Firefox wants to provide one, but hasn't yet. I have no idea if this helps, but here's one I found: [Ubuntu Calculator App](https://code.launchpad.net/ubuntu-calculator-app) ( http://bazaar.launchpad.net/~dpm/ubuntu-calculator-app/snap-all-things/files )

**Comment by CreamyCookie** [comment]
There is also [Flatpak](https://en.wikipedia.org/wiki/Flatpak) (called xdg-app until May 2016) which currently seems to be officially supported by [more distributions](http://flatpak.org/getting.html) than snap. Even Ubuntu will have [flatpak with 17.04](https://launchpad.net/ubuntu/zesty/+source/flatpak).

**Comment by lazka** [comment]
See #1806

**Comment by CreamyCookie** [comment]
Ah, thanks, I have missed that.

**Comment by CreamyCookie** [comment]
I'm closing this. Flatpak seems better.
