### ISSUE TITLE
'Library' playlist in playlist browser

### ISSUE THREAD

**Issue by Bulmanator** [quodlibet/quodlibet#1924]
I was wondering if it would be possible to add an option to have a Library playlist in playlist browser, all it would be is a playlist which contains all songs in the library and automatically updates/ adds new songs when they are added into the library. Like the image attached only the 'Library' playlist would update automatically

![quodlibet](https://cloud.githubusercontent.com/assets/8584482/14707145/e64fff3e-07ba-11e6-8be1-cf8f0ab341cd.png)

**Comment by declension** [comment]
But... why?

This is really a search (of "" or equivalent), not a [QL] playlist.

Not sure on your use case, but perhaps try using a secondary browser (noting that drag & drop us supported), as this can add a lot of flexibility

**Comment by Bulmanator** [comment]
I would like my full library and my playlists all accessible from the same window, is there any way to dock new browsers rather than having them in a separate window?
It's just the way I used Foobar2000 when I was on windows and Quod Libet is so close to being the perfect replacement

**Comment by pschwede** [comment]
Closest Foobar2k replacement would be [DeaDBeeF](http://deadbeef.sourceforge.net/). Playlists on Quodlibet are used like tags rather than actual lists.

**Comment by Bulmanator** [comment]
DeaDBeeF doesn't have a Library watcher, the main reason I want to use Quod Libet. Thanks for your suggestion though

**Comment by CreamyCookie** [comment]
I don't think, it's possible to dock another window to the main window yet. However, I agree that it would be really nice to have. Even for some plugins being able to choose between a separate window or an area in the main window, would be very useful. Currently browser windows also have the problem that they don't become visible when the main window is brought to the front.

**Comment by declension** [comment]
Docking would be cool, but no idea how or even _if_ that's possible in GTK+.

We've been discussing plugins owning UI areas on and off for years, see Issue #152, and I'm still really keen to work out a way of doing this generically (and neatly enough). _One day_...

**Comment by declension** [comment]
I've raised #1991 to continue the UI part of this.

The playlist part is not achievable with the current model (library); discussions of a new playlist library are in #518.

Closing this ticket for now.
