### ISSUE TITLE
PyPI index for quodlibet is out of date (showing 2.5.1 as latest)

### ISSUE THREAD

**Issue by woodsb02** [quodlibet/quodlibet#1925]
The [PyPI index for quodlibet](https://pypi.python.org/pypi/quodlibet) is out of date, as it shows 2.5.1 is the most recent release, whilst at the time of writing 3.6.1 is the most recent.

One of the PyPI package index owners (lazka or piman) needs to [update the PyPI index](https://docs.python.org/2/distutils/packageindex.html).

**Comment by lazka** [comment]
Thanks. I don't think there is any value in having quodlibet on pypi, so we should probably remove it.

**Comment by declension** [comment]
+1

**Comment by lazka** [comment]
pypi is currently broken... https://bitbucket.org/pypa/pypi/issues/442/500-server-error-trying-to-register

**Comment by lazka** [comment]
Done
