### ISSUE TITLE
Lyrics Window plugin: prevent malicious ads from running

### ISSUE THREAD

**Issue by CreamyCookie** [quodlibet/quodlibet#1927]
So, I have no idea if this is even possible to fix, but when I returned to my PC I saw this:

![web cancer](https://cloud.githubusercontent.com/assets/3063858/14897859/169768ca-0d84-11e6-9239-c6bacccd692e.png)

(I don't even have a Nexus 5.)

After clicking okay, the browser of the lyrics window showed me a phishing page that basically said something similar to the above Javascript messagebox. It also used the Google logo to make it seem official. I sadly couldn't make a screenshot of that, because the song was over before I had done it. The song was "J'ai Dormi Sous L'Eau" and it has a [lyrics wiki page](http://lyrics.wikia.com/wiki/Air:J'ai_Dormi_Sous_L'Eau).

The only explanation I have is that some advertisement code from lyrics wikia or the site itself has been hijacked. When I now play that song, it doesn't happen, so my guess is that it's just one advertiser.

**Comment by lazka** [comment]
Uh, the lyricswiki page is horrible now; lots of big and slow ads...

**Comment by CreamyCookie** [comment]
Yeah, I  have no problem with text ads that don't need JavaScript and don't track one either. But these ads are not only sometimes malicious, they also waste your time in many different ways (slowing down the browser / loading the site, being distracting and (sometimes) having to click them away).

Anyway, it would be cool if an organization like Wikimedia could provide a site for lyrics (without having to pay royalties and obviously without ads).
