### ISSUE TITLE
[exfalso] Missing 'Release' info in MusicBrainz lookup for versions > 3.5.3 ?

### ISSUE THREAD

**Issue by Negativland** [quodlibet/quodlibet#1929]
Hi,

I'm running Fedora 23 with the latest stable packages from the official repo, aka version 3.5.3.

I tested your Fedora repos (stable & unstable - 3.6.1 & 3.6.99) and it seems that when I make a lookup on the MusicBrainz database, the "Release" information is missing on the bottom of the window (see screenshot attached).  
![exfalso-3 5 3-release](https://cloud.githubusercontent.com/assets/17674151/14941286/0b61be24-0f96-11e6-9b9c-b5b8ee2e5cc8.png)

As a consequence, the `<labelid>` tag is not populated. 
Is this an expected behavior? It was a handy feature, for those who have multiple versions of the same release (eg. different remasters).

Cheers,
Negativland

**Comment by lazka** [comment]
> I tested your Fedora repos (stable & unstable - 3.6.1 & 3.6.99) and it seems that when I make a lookup on the MusicBrainz database, the "Release" information is missing on the bottom of the window (see screenshot attached).

The plugin was ported to musicbrainz NGS in 3.6, the top combobox should now contain all releases. Is there any information on the release you are missing to make a decision?

> As a consequence, the tag is not populated. 

Which tag are you missing?

**Comment by Negativland** [comment]
I'll retest with the latest version ASAP and I'll let you know, thanks.
The missing tag is the _labelid_ one, sorry (wrote it between < and >, it must have been interpreted badly).

**Comment by lazka** [comment]
>  The missing tag is the labelid one, sorry (wrote it between < and >, it must have been interpreted badly).

Ah ok. labelid should no longer be needed; the plugin writes `musicbrainz_albumid` tags which identify the release. e.g. https://musicbrainz.org/release/3663a8a9-1c67-41c2-82c8-6a241d1558f7

The plugin now also can tag multi disc releases e.g. your posted example will be split into 4 discs with one track each, all having the same `musicbrainz_albumid`

**Comment by Negativland** [comment]
Indeed, the `musicbrainz_albumid` tag is set and correctly identify the release!

I'm using the human readable `labelid` tag in quodlibet for custom searches (eg: search for all releases of a specific label, when the cat# are coherent of course), and it is a part of my file path for storing releases (eg: `<artist>/<year> - <album> [<labelid>]/<discnumber>.<tracknumber> - <title>`)
For famous releases, it is also handy to quickly pick the correct issue in a long list of reissue. =)

**Comment by lazka** [comment]
ok, maybe we can add an option for writing and displaying labelid.

**Comment by Negativland** [comment]
Thanks!
