### ISSUE TITLE
Missing shortcut labels on control menu

### ISSUE THREAD

**Issue by urielz** [quodlibet/quodlibet#1931]
Minor detail but thought I should report it anyway: shortcut labels for “Information” (Primary + I) and “Edit Tags” (Alt + Return) are missing in the “Control” menu (they do appear in the right click context menu though). (QL 3.6.1, OS X)

**Comment by lazka** [comment]
The one on the control menu are for the current song while the one in the context menus are for the selected song. I'm worried that having the same shortcut in both places is confusing as the result depend on the keyboard focus then.

Any ideas welcome..

**Comment by urielz** [comment]
Thanks for the clarification. In my opinion as it is right now is confusing. Perhaps it’s just me, but it was not clear till you pointed out that ‘edit tags’ and ‘information’ in the control menu were for the currently playing song. Couple of ideas:

(a) Perhaps making it more explicit would help, for example have a sub-divider in the control menu with a title? Something like “Currently playing” and then underneath the option to add bookmarks, edit bookmarks, edit tags and information. It's not the style of the UI right now so I don't know...

(b) Definitely not fan of assigning the same shortcut keys for both. But perhaps add a modifier like shift for the option in control menu? (shift+primary+I, shift+alt+enter)

Anyway, will keep this open for a bit and see if someone come up with better ideas. This is definitely nit picking on my book..

**Comment by CreamyCookie** [comment]
I've moved the remaining part of this to a new issue for clarity: #3229
