### ISSUE TITLE
Rename files crashes when pattern contains directory separators

### ISSUE THREAD

**Issue by ccerghed** [quodlibet/quodlibet#1937]
After entering this pattern in Ex Falso:
`<artist>/<album>/<tracknumber> - <title>`
the software throws an exception (see attached file).
I wasn't sure whether directory renaming was supported?  I know it's supported in Easytag.
[Dump_20160510_223745.txt](https://github.com/quodlibet/quodlibet/files/258487/Dump_20160510_223745.txt)

**Comment by lazka** [comment]
Thanks. The error happens when we want to display the following error message:

![screenshot from 2016-05-11 06-50-48](https://cloud.githubusercontent.com/assets/991986/15170356/45fa83b6-1745-11e6-8964-9177a58cf369.png)
