### ISSUE TITLE
"Force Write" is a scary name for a plugin.

### ISSUE THREAD

**Issue by quequotion** [quodlibet/quodlibet#1938]
I'm not reporting a bug about quodlibet or the plugin's fuctionality, just this string:

http://postimg.org/image/dyby69nsx/

The description sounds like _overwrite_ to me, while _force write_  has the connotation that files will be written _even in case of error_.

Unless that is actually the case (quodlibet forces a write-to-disk operation disregarding failure),  "Overwrite" (quodlibet writes to files the traditional way, disregarding only that they already exist) _sounds_ better to me.

**Comment by lazka** [comment]
It just writes the tags as if a tag was changed in the editor.

**Comment by declension** [comment]
Yeah, I see what the OP is saying. Perhaps _flush_ or _synchroni(s|z)e_ would convey the intention better, but they're not exactly user friendly either...

**Comment by quequotion** [comment]
I'd go with _synchronize_ of the two; _flush_ (dump data to disk) is sort of jargon in this sense and could be misinterpreted. _Synchronize_ has an en-* problem; _overwrite_ feels somewhat jargon as well.

thesaurus:
transcribe, overtype, crush, run over

On top of this, I don't think end-users {want to be, are} aware that tags are written separately to the database and (not) to the files to begin with while I understand the need to default to not risking people's files though--writes are vulnerable, even if the plugin doesn't have bugs.

**Comment by CreamyCookie** [comment]
I would rather be more verbose and name it something like "Write tags to files" or "Update tags in files".

**Comment by quequotion** [comment]
Cookies' idea has the best ring to it. "Write tags to files" is very clear.

**Comment by declension** [comment]
+1 for _Update tags in files_ - and prefer it to write as it indicates the repeatable nature of the action a bit better IMO.

**Comment by lazka** [comment]
Sounds good.
