### ISSUE TITLE
Move Library Path

### ISSUE THREAD

**Issue by kaffeeundsalz** [quodlibet/quodlibet#1939]
I have stored all my music files on an SMB share in the local network. Since the music collection is pretty large and the network pretty slow, scanning the library over my wifi network literally takes forever. So my idea was to first plug in the drive directly via USB, let QuodLibet scan all my files, put the drive back to the network and then adjust the path to the music files afterwards.

Since there doesn't seem to exist a library migration plugin or something the like, I tried to achieve this by directly manipulating the song list of QuodLibet. What I did was that I took the `~/.quodlibet/songs` file and replaced all occurrences of `/Old/Path/` with `/New/Network/Path` and also changed the scan directory in `~/quodlibet/config` to match the new library path.

This doesn't seem to do the trick. Whenever I open QuodLibet after editing the above files, the song list seems to be empty. Also, I get a `~/.quodlibet/songs.notvalid` file, so QuodLibet seems to remember the old file paths somewhere.

What have I missed? Is the whole approach possibly stupid?

QuodLibet 3.6.1 on OS X 10.11.4 El Capitan

**Comment by lazka** [comment]
The code to move files in 3.6 would be:

```
#!/usr/bin/env python2

import os
import re
import quodlibet
from quodlibet import library

quodlibet.init()
lib = library.init(os.path.join(quodlibet.get_user_dir(), "songs"))

for song in list(lib):
    fn = song["~filename"]
    new = re.sub("^/old/dir/", "/new/dir/", fn)
    if new != fn:
        lib.remove([song])
        song["~filename"] = new
        lib.add([song])

lib.save()
```

which you have save, adjust the paths and execute like `./QuodLibet.app/Contents/MacOS/run myfile.py`

Is the slowness a QL only problem? Does it affect other players?

**Comment by lazka** [comment]
btw, if the modification time of the files changes QL will try to reload them during a library scan.

**Comment by urielz** [comment]
It would be great if this can be added officially as a feature to quodlibet. Or at the very least put it somewhere in the documentation...

**Comment by kaffeeundsalz** [comment]
Wow @lazka, thanks for the pretty much complete solution! It seriously didn't cross my mind to do it with Python.

Concerning network speed: The low transfer rates are really the result of my poor implementation. In a very amateurish way, I connected a regular external hard disk to the USB port of my router, the drive itself being HFS+ formatted and shared via the router's internal SMB client. I know there are much smarter solutions for this – I just needed a quick, free-of-cost way to get my library on the network. So the snail's pace is essentially by design here and definitely not a QuodLibet issue. Anyway, it's still fast enough to play FLAC files without dropouts (not for scanning large amounts of files in a reasonable amount of time though).

Thank you again for your kind support.

**Comment by davidSchlosser** [comment]
I also need to move my library. What changes do I need to make to the code & instructions @lazka provided for it to work for QL 3.9.1 on Ubuntu 16.04 LTS?

**Comment by declension** [comment]
Hmm, perhaps we should add this as a feature

**Comment by fdw** [comment]
Is this now integrated into version 4.0?
I have tried @lazka's code, but unfortunately it run into some AssertionErrors. How can I migrate my database without losing all the metadata?

**Comment by urielz** [comment]
@fdw I haven't tried lazka's code. But you can migrate your database without loosing the metadata by using the "Update tags in files" plugin. The only field that is NOT saved is the "Last Played" field. It is not a complete solution but it worked quite well for me when I migrated all my music to a NAS server.

**Comment by fdw** [comment]
Thanks, @urielz!
Unfortunately I can't test it currently. Is the "date added" field preserved? Because, ideally, I'd keep both that "last played".

**Comment by TombusPL** [comment]
Hi!
I do not know if this option is in 3.9.1, but how to deal with this version?

I moved my files, which were also in playlists and were given raiting.
How to fix it? I tried the script, but it did not work or I did something wrong.

**Comment by deutrino** [comment]
Ouch. I thought I could just move my library to a new computer and rsync .quodlibet (preserving modification times), and it's filling with duplicates on the initial 'loading files....' even after I munged all paths in playlists and in the config file and everything. It's adding dupes that have outdated play counts and rating data (which I chose to store in the file but isn't always properly synced between QL's db and the file metadata). This is painful. I will try to poke at it with Python like the example posted above almost 2 years ago and hope that not much has changed and it will work, but moving libraries is a fairly common use case that could stand a bit of love. Thanks for all the hard work.

**Comment by davidSchlosser** [comment]
FWIW - In another script using QL4.2 (development) I've found the following code sequence avoids the AssertionError (call init() before importing the library module):

import os
import re
import quodlibet
quodlibet.init()
from quodlibet import library

**Comment by azarmadr** [comment]
i modified the file path using musicbrainz picard and rescanned the library.
now i lost all my user stats like play count and skips and rating, etc.

**Comment by declension** [comment]
Looking for volunteers to try a branch - see #3506 to see how it works on various systems @kaffeeundsalz @urielz @deutrino and others...

**Comment by urielz** [comment]
@declension Just seeing this. Will test it later this week and report back.
