### ISSUE TITLE
Add query syntax to match on missing tag values

### ISSUE THREAD

**Issue by CreamyCookie** [quodlibet/quodlibet#1940]
I'd like to search for all the songs with high ratings that I haven't listened to in a while or which have no recorded "lastplayed" date. The query might look like this

`&(#(rating:max > 0.8), |(#(lastplayed > 6 month ago), #(lastplayed is None)))`

Similarly, searching for songs that haven't been rated yet could be interesting if you want to rate most or all of the songs in your library.

**Comment by lazka** [comment]
Sounds good. I'd go for `#(lastplayed = none)` to not introduce more keywords for this.

**Comment by CreamyCookie** [comment]
@lazka Hmm, good point, but would this also work for string values, so that  `artist = none` finds all songs where the artist hasn't been set? Of course, that's a use case I
