### ISSUE TITLE
Rename "Search Library" to "Song Browser"

### ISSUE THREAD

**Issue by CreamyCookie** [quodlibet/quodlibet#1943]
I think we should rename "Search Library" to "Song Browser" (or similar), as most browsers can search, and so the name "Search Library" doesn't really differentiate it from the other browsers.

**Comment by urielz** [comment]
Agree with you. "Song Browser" or "Library Browser" are more appropriate.

**Comment by lazka** [comment]
Related: #1716

**Comment by declension** [comment]
Agree, insofar as it's a weird name... **but**:
 _all_ the browsers are song browsers and/or library browsers of some sort, so I'm not sure that's much clearer in the end.

That said, this might be mitigated if we renamed the _View_ menu to _Browse_, moving the two toggle options if it's too weird keeping them. Then the implied _browse songs / library_, _browse playlists_, _browse media devices_ etc makes more sense, IMO. However it's a little non-standard.

**Comment by figtrap** [comment]
I totally disagree, "song" is only one of many forms of music, everything isn't a "song",  "library" or "collection" is more appropriate.

**Comment by CreamyCookie** [comment]
@figtrap The reason I chose "song" is because compared to most other browsers, this one doesn't group songs into albums. But yeah, it isn't the best name. How about "Individual Track Browser"? A bit long, but more specific and not focused on songs only.

As @declension already mentioned, "library" or "collection" isn't really better since all browsers are library browsers because they contain music from the library.

**Comment by declension** [comment]
Are people still keen for this? _Track Browser_ seems to be the best option from above (i.e. _Browse_ -> _Tracks_)

**Comment by CreamyCookie** [comment]
Yeah, *Track Browser* would be a big improvement.

**Comment by lazka** [comment]
(Track List?)
