### ISSUE TITLE
performer:role search functionality

### ISSUE THREAD

**Issue by urielz** [quodlibet/quodlibet#1948]
Is there a way to search for performers without having to explicitly type the role? 

A search for performer = X won’t show anything if X is tagged as performer:role. If this is something not currently possible I would suggest to consider this as an enhancement...

**Comment by lazka** [comment]
There is `~performer` and `~performer:roles`

https://quodlibet.readthedocs.io/en/latest/guide/tags/internal_tags.html#the-performers-internal-tag

(there is a bit of confusion there with "performer" vs "performers", both variants work)

**Comment by lazka** [comment]
Does this work for you?

**Comment by urielz** [comment]
Got it. Thanks for the answer. But just to be clear what seems to work on my end is: ~performer = X  and performer:role = X but ~performer:role = X does not work for me. Am I doing something wrong? Anyway, the functionality is there, just a bit confusing that ~ is needed only in one case...

**Comment by lazka** [comment]
~performer:role**s** ?

**Comment by urielz** [comment]
Ah I see. That works. What I was searching is for explicit roles, for example performer:vocals = X.

**Comment by urielz** [comment]
Thanks for your help lazka. Much appreciated!

**Comment by lazka** [comment]
Yeah, while in the tags ":" is just part of the tag name to separate the role. In the "internal" tag starting with "~" it allows to select a different variant of that internal tag. A bit confusing...
