### ISSUE TITLE
Playing from Filesystem browser

### ISSUE THREAD

**Issue by alan12345678** [quodlibet/quodlibet#1949]
Hope it's okay to ask here, otherwise will post elsewhere as advised.

A few things I don't quite understand. Don't think these are bugs:

I'm able to create custom actions within my file manager. Despite it using context correctly in file manager (Thunar) such that "Play with Quod Libet" appears on any music directory or file, the action itself neither enqueues or plays the files/folders in question. I see a very quick notification flash, but the playlist or queue doesn't change. Does QL even support this?

I've ended up using "file system" to browse my music library in a second browser. However, it appears that I cannot right click to either enqueue or play files from this browser. If I have "file system" as my primary browser then it does work, but with this browser I get no metadata i.e. track titles, times etc. displayed.

So either: is it possible to add right click context to all browsers, such that I can enqueue or play a file or folder from "file system" browsers
Or
Is there a neat way of combining regex (?) to better sort a secondary browser of "album collection" such that if I use "~dirname" to sort, I can omit the first part of the file structure from the display e.g.

"/home/username/music/<artist folder>/<album>" so that I only see the

"../music/<artist>.."

part displayed?

I ask because "file system" seems to be the only browser where there are no context menu items such as tagging, enqueue etc. So, if it's possible to configure a browser to essentially order the display by directory structure FIRST, and then by artist/album, I'm away! :0)

**Comment by lazka** [comment]
> I'm able to create custom actions within my file manager.

You should be able to open files with quodlibet without adding anything. How do you create custom actions? If you want do do it manually it should be `quodlibet --run --play-file <path_to_file>`

> Despite it using context correctly in file manager (Thunar) such that "Play with Quod Libet" appears on any music directory or file, the action itself neither enqueues or plays the files/folders in question. I see a very quick notification flash, but the playlist or queue doesn't change. Does QL even support this?

It does, but only one song of the selected will be played. And it will only be played and not enqueued etc.

Before we go any further -> Which distro and which quodlibet version are you using?

**Comment by alan12345678** [comment]
I realise I should have been more explicit in my original post. There are two separate issues here.

With QL open, having "file system" as my primary browser - thus displayed below the player - presents no problems. However, I want to use a second browser, as the separate window, for selecting and enqueueing or playing my music.

Once I have the music library folder open within this second file system browser, my problems are within the left-hand panel. Imagine that my albums are grouped within artist folders. Thus I can easily navigate to the desired location. From here I would like to simply right click and see "play" or "enqueue" appear. But it doesn't, because all there are as menu items are:

New Folder
Delete
Refresh
Select all subfolders

Of course if I were to click on a discrete folder, such that all the music files then appear on the right hand pane, I could play them. But this entails "select all" followed by right click. That's a bore - basically a deal breaker. In the absence of context menus in the leftmost pane that would simply allow me to either play or enqueue, I went to a secondary option which is:

Use file manager to open the music library, and see if I can simply "play with Quod Libet" on any desired folder. I can't. I'm running Fedora 23 with Gnome 3.18.2. However, I also installed @xfce which means I could log on under an xfce session. This is relevant because now my default file manager is Thunar (!), which is now running under Gnome.

It is Thunar which lacks any native context "play with" menus, but which allows me to create custom actions. Their own syntax states that to simply use

command | /usr/bin/quodlibet %F

is sufficient because %f is a single file, whereas %F is multiple files at location. However, all the online instrucitons may well be wrong. Point being that

command | /usr/bin/quodlibet -e %F is supposed to enqueue not play. In any event it does nothing. I get a brief notification banner flash, while the playlist or queue in QL doesn't change or update.

**Comment by lazka** [comment]
> I realise I should have been more explicit in my original post. There are two separate issues here.
>
> With QL open, having "file system" as my primary browser - thus displayed below the player - presents no problems. However, I want to use a second browser, as the separate window, for selecting and enqueueing or playing my music.

Opening the browser in a new window should only change the action of playing a song (double click), everything else should be the same.

> Once I have the music library folder open within this second file system browser, my problems are within the left-hand panel. Imagine that my albums are grouped within artist folders. Thus I can easily navigate to the desired location. From here I would like to simply right click and see "play" or "enqueue" appear. But it doesn't, because all there are as menu items are:
>
> New Folder
Delete
Refresh
Select all subfolders

Yeah, we only load the songs from disks once a folder is selected. This is so we don't have to deal with large folders, where a right click could then take minutes to load all the files (as one major use case for the file system browser is to play songs not in the library). It's a bit unclear what we should do here... ideas welcome.

> Of course if I were to click on a discrete folder, such that all the music files then appear on the right hand pane, I could play them. But this entails "select all" followed by right click. That's a bore - basically a deal breaker. In the absence of context menus in the leftmost pane that would simply allow me to either play or enqueue, I went to a secondary option which is:

What is your main browser in case you open the file system one as a separate window? And why?

> Use file manager to open the music library, and see if I can simply "play with Quod Libet" on any desired folder. I can't. I'm running Fedora 23 with Gnome 3.18.2. However, I also installed @xfce which means I could log on under an xfce session. This is relevant because now my default file manager is Thunar (!), which is now running under Gnome.

Ah, yes, playing folders is not supported atm, only files. We should probably add support for that and queue the files.

> It is Thunar which lacks any native context "play with" menus, but which allows me to create custom actions. Their own syntax states that to simply use
>
> command | /usr/bin/quodlibet %F
>
> is sufficient because %f is a single file, whereas %F is multiple files at location. However, all the online instrucitons may well be wrong. Point being that
> 
>command | /usr/bin/quodlibet -e %F is supposed to enqueue not play. In any event it does nothing. I get a brief notification banner flash, while the playlist or queue in QL doesn't change or update.

As I said above `quodlibet --run --play-file <path_to_file>` works, nothing else will, so `quodlibet --run --play-file %f` in your case

----

Back to your original post:

> So either: is it possible to add right click context to all browsers, such that I can enqueue or play a file or folder from "file system" browsers
Or

See problem with loading on demand stated above.

> Is there a neat way of combining regex (?) to better sort a secondary browser of "album collection" such that if I use "~dirname" to sort, I can omit the first part of the file structure from the display e.g.
> 
> "/home/username/music//" so that I only see the
>
> "../music/.."
> 
> part displayed?

As files can have any path and not have to have a common root dir I can't think of a generic solution for this.

**Comment by alan12345678** [comment]
Ah, I see now :0)

To answer your questions:

The only reason I use a second browser window is because: if I use "file system" as the primary browser (following your other answers, it seems I cannot configure other browsers to sort and display in this exact way), while it does indeed allow me to navigate and simply double click a folder to play it, this browser also has a weirdly minimal interface. What I mean is that when using other browsers, I'm able to edit the prefs and show tag info as I wish and control exactly what gets displayed. This is often highly relevant if I wish to pick a particular track from an album. However, using "file system" it seems you've disabled editing of prefs and simply show a file browser. So I'll open an album folder and it simply tells me "x songs, y hours/minutes" but there's no way of digging down into individual tracks.

I've come to realise that I'm rather fond of the deliberate directory structure of my library, wherein genres have been grouped within folders. I accept that QL respects grouping, but that's several more days of adding more tags.

So, if I then use a second "file system" browser, I at least then get access to discrete tracks in the right-hand pane. As things currently stand, following your answers above, the ONLY thing really missing at this stage is the ability to double click in the left hand pane _in this browser_ to load the folder, although you've also explained why you don't do this. Bit of a predicament ;0)

Suggestions? Well, since the file managers/OS support content filtering, perhaps you could allow the "file system" browser to load folders by filtering only audio formats and ignore everything else. Perhaps this should be as a user set filter. For example, going back to Thunar, my custom actions are allowed to specify file types. If I type "*.mp3" it will only enable an action when it encounters that format within a folder rather than any music file. Obviously I simply extend that filter list to include all the known audio formats in my library. I don't see why it should be a problem if I were mad enough to right click the parent folder for my music library (35,000 tracks). Might take a while, but perhaps I'd like to just play it all the way through? I do see that it's a problem if one collects music in a more 'modern' way whereby it's all linked via playlists and metadata and not its physical location, and whereby files end up all over the place, but then I'm a bit of a nerd and have everything neatly ordered.
