### ISSUE TITLE
Duplicate track in queue option

### ISSUE THREAD

**Issue by Jimi-James** [quodlibet/quodlibet#1952]
Basically, I wouldn't mind having a right-click menu option on songs in my queue that automatically does exactly what the following does:
-Clicking "Add to queue" on a song already in the queue
-Dragging the added track from the bottom of the queue to immediately after itself, so that you have that song twice

It's especially important while we wait for #1915 to get fixed, since I can't actually do this manually at all in a reasonable amount of time with that bug happening if my queue has more than a few songs in it (which it almost always does).

**Comment by lazka** [comment]
You can now ctrl+drag a song to copy it instead of moving it.

**Comment by CreamyCookie** [comment]
Okay, I think is basically fixed with @lazka's change and the [<kbd>Ctrl</kbd> + <kbd>Return</kbd>](https://quodlibet.readthedocs.io/en/latest/guide/shortcuts.html) shortcut (Queue the selected song(s))

I'm also adding the ctrl+drag shortcut to the docs.
