### ISSUE TITLE
Release version on Fedora 23: still on 3.5.3

### ISSUE THREAD

**Issue by alan12345678** [quodlibet/quodlibet#1954]
Not a biggie, as the player's working fine, but I note that there are two newer versions now.

Is there some reason why 3.6 hasn't been packaged (or approved?) for Fedora 23? I've really gone off building my own locally - much prefer to install from repo.

**Comment by lazka** [comment]
I don't know what the update policies are for fedora regarding older distro versions. Johannes Lips is our maintainer there and you can reach him through https://fedoraproject.org/wiki/User:Hannes

If you can't wait we also have fedora repos including the newest version at https://quodlibet.readthedocs.io/en/latest/downloads.html#fedora

**Comment by alan12345678** [comment]
Thanks :0)

Fedora 23 is the current version. I gather Fedora 24 is due in early June? So, afaik I was using current distro :0)

**Comment by lazka** [comment]
By old versions I mean already released versions.

> I gather Fedora 24 is due in early June?

yeah, https://fedoraproject.org/wiki/Releases/24/Schedule
