### ISSUE TITLE
Exception after upgrading to 3.6.2

### ISSUE THREAD

**Issue by HughTG** [quodlibet/quodlibet#1955]
[MiniDump_20160524_085538.txt](https://github.com/quodlibet/quodlibet/files/279551/MiniDump_20160524_085538.txt)
[Dump_20160524_085538.txt](https://github.com/quodlibet/quodlibet/files/279552/Dump_20160524_085538.txt)

Immediately open opening the upgraded version.

**Comment by lazka** [comment]
This looks unrelated to the 3.6.1->3.6.2 upgrade.

Is it still a problem? You can disable the "Last.fm Cover Source" plugin for now.

**Comment by HughTG** [comment]
Thank you, 

I have not disabled "Last.fm Cover Source" but the problem has not recurred so I will close the issue.  Apparently a one off event.
