### ISSUE TITLE
Bayesian Avg Amount

### ISSUE THREAD

**Issue by leblowl** [quodlibet/quodlibet#1956]
Hey all,

sorry to add another issue to this tracker... I'm curious about this Bayesian Avg. Amount in preferences. What does this mean: 
```
"Bayesian Average factor (C) for aggregated ratings.\n"
"0 means a conventional average, higher values mean that "
"albums with few tracks will have less extreme ratings. "
"Changing this value triggers a re-calculation for all "
"albums."
```
- particulary `less extreme ratings`, I don't get it. Does that mean songs from albums with fewer tracks will get lower ratings than songs from albums with more tracks? Why do the number of tracks in an album even come into consideration with this? Can we edit how the Bayesian Avg. is calculated? Do # of times a song is played get factored into this rating thing? Lot's of questions haha. Thank you so much, I am really enjoying your app.

**Comment by declension** [comment]
See [Bayesian average](https://en.wikipedia.org/wiki/Bayesian_average) for the theory.

The idea is that an album of 12 songs with an average of `0.75` is, in human terms, more likely to be a highly valued album than, say two songs with `1.0` and `0.5`, even though the traditional mean is the same.

By _less extreme ratings_ I meant that albums with only a few songs won't get close to `0.0` or `1.0`. Personally I find it very useful for ordering by rating.  

Similar algorithms are used for rating online purchases etc, to avoid one good / bad review spoiling an item when _n_ is low.

By setting the QL setting value for `c` to `0` you can effectively disable this feature.

Play count is not involved in ratings, but you can of course sort or query on `~#playcount`

**Comment by leblowl** [comment]
ok I get it, thanks for explaining
