### ISSUE TITLE
Selected text in display area doesn't appear selected if custom background color is set

### ISSUE THREAD

**Issue by spxxxk** [quodlibet/quodlibet#1957]
Hopefully the screenshot will be more clear.
Here all text is selected but only the last line appear selected.
Copying text works but I can't tell what is selected ...
It used to work ok, but no longer works on all themes, Ambiance included.

Display area setting: http://sprunge.us/PYAB

![ql_ss](https://cloud.githubusercontent.com/assets/11503399/15626602/a83520c8-24c8-11e6-96e5-2b6d89981efa.png)

**Comment by lazka** [comment]
Thanks. Looks like a gtk+ bug/change (assuming it worked before as you said..)
