### ISSUE TITLE
Cover isn't displayed

### ISSUE THREAD

**Issue by CreamyCookie** [quodlibet/quodlibet#1962]
I've found another cover that isn't displayed in Quod Libet. The cover works fine in Ubuntu's image viewer. It's in the same folder as the mp3's and named "folder.jpg". ("Prefer embedded album art" is disabled.) "Reload cover art" has no effect.

The cover is from the Fallout 1 soundtrack that can be downloaded from GOG if you own the game: https://mega.nz/#!2UpjhZQR!svtAuk0o5yj4ovGLLpLHuE3vPceBfbqVd2xfUrP3Rp8

(Weirdly enough the same happens with the fallout 2 cover.) 

I'm on Ubuntu 16.04. QL is 3.6.2

**Comment by urielz** [comment]
I can confirm same happens on QL 3.6.1 OS X. It's just the thumbnail that doesn't appear, clicking the empty thumbnail displays the full cover fine.

**Comment by lazka** [comment]
Same problem as #1670

The image is probably invalid somehow (firefox, eog are missing the bottom, in gimp it works)

As noted in the other bug report I've reported the inconsistent error handling upstream: https://bugzilla.gnome.org/show_bug.cgi?id=753605

**Comment by CreamyCookie** [comment]
@lazka Thanks and sorry for reporting it twice.
