### ISSUE TITLE
"An exception has occured in Quod Libet"

### ISSUE THREAD

**Issue by rmlrml** [quodlibet/quodlibet#1964]
...but I was not running Quod Libet.  I don't have Quod Libet installed on my system, only Ex Falso, which I was running.  I was looking through the custom commands window, closed that window, and this exception notice popped up.

[Dump_20160608_033145.txt](https://github.com/quodlibet/quodlibet/files/304234/Dump_20160608_033145.txt)

**Comment by lazka** [comment]
```
Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/quodlibet/qltk/exfalsowindow.py", line 222, in __changed
    if song("~#mtime") + 1. < mtime(filename):

TypeError: coercing to Unicode: need string or buffer, float found
```
