### ISSUE TITLE
Add option to display lenght in seconds instead of hh:mm:ss

### ISSUE THREAD

**Issue by MartinBorg** [quodlibet/quodlibet#1967]
I prefer the length of tracks displayed in seconds rather than hours:minutes:seconds.
Sounds odd, but is useful in some situations, at least for me.

**Comment by lazka** [comment]
In which context do you want it to display seconds (in the UI)?

**Comment by MartinBorg** [comment]
Practically any context.

**Comment by lazka** [comment]
OK, thanks. Could you go into detail why you prefer seconds and in which situations it is useful?

**Comment by MartinBorg** [comment]
1. When I estimate roughly the length of multiple tracks, addition of decimal numbers is easier for me than with a combination of decimal and babylonian, sexagesimal numbers (hh:mm:ss).
2. When I need the length in seconds to use in another program, e.g. I'm looking for a track of a certain length for a video and this video (scene) is given in seconds.

I assume, that not many people would make use of this feature. That's why I put the option "hidden" in the config file. But I would change the implementation to look up the config option only once at startup.

**Comment by declension** [comment]
Fixed in #2021
