### ISSUE TITLE
Quodlibet does not work on openSUSE Leap 42.1

### ISSUE THREAD

**Issue by jovo-** [quodlibet/quodlibet#1969]
[Dump file](http://paste.opensuse.org/4882128)
```
== SYSTEM INFORMATION:
Quod Libet 3.6.2
Mutagen 1.32
Python 2.7.9 (default, Dec 13 2014, 18:02:08) [GCC] linux2
Platform Linux-4.1.21-14-default-x86_64-with-SuSE-42.1-x86_64

=== STACK TRACE
Traceback (most recent call last):

  File "/usr/lib/python2.7/site-packages/quodlibet/player/gstbe/player.py", line 524, in __message
    self.__handle_missing_plugin(message)

  File "/usr/lib/python2.7/site-packages/quodlibet/player/gstbe/player.py", line 569, in __handle_missing_plugin
    context.set_desktop_id(app.id)

Error: g-invoke-error-quark: Could not locate gst_install_plugins_context_set_desktop_id: 'gst_install_plugins_context_set_desktop_id': /usr/lib64/libgstpbutils-1.0.so.0: undefined symbol: gst_insta
ll_plugins_context_set_desktop_id (1)
```

**Comment by lazka** [comment]
Weird. (Not that familiar with opensuse) Are GStreamer related libraries and plugins included in the main repository in openSuse? Looks like there are some package versions out of sync.

Either way, this error happens when you're missing some GStreamer plugins, so installing them should help (gstreamer-plugins-good, gstreamer-plugins-bad, gstreamer-plugins-ugly)

**Comment by jovo-** [comment]
> Looks like there are some package versions out of sync.
I think this is the case. I have reinstalled gstreamer & plugins from Packman & received more error messages. Some parts of gstreamer are from main openSUSE repo and some from Packman repo.

**Comment by lazka** [comment]
OK. From what I see the above error can occur if the opensuse package "gstreamer" is not the same version as the package "typelib-1_0-GstPbutils-1_0". Maybe that helps.

**Comment by lazka** [comment]
Still not working? Got any new errors?

**Comment by jovo-** [comment]
Do not know. I am on Slackware right now :).

**Comment by lazka** [comment]
OK, let's close this then.
