### ISSUE TITLE
Crash while searching Musicbrainz

### ISSUE THREAD

**Issue by iwarford** [quodlibet/quodlibet#1971]
Searching Musicbrainz, got an exception window:

![screenshot - 06252016 - 09 52 43 pm](https://cloud.githubusercontent.com/assets/119796/16360149/2c946bfa-3b1f-11e6-9ebf-49dc2a84c2f7.png)

`$ dpkg -l|grep quodlibet`
`ii  quodlibet                                                   3.6.2-0~ppa0~trusty                                 all          audio library manager and player for GTK3
`

Attached dump file as per request:

[Dump_20160625_215052.txt](https://github.com/quodlibet/quodlibet/files/333368/Dump_20160625_215052.txt)

**Comment by lazka** [comment]
Thanks.

Was this a one time thing? Or always with one album? Or multiple albums?

**Comment by iwarford** [comment]
Happens on any album that gets results back from a query.  Albums/compilations which aren't found don't cause the exception.

This is typical right now:  https://a.desu.sh/rjyglp.webm

Attached the Dump files that were generated by what I did in that video, just because:

[Dump_20160628_135417.txt](https://github.com/quodlibet/quodlibet/files/337701/Dump_20160628_135417.txt)
[Dump_20160628_135416.txt](https://github.com/quodlibet/quodlibet/files/337705/Dump_20160628_135416.txt)
[Dump_20160628_135415.txt](https://github.com/quodlibet/quodlibet/files/337703/Dump_20160628_135415.txt)
[Dump_20160628_135414.txt](https://github.com/quodlibet/quodlibet/files/337702/Dump_20160628_135414.txt)
[Dump_20160628_135413.txt](https://github.com/quodlibet/quodlibet/files/337706/Dump_20160628_135413.txt)
[Dump_20160628_135412.txt](https://github.com/quodlibet/quodlibet/files/337704/Dump_20160628_135412.txt)
[Dump_20160628_135411.txt](https://github.com/quodlibet/quodlibet/files/337707/Dump_20160628_135411.txt)
[Dump_20160628_135410.txt](https://github.com/quodlibet/quodlibet/files/337708/Dump_20160628_135410.txt)
[Dump_20160628_135409.txt](https://github.com/quodlibet/quodlibet/files/337709/Dump_20160628_135409.txt)
[Dump_20160628_135408.txt](https://github.com/quodlibet/quodlibet/files/337710/Dump_20160628_135408.txt)
[Dump_20160628_135407.txt](https://github.com/quodlibet/quodlibet/files/337711/Dump_20160628_135407.txt)
[Dump_20160628_135406.txt](https://github.com/quodlibet/quodlibet/files/337712/Dump_20160628_135406.txt)
[Dump_20160628_135405.txt](https://github.com/quodlibet/quodlibet/files/337716/Dump_20160628_135405.txt)
[Dump_20160628_135404.txt](https://github.com/quodlibet/quodlibet/files/337713/Dump_20160628_135404.txt)
[Dump_20160628_135403.txt](https://github.com/quodlibet/quodlibet/files/337715/Dump_20160628_135403.txt)
[Dump_20160628_135402.txt](https://github.com/quodlibet/quodlibet/files/337714/Dump_20160628_135402.txt)
[Dump_20160628_135401.txt](https://github.com/quodlibet/quodlibet/files/337718/Dump_20160628_135401.txt)
[Dump_20160628_135400.txt](https://github.com/quodlibet/quodlibet/files/337717/Dump_20160628_135400.txt)
[Dump_20160628_135359.txt](https://github.com/quodlibet/quodlibet/files/337719/Dump_20160628_135359.txt)
[Dump_20160628_135358.txt](https://github.com/quodlibet/quodlibet/files/337720/Dump_20160628_135358.txt)
[Dump_20160628_135357.txt](https://github.com/quodlibet/quodlibet/files/337721/Dump_20160628_135357.txt)
[Dump_20160628_135356.txt](https://github.com/quodlibet/quodlibet/files/337724/Dump_20160628_135356.txt)
[Dump_20160628_135355.txt](https://github.com/quodlibet/quodlibet/files/337723/Dump_20160628_135355.txt)
[Dump_20160628_135354.txt](https://github.com/quodlibet/quodlibet/files/337722/Dump_20160628_135354.txt)
[Dump_20160628_135353.txt](https://github.com/quodlibet/quodlibet/files/337726/Dump_20160628_135353.txt)
[Dump_20160628_135352.txt](https://github.com/quodlibet/quodlibet/files/337725/Dump_20160628_135352.txt)
[Dump_20160628_135351.txt](https://github.com/quodlibet/quodlibet/files/337727/Dump_20160628_135351.txt)
[Dump_20160628_135349.txt](https://github.com/quodlibet/quodlibet/files/337728/Dump_20160628_135349.txt)

**Comment by lazka** [comment]
Uh :/ thanks

I guess some difference in the musicbrainzngs library shipped with trusty

**Comment by lazka** [comment]
Sadly the version shipped with trusty is too broken. I've disabled the plugin there now.

**Comment by lazka** [comment]
I've added a newer version of musicbrainzngs to the PPA, so things should work again.
