### ISSUE TITLE
Go to bookmark plugin is broken

### ISSUE THREAD

**Issue by declension** [quodlibet/quodlibet#1972]
### Steps
* Select a song with bookmarks (e.g. using `~bookmark = !""`)
* Play the song
* Right click for songs menu then click  _Plugins -> Go To Bookmark_ -> (song) -> (any bookmark)
* Also,  _Plugins -> Go To Bookmark_ -> (song) -> Edit Bookmarks

### Expected
* Jumps to the bookmark position
* Brings up the edit bookmarks dialog

### Actual
Neither works for me

**Comment by declension** [comment]
Seems to be something to do with the sub-sub-menu nature - adding these directly to the (standard plugin) `Gtk.Menu` means it works as expected...

**Comment by lazka** [comment]
b02f93759a93c15
