### ISSUE TITLE
Some local album art no longer shows as thumbnails

### ISSUE THREAD

**Issue by declension** [quodlibet/quodlibet#1978]
### Steps
* Choose Album Browser
* Double some albums without art thumbnails showing but with local files (that used to show)
* Click album art

### Expected
* The album art is displayed as a thumbnail in the browser
* The album art is showed in the top left album art section
* On clicking, a large version is showed

### Actual
* No thumbnails in either place
* Clicking the album art cover *does* show the image at full size.
* Clicking _Reload album cover_ does nothing

**Comment by declension** [comment]
Seems to be something to do with some larger JPEGs - though the are loadable they seem hard to thumbnail (corrupt embedded thumbnail, or too big). 

Nemo & Nautilus also don't thumbnail them, yet `eog` is fine at displaying them (similar behaviour to QL really)

**Comment by lazka** [comment]
#1962 maybe?

**Comment by declension** [comment]
Yes, or #1670 really I guess - silent failures to render image. Don't seem that corrupt:

    $ identify $filename
    ... JPEG 1445x1405 1445x1405+0+0 8-bit sRGB 746KB 0.000u 0:00.000


    $ file -b $filename
    JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, baseline, precision 8, 1445x1405, frames 3

**Comment by declension** [comment]
... but closing as duplicate of #1670
