### ISSUE TITLE
Expanding the Queue is confusing

### ISSUE THREAD

**Issue by CreamyCookie** [quodlibet/quodlibet#1980]
In the Radio Browser the queue is visible at the bottom but it cannot be expanded. Since it isn't very reasonable (and not possible currently) to add radio streams to the play queue, I'd vote for removing the queue when the Internet Radio browser is selected. (However, making it possible to expand the queue would also be a solution.)

Version: master and 3.6.2
Ubuntu 16.04

**Comment by declension** [comment]
Are you sure? I can expand and view the queue with the Internet Radio Browser (as shown in attached). Remember, just because you're in one browser doesn't mean that the queue items were _added_ in that browser.

![screenshot from 2016-07-10 10-32-16](https://cloud.githubusercontent.com/assets/3322808/16712788/a3c043c8-4689-11e6-8b8b-b4e9a9f912de.png)

**Comment by CreamyCookie** [comment]
@declension Oh weird.. Actually it seems to be in every browser. It's when I try to increase the size of the Queue while it's closed.

![screenshot from 2016-07-10 12-01-17](https://cloud.githubusercontent.com/assets/3063858/16712907/385b6e7a-4696-11e6-85c5-4da429856efd.png)

So when I try to resize it.. It flickers between these two states (ignore the mouse cursor in the above image).

![screenshot from 2016-07-10 12-00-29](https://cloud.githubusercontent.com/assets/3063858/16712908/3fc0cce6-4696-11e6-945c-8454340d8e8a.png)

**Comment by declension** [comment]
Yeah, I've noticed some weird stuff like that recently. Quite annoying, but no idea when it started hapenning..

**Comment by lazka** [comment]
I think thats a gtk 3.16 or 3.18 bug, fixed in 3.20

**Comment by CreamyCookie** [comment]
Oh okay. Good to hear it has been fixed. Should this report be closed?
