### ISSUE TITLE
There's a checkmark even for songs that have no rating set

### ISSUE THREAD

**Issue by CreamyCookie** [quodlibet/quodlibet#1981]
This is about the checkmark that was added in the context menu of songs. #1891

Maybe we could also use radio buttons instead of the check mark as radio buttons are usually used when you can only select one option of a set.

![screenshot from 2016-07-09 23-55-10](https://cloud.githubusercontent.com/assets/3063858/16710502/3fac96be-4631-11e6-84be-b19c3fc78be6.png)

**Comment by declension** [comment]
Yes, you can't _select_ more than one, but more than one can be selected - try choosing several songs (with different ratings) from the songlist and right-clicking. A radio button set should never have more than one selected.

Your screenshot, meanwhile, illustrates that perhaps the behaviour is a little odd on Collections (Albums, in this case) but looks consistent(ish) with (Bayesian) average of those song ratings). Confusingly, selecting what's already selected would set _all_ the ratings to that value instead, but a radio button would be no better here and arguably slightly worse. 

Either way this is most consistent with the Playlists songsmenu functionality.

**Comment by declension** [comment]
But to the simpler point of showing a rating when there really is none - good catch, I'll fix that.

**Comment by CreamyCookie** [comment]
@declension Good point. I forgot about rating collections of songs. Sorry!
