### ISSUE TITLE
How do :min, :max an other :numeric_func work?

### ISSUE THREAD

**Issue by stoempsaucisse** [quodlibet/quodlibet#1982]
Hi,
I would like to search for "all song with ~#playcount =  ~#playcount:min" which does not work.
How do the :numeric_functions work?

Thanks,

--
martin

**Comment by declension** [comment]
No, that will never work. What are you trying to achieve?

The numeric functions are for _collections_ of songs, where that means something, for example in the context of the album list browser where `#(rating:max > 0.8)` gets albums with at least one song rated over 0.8, or `#(replaygain_track_gain:min > 0)` to find albums with nothing but quiet(ly recorded) songs on them.
