### ISSUE TITLE
Research filter/sort by Album Artist Year

### ISSUE THREAD

**Issue by ldexterldesign** [quodlibet/quodlibet#1985]
Hey,

Thanks for app'

Can you tell me if it's possible to filter/sort by Album Artist Year in the paned view?

Currently struggling to sort artist albums by year <span class="emoji-outer emoji-sizer"><span class="emoji-inner" style="background: url(chrome-extension://immhpnclomdloikkpcefncmfgjbkojmh/emoji-data/sheet_apple_64.png);background-position:67.5% 7.5%;background-size:4100%" title="disappointed"></span></span>

I've had a brief read of https://quodlibet.readthedocs.io/en/latest/guide/tags/tags.html and a play, but nothing's clicking

Hope to hear back

Kind thanks

**Comment by urielz** [comment]
In the paned browser preferences (Icon just below the cover image), you can customize your paned view (click on custom). Not exactly sure what you are looking for, but for example this would let you filter by artists and then year/album:

artist
<~year|[b][i]<~year>[/i][/b] - ><album>

Hope this helps.

**Comment by ldexterldesign** [comment]
Cheers for reply

Hmm, can you check your syntax?

If you use the following syntax, then GitHub will use plain formatting:

```
```text```
```

Hope to hear back

Kind thanks

**Comment by CreamyCookie** [comment]
@ldexterldesign Do I understand you correctly? You want to be able sort the album of a certain artist by the year? 

You can customize the panels in the paned browser:

1) Click on <kbd>Preferences</kbd>

![screenshot from 2016-07-16 18-05-39](https://cloud.githubusercontent.com/assets/3063858/16895781/5a7f8bbe-4b80-11e6-9a6e-b8ae4655b0e6.png)

2) Then add a custom column `~year`
![screenshot from 2016-07-16 18-06-41](https://cloud.githubusercontent.com/assets/3063858/16895799/7ae377b2-4b80-11e6-8b1d-52e0759bb968.png)

3) Click apply.

Now you have 4 panels (if you didn't delete any). Select an artist and you see all the years for the different releases from this artist.

**Comment by ldexterldesign** [comment]
Hey @CreamyCookie,

Cheers for reply

Yep, totally familiar with this solution (Quod Libet's setup this way be default):

<img width="1440" alt="screen shot 2016-07-18 at 10 09 08" src="https://cloud.githubusercontent.com/assets/1715809/16908982/b1aed28c-4ccf-11e6-85b7-2d02793a49c7.png">

However, I want this arrangement for *all* tracks in the main, lower, section/window

If stray tracks, with no album or year, were grouped together at the top or bottom that would be logical/useful

Often I collect large amounts of music (e.g. 10GB+) and want a way of listening to it with some semblance of order before I decide to keep the music; when I decide to run it through https://musicbrainz.org/ before storing it on my server

Anyone know if this filtering/sorting use case is possible - currently finding a lot of players worth their mustard don't support it (e.g. http://swinsian.com/ )

NB iTunes does allow this ( https://twitter.com/ldexterldesign/status/752839484396437504 ), but I've decided not to use iTunes any longer, for a number of reasons, but primarily because it lacks open format support

Hope to hear back

Kind thanks

**Comment by lazka** [comment]
Not sure what you want exactly, but two things:

* Holding Command when clicking a column headers to sort allows you to sort by multiple columns
* You can add a new column with a pattern `<~album~artist~~year>`

There is atm no grouping support in the main song list.

**Comment by declension** [comment]
> If stray tracks, with no album or year, were grouped together at the top or bottom that would be logical/useful

This _is_ the case. Songs with missing tags are grouped as _Unknown_ (in English), and are in bold at the bottom, as below for `year`:

![screenshot from 2016-07-18 09-43-47](https://cloud.githubusercontent.com/assets/3322808/16909699/2835a2fe-4ccc-11e6-84dc-7b4f6757a7dc.png)

**Comment by ldexterldesign** [comment]
Hey @lazka,

Cheers for reply

>There is atm no grouping support in the main song list.

This is all I needed to know

Can I make a feature request for this because at the moment it's impossible to listen to all tracks ordered by artist > album > year, which, to me, seems an incredibly obviously use case, no?

Hope to hear back

Kind thanks

**Comment by ldexterldesign** [comment]
Hey @declension,

Thanks for reply

You are not wrong, but you've overlooked the context of my question:

>However, I want this arrangement for *all tracks* in the main, lower, section/window

Kind regards

**Comment by ldexterldesign** [comment]
FYI My use case is solvable with http://swinsian.com/ http://quick.as/6xnXHyReX

Not being able to group artists, then order their releases (i.e. albums) by date is, unfortunately, a deal breaker for me in this instance 🙁

I'm aware I may be a huge edge case , but if you agree too then reply +1 or vote this issue up

I'll leave this issue open, since it would be great to see it road mapped; else feel free to close

Kind regards

**Comment by CreamyCookie** [comment]
So you want to select and artist and then see something like this:

* Root (1996)
* Stem (2001)
* Leaf (2012)

But why not use the album browser (search for artist and sort by year) then?

**Comment by ldexterldesign** [comment]
Hi @CreamyCookie/all,

> So you want to select an artist

> Why not use the album list (search for artist and sort by year) or album collection browser then?

No, I want to select ``all`` so my whole library plays in the order I want so I don't have to keep filtering. It's not about filtering it's about sorting.

> [...] at the moment it's impossible to listen to all tracks ordered by artist > album > year

... and, as @lazka mentions above, this is because:

> There is atm no grouping support in the main song list

> Holding Command when clicking a column headers to sort allows you to sort by multiple columns

Not working for me or else this would solve my use case. Is there documentation on this or another command in macOS?

Lastly today, hoping grouping support has been added, I created a custom header hoping this would work but the year sorting is still not accurate:

```
~artist~year~album
```

<img width="1440" alt="Screenshot 2019-07-26 at 19 35 55" src="https://user-images.githubusercontent.com/1715809/61970286-c2f4cd80-afdc-11e9-88e6-4345cca84f57.png">

<img width="1440" alt="Screenshot 2019-07-26 at 19 34 19" src="https://user-images.githubusercontent.com/1715809/61970293-c5efbe00-afdc-11e9-8417-e86b9df64355.png">

Hope to hear back

Cheers

**Comment by CreamyCookie** [comment]
> No, I want to select all so my whole library plays in the order I want so I don't have to keep filtering. It's not about filtering it's about sorting.

Still not sure if I get it. Is this what you want (artists albums grouped and sorted by year):


Track 1 - Root (1996) by Artist X
Track 2 - Root (1996) by Artist X
Track 1 - Stem (2001) by Artist X
Track 2 - Stem (2001) by Artist X
Track 3 - Stem (2001) by Artist X
Track 1 - Telephone (1999) by Artist YYY
Track 2 - Telephone (1999) by Artist YYY

> Lastly today, hoping grouping support has been added, I created a custom header hoping this would work but the year sorting is still not accurate:

Weird, I have no idea why the year is shortened to 2 digits, because that also seems to be the reason for 1996 being sorted after 2011.

> Not working for me or else this would solve my use case. Is there documentation on this or another command in macOS?

There is:
https://quodlibet.readthedocs.io/en/latest/guide/shortcuts.html?highlight=column

⌘ key + Left Click 

So Command + Left Click seems to be correct. If it's still not working, could you add it to #1930 (and maybe mention if the shortcuts listed there don't work for you either)?

**Comment by ldexterldesign** [comment]
Hi @CreamyCookie,

Your example looks punctilious

> Weird, I have no idea why the year is shortened to 2 digits, because that also seems to be the reason for 1996 being sorted after 2011. Other than that it works correctly, right?

Ahh, if that's what's going on then this is a bug. Once fixed should solve my issue.

> If it's still not working, could you add it to #1930

Done

Cheers

**Comment by CreamyCookie** [comment]
Thanks! For now you can try `~artist~date~album` as a custom column:

![~artist~date~album](https://user-images.githubusercontent.com/3063858/62082972-2c334580-b256-11e9-8b3c-c59fbd762563.png)

Seems to work in this limited test (but maybe there are edge cases).

**Comment by CreamyCookie** [comment]
Thanks! For now you can try `~artist~date~album` as a custom column:

![~artist~date~album](https://user-images.githubusercontent.com/3063858/62082972-2c334580-b256-11e9-8b3c-c59fbd762563.png)

Seems to work in this limited test (but maybe there are also edge cases). Does this work for you?

**Comment by CreamyCookie** [comment]
@ldexterldesign Okay, I see the issue is actually our fault. Columns need to follow a [specific syntax](https://quodlibet.readthedocs.io/en/latest/guide/tags/tied_tags.html):

So there needs to be an additional tilde before year: `~artist~~year~album`

**Comment by ldexterldesign** [comment]
@CreamyCookie 

No, this isn't a syntax issue

Your screen shot hierarchy syntax (e.g. foo - bar - baz) has allowed me to discover users can create "custom columns" and "custom headers":

<img width="1440" alt="Screenshot 2019-07-30 at 00 02 57" src="https://user-images.githubusercontent.com/1715809/62086034-67854280-b25d-11e9-828c-212b547107bc.png">

This is a UX issue

The paned browser layout features should be kept in the preferences dropdown but all the custom header features should use the same interaction (i.e. right clicking on column headers):

<img width="1440" alt="Screenshot 2019-07-30 at 00 23 19" src="https://user-images.githubusercontent.com/1715809/62086940-3fe3a980-b260-11e9-818a-b6d1e8de1912.png">

If you agree then happy to create a new issue for this

--

So now I've finally discovered custom headers, I've set some up:

<img width="1440" alt="Screenshot 2019-07-30 at 00 34 45" src="https://user-images.githubusercontent.com/1715809/62087389-d8c6f480-b261-11e9-9c23-8b165a9ce472.png">

~artist~album~year - year is missing as per https://github.com/quodlibet/quodlibet/issues/3234
~artist~year~album - "
~artist~album~date -  sorting conflates other artists
~artist~date~album - "

With the last two syntax here the logic seems to be prioritising date above artist 🥴 so perhaps a case for another bug issue concerning ``~date`` - what do you think?

Cheers

**Comment by CreamyCookie** [comment]
> No, this isn't a syntax issue but thanks for docs link

But it is. The reasons the custom columns didn't work was because we didn't separate the individual tags with `~`. The whole thing also needs to start with a `~`.

So to combine `artist`, `~year` and `album` we do this:

`~` + `artist` + `~` + `~year` + `~` + `album` (the + here means we combine the strings) 

which is `~artist~~year~album`

This is described here: https://quodlibet.readthedocs.io/en/latest/guide/tags/tied_tags.html

See also: https://quodlibet.readthedocs.io/en/latest/guide/tags/internal_tags.html#internaltags



> ~artist~album~year - year is missing as per #3234
> ~artist~year~album - "

See above.

**Comment by ldexterldesign** [comment]
@CreamyCookie

Yes, ``~~year`` works - I should have read the docs

I'm still struggling to get this working - any chance we could hop on a video call - I'm still convinced there's a bug here somewhere?

Yours hopefully

**Comment by CreamyCookie** [comment]
>  I'm convinced there's a (macOS) bug here somewhere (I presume you're using non-macOS)?

That's a possibility! (I'm on Ubuntu.)

> I'm still struggling to get this working - any chance we could hop on a video [c]all -

I'm not using Matrix yet (I like its ideas) and I'm not a fan of doing a (video) call. Could you upload a video of the problem + description, or explain what you're struggling with?

**Comment by ldexterldesign** [comment]
@CreamyCookie just remembered I have a partition ready for Ubuntu so I'll give that a whirl and if report back. Cheers.

**Comment by ldexterldesign** [comment]
FYI same issue on Ubuntu so I don't consider this issue resolved

**Comment by CreamyCookie** [comment]
@ldexterldesign I'm not sure what issue you're referring to. Have you created a custom column `~artist~~year~album`. 

I could reopen, but I feel like this issue is now so long, messy and confusing, that I think it would be better (if you want exposure) to create a new one that explains your problem more clearly.

I also don't see how the title "Research ... by artist album year" describes a bug or feature request.

**Comment by ldexterldesign** [comment]
Yes, please reopen and my next post will be a screen cast with commentary

Cheers

**Comment by CreamyCookie** [comment]
Please create a new bug report with a clearer title and description.

You can post your screen cast there too.

Cheers
