### ISSUE TITLE
ImportError: No module named quodlibet.cli

### ISSUE THREAD

**Issue by jacare-do-alto** [quodlibet/quodlibet#1995]
I'm receiving  this message when trying to launch quodlibet:

> Traceback (most recent call last):
>   File "/usr/bin/quodlibet", line 15, in <module>
>     from quodlibet.cli import process_arguments, exit_
> ImportError: No module named quodlibet.cli

My system is a Linux Mint 17.3, and the ppa repository is 

> ppa:lazka/dumpingplace

Python is:

> Python 2.7.11 (default, Jun 23 2016, 19:13:09) 
> [GCC 4.8.4] on linux2
> Type "help", "copyright", "credits" or "license" for more information.

Any idea what's wrong? Thanks.

**Comment by lazka** [comment]
Did it work at one point?

**Comment by jacare-do-alto** [comment]
Hi lazca! No, it doesn't work at all, stops and doesn't launch nothing. I received the message above when running from the terminal.

**Comment by lazka** [comment]
Just tried with mint 17.3 and everything worked fine.

Maybe try reinstalling quodlibet and exfalso

**Comment by jacare-do-alto** [comment]
Yes, it was working with Mint 17.3 until something changed in my system. I've already reinstalled QL and exfalso and nothing changes. Maybe is the time for update the OS to Mint 18...

**Comment by lazka** [comment]
No idea, sorry.
