### ISSUE TITLE
Quodlibet crashes when trying to fetch metadata via MusicBrainz plugin

### ISSUE THREAD

**Issue by andriyamelin** [quodlibet/quodlibet#1998]
Ubuntu 14.04

To reproduce just enable MusicBrainz plugin, select any album and try to get metadata for it

[Dump_20160728_234113.txt](https://github.com/quodlibet/quodlibet/files/389430/Dump_20160728_234113.txt)

**Comment by lazka** [comment]
See https://github.com/quodlibet/quodlibet/issues/1971#issuecomment-233173138

**Comment by lazka** [comment]
I've added a newer version of musicbrainzngs to the PPA, so things should work again.
