### ISSUE TITLE
Gnome Shell: No tray icon

### ISSUE THREAD

**Issue by sebadorn** [quodlibet/quodlibet#1999]
I upgraded today from Ubuntu 14.04.4 to 16.04.1. After that Quod Libet's tray icon wasn't visible, but still interactable. Only the tray icon is affected, all other icons (application menu etc.) show just fine.

Some general info:
Quod Libet 3.6.2, Gnome Shell 3.18.5 with [TopIcons](https://extensions.gnome.org/extension/495/topicons/) extensions, Numix icon theme (but changing the icon theme didn't solve the problem).

---

After some digging, I found that `quodlibet.app.symbolic_icon_name()` in quodlibet.appindicator returned "None-symbolic", because `quodlibet.app.id` is not set (same with `quodlibet.app.name`). So I changed the ID to 'quodlibet'.

Still didn't show the icon. So I probably have to add a "quodlibet-symbolic" icon to the theme, but I just changed `symbolic_icon_name()` to omit the "-symbolic" part and now it works:

![working_ql_tray_icon](https://cloud.githubusercontent.com/assets/1146318/17262512/10a5e964-55dc-11e6-843f-fe1f082207e9.jpg)

---

Btw: I love how fast indexing and searching are in Quod Libet and the tagging + renaming options of Ex Falso. Great job!

**Comment by lazka** [comment]
hm, could it be that only the "exfalso" package is up to date, but not the "quodlibet" package?

**Comment by sebadorn** [comment]
If it is relevant: I use the PPA http://ppa.launchpad.net/lazka/ppa/ubuntu to keep Quod Libet up-to-date.

**Comment by lazka** [comment]
ok. another weird thing is that appindicator should only be used when running under unity, not gnome.

I'll try installing gnome under 16.04

**Comment by lazka** [comment]
Are you using lightdm or gdm3?

**Comment by sebadorn** [comment]
lightdm.

`quodlibet.util.is_unity()` returns True for me. Maybe because I also have Unity installed, though I'm using Gnome Shell?

**Comment by lazka** [comment]
It detects if unity is running.

Do you use default ubuntu or gnome ubuntu etc..?

**Comment by sebadorn** [comment]
The "normal" Ubuntu. I think since 12.04 I only used upgrades, never a fresh install. At some point I installed gnome-shell.

**Comment by lazka** [comment]
I can't reproduce with an updated 16.04 + gnome + lightdm. No idea how else we can detect if unity is running. Maybe check for "com.canonical.Unity.Launcher" as well?

**Comment by sebadorn** [comment]
Oh, my mistake, sorry. `app.id` is set. It wasn't because I did my testing in a Python console and just did an `import quodlibet`. When properly starting `/usr/bin/quodlibet` it is set.

Which means my only remaining workaround/fix is now removing "-symbolic" from `symbolic_icon_name()`.

Checking for `com.canonical.Unity` returns True, but `com.canonical.Unity.Launcher` returns False. Here is my (shortened) result for `bus.list_names()`:

```
com.canonical.Unity
com.canonical.Unity.WindowStack
com.canonical.URLDispatcher
com.ubuntu.Upstart
org.cairodock.CairoDock
org.freedesktop.DBus
org.freedesktop.FileManager1
org.freedesktop.IBus
org.freedesktop.Notifications
org.freedesktop.ScreenSaver
org.freedesktop.secrets
org.freedesktop.Telepathy.*
org.gnome.Caribou.Keyboard
org.gnome.evolution.dataserver.*
org.gnome.GConf
org.gnome.Identity
org.gnome.keyring
org.gnome.keyring.SystemPrompter
org.gnome.Magnifier
org.gnome.Mutter.DisplayConfig
org.gnome.Mutter.IdleMonitor
org.gnome.Nautilus
org.gnome.OnlineAccounts
org.gnome.Panel
org.gnome.ScreenSaver
org.gnome.SessionManager
org.gnome.SettingsDaemon
org.gnome.Shell
org.gnome.Shell.CalendarServer
org.gnome.Shell.Screencast
org.gnome.Shell.Screenshot
org.gnome.Software
```

**Comment by lazka** [comment]
Thanks for debugging.

**Comment by lazka** [comment]
Regarding the icon: We don't want to use the indicator anyway under GNOME, so it doesn't matter if it is broken there. Also gnome has no official app indicator implementation, there is just this unmaintained extension: https://extensions.gnome.org/extension/615/appindicator-support/

Will be available in the next release or in the unstable PPA right now.
