### ISSUE TITLE
Add album art through player

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#2]
Original [issue 2](https://code.google.com/p/quodlibet/issues/detail?id=2) created by joe.wreschnig on 2008-09-07T04:48:42.000Z:

Clicking the empty CD case in the player should pop up a file browser
asking for an image; selecting an image should scale it appropriately
(256x256 max?) and save it in the right folder for the file.

**Comment by declension** [comment]
This has been merged for ages => closing.
