### ISSUE TITLE
Musicbrainz issue - Ex Falso crashes at Musicbrainz lookup

### ISSUE THREAD

**Issue by JoseBarakat** [quodlibet/quodlibet#2000]
I'm trying to change my music tags from Musicbrainz plugin but an error pops up that says:

> An exception has occured in Quod Libet. A dump file has been saved to ~/.quodlibet/dumps/Dump_20160731_015032.txt that will help us debug the crash. Please file a new issue at https://github.com/quodlibet/quodlibet/issues/newand attach this file or include its contents. This file may contain some identifying information about you or your system, such as a list of recent files played. If this is unacceptable, send ~/.quodlibet/dumps/MiniDump_20160731_015032.txt instead with a description of what you were doing.
> 
> Puede ser que QuodLibet esté inestable. Se recomienda cerrarlo y abrirlo de nuevo. Se guardará la colección.
> 

Thanks!

[Dump_20160731_015032.txt](https://github.com/quodlibet/quodlibet/files/392298/Dump_20160731_015032.txt)

**Comment by lazka** [comment]
Thanks

**Comment by lazka** [comment]
Can you provide the album and artist name of the album you where trying to tag?

**Comment by JoseBarakat** [comment]
Yes. 

![captura de pantalla de 2016-07-31 02-16-44](https://cloud.githubusercontent.com/assets/15618933/17275198/eec5f82c-56c4-11e6-9a4e-bcbc4dac2ba3.png)

**Comment by JoseBarakat** [comment]
Thanks!

**Comment by JoseBarakat** [comment]
@lazka , Issue persist.
Reproduce:
File: "13 Años - Wilfrido Vargas.mp3"
- Play song
- Open "MusicBrainz Lookup" plugin while playing.
- Query: artist:"Wilfrido Vargas"
- Select best album match. 
- Select song from album results. (In my case, track 9)
- Click on Save button (while song still plays)
- Quod Libet pops up new window with an error message "An exception has occured in Quod Libet. A dump file has been saved to..."

Dump file:
[Dump_20160806_095903.txt](https://github.com/quodlibet/quodlibet/files/405056/Dump_20160806_095903.txt)
