### ISSUE TITLE
Narrow default widths for columns

### ISSUE THREAD

**Issue by pschwede** [quodlibet/quodlibet#2001]
![Screenshot of a search browser](http://imgur.com/kYMYVbsl.png)

Each time I start quodlibet, I get these unpractically narrow columns widths.

Since QL does not have this issue when I rename my `~/.quodlibet`, I checked my config file. In my `.quodlibet/config`, I can find the lines

```
column_expands = ~playlists,0,~title~version,0,artist,0,genre,0,~codec,0,~#laststarted,0,~#added,1

column_widths = ~playlists,40,~title~version,40,artist,40,genre,40,~codec,40,~#laststarted,40,~#added,40
```

I don't know / cannot remember where they're coming from.

**Comment by spxxxk** [comment]
Yep, columns with "Expand column" unchecked gets resized to minimal width, no longer remember previous width.

QL: 3.6.99+8332~0ca033c-0~ppa0~xenial

**Comment by lazka** [comment]
Oops, right.
