### ISSUE TITLE
UI button for plugins list?

### ISSUE THREAD

**Issue by urielz** [quodlibet/quodlibet#2002]
Perhaps adding a UI button to access the plugins list might help new users? Not sure it's really necessary but there's plenty of space at the bottom bar for this...

**Comment by lazka** [comment]
I was thinking of moving the "View>queue" to a button there and instead add a new main plugin menu

**Comment by urielz** [comment]
I liked that idea. It would definitely give the plugins more exposure. Besides configure plugins, what else would the menu list? Perhaps listing the active plugins?

**Comment by lazka** [comment]
Yeah, let the active plugins expose menu items there.
