### ISSUE TITLE
Don't change current song list, when album doesn't apply to the filter anymore

### ISSUE THREAD

**Issue by CreamyCookie** [quodlibet/quodlibet#2003]
Very often I use the filter `&(#(playcount:min = 0), #(added < 1 month ago))` so I only see albums that were recently added but from which I haven't played every song. Whenever I've finished an album I want to "Force Write" all songs so ratings and playcounts are stored in the tags. The problem is that whenever I've finished the last song of an album, the filter doesn't apply any more and the song list changes to another album before I can apply the plugin.

Maybe I'm wrong about this, but I don't see any reason why QL should change the current song list without any action by the user.

**Comment by declension** [comment]
Is that just the Random Album plugin kicking in?

**Comment by CreamyCookie** [comment]
@declension Hmm.. no. I don't use that one.

**Comment by declension** [comment]
ok. Hmm. So what does the song list change to? Does the filter update itself?

**Comment by CreamyCookie** [comment]
@declension Sorry if I was unspecific. Yes, the filter hides albums from the album list (browser), whenever they don't apply anymore, which of course is correct. The song list changes to the album below (and no song is played).
