### ISSUE TITLE
Issue #2000 persist (Musicbrainz issue - Ex Falso crashes at Musicbrainz lookup)

### ISSUE THREAD

**Issue by JoseBarakat** [quodlibet/quodlibet#2005]
**SYSTEM INFORMATION:**
Quod Libet 3.7 (development, 65b8e15)
Mutagen 1.35.-1
Python 2.7.12 (default, Jul  1 2016, 15:12:24) 
[GCC 5.4.0 20160609] linux2
Platform Linux-4.3.0-040300-generic-x86_64-with-Ubuntu-16.04-xenial

**Issue**
I have commented on issue #2000 that, in some circumstances, the Musicbrainz lookup plugin still crashes. This time when I save a new metatag for a song while this song is still playing.

**May be affected**
From *quodlibet/quodlibet/quodlibet/ext/songsmenu/brainz/*
[widgets.py](https://github.com/quodlibet/quodlibet/blob/master/quodlibet/quodlibet/ext/songsmenu/brainz/widgets.py) 
[mb.py](https://github.com/quodlibet/quodlibet/blob/master/quodlibet/quodlibet/ext/songsmenu/brainz/mb.py)
*IndexError: list index out of range*

**How to Reproduce:**
File: "13 Años - Wilfrido Vargas.mp3"

1. Play song
2. Open "MusicBrainz Lookup" plugin while playing.
3. Change the default query and write a custom one: artist:"Wilfrido Vargas"
4. Select best album match.
5. Select song from album results. (In my case, track 9)
6. Click on Save button (while song still plays)
7. Quod Libet pops up new window with an error message "An exception has occured in Quod Libet. A dump file has been saved to..."

**Dump file**
[Dump_20160806_095903.txt](https://github.com/quodlibet/quodlibet/files/405599/Dump_20160806_095903.txt)

**Comment by lazka** [comment]
Thanks

**Comment by JoseBarakat** [comment]
Thanks to you @lazka . I just tested it. This issue is resolved for me, but unfortunately there's still another issue that keeps bugging me (hehe see what I did?). I'll report it as a new one.
Again, thanks. Very good audio player.
