### ISSUE TITLE
All styling, images and icons should scale with DPI

### ISSUE THREAD

**Issue by declension** [quodlibet/quodlibet#2008]
On HiDPI screens whilst most things are fixed, some seem not to be. A list (from memory, haven't got HiDPI here):
- [ ] Album covers in the Album List
- [ ] Paddings, margins and other GTK+ styling generally expressed in pixels AIUI; this gives the app a clunkier feel in HiDPI
- [ ] Some icons e.g. Soundcloud assets from that browser, don't scale automatically

**Comment by lazka** [comment]
Which platform/environment is this? This should all work currently (except on Windows)

**Comment by lazka** [comment]
Braindump:

* gtk+ under X11/wayland can currently only do integer scaling "GDK_SCALE=2" 
* GDK_SCALE also affects the font size, which you can readjust using "GDK_DPI_SCALE=0.5"
* afaik there is a plan to do float scaling with Wayland (not sure about MIR) but nothing is done there
* Adwaita (the default theme, not Ubuntu) has a bug for widget scaling based on the font size: https://bugzilla.gnome.org/show_bug.cgi?id=761435 but there hasn't been any progress recently.

**Comment by declension** [comment]
Thanks. 

For completeness, as per IRC this is Ubuntu 16.04 at 3200 x 1800 but with display scaling set to a non-integer amount (2.25? TBC), so this is probably another instance of the integer vs non-integer scaling making things look slightly off.

**Comment by lazka** [comment]
This gets you the dpi value:

``Gtk.Settings.get_default().props.gtk_xft_dpi / 1024``

**Comment by lazka** [comment]
I don't really want to look into making everything resize based on the font size as that's a lot of work and there is no support for this in gtk+.

I'd suggest that we go through the cases one by one with preferably a screenshot (as this also depends on the distro/theme) and work out what to do.

**Comment by lazka** [comment]
Some related news:

* We now have some css to scale buttons/entries with font size, because this never made it into gtk+ and it's unlikely that it will happen with 3.22: https://github.com/quodlibet/quodlibet/blob/9b4786b664be1c6a156f3c94fddcb1d3bac0983e/quodlibet/quodlibet/_init.py#L398
* GTK+ 3.22 on Windows gained HIDPI support: https://git.gnome.org/browse/gtk+/commit/?h=gtk-3-22&id=4add92a4314c152b852f2f4ffdb0d4a64d60e361

**Comment by Safari77** [comment]
> Which platform/environment is this? This should all work currently (except on Windows)

Album covers in the Album List: on gnome wayland (Fedora 32) the cover pictures are 48x48 pixels.

**Comment by Safari77** [comment]
I found Advanced Preferences: ```Album cover size```.
Problem solved.

**Comment by declension** [comment]
I think this can be closed now with upstream changes
