### ISSUE TITLE
Plugins Not Working

### ISSUE THREAD

**Issue by pyroserpent** [quodlibet/quodlibet#2010]
Hello I installed qoud libet and running it on ubuntu 14.04, it's a perfect music player for me except for one issue, the plugins are not working and there seem to be an error message that's coming up. Can any of you help me with this issue and let me know how to fix it? I have attached a screenshot of the problem

![qoud libet](https://cloud.githubusercontent.com/assets/21161537/17839757/f2b51598-6813-11e6-83a2-6dd83f06e113.png)

Also please forgive me if I broke any kind of rule by posting this randomly, I have no idea how to and where to ask for help and this is my first post ever on git hub as well.

**Comment by declension** [comment]
Welcome to Github :) and this is the right place yes.

From what's shownm you have two errors amongst the 80+ plugins there: a strange import error with Kakasi (for dealing with Japanese character conversion), and Gnome search provider, for better integration with the searching in your operating system (Ubuntu).

Was there a particular problem you were having?

**Comment by pyroserpent** [comment]
Yes I am having a problem as I am unable to export or save my playlist. Plugin -> Export playlist option can't be found anywhere. I have no idea how I can export my playlist.

**Comment by declension** [comment]
OK. Once that plugin is enabled, you need to right-click on the playlist in your Playlists Browser, then click "Export as playlist..."

This should probably be moved into the playlist browser core. I think there was an old old ticket about this somewhere.

**Comment by pyroserpent** [comment]
The problem is there are no button to enable that plugin or any plugin for that matter, there two buttons one reads "show error" another "reload". Right clicking my playlist doesn't give me the export playlist option either.

**Comment by pyroserpent** [comment]
Sorry it says "refresh" button not reload

**Comment by declension** [comment]
Hmm, so looks like a theme issue. You should select (check / tick) any plugins you want to enable from that window, but your screenshot indicates the checkboxes are invisible(ish).

See the [Plugin Overview in the User Guide](https://quodlibet.readthedocs.io/en/latest/guide/overview.html#plugins) for how this is meant to look (with a different theme)

Are you using a custom Ubuntu / Gnome theme?

**Comment by pyroserpent** [comment]
Ahhh I see, it might possibly be a theme issue, as I am running a custom dark theme. I will check this in the morning with default Ubuntu theme and if I can check/tick plugin options I will let you know! Thank you so much for such fast response and cooperation!!

**Comment by pyroserpent** [comment]
@declension thank you so much for helping me out, problem fixed I can get all the plugins to work now and successfully exported my playlist. You have been a great help, thanks a lot!

**Comment by declension** [comment]
No problem

**Comment by lazka** [comment]
@pyroserpent There also is a "Theme switcher" plugin where you could for example select "Adwaita" + prefer dark to get the default/supported theme.
