### ISSUE TITLE
Playlist column or sidebar in panelbrowser view

### ISSUE THREAD

**Issue by brenthuisman** [quodlibet/quodlibet#2011]
I'm looking to have a combined playlist/browser view but it appears that is not (yet) possible.

I tried to add a 'playlist' (and 'PLAYLIST') panel to the panelbrowser view, in order to have my playlists show up, but that doesn't work (#1619 mentioned this variable being available).

If that is intended behavior, I hereby request a playlist sidebar or column in the panelbrowser view.

**Comment by declension** [comment]
No, that `PLAYLIST` variable only applies to the Custom Commands plugin.

Best current workaround: launch a secondary browser window for the playlists with Paned Browser as the primary (or vice versa)

**Comment by declension** [comment]
See related #1991

**Comment by brenthuisman** [comment]
Yes, dockability would solve the issue as well: the goal is to have a single window, where selecting a playlist is merely a selection criterion for the panelbrowser.

**Comment by declension** [comment]
@brenthuisman on re-reading your request, you should actually be able to achieve what you're after by adding a custom pane with `~playlists` as the tag.

**Comment by brenthuisman** [comment]
Nice, that indeed does what I want! Great! Unfortunately it is not possible to drag and drop songs to add (or remove) them from playlists this way. Is that then a feature that could be added?

**Comment by declension** [comment]
Great, glad that solved the problem.

Re: drag-and-drop to playlists: not without rewriting the paned browser completely. The recommended way to do this is either right-click the songs and use the playlists context menu, or to drag-and-drop them to a secondary playlists browser.

Closing ticket.

**Comment by brenthuisman** [comment]
Yes, I just discovered the right click menu. However, it does not cause the song to actually pop up in the playlist view until I restart quodlibet. So I suppose the pane is populated once, and not dynamically updated. Is that true for all panes?
