### ISSUE TITLE
MPD plugin uses incorrect local address and it's not editable

### ISSUE THREAD

**Issue by nkuttler** [quodlibet/quodlibet#2014]
The MPD server plugin tries to autodetect the "local" IP address but doesn't get it right. I have three network devices, LAN, WLAN and VPN and the plugin listens on the latter every time. I don't mind the guesswork, but I should be able to edit the IP address, I know which one my devices can connect to.

**Comment by lazka** [comment]
This is the code currently: https://github.com/quodlibet/quodlibet/blob/master/quodlibet/quodlibet/ext/events/mpdserver/__init__.py#L34

We try to connect to google and get the local IP. Either we can improve it somehow or we can indicate that it's just a guess.

Either way, the IP is not used by the server, it's just to help you fill in the configuration of the client.

**Comment by nkuttler** [comment]
Oh, ok. I guess the plugin config window could include a small text like "Your mpd clients can connect to this mpd with the following settings". Seeing that IP address had me confused last night, it seems like quodlibet simply listens on all interfaces?

**Comment by lazka** [comment]
> Oh, ok. Seeing that IP address had me confused last night, it seems like quodlibet simply listens on all interfaces?

Yeah

Re your original post: I agree that the text entry is a bit confusing and that we should convert it to a text description including the guessed IP.

**Comment by lazka** [comment]
Changed it to a label now.
