### ISSUE TITLE
Browse panes not updated

### ISSUE THREAD

**Issue by brenthuisman** [quodlibet/quodlibet#2017]
It appears that in the specific case of adding playlists to the panelbrowser, with `~playlists`, see #2011, and then adding or removing songs to playlists (which I do with the right click menu), the panel view isn't update until I restart quodlibet. So I suppose the pane is populated once, and not dynamically updated. Is that true for all panes?

**Comment by lazka** [comment]
They should get updated. I guess we miss a "changed" signal when adding/removing songs to/from a playlist.

**Comment by declension** [comment]
+1
IIRC at the time it seemed like an edge case, but now that tag is in wider use we should definitely support its changes.
