### ISSUE TITLE
Feature: Support multiple versions of albums/songs (FLAC/mp3/etc)

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#202]
Original [issue 202](https://code.google.com/p/quodlibet/issues/detail?id=202) created by tyler.cordrey on 2009-05-16T21:07:31.000Z:

I'd love for my media library to be aware of multiple versions of the same
track, and play the highest quality by default. Maybe I currently only have
an mp3 of a particular song, but later get a FLAC copy. Or maybe I'd like
to keep mp3's around for my portable device, but prefer flacs when
listening on the computer. Viewing Info for a track would show all versions
the program knows about.

Ideally Quod Libet would recognize songs with some tolerance for
differences in file/folder or tag names (ie AlbumName [FLAC] vs AlbumName
[MP3]). Personally I would structure my library with root folders for each
version type, but this would have to be up to the user. I've envisioned
accomplishing this through scripts to build symlinks, updating the links to
point to the apropriate place with the highest quality. It seems that this
can be accomplished more gracefully using an existing tool like Quod Libet.

**Comment by declension** [comment]
With 7 years since last update I think it's safe to now close this
