### ISSUE TITLE
Menus broken with X11 forwarding

### ISSUE THREAD

**Issue by zsau** [quodlibet/quodlibet#2024]
Starting recently, running QL via X11 forwarding causes the main menus to not show up when clicked. Instead I get console warnings like this:

```
(quodlibet:5896): Gtk-WARNING **: Negative content width -11 (allocation 1, extents 6x6) while allocating gadget (node menuitem, owner GtkImageMenuItem)

(quodlibet:5896): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to underallocate GtkImageMenuItem's child GtkAccelLabel 0x9de2d70. Allocation is 1x13, but minimum required size is 38x15.
```

**Comment by lazka** [comment]
gtk+ 3.21?

**Comment by lazka** [comment]
Do you have "gtk3-demo-application" (gtk-3-examples package in debian) and does the same error happen there?

**Comment by zsau** [comment]
On the (Debian) host, yes, it's libgtk 3.21.5-3. And you're right, the gkt3 demo application does the same thing, so this must be a Gtk bug. Is there a bug report for it already?

**Comment by lazka** [comment]
Doesn't look like it. Should I forward this upstream?

**Comment by zsau** [comment]
Yes, please do. Thanks!

**Comment by lazka** [comment]
Hm, at least doing forwarding over localhost I can't reproduce the issue (also using debian sid).

Are you using GNOME?

**Comment by zsau** [comment]
I'm not using Gnome on the host, just WindowMaker. The client is a Mac running XQuartz 2.7.9.

**Comment by lazka** [comment]
Uh, that will be hard to reproduce :/

I'm wondering if there is much value forwarding this issue if I can't reproduce, bisect and test...

**Comment by zsau** [comment]
I just tried forwarding over localhost, and the menus do show up (though I still get a bunch of similar console warnings).

How would you suggest I go about tracking this down further?

**Comment by lazka** [comment]
> I just tried forwarding over localhost, and the menus do show up (though I still get a bunch of similar console warnings).

Afaik most of those console warnings visible now will be disabled for the stable release (3.22), I see them too...

> How would you suggest I go about tracking this down further?

No idea atm

**Comment by zsau** [comment]
Do you think it's more likely a bug in Gtk or XQuartz? I can file with whichever one seems more appropriate, and hopefully they will know how to track it down further.

**Comment by lazka** [comment]
No clue. Filed upstream: https://bugzilla.gnome.org/show_bug.cgi?id=770838

**Comment by zsau** [comment]
Problem has disappeared, presumably because of the latest gtk+ update in Debian (3.21.6). Thanks anyway for looking into this.

**Comment by zsau** [comment]
Hm, seems I spoke too soon. It was working earlier this morning, now broken again (not sure why). But we can keep this issue closed, and I'll keep an eye on the upstream report.

**Comment by lazka** [comment]
ok
