### ISSUE TITLE
Song Notifications plugin: option to disable "Next" button

### ISSUE THREAD

**Issue by Jimi-James** [quodlibet/quodlibet#2026]
I personally would never use this button (though I can see why some would), but sometimes I accidentally click it when I'm trying to click on the notification to get rid of it, and that's especially annoying (to accidentally skip a song) when I'm using the queue. I want to be able to hide that button from the notifications.

**Comment by lazka** [comment]
Which desktop environment?

**Comment by Jimi-James** [comment]
XFCE
