### ISSUE TITLE
Plugin to manually measure BPM

### ISSUE THREAD

**Issue by pschwede** [quodlibet/quodlibet#2027]
I'd like something like this but (maybe as a plugin) with a user friendly GUI button for mouse/keyboard:

https://gist.github.com/pschwede/98c4580b563d8b8c6948947aee72e051

**Comment by lazka** [comment]
Have a look at #2264

**Comment by ptitjes** [comment]
@pschwede My "Tap BPM" plugin is now in QL ? (see merged PR #2264)
Please, do tell if that answers to your request and if we can close this issue ?

**Comment by pschwede** [comment]
That is beautifully done. I like it.
