### ISSUE TITLE
100% CPU usage when length column shown

### ISSUE THREAD

**Issue by qwence** [quodlibet/quodlibet#2030]
I've bisected the following issue to commit 295cc6d900a13b7dd6f9c (and checked that the bug is not present when this commit is reverted).

When using the following minimal config

```
[settings]
columns = artist,composer,title,~#track,album,~#length
	
[memory]
column_expands = artist,0,composer,0,title,0,album,0
```

I get 100% CPU usage if (1) I'm using the "search library" view, and (2) the "length" column is fully visible (i.e. not squished horizontally by weird column widths). I can delete the last line in the config and this doesn't happen, but after playing with the column widths a little bit a line like this will be automatically inserted in my config, and on next startup, the issue happens again.

**Comment by lazka** [comment]
Thanks. Which distro/version?

**Comment by lazka** [comment]
Never mind. I can reproduce using your config.

**Comment by lazka** [comment]
The workaround is to right click > "Expand column" on at least one other column in the list.
