### ISSUE TITLE
No longer able to edit metadata on Linux.

### ISSUE THREAD

**Issue by thisfred** [quodlibet/quodlibet#2032]
I think there may be a bug in the new platform independent file library. (Which is otherwise very exciting! ;)

When I rightclick any song, and choose 'Edit Tags' I get an error pop up. Attaching dump file below.

**Comment by thisfred** [comment]
[Dump_20160912_103706.txt](https://github.com/quodlibet/quodlibet/files/467964/Dump_20160912_103706.txt)

**Comment by lazka** [comment]
Thanks
