### ISSUE TITLE
Time to think about a database. Really.

### ISSUE THREAD

**Issue by Moonbase59** [quodlibet/quodlibet#2037]
I love QL for what it can do (and because it uses mutagen), but even on a Ubuntu Studio 14.04 2x1TB SSD (!) system with 4 cores and 32GB of RAM it now takes up to 3 HOURS (!!!) just for updating my music library upon start. A complete rescan takes DAYS. Which, unfortunately, makes it way too slow for any use.

A recent example, adding about 800 tracks to my collection:
a. Banshee took around 10 minutes
b. Guayadeque took about 1 minute
c. Quod Libet used almost 3 hours

My collection has about 105000 tracks. High time for a database, I think. I’d hate to lose QL … :-(

**Comment by lazka** [comment]
Here it takes 1:49 to load 8100 songs from a HDD.

* Are you using the version from the PPA?
* Which browser is active when you add songs?
* You can disable the startup scan in the preferences.

**Comment by kaffeeundsalz** [comment]
Can't reproduce either. Granted, hitting "Rebuild Library" with 135.000 songs will definitely take quite a while. But why would you wanna do that on a regular basis? I do use "scan library on start" and QL is ready after a few minutes even with a library that big. The only problem with this is that QL is almost unresponsive during the library update. I'd be great to have the process run in the background so I could use QL in the meantime instead of a few minutes after launch. But that's a different issue of course.

**Comment by Moonbase59** [comment]
Yes, I’m using the PPA version (shows as 3.7.0).
I use the "Browser" browser (at least that’s what it’s called in the German version; Ctrl+3).

**Comment by lazka** [comment]
Please execute the following, do something like adding those 800 songs and then quit QL:
```
python2 -m cProfile -o prof.out /usr/bin/quodlibet
```

This should produce a file called "prof.out" in your working directory. You can send it to me (reiter.christoph@gmail.com) or provide it some other way.

Is it any different with another browser (album list for example)?

**Comment by Negirno** [comment]
While I'm not experiencing as massive slowdowns as Moonbase59, searching and scanning the database is still slower than Foobar2000. If I have search after typing enabled in QL, the UI gets bogged down for a second or two, while I do a search in my 200GB collection. In the former, you get immediate results for every letter you type, without freezing, even if you run it in Wine.

Startup scan also bogs down the program for me: if enabled, the user can't do anything in the first couple of seconds.

**Comment by nodiscc** [comment]
The slowdown usually occurs for me when you the first (or is it second?) letter in the search bar - I think the search is only triggered after entering a certain number of characters. Returning all matches for `th` looks like a tedious operation (~20 000 tracks). Maybe the number of required chars to run the search can be increased?

**Comment by lazka** [comment]
> While I'm not experiencing as massive slowdowns as Moonbase59, searching and scanning the database is still slower than Foobar2000. If I have search after typing enabled in QL, the UI gets bogged down for a second or two, while I do a search in my 200GB collection. In the former, you get immediate results for every letter you type, without freezing, even if you run it in Wine.

This is mostly due to Python being slower and the Gtk+ list widget not scaling well. Nothing we can fix without major changes.

> Startup scan also bogs down the program for me: if enabled, the user can't do anything in the first couple of seconds.

Yeah, we should move more IO into background threads... someday
