### ISSUE TITLE
100% CPU usage, when quodlibet is idle

### ISSUE THREAD

**Issue by goxaxa** [quodlibet/quodlibet#2039]
* What did you try to do?
run quodlibet

* What did you expect to happen?
quodlibet runs, displays tracks (in Browse / File System view).
quodlibet does nothing, it just waits for a track to be selected to be played without consuming an excessive amount of CPU resources.

* What did happen instead?
'top' shows 99% and 100% usage by quodlibet

* Which version of Quod Libet?
3.7.0

* Which operating system including version (Ubuntu 14.04, Win7, Debian sid, ...)?
Linux, Fedora 24

If I change the view to a folder with no audio tracks, then CPU usage drops to < 10%.
If I then change the view back to a folder with audio tracks, then CPU usage shoots up to 100% again.

**Comment by lazka** [comment]
Thanks. Looks like #2030. Can you try the workaround posted there?

**Comment by lazka** [comment]
> Right click > "Expand column" - seems to work around the problem. 

Thanks for testing.

> In version 3.7.1 the problem will be fixed completely?

Yes. 3.7.1 will be released in one week.
