### ISSUE TITLE
Display a long size timescolling-bar on the window

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#204]
Original [issue 204](https://code.google.com/p/quodlibet/issues/detail?id=204) created by nanocmoi on 2009-05-22T09:02:53.000Z:

It's quite tying to have to click on the time button to display the time bar.
I think there is a lot of place to display such a bar all the time in the
window. If the bar could be bigger than now it would be easier to navigate
into long songs.

**Comment by declension** [comment]
+1

**Comment by Moilleadoir** [comment]
As a new user it’s really surprising to find that this basic element of playback control is missing in Quod Libet.

OK, not missing as such, but certainly well hidden and inadequate. The current slider is not wide enough for any practical use in seeking. Compare Rhythbox (about 25% of the window), Clementine (> 50% of the playlist pane) or Audacious (75% of the window).

Of course, QL doesn’t *have* to be the same as those programs, but not implementing something so common does make the program distinctive in a *negative* way. It also limits users to using the program in a particular way. For example if I want to find a particular phrase in a long piece of music I’m definitely not going to choose QL to do it.

So is this issue effectively dead or is there a chance it might be implemented one day?

**Comment by declension** [comment]
Personally I'm in favour of getting this done (but have limited time currently).

Six years of discussions and trial patches hasn't really helped the bigger picture much... 

If users shout and cry, we can revert it (or provide a config option)

**Comment by Jimi-James** [comment]
I desperately want this feature, and also a "moodbar" (i.e. a waveform-type view like in Clementine) as an option. Currently, seeking in QL is, frankly, awful with the current implementation, and the lack of some sort of moodbar/waveform option makes it useless for something that was so easy in Clementine: skipping through a large silent portion of a track to get to the hidden track at the end.

**Comment by timpulver** [comment]
Just tried Quod Libet and I’m very happy so far. Not having an all-time visible (long) progress bar is the only thing I’m really missing right now.
As @Jimi-James suggested having some sort of waveform view for seeking would be the ultimate thing. [Soundcloud](http://soundcloud.com) currently has the best waveform-seeking I know.

![Soundcloud playse image](http://soundcheck.soundcloud.com/wp-content/uploads/2012/10/Screen-Shot-2012-10-31-at-11.23.11.png)

**Comment by pierregermain** [comment]
That would be awesome @timpulver

**Comment by pierregermain** [comment]
for the time-being what I do for seeking is to use these shortcuts:

```
quodlibet --seek +0:10"
quodlibet --seek -0:10"	
```

**Comment by timpulver** [comment]
I will go with scrolling on the time label/button. Only downside is that I don’t know where I am in the track.

**Comment by felixsanz** [comment]
Missing this feature much!

**Comment by lazka** [comment]
This is now in master, as a plugin.

![screenshot from 2016-03-07 14-43-11](https://cloud.githubusercontent.com/assets/991986/13571116/0bb5960a-e473-11e5-85f7-801d7970fb87.png)

**Comment by felixsanz** [comment]
@lazka  awesome! thanks so much!

**Comment by spxxxk** [comment]
Awesome indeed, thanks !

Notes: 
- Seeking steps using mouse wheel are not consistent between old and new seekbar (and I prefer the old one, ie smaller steps)
- It's weird to have two updated current length times displayed, old seekbar button and left of new seekbar. Maybe the old seekbar button could display the fixed total length time..
- Doesn't seem to increase CPU on my side.

Also, If someone happens to know the gtk code that affect that seekbar/progressbar color, I'd appreciate it.

**Comment by lazka** [comment]
> Notes: [...]

Thanks, I'll have a look

> Also, If someone happens to know the gtk code that affect that seekbar/progressbar color, I'd appreciate it. 

```
.scale.trough.highlight {
    background-image: none;
    background-color: #ffbb00;
    border-color: #000000;
}
```

**Comment by urielz** [comment]
Excellent! Much better now.

**Comment by CreamyCookie** [comment]
Nice, I like this new version! I think the only thing left to improve regarding the design is the empty space (highlighted in yellow) and the time being displayed twice.

In the mockup below, this isn't true anymore, but it sadly leaves a new empty spot there.

![screenshot mockup](https://cloud.githubusercontent.com/assets/3063858/13699849/660b045c-e77d-11e5-9ada-d06b090f4df4.png)

**Comment by urielz** [comment]
The icons at the bottom left of the window could be placed there, following the previous mockup:

![ql_mup](https://cloud.githubusercontent.com/assets/11670888/13706407/fb9b7412-e772-11e5-8c76-5f38cc7e44a4.png)

**Comment by declension** [comment]
Shall we close this ticket now? There are in fact two versions of this now available (as plugins)....

**Comment by urielz** [comment]
It seems that pretty much everything raised in this thread is covered by the plugins.

**Comment by declension** [comment]
Great. Closing for now.

**Comment by sylvainfaivre** [comment]
for anyone finding this bug with a google search, the plugins are "alternative seek bar" and "waveform seek bar".
