### ISSUE TITLE
Problem in tag editing in Ex Falso

### ISSUE THREAD

**Issue by Floydlovr** [quodlibet/quodlibet#2041]
When I rename the _title_ tag, it appears in the Ex Falso window, but when I look at the files, the updated title name is not there. Am I doing something wrong?

**Comment by lazka** [comment]
Does it only affect "title"? Which file format?

**Comment by declension** [comment]
Potentially related (though probably not) #2033

**Comment by Floydlovr** [comment]
Yes, it is onlythe title field. The files are *.mp3.

**Comment by lazka** [comment]
I can't reproduce.

"but when I look at the files" <- What do you use for looking at the files?

And which version of Ex Falso?

**Comment by JoseBarakat** [comment]
@Floydlovr Have you clicked the `Save`button placed on the bottom right corner of Ex Falso window? I made the same mistake several times in the past.

![exfalso-win](https://cloud.githubusercontent.com/assets/15618933/19728613/b55e88d6-9b59-11e6-8e8d-8a942d4f52db.jpg)

**Comment by Floydlovr** [comment]
Thanks everybody for your help. I think the matter lies in which version of ID3 is being used vs. the version of Windows. When I look at the tags in Ex Falso, they are there, but they don't appear in Windows. More research for me...
Thanks,Corey 

    On Wednesday, October 26, 2016 9:54 AM, Jose Barakat <notifications@github.com> wrote:
 

 @Floydlovr Have you clicked the Savebutton placed on the bottom right corner of Ex Falso window? I made the same mistake several times in the past.—

**Comment by lazka** [comment]
Windows can't handle id3v2.4 tags which ex falso writes.

**Comment by Floydlovr** [comment]
Is there any way I can get ExFlaso to revert to an earlier version? 

    On Thursday, October 27, 2016 1:13 PM, Christoph Reiter <notifications@github.com> wrote:
 

 Windows can't handle id3v2.4 tags which ex falso writes.—

**Comment by lazka** [comment]
No, sorry.

**Comment by lazka** [comment]
See #160

**Comment by svnpenn** [comment]
https://github.com/quodlibet/quodlibet/issues/403

**Comment by svnpenn** [comment]
https://github.com/quodlibet/mutagen/issues/82

**Comment by svnpenn** [comment]
https://github.com/quodlibet/mutagen/issues/85
