### ISSUE TITLE
Runtime error + wrong display

### ISSUE THREAD

**Issue by bert07** [quodlibet/quodlibet#2047]
Using Windows 7 32-bit.

See the attached files: 1.jpg + 2.jpg + 3.jpg.

![3](https://cloud.githubusercontent.com/assets/22558426/19013247/87e52654-87cb-11e6-8441-eb70959a9b9d.jpg)
![1](https://cloud.githubusercontent.com/assets/22558426/19013248/87e716d0-87cb-11e6-98f1-bb738d55066d.jpg)
![2](https://cloud.githubusercontent.com/assets/22558426/19013249/87e8c55c-87cb-11e6-975c-fcdb06493161.jpg)

**Comment by bert07** [comment]
Forgot to tell:

Quod Libet 3.7.1, but I checked: I also have it with Quod Libet 3.6.1, except for the runtime error.

**Comment by lazka** [comment]
Thanks. When does the runtime error occur?

**Comment by bert07** [comment]
When Quod Libet is open for 10 to 30seconds (more or less).
You do not have to do anything: it'll come.
And as you can see: the display is not correct.

**Comment by lazka** [comment]
Maybe the same cause as #1696 ? Try disabling library scan in the preferences.

**Comment by lazka** [comment]
Regarding the missing font, I think that's a different issue.

**Comment by bert07** [comment]
I think that the 32-bit may be an issue.
It works fine on my other computer with Windows 7 64-bit and Debian Jessie 64-bit and Ubuntu 16.04 64-bit..
They all scan at system start-up,
But I'll turn it off on this 32-bit Windows, and wait what happens.

**Comment by bert07** [comment]
At this moment nothing happens, also when I let it scan at start-up again.
It happened 3 times in a row before I wrote you though.

If the problem with the display is a missing font, how come it is correct in the 64-bit than?

**Comment by lazka** [comment]
> At this moment nothing happens, also when I let it scan at start-up again.
It happened 3 times in a row before I wrote you though.

OK thanks for testing

> If the problem with the display is a missing font, how come it is correct in the 64-bit than?

No idea.

**Comment by bert07** [comment]
Forgot to tell: The runtime error did NOT occur in version 3.6.1 and version 3.7.0. Only in version 3.7.1.
The font issue in all of them.
I als need to tell, that till a few weeks ago ALL my computers where 64-bit and everything worked fine, but a few weeks ago I reinstalled Windows 7 on my laptop but I installed the 32-bit Windows 7 (SP1).
I had not used Quod Libet on this computer since, till this morning. So I really think that the 32 or 64-bit may be an issue.

**Comment by bert07** [comment]
Extra: I like Quod Libet, especially because one can use it on Windows and Linux. (And Mac.)
The only thing I'm miccing at this program is a complete random play. Such as MediaMonkey can do.
Otherwise: I love Quod Libet!
Take care. Hopefully you can fix this issue.

**Comment by bert07** [comment]
I also should have mentioned that BEFORE I wrote here, I reinstalled/repaired all my "Microsoft Visual C++" drivers. (2005, 2008, 2010 SP1, 2012, 2013),
Perhaps that is why the runtime crash does not repete no longer at this moment.

Maybe that cured the "runtime error". But than there is still the issue of the display.
And I use the same font (DejaVu Sans) for all my systems.

**Comment by bert07** [comment]
I was wrong! 
I started Quod Libet up again just after I wrote previous, and I got the "runtime error" in 2 seconds.

**Comment by RoestVrijStaal** [comment]
Same issue here. The weird thing is that it occurs occasionally, but it seems very related to scanning / rebuilding  the library.

Does Quod Libet write a log somewhere which i could put here so you could have a clue? "The message C++ Visual Runtime error" isn't that verbose. 
I looked in the %appdata% and %temp% folder but it seems Quod Libet doesn't write a log?

**Comment by lazka** [comment]
If anyone is feeling adventurous, there is now a new installer based on msys2: https://github.com/quodlibet/quodlibet/issues/1718#issuecomment-258706608

**Comment by lazka** [comment]
@bert07 could you test the new installer? https://github.com/quodlibet/quodlibet/issues/1718#issuecomment-258706608

I've just tried switching the Windows font to dejavu sans and things seem to work.

**Comment by lazka** [comment]
Feel free to reopen this if the problem persists with the new installer.

**Comment by 07416** [comment]
@lazka The issue persists with `3.7.1` every now and then. QL starts to crash on startup (related to rebuilding library, only happens when I have added new songs to my music folder if I recall correctly) and sometimes I'm unable to open the program at all and have to switch music player.
Is there a need for a fresh reinstall?

**Comment by lazka** [comment]
@07416: You can either try the [current unstable installer](https://bitbucket.org/lazka/quodlibet/downloads/quodlibet-latest-installer.exe) or wait 2.5 weeks for v3.8.0
