### ISSUE TITLE
usage: library

### ISSUE THREAD

**Issue by paystreak** [quodlibet/quodlibet#2073]
Quod Libet keeps scanning the library even though I don't have auto scan at start checked. My music folder has a lot of junk sound files that I don't want Quod Libet to list in the playlist. So, I thought I could outsmart Quod Libet by leaving the library field blank. But, Quod libet was smarter than me. I opened the player and found a blank playlist. Without removing those files from the directory, is there another way to keep Quod Libet from scanning the folder? Also, unclear about scan vs. rebuild options. Well, I had to scan the folder to get the music back in there, then manually remove from library the files I didn't want in the playlist.(main list) (the user manual didn't seem to cover this stuff)
Thanks,
paystreak

**Comment by urielz** [comment]
That's odd. The option to prevent scanning on startup works for me (QL 3.7.1 on OS X). What version and system are you using?

**Comment by paystreak** [comment]
I'm using 3.7.1 on Mint linux. The other point I forgot to mention was the duplicate entries. Also, QL read another directory besides the one I listed in the library field. I have two music dirs:
~/Music and ~/myMusic. Not sure why QL would read the myMusic dir. So for some songs I had 4 listings, 2 from each dir. That's the other reason I left the library field blank.

**Comment by declension** [comment]
Hmm just found this
@paystreak
 * to manage actual (near-)duplicates, try the _Duplicate Browser_ plugin.
 * If you want a global filter (exclude), you can do that in the Prefs (under _Browser_ ) , and it can be on directory e.g. `~dirname=!/^\/home\/me\/myMusic/`
* Also: in general, I tend not to use symlinks for library directories as this can cause odd behaviour.

**Comment by CreamyCookie** [comment]
Closing this one as there are no similar reports (to my knowledge), the user seems to be gone and there isn't enough information to fix this.
