### ISSUE TITLE
Ctrl+w to close Edit Tags dialog

### ISSUE THREAD

**Issue by lorentrogers** [quodlibet/quodlibet#2075]
I expected `Ctrl+w` to close the dialog for Edit Tags, but it doesn't look like that's a shortcut. Since closing the window via the window manager closes, it would make sense to also have this fairly standard shortcut as well.

**Comment by lazka** [comment]
It does here. Which version are you using?

**Comment by lorentrogers** [comment]
My mistake! (I really need to fix the ctrl key on my keyboard.) Totally works.

**Comment by lazka** [comment]
Maybe you tried with 3.2 first (not sure if that worked there..)

Thanks.

**Comment by lorentrogers** [comment]
I didn't.. sorry
