### ISSUE TITLE
AttributeError: 'module' object has no attribute 'CancelRevertSave'

### ISSUE THREAD

**Issue by rbrito** [quodlibet/quodlibet#2081]
Hi.

I was tagging some vorbis files in Ogg containers with exfalso (I was actually trying to compare the internal names that exfalso uses vs. those that easytag uses) on my Debian testing/sid system.

I apparently triggered something that gave me a stack trace. I will attach the dump that exfalso generated and I can try to answer questions about the problem, but I don't know if I will be able to reproduce the specific steps that led to this problem.

Thanks,

Rogério Brito.

[Dump_20161103_224454.txt](https://github.com/quodlibet/quodlibet/files/570397/Dump_20161103_224454.txt)

**Comment by lazka** [comment]
Can reproduce, thanks.

**Comment by rbrito** [comment]
Super thanks, @lazka!
