### ISSUE TITLE
Wrong song plays on restart

### ISSUE THREAD

**Issue by lorenrogers** [quodlibet/quodlibet#2082]
I keep getting this strange state where the wrong song file is playing even though the current playing song label is correct.

I believe this happens because of some interaction between the queue and the current playing logic. I'm not able to reproduce this every time, but I believe this is the scenario that it happens in:
- Add some songs to the queue
- Start playing the queue
- Quit QL mid-song (possibly paused?)
- Open QL again
- Find a different track in the library and double click it to start playing

The result should be that the audio from the last track in the queue starts playing, but the metadata (title, artist, etc.) for the selected song is shown in the current track.
 
I'm running Debian 8 with QL 3.7.1

Supported formats: AAC, AIFF, ASF, FLAC,
MIDI, MOD/XM/IT, MPEG-1/2, MPEG-4,
Monkey's Audio, Musepack, Ogg FLAC, Ogg Opus,
Ogg Speex, Ogg Theora, Ogg Vorbis, Remote File,
SPC700, True Audio, VGM, WAVE,
WavPack

Audio device: GStreamer (autoaudiosink)
Python: 2.7.9
Mutagen: 1.34.1
GTK+: 3.14.5 (X11)
PyGObject: 3.14.0
GStreamer: 1.4.4.0

**Comment by CreamyCookie** [comment]
> The result should be that the audio from the last track in the queue starts playing, but the metadata (title, artist, etc.) for the selected song is shown in the current track.

@lorenrogers You mean that's what shouldn't happen, right? Are you using gapless playback? (If so, this might be #837)

**Comment by CreamyCookie** [comment]
Closing as not enough information and I had a similar issue #1566 (which turned out to be #837).
