### ISSUE TITLE
Keyboard volume control stopped working: Fedora 24

### ISSUE THREAD

**Issue by alan12345678** [quodlibet/quodlibet#2088]
Not a bug per se but hoping you can help.

All's been working perfectly until a recent, regular "dnf upgrade --refresh". This morning my keyboard volume controls stopped working altogether. Having now updated the gnome shell extension, the keyboard alters the output sound channel (as it should) although this now doesn't control the volume in Quodlibet as it did before. Changing volume in QL manually using slider works fine, it's just not hooked up to the keyboard anymore :0/

Is there some cache I can clear/rebuild or other small config change I can make? A small but annoying problem.

**Comment by lazka** [comment]
We register with gnome-settings-daemon and get the volume events over dbus. Not sure what the problem could be.

Have your tried restarting your computer?

**Comment by alan12345678** [comment]
Yup, sure have. Several times. First time after this morning's update the keyboard wasn't registering at all (for media. It was working). First reboot and the volume icon returned. Second reboot and now the keyboard volume icon shows increase/decrease in volumes, but it just doesn't affect the volume of QL.

My taskbar (where the volume icons display) shows the output channels, but again, keyboard presses only affects output channel, doesn't alter QL volume.

Happy to fiddle. Anything I can reset? Any conf files need checking?

**Comment by alan12345678** [comment]
Yup, sure have. Several times. First time after this morning's update the keyboard wasn't registering at all (for media. It was working). First reboot and the volume icon returned. Second reboot and now the keyboard volume icon shows increase/decrease in volumes, but it just doesn't affect the volume of QL.

My taskbar (where the volume icons display) shows the output channels, but again, keyboard presses only affects output channel, doesn't alter QL volume.

Happy to fiddle. Anything I can reset? Any conf files need checking?

**Comment by lazka** [comment]
No idea how this works on the gnome shell side.

You can monitor the communication between QL and GS with `dbus-monitor --session "interface='org.gnome.SettingsDaemon.MediaKeys'"`

**Comment by alan12345678** [comment]
I should perhaps mention! - this volume problem is 'system-wide': my volume has stopped working to control e.g. streaming video in a browser. Presumably then this isn't strictly a QL issue?

Here's the output from above terminal:

    signal time=1478771388.614712 sender=org.freedesktop.DBus -> destination=:1.66 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.66"
signal time=1478771388.614738 sender=org.freedesktop.DBus -> destination=:1.66 serial=4 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string ":1.66"

If I press volume keys, no further output appears in the terminal.

**Comment by lazka** [comment]
What's the output of

``dconf read "/org/gnome/settings-daemon/plugins/media-keys/active"``

**Comment by alan12345678** [comment]
err... nothing. Doesn't return anything!

**Comment by lazka** [comment]
Weird.. try 

`dconf reset -f "/org/gnome/settings-daemon/plugins/media-keys/"`

then (and maybe check if "gnome-settings-daemon" is installed, but I'm wondering if GS would even start without it)

**Comment by alan12345678** [comment]
Done. Above returned no output. Re-ran the previous command, again no output. The daemon is installed:

    gnome-settings-daemon-3.20.2-1.fc24.x86_64

**Comment by lazka** [comment]
Hm, maybe that has changed in 3.22. You can try installing dconf-editor and try to find the config there.. anyway, I don't really no how this all works.

**Comment by alan12345678** [comment]
Thanks for your help. It would seem to be a Fedora/Gnome issue (grrr...)

Your player remains BRILLIANT! Thanks :0)
