### ISSUE TITLE
The Waveform Seek Bar doesn't work at all for me

### ISSUE THREAD

**Issue by NoahAndrews** [quodlibet/quodlibet#2094]
I usually use the Alternative Seek Bar plugin, but disabled it for the purpose of trying the Waveform Seek Bar. Enabling the Waveform Seek Bar plugin looks like this: 
![image](https://cloud.githubusercontent.com/assets/10224994/20223724/e4b45c94-a808-11e6-9ad0-5728278eee8d.png)

I get this result both on the latest stable version and the latest development commit. I'm using Windows 10, and I have the new MSYS environment set up for the development version.

**Comment by lazka** [comment]
> I usually use the Alternative Seek Bar plugin, but disabled it for the purpose of trying the Waveform Seek Bar. Enabling the Waveform Seek Bar plugin looks like this:

Right, noticed that too but forgot to file an issue. There is some gstreamer error while decoding afair.

> I get this result both on the latest stable version and the latest development commit. I'm using Windows 10, and I have the new MSYS environment set up for the development version.

Thanks for trying out the new windows stuff!

**Comment by NoahAndrews** [comment]
That was fast! Thanks for the fix.

**Comment by lazka** [comment]
``./quodlibet.py --debug`` should also be nicer now.
