### ISSUE TITLE
switch views - time lag

### ISSUE THREAD

**Issue by urielz** [quodlibet/quodlibet#2100]
There’s a noticeable delay when switching views. On my end, it can take from 0.5 up to 1.5 seconds (the paned browser view seems to be the one with the most lag). This is on QL 3.7.1 on OS X Sierra (but older versions of QL suffered from the same problem). 

I’m curious to whether this behavior is consistent across all systems or perhaps this is something occurring only on macs (or just my system?). Although not something that bothers me much, it would be nice to improve performance if possible…

**Comment by lazka** [comment]
That's to be expected and depends on the size of your library. Things could maybe be delayed to after the layout is shown, but the browser would still only be usable after that initial work is done.

**Comment by urielz** [comment]
My library size is not that big (~2.8k files). I hope the delay plateaus at some point or slows down growth at least. I can see this being a potential issue in my opinion if it takes much longer than that. I'll close this thread now. Thanks for the clarification lazka.

**Comment by lazka** [comment]
With the paned browser it also depends on the complexity of the patterns used. There are fast paths for simple tags etc.
