### ISSUE TITLE
Pickle & Python 3

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#2120]
(braindump)

Things we need:

* Support protocol 0, 1, 2
* Somehow don't call `__setitem__` with protocol 2
* Work with old existing pickles, so no `__setstate__` or `__getnewargs__`
  because they only get used when enabled at pickle time.
* For Python 3 we can use the special "bytes" codec and protocol <= 2, to
  load/save Python 2 compatible pickles.
* Python 3: For serializing paths we need to use bytes on unix since the
  surrogateescapes depend on the runtime encoding. Also for Python 2 compat. Windows paths stay the same (unicode +  surrogates)
* Figure out how pickled lone surrogates are handled in Python 3. We don't want
  them to end up in tags, otherwise things will explode randomly.
* Figure out if there is an easy way to see if something was pickled with py2
  or py3. So in case we need to strip surrogates this only happens when
  switching Python versions.
* It would be nice if we could find a semi-fast way to instance check
  keys/values under Python 2 so we can switch to unicode keys/values
  and can get rid of some runtime checks, speeding things up there. (a simple isinstance check adds 100ms here for a 1.8s startup)
* Make sure we still support pickles where some classes don't resolve.

Also found this: https://docs.python.org/2/library/pickletools.html

pickletools.optimize reduces my unpickle time from 160ms to 110ms. But also
takes 1.8s additionally for saving. Not sure if that's worth it.

The other functions in that module might come in handy for debugging.

**Comment by lazka** [comment]
(to summarize: looks like we can get away with sharing the songs db between Python2/3, but performance might be a problem)

**Comment by lazka** [comment]
* Python 3 will unpickle lone surrogates pickled with Python 2 as is.

**Comment by zsau** [comment]
Rather than go through the pain of supporting the same pickled file between Python versions, I strongly favor taking this opportunity to rethink QL's serialization format altogether. Serializing an object graph directly to disk is brittle and inflexible, and good performance can be achieved with other methods.

Did anything ever come of your msgpack experiments (#1330)? I'm very willing to help with the work here.

**Comment by lazka** [comment]
Note that we need to handle old pickles and ~99% of this work is needed anyway.

**Comment by lazka** [comment]
Everything for the transition should be done now.
