### ISSUE TITLE
play order: one song is missing

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#2121]
I don't remember if that was removed intentional.

someone on IRC asked about it

**Comment by declension** [comment]
As I remember this was only semi-intentional. It definitely didn't make any sense as a Shuffle Order... Could be rethought / added as a Repeat Order though. 

Obviously there's still _Stop After This Song_ but I guess that's slightly different

**Comment by declension** [comment]
(added #2123 to improve UI a bit)
