### ISSUE TITLE
quodlibet paused playback during scan, then continued with next song showing "Error Occured"

### ISSUE THREAD

**Issue by floesche** [quodlibet/quodlibet#2124]
The "Error Occured" windows asked me to open a new issue attaching the dump.

[Dump_20161127_194900.txt](https://github.com/quodlibet/quodlibet/files/614968/Dump_20161127_194900.txt)

Playback worked fine afterwards.

**Comment by lazka** [comment]
Hm, not sure why writing to stderr would fail. Anyone else got any ideas?

**Comment by declension** [comment]
Hmm is it being redirected (or is this within a Docker or other container)?

**Comment by lazka** [comment]
Could it be that your disk is full? Maybe stdout/err being redirected to the journal and that failing there.

**Comment by floesche** [comment]
I am running on a physical machine (no virtualisation of any kind).

Currently /dev has 5.9GB available, / has 6.8, ~ has 40GB. The computer was booted just before the error occured yesterday and I didn't do much but web browsing, so I doubt, that any of the file systems ran out of space.

**Comment by lazka** [comment]
No idea then :(

**Comment by floesche** [comment]
don't worry, I'll close this then as the issues doesn't seem to be related to quodlibet. I'd reopen should I be able to replicate the problem.

**Comment by floesche** [comment]
It seems that the file scanned is faulty - it seems to break pretty much any player/library including ffprobe, audacity etc... It seems to consist of the (possibly incomplete) header information only. Let me know if you want to have it (only 2k) in case you want to replicate. Might not be relevant for other users, though...

**Comment by lazka** [comment]
Sure. Please send to reiter.christoph@gmail.com
