### ISSUE TITLE
Ex Falso should prompt to save changes before switching to a new track

### ISSUE THREAD

**Issue by NoahAndrews** [quodlibet/quodlibet#2126]

**Comment by declension** [comment]
Sounds like #383

**Comment by NoahAndrews** [comment]
I need to not be lazy about searching. Sorry for the spam.

**Comment by NoahAndrews** [comment]
Actually, that issue is about Quod Libet proper. Is this something that will need to be fixed twice or just once?

**Comment by declension** [comment]
No problem, thanks for the report. It's actually useful sometimes to re-prioritise old bugs, as there are so many open ones...

And yes Ex Falso shares the vast majority of its code so this should be the same one. So: (re-)closing as duplicate.
