### ISSUE TITLE
Convert and Export Plugin

### ISSUE THREAD

**Issue by Tamriel** [quodlibet/quodlibet#2135]
I created a plugin, which converts all songs from selected saved searches to 192 kbs and synchronizes them to the specified path (all songs at that path which are not in the saved searches will be deleted).

In case people have need for it, it could be added to the shipped plugins.

https://gist.github.com/Tamriel/204ee6e3fe84e7450d2a71d6127f34eb

**Comment by CreamyCookie** [comment]
Thanks, but I think that's too specific to be included by default (and would require a compatible license). 

Closing this, but maybe we could create an issue-only repository where users could post their custom plugins. (Not sure how common that is though.) Then we could use GitHub's transfer issue function (on the lower right) if someone accidentally reports them here. @lazka

**Comment by frestr** [comment]
This is essentially #2636 btw.
