### ISSUE TITLE
Repeatedly invoking song notifications makes Quod Libet unresponsive

### ISSUE THREAD

**Issue by cloudscream** [quodlibet/quodlibet#2139]
Repeatedly invoking song notifications (e.g: playing consecutive tracks in quick succession, pressing "Show notifications" repeatedly in the plugins settings of the Song Notifications plugin) makes the Quod Libet window unresponsive. Music is still playing in the background but the program freezes and becomes unusable. 

The following error message is produced: "**[notify] Couldn't connect to notification daemon.**"

Other music players like Banshee and Rhythmbox do not exhibit the same behavior. I'm using Linux Mint 18 and the error occurs in quodlibet 3.5.3 and 3.7.1.

**Comment by lazka** [comment]
Thanks. Looks like #1679
