### ISSUE TITLE
Unicode error

### ISSUE THREAD

**Issue by spxxxk** [quodlibet/quodlibet#2142]
QL version: `3.8.99+8752~8785555d4-0~ppa0~xenial`

[Dump_20161211_100612.txt](https://github.com/quodlibet/quodlibet/files/644347/Dump_20161211_100612.txt)

**Comment by lazka** [comment]
Thanks

**Comment by lazka** [comment]
Do you use `~mountpoint` in your display pattern?

**Comment by spxxxk** [comment]
Yes.

**Comment by lazka** [comment]
Thanks. Removing it from the pattern until this is fixed would be a workaround.

**Comment by spxxxk** [comment]
Indeed, thanks.

**Comment by lazka** [comment]
It's part of a larger problem, so might take a few days..

**Comment by spxxxk** [comment]
- my QL version is 3.8.99+8781~`fc132bc8f`-0~ppa0~xenial
 - based on https://github.com/quodlibet/quodlibet/commits/master , `fc132bc8f` has been commited after `c0454aa`

So I'm led to believe I have that `c0454aa` fix ... Anyway, sorry if I'm wrong, ignore the following.

I now have that error dump [Dump_20161217_120041.txt](https://github.com/quodlibet/quodlibet/files/658822/Dump_20161217_120041.txt) when trying to add that `~mountpoint` part.

**Comment by lazka** [comment]
Hm, weird, thanks.

**Comment by spxxxk** [comment]
Actually, the error is only triggered when using `~mountpoint` with the syntax
`<~mountpoint="/"|yes|no>`

`<~mountpoint>` alone is fine and working.

**Comment by lazka** [comment]
Thanks!
