### ISSUE TITLE
IndexError while scanning library

### ISSUE THREAD

**Issue by tilmanginzel** [quodlibet/quodlibet#2143]
Hey, 

while trying to scan my library, I get an IndexError: list index out of range.
I suspect [this](https://github.com/quodlibet/quodlibet/commit/3bca05a940882a9563f56d6251ed39bc484e242a?diff=unified#diff-141a099dbfed2bae0107ead6da2cb645) or [this](https://github.com/quodlibet/quodlibet/commit/93f2efd3f3f68d594eaa18d722e126260401ee0e#diff-141a099dbfed2bae0107ead6da2cb645) commit broke something, but I didn't go too much into detail there.

```
=== SYSTEM INFORMATION:
Quod Libet 3.7.1
Mutagen 1.34.1
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] linux2
Platform Linux-4.4.0-47-generic-x86_64-with-LinuxMint-18-sarah
=== STACK TRACE

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/quodlibet/util/copool.py", line 25, in wrap
    for value in func(*args, **kwargs):

  File "/usr/lib/python2.7/dist-packages/quodlibet/library/libraries.py", line 690, in rebuild
    for value in self.scan(paths, exclude, cofuncid):

  File "/usr/lib/python2.7/dist-packages/quodlibet/library/libraries.py", line 740, in scan
    item = self.add_filename(fullfilename, False)

  File "/usr/lib/python2.7/dist-packages/quodlibet/library/libraries.py", line 840, in add_filename
    song = MusicFile(filename)

  File "/usr/lib/python2.7/dist-packages/quodlibet/formats/_misc.py", line 118, in MusicFile
    return loader(filename)

  File "/usr/lib/python2.7/dist-packages/quodlibet/formats/mp4.py", line 91, in __init__
    cur, total = values[0]

IndexError: list index out of range
```

**Comment by lazka** [comment]
Thanks

**Comment by lazka** [comment]
(I haven't looked into it) In case this is something new for you, my guess is that

* it is because you have new mp4 file which triggers this bug in QL
* you updated to 3.7. In <=3.6 such errors would be ignored and the file not loaded.

**Comment by tilmanginzel** [comment]
Your second guess is right. Previously I had version 3.5.3 installed, which worked fine. I wouldn't care too much, if the file would be ignored. But I don't know the underlying problem, so ignoring the error could be wrong.

**Comment by lazka** [comment]
OK. Sadly I can't think of an easy workaround.

You can use exfalso and look through your music library until you get an error, so you can at least see in which directory the problematic file is and maybe move that file out of the way.

**Comment by tilmanginzel** [comment]
Ok. Would it help if I identify the file in question and give you more info about it, or do you already know the underlying problem?

**Comment by lazka** [comment]
Having a real file always helps, but it's not required. If you find it please send to reiter.christoph@gmail.com Thanks!

**Comment by tilmanginzel** [comment]
Check your inbox. ;)

**Comment by lazka** [comment]
Thanks!

**Comment by tilmanginzel** [comment]
Wow, that was a fast fix! Great, now the file even gets scanned. Thank you very much. :)
