### ISSUE TITLE
quodlibet hides automounted library

### ISSUE THREAD

**Issue by nemoinis** [quodlibet/quodlibet#2146]
Hello,
I'm running quodlibet 3.7 on Debian testing (Stretch right now).
My music library is a NFS mount managed by automount (autofs) so it gets mounted automatically on first access if not already, and is unmounted after a while when not in use.

The problem I have is that when first launched, quodlibet "hides" the library (I think this was the fix for bug #984) because it thinks it's not mounted. That's because the python os.path.ismount() call used by quodlibet, does not trigger an autofs mount.

I worked around that by using a little script that "test -e /path/to/music/." before launching quodlibet (that's enough to trigger the automount). But I think maybe quodlibet "jumps the gun" a little by assuming that an unmounted mountpoint means the music is not available. Maybe it should actually try to access it.

cheers!

**Comment by lazka** [comment]
What does "access" mean in this case? ismount calls stat, just like "test -e".

**Comment by lazka** [comment]
https://hg.python.org/cpython/file/95140ff/Lib/posixpath.py#l188

**Comment by nemoinis** [comment]
Hi lazka,
Thanks for the crystal-clear response. I think you missed the point, though.
Just assume my script does "test -e /path/to/music/crickets/chirping.mp3"

**Comment by lazka** [comment]
ok, I assumed "/path/to/music/" is your mount point which confused me.

We should stat the first file we have for each mount point before calling ismount then.

**Comment by lazka** [comment]
I hope that works, if not please reopen.

**Comment by nemoinis** [comment]
It works on my system. Thanks!
