### ISSUE TITLE
treat apostrophes in metadata as straight single quotes for search

### ISSUE THREAD

**Issue by uapeaggu** [quodlibet/quodlibet#2147]
Due to constraints of a keyboard, users enter apostrophes into search fields using the straight single quote character ( ' ), but if the metadata for a song has a proper curly quote apostrophe, it won't be found.

If you don't know what I'm talking about, compare the following (the top one uses a proper apostrophe):
# We’ve Got Tonight
# We've Got Tonight

It would be best if Quod Libet were to treat straight single quotes and proper curly quote apostrophes the same for the purposes of search.

The same issue affects double quote characters, but those appear much less frequently in metadata.

**Comment by lazka** [comment]
Sounds good

**Comment by uapeaggu** [comment]
nice! :-)
