### ISSUE TITLE
Translated strings are made Title Case but is not disired

### ISSUE THREAD

**Issue by scootergrisen** [quodlibet/quodlibet#2155]
I am translating this software and it seems some strings case are changed in the software.

Example:
```
#: ../quodlibet/util/tags.py:101 ../quodlibet/util/tags.py:102
msgid "disc subtitle"
msgstr "disk-undertitel"
```

source code:
```
    T("discsubtitle", "u", _("disc subtitle")),
    T("part", "u", _("disc subtitle")),
```

The string becomes "Disc Subtitle" which might be correct in english.
But in my language it becomes "Disk-Undertitel" with a large "U" which is not correct.
I see it in other strings to.

**Comment by lazka** [comment]
Have a look at: https://quodlibet.readthedocs.io/en/latest/translation/faq.html#what-does-titlecase-mean

Does that help?

**Comment by scootergrisen** [comment]
Thanks.

It seems leaving the string empty gives title case despite the comment saying "translate this string as something other than "titlecase?"". Perhaps the software uses the source string if msgstr is empty and there for both are "titlecase?".

**Comment by lazka** [comment]
Yeah, leaving a string empty in a .po file is equivalent to "untranslated"

**Comment by scootergrisen** [comment]
Ok but i don't think the comment is correct when it says "something other then "titlecase?"".

**Comment by lazka** [comment]
Regarding the original issue: Does the "titlecase?" trick lead to the desired behavior?

**Comment by scootergrisen** [comment]
Yeah i just wrote something that is not "titlecase?" and not "" and it does not use title case.
