### ISSUE TITLE
Toggle plugins with space bar

### ISSUE THREAD

**Issue by scootergrisen** [quodlibet/quodlibet#2157]
I am trying to test the plugin and want to enable and disable them all, but its really boring to have to click so many times and scroll the list.

I can't toggle with space bar.
Perhaps it would nice to be able to toggle with space bar or something so it would be easier to enable/disable a lot of plugins.

**Comment by lazka** [comment]
Sounds good, thanks.

**Comment by urielz** [comment]
A select/unselect all button would also be handy...
