### ISSUE TITLE
Place short cut dialog in middle of screen

### ISSUE THREAD

**Issue by scootergrisen** [quodlibet/quodlibet#2160]
When i open the short cut key dialog it seems to be place in the most bottom right corner of the screen.
If i move it to the middle and close it, it will open in the bottom right corner again next time.

Suggest placing the dialog in the middle of the screen.

Also Ctrl+F1 does not open the dialog. At least in LXQt desktop manager.

**Comment by lazka** [comment]
The ctrl+f1 not working is most likely your window manager handling that before we get it.

**Comment by scootergrisen** [comment]
I see it works in GNOME.
I will try and investigate some more.

**Comment by scootergrisen** [comment]
It seems both Plasma and LXQt use Ctrl+F1 to switch to desktop 1.

**Comment by lazka** [comment]
ok, gnome also uses ctrl+shift+?, I guess we can use that instead

**Comment by scootergrisen** [comment]
I don't know what is best.
In my language i have to hold Shift to enter a "?".
I can try and test if Ctrl+Shift+? does anything in the desktop managers i have.
Maybe tjek what ofter software use the most if they use it at all.

**Comment by lazka** [comment]
gnome apps support both Ctrl+F1 and ctrl+shift+? for this. I don't know anything similar on other platforms.

**Comment by scootergrisen** [comment]
Maybe better to keep somthing+F1 because F1 seems to be used a lot for help stuff.

**Comment by scootergrisen** [comment]
Yeah i also saw both Ctrl+F1/Ctrl+? in Nautilis.
It says Ctrl+? without Shift but in my keyboard layout i have to hold Shift to get a "?".
I don't see any desktop manager using Ctrl+Shift+? for anything.
Alt+F1 seems to be used for opening application menu and something with desktop.

**Comment by lazka** [comment]
You're right, changed now, thanks.

**Comment by scootergrisen** [comment]
You could do the same as Nautilus and use both short cuts. That way old users can still use the old way.
