### ISSUE TITLE
Plugin to skip low-rated tracks

### ISSUE THREAD

**Issue by ghostwords** [quodlibet/quodlibet#2161]
Would Quod Libet be interested in bundling a plugin to skip low-rated tracks?

If yes, you can find my work in progress here: https://gist.github.com/ghostwords/f6469841f88183599c25bbfecd087fce. It would be good if `plugin_on_song_started` was told if the song was started via user interaction, since we should then let the song play regardless of rating.

Let me know if I should make a pull request.

**Comment by CreamyCookie** [comment]
Maybe I'm missing something, but shouldn't that be a [PlayOrderPlugin](https://github.com/quodlibet/quodlibet/blob/master/quodlibet/quodlibet/plugins/playorder.py). I think it also has what you need:

> There is also
>        def set(self, playlist, iter): ...
>    for when the user manually selects a song from the list.

[Here](https://github.com/quodlibet/quodlibet/blob/master/quodlibet/quodlibet/ext/playorder/playcounteq.py)'s one that prefers songs with a lower playcount.

**Comment by 101100** [comment]
This was addressed by https://github.com/quodlibet/quodlibet/commit/2c446eb4f5a08ae7d7dadf2fd3ff9b81adc091d6.
