### ISSUE TITLE
Persist Replay Gain mode

### ISSUE THREAD

**Issue by CreamyCookie** [quodlibet/quodlibet#2162]
The Replay Gain Mode determines whether volume is normalized [per track or per album](https://en.wikipedia.org/wiki/ReplayGain#Track-gain_and_album-gain) (so for the latter the differences in loudness in an album stay intact). It can be set when right clicking the loudspeaker like this:

![screenshot from 2016-12-21 23-04-08](https://cloud.githubusercontent.com/assets/3063858/21408069/2e68e0d2-c7d3-11e6-8c11-7c918ae82def.png)

I personally prefer the Track Mode, especially since currently the queue seems to use album gain.

_Slightly related:_ It could also be interesting to have a slider there to decide how much you value differences in loudness per track vs. within an album.

**Comment by declension** [comment]
Sounds good

**Comment by CreamyCookie** [comment]
Thanks @ptitjes and @lazka!

**Comment by ptitjes** [comment]
@CreamyCookie You're welcome :)
