### ISSUE TITLE
[Burn CD plugin] opens both a data composition and an audio composition task in xfburn

### ISSUE THREAD

**Issue by iyeprai** [quodlibet/quodlibet#2164]
I'm not sure if this is intended behavior -- the Burn CD plugin opens both a data composition and an audio composition task in xfburn. Perhaps this should be a configurable option for the plugin, rather than doing both ways every time?

**Comment by lazka** [comment]
We just call "xfburn --audio-composition file1.mp3 file2.mp3 ...". Is there any other way?

**Comment by iyeprai** [comment]
there are options for --data-composition and --audio-composition ... data composition works as expected, whereas audio composition opens both. this seems to be a bug in xfburn and has nothing to do with quod libet....
