### ISSUE TITLE
[Burn CD plugin] configuration option to set burning application to use

### ISSUE THREAD

**Issue by iyeprai** [quodlibet/quodlibet#2165]
it would be nice if there was a configuration option to choose from the supported burning applications (K3b, Brasero or xfburn). Instead of requiring the user to go through the extra menu to select one of those applications each time, the "Burn CD" context menu item would immediately open the user's configured choice.

**Comment by lazka** [comment]
I think that burning a CD is a rather infrequent task, for most users at least. I prefer the discoverability and lack of configuration of the current approach.

**Comment by iyeprai** [comment]
how about when user only has one of the burning applications available, make "Burn CD" clickable and open up the installed application? Wouldn't you expect most users don't use multiple burning programs anyway?

**Comment by declension** [comment]
Agreed a drop-down of one program is not good UX.

Personally i believe a fair few of these plugins could be converted to Custom Command plugins, and there are a few issues / ideas for consistent UX improvements there.... (though at the loss of some specific features / config)... but i _would_ say that...
