### ISSUE TITLE
musicbrainz_albumid isn't prioritized over labelid for album grouping

### ISSUE THREAD

**Issue by Hunter16g** [quodlibet/quodlibet#2176]
Having different musicbrainz_albumid tags in one album means some of them are incorrect, whereas different releases can share the same catalog number. Maybe I missed something, but I don't really understand the current behavior, is there a reason some people would want tracks with different MB ids grouped under the same album ?

**Comment by Hunter16g** [comment]
Reading this, https://quodlibet.readthedocs.io/en/latest/guide/tags/tags.html#album-identification it seems it already is supposed to work this way. However I have two albums with different musicbrainz_albumid tags and the same labelid, and they are still merged in quodlibet 3.8.

**Comment by CreamyCookie** [comment]
Could you test if this is still the case in 4.2.1 and if so, post a screenshot of the affected albums with as many columns visible as possible?

**Comment by CreamyCookie** [comment]
Closing this as no information has been provided.
