### ISSUE TITLE
Cover Grid: Speed up switching to the browser

### ISSUE THREAD

**Issue by CreamyCookie** [quodlibet/quodlibet#2181]
I don't know how achievable that is, but it would be great if the cover grid album would open faster. Switching from the album list to the cover grid takes about 5s here, while switching back to the album list takes less than 2s. This happens even when repeated within the same session.

**Comment by declension** [comment]
Yep, it's too slow. 

This got mentioned in the original PR. See #2071

**Comment by declension** [comment]
Fixed in #4101
