### ISSUE TITLE
Cannot create new playlists with selected files from context menu

### ISSUE THREAD

**Issue by CreamyCookie** [quodlibet/quodlibet#2183]
When doing this 

![screenshot from 2017-01-06 12-10-33](https://cloud.githubusercontent.com/assets/3063858/21716410/a6287496-d40a-11e6-8e04-5b6fde0cd06d.png)

an empty playlist file is created (it contains no songs), but no empty playlist appears in the playlist browser until restarting. Adding to an existing playlist does work.

**Which version of Quod Libet?**

3.8.0

**Which operating system including version (Ubuntu 14.04, Win7, Debian sid, ...)?**

Ubuntu 16.04

**Comment by declension** [comment]
Thanks

**Comment by CreamyCookie** [comment]
Thanks for fixing!
