### ISSUE TITLE
windows executable does not start

### ISSUE THREAD

**Issue by madewokherd** [quodlibet/quodlibet#2186]
Quod Libet fails to start when run from the start menu shortcut or quodlibet.exe.

However, this command in cmd works: "\Program Files\Quod Libet\bin\python2w.exe" -c "import quodlibet.main; quodlibet.main.main()"

**Comment by lazka** [comment]
Thanks. Which Windows version and is this 32 or 64 bit?

Is there any output when starting "quodlibet.exe --debug" from the terminal?

**Comment by madewokherd** [comment]
32-bit Windows 10

I don't see any output from "quodlibet.exe --debug".

**Comment by lazka** [comment]
Thanks. I forgot that it's a separate exe on Windows. Please try
"quodlibet-cmd.exe --debug" instead.

**Comment by madewokherd** [comment]
Turns out quodlibet-cmd.exe works, with no arguments or with --debug.

But, I was able to get some output out of the regular exe. I had to redirect stderr. (When I ran it earlier I was redirecting stdout.)

D: 0.087: _init._init_gettext: LANGUAGE: u'en_US:C:en_US:C'

D: 0.087: _init._init_gettext: LANG: u'en_US'

D: 0.089: _init._init_gettext: No translation found in 'C:/Program Files/Quod Libet\\share\\locale'

D: 0.230: formats._misc.init: MimeType=application/x-flac;audio/aac;audio/aiff;audio/midi;audio/mp3;audio/mp4;audio/mpeg;audio/mpeg4;audio/mpg;audio/ogg;audio/vorbis;audio/wav;audio/wave;audio/x-aac;audio/x-aiff;audio/x-flac;audio/x-m4a;audio/x-midi;audio/x-mp3;audio/x-mpc;audio/x-mpeg;audio/x-ms-wma;audio/x-ms-wmv;audio/x-musepack;audio/x-oggflac;audio/x-speex;audio/x-tta;audio/x-wav;audio/x-wavpack;audio/x-wma;video/ogg;video/x-ms-asf;video/x-theora;video/x-wmv;

D: 0.230: formats._misc.init: Supported formats: aac, aiff, midi, mod, monkeysaudio, mp3, mp4, mpc, spc, trueaudio, vgm, wav, wavpack, wma, xiph

**
Gdk:ERROR:gdkdisplay-win32.c:941:_gdk_win32_enable_hidpi: code should not be reached

**Comment by lazka** [comment]
>  Gdk:ERROR:gdkdisplay-win32.c:941:_gdk_win32_enable_hidpi: code should not be reached

That's helpful. https://git.gnome.org/browse/gtk+/tree/gdk/win32/gdkdisplay-win32.c?h=3.22.5#n941

> Turns out quodlibet-cmd.exe works, with no arguments or with --debug.

Just to clarify, by "works" you mean there is output, or that the program starts successfully?

**Comment by lazka** [comment]
Reported upstream: https://bugzilla.gnome.org/show_bug.cgi?id=777031

For 3.8.1 we should set GDK_WIN32_DISABLE_HIDPI as a workaround.

**Comment by madewokherd** [comment]
quodlibet-cmd.exe starts correctly.

This may be my fault. I forgot I had checked "Disable display scaling on high DPI settings" in properties of quodlibet.exe, on the Compatibility tab. I unchecked it, and now it starts correctly.

In previous releases, enabling that setting had prevented Windows from adding blurry upscaling. In this release, I don't have this problem.

So, my apologies if this is an invalid bug, and thank you for your help in tracking this down.

**Comment by lazka** [comment]
> quodlibet-cmd.exe starts correctly.
>
> This may be my fault. I forgot I had checked "Disable display scaling on high DPI settings" in properties of quodlibet.exe, on the Compatibility tab. I unchecked it, and now it starts correctly.

This setting exposed a bug in GTK+, and it's already fixed upstream.

> In previous releases, enabling that setting had prevented Windows from adding blurry upscaling. In this release, I don't have this problem.

Good to hear. This means we can point users to disable that setting in case things are broken until we get a fixed gtk+.

> So, my apologies if this is an invalid bug, and thank you for your help in tracking this down.

Without your report the bug wouldn't have been fixed in gtk+, so thanks!
