### ISSUE TITLE
Plugin: Edit Embedded Images, popup menu problem

### ISSUE THREAD

**Issue by goxaxa** [quodlibet/quodlibet#2187]
* What did you try to do?
From the File System view,
R-click track, select "Plugins", select "Edit Embedded Images"

I wanted to use the "Edit Embedded Images" plugin to
1. Embed an image into a track, and
2. Remove an unwanted image from a track

* What did you expect to happen?
The image is added or removed from the track.

* What did happen instead?
When I select "Edit Embedded Images" the usual popup menu does not appear (a small, narrow empty box appears).

* Which version of Quod Libet?
3.8.0

* Which operating system including version (Ubuntu 14.04, Win7, Debian sid, ...)?
Fedora 25.
This plugin was working OK on Fedora 24.

**Comment by urielz** [comment]
I can confirm that the plugin is working fine on OS X 10.11.6 QL 3.8.0

**Comment by declension** [comment]
Can't replicate either here.

@goxaxa did you get any debug logging (you can run with `--debug` to get this).

**Comment by goxaxa** [comment]
When I run with --debug and select the small, narrow, empty popup box I get:

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

One major change from Fedora 24 to Fedora 25 is that Wayland has replaced the X Server,
so maybe the bug is related to this. But it is strange since all the other popup menus seem to work OK.

**Comment by lazka** [comment]
> One major change from Fedora 24 to Fedora 25 is that Wayland has replaced the X Server,
> so maybe the bug is related to this.

that seems likely, I don't think I've tested that part under wayland yet.

You should be able to force xwayland by starting with "GDK_BACKEND=x11 quodlibet"

**Comment by goxaxa** [comment]
Yes, when I run
$ GDK_BACKEND=x11 quodlibet
the "Edit Embedded Images" popup menu works fine.
So it looks like it must be a Wayland backend problem.

**Comment by lazka** [comment]
>  So it looks like it must be a Wayland backend problem.

Thanks for testing

**Comment by cdfa** [comment]
I'm having the same issue, but I'm not using Wayland.
`uname -or`: `4.19.59-1-MANJARO GNU/Linux`
`xdpyinfo | grep version`:
```
version number:    11.0
X.Org version: 1.20.5
```
`echo $XDG_SESSION_TYPE`: `x11`

**Comment by declension** [comment]
Can anyone re-test this with current `master`?

**Comment by cdfa** [comment]
It's working for me :smile: . It's great to finally see some work on this!

**Comment by goxaxa** [comment]
The original problem I reported, which was a problem when using Fedora 25 Linux + Wayland + quodlibet 3.8.0, no longer occurs on Fedora 31 Linux + Wayland + quodlibet 4.2.1. Maybe Wayland was updated and fixed the problem, I don't know.

But the problem does occur for me with Fedora 31 Linux + X11 Server + quodlibet 4.2.1. So it looks like the problem switched over from Wayland to the X11 Server.
(I've not been able to re-test with the current quodlibet master)

**Comment by CreamyCookie** [comment]
@goxaxa Did you get the chance to test with Quod Libet 4.4.0?

**Comment by goxaxa** [comment]
I tested with
Fedora 33 Linux + Quod Libet 4.4.0 + Wayland (or x11)
and it is working OK.

**Comment by CreamyCookie** [comment]
@goxaxa Thanks! Feel free to comment here (or create a new report) if it comes up again.
