### ISSUE TITLE
Unclear strings

### ISSUE THREAD

**Issue by Mellthas** [quodlibet/quodlibet#2189]
While translating Quod Libet I couldn’t find how these strings are used:

* editing (../quodlibet/qltk/edittags.py:196 … ../quodlibet/qltk/tagsfrompath.py:73)
* conducting (../quodlibet/util/tags.py:79)
* New %s (../quodlibet/qltk/data_editors.py:118)

"conducting" seems to be the noun (like "arrangement" and "composition" etc.) but that confused me quite a bit at first.

Translator comments might be helpful here.

**Comment by lazka** [comment]
uh, the first one is config.gettext getting marked as translatable :/

**Comment by lazka** [comment]
I hope it's clearer now

**Comment by Mellthas** [comment]
Thanks! Left a comment on the comment commit ;-)
