### ISSUE TITLE
Untranslatable strings in plugins

### ISSUE THREAD

**Issue by Mellthas** [quodlibet/quodlibet#2190]
The following plugin-related strings are not translatable:

* Play Count Equalizer: "Prefer less played" in the shuffle menu
* Gajim Status Message: "Patterns", "Accounts", "Add '[paused]'", "online", "offline", etc. in the settings pane

**Comment by Mellthas** [comment]
Also:

* Edit Playcount: "Multiple files selected. Counts will be incremented" in the edit dialog

**Comment by declension** [comment]
Thanks
