### ISSUE TITLE
Audio stutter on Internet radio station

### ISSUE THREAD

**Issue by aksarkar** [quodlibet/quodlibet#2191]
http://audio-ogg.ibiblio.org:8000/wcpe.ogg

The audio stutters every several seconds. This doesn't happen when playing the stream using mpv.

Arch Linux
quodlibet 3.8.0

**Comment by lazka** [comment]
In File>Preferences>Playback you can increase the buffer duration. mpv seems to use something like 5 seconds by default while QL defaults to 1.5.

**Comment by lazka** [comment]
I've doubled the default buffer duration.
