### ISSUE TITLE
Sort by column appears to not work anymore

### ISSUE THREAD

**Issue by thisfred** [quodlibet/quodlibet#2196]
On master, up to date as of now, clicking on a column header in the search view does not sort the entries by that column anymore (or at least not in the expected sort order at all). Clicking twice does reverse the results, but again, for title, it's not sorted alphabetically, for date fields they are not sorted by time, etc.

**Comment by declension** [comment]
Replicated

**Comment by thisfred** [comment]
Awesome, thank you for another amazing turnaround!
