### ISSUE TITLE
Previous doesn't work on Internet Radio sources

### ISSUE THREAD

**Issue by somini** [quodlibet/quodlibet#2198]
The "previous" action doesn't work for Internet Radio sources, when the station is playing. If the station is connecting the button works, so as a workaround I can click next and quickly hit previous to get to the previous station.

I tested the menubar, the keyboard shortcut and the MPRIS interface.

**Comment by lazka** [comment]
Confirmed, thanks.

**Comment by somini** [comment]
I recently found a workaround. If you stop playback and hit previous, it correctly gets to the previous station.
