### ISSUE TITLE
CSV import plugin

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#220]
Original [issue 220](https://code.google.com/p/quodlibet/issues/detail?id=220) created by yyquest on 2009-06-13T13:56:29.000Z:

Hi,

I am currently tagging my music files (mp3) using foobar2000 v0.9.6.7,
under Wine on an Ubuntu 64bit box. As I understand, foobar2000 writes both
id3v1 and id3v2.4. All of the files I am tagging has a date field of the
form yyyy-mm-dd. After tagging, the date fields remain blank when I import
the mp3 files into quod libet. By the way, when I open these mp3 files
using Ex Falso, the date tag is similarly missing. However, when the same
mp3 files are imported into Easytag, all of the tags are there (under
id3v2.4 section).

My question is: what tags is quod libet reading, and is there anything I
can do (as a user, not a developer, sorry) to display my date tags
correctly? As I am actually tagging quite a number of files by importing
csv files, manual entry of dates is something I would like to avoid if
possible.

Thanks a lot!

**Comment by CreamyCookie** [comment]
Part of this was closed with 533fe17, the other part is basically done with the Import/Export Metadata plugin AFAICS.
