### ISSUE TITLE
Filter function (e.g. max, min) doesn't work correctly with lastplayed

### ISSUE THREAD

**Issue by CreamyCookie** [quodlibet/quodlibet#2200]
![screenshot from 2017-01-15 14-29-23](https://cloud.githubusercontent.com/assets/3063858/21962945/a9bac7f8-db30-11e6-9076-90bdaba8db33.png)

Note that "Mittwoch" is German for "Wednesday".

The part of the filter / search that doesn't seem to work is `#(lastplayed:min > 9 month ago)`. Unless I'm missing something, the selected album should not be there, since all songs have been played recently. 

Ubuntu 16.04
Quod Libet 3.8.0
Python: 2.7.12
Mutagen: 1.36
GTK+: 3.18.9 (X11)
PyGObject: 3.20.0
GStreamer: 1.8.2.0

**Comment by declension** [comment]
Quite a query there :)

I first thought that's actually correct, as the minimum _time_ for that album (some time on Wednesday) is indeed larger (newer) than nine months ago but now I see that it seems to be the duration after all `#(lastplayed < 7 days ago)` is the standard _recently played_ filter.

It does feel like there's a bug with the aggregates. Testing here is proving hard either way though; remember that a min for the timestamps is often 0 (i.e. 1970) which can be confusing.

@CreamyCookie perhaps you can try experimenting with the Python Console plugin: select the album you think is buggy and use the new(ish) `col` variable in the console, e.g. `col('~#lastplayed:min')` to see what the results for the _collection_ are coming out as. It can sometimes be quite helpful.

**Comment by CreamyCookie** [comment]
> it seems to be the duration after all #(lastplayed < 7 days ago) is the standard recently played filter.

It's a bit unintuitive that `~#lastplayed` returns a Unix timestamp of when the song was last played, but in a query it's the duration since it was last played. 

Maybe `#(lastplayed in 7 days)` would be more intuitive, as then to you'd immediately know that in this context it's a duration. Then when you want to find only the songs that haven't been played in the last 7 days (i.e. `#(lastplayed > 7 days ago)`), you'd just negate the query.

> perhaps you can try experimenting with the Python Console plugin

Good idea! Haven't used it before, but that's a pretty useful plugin for debugging. Here's the output:

```python
>>> col('~#lastplayed:max')
1484149887
>>> col('~#lastplayed:min')
1484148684
>>> import datetime
>>> datetime.datetime.utcfromtimestamp(int('1484148684'))
datetime.datetime(2017, 1, 11, 15, 31, 24)
>>> col('title')
u'Alice\nBread and Butterflies\nLost\nUnBirthday'
```

That seems correct.. .

> remember that a min for the timestamps is often 0 (i.e. 1970) which can be confusing.

True! That also explains why `#(lastplayed > 9 month ago)` returns albums where `lastplayed` is "Never" for all songs. On it's own that seems kinda weird, but when one considers that it calculates the duration from 1970 to today, and compares that to the 9 month duration, it does make sense.

**Comment by declension** [comment]
Agree it's super confusing in some situations. Actually, in a very similar way to `find -atime +123` etc on the CLI.

In terms of this bug, we might try replicating with `:max` as it's at least a bit more predictable. That's also the default actually, so it might prove whether it's parser or expression evaluation related. 

> On the hand, it probably better to spend efforts on making sure it's more intuitive in #821 if that might become the default

Hmm yes #821, I should definitely get back on to that! Just need a few spare,,, _weeks_ to finish off all these other tickets first... :grimacing:

**Comment by CreamyCookie** [comment]
> In terms of this bug, we might try replicating with :max as it's at least a bit more predictable. That's also the default actually, so it might prove whether it's parser or expression evaluation related.

Good point!

> Hmm yes #821, I should definitely get back on to that! Just need a few spare,,, weeks to finish off all these other tickets first... :grimacing:


It's great idea! The current syntax isn't really that... beautiful, nor is it self-explaining. It works, but of course there are some things it can't do (like ORDER BY). But yeah, it really isn't critical, so it doesn't matter if it takes even a few weeks/months more. :)

**Comment by slosd** [comment]
I just created a pull request to fix this issue. 

The problem is that tags with functions are not identified as "time tags" which then produces wrong results. This also explains why queries like `lastplayed:max > 1 month ago` and `lastplayed > 1 month ago` return different results even though `max` is the default function for `lastplayed`.
