### ISSUE TITLE
Wrong song is played when changing songs while the song is changing

### ISSUE THREAD

**Issue by rosslagerwall** [quodlibet/quodlibet#2203]
Suppose song A is playing and the next song to be played is song B.
If I double click on song C as A ends and changes to B, the 'Now playing' song is shown as C but it actually still plays B. It should play C instead.

This is quite easy to reproduce - just double click on a different song exactly when a song ends.

I'm using 3.8.0 on Arch Linux 64 bit.

**Comment by lazka** [comment]
Thanks. That's a known problem but I currently fail to find the issue (too many..)

**Comment by rosslagerwall** [comment]
OK, thanks. Feel free to close as a duplicate...

**Comment by spxxxk** [comment]
@lazka For your peace of mind, see #837.

**Comment by lazka** [comment]
@spxxxk thanks!
