### ISSUE TITLE
HTTPS Stream using Opus and FLAC don't play

### ISSUE THREAD

**Issue by CreamyCookie** [quodlibet/quodlibet#2207]
These streams don't seem to work in Quod Libet 3.8.1.

* https://chiru.no:8080/stream.opus (works in Firefox)
* https://chiru.no:8081/stream.flac (should stream in Firefox 51)

The Opus one seems to buffer indefinitely and the FLAC one loads the current artist and title, but there's no sound.

The aac stream does work: https://chiru.no:8080/stream.aac

(Opus and FLAC streams over HTTP do work.)

**Comment by lazka** [comment]
Thanks, filed upstream:

* https://bugzilla.gnome.org/show_bug.cgi?id=777738
* https://bugzilla.gnome.org/show_bug.cgi?id=777739

**Comment by lazka** [comment]
The flac one has been fixed upstream now: https://cgit.freedesktop.org/gstreamer/gst-plugins-good/commit/?id=0747b56f8e7f4731d67f8d13a4bdc453dde0fdf7

**Comment by lazka** [comment]
The opus one I can no longer reproduce. Either there was a fix in the meantime or the stream no longer triggers the bug -> Closing.
