### ISSUE TITLE
Move outside files to library folder when adding a folder

### ISSUE THREAD

**Issue by deshmukhs** [quodlibet/quodlibet#2216]
I have a large music collection that is organized in Artist/ Album structure.

When I want to add more tracks, I will like to keep my collection organized.

File -> Add a folder adds the files to the library but keeps them at the same location.

Any way to move (copy) the files to the library folder in the library structure?

**Comment by declension** [comment]
No this is not supported currently. It's recommended to use your file manager or terminal to do file management.
