### ISSUE TITLE
Track length displayed as zero

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#222]
Original [issue 222](https://code.google.com/p/quodlibet/issues/detail?id=222) created by eric.potash on 2009-06-15T00:22:44.000Z:

I have a couple of tracks whose length gets displayed as 0:00.  However,
they are several minutes long and play fine.  There is no error or debug
info printed when loading or playing the track and it is correctly
displayed elsewhere (totem, amarok).  I have attached an example.

**Comment by 07416** [comment]
@lazka I've encountered the same issue (please tell me if I should open a new issue as this one was resolved).

Length is displayed as `0:00` for some tracks and trying to switch tracks or albums during playback results in a crash. This results in a "crash loop" and the files must be removed from the library to recover. 
According to [MusicBrainz Picard](https://picard.musicbrainz.org/) the length for these files has been defined.

![tempsnip](https://user-images.githubusercontent.com/14923168/39640206-edf7a3ba-4fd2-11e8-8825-2eb6da59c44d.png)

example file:
[01 Piano Sonata No.3 in Bb, K.281, 1. Allegro.zip](https://github.com/quodlibet/quodlibet/files/1975218/01.Piano.Sonata.No.3.in.Bb.K.281.1.Allegro.zip)

**Comment by lazka** [comment]
@07416 fixed by de49a27d92eae hopefully

**Comment by 07416** [comment]
@lazka However, I don't understand how this track differs from the others — care to elaborate?

I would like to fix these albums (all from the same source) locally rather than waiting for the new QL release or building from source.

**Comment by lazka** [comment]
@07416 https://github.com/quodlibet/quodlibet/commit/7bb1213df698bdbe662cde74a2e1ba89b52595d9#diff-03e3b3c9b93ca58e0207588491c4efffL37

The plugin to fix it is sadly broken in 4.0, due to an oversight in the Python 3 port, so I don't know an easy way, at least on Windows.
