### ISSUE TITLE
Queue only plugin doesn't work

### ISSUE THREAD

**Issue by aksarkar** [quodlibet/quodlibet#2223]
Double-clicking a song in the browser does not put the song in the queue, instead it starts playback immediately.

When the queue is emptied, playback continues with the first song in the current browser view.

Quod Libet 3.8.1
Arch Linux

**Comment by declension** [comment]
Play Order plugins have been refactored / rethought a while back.

The "Queue Only" plugin conceptually doesn't fit that well as a "Shuffle" _or_ a "Repeat" play order (the two newly distinct types); it's currently implemented as a Shuffle Plugin.

So you just need to select this order (bottom left) instead of _Random_ / _Prefer higher rated_ etc.

**Comment by aksarkar** [comment]
This still happens when queue only is selected in the playback order.

**Comment by pschwede** [comment]
I can reproduce in QL 3.9

**Comment by declension** [comment]
I can't replicate on `master`.

Is shuffle mode on (as well as the _Queue Only_ plugin selected)?

**Comment by aksarkar** [comment]
I checked out and built revision 728750e7e using cower.

In the GUI, shuffle mode is not on (according to the button state).

According to ~/.quodlibet/config:

    order_shuffle = shuffle

This doesn't change when I toggle shuffle mode (and leave it off) and exit quodlibet.

After deleting ~/.quodlibet/config, restarting, re-enabling Queue only.

     shuffle = False
     shuffle_mode = Queue Only

But again, double-clicking songs starts playback, hitting next moves to next track in current browser.

**Comment by declension** [comment]
Thanks @aksarkar 
Sounds like the button is not having any effect in your UI.

Presumably if you try the other shuffle modes, they _also_ exhibit this problem (i.e. _no_ shuffle mode can be used?

**Comment by aksarkar** [comment]
I see my mistake: turning shuffle mode on makes this work. This terminology is confusing, as you pointed out earlier.

The funniness with my original config is because the config file was generated by an older version of quodlibet.
