### ISSUE TITLE
recreating or deleting a library

### ISSUE THREAD

**Issue by Sugarbear1965** [quodlibet/quodlibet#2229]
I am having an issue with a music library I have created using the latest version of quodlibet.  When I go to change the library directory, it keeps pointing back to the old library.  When I delete the program and reinstall, again the old library appears.

How do I edit or delete the old library?

Forgot to mention,   I am using the latest version of Mac OS-X and I am an average user.  Step by step how to answers will work the best for me

**Comment by lazka** [comment]
By library do you mean the filesystem paths you can edit under "Preferences>Library>Scan Directories"?

**Comment by lazka** [comment]
Answering the following questions might make it clearer:

* What did you try to do?
* What did you expect to happen?
* What did happen instead?

**Comment by Sugarbear1965** [comment]
Yes.  This added the files to the library, but I noticed too many files from other folders in that location were being added so I refined my search to a specific folder and performed a new scan.  This did not remove any of the files from the first scan.  When I tried uninstalling the program to delete all of previous settings and files installed by the program installation and then reinstalling the program as a new program,  all of the previous settings remained including the old library and files.  How do I correct this?  I am sure I will need to manually delete a database XML file somewhere.  What do I need to do?

On February 11, 2017, at 1:48 AM, Christoph Reiter <notifications@github.com> wrote:

By library do you mean the filesystem paths you can edit under "Preferences>Library>Scan Directories"?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/quodlibet/quodlibet","title":"quodlibet/quodlibet","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/quodlibet/quodlibet">https://github.com/quodlibet/quodlibet</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@lazka in #2229: By library do you mean the filesystem paths you can edit under \"Preferences\u003eLibrary\u003eScan Directories\"?"}],"action":{"name":"View Issue","url":"<a href="https://github.com/quodlibet/quodlibet/issues/2229#issuecomment-279128280">https://github.com/quodlibet/quodlibet/issues/2229#issuecomment-279128280</a>"}}}

**Comment by declension** [comment]
If you want to remove **all** your settings, you can delete the `.quodlibet` folder (note the dot) in your home directory.

**Comment by lazka** [comment]
> Yes. This added the files to the library, but I noticed too many files from other folders in that location were being added so I refined my search to a specific folder and performed a new scan. This did not remove any of the files from the first scan. 

That's expected, tje paths listed there are just for finding *new* songs.

1) Show all songs in the songlist
2) cmd+a to select all
3) right click -> remove from library
4) "Main menu -> File -> Scan library" to find all songs in the library scan dirctories

**Comment by Sugarbear1965** [comment]
Nick,

Not finding the .quodlibet file anywhere.  Sounds like it may be a hidden
file.  I am running MacOS Sierra 10.12.3.  Have searched the Home folder,
library, and system folders.  No such file.  Where do I need to search?

**Comment by Sugarbear1965** [comment]
Christoph Reiter,

That seemed to work.  Tried once before and it didn't work at all.  Now
correct files are showing up.  Thanks.

**Comment by lazka** [comment]
Yeah, it's hidden in finder. You can either reach it through the terminal (and execute "open .") or look on google for how to show them in finder.
