### ISSUE TITLE
Scan: AlbumLibrary raises KeyError

### ISSUE THREAD

**Issue by erixtekila** [quodlibet/quodlibet#2230]
Hi team,

My env : OSX 10.11.6

Here is an attached crash report.
[Dump_20170211_123753.txt](https://github.com/quodlibet/quodlibet/files/768373/Dump_20170211_123753.txt)
It seems to belong to the library scan ?…

**Comment by lazka** [comment]
```
Traceback (most recent call last):

  File "site-packages/quodlibet/library/libraries.py", line 355, in __removed
```

Thanks. No idea at the moment.

**Comment by declension** [comment]
@erixtekila does this happen every time?

**Comment by urielz** [comment]
Using 10.11.6 as well. I've never encounter this error in 3.8.1

**Comment by lazka** [comment]
We'll have to wait for a sentry report with some more context, or some other way to reproduce.

Given the current information we can't do anything sadly.
