### ISSUE TITLE
Cannot select "comment" field to be shown in a column

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [quodlibet/quodlibet#2233]
Quodlibet allows to select to display in the grid view any column except for the "comment" one.
Why is it special?
Is this a bug or by design?

**Comment by pschwede** [comment]
Untrue. There are many more tags that cannot be chosen. However, you can choose *any* tag for your grid view in

**Comment by DavidPerezIngeniero** [comment]
Thanks, that solves it.
