### ISSUE TITLE
Filesystem browser doesn't restore last open folder

### ISSUE THREAD

**Issue by alan12345678** [quodlibet/quodlibet#2234]
I've recently switched to Manjaro and have to say that QL runs even better (than it did on Fedora). I have one odd issue. Note that because I'd heavily customised all my browser display prefs, I backed up my .quodlibet folder and copied it back under my home directory after installation.

Whenever I boot up, and QL boots with the session minimised into the system tray, it is always pointing to the exact same music folder in the file browser, despite my having last played very different album/tracks.

It might simply be a case of deleting some temp file or cache? I looked at the local "config" file and note that there is an entry written there for this same "wrong" album. I'm assuming this should get overwritten? Or do I simply delete it and let it recreate?

**Comment by declension** [comment]
Thanks. Presumably this was working before the change of OS?

Also, what's that exact config entry (or at least the key)?

**Comment by alan12345678** [comment]
Yes, this worked fine before. From my local config file I have the following, but can post the complete (pastebin?) if you wish:

    filesystem = /home/alan/Music/Leonard Cohen/The Essential Leonard Cohen/Disc 1
    filesystem_pos = 0.37380952381

**Comment by alan12345678** [comment]
I thought the following further info might help. Not saying I've fixed it, or know exactly what the problem is/was:

Was getting very fed up with additional problems occurring such as QL not starting minimized. Small thing but annoying.

I decided to delete the local "config" file. After a restart, I fuond the file had been recreated _exactly the same_ i.e. wrong restore state etc.

I realised that in my backups - on a physically separate drive, but mounted on startup - was a complete .quodlibet folder. I deleted this. I then stopped QL on a particular song and then manually exited the program (as opposed to "exit/minimize to tray") and then restarted the computer.

Now, not only does it restore the correct folder, but it has even stored the "paused" state of the player part way through a track, which is behaviour I've never even seen before :0)

**Comment by declension** [comment]
Great, sounds like it's fixed then (and yes the current track position is persisted too, as of quite a while ago now).

**Comment by alan12345678** [comment]
Well... yes and no. While this may turn out to be not strictly a QL issue after all, there's more (!).

Yesterday my machine shut off with no warning (I suspect cat hair, so out came the hoover). After reboot, QL had again gone back to starting non-minimised, and the current track not stored.

So I did a bit of experimenting, and it seems that this has something to do with the option in (my case) Manjaro, where one specifically asks that QL be added  to the list of programs stored in the session and restored on next boot.

That said, overall the issues have mostly gone away :0)

**Comment by declension** [comment]
OK, thanks, closing. Re-open if you find anything QL-specific.

**Comment by lazka** [comment]
``quodlibet --start-hidden`` should work

**Comment by alan12345678** [comment]
sorry to dim! yes, where do I specify this?? I'm not starting it from terminal/cl  I currently have it added to the session manager to auto-start. But where can I add this parameter? I seem to recall doing a similar thing to my terminal to make it dropdown...

Thanks for the help! :)
