### ISSUE TITLE
Editing features are disabled when editing tags on KDE

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [quodlibet/quodlibet#2235]
Steps to reproduce:

1. Press Alt-Enter in order to see the tags of a song
1. I double click the value of a tag in order to edit it
1. I cannot select any text to copy it to the clipboard, by using the mouse or the keyboard.

It doesn't behave like a regular text edit field.

**Comment by pschwede** [comment]
Thanks, I didn't know about [Alt]+[Enter] :+1:

However, I cannot reproduce your problem in QL 3.9 (dev) but can copy/paste things normally.

**Comment by DavidPerezIngeniero** [comment]
I'm using Linux, KDE Neon 4.9.1 and QL 3.8.1

**Comment by declension** [comment]
I can't reproduce this either (on Ubuntu with GTK+ 3.20.9). 

Sounds like this is probably a KDE-specific issue.

**Comment by DavidPerezIngeniero** [comment]
If necessary, I can provide the song.

**Comment by DavidPerezIngeniero** [comment]
It's strange, it is the only app I have installed in my computer with this problem in a text field.  The search field works ok.

**Comment by lazka** [comment]
I can't reproduce with plasma from arch.

**Comment by DavidPerezIngeniero** [comment]
Strange.  KDE Neon must have little bugs, as this is the distro that KDE developers use more on a daily basis.

**Comment by DavidPerezIngeniero** [comment]
Tried with OpenSuse Leap 42.1 in a Plasma desktop and it works.

**Comment by lazka** [comment]
Maybe a theme issue? Try selecting a different theme using the theme switcher plugin in QL.

**Comment by CreamyCookie** [comment]
@DavidPerezIngeniero Is this still an issue? Can't reproduce here either. (Kubuntu 18.04)

**Comment by CreamyCookie** [comment]
Closing this for now as `Can't reproduce`. Feel free to comment here if the issue re-appears in the latest version.
