### ISSUE TITLE
Only title tag can be entered in AAC files

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [quodlibet/quodlibet#2237]
I have an .acc file with no tags.
I press Alt-Enter, and I add a tag.  
A combobox allows to select the name of the tag.
A textfield allows to enter the value.
The problem is that as the name of the tag, only "Title" is allowed.
I'd like to enter the album, artist, ....

**Comment by DavidPerezIngeniero** [comment]
I attach a screenshot.
![image](https://cloud.githubusercontent.com/assets/6008104/22865798/6142793e-f16b-11e6-9892-ceb6aef3dc58.png)

**Comment by pschwede** [comment]
How about clicking that combo box?

**Comment by DavidPerezIngeniero** [comment]
Only the title can be selected.

**Comment by lazka** [comment]
Yeah, aac files have no official tagging format. For all files where we can't save tags to the file we just save the title in the database.

Some programs use ID3 tags, but I wasn't sure how much that breaks so I didn't implement it.

I'd recommend to put it into a MP4 container:

```
ffmpeg -i input.aac -codec: copy -movflags +faststart ouput.m4a
```

**Comment by DavidPerezIngeniero** [comment]
OK, I'll try and let you know.

**Comment by DavidPerezIngeniero** [comment]
Confirmed that it works after converting to .m4a.
Thanks for the useful suggestion. :-)
