### ISSUE TITLE
Allow queries to include other (named) queries

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [quodlibet/quodlibet#2238]
I can make a named search (smartlist) based on the inclusion in a playlist, but not on the inclusion in another smartlist.  This would be a convenient feature for writing complex smartlist and reuse of complex expressions.

**Comment by declension** [comment]
See slightly related #809

**Comment by DavidPerezIngeniero** [comment]
Thanks declenasion.  It is related, but I think what I'm asking for, is simpler to implement.

**Comment by ptitjes** [comment]
@DavidPerezIngeniero I don't get how this is different from `@(saved:...)` queries ?

**Comment by DavidPerezIngeniero** [comment]
I didn't know about the feature you mention.  Thanks for pointing this out.  Where can I find documentation about the syntax?

**Comment by ptitjes** [comment]
Hmm, I think it is there since 3.6 but not yet documented... I found about it while looking in the code :(

So let me explain it to you. When you save a search query under the name "FooBar" (using the "Edit saved searches..." item in the drop-down at the right of the query text box), you can then use it in another query:
```
@(saved:FooBar)
```

And you can mix with other stuff as usual, say:
```
&(@(saved: FooBar),#(bpm > 80),#(bpm <= 100))
```

**Comment by lazka** [comment]
It's the "Include Saved Search" plugin providing this

**Comment by ptitjes** [comment]
Yeah, sorry, forgot to tell you that you must activate the plugin @DavidPerezIngeniero !

**Comment by DavidPerezIngeniero** [comment]
Cool.  That's exactly what I'm been asking for.  
I'll try later and let you know.

**Comment by DavidPerezIngeniero** [comment]
it would be a good idea to update the search documentation page.

**Comment by ptitjes** [comment]
@DavidPerezIngeniero Indeed ! If you feel like contributing to it,  that would be great :)

This particular documentation page is:
https://github.com/quodlibet/quodlibet/blob/master/quodlibet/docs/guide/searching.rst

**Comment by DavidPerezIngeniero** [comment]
OK!

**Comment by DavidPerezIngeniero** [comment]
Done https://github.com/quodlibet/quodlibet/pull/2282
