### ISSUE TITLE
Lyrics downloader pluggin

### ISSUE THREAD

**Issue by kellogsgit** [quodlibet/quodlibet#2241]
Dear all,

This is a brainstorming post, feel free to post your ideas.

As my first Python project, I would like to work on Lyrics.
My ideas are not clear how to retrieve .lic files using a pluggin.

Could be some kind of downloader (like cover-art), but I doubt that individual work can be valuable...

So I would prefer automation using API and collaborative work, using LyricsWiki.
This could be much powerful, as once your collection is tagged, lyrics can be retrieved automatically.

Is some kind of logic already implemented within Quodlibet ?

LyricsWiki has given permission to use MusicBrainz and conversely:
https://blog.musicbrainz.org/2010/02/25/lyricwiki-and-musicbrainz-integration

So we could think about embedding some kind of logic within Quod Libet to retrieve Lyrics artist ID from MusicBrainz and conversely connect to MusicBrainz to submit a LyricsWiki tag. Then we should be able to retrieve LyricsWiki Artist Lyrics tag using MusicBrainz. And finally query LyricsWiki.

Can we brainstorm around the idea of lyrics?

**Comment by kellogsgit** [comment]
Tagging the example of Prince Album: Prince. 

Added the following tags:
https://musicbrainz.org/release-group/5436e902-e53d-3ab8-82b7-3b96a04d6f40

Points to:
http://lyrics.wikia.com/wiki/Prince:Prince_%281979%29

It seems possible to tag individual songs using MusicBrainz "works", but no idea howto...

**Comment by lazka** [comment]
http://lyrics.wikia.com/wiki/LyricWiki:Permission

**Comment by declension** [comment]
Is this a duplicate of #54?

**Comment by kellogsgit** [comment]
Yes, this is a duplicate, closing.
