### ISSUE TITLE
Muting during playback when using Teamviewer

### ISSUE THREAD

**Issue by ApolloLV** [quodlibet/quodlibet#2242]
Environment:
using version 3.8.1

Supported formats: AAC, AIFF, ASF, FLAC,
MIDI, MOD/XM/IT, MPEG-1/2, MPEG-4,
Monkey's Audio, Musepack, Ogg FLAC, Ogg Opus,
Ogg Speex, Ogg Theora, Ogg Vorbis, Remote File,
SPC700, True Audio, VGM, WAVE,
WavPack

Audio device: GStreamer (pulsesink)
Python: 2.7.13
Mutagen: 1.36.2
GTK+: 3.22.7 (X11)
PyGObject: 3.22.0
GStreamer: 1.10.3.0

Steps to reproduce:
Open Teamviewer, establish a connection
Open Quodlibet
Start playing a song
Use skip button

Expected behaviour:
The next song should be played without being muted, as long as no user interaction with muting functionality occurs.

Actual behaviour:
The output volume is being preserved, but the "mute" checkbox is active. No sound is being outputted even though playback of the next song starts.

Reproducability:
I didn't restart yet, but in the current state this always happens.

**Comment by ApolloLV** [comment]
I started quodlibet on my side of the connection. Restarting fixed the problem, so I do not see much need to investigate this any further.

**Comment by lazka** [comment]
OK, thanks for the update.
