### ISSUE TITLE
Pluggin: Discogs marketplace

### ISSUE THREAD

**Issue by ffries** [quodlibet/quodlibet#2243]
Dear all,

I would like to brainstorm the idea of a Discogs marketplace pluggin for Quod Libet.

This is not a commercial project, which I am NOT getting paid for. Only I registered a computing exam dealing with Python and I need some practice on a real project in order to train in a pleasant way.

The Discogs pluggin is targetted at users (like me) who have CDs and ripped them all and would like to publish the information easily on Discogs without rescanning the collection and without physical access to the CD library. Besides, I think that such a project could boost Quod Libet popularity and bring in new talents.

Personally, I am back buying 10 to 20 CDs every month from cheap second-hand suppliers and I think 
digital ownership in FLAC (not renting) is the future. So I probably need to buy and sell CDs and I would like to be able to handle them all without manipulation of CDs except buying/selling CDs.

Marketplace means exporting CD information to Discogs AND buying/selling physical CDs of course, not the ripped files.

As for Discogs, the idea would be:

* Tag local Quod Libet with Discogs market place information : 
=>publish on Discogs: yes/no
=>for sale: yes/no
=>sales price of my CD
etc ...
So we probably need to invent some special tags and/or agree about them with Discogs.

* Update Discogs collection based on Quod Libet. i.e. export from Quod Libet to Discogs to make sure that Discogs is always up-to-date.

At first, to avoid any underlying database in Quod Libet, I would prefer to publish only information present locally in Quod Libet.

As a beginner in Python, I would iike to be mentored on Python issues by the community, if possible of course. If you previously discussed a Discogs marketplace pluggin, or if someone in the community is dealing with such issues, please let me know.

If you have any idea about the Discogs pluggin, please brainstorm. Before starting anything, we need to discuss about the specs and I wron't start anything that is not accepted no needed by the community.

Is there anything that you would like in this pluggin?

Kind regards,
Kellogs

**Comment by kellogsgit** [comment]
I had a very quick look and it seems that QL needs more internal support of MusicBrainz tagging library, which is only offered as a pluggin. We need very good support of MusicBrainz album ID as well as Discogs album ID, to make sure that the information is accurate.

IMHO it would be valuable to complete tagging entirely within QL. 

Also, I would like to have visual blending of covert art when no MusicBrainz ID is saved to file (as settings). Exemple Half Red: No LibmusicBrainz ID. Half Pink : no Discogs ID. Therefore, users may catch immediatly which CDs are not tagged correctly.

**Comment by kellogsgit** [comment]
So let's go here:
https://github.com/quodlibet/quodlibet/issues/2236

**Comment by CreamyCookie** [comment]
Thanks!

Seems there's not much interest at the moment, so I'm closing this for now. 

Regarding MusicBrainz (which is great), there are already quite a [few reports](https://github.com/quodlibet/quodlibet/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+MusicBrainz) about improving support, but if there's something missing feel to create a new one.
