### ISSUE TITLE
Output track path on error

### ISSUE THREAD

**Issue by Meriipu** [quodlibet/quodlibet#2250]
I get some output on import errors in my terminal that I ran quodlibet from, but I have no idea which tracks caused it. 

As of now I think my only option is to try adding ranges of directories and gradually refining the range to find the directory with the tracks that causes the output.

My current output:

E: 23.373: formats._misc.MusicFile: monkeysaudio.py:50:__init__: AudioFileError: not a Monkey's Audio file
E: 23.384: formats._misc.MusicFile: __init__.py:391:__init__: AudioFileError: can't sync to MPEG frame
E: 23.396: formats._misc.MusicFile: __init__.py:391:__init__: AudioFileError: can't sync to MPEG frame
E: 23.408: formats._misc.MusicFile: __init__.py:391:__init__: AudioFileError: can't sync to MPEG frame
E: 23.419: formats._misc.MusicFile: __init__.py:391:__init__: AudioFileError: can't sync to MPEG frame
E: 23.430: formats._misc.MusicFile: __init__.py:391:__init__: AudioFileError: can't sync to MPEG frame
E: 23.446: formats._misc.MusicFile: __init__.py:391:__init__: AudioFileError: can't sync to MPEG frame
E: 23.461: formats._misc.MusicFile: __init__.py:391:__init__: AudioFileError: can't sync to MPEG frame
E: 23.473: formats._misc.MusicFile: __init__.py:391:__init__: AudioFileError: can't sync to MPEG frame
E: 23.484: formats._misc.MusicFile: __init__.py:391:__init__: AudioFileError: can't sync to MPEG frame
E: 23.496: formats._misc.MusicFile: __init__.py:391:__init__: AudioFileError: can't sync to MPEG frame
E: 23.507: formats._misc.MusicFile: __init__.py:391:__init__: AudioFileError: can't sync to MPEG frame

It would be great to know which tracks caused this so I could open them in my file manager and try to troubleshoot/fix.

**Comment by lazka** [comment]
3.8.1 should display which files fail if you pass "--debug"

**Comment by lazka** [comment]
I'm always happy to look at files which don't work, just send to reiter.christoph@gmail.com

**Comment by Meriipu** [comment]
It turns out to have been .mpg videos, if that is relevant. 
the .ape file was leftover from sometime, I do not think I have any other .ape files.

--debug works great, thanks.
