### ISSUE TITLE
Allow custom ellipsizing for FS songlist columns

### ISSUE THREAD

**Issue by Meriipu** [quodlibet/quodlibet#2251]
Is there some way to change the way the path/fullname is split in the column?

When the column is too narrow to contain the entire string, I prefer it to display the last part of the path rather than both the beginning and the end. 

As it is now I only see the directory all my music is in (mostly identical for all tracks) in the left part,
and the filetype and name of the track but not the album/artist directory on the right. 

Would an option to change it to display as ".../artistalbum/01 - trackname.flac" be too specific?

**Comment by lazka** [comment]
Hm, this seems a bit too edge case for me to get its own option. Any thoughts from someone else?

@Meriipu: Given ~dirname, ~filename, ~basename. Assume you could use multiple columns, would changing of the default ellipsizing for any of the tags improve the situation?

**Comment by Meriipu** [comment]
The current ellipsizing in the middle of the full path looks cleaner, so it makes sense as a default.

I have it set to ellipse at the beginning of the path in my current build, so that I usually see the directory the file resides in and maybe one directory up, rather than just the filename + top level directories. This looks pretty unclean though.

I think what I would prefer is having the filename take a constant width, ellipsized in the middle if appropriate. That way the trailing slashes of the leaf-directories should line up -- and then also ellipsize the beginning of the path so that the directories closest to the leaf are likely to be visible.

This sounds pretty edge case to me though yes.

**Comment by CreamyCookie** [comment]
As the associated pull request was closest, I'm also closing this.

It definitely feels a bit too edge case though I fully understand the interest in improving the situation. Maybe there's even a way to make all parties happy without a setting. Anyway, thanks for the report!
