### ISSUE TITLE
Set delay on hover textfield

### ISSUE THREAD

**Issue by Meriipu** [quodlibet/quodlibet#2252]
I have my window manager set up to enable moving of windows by holding a key and dragging the window. 

This does not interact well with the almost instant context menus that activate when you hover a field with a too narrow column to contain the text in it.

Could an option to set a short delay on it be added?

**Comment by lazka** [comment]
There is an option in the "Advanced Preferences" plugin called "Disable Hints", which disables them.

What's the key you use for dragging windows?

**Comment by Meriipu** [comment]
super/the windows key

**Comment by lazka** [comment]
Thanks. We should probably hide the tooltip if super is pressed like we do for ctrl/shift atm
