### ISSUE TITLE
Playlists browser clears selection on track change if playlist is selected

### ISSUE THREAD

**Issue by Meriipu** [quodlibet/quodlibet#2253]
I do not know if it is intended, but in the playlist mode (ctrl+2) having disabled the behaviour of jumping to the playing song automatically seems to have no effect.

Regardless of if a different track further down in the list is selected or not, the currently playing track is in view, or track changes are automatic or manual - It jumps (shifts the view) to the next song.

**Comment by Meriipu** [comment]
I found a pretty silly workaround but it works

In the main view, add the ~Playlists column. Then just search for the playlist name.
It is still a bug though I think unless I have misunderstood something.

**Comment by Meriipu** [comment]
Is this intended behaviour? I have not used the playlist tab because of this.

**Comment by declension** [comment]
For me, the track _selection_ disappears on track change - though the currently playing highlight (in light grey on my theme) correctly moves to the new playing track. This _doesn't_ happen on the search browser, and is definitely a bug (possibly long-standing).

@Meriipu if that's _not_ what you meant please describe more exactly what's happening and what you're expecting (maybe with screenshots) and I'll update this

**Comment by Meriipu** [comment]
@declension it is kind of similar but not what I initially reported

So despite the option 
preferences>song list>jump to playing song automatically 
being disabled:
1) Go to playlist view
2) Select a playlist with enough songs to be able to scroll
3) Start playback of a song 
4) Scroll down so the playing song is not centered
5) Select "next track", let a song finish, or just click another track that is not in the center of the current view
6) the view should jump so that the next song is centered (despite this option being disabled)

**Comment by Meriipu** [comment]
I have been trying to look into this but it seems the list of songs in the playlists-browser are cleared and recreated each time a track finishes playing ?

So if this is the case, would a workaround be to store the last position (percentage of scroll-wise) in the list and then scroll to it?

I do not really understand the playlist browser. If you start playing a track by selecting it from the main browser, it seems a temporary playlist is constructed or something like that when you swap to the playlist view, but once a track finishes playing after having swapped to the playlist view, it gets removed from this temporary list
So the number of songs in the list gradually dwindle down to none if you remain in the playlist-browser after having started playing tracks from the main browser but without selecting an actual playlist after having swapped to the playlist browser (or something like that).

**Comment by Meriipu** [comment]
```
diff --git a/quodlibet/quodlibet/qltk/songlist.py b/quodlibet/quodlibet/qltk/songlist.py
index b7cc85758..bdb3ea066 100644
--- a/quodlibet/quodlibet/qltk/songlist.py
+++ b/quodlibet/quodlibet/qltk/songlist.py
@@ -832,6 +832,7 @@ class SongList(AllTreeView, SongListDnDMixin, DragScroll,
 
         # scroll to the first selected or current song and restore
         # selection for the first selected item if there was one
+        old_rect = self.get_visible_rect()
         if scroll or scroll_select:
             if restore_song is not None and restore_song is not model.current:
                 try:
@@ -849,6 +850,12 @@ class SongList(AllTreeView, SongListDnDMixin, DragScroll,
                     self.set_cursor(path)
                 self.scroll_to_cell(path, use_align=True, row_align=0.5)
 
+        if not config.getboolean("settings", "jump"):
+            x,y = old_rect.x, old_rect.y
+
+            print('scrolling to', x,y)
+            GLib.idle_add(self.scroll_to_point,x,y)
+
         # the song selection has queued a change now, cancel that and
         # pass the songs manually
         self.info._update_songs(songs)
```

This kind of works, except there is a short delay where it first scrolls to the specified cell (current behaviour), before scrolling to the saved exact position again, so the view will be a bit jumpy when scrolling despite ending up in the same position it was when the previous track ended. 

If I comment out the code for scrolling (the sortof large if-statement), the player will first scroll to the top of the list (first cell) before then jumping to the saved exact position, so it will still be jumpy.

If I do not make a delayed call to self.scroll_to_point, nothing seems to happen (I assume because the TreeView is not realized, as per the pygtk documentation http://www.pygtk.org/pygtk2reference/class-gtktreeview.html#method-gtktreeview--scroll-to-point  "The treeview must be realized before this method is called." ?)

songlist.py jump_to only seems to be called when the "jump" config-option is enabled, when a track finishes (either by skip or by reaching the end) -- both for the playlist and search browsers. 
It is not called when a track is manually selected. 
Even with the "jump" option on, only the playlist browser jumps when a new track is selected by double-clicking a track (this happens with the option off too). The search browser only seems to jump when the option is on and a track finishes or is skipped. 
Even with the "jump" option off, the playlist browser always jumps no matter how a track change happens. 

this all feels very confusing to make sense of

**Comment by Meriipu** [comment]
now, it seems like even playlists with duplicates act weird. When a duplicate starts playing, the track jumps to the last instance of it in the playlist.

**Comment by Meriipu** [comment]
Fixed.
