### ISSUE TITLE
Custom window title

### ISSUE THREAD

**Issue by Meriipu** [quodlibet/quodlibet#2254]
I would like my window title to be "title - artist", rather than "title - people"
I have not found a way to accomplish this.

**Comment by lazka** [comment]
In which scenario do you read the information from the window title?

Asking since in most environments you don't see the window title (gnome, windows, osx)

**Comment by Meriipu** [comment]
I use twm (or ctwm to be more specific), and iconified windows get their title set as the window title.

I find that the people-field of tracks tend to be pretty cluttered compared to the artist-field.

**Comment by lazka** [comment]
Hm, ok. I'm not sure if that is worth another option in the UI.

Note that ~people will first return artist anyway

**Comment by Meriipu** [comment]
It seems to still include a lot of people in the window title even when the artist field exists for me, somehow.

**Comment by lazka** [comment]
I meant that whatever gets include in ~people, artist should be at the start at least.

**Comment by Meriipu** [comment]
I think I understand, then.

Either way, for me being able to decide on whether to use ~artist or ~people would be enough -- the main issue being that ~people sometimes is a bit on the lengthier side of things. 
Although free-form customization of the sort that exists elsewhere in the client (for instance in the main display of the current track) seemed like a more general solution.

**Comment by ptitjes** [comment]
@lazka I do see the window title in Gnome... Am I not supposed to ?
I'd rather for the header bar to be filled with the player controls, but it is not. Just the plain bar with "title - people".

So I understand @Meriipu because it is very common that I have "That artist, Various Artists - That title"...
If not even more when I carefully modified the song's tag. Just saying!

**Comment by ptitjes** [comment]
@lazka Do you prefer that I implement #2272 with a hidden ("advanced") configuration or that I drop it completely ? Personally, I don't really care and I just did it to help :)

**Comment by lazka** [comment]
> @lazka Do you prefer that I implement #2272 with a hidden ("advanced") configuration or that I drop it completely ?

Advanced prefs sounds like a good compromise.

**Comment by ptitjes** [comment]
> Advanced prefs sounds like a good compromise.

OK, I'll rework it in that end.
