### ISSUE TITLE
Allow higher granularity tickrate [enhancement]

### ISSUE THREAD

**Issue by Meriipu** [quodlibet/quodlibet#2255]
Allow higher granularity tickrate, e.g updating seekbar every 0.2 seconds.

**Comment by Meriipu** [comment]
from some trying around, this replacement in qltk/tracker.py works for the waveform seek bar, but not the other two. I have no idea if it has any negative side effects beyond slightly higher cpu usage when the player is not iconified.
```
                #self.__id = GLib.timeout_add_seconds(1, self.__update)
                self.__id = GLib.timeout_add(250, self.__update)
```

**Comment by lazka** [comment]
Why do you need/want it?

**Comment by Meriipu** [comment]
It was purely for cosmetic purposes. I was looking at the waveform seek bar plugin, and I felt the movement in seconds was a bit jaggy.
