### ISSUE TITLE
Adding invalid/large files URLs as audio feed sources hangs quodlibet

### ISSUE THREAD

**Issue by nodiscc** [quodlibet/quodlibet#2257]
Hi, this problem happened after mistakenly trying to add a _webradio_ (icecast stream) to the _audio feeds_ browser. I should have used the Webradio browser, but mistakenly added http://ice.somafm.com/groovesalad as a new audio feed.

After confirming with the `+ Add button` in the `New feed` dialog, quodlibet hangs indefinitely (I had to `kill -9` it). By attaching strace to the quodlibet process it appears it performs an endless number of `recvfrom` calls.

Maybe a timeout/max filesize limit should be added to the audio feed browser. When the file at the specified URL exceeds that size/download takes too long, abort operation with an error (`The file at the specified URL is too large`).

Or perform mimetype recognition on the response headers and abort when it doesn't match valid feed mimetypes (`content-type: text/xml`) though I'm not sure all servers properly set that mimetype.

The timeout solution seems preferable.

**Comment by declension** [comment]
Replicated - thanks.
