### ISSUE TITLE
Waveform: add a HiDPI mode

### ISSUE THREAD

**Issue by ptitjes** [quodlibet/quodlibet#2258]
On my retina laptop, the waveform looks ugly.

I have code on my local repository that adds a third mode to the lowres/highres setting. This new mode enhances the number of values calculated and disables any averaging during rendering. The result is far more beautiful.

If you're OK with the idea, I'll a PR.

**Comment by lazka** [comment]
If it looks different on HiDPI then that's a bug.

If you just want it to be smoother we can

* fit a curve instead of the bars
* add spacing between the bars like soundcloud/dropbox do. so that it at least looks like it's not high resolution on purpose.

**Comment by ptitjes** [comment]
@lazka Thanks for your answer.

> If it looks different on HiDPI then that's a bug.

Nah, it does look no different from a rendering on a non-HiDPI display. The thing is it does not take benefit of the HiDPI display.

Let me more precise about it. The current drawing algorithm :

- does disable Cairo's anti-aliasing by doing `cr.set_antialias(1)`
- every coordinates given to the move_to/line_to calls are rounded to integers even the computed values for the waveform contain far more precision (remember that Cairo takes coordinates as float for the very reason that displays can be more precise than the coordinate system)
- the values are averaged in order to have one value per pixel (whereas HiDPI have far more displayed pixels per pixels of the coordinate system)

All in all, all (averaging) computations that does the drawing algorithm should be taken care of by Cairo itself.

**Comment by lazka** [comment]
Ok, whatever the improvement in that area, things I'd like to see:

* The display code should not depend on the sampling frequency of the audio file. If there are not enough samples we can interpolate. It's not like it adds any more useful information when sampling 100 times a second.
* We should try to get rid of any "high resolution" options, it should look acceptable by default.

If your fix is short enough and doesn't make things worse then that's fine in the mean time.

**Comment by ptitjes** [comment]
Then I'll modify my code in order to address both the HiDPI accounting (detecting it with widget.get_scale_factor() == 2) and your two concerns above.

So just to be sure : Currently the interval between points computed for the waveform is `length-of-file-in-nanosecond / max-points-from-config / linewidth`. I understand from your first point that you still want a fix number of points whatever the length of the soundfile. So I just get rid of the `/ linewidth`, right ?
