### ISSUE TITLE
Regex Substitution plugin is broken

### ISSUE THREAD

**Issue by spxxxk** [quodlibet/quodlibet#2260]
The regex entry doesn't show up after clicking "More options" in the edit tag windows.

Before:
![ql_not_collapsed](https://cloud.githubusercontent.com/assets/11503399/23222716/16625964-f929-11e6-96c4-f8b432c869f2.jpg)

After:
![ql_collapsed](https://cloud.githubusercontent.com/assets/11503399/23222729/20a62f68-f929-11e6-94f8-16f811a07b1c.jpg)

QL version: 3.8.99+8900~05c6d0e1b-0\~ppa0\~xenial

**Comment by lazka** [comment]
Works under debian sid, but confirmed under ubuntu xenial. Thanks

**Comment by ptitjes** [comment]
Works on Fedora too. Based on @frestr's comment in #2294, I guess it does not work on Arch.
What's the difference between GTK/QuodLibet on Ubuntu Xenial/ArchLinux vs Debian Sid/Fedora 25 ?

**Comment by frestr** [comment]
It does actually work fine on Arch too. I only experienced the issue on Ubuntu (Xenial). I'm not sure why this seemingly only affects Ubuntu. It may possibly be an upstream bug?
