### ISSUE TITLE
Meta key not working on OS X

### ISSUE THREAD

**Issue by loopernow** [quodlibet/quodlibet#2271]
Is this an issue for anyone else? Keyboard shortcuts requiring the meta key, such as for Add to Queue, do not work because quodlibet isn't recognizing the Command key. Alt/option key shortcuts work fine.

Quod Libet 3.8.1
OS X 10.11.6

**Comment by lazka** [comment]
@urielz might know

**Comment by davidSchlosser** [comment]
I have the same issue.

**Comment by urielz** [comment]
Yes. It used to work. Can't remember when it stopped working though...

**Comment by urielz** [comment]
@lazka it seems that all the shortcuts managed by if_accel (in /qltk/__init.py) are not working. The rest of the shortcuts (control, switch browsers, etc) work fine...

**Comment by lazka** [comment]
uh, ok, thanks.

**Comment by lazka** [comment]
yeah, is_accel is buggy. I wonder how this has ever worked..

**Comment by urielz** [comment]
I'm almost sure it worked. But I do use QL on Win and Linux so perhaps I'm wrong..
