### ISSUE TITLE
question - keyboard shortcuts help

### ISSUE THREAD

**Issue by urielz** [quodlibet/quodlibet#2281]
Is there a design reason why 'Help' > 'Keyboard Shortcuts' doesn't show all available shortcuts? If this is an oversight then I can complete it and do a PR...

**Comment by lazka** [comment]
I've focused on shortcuts not visible in menus afair.

**Comment by urielz** [comment]
Got it, makes sense.

**Comment by lazka** [comment]
We could add more of course, I was just worried that including all would make it confusing.

**Comment by urielz** [comment]
Personally I'd prefer to have all shortcuts there. I'll give it a shot and see how it looks.

**Comment by urielz** [comment]
@lazka if you don't mind me asking (I'm learning about this as I go)... is there a reason why you didn't use Gtk.Builder.add_from_file to read an XML file?

**Comment by lazka** [comment]
Mostly because we never used it in the entire code base and I wasn't sure about translations etc..

**Comment by urielz** [comment]
@lazka I tried adding sections to make it a bit more organized:

    w = Gtk.ShortcutsWindow()
    for section_title, groups in data:
        section = Gtk.ShortcutsSection(title=section_title)
        section.show()
        for group_title, shortcuts in groups:
            group = Gtk.ShortcutsGroup(title=group_title)
            group.show()
            for accel, shortcut_title in shortcuts:
                short = Gtk.ShortcutsShortcut(
                    title=shortcut_title, accelerator=accel)
                short.show()
                group.add(short)
            section.add(group)
            w.add(section)

    return w

with SHORTCUTS defined like this:

` SHORTCUTS = [
    (_("Section 1"), [
          (_("Main Window"), [
              ("<Alt>Left", _("Seek backwards by 10 seconds")),
              ("<Alt>Right", _("Seek forward by 10 seconds")),
              ("<Primary>L", _("Focus the search entry")),
          ]),
          ... etc ...
      ]),
      (_("Section 2"), [
        ... etc ...
      ]),
  ]`

It works except that the search functionality is broken (as you mentioned in the code). Is there a way around this without using XML? 

Btw this is mostly an excuse to learn python and familiarize myself with QL, your help/comments are a huge help. Thanks again.

**Comment by lazka** [comment]
`w.add(section)` is one level too much indented. And gtk complains about duplicates section names, seems like section_name needs to be passed.

```
    w = Gtk.ShortcutsWindow()
    for i, (section_title, groups) in enumerate(data):
        section = Gtk.ShortcutsSection(
            title=section_title, section_name="section%d" % i)
        section.show()
        for group_title, shortcuts in groups:
            group = Gtk.ShortcutsGroup(title=group_title)
            group.show()
            for accel, shortcut_title in shortcuts:
                short = Gtk.ShortcutsShortcut(
                    title=shortcut_title, accelerator=accel)
                short.show()
                group.add(short)
            section.add(group)
        w.add(section)

    return w
```

**Comment by urielz** [comment]
Thanks! Will play around a bit more with this..
