### ISSUE TITLE
Drop Ubuntu 14.04 support

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#2288]
Questions:

* It's currently the oldest supported, what would be the new "oldest"?
* What does it give us in terms of dependencies?

**Comment by lazka** [comment]
Previous issue: #1714

**Comment by lazka** [comment]
Supported:

debian jessie: 2018-05
ubuntu trusty:  2019-04
ubuntu xenial:  2021-04
openSUSE 42.1: Q2 2017
fedora: 24 still supported

With jessie being the oldest we have:

gtk: 3.14 (currently 3.10), would give us GtkFlowBox/GtkPopover
pygobject: 3.14 (currently: 3.12)
gstreamer: 1.4 (currently 1.2)

-----

conclusion: I'm for dropping support after the next release and adding a docker file for debian jessie first.

**Comment by declension** [comment]
+1 to ditching it 14.04

Worst case we can make another branch later and  backport / revert stuff...

**Comment by lazka** [comment]
OK, lets do it now.

**Comment by lazka** [comment]
#2290
