### ISSUE TITLE
album has duplicate songs

### ISSUE THREAD

**Issue by ambergrant** [quodlibet/quodlibet#2291]
I see many albums that list duplicate songs. One example is "The  Very Best of Cat Stevens." Every song on this album is listed twice in exactly the same way.  

1 Where Do the Children Play / Folk Pop / Cat Stevens / The Very Best of Cat Stevens / 3:53
1 Where Do the Children Play / Folk Pop / Cat Stevens / The Very Best of Cat Stevens / 3:53
2 Wild World / Folk Pop / Cat Stevens / The Very Best of Cat Stevens / 3:20
2 Wild World / Folk Pop / Cat Stevens / The Very Best of Cat Stevens / 3:20
...

I'm running Quod Libet on a MacBook Pro (15-inch, Mid 2010) Processor 2,4 GHz Intel Core i5 Memory 4 GB, OS X El Capitan version 10.11.6

The music files are stored on a shared disk (Western Digital MyCloud) mounted using SMB protocol.

I have seen this problem with Quod Libet versions 3.8.0 and 3.8.1.

![2017-03-02 album cat stevens](https://cloud.githubusercontent.com/assets/26147631/23521149/219b9ec0-ff7e-11e6-8bef-d62a30cf8f4b.jpg)
![2017-03-02 folder contents](https://cloud.githubusercontent.com/assets/26147631/23521159/2ac4dda4-ff7e-11e6-8fb0-4b230121c039.jpg)
![2017-03-02 song tags](https://cloud.githubusercontent.com/assets/26147631/23521182/34bb45e6-ff7e-11e6-8ffd-fbee2b829ad7.jpg)

**Comment by zsau** [comment]
Try adding a column in QL with the tag `~dirname`, to see where QL thinks these files are. Maybe there's some symlinking involved?

**Comment by ambergrant** [comment]
Brilliant! But frustrating. Yes, the songs are in two different locations. But in the preferences there is only one directory listed in the Library settings. How / why is QL searching other directories on my computer? 

Thanks!

![2017-03-02 directory](https://cloud.githubusercontent.com/assets/26147631/23522878/f1bdcf32-ff84-11e6-8817-f108d0f0a19e.jpg)
![2017-03-02 preferences library](https://cloud.githubusercontent.com/assets/26147631/23522889/fab24834-ff84-11e6-8582-712d7fd82aa3.jpg)

**Comment by zsau** [comment]
That "Scan Directories" setting only allows QL to find new songs as they're added; the ones already in your library stay there regardless.

As to how they got there in the first place, is it possible you added them twice at some point, via different paths? If not, it could be that QL got confused by some combination of symlinks and/or mount points. If you can reproduce the behavior from an empty library, that would be very helpful.

To fix your library, sorting by ~dirname should let you select all the duplicates at once.

**Comment by ambergrant** [comment]
Yes, it's possible that I had added this folder at some point and then removed it. I will delete the "songs" file and start over. Will update if bug re-occurs. Thanks for all your help.

**Comment by lazka** [comment]
I could be that the behavior regarding resolving of symlinks changed and after an update to a newer version they got detected as new and added again. (I cleaned up that code in 3.8, so either I added a bug or fixed one.. ;)

If you remove all of them and rescan, only one should be added back (note that this will remove ratings/statistics for those songs)

**Comment by ambergrant** [comment]
I saw this problem is both 3.8.0 (my first installed version) and 3.8.1 so not likely a difference between versions.

**Comment by lazka** [comment]
Oh, that rules out my guess :( If you figure out under which circumstances the duplicates appear, please tell us.

**Comment by ambergrant** [comment]
After I removed the "songs" file and rebuilt the library the one album I mentioned--The Very Best of Cat Stevens--shows no duplicates. It appears that the problem is resolved. Thanks for your quick help!

Just one note--I am a new user of Quod Libet and it was confusing for me that removing a directory from the Preferences:Library:Scan Directories does not remove songs from the library. 

Overall, great product and I look forward to getting to know it better!

**Comment by declension** [comment]
@ambergrant are you happy for us to close this ticket then?

**Comment by ambergrant** [comment]
Sure, close the ticket--problem solved! Thanks for your quick support.

Cheers,
Amber

**Comment by declension** [comment]
Thanks

**Comment by GaryReg** [comment]
Great Post. Cleared my duplicates by rescanning. Somehow QL had picked up iTunes folders with duplicate albums/ songs.
