### ISSUE TITLE
KDE: Quod Libet does not react on pressed Media Keys

### ISSUE THREAD

**Issue by pschwede** [quodlibet/quodlibet#2298]
Title says it. KDE seems to have some own way of telling apps about pressed Play and Stop keys.

**Comment by lazka** [comment]
Does installing libkeybinder3 help?

**Comment by pschwede** [comment]
Sorry, no. I think KDE catches the events.

**Comment by lazka** [comment]
OK, thanks. Any info welcome...

Maybe they forward the events over MPRIS? Try enabling the QL mpris plugin.

**Comment by lazka** [comment]
Searching around indicates that MPRIS is the solution (untested..), maybe we should move MPRIS into the core.

**Comment by ptitjes** [comment]
Or make it an always enabled plugin...

**Comment by pschwede** [comment]
You mean, an OS dependent plugin?

**Comment by ptitjes** [comment]
@pschwede MPRIS is a standard protocol for media players, that runs over DBus message system (a kind of inter-process communication bus). In that protocol, messages on the bus are of the kind "play/pause the music", "go to next song", etc. And also there can be feedback messages, from the media player, on the same bus like "the song 'It ain't what you do' has started (length: _, artist: _, ...)", etc.

What @lazka is suggesting is that KDE maybe exclusively transmit the entirety of the media key presses through MPRIS for applications to consume. Whereas Gnome, for instance, uses MPRIS for the widget in Gnome Shell's center menu and transmits media key presses through another channel (also DBus-based by the way).

QuodLibet *already* handles this MPRIS protocol through its "MPRIS D-Bus Support" plugin.
So you should try to activate this plugin in the plugin window, as @lazka asked you, and then report here if that fixed the problem or not.

**Comment by pschwede** [comment]
That works! Thanks for clearing things up!

**Comment by lazka** [comment]
> Or make it an always enabled plugin...

that would also work. afair the "enabled" part is currently an UI hack, so some work is needed there.

**Comment by ptitjes** [comment]
@lazka I'd be glad to work on that.

**Comment by lazka** [comment]
> @lazka I'd be glad to work on that.

+1
