### ISSUE TITLE
Look into mypy

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#2299]
http://mypy-lang.org/

**Comment by pschwede** [comment]
Do I understand it correctly, that mypy is some kind of pre-processor to generally understood python code/syntax?

**Comment by lazka** [comment]
https://engineering.instagram.com/let-your-code-type-hint-itself-introducing-open-source-monkeytype-a855c7284881

**Comment by lazka** [comment]
I've added some things in master

**Comment by lazka** [comment]
@declension because we were wondering why a simple `[int]` isn't allowed instead of `typing.List[int]`. A guess:

```pycon
>>> typing.List.__mro__
(typing.List, <class 'list'>, typing.MutableSequence, <class 'collections.abc.MutableSequence'>, typing.Sequence, <class 'col
lections.abc.Sequence'>, typing.Reversible, <class 'collections.abc.Reversible'>, typing.Collection, <class 'collections.abc.
Collection'>, <class 'collections.abc.Sized'>, typing.Iterable, <class 'collections.abc.Iterable'>, typing.Container, <class
'collections.abc.Container'>, typing.Generic, <class 'object'>)
>>> typing.Tuple.__mro__
(typing.Tuple, <class 'tuple'>, <class 'object'>)
```

They are subclasses of the corresponding "interface types/ABCs" in Python and if you subclass them instead of the interface you get the same bases but with annotations. Example: https://github.com/pygobject/pycairo/blob/8694cd82bbdfbd9f9aef18ba1892ff9bf900b8ab/cairo/__init__.pyi#L247

So a simple `[int]` wouldn't work in all places.

**Comment by lazka** [comment]
We now run mypy in CI and there are no errors with master. We only have minimal type checks atm to get to that point, but this allows us to add type hints to new code for example.
