### ISSUE TITLE
Clicking internal URI links break in PY3

### ISSUE THREAD

**Issue by declension** [quodlibet/quodlibet#2303]
### Steps
* Load plugin manager
* Search for Squeezebox plugin
* Click link to other plugin

### Expected
Taken to the other SB plugin

### Actual
Exception:
```Traceback (most recent call last):
  File "/home/nick/workspace/quodlibet/quodlibet/quodlibet/qltk/__init__.py", line 45, in show_uri
    return __show_quodlibet_uri(parsed)
  File "/home/nick/workspace/quodlibet/quodlibet/quodlibet/qltk/__init__.py", line 58, in __show_quodlibet_uri
    return PluginWindow().move_to(uri.path[len("/prefs/plugins/"):])
  File "/home/nick/workspace/quodlibet/quodlibet/quodlibet/qltk/window.py", line 434, in __new__
    new_parent = get_top_parent(widgets[0])
TypeError: 'filter' object is not subscriptable
```

**Comment by ptitjes** [comment]
Sorry about that... Forgot to test on 3.5 !
I've got a fix ready if you want.

**Comment by declension** [comment]
No worries - there are quite a few areas still like this. I've done the fix / test anyway, but thanks.

**Comment by ptitjes** [comment]
@declension Just a note. From what I read, it seems that using next is more efficient because the list may not be processed completely (and still it is py2.7/3.5 compatible). (Even if this one list is supposed to be short...)
```
widget = next((w for w in args if isinstance(w, Gtk.Widget)), None)
if widget:
    # ...
```

**Comment by declension** [comment]
@ptitjes noted - please PR if you feel it's worthwhile.
