### ISSUE TITLE
URL links not working

### ISSUE THREAD

**Issue by urielz** [quodlibet/quodlibet#2306]
Some URL links are not working. This is on QL 3.8.1 OS X version.

See for example links in "About Quod Libet", "website", and "GNU License".

Console output is:

(quodlibet:12041): Gtk-WARNING **: Couldn't export handle, unsupported windowing system

(quodlibet:12041): Gtk-WARNING **: Unable to show 'http://www.gnu.org/licenses/old-licenses/gpl-2.0.html': Operation not supported

Same behavior is found in plugin "MPD Server". To be clear, URL links attached to GTK.button are working fine (for example "Download Album Art" plugin).

**Comment by ptitjes** [comment]
I don't get it... They are working on unstable !

**Comment by lazka** [comment]
@ptitjes it's a gtk+macOS issue

**Comment by ptitjes** [comment]
Oh sorry, skimmed over the "OS X" mention...

**Comment by lazka** [comment]
There is some work implementing this going on upstream:

https://git.gnome.org/browse/glib/log/?h=osx-appinfo
https://bugzilla.gnome.org/show_bug.cgi?id=734946
