### ISSUE TITLE
Error when changing browser to Album Collection

### ISSUE THREAD

**Issue by frestr** [quodlibet/quodlibet#2315]
**What was tried**: Tried to change from another browser (Paned Browser) to the Album Collection browser.

**What was expected to happen**: Successfully change browser with no errors.

**What happened**: QL throws an error/exception, `unorderable types: str() > object()` (see stacktrace below). As the error suggests, the issue seems to be that the cmp function in line 167 of quodlibet/browsers/collection/main.py gets called with t1 being a string and t2 an object, which is not orderable between each other. Judging by the FIXME in the code this part already has some issues, but I couldn't find an issue describing this problem.

**QL version**: 3.9 (dev)

**OS**: Ubuntu 16.04

System info & stack trace:
```
=== SYSTEM INFORMATION:
Quod Libet 3.9 (development)
Mutagen 1.37
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] linux
Platform Linux-4.4.0-66-generic-x86_64-with-Ubuntu-16.04-xenial
=== STACK TRACE

Traceback (most recent call last):

  File "/home/mark/Projects/quodlibet_orig/quodlibet/quodlibet/browsers/collection/main.py", line 167, in sort
    return -cmp(t1, t2)

  File "/home/mark/Projects/quodlibet_orig/quodlibet/quodlibet/compat.py", line 112, in <lambda>
    cmp = lambda a, b: (a > b) - (a < b)

TypeError: unorderable types: str() > object()
```

**Comment by declension** [comment]
Replicated - thanks.
