### ISSUE TITLE
Consider Tox for portable cross-version builds

### ISSUE THREAD

**Issue by declension** [quodlibet/quodlibet#2317]
Placeholder for collecting thoughts.

[Tox](https://tox.readthedocs.io/en/latest/) allows testing across multiple environments with a matrix of Python versions / dependencies via `virtualenv`.

### Pros
 * Would be good to have a lightweight way to test py2 and py3
 * Supports pytest
 * Could make sure (new) devs have the right Python dependencies at least

### Cons
 * we have system dependencies (and don't use `virtualenv`), might not be so practical here.
 * Anything extra layer no matter how easy is annoying

### Other options
 * Stick with the decent Travis matrix we now have (doesn't work locally of course)
 * Use Docker more to run things locally, and this definitely allows us more control e.g. of O.S. and GTK+ versions etc.

**Comment by lazka** [comment]
@ptitjes, @urielz, @frestr having created PRs lately might have something to add regarding our current dev process

**Comment by ptitjes** [comment]
I do use PyCharm to develop (and mainly terminal for versioning). I created "Run configurations" for QL, quality and tests (minus quality) for both py2.7 and py3.5. It was difficult at first to have the python dependencies on par for 2.7 and 3.5 (and have them all to not miss stuff that CI would not). Now it is difficult to not miss one target when trying to run all of them. It would be great to have a "run them all" (once and for all) before pushing PR.

Also, I see that I only have a Linux/Gnome environment and CI blatantly made me realized recently that this is not enough. I would be glad if there was a doc (maybe I missed it) or, better, an automated process to have some more build targets. I bet Docker is the way to go but, even if I have basics about it, I believe I won't go all the way if it is not automated.

**Comment by frestr** [comment]
Although I haven't tried tox myself, it seems like a good idea to have something like it in place. In addition to testing across versions and dependency handling, it will make it more explicit that both Python 2 and 3 should be tested. It isn't that obvious that the codebase is a combination of Python 2 and 3 (unless you have read through issue  #1580 or peeked around in the code), and to add to the confusion, doing `./quodlibet` will run QL with Python 3, while `./setup test` will run the tests in Python 2. If nothing else, this should be explained better in the documentation.

**Comment by urielz** [comment]
Not being a developer myself, I appreciate how things are setup right now for OS X. It's really easy to jump into the code right away without the need to create a dev environment. However I can see the benefits of using something like Tox. Whatever direction this is taken, I think the documentation should be as clear as possible, so people without much experience can continue/start contributing to QL with minimal effort.
