### ISSUE TITLE
Gnome Header Bar Menu Button Displays Icon Incorrectly

### ISSUE THREAD

**Issue by redvimo** [quodlibet/quodlibet#2320]
Hi, developers of quod-libet. 

Thanks for the great work, i really like your app, especially the equilizer plugin. For some reason it sounds better than the rhythmbox equilizer.

Anyway as it is in the screenshot below, the icon displays incorrectly in the top left corner.
I am running Ubuntu Gnome 16.10.
![screenshot from 2017-03-17 14-35-16](https://cloud.githubusercontent.com/assets/16490763/24043542/c8458d1a-0b1f-11e7-81ec-3e3e7898e3c0.png)

**Comment by lazka** [comment]
I can reproduce. Thanks!

**Comment by redvimo** [comment]
Cool.

**Comment by redvimo** [comment]
So i have a few help questions.
I created a new project just to see how it works, and then I forked this project (quod-libet) because I need something to work on. I was wondering what information in the fork must I change, for example the name of the software, the author, etc. Is there anything else I need to know. I think I understand the conditions of the gpl v2 licence. This is just for fun.
 Thanks.

**Comment by IBBoard** [comment]
I noticed this and tried to understand and then fix it. The problem appears to be a lack of icon smaller than 64x64. If you create a 16x16 QuodLibet icon and put it in `…/site-packages/quodlibet/images/hicolor/16x16/` then it'll show a correct icon.

I could bash a quick fix together based on the SVG icon, but I don't know whether you've got an icon artist who would want to do a better quality image with appropriate hinting and accommodation for the scaling 😊

**Comment by lazka** [comment]
There is already a PR for this: #2334

**Comment by ptitjes** [comment]
@lazka Maybe this can be closed as you merged #2334 ?

**Comment by lazka** [comment]
ah yes, thanks
