### ISSUE TITLE
Preserve queue height when queue is hidden and browser is changed

### ISSUE THREAD

**Issue by frestr** [quodlibet/quodlibet#2321]
**Steps**:
* Show the queue by clicking the queue visibility button in the lower right corner and expand it
* Set the queue to a preferred height
* Hide the queue by clicking the button again
* Change browser
* Show the queue again

**Expected**: The queue will have the same height as it had when being hidden in step 3. 

**Actual**: The queue height is set to the minimum/default height.

The queue height is preserved if
- toggling visibility in the same browser,
- changing browser with with the queue being visible and
- after a restart (both when visible and not),

but not when the queue is hidden and the user changes browser.

May seem negligible, but can occasionally be a little annoying.

**Comment by urielz** [comment]
I can reproduce this. Agree that it would be nice to preserve queue height.
