### ISSUE TITLE
Queue is not properly expanded when dragged

### ISSUE THREAD

**Issue by frestr** [quodlibet/quodlibet#2323]
**Steps**:
* Show the queue by toggling the queue visibility button
* Make sure the queue is unexpanded (only the queue header is shown)
* Drag the queue upwards

**Expected**: The queue is automatically expanded. This is what happens in my Arch installation.

**Actual**: The queue can be dragged up, but the queue content is not shown, and it's overall quite glitchy. It's a little hard to explain, so here's a GIF of what's happening: https://i.imgur.com/WgB5YdI.gif (didn't want to embed, as GIFs can be a little annoying).

**QL version**: 3.9 (dev)

**OS version**: Ubuntu 16.04

**Comment by lazka** [comment]
That's a bug with some gtk+ versions (3.16-3.20 or so)

**Comment by frestr** [comment]
Ah, I see. I'm running version 3.18, so that's probably it. I'll close this then.
