### ISSUE TITLE
Add default path patterns to Ex Falso

### ISSUE THREAD

**Issue by CreamyCookie** [quodlibet/quodlibet#2329]
IIRC there are no default path patterns for renaming files in Ex Falso. I suggest to add the following (or similar) patterns:

**normal**
```xml
~/Music/<performer|<performer>|<albumartist|<albumartist>|<artist>>>/(<~year>) <album>/<tracknumber|<tracknumber> - ><title>
```

**various artists**
```xml
~/Music/<performer|<performer>|<albumartist|<albumartist>|<artist>>>/(<~year>) <album>/<tracknumber|<tracknumber> - ><artist> - <title>
```

Even if they're not to the liking of the user, they can be used as a good starting point.

**Comment by lazka** [comment]
These are the default ones:

https://github.com/quodlibet/quodlibet/blob/master/quodlibet/quodlibet/qltk/renamefiles.py#L34

**Comment by CreamyCookie** [comment]
Ah.. so they're not saved, just appear in the dropdown. I guess that's fine. I've created a small little PR anyway.
