### ISSUE TITLE
Command line ReplayGain

### ISSUE THREAD

**Issue by svnpenn** [quodlibet/quodlibet#2335]
I see that ReplayGain can be set with Ex Falso via the "Replay Gain" plugin.

However I am trying to set it via command line with Operon. Is this possible?

**Comment by lazka** [comment]
It should work.

I just noticed that "operon tags" doesn't list programmatic tags, we should add a "-a --all" switch there like with "operon list"

**Comment by svnpenn** [comment]
@lazka thanks for fast reply. Will you please provide example command for setting ReplayGain?

**Comment by lazka** [comment]
Hm right, it would be ``operon set replaygain_track_gain "-12.345 db" a.mp3``, but it fails because the value stars with "-".

**Comment by svnpenn** [comment]
and how would you aquire the `-12.345 db`? Can we do command line ReplayGain scanning?

**Comment by lazka** [comment]
operon just does tagging, nothing more atm.

This looks like something you want, but haven't tried: https://pypi.python.org/pypi/rgain

**Comment by lazka** [comment]
(note for myself, OptionParser.disable_interspersed_args should help with the ambiguity for values at least..)

**Comment by svnpenn** [comment]
I guess this is a feature request then. I see you use BS1770GAIN internally:

https://github.com/quodlibet/quodlibet/blob/20ad20df210c56f1f0826d16b3ba2fb556078c2f/quodlibet/quodlibet/ext/songsmenu/replaygain.py#L152-L162

So the desired functionality would be: similar to how BS1770GAIN can scan and set ReplayGain from the command line, Operon could scan and set ReplayGain from the command line

**Comment by lazka** [comment]
In Quod Libet we use the GStreamer replaygain implementation. It's unlikely that we will expand our GUI plugins to operon.

I've opened #2339 for the value problem.
