### ISSUE TITLE
Adding an audio feed may throw TypeError if "length" parameter in <enclosure> is a blank string

### ISSUE THREAD

**Issue by felixleong** [quodlibet/quodlibet#2342]
An example feed would be <https://www.shutupandsitdown.com/podcastle/feed/>:

```xml
<enclosure url="http://feeds.soundcloud.com/stream/314084184-susd-podcast-54-when-teenagers-become-roman-soldiers.mp3" length="" type="" />
```

This would cause a TypeError to trigger in [quodlibet/browsers/audiofeeds.py](https://github.com/quodlibet/quodlibet/blob/master/quodlibet/quodlibet/browsers/audiofeeds.py#L180-L183).

```python
try:
    size = float(enclosure.length)  # float('') would trigger TypeError here
except AttributeError:
    size = 0
```

Would suggest either adding an additional if/else check or that the except block should catch for TypeError as well.

**Comment by lazka** [comment]
Thanks

**Comment by CreamyCookie** [comment]
This seems to be taken care of in master: 

https://github.com/quodlibet/quodlibet/blob/b973220cccc9f3cdb411e68f595d2c79bf4bf76a/quodlibet/browsers/audiofeeds.py#L174-L177

`float('')` throws `ValueError` (at least in Python 3.8)

So I'm closing this. Thanks for the report, felixleong!
