### ISSUE TITLE
list() for tied tags returns all values of each tag, not the tied tag

### ISSUE THREAD

**Issue by archy3** [quodlibet/quodlibet#2344]
--random currently accepts tied-tags but doesn't handle them properly (that is as if \~tag1~tag2 were really just one tag with a name of "~tag1\~tag2" and a value of "tag1val - tag2val").

Say I `quodlibet --random=~album~grouping` or `echo "random ~album~grouping" > $HOME/.quodlibet/control`

I would expect this to have the affect of picking a random album, then picking a random grouping from that album. So the filter might be `~album~grouping='Sammy Conducts Beethoven - Symphony No. 5'c`. But instead it will either set \~album~grouping equal to a random album, or ~album\~grouping equal to a random grouping. In all cases (except when the other tag is missing) this leads to zero songs in the song list because the filter might be `~album~grouping='Sammy Conducts Beethoven'c` or `~album~grouping='Symphony No. 5'c` but neither of those values exist for that tied tag. The value 'Sammy Conducts Beethoven - Symphony No. 5' exists though and is an example of the kind of values I'm trying to generate.

Image all the possible values of ~tag1\~tag2 are in a list. `quodlibet --random=~tag1~tag2` should select a value from that list and filter by `~tag1~tag2='selectedValue'c` instead of selecting a value from either the tag1 list or the tag2 list. It should be like I have a pane set up by `<~tag1~tag2>` and `quodlibet --random=~tag1~tag2` would select a random item from that pane (just as if I have a pane set up by `<album>`, then `quodlibet --random=album` would select a random item from that pane).

**Comment by declension** [comment]
Had a quick look, and yes I see why this happens. Not sure whether this was ever meant to be supported, mind you but let's call it a bug for now as it seems 

Dev note: it happens everywhere lists of tied tags are handled, i.e.
```af.list('~artist~title') != [af('artist') + ' - ' + af('title')]```

**Comment by declension** [comment]
an example of the existing / previous behaviour:

```sdict[0]("~~people~title")
"Garbage\nCrystal Method - I Think I'm Paranoid"```
