### ISSUE TITLE
Gapless playback not working across platforms and file types

### ISSUE THREAD

**Issue by pt8o** [quodlibet/quodlibet#2347]
I've got the latest version of Quod Libet on Mac, Windows, and Linux (ElementaryOS). On all three versions, the gapless playback doesn't work; there's a short gap, sometimes a pop, between songs. I've tested with OGG, AAC, and MP3 files, and verified that all play gaplessly in iTunes.

**Comment by iondissonance** [comment]
Try change buffer size to 1s. In preferences.

**Comment by suprko** [comment]
Thanks, I tried that but I still get the gap.
(Nice username by the way :+1: )

**Comment by bassstorm** [comment]
Not reproduced on QL 4.4 with gstreamer 1.18.4. Buffer size is 3s (probably default value). FLAC files (sorry, don't recall any good gapless example in OGG or MP3 in my collection).
@pt8o would you like to re-check please?

**Comment by pt8o** [comment]
Yep, seems good now

**Comment by bassstorm** [comment]
Close after confirmation with OP, thanks.
