### ISSUE TITLE
Playlist: tracks with non-ascii filenames throw exceptions on import

### ISSUE THREAD

**Issue by josky1** [quodlibet/quodlibet#2356]
Tracks containing umlaute (a, ü, ö) or – (U+2013) in its path wont show in imported playlistfiles.
I can add them to the library just fine.

Using Windows 7, Quod Libet 3.8.1 
[playlist.zip](https://github.com/quodlibet/quodlibet/files/924402/playlist.zip)

**Comment by lazka** [comment]
The playlist has latin-1 encoded filenames while we expect utf-8. We should probably try multiple encodings.

**Comment by josky1** [comment]
I changed the encoding of the playlist to utf-8 and imported it. 
Received the following error. 

[MiniDump_20170419_191506.txt](https://github.com/quodlibet/quodlibet/files/936662/MiniDump_20170419_191506.txt)

**Comment by lazka** [comment]
uh :( thanks for the error report

**Comment by declension** [comment]
@josky1 this has changed a bit recently. Do you still get this on the latest development build?

**Comment by josky1** [comment]
Just tried and imports the playlists fine!
Might be the time to bin winamp..
