### ISSUE TITLE
Updated waveform disappears on repeat track

### ISSUE THREAD

**Issue by Meriipu** [quodlibet/quodlibet#2357]
I recently updated to head rather than using my local similar change of increase tickrate to milliseconds, though now when a track finishes and repeats, the waveform is a flat line without any visible progress. 

latest version from github on Linux

**Comment by urielz** [comment]
Thanks for the report. I can reproduce as well.

**Comment by ptitjes** [comment]
I can reproduce it too. I'll look into it during next week.

**Comment by ptitjes** [comment]
Sorry for the delay...
I hope it is not too late to make it for 3.9 !

**Comment by Meriipu** [comment]
The waveform persists between repeats now, but did a recent change break #2255 ? 
I went through the commits but could not find any that made sense to me for breaking it

The waveform is at least for me back to updating every second or so.

**Comment by Meriipu** [comment]
Thanks.

I thought it broke the interval at first but I just installed the wrong branch.
