### ISSUE TITLE
Auto-mutes on next track.

### ISSUE THREAD

**Issue by piousminion** [quodlibet/quodlibet#2361]
When the next track is played, automatically or by click, the player mutes. The volume remains the same, but is muted and playback tracking continues.  I have to uncheck "mute" every time the track changes.  This is rather rage-inducing. heh

Distro: Archlinux x86_64
quodlibet: 3.8.1
Audio device: GStreamer (pulsesink)
Python: 2.7.13
Mutagen: 1.37
GTK+: 3.22.10 (X11)
PyGObject: 3.22.0
GStreamer: 1.10.4.0

**Comment by lazka** [comment]
Is this a new problem? Have you tried restarting the machine?

**Comment by piousminion** [comment]
@lazka This is my first time using this player.  Oddly enough a system reboot solved the problem. I did not expect that, but thanks.

**Comment by piousminion** [comment]
I may have closed too soon, not sure.  It seems to auto-mute when teamspeak is open.  No other audio software is affected by TeamSpeak being open.

**Comment by lazka** [comment]
OK, thanks, I'll have a look.

**Comment by lazka** [comment]
TeamSpeak registers itself with a "phone" role to pulseaudio while quodlibet uses the "music" role. Pulseaudio mutes music by default when a "phone" gets active.

This should help: http://www.alexandervolf.com/?p=589
