### ISSUE TITLE
filtering/sorting in one Browse view affect others in unexpected ways

### ISSUE THREAD

**Issue by fecraow** [quodlibet/quodlibet#2374]
this may warrant multiple bugs -- if this should be split up, please let me know.

i'm only going to describe how this affects switching between "Paned Browser" and "Playlists", as these are the ones I use, although other views may be affected in other ways....

1)
okay, so when I open quodlibet, it's in "Paned Browser", because that's what I most often use. If I switch to "Playlists", the right pane starts filled with whatever songs show up with the filters that were selected in Paned Browser (or all songs if no filters were applied), whereas I'd expect no songs to show up until one of the playlists is selected (and that is actually what happens if you open quodlibet and the last view was Playlists). Once you select a playlist, the view appears as you'd expect.
(I don't consider the above an especially big deal, but I include it to help illustrate what's going on.)

2)
now, when I switch back to "Paned Browser", the list of songs remains the last selected playlist from Playlist view. There's no UI indication that a playlist is selected. All my filters have "All" selected, and yet the song list is including only songs from a particular playlist. I have to click on one of the (already selected) "All" lines again in order to show all my songs.

3)
once i've got all the songs showing again, I notice that the song list no longer has any apparent sorting (in Paned Browser, I normally sort by Title)

should the filters and sorting be done per-view to avoid these types of issues?

**Comment by declension** [comment]
Thanks for the report and sorry about the delay. This kind of issue has come up a few times. The songlist is confusing sometimes in QL especially in the way it persists across browser changes as you describe.

This sounds like two issues to me:
 * Refreshing the songlist moving to Playlists browser (capture in #2053)
 * Sorting per browser or sort order being forgotten somewhow. 

Perhaps we should reduce this issue to the latter and continue the other discussion on #2053

**Comment by frestr** [comment]
Fixed in #3041.

Regarding the 3rd point: the sorting is reset when switching to the playlist browser since one usually wants to restore the original playlist order. When switching back to another browser the sorting is reset, since state across browser switches aren't retained (captured in #1850).
