### ISSUE TITLE
3.9 Release

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#2379]
- [x] Fix UI changes with long translations in mind
- [x] Write changelog
- [x] refresh macOS deps
- [x] ~Check if we need to include the python source on win/osx to get good sentry reports~ (leave that for 3.10...)
- [x] Depend on faulthandler?

**Comment by lazka** [comment]
@declension any objections for queue UI changes? I'd file them under not perfect, but better than before.

**Comment by declension** [comment]
@lazka yep, agreed.

**Comment by lazka** [comment]
stable branch is here...

**Comment by frestr** [comment]
I'm a bit curious: any particular meaning behind the release names?

**Comment by lazka** [comment]
https://quodlibet.readthedocs.io/en/latest/guide/faq.html#where-do-the-release-names-come-from

**Comment by lazka** [comment]
release tagged, builds will follow in the coming days
