### ISSUE TITLE
Enhancement suggestion: Playlist export

### ISSUE THREAD

**Issue by alan12345678** [quodlibet/quodlibet#2382]
Am running QL under Manjaro now - jumped ship from Fedora. Player works great of course, couple of things would be nice to see:

I now use Mixxx DJ software on my machine. As such, its own playlist/crate management is great. Because it's DJ software and not a media player, one common way for me to put together a playlist for it is to go back to QL and every time a song comes on that I want to tag, I add it to a new/existing playlist in QL.

However, to get that playlist seen by Mixxx I have to do two things. First is to rename the playlist to add some form of extension. Okay, so that's hardly a problem (and anyway, mime types make way more sense to me) but before I can rename it, I have to expose hidden folders in my home directory and navigate within to find the playlists as QL has stored them.

Do you think you could add an "export playlist" or "save playlist as" or even just expand "add to playlist" to add dialogue boxes for location and type?

**Comment by declension** [comment]
@alan12345678 Thanks, interesting ideas

Please make sure each issue is just one feature request - I suggest perhaps making this one the playlist feature and creating a new one for the EQ auto-save, etc. They are very different parts of the codebase

**Comment by declension** [comment]
@alan12345678 on re-reading this I must have missed something originally. 

Anyway, there's already the _Export as Playlist_ plugin for saving to m3u / pls files. It's now a songlist plugin (right click on some songs) _and_ a playlist plugin (right click on a playlist, it will suggest a suitable name). Yes, this should probably be part of the QL core (there are some issues floating around to do this, I might get round to it soon)...

Is that what you wanted or was there something extra (_bulk_ handling as per #2012 perhaps)?

**Comment by alan12345678** [comment]
@declension 

Oh yes! Sorry, yes I've just seen those two plugins now you mention it! That was indeed what I was looking for, thanks!

If what you mean by being QL core, I suppose I'd simply assumed (prior to just now finding those plugins) that the "playlist" meun, itself just below the "plugins" menu - when right-clicking a title - was where such a feature would naturally live. But very happy obviously just to have the feature at all :-)

**Comment by declension** [comment]
Great. Thanks @alan12345678, sorry about the delay. 

That place (in the songs context menu) is for manipulating the _contents_ of those playlists, but I see where you were coming from.

I'll close this ticket now.
