### ISSUE TITLE
ImportError: No module named faulthandler.

### ISSUE THREAD

**Issue by thisfred** [quodlibet/quodlibet#2390]
When I start quodlibet I now get the above error. Looks like a new dependency was added, but maybe the setup.py wasn't updated to reflect this? (I did reinstall, and the error persists.)

**Comment by lazka** [comment]
We currently don't do any dependency stuff in setup.py, as python dependencies alone would only cover a small part of what is needed anyway.

See https://quodlibet.readthedocs.io/en/latest/development/devenv.html

**Comment by lazka** [comment]
Or did I miss adding the dependency for a repo?

**Comment by thisfred** [comment]
Oh, ok, I guess this can be closed. faulthandler is in that list of dependencies in the devenv setup.

**Comment by Meriipu** [comment]
I had to install it manually with pip2.7 since it did not exist in my package manager, and my system uses python2.7 by default (it seems only python3 has it by default?)

**Comment by lazka** [comment]
@Meriipu which distro?

**Comment by Meriipu** [comment]
@lazka gentoo linux

**Comment by lazka** [comment]
When you install it it will default to 2.7, when running from source it defaults to 3 so we get some testing.

ok, I guess gentoo will include faulthandler once they update to QL 3.9

**Comment by PeadarO** [comment]
I'm no wiser.  I typed "python setup.py install" in Ubuntu and I got "ImportError: No module named faulthandler" and I've been through just so many websites looking for a solution and they are all about as helpful as this one.

**Comment by lazka** [comment]
python might be Python 2, which is no longer supported. Also you shouldn't use `python setup.py install`, it will mess up your system.
