### ISSUE TITLE
ReplayGain processes again files when it shouldn't

### ISSUE THREAD

**Issue by jkohen** [quodlibet/quodlibet#2396]
This bug is nuanced, so please bear with me. I'm attaching a screenshot to help visualize the problem.
![capture](https://cloud.githubusercontent.com/assets/7148392/26477711/9889c012-4195-11e7-8ac9-ff9043cdef13.JPG)

I set up ReplayGain to only rewrite files when tags are missing. QuodLibet will say only X albums out of XXX need to be processed, and for a few albums, ReplayGain will do exactly what is expected. However, after a few albums ReplayGain will just start processing all albums from the list sequentially starting from the last one that needed processing, even if they were already up to date.

It seems that for me the number of albums after this breaks is 4, which is also the number of cores in my CPU.

**Comment by lazka** [comment]
Thanks. I can reproduce
