### ISSUE TITLE
Add ListenBrainz scrobbling support

### ISSUE THREAD

**Issue by stephenjudge** [quodlibet/quodlibet#2397]
Whilst it's great to have support for GNU FM servers in the AudioScrobbler Submission plugin, could you also look into adding support for submissions to ListenBrainz as well.

You might find the documentation you need here: https://listenbrainz.org/contribute
Another Scrobbler for Android has been able to do it: https://github.com/tgwizard/sls/search?utf8=%E2%9C%93&q=listenbrainz&type=

**Comment by Freso** [comment]
I'll just quote myself from #2549:
> [ListenBrainz](https://listenbrainz.org/) is a new open source and open data alternative to Last.fm. While it *would* be possible to simple call ListenBrainz using the scrobbling API, adding support for [ListenBrainz's native API](https://listenbrainz.readthedocs.io/) would allow for a lot more information about each listen to be submitted (e.g., all MusicBrainz identifiers (and not just the Recording one)).

**Comment by phw** [comment]
Just as an info for people who want to use ListenBrainz with Quod Libet right now, you can configure the existing Audioscrobbler plugin to submit to ListenBrainz via the [Last.fm compatibility API](https://listenbrainz.readthedocs.io/en/latest/dev/api-compat.html).

In the settings of the Audioscrobbler plugin:

1. Choose "Other" for the service
2. Set "http://proxy.listenbrainz.org" as the URL
3. Use your MusicBrainz username as username
4. Use your ListenBrainz user token as password (get it on https://listenbrainz.org/profile/)

Of course having Quod Libet use the real ListenBrainz API is preferrable

**Comment by phw** [comment]
I am not sure I will find the time to work on this, but for anyone wanting to give this a go I have working Python code for a [ListenBrainz Rhythmbox plugin](https://github.com/phw/rhythmbox-plugin-listenbrainz) . The code in [listenbrainz_client.py](https://github.com/phw/rhythmbox-plugin-listenbrainz/blob/master/listenbrainz_client.py) is mostly independent of the rest of the plugin code and could be directly reusable.

Also similar code was [merged into Lollypop](https://gitlab.gnome.org/gnumdk/lollypop/merge_requests/1294)

**Comment by ijc** [comment]
I put together a quick plugin using @phw's `listenbrainz.py` (thanks!) and bits of the existing `qlscrobble.py` extension, see https://github.com/ijc/quodlibet-listenbrainz-plugin/.

I've been running it all day today and in the "all's well" case it seems to be working fine but the error handling is pretty sketchy (some might say practically non-existent) and on some failures it can get into a pretty tight resubmission loop.

I stuck it in a new repo for simplicity but ideally I'd like to get it into a state where it could be submitted upstream/here.

**Comment by LoveIsGrief** [comment]
@lazka How would one go about adding @ijc's plugin to the main list of plugins in Quod Libet?

**Comment by ldexterldesign** [comment]
BUMP

**Comment by kurobeats** [comment]
not sure how much "testing" is needed, but can confirm that this plugin works flawlessly. Well worth adding to packaged list of plugins. Tested on Linux and Windows FYI.

**Comment by declension** [comment]
@ijc how do you feel about submitting a PR here?

**Comment by ijc** [comment]
@declension I threw the current code at https://github.com/quodlibet/quodlibet/pull/3528
