### ISSUE TITLE
Feature: Playlist filters

### ISSUE THREAD

**Issue by codejodler** [quodlibet/quodlibet#2398]
Hello, 

I'm using quodlibet 3.7.1. on Debian Linux 9, and some other linux variants, since 2 years because i did not like bloated players or the others lack some specific feature.

I'm using different music players on different OS nearly exclusively with their file browser since i've got a huge music file collection. The files are sorted into folders (character stations) which resemble specific moods, or other criteia, and targeted at semiprofessional DJ usage. I'm used to quickly find a file for a specific mood, or mix some 2 or 3 stations. It's even possible to let it just play random from the mix, unattendet.

All music files have their attribute data both in filename and tags.

* What did you try to do?
I tried to filter a playlist for a specific tag, or for a specific artist. 
In the file browser, i tried the "instant search letter input" feature and typed in a search string.

* What did you expect to happen?
All files with that string in their filename should be displayed, the other should be invisible (and not used in the playlist anymore)

* What did happen instead?
Well, it jumps to the first hit.

I would like to have such a playlist filter feature because i'm rather often looking for a specific tag, within a file list. Let's say i'm in the semi-classical section, station 'miracles and phantasy' and want to find another file with 'anime music' tag. Or in the chillout station, flavor 'cool and spacy', and want to quickly find another file with "intelligent dance music" tag (idm) referring to some beat characteristics. 

I'm also often looking for elements of the filename, like 'which other files of that artist or album do i have", and i use to insert special markers in the filenames too. (Because i'm working on different OS with different players, that's finally the most reliable thing.) For example, 'favorite' likes are not realized the same in different players, which is why i'm just adding a specific character into the filename.

I agree that my usage is far from 'widespread' but i think a playlist filter would be useful to other people too.

**Comment by codejodler** [comment]
I'm depending so much on the file system (as the database) because i'm trying to be compatible, working in all of Windows, iOS, Android, and Linux, on different devices. With files in the many thousands, even cloud storage becomes uneasy and i'm preferring external SDD drives connecting to the specific player, either plugged or NAS by direct WiFi.

**Comment by declension** [comment]
Thanks for the detailed issue report.

I think your use of the word playlist refers to the QL "songlist" rather than physical playlists on disk (as per the Playlists browser).

What you describe should already be possible to an extent using the existing progressive search feature, which you might have to (re)enable in the preferences. Just use the search browser, and perhaps add a songlist (view) column of `~filename`. Then focus the search bar (which you can quick select with ctrl-L, IIRC) and typing will filter the songlist to only songs matching all terms, though across _any_ of your columns.

Also you can construct more specific queries like `~filename=|(foo, bar, baz)` to refine to files matching any of those path name fragments and similar using `~dirname`.

**Comment by codejodler** [comment]
Nick,

thx so far for your informative answer.

I gave it a try, had only 15 minutes, but still couldn't do what i wanted to do. Mainly, I need documentation about the expression syntax. I have special chars like +,&,() in filenames too. 

I need more time, because i'm heavily under load  ... 

So, even if you closed the bug - pls don't mind if some day i suddenly crawl out with a follow-up ... !

By the way, there are incredible bad (or rudimentary) players out in the Android world, and even the iOS ones are not really suitable for me. For example, they still mix anything together to their own criteria, not mine .... i wonder how those smartpphone teens are listening, today. Will they ever be able to imagine what it means to sort stuff out, tio be able to quickly create collections, special playlists, daily, just for the next few hours, or so. Or do they simply suck whatever drops in ... i'll never get used to that habit.

Merci & bon nuit,

Micha

**Comment by declension** [comment]
Hi @codejodler 

Thanks.  I'll leave this open for now, but please come back if you work it out so we can either refine or close the issue.

Meanwhile here is the [User Guide section on searching your library](http://quodlibet.readthedocs.io/en/latest/guide/searching.html).

**Comment by codejodler** [comment]
Nick,


I was doing this right now:

(1) Re-Scan the library. It's several thousand songs but seems to be fast.

(2) Open Search browser and type in: ~dirname=|(blafoo) for one music file folder starting with that expression.

Now the search browser shows the files of that folder, including subfolders.

(3) Mark all -> add to queue

Now i can play the queue. The problem here is, since a queue is not a playlist, a song gets removed once its done. So i'm rather doing this:

(3) Playlist -> New playlist

I explained in the beginning that i want to be able to select sub-sets of folders, in my case i'm marking favorutes with a '+' sign and i wanted to select all filenames containing that + char.

Q: How can i combine search terms, is it possible to do something like '~dirname=|(void) && filename=|(+)' ?

This apporach also has a serious disadvantage. I'm always working on my files, deleting some, adding some, dis/liking some (by + filename). So i would have to re-scan the library and re-create the final playist over and over.  

And there is another thing i wanted to do, maybe even more important: Mixing a selected set of different folders. This boils down to complex search terms like (~dirname=|(void) && ~dirname=|(bluedrift)) && filename=|(+).

I don't know if something like this already is possible. But i can tell how the thing would be looking like in a Quodlibet way:

1. Creating a selection (songlist) by complex search term
2. Being able to 'move' the result as songlist to the main player window (Right click -> 'Play result')
3. Save and reload search terms as  profile. This is basically already there, but search saves anything which is cluttered. I would like to save and reload only the coolest profles, not the crap. Basically, it would extend the 'search library' browser to select those profiles.
The important point here is, that reloading a search profile, would  re-scan the library, automaticly.

hth mi

**Comment by declension** [comment]
> Q: How can i combine search terms, is it possible to do something like '~dirname=|(void) && filename=|(+)' ?

Something like `&(~dirname=foo, date=2009)` or in your case `&(~dirname=void, ~filename=+)`

> Save and reload search terms as profile. This is basically already there.

You can manage your saved searches by clicking _Edit Saved Searches_, and naming these. See [the query documentation section](https://quodlibet.readthedocs.io/en/latest/guide/searching.html#reusing-queries) 

There are quite a lot of open issues / enhancement proposals around searching and playlists - have a look around. In particular, #1221 comes to mind.

Other than that everything seems here seems implemented, so I suggest we close this issue.

**Comment by CreamyCookie** [comment]
> The problem here is, since a queue is not a playlist, a song gets removed once its done.

There is an option "Keep Songs" when clicking on the queue's settings icon. Not sure, but I don't think it existed when this was opened.

Closing this for now, because, as mentioned by @declension, the required functionality exists.
