### ISSUE TITLE
"quodlibet --random=tagName" does not work

### ISSUE THREAD

**Issue by archy3** [quodlibet/quodlibet#2400]
`quodlibet --random=tagName` does not work (it just focuses the Quod Libet window), but `echo "random tagName" > $HOME/.quodlibet/control` does work.

Tested with Quod Libet 3.9.0 on Debian 8.

**Comment by declension** [comment]
I can't reproduce this (on c234be45be9ce26f545c3df4cecc95af88d0da53) with `artist`, `genre`, `album`.
