### ISSUE TITLE
Invalid byte sequence in conversion input

### ISSUE THREAD

**Issue by anewuser** [quodlibet/quodlibet#2406]
I get this when I try to use the `File - Add a Folder` menu or the library settings to add a folder in a directory path that contains letters with accent marks, such as `á` or `ú`:

```
Exception: Item 0: Invalid byte sequence in conversion input
------
Traceback (most recent call last):


  File "C:\apps\quodlibet\data\lib\python2.7\site-packages/quodlibet/qltk/quodlibetwindow.py", line 1372, in open_chooser
    fns = choose_folders(self, _("Add Music"), _("_Add Folders"))

  File "C:\apps\quodlibet\data\lib\python2.7\site-packages/quodlibet/qltk/chooser.py", line 190, in choose_folders
    return _run_chooser(parent, chooser)

  File "C:\apps\quodlibet\data\lib\python2.7\site-packages/quodlibet/qltk/chooser.py", line 85, in _run_chooser
    result = [glib2fsn(fn) for fn in chooser.get_filenames()]

Exception: Item 0: Invalid byte sequence in conversion input
```

The only actions I've done were: 
* I didn't import the library when I first launched the program
* I enabled the Last.fm scrobbler plugin
* I deleted the locales from `\data\share\locale`

3.9.0 portable
Windows 10

**Comment by lazka** [comment]
Thanks.

Unrelated, but QL now has a plugin for selecting/disabling translations.

**Comment by lazka** [comment]
https://twitter.com/QuodLibetApp/status/836878012431888384

**Comment by lazka** [comment]
File a bug+patch upstream: https://bugzilla.gnome.org/show_bug.cgi?id=783347

**Comment by anewuser** [comment]
Thank you for spending your time on this!
