### ISSUE TITLE
Queue play order is not random after startup

### ISSUE THREAD

**Issue by CreamyCookie** [quodlibet/quodlibet#2411]
Unless I got extremely (un)lucky (I tried 10 times just now, and also noticed it the last few days), the order of the queue is not random, when the respective option is enabled. It's played from the top to bottom. It seems to work, once "Random" is dis- and then re-enabled in the queue's drop down menu.

-----

Quod Libet 3.9.0

Audio device: GStreamer (pulsesink)
Python: 2.7.12
Mutagen: 1.37
GTK+: 3.18.9 (X11)
PyGObject: 3.20.0
GStreamer: 1.8.3.0

**Comment by declension** [comment]
Confirmed on e7e24b3930e627dce675b285dec4701a11d7ac4d.
Thanks @CreamyCookie
