### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character

### ISSUE THREAD

**Issue by 17ts** [quodlibet/quodlibet#2412]
Importing playlists with certain unicode characters crashes on windows (fine on unix as far as I can tell)

UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 43: ordinal not in range(128)

Playlist in question, which was saved from quodlibet. Opens fine in VLC. Saving the m3u with UTF-8 encoding doesn't help.

```
#EXTM3U
#EXTINF:166,Bob Dylan - Blowin’ in the Wind
..\album\bob dylan - 1963 - the freewheelin’ bob dylan\01 - bob dylan - blowin’ in the wind.flac
```

u\2019 is ’ but it happens on other characters as well, like question marks.

[Dump_20170602_131813.txt](https://github.com/quodlibet/quodlibet/files/1047513/Dump_20170602_131813.txt)

**Comment by lazka** [comment]
Thanks, this was already reported in #2404
