### ISSUE TITLE
[feature request] exfalso without quodlibet for windows.

### ISSUE THREAD

**Issue by mer2329** [quodlibet/quodlibet#2413]
now i really like ex-falso for may tagging. 
but i use another player to play my media. so i have no need for quodlibet.
is there any way for an official build of just ex-falso to be published without quod libet. (like the mac has)
or can the installer be changed to let you choose ex-flaso and quodlibet as components.

**Comment by lazka** [comment]
Any specific reason why you want to get rid of it or it can't be ignored? They both share 90% of the code/dependencies so splitting them would not safe any space at least.

**Comment by mer2329** [comment]
Yes the icon could be ignored and I didn't realize they shared 90% of the code. 
But number of start menu icons is also a concern for me. 
Sure I could hide what I don't want but that is beyond most people and they will just live with the extra icon.

Also thinking from a HDD perspective every file uses at at least 4kb due to clusters. (it depends on cluster size).

If the user only needed exfalso then there should be no need for the playback dependincies as well. 

But I would be happy for a official way to remove the start menu icon. 

Also thanks for making exfalso possible.

**Comment by lazka** [comment]
Regarding the current size of the installation and the amount of files installed there is definitely things that could and should be improved. Some random thoughts:

* There are some larger tls related files which might not be needed. I need to delete them one by one and see if the test suite still passes.
* We currently ship a lot of icons. Question is how removing all png ones would affect the loading time.
* We ship quite a few video related gstreamer plugins. Needs checking if we need them for playing audio in video files.
* We might not need all gi typelibs
* ...

Having a separate installer makes things complicated for us and adding an option to select at installation time makes things more complicated for users. Which is imo not worth it.

**Comment by lazka** [comment]
> If the user only needed exfalso then there should be no need for the playback dependincies as well.

Ex Falso has plugins for replaygain detection and audio fingerprinting, both need 90% of the audio playback machinery for decoding and processing all our supported audio formats etc.
