### ISSUE TITLE
AttributeError: 'SongLibrarian' object has no attribute 'masked'

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#2414]
https://sentry.io/share/issue/3134323431352e323836333533383237/

```
AttributeError: 'SongLibrarian' object has no attribute 'masked'
  File "quodlibet/browsers/playlists/menu.py", line 66, in _on_toggle_playlist_activate
    playlist.remove_songs(songs)
  File "quodlibet/util/collection.py", line 443, in remove_songs
    if self.library is not None and self.library.masked(song):

AttributeError: 'SongLibrarian' object has no attribute 'masked'
```

**Comment by declension** [comment]
Hmm. I guess off the top of my head we should either expose a `masked` method on librarian too, or always try to get a library assuming it's a librarian (ugh)?

**Comment by lazka** [comment]
There is one instance where the playlist get created with a librarian instead of the main file library which exposes the masking. I'm trying to get rid of it atm.
