### ISSUE TITLE
Remove device support

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#2415]
* It's hardly tested code
* We only support players with MSC, which are rare I guess.
* It's linux only

Thoughts?

(I still use my sans clip often, but I just use nautilus for filling it anyway..)

**Comment by declension** [comment]
Yep it feels like dead code, and takes up space in the UI. If it supported Mass media, then that would be great (see #1148) but it doesn't.
 
So :+1:  from me...

**Comment by lazka** [comment]
OK.

If someone wants to work on bringing it back in some form, I'd suggest making it a plugin for a specific use case and continue from there.
