### ISSUE TITLE
[3.9.0] on Windows XP nothing happens ...

### ISSUE THREAD

**Issue by marmz** [quodlibet/quodlibet#2416]
I just installed Quod Libet **3.9.0** on **Windows XP**:
when launching the executables (Quod Libet / Ex Falso) nothing happens, no errors are thrown.

Same issue with the "portable" version.
Maybe i will try with a previous release ...

**Comment by lazka** [comment]
Windows XP isn't supported/tested since 2.6 as far as I remember. Some early 3.x might work if you install the vsc 2008 redist package.

**Comment by marmz** [comment]
well, just tried Quod Libet: 
- **3.9.0**
- **3.8.1**
- **3.7.1**

but nothing ..

for information ... i have installed **Microsoft Visual C++ Redist**.
- **2005**
- **2008**
- **2010**
- **2013**

**Comment by lazka** [comment]
Yeah, 3.7+ definitely wont work, I think we've started using Vista+ API in 3.3 and since 3.7 many of our dependencies also dropped XP support.

**Comment by marmz** [comment]
okok.. thank ;)

Anyway, i went back through releases, and finally i got version 3.2.2 to start in XP :)

Of course, when i try to "add" a Directory from the toolbar, the app. crashes and terminate ......

**Comment by lazka** [comment]
Maybe try an old musicbee: https://getmusicbee.com/forum/index.php?topic=18444.0
or foobar2000: https://www.foobar2000.org/download
