### ISSUE TITLE
NameError: free variable 'CommandError' referenced before assignment in enclosing scope

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#2422]
https://sentry.io/quodlibet/quodlibet/issues/289964526/

```
NameError: free variable 'CommandError' referenced before assignment in enclosing scope
  File "quodlibet/main.py", line 122, in exec_commands
    except CommandError:

NameError: free variable 'CommandError' referenced before assignment in enclosing scope
```

**Comment by CreamyCookie** [comment]
Have never seen this exception before.

Anyway.. I could be missing something, but this [seems fixed](https://github.com/quodlibet/quodlibet/blob/8b58a81b077e00b32cc4ad30520ccc8ca70f4406/quodlibet/main.py#L121).. There's no assignment to `CommandError`. Closing.
