### ISSUE TITLE
"Tap BPM" plugin error when exiting

### ISSUE THREAD

**Issue by 07416** [quodlibet/quodlibet#2428]
The error can be ignored, but it appears that then closing the Tap BPM window isn't possible.

```
AttributeError: 'TapBpm' object has no attribute '_window'
------


Traceback (most recent call last):

  File "C:\Program Files (x86)\Quod Libet\lib\python2.7\site-packages\quodlibet\ext\songsmenu/tapbpm.py", line 200, in response
    self._window.hide()

AttributeError: 'TapBpm' object has no attribute '_window'
```

![capture3](https://user-images.githubusercontent.com/14923168/27013385-3a2ce464-4eeb-11e7-9e80-e72eaae21ecf.PNG)
---
- Quod Libet 3.9.1 (2eec3a541)
- Windows 10

**Comment by lazka** [comment]
Thanks.

Just curious, why didn't you use the "Submit Error Report" button?

**Comment by 07416** [comment]
@lazka I wanted to document the issue publicly. Should I have?

**Comment by lazka** [comment]
Either is fine. I was just wondering if the error reporting feature did not work for you.

https://sentry.io/share/issue/3134323431352e323932353132333537/
