### ISSUE TITLE
Quodlibet crashed

### ISSUE THREAD

**Issue by iondissonance** [quodlibet/quodlibet#2429]
Start Quodlibet
See this 

Quodlibet 3.9.1, openSUSE Tumbleweed

> mephisto@desktop:~> quodlibet
> 
> (quodlibet:11591): Gtk-WARNING **: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version
> 
> (quodlibet:11591): Gtk-WARNING **: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version
> 
> (quodlibet:11591): Gtk-WARNING **: Theme parsing error: gtk.css:71:36: The style property GtkCheckMenuItem:indicator-size is deprecated and shouldn't be used anymore. It will be removed in a future version
> 
> (quodlibet:11591): Gtk-WARNING **: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
> /usr/lib/python2.7/site-packages/quodlibet/qltk/entry.py:249: TypeError: Passing arguments to gi.types.Boxed.__init__() is deprecated. All arguments passed will be ignored.
>   INVALID = Gdk.RGBA(0.8, 0, 0)
> /usr/lib/python2.7/site-packages/quodlibet/qltk/entry.py:250: TypeError: Passing arguments to gi.types.Boxed.__init__() is deprecated. All arguments passed will be ignored.
>   VALID = Gdk.RGBA(0.3, 0.6, 0.023)
> E: 0.182: util.importhelper.load_dir_modules: models.py:183:__init__: TypeError: GObject.__init__() takes exactly 0 arguments (1 given)
> E: 0.188: util.importhelper.load_dir_modules: media.py:142:MediaDevices: TypeError: GObject.__init__() takes exactly 0 arguments (2 given)
> E: 0.202: util.importhelper.load_dir_modules: audiofeeds.py:260:AudioFeeds: TypeError: GObject.__init__() takes exactly 0 arguments (1 given)
> E: 0.276: errorreport.main.errorhook: quodlibetwindow.py:1155:__create_menu: TypeError: Gtk.UIManager.add_ui_from_string() takes exactly 3 arguments (2 given)
> mephisto@desktop:~>

**Comment by lazka** [comment]
Looks like pygobject is missing its Python overrides. Not sure how/why..

**Comment by iondissonance** [comment]
Install python2-gobject-Gdk, python3-gobject2 packages and all work. Add this packages to dependencies

**Comment by lazka** [comment]
Ah, thanks. I'll look into it.

**Comment by lazka** [comment]
I've added the dependency and added a comment upstream that the opensuse package split is useless: https://build.opensuse.org/package/show/openSUSE:Factory/python-gobject
