### ISSUE TITLE
Highlight repeat & shuffle mode states better

### ISSUE THREAD

**Issue by 07416** [quodlibet/quodlibet#2430]
As a person with normal eyesight, I have some issues telling if the repeat mode is on or off. 

![capture7](https://user-images.githubusercontent.com/14923168/27013675-37fa7354-4ef1-11e7-8995-76a14da8e658.PNG)
_repeat mode off_

![capture6](https://user-images.githubusercontent.com/14923168/27013676-3c34d0e0-4ef1-11e7-8150-b0f4bfcc3794.PNG)
_repeat mode on_

I suggest coloring the button in familiar blue (when on) instead of a shade of grey:

![untitled2](https://user-images.githubusercontent.com/14923168/27014232-64782276-4efd-11e7-8d2b-4068276cf58b.PNG)

**Comment by lazka** [comment]
What about this?

![screenshot from 2017-06-12 20-08-21](https://user-images.githubusercontent.com/991986/27048235-56131ade-4fab-11e7-86b2-fb88fce86385.png)
