### ISSUE TITLE
Waveform seek bar freezes UI

### ISSUE THREAD

**Issue by slosd** [quodlibet/quodlibet#2431]
When a new song starts the UI freezes pretty consistently for 25 sec until the waveform seek bar appears. My music folder is a mounted nfs share, which may be amplifying this effect in my case. 

openSUSE Leap 42.2
quodlibet-3.9.0-2.1

**Comment by slosd** [comment]
Seems like I jumped to a conclusion too soon. After disabling/enabling the plugin I can no longer reproduce this issue. I'll have to look into it some more.

**Comment by lazka** [comment]
It does decode the whole file and QL does not do all IO in threads, so that might be a problem. For why it's no longer reproducible, it might be in your filesystem cache now and no longer hitting the network.

**Comment by slosd** [comment]
I skipped to files it hadn't played in a while.
