### ISSUE TITLE
Plugin: Seek points

### ISSUE THREAD

**Issue by Meriipu** [quodlibet/quodlibet#2432]
Would a plugin that stores points in a field for each track, and whenever that track is played, it starts playing from and continues to the next songs at the timestamps A,B be feasible?

Some tracks have intros I would like to skip, but without the whole ordeal of reencoding it to a new track.

**Comment by declension** [comment]
Well this sounds like a use for bookmarks for a start.

And based on that - yes.

**Comment by Meriipu** [comment]
I will try looking into it though I might not get very far.

**Comment by Meriipu** [comment]
I have a pretty trashy implementation that kind of works
Apparently seeking immediately on song_started does not work?

https://github.com/Meriipu/quodlibet/blob/seekpoints/quodlibet/quodlibet/ext/events/seekpoints.py

I use a short callback timeout for point A (start_from).
I check for whether the current position is past point b (end_at) each tick (second, I guess?)

It reads the bookmarks SeekPoint_A and SeekPoint_B if they exist, otherwise do nothing. 

This is probably very not clean at all, and I have not tested it much.

**Comment by lazka** [comment]
>  Apparently seeking immediately on song_started does not work?

Try now

**Comment by Meriipu** [comment]
Seems to work, thanks.

**Comment by Meriipu** [comment]
There is likely room for improvement like a cleaner way to avoid unnecessary on_tick-checks when there is no B-point set to compare the current position to (than the method that was used in the implementation), though if it looks ok I suppose this can be closed.

**Comment by lazka** [comment]
The once a second check isn't that bad as long as it doesn't block the main loop too much. We wake up once second anyway for various reasons..

**Comment by Meriipu** [comment]
I had not reverted it to using the once a second check yet.
So at the moment when a track starts, it starts the tracker, checks for point A and seeks to it if it exists. Then on the first tick it checks whether point B exists, and if it does not, it destroys the tracker until next track-start. 

If a check "if not self._seekpoint_B: return" in _on_tick is a really minor impact when B is None, then it would probably simplify the code a bit to just use enabled and disabled to start/stop the tracker as suggested.

**Comment by lazka** [comment]
> If a check "if not self._seekpoint_B: return" in _on_tick is a really minor impact when B is None, then it would probably simplify the code a bit to just use enabled and disabled to start/stop the tracker as suggested.

I think doing the work in every tick shouldn't be a problem. Feel free to change it if you want.
