### ISSUE TITLE
Fails to start in LXDE

### ISSUE THREAD

**Issue by yselkowitz** [quodlibet/quodlibet#2435]
quodlibet 3.9.1 fails to start in LXDE (or a custom lxsession-managed session) when GNOME dbus compatibility is enabled.  To reproduce:

1) Launch an LXDE session
2) Launch Preferences->Default applications for LXSession
3) In Settings tab, set Dbus->Gnome to ON.
4) Logout from and back in to LXDE.
5) Try starting Sound & Video -> Quod Libet.

Result:
"An Error Occurred"
And the relevant error being:
lxsession[PID]: dbus-gnome-session.vala:76: Error, lxsession doesn't implement this API

IOW lxsession's org.gnome.SessionManager implementation is incomplete.

Fix: [https://github.com/cygwinports-extras/quodlibet/blob/master/3.9.1-lxsession.patch](https://github.com/cygwinports-extras/quodlibet/blob/master/3.9.1-lxsession.patch)

**Comment by lazka** [comment]
Thanks. What's the exception thrown there in that case? I don't like the catch all approach without knowing more.

**Comment by yselkowitz** [comment]
TypeError: validate_object_path() argument must be string, not None

But why *not* a catch-all?  This is not essential functionality, and a failure here shouldn't prevent normal use of the program.

**Comment by lazka** [comment]
Thanks. I'd just like to understand the problem a bit more first.

**Comment by lazka** [comment]
I can reproduce the error. Thanks for the instructions.
