### ISSUE TITLE
Incorrect MPRIS volume scaling

### ISSUE THREAD

**Issue by JasonLG1979** [quodlibet/quodlibet#2439]
The volume widget uses cubic volume scaling not linear so you can't map MPRIS's volume 1 to 1. If you do your volume will be out of sync as it is now.

**Comment by JasonLG1979** [comment]
![screenshot from 2017-06-17 14-03-46](https://user-images.githubusercontent.com/6667703/27255572-df0384ba-5365-11e7-8bad-88bb258b73f9.png)

**Comment by lazka** [comment]
As far as I remember, we expose linear volume over MPRIS and use cubic for our own volume widget.

**Comment by JasonLG1979** [comment]
Yep my bad. The widget uses cubic.

So here:
https://github.com/quodlibet/quodlibet/blob/e12df98e180d6d1f6aa2ee74bdf3557a2e237a6d/quodlibet/quodlibet/ext/events/mpris/mpris2.py#L322

you'd want to do:
```python
player.volume = math.pow(value, 3.0 / 1.0)
```

And here:
https://github.com/quodlibet/quodlibet/blob/e12df98e180d6d1f6aa2ee74bdf3557a2e237a6d/quodlibet/quodlibet/ext/events/mpris/mpris2.py#L369

You'd want to do:
```python
return math.pow(player.volume, 1.0 / 3.0)
```

**Comment by JasonLG1979** [comment]
That should fix the scaling issue. That's what we do in Pithos.

**Comment by JasonLG1979** [comment]
That assumes player.volume is a property connected to your volume slider.

**Comment by lazka** [comment]
What makes you assume that the MPRIS volume isn't linear?

**Comment by JasonLG1979** [comment]
MPRIS volume is linear. But the volume widget is cubic. You have to convert back and forth.

**Comment by lazka** [comment]
I'm confused now, player.volume is linear, so why would we need to convert it before passing it to MPRIS?

**Comment by JasonLG1979** [comment]
> I'm confused now, player.volume is linear, so why would we need to convert it before passing it to MPRIS?

If it's the value of the volume slider then it's not linear, it's cubic.

**Comment by lazka** [comment]
Our volume slider just uses cubic for display purposes, player.volume is linear.

**Comment by JasonLG1979** [comment]
Are you sure because I just tested what I just posted and it fixed the issue?

**Comment by JasonLG1979** [comment]
![screenshot from 2017-06-17 14-58-42](https://user-images.githubusercontent.com/6667703/27255897-7aa4e51a-536d-11e7-856d-75e4841c0f0c.png)

**Comment by lazka** [comment]
My guess would be that the MPRIS client you have there just shows the linear volume as is.

**Comment by JasonLG1979** [comment]
The slider in my extension is linear. It's a 1 to 1 map to and from MPRIS from 0.0 to 1.0. You're not sending a linear value to MPRIS. At around 50% volume you're sending something like  0.129.

![screenshot from 2017-06-17 15-14-45](https://user-images.githubusercontent.com/6667703/27256013-c0df6bac-536f-11e7-9d4c-6290aa8e9c9d.png)

**Comment by lazka** [comment]
Why do you expect the sliders to match then? Our slider isn't linear while yours is.

**Comment by JasonLG1979** [comment]
They should match. The reason they don't is because you're sending a cubic value to MPRIS. MPRIS volume is suppose to be linear from 0.0 to 1.0 not cubic.

**Comment by JasonLG1979** [comment]
At 50% volume you're sending 0.129. By my math 0.129 is nowhere near 50% of 1.0.

**Comment by lazka** [comment]
Where do you get the 50% from?

**Comment by JasonLG1979** [comment]
> Where do you get the 50% from?

Your volume icon tooltip

**Comment by lazka** [comment]
> Your volume icon tooltip

The shows the value of the slider, 0.129^(1/3)=0.5

**Comment by JasonLG1979** [comment]
So the volume slider tooltip doesn't show the volume level that's helpful?

**Comment by JasonLG1979** [comment]
So at the half way point of the slider the volume of your player is not 50% ?

**Comment by JasonLG1979** [comment]
Gstreamer volume is also linear are you not converting the cubic slider value when going back and forth to and from Gstreamer also?

**Comment by JasonLG1979** [comment]
https://github.com/pithos/pithos/blob/master/pithos/pithos.py#L1101-L1110

**Comment by JasonLG1979** [comment]
If you're sending 0.129 to Gstreamer when your slider is at 50% you're doing that wrong too, sorry.

**Comment by lazka** [comment]
> So at the half way point of the slider the volume of your player is not 50% ?

The widget tries to mirror what the GNOME sounds settings panel and pavucontrol show.

> Gstreamer volume is also linear are you not converting the cubic slider value when going back and forth to and from Gstreamer also?

We do.

> https://github.com/pithos/pithos/blob/master/pithos/pithos.py#L1101-L1110

They convert it again for MPRIS: https://github.com/pithos/pithos/blob/master/pithos/plugins/mpris.py#L355

**Comment by JasonLG1979** [comment]
> They convert it again for MPRIS: https://github.com/pithos/pithos/blob/master/pithos/plugins/mpris.py#L355

I know, I wrote most of the MPRIS implementation in Pithos. Just do me a favor and actually try what I said to do and see for yourself.

**Comment by JasonLG1979** [comment]
https://github.com/pithos/pithos/blame/master/pithos/plugins/mpris.py

**Comment by lazka** [comment]
OK, so you propose changing the MPRIS volume to be non-linear. Which brings me back to my original question:

What makes you assume that the MPRIS volume isn't linear?

**Comment by JasonLG1979** [comment]
Have you looked at what you're sending to MPRIS. Just take 2 minutes and fire up D-Feet, set your Volume to 50% and see what you're sending to MPRIS. It should be 0.5 which is 50% of 1.0 on a linear scale but it is not. You are clearly and obviously not sending a linear value to MPRIS. Look I'm done if all you want to do is argue and not actually look at what your app is doing.

**Comment by JasonLG1979** [comment]
https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/wiki/Known-Player-Bugs#quod-libet

**Comment by lazka** [comment]
I guess I'm missing something then. If I set it to 0.5 I see 0.5 in d-feet. Sorry for wasting your time.

**Comment by JasonLG1979** [comment]
With PulseAudio installed or not?

**Comment by JasonLG1979** [comment]
What output sink in Gsreamer are you using? Volume works differently dependent on what output sink you use.

**Comment by JasonLG1979** [comment]
On my system, Fedora 25 GNOME with quodlibet installed from the latest git master running the default config I do not get a linear value from your MPRIS implementation.

**Comment by lazka** [comment]
Using GStreamer pulsesink with pulseaudio. If I start "GST_DEBUG=pulse:5 quodlibet" the volume printed when changing it matches the value in d-feet.

**Comment by JasonLG1979** [comment]
> Using GStreamer pulsesink with pulseaudio. If I start "GST_DEBUG=pulse:5 quodlibet" the volume printed when changing it matches the value in d-feet.

PulseAudio also uses a cubic volume scale.

**Comment by JasonLG1979** [comment]
![screenshot from 2017-06-18 06-58-33](https://user-images.githubusercontent.com/6667703/27260514-94911206-53f3-11e7-8755-9280b02ca23a.png)

**Comment by JasonLG1979** [comment]
![screenshot from 2017-06-18 07-00-38](https://user-images.githubusercontent.com/6667703/27260522-dc925d8a-53f3-11e7-8538-5ff5bbadd32b.png)

**Comment by lazka** [comment]
> PulseAudio also uses a cubic volume scale.

Yeah, but pulsesink, which is printing this message does not https://cgit.freedesktop.org/gstreamer/gst-plugins-good/tree/ext/pulse/pulsesink.c#n2408

**Comment by JasonLG1979** [comment]
Look I'm done beating a dead horse.
