### ISSUE TITLE
Clarify purpose of browsers/playlists/main.py: __check_current

### ISSUE THREAD

**Issue by Meriipu** [quodlibet/quodlibet#2446]
In browsers/playlists/main.py, what does the method __check_current do (or rather, what is its purpose) ?
https://github.com/quodlibet/quodlibet/blob/master/quodlibet/quodlibet/browsers/playlists/main.py#L304
```
    def __check_current(self, model, path, iter):
        model, citer = self.__selected_playlists()
        if citer and model.get_path(citer) == path:
            songlist = qltk.get_top_parent(self).songlist
            self.activate(resort=not songlist.is_sorted())
```

Not running it seems to fix #2253 for me, but I noticed at least one thing that breaks:
I am in the playlist browser (ctrl+2), and have a playlist selected. If I drag and drop a track to the playlist I am in from the tracklist in the playlist (so to add a duplicate track), the playlist does not update with the new track until I select a different playlist. 

Other than that I have not noticed anything that breaks. 

__check_current (only?) seems to be called as a result of the signal row-changed.

**Comment by lazka** [comment]
For such cases it's always good to have a look at the blame output: https://github.com/quodlibet/quodlibet/blame/master/quodlibet/quodlibet/browsers/playlists/main.py

row-changed is not the best place for this as it's usually just meant for updating the view. +1 for getting rid of it.

**Comment by Meriipu** [comment]
I have no idea how it could be changed though.
If the only thing that breaks is that the playlist is not reloaded when it grows (or shrinks?) then maybe an extra check for whether the playlist actually grew or shrunk, or a separate callback for that and removing this.

I am not very into gtk concepts like signals, eventsl and updates at all though.

**Comment by Meriipu** [comment]
since it was removed with that commit I suppose this can be closed unless maybe the reason it was there in the first place resurfaces.
