### ISSUE TITLE
Add shortcut to switch tabs in "Edit tags" window

### ISSUE THREAD

**Issue by spxxxk** [quodlibet/quodlibet#2452]
Eg, thinking of Ctrl+tab/Ctrl-shift-tab.

**Comment by lazka** [comment]
I think alt+1/2/3/4 works if the notebook has focus. Would it be OK if we make these work without focus?

**Comment by spxxxk** [comment]
Sure. Could be even better. 

But alt+num doesn't seem to work for me. Could be because I'm on an azerty keyboard on a laptop.
When focused I can use left and right arrows though.

**Comment by declension** [comment]
I'd be keen for ctrl-tab / ctrl-shift-tab (additionally I guess) if possible
