### ISSUE TITLE
Python 3 switch

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#2467]
The macOS part is done now on travis and everything worked as expected so far.
The only remaining thing is that versioning the DB could improve the startup time by a bit by skipping the py2 upgrade, but I don't care enough right now.

1) For 3.10: Switch the official Windows build to Python 3
2) Collect/Fix errors
3) For 3.11: Switch the rest
4) After 3.11: Drop Python 2 support

**Comment by lazka** [comment]
It came up on IRC that maybe we just switch everything at once (and maybe call it 4.0 so breakage is a bit expected?)

**Comment by declension** [comment]
...though we might want to have some "big features" for 4.0 too, of course, to balance out all those "new" bugs...

**Comment by declension** [comment]
Timing seems good, with Ubuntu 17.10 (now out) officially dropping PY2.

**Comment by lazka** [comment]
> Timing seems good, with Ubuntu 17.10 (now out) officially dropping PY2.

Many of our dependencies aren't on the default ISO, so this doesn't change much.

**Comment by lazka** [comment]
If there are any remaining 4.0 issues, please add them to the 4.0 milestone

**Comment by lazka** [comment]
Debian/Ubuntu PPA switched to py3
