### ISSUE TITLE
An exception has occured in Quod Libet

### ISSUE THREAD

**Issue by alexloomis** [quodlibet/quodlibet#2468]
Please file a new issue at https://github.com/quodlibet/quodlibet/issues/new
[Dump_20170707_105159.txt](https://github.com/quodlibet/quodlibet/files/1131346/Dump_20170707_105159.txt)

**Comment by lazka** [comment]
This should be fixed for a while. Any idea why you are using such an old development version of Quod Libet on Arch?

**Comment by alexloomis** [comment]
I had quodlibet-git installed from the AUR and never updated it, not sure why. Switching to the usual repo and updating.
