### ISSUE TITLE
Column sort not working with optional column "performer"

### ISSUE THREAD

**Issue by cmerr388** [quodlibet/quodlibet#2477]
New to QuodLibet but like it so far.  Note a bug in the column sort where the optional parameter ~performer does show with correct data but will not sort.  When sorted with this column, it defaults to "Album" instead.

**Comment by Meriipu** [comment]
it sorts on ~performer for me if the data exists, though a lot majority of my tracks have blank performer fields and get sorted piled above or below the ones that have it when sorted on performer. In the latter case it seems to sort on album as a secondary sort key to (the blank) performer.

**Comment by cmerr388** [comment]
The data for perform is populated as you can see from the attached screenshots.  Changing the sort on performer does not sort by performer but Album. 
![sort perform down](https://user-images.githubusercontent.com/30178853/28368336-ffe8574a-6c61-11e7-9014-086118f27085.png)
![sort performer up](https://user-images.githubusercontent.com/30178853/28368335-ffe7d284-6c61-11e7-8bce-91740570a66f.png)
