### ISSUE TITLE
UI: Option to have solid scrollbar

### ISSUE THREAD

**Issue by Meriipu** [quodlibet/quodlibet#2487]
Are solid scrollbars (with reserved space) even possible in GTK? It is a bit tricky for me to see the current scrollbars always, and they tend to just barely but in a somewhat distracting way cover up the bottom element in lists whenever I move my cursor.

**Comment by lazka** [comment]
We default to it on macOS: https://github.com/quodlibet/quodlibet/blob/master/quodlibet/quodlibet/_init.py#L251

**Comment by MartinBorg** [comment]
On 2017-07-18 13:23, Christoph Reiter wrote:
> We default to it on macOS: https://github.com/quodlibet/quodlibet/blob/master/quodlibet/quodlibet/_init.py#L251

Works great on Linux, too:

$ GTK_OVERLAY_SCROLLING=0
$ export GTK_OVERLAY_SCROLLING
$ quodlibet

**Comment by lazka** [comment]
> is it a sensible thing to have an option for?

If it affects all gtk+ applications I think it would be better if you override the setting globally somehow as @MartinBorg suggested.

But if you care enough to provide a patch for adding it to the advanced settings plugin, that would be fine with me.
