### ISSUE TITLE
DSD (.dsf) Support

### ISSUE THREAD

**Issue by mayanez** [quodlibet/quodlibet#2491]
I am quite enjoying this player. However, I have a large collection of DSD files and realized it doesn't seem to support playback for this. Is this something that is planned? How much effort would be involved in adding support in case I decide to do a PR?

Thanks!

**Comment by lazka** [comment]
It wouldn't be to hard tagging wise as mutagen already supports it. But, last time I checked there was no decoder for this.

Which operating system?

**Comment by mayanez** [comment]
Yes I saw mutagen has support. So from my understanding `ffmpeg` can decode dsf. I'm on Arch Linux.

**Comment by lazka** [comment]
See https://bugzilla.gnome.org/show_bug.cgi?id=721186 and the referenced https://bugzilla.gnome.org/show_bug.cgi?id=779805

**Comment by lazka** [comment]
For future reference, mpv can play those files here.

**Comment by mayanez** [comment]
I'm not entirely sure how those bugs fit into the grander scheme of things yet as I'm not that familiar with the architecture of linux audio. However, looking into the mainline kernel, there is native support for DSD via ALSA (See https://github.com/torvalds/linux/blob/master/sound/usb/quirks.c#L1326). Also, this might be useful https://github.com/lintweaker/python-dsd-tools

**Comment by lazka** [comment]
The default pipeline would be something like `QL -> (GStreamer <-> ffmpeg) -> pulseaudio -> kernel` and the interface between GStreamer and ffmpeg is currently missing some things.

We don't do any playback ourself here, so for DSD to work the following has to work first `gst-play-1.0 somefile.dsf`

**Comment by lazka** [comment]
I've added support in QL now. Once GStreamer adds support things should just work.

As there is nothing more we can do here, I'm closing this.
