### ISSUE TITLE
Can pause but not play, with both pause and play buttons

### ISSUE THREAD

**Issue by joshtriplett** [quodlibet/quodlibet#2495]
I have a bluetooth headset with a play/pause button; rather than sending "play" every time, it alternately sends "play" and "pause". These do get properly translated into AudioPlay and AudioPause keys. quodlibet correctly responds to the "pause" by pausing, but the "play" does not resume playback.

quodlibet 3.7.1 from latest Debian unstable, running under GNOME 3.22.

**Comment by lazka** [comment]
>  These do get properly translated into AudioPlay and AudioPause keys. 

How did you check that?

"quodlibet --debug" should print the executed action, anything standing out there?

**Comment by joshtriplett** [comment]
> How did you check that?

I checked the underlying input device with `libinput debug-events` (it sends PLAYCD (200) and PAUSECD (201)), and then checked the translated keys (AudioPlay and AudioPause) by using GNOME's keyboard shortcut editor (without saving).

> "quodlibet --debug" should print the executed action, anything standing out there?

No reaction to "play" at all. Pause produces this:
```
D: 42.114: MMKeysHandler._callback: Event 'pause' from 'GnomeBackend'
```

I'll attach a test program to help reproduce this without needing a headset/keyboard that sends these keys.

**Comment by joshtriplett** [comment]
Compile the following program as `uinput-key`. Load the `uinput` module (`sudo modprobe uinput`). Run `sudo ./uinput-key 163` to send `KEY_NEXTSONG`, which should work and switch to the next song. With quodlibet playing, run `sudo ./uinput-key 201` to send `KEY_PAUSECD`, which should pause. With quodlibet paused, run `sudo ./uinput-key 200` to send `KEY_PLAYCD`, which does nothing, though it should start playing.

```c
#include <err.h>
#include <fcntl.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <linux/uinput.h>
#include <unistd.h>

void emit(int fd, int type, int code, int val)
{
   struct input_event ie = { .type = type, .code = code, .value = val };
   write(fd, &ie, sizeof(ie));
}

int main(int argc, char *argv[])
{
   struct uinput_setup usetup = { .id.bustype = BUS_VIRTUAL, .name = "uinput-key" };
   int fd;
   int key;

   if (argc != 2)
       errx(1, "Usage: uinput-key keycode");

   fd = open("/dev/uinput", O_WRONLY);
   if (fd < 0)
       err(1, "/dev/uinput");
   key = atoi(argv[1]);
   if (key <= 0)
       errx(1, "Invalid keycode");

   ioctl(fd, UI_SET_EVBIT, EV_KEY);
   ioctl(fd, UI_SET_KEYBIT, key);
   ioctl(fd, UI_DEV_SETUP, &usetup);
   ioctl(fd, UI_DEV_CREATE);

   sleep(1);

   emit(fd, EV_KEY, key, 1);
   emit(fd, EV_SYN, SYN_REPORT, 0);
   emit(fd, EV_KEY, key, 0);
   emit(fd, EV_SYN, SYN_REPORT, 0);

   ioctl(fd, UI_DEV_DESTROY);
   close(fd);

   return 0;
}
```

**Comment by lazka** [comment]
Thanks. Looks like gnome-settings-daemon doesn't forward the last event to us (checked with `dbus-monitor "interface=org.gnome.SettingsDaemon.MediaKeys" `)

**Comment by lazka** [comment]
And looks like gnome-settings-daemon gets the mapping from dconf, where it's saved under "/org/gnome/settings-daemon/plugins/media-keys/play" which is "XF86AudioPlay" here.

I don't know how things work below that layer, any ideas?

**Comment by joshtriplett** [comment]
@lazka As far as I can tell, PLAYCD does get translated to XF86AudioPlay. And as far as I can tell from the keyboard shortcuts dialog, that's the key mapped to the "Play" action.

**Comment by lazka** [comment]
a bit more investigating.

* with `xinput test-xi2 --root` both events look the same
* with `xev -root` things look different
* the media-keys plugin in gnome-setting-daemon gets the events over dbus from gnome shell (grep for "AcceleratorActivated")
* gnome shell gets the events from mutter (grep for accelerator-activated)
* ..?

**Comment by lazka** [comment]
Instead of doing more guesswork I've filed a bug with mutter: https://bugzilla.gnome.org/show_bug.cgi?id=785350

**Comment by lazka** [comment]
Also filed https://bugzilla.gnome.org/show_bug.cgi?id=785995 which might be related

**Comment by lazka** [comment]
I don't think there is anything we can do from our side here, so I'm closing this. If anything interesting in the upstream bugs happens I'll post it to this issue.
