### ISSUE TITLE
Gnome Multimedia Keys: Not all actions supported

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#2499]
There are a few unhandled actions which we could support: Rewind, FastForward, Repeat, Shuffle

**Comment by lazka** [comment]
The events can be emulated under X11 using xdotool:

```
xdotool key XF86AudioRewind
xdotool key XF86AudioRepeat
xdotool key XF86AudioForward
xdotool key XF86AudioRandomPlay
```

**Comment by LudoBike** [comment]
I'm working on this issue so I'm trying to understand how it works. 

Currently I'm understanding that there is the backends which catch the signal and then it communicates with the MMKeysHandler using MMKeysAction. The keys are associated with action in MMKeysHandler._callback().

In fact my problem is to know what I have to put in GnomeBackend._EVENTS (in gnome.py). For example for the shuffle I don't know if it is `"Shuffle": MMKeysAction.SHUFFLE` or `"RandomPlay": MMKeysAction.SHUFFLE`.

Furthermore as I am on i3wm, my backend isn't GnomeBackend (`D: 0.495: mmkeys.find_active_backend: Found 'KeybinderBackend'` in the log with `./quodlibet.py --debug`) so I can't test my changes. Is there a way to test them without installing a virtual machine ?

**Comment by lazka** [comment]
> In fact my problem is to know what I have to put in GnomeBackend._EVENTS (in gnome.py). For example for the shuffle I don't know if it is "Shuffle": MMKeysAction.SHUFFLE or "RandomPlay": MMKeysAction.SHUFFLE.

It should be "Shuffle": https://github.com/GNOME/gnome-settings-daemon/blob/master/plugins/media-keys/README.media-keys-API

> Furthermore as I am on i3wm, my backend isn't GnomeBackend (D: 0.495: mmkeys.find_active_backend: Found 'KeybinderBackend' in the log with ./quodlibet.py --debug) so I can't test my changes. Is there a way to test them without installing a virtual machine ?

You can also implement it for the KeybinderBackend and test it there. xdotool might work there too.

> And I also need to know what the rewind function is, does it restart the current title ?
> Edit: same problem with forward, I guess it's the opposite of rewind.

Good question. I'd say have XF86AudioRewind seek back 10 sec and XF86AudioForward seek 10 sec forward, like we already do in other places: https://github.com/quodlibet/quodlibet/blob/46748eaf2568d2d6620976d2bf3198fc5df51894/quodlibet/quodlibet/qltk/quodlibetwindow.py#L791

**Comment by LudoBike** [comment]
>  You can also implement it for the KeybinderBackend and test it there. xdotool might work there too.

I tried to implement Repeat and RandomPlay in KeybinderBackend but it don't work with xdotool however, Rewind and Forward are regonize so I've tested my callback with these keys and it has the right behavior.

**Comment by LudoBike** [comment]
Is it the proper way to implement rewind and forward by writing BasePlayer.rewind() (resp. forward()) functions?

**Comment by lazka** [comment]
> Is it the proper way to implement rewind and forward by writing BasePlayer.rewind() (resp. forward()) functions?

Sounds good

**Comment by LudoBike** [comment]
The function __key_pressed use player.seek() function, however if I look in BasePlayer, seek isn't implemented (cf. https://github.com/quodlibet/quodlibet/blob/f58e102c9006fb78a1a51b1f2e6ad33916939ca5/quodlibet/quodlibet/player/_base.py#L208)

How does it works ?

**Comment by lazka** [comment]
> How does it works ?

BasePlayer is an abstract base class and partly implemented by the backends. For example the implementation of the GStreamer backend is here: https://github.com/quodlibet/quodlibet/blob/f58e102c9006fb78a1a51b1f2e6ad33916939ca5/quodlibet/quodlibet/player/gstbe/player.py#L873

**Comment by lazka** [comment]
All the needed interfaces are provided by BasePlayer so you can just copy the existing code.

But feel free to skip all this, we can always clean it up later..
