### ISSUE TITLE
Running tests locally: Trace/breakpoint trap

### ISSUE THREAD

**Issue by Meriipu** [quodlibet/quodlibet#2503]
Is there anything I have to do to run the full set of tests locally? If I try python setup.py test, it tends to fail after a short while. 

```
python setup.py test
running test
================================================================= test session starts ==================================================================
platform linux -- Python 3.5.3, pytest-3.1.2, py-1.4.33, pluggy-0.4.0
rootdir: /....../quodlibet/quodlibet, inifile:
plugins: timeout-1.2.0, pep8-1.0.6, cov-2.3.1
collected 2940 items 

tests/test___init__.py .....
tests/test_appdata_files.py ....
tests/test_browsers___init__.py .........
tests/test_browsers__base.py ..................................................................................................................................................................
tests/test_browsers_albums.py ...............
tests/test_browsers_audiofeeds.py ..
tests/test_browsers_collection.py .......
tests/test_browsers_filesystem.py .
tests/test_browsers_iradio.py ...........
tests/test_browsers_paned.py .Trace/breakpoint trap
```
though if I run the last test manually it succeeds:
python setup.py test --to-run=tests/test_browsers_paned.py

this on the other hand fails almost instantly with the same error:
python3 setup.py test --to-run=tests/test_commands.py

my kernel log says
Jul 24 21:08:17 Meowth kernel: traps: python[4523] trap int3 ip:7f4609941101 sp:7ffc153387a0 error:0

**Comment by lazka** [comment]
Which distro?

**Comment by Meriipu** [comment]
Gentoo

**Comment by lazka** [comment]
uh, ok, not something I can quickly test then.

You can either uncomment tests until it no longer crashes or use gdb to get a stacktrace.

**Comment by lazka** [comment]
We don't require any plugin atm

**Comment by Meriipu** [comment]
Installed dev-python/xvfbwrapper and everything works.

**Comment by lazka** [comment]
Good to know.

My guess would be it changes the timing of UI tests so they.. maybe happen to not crash. ?
