### ISSUE TITLE
amazon cover search is broken

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#2508]
```
<?xml version="1.0"?>
<ItemSearchErrorResponse xmlns="http://ecs.amazonaws.com/doc/2005-10-05/">
    <Error>
        <Code>AWS.InvalidAssociate</Code>
        <Message>Your XXXXXXXXXXXXXX is not registered as an Amazon Associate. Please register as an associate at https://affiliate-program.amazon.com/gp/associates/join/landing/main.html.</Message>
    </Error><
    RequestID>a279cafa-5716-4c3c-839a-3bf74afea7f5</RequestID>
</ItemSearchErrorResponse>
```

@wmeddie any idea why?

**Comment by wmeddie** [comment]
Ah sorry about that.  Amazon sent an e-mail last month about having to register as an associate which means providing tax information.  I've just completed the registration, but now I think they are verifying/limiting the store ID.  I'll see if there's anything I need to do to enable item search again.

**Comment by lazka** [comment]
lightning fast :) Thanks for keeping it working!

From quick test everything works again here.

**Comment by lazka** [comment]
Also confirmed on IRC. Thanks again.

**Comment by wmeddie** [comment]
It looks like there's also a restriction that if you don't use your store-id at least once every 180 days it'll be cancelled.  I think QL is using gnomestore-20 which I don't own, so we might get the same error after 180 days again.

**Comment by lazka** [comment]
What does "use" mean here?

**Comment by wmeddie** [comment]
I'm not sure, but I think it's "Someone opened an Amazon product page with the affiliate store-id".  But it might just be "Included it in the search query".  The former is much more likely though.

**Comment by lazka** [comment]
Ah, right, that makes sense. I think that was the ID used by Ubuntu to get money to the gnome foundation, but it's likely not used by anything anymore.

"electronicfro-20" by the EFF should be a good replacement I guess (not that it gives them anything because we don't link things..)

**Comment by wmeddie** [comment]
Yeah, we don't generate revenue at all, so it doesn't matter what you put for the ID.  If problems start happening again I might be able to change the store-id server-side and maybe advertise my boss's book on my blog to keep the ID alive.

**Comment by wmeddie** [comment]
Looks like my Amazon Associates account was closed due to lack of sales. So you might start getting bug reports from people on older versions now.

**Comment by lazka** [comment]
ok, thanks

**Comment by declension** [comment]
Yep I've just noticed this recently @wmeddie

**Comment by declension** [comment]
I'm happy to sign up for an Amazon associates account if that helps keep the album art search alive. Potentially even host / sponsor the proxy app thing (on AWS lambda, maybe?)
