### ISSUE TITLE
question about where to place test

### ISSUE THREAD

**Issue by Meriipu** [quodlibet/quodlibet#2513]
where would I place a test for picking a choice (cancel, ok) in a confirmation prompt on removal of tracks from e.g library or playlists? 

what about prompts on other actions such as when (mistakenly) trying to reorder playlists in the playlist browser and having it result in expanding a playlist with tracks instead?

**Comment by lazka** [comment]
What do you mean by "test" here?

**Comment by Meriipu** [comment]
So say the prompt did not exist, and after adding the prompt, I create a test to see whether actions that cause the prompt actually get cancelled if the cancel option is chosen, and actually get done if the ok-option is chosen.

if that is something that is testable and makes sense to test.
I assume with_response(Gtk.ResponseType) does something like this?

**Comment by lazka** [comment]
For test file placement, the tests usually mirror the file structure where the code to test resides.

Regarding if it makes sense to test something, that depends. Many Gtk UI things are really hard to test. If it complicates the code to test too much just let it be.. imo
