### ISSUE TITLE
Request: 'spotlight' - a suggestion of random albums from library

### ISSUE THREAD

**Issue by lukaszkruk** [quodlibet/quodlibet#2536]
An Android player I use with my NAS, [Qmusic](https://www.qnap.com/en-us/how-to/tutorial/article/how-do-i-play-my-music-through-qmusic), has a feature I love called Spotlight: when I start the app it shows a random selection of a few albums from my library. The albums are displayed as covers. It's great for rediscovering albums from my library I haven't listened to for a while. 

Would it be possible to have a similar feature in Quod Libet? Or is there maybe a search string I could put into cover grid browser to get similar effect? Alternatively, I know some Python but have never written a plugin for anything, would implementing something like this be tough for a newbie?

Thanks

**Comment by lazka** [comment]
What I usually do is press "ctrl+m" a few times to jump to random albums until I find something I like.

**Comment by lukaszkruk** [comment]
Thank you for the tip, this is quite helpful. Doesn't quite do the trick, but I will certainly be using it.

**Comment by declension** [comment]
@lukaszkruk FYI in latest build I've added features to allow more powerful Python expressions. You can get a basic Spotlight (updated every minute) by using this query:

`@(python: Random((int(_ts / 60), a)).random() < 0.01)`

**Comment by lukaszkruk** [comment]
I'm running version 3.9.1 from lazka/ppa - should this work? I get an empty result from this query.

**Comment by lukaszkruk** [comment]
Great to know, I see it's already documented too!

I just switched to the unstable repo and am running 6d14d2aab - should this work already? I currently get empty results from this query.

**Comment by declension** [comment]
No  https://github.com/quodlibet/quodlibet/commit/6d14d2aabbd9a051604987ac83803ebec022eab3 is not new enough.

You'll have to wait till a newer build is generated or build from source directly.

Also, you'll need to enable the Python query plugin for this to work. If still no joy, run with `--debug`, I've added much better error logging.

**Comment by lukaszkruk** [comment]
I'll be patient then. Thank you again, this is an incredible level of customer support :D
