### ISSUE TITLE
macOS: lyricswindow plugin not available

### ISSUE THREAD

**Issue by MunMunMiao** [quodlibet/quodlibet#2539]

**Comment by lazka** [comment]
webkit is a pain to build and requires security updates every week, which is why I haven't bothered yet.

**Comment by adidi199** [comment]
@lazka So I will not be able to use the lyrics function yet?

**Comment by lazka** [comment]
Not right now, maybe in a future release.

**Comment by adidi199** [comment]
@lazka Thank you

**Comment by CreamyCookie** [comment]
Closing as the plugin was removed.
