### ISSUE TITLE
Various GTK deprecation warnings

### ISSUE THREAD

**Issue by declension** [quodlibet/quodlibet#2540]
### Steps
run `python3 -Wall quodlibet/quodlibet.py`

### Output
Bit of a catch-all but some notable problems:
 * ...`/quodlibet/quodlibet/browsers/playlists/menu.py:33: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations`
 * ...`/quodlibet/quodlibet/ext/events/animosd/osdwindow.py:292: PyGIDeprecationWarning: GObject.get_current_time is deprecated; use GLib.get_current_time instead                                                      
  delta = GObject.get_current_time() - self.fade_start_time`
* ...`/quodlibet/quodlibet/ext/events/animosd/osdwindow.py:292: PyGIDeprecationWarning: get_current_time is deprecated; use GLib.get_real_time() instead                                                               
  delta = GObject.get_current_time() - self.fade_start_time`
* ...`/quodlibet/quodlibet/ext/events/animosd/osdwindow.py:51: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "type" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations`
*  ...`/quodlibet/quodlibet/qltk/pluginwin.py:404: DeprecationWarning: Gtk.Button.set_focus_on_click is deprecated`
    `errors.set_focus_on_click(False)`

**Comment by lazka** [comment]
Note that GTK+ deprecation warnings in many cases mean that those things will be removed in gtk4 and might only have a replacement in gtk4.

**Comment by lazka** [comment]
xalign is special here as the method is a method of GtkMisc and the property is a property of GtkLabel

**Comment by zsau** [comment]
After more testing, I discovered that nothing happens when I assign to a label's `margin` property (nor `margin_start`, `margin_top`, etc). Not sure if that's a bug.

`set_margin_start()` and friends work as expected, but there's no `set_margin()` so it seems the verbose way is the only working method.

**Comment by lazka** [comment]
oh, it's `label.props.margin_start` btw :)

**Comment by zsau** [comment]
...that explains why `__clabel.xalign = 0` didn't work either. I wish there were a warning for that.

**Comment by declension** [comment]
Perhaps we should close this now?
