### ISSUE TITLE
Soundcloud / iradio / file browser: rendering of separators is broken

### ISSUE THREAD

**Issue by declension** [quodlibet/quodlibet#2541]
It seems on my setup
 * the background has become white (unless I was imagining this before?)
 * The separators are suddenly more pronounced
 * The height-rendering messes up completely when hovering over rows making it hard to use

It actually appears much _more_ broken than this image, but the act of taking the screenshot seems to force a re-render...

![image](https://user-images.githubusercontent.com/3322808/29409202-21c930ee-8343-11e7-90a0-543a58893b1d.png)

**Comment by declension** [comment]
This also affects Internet Radio Browser (arguably worse but they're both bad)

**Comment by declension** [comment]
![image](https://user-images.githubusercontent.com/3322808/29409840-ed17620a-8345-11e7-8220-5805321015aa.png)

**Comment by Muges** [comment]
This is a bug which affects several GTK themes. See [ubuntu-themes bug report](https://bugs.launchpad.net/ubuntu-themes/+bug/1701512) and https://github.com/exaile/exaile/issues/362.

**Comment by genodeftest** [comment]
According to upstream, this bug has been fixed in Ubuntu.

**Comment by lazka** [comment]
@genodeftest , thanks

http://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-themes/trunk/revision/560

**Comment by declension** [comment]
Didn't notice, but this is on the filesystem browser too. Quite unusable, perhaps we should consider a workaround whilst we wait for latest Ubuntu...

**Comment by declension** [comment]
Works here perfectly - thanks @lazka :slightly_smiling_face:
