### ISSUE TITLE
downloading in audiofeed broken

### ISSUE THREAD

**Issue by omegerard** [quodlibet/quodlibet#2543]
When you right-click on a podcats in the audio feed, nothing happens. Hence, you can't download.
(macOS Sierra - Version 10.12.6)
[quodlibet.debug.zip](https://github.com/quodlibet/quodlibet/files/1236293/quodlibet.debug.zip)

**Comment by declension** [comment]
Thanks for reporting. Audiofeed is disabled currently, but it shouldn't be behaving like _this_.

Is this on OS X? Please add some details to this ticket - we have some info on
[filing bug reports](http://quodlibet.readthedocs.io/en/latest/development/contributing.html)

Can you run `quodlibet --debug` and paste any errors that result (this will be improved when #2077 is solved)?

**Comment by lazka** [comment]
See 9afb2ae343246

**Comment by lazka** [comment]
Noticed that we already have something open for this: #2543
