### ISSUE TITLE
[Ex Falso] Missing feedparser module in Fedora 26 package

### ISSUE THREAD

**Issue by gariguette666** [quodlibet/quodlibet#2545]
I was unable to launch **Ex Falso 3.9.1** after a raw installation from the **Fedora 26** repositories and discovered that was due to a missing Python module called _feedparser_ in the package.

Indeed when I try to launch the application using the terminal it prints the following message:
`E: 0.266: errorreport.main.errorhook: update.py:20:<module>: ImportError: No module named feedparser`.

As a workaround I did install manually the package using the following command: `sudo pip install feedparser` and Ex Falso launches correctly.

**Comment by lazka** [comment]
Is this with the package from the official fedora repos or the ones listed here: https://quodlibet.readthedocs.io/en/latest/downloads.html#fedora

**Comment by gariguette666** [comment]
From the official Fedora repositories.

**Comment by lazka** [comment]
Thanks. Looks like this is already know in Fedora: https://bugzilla.redhat.com/show_bug.cgi?id=1461484

I'd suggest you "sudo pip uninstall feedparser" and install python-feedparser through yum/dnf instead to avoid future conflicts.

**Comment by gariguette666** [comment]
Thanks for the advice!
