### ISSUE TITLE
ListenBrainz support/plugin

### ISSUE THREAD

**Issue by Freso** [quodlibet/quodlibet#2549]
[ListenBrainz](https://listenbrainz.org/) is a new open source and open data alternative to Last.fm. While it *would* be possible to simple call ListenBrainz using the scrobbling API, adding support for [ListenBrainz's native API](https://listenbrainz.readthedocs.io/) would allow for a lot more information about each listen to be submitted (e.g., all MusicBrainz identifiers (and not just the Recording one)).

**Comment by declension** [comment]
Duplicate of #2397 ?

**Comment by Freso** [comment]
Yes, for some reason my searches for "brainz" and "listenbrainz" did not show that… 😖
