### ISSUE TITLE
Sidebar resizing

### ISSUE THREAD

**Issue by elbeardmorez** [quodlibet/quodlibet#2556]
@declension
The recent #152 work added a lovely sidebar which looks great, especially for embedded lyrics. However, just a small gripe in that one doesn't appear to be able to make the contents of the pane smaller than some fixed value, and thus extra unwanted white space persists. See the off-centered look of the lyrics in the pic below.

[sidebar spacing issue](http://picpaste.com/pics/dd335693ebfb87e62759e82e853a18b0.1504690286.png)

**Comment by declension** [comment]
Thanks. Not sure if that fixes it, I couldn't see much difference. Still, it was definitely unnecessary now...

**Comment by elbeardmorez** [comment]
Excellent, thanks!

![white space collapsing nicely!](http://picpaste.com/79fbcfc91161978d26afe5ccafcf14bc.png)

**Comment by declension** [comment]
Thanks for investigating :+1:

**Comment by elbeardmorez** [comment]
should just add that if other sidebars are also open (e.g. Python Console) then they (well, 'it', in this example) seems to hinder the correct collapsing of the ViewLyrics pane. doesn't bother me at all, just noting!

**Comment by declension** [comment]
Hmm, @elbeardmorez if you can please post a screenshot

**Comment by elbeardmorez** [comment]
open ViewLyrics alone
[perfect](http://picpaste.com/948250299c6211780aed3a24da24abc9.png)
open Python Console
[still perfect](http://picpaste.com/42570b5147e0b81b6df3c0279860b0b1.png)
move mouse on and off pane
[why did the lyrics appear to move?](http://picpaste.com/a772dafc2c738dd6f8bd6d9e412ee4ce.png)
pane grows due to the content of the Python Console side bar, which appears to be wrapping its lines, but **really** slowly in the background. every time you move the move on/off the View Lyrics content it disappears every so slightly more
[where did my nicely centered lyrics go?](http://picpaste.com/7125fdae3cf3d3067fedeb0b749efffe.png)
if you can pick out the red dot on the above image, that's where i had my mouse, moving a couple of pixels left, a couple right over and over.

note, on the Python Console word wrapping, my 'current working directory' is very long, and is the culprit for the 'needs to be wrapped' charge ..hence if your work is in /short/path then you might not see this.

flicking onto the actual Python Console and then manually resizing the sidebar bigger then smaller to 'force redraws' gets the line wrapped properly and from then on, switching back to the ViewLyrics pane there are no issues.

not sure what to suggest .."on enable any sidebar show it immediately to force it to realise its available space properly" ..or maybe there's something simpler, i've not looked. anyway, there are of course much bigger fish to fry!
