### ISSUE TITLE
 Wrong cover pictures shown 

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#2557]
See https://groups.google.com/forum/#!topic/quod-libet-development/ual2XnbUBSA

I couldn't reproduce, but needs another look to be sure.

[grimm_ruhrpott_sterntaler.zip](https://github.com/quodlibet/quodlibet/files/1280709/grimm_ruhrpott_sterntaler.zip)

**Comment by urielz** [comment]
I can't reproduce either.

**Comment by CreamyCookie** [comment]
Cannot reproduce either. Closing.
