### ISSUE TITLE
LyricsWindow doesn't scroll to lyrics section any more

### ISSUE THREAD

**Issue by declension** [quodlibet/quodlibet#2558]
On my system the magic JS doesn't seem to be doing its thing, maybe some new async stuff on the webpage. 

```
Python: 3.5.3
Mutagen: 1.38
GTK+: 3.22.11 (X11)
PyGObject: 3.22.0
```

**Comment by CreamyCookie** [comment]
Closing this for #3631 (which also mentions how broken it is)
