### ISSUE TITLE
Debian Testing still has version 3.7.1

### ISSUE THREAD

**Issue by pschwede** [quodlibet/quodlibet#2559]
Just saying.

**Comment by lazka** [comment]
Not much we can do, except look into flatpak maybe :)

**Comment by MartinBorg** [comment]
This is a bug you probably should open at Debian, not here.
But no need to do it, it's already there: https://bugs.debian.org/862074

**Comment by lazka** [comment]
Thanks @MartinBorg for the link

**Comment by pschwede** [comment]
Here is a work-around:
```bash
# install required packages for adding PPAs
sudo apt-get install software-properties-common python-software-properties

# add PPA
sudo add-apt-repository ppa:lazka/dumpingplace

# register lazka's key "Lauchpad stable"
sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 026382005806C7C4
```
(via [my blog ;-)](https://splogz.wordpress.com/2017/09/09/solved-how-to-install-newest-quodlibet-on-debian/))

**Comment by MartinBorg** [comment]
@pschwede The Debian maintainer uploaded 3.9.1 to unstable today! (It takes some hours until it is available, though.)
