### ISSUE TITLE
ViewLyrics window does not disappear when pressing Alt-l

### ISSUE THREAD

**Issue by ghost** [quodlibet/quodlibet#2562]
Version: 3.9.1
Desktop: XFCE 4.12.3 on Debian 9 testing (amd64)

Expected behaviour: ViewLyrics is shows external lyrics files. When either pressing Alt-l or clicking on the arrow, the lyrics window disappears and the full window can used for song browsing.

Actual behaviour: ViewLyrics does show external lyrics files. But when pressing Alt-l or clicking on the arrow, only the grey header area of the lyrics window disappears. The actual lyrics stay visible and not the complete window is used by the song browser view.

This was fine with 3.7.1-2 (Debian package).

(I have screenshots of the wrong behaviour, but drag & drop to GitHub does not work for me.)

**Comment by declension** [comment]
@MartinBorg Thanks for reporting. FYI you can also attach the files by clicking _selecting them_ in the comment box (or even using cut and paste).

The ViewLyrics plugin has recently been converted to a sidebar / UserInterface plugin, for this and other reasons. Could you try out a [development build](http://quodlibet.readthedocs.io/en/latest/development/devenv.html) and see if that's better? If it's urgent we could backport a fix to the `3.9.x` series, but IMO probably more trouble than it's worth.

**Comment by MartinBorg** [comment]
@declension No, it's not urgent. If it is (or will be) fixed anyway, just close this issue. Thanks for caring!

**Comment by CreamyCookie** [comment]
Seems this has been fixed by making it a sidebar.
