### ISSUE TITLE
Any changes to the playlists can not be saved

### ISSUE THREAD

**Issue by Terpki** [quodlibet/quodlibet#2564]
I'm trying to add some new songs to the playlists but after closing the app it is just ignoring all the changes. Deleting the songs is ignored as well. Sometimes it can save the changes after adding only 1 song, but another time it won't save the same song from the same folder. It's really weird. I am adding all the songs from the hard drive, not from any flash drive or ssd. I've just installed the app and have created few playlist with about 3000+ songs in it and everything was great untill that started to happen. I've checked the Help section on the website and I haven't found similar issue.

**Comment by declension** [comment]
Hi. Thanks for reporting. To help us investigate, please post some more details.

* Your OS and version
* Steps to replicate the problem (for us)
* What you expected to see
* What you actually saw
* A screenshot maybe if that helps explain
* Any logs

For the logs please start QL with `--debug`. This is very helpful to see what's going on internally

**Comment by Terpki** [comment]
Here is the link to the video of what is happening, hope it will help https://streamable.com/p11my
Sorry I'm not really sure how to start that debug process, can you please give me some more detailed instructions about it. 
I've tried to install the previous version of the program but rusults were the same.
I remember that everything was working fine and I was able to create several playlists with a bunch of songs in them, then I think I've turned on some plugins and after that I wanted to use my MIDI Contoller to start and close the program with just pressing a button on that controller, so I've created a .bat file with this line ( TASKKILL /F /IM quodlibet.exe ) so it can be activated when I want to close the program.
I think after that I've noticed that some playlists are empty, allthhough I added some songs into them before. Maybe one of these things is the reason, maybe not, I can't tell for sure.
Hopefully debugging will be helpful.

**Comment by Muges** [comment]
I was able to reproduce this issue on the latest commit of the master branch (eef5a50) on linux with python 2 and 3.

### Steps to replicate

 - create a new playlist from the playlist browser
 - add a song to this playlist via the right-click menu of the paned or filesystem or paned browsers (I only tried one those)
 - restart quodlibet

### Expected behaviour

The new playlist has a song.

### Actual behaviour

The new playlist has a song before restarting quodlibet, but is empty after restarting quodlibet.


Adding songs to existing playlists works as expected, and adds this to the logs:

```
D: 51.108: FileBackedPlaylist._emit_changed: Emitting changed (extend) for 1 song(s) from playlist "old" (1 titre) 
D: 51.110: qltk.completion.__update_song: Updating tag model for 1 songs
D: 51.110: qltk.completion.__update_song: Done updating tag model for 1 songs
D: 51.110: PlaylistsBrowser.changed: Refreshing playlist "old" (1 titre)...
```

Adding songs to a new playlist does not add anything to the logs.

**Comment by Meriipu** [comment]
If I create a new playlist, restart QL without having adding a track to it, then add a track to it, then restart -- it saves as if it was an "existing playlist" as described above.
