### ISSUE TITLE
Conflict between musicbrainz plugin and sort by discnumber ?

### ISSUE THREAD

**Issue by jberli** [quodlibet/quodlibet#2568]
Hello,
First, thank you all for Quod Libet which is imo one of the finest music browser, especially with my large database.

I was wondering if there are any conflicts between the musicbrainz plugin and the sorting by discnumber ? Maybe it's that I don't really get how things work which is more than possible, but I can't get the following sorting code to be effective in paned view:
`<~year|[b]<~year>[/b]. <album>|<album><discnumber|[i][small] - Disc <discnumber>[/small][/i]>>`

The problem seems to be occurring only on albums updated by musicbrainz plugin (mainly to get date infos and clean track names) but not on manually edited albums.
So I was wondering if this is a known issue, if I just don't get it, or if there is some kind of workaround.
This leads to an other question which is kind of similar : Is there a way to separate different discs according to the discnumber tag inside the tracks panel of the paned view ?

**Comment by zsau** [comment]
What behavior do you get with the pattern you posted, and what were you expecting?

**Comment by jberli** [comment]
Maybe you need the whole paned view preferences to get the full picture.
In the first view, I sort by albumartist or by artist if none is found:
`<albumartist|<albumartist>|<artist>>`
Then, I sort by year (bold), album and discnumber (small, italic):
`<~year|[b]<~year>[/b]. <album>|<album><discnumber|[i][small] - Disc <discnumber>[/small][/i]>>`

With the last pattern, I get only the year followed by the album but no sign of discnumber... 
If I only put `<~year|[b]<~year>[/b]. <album>|<album>>` I get the correct [year]. [album] display so I believe the discnumber is the issue here.

As I said, it only seems to be happening with albums I modified using MusicBrainz Lookup plugin. Otherwise, when I manually edit the discnumber of an album, it works fine. Furthermore, when I manually edit the discnumber of an album I already modified with the MusicBrainz Lookup plugin, it still doesn't work.

Thanks for your time, I really appreciate.

**Comment by zsau** [comment]
I think maybe you want to move the last closing angle bracket to right after the second `<album>` tag, since right now the `<discnumber>` stuff is part of the else-clause of the outer `<~year|...|>` conditional.

**Comment by jberli** [comment]
Thanks ! It works like a charm !
It seems I just didn't get the conditional syntax, but it's clearer now. Here's my pattern if anyone needs it (I added a conditional to avoid displaying 'Disc 1/1' following https://github.com/quodlibet/quodlibet/issues/1887):

`<~year|[b]<~year>[/b]. <album>|<album>><discnumber|<discnumber="1/1"||[i][small] - Disc <discnumber>[/small][/i]>>`

Thanks again and take care.
