### ISSUE TITLE
Stubborn no-show cover.

### ISSUE THREAD

**Issue by minombreespollo** [quodlibet/quodlibet#2572]
I have three albums in my library which refuse to show the cover in Album-list view. I've made sure that the album art is embedded into the music file.It doesn't appear in the list or at the top during playback, but when I click in the empty case icon the album art is shown as is expected: a little "window" with no buttons just showing the art. 

Has anyone encountered a similar problem?
Do you guys need more info? If so, which?

Thanks for reading.

**Comment by lazka** [comment]
Can you provide an example file? (you can send to reiter.christoph@gmail.com if you want)

**Comment by minombreespollo** [comment]
Update, I migrated my files to a fresh install and it got resolved. Thank you for offering your help. I actually need help to migrate without losing library data. I will open a new issue for that.
