### ISSUE TITLE
Information window doesn’t display album title containing an ampersand

### ISSUE THREAD

**Issue by Mellthas** [quodlibet/quodlibet#2573]
### Steps to Reproduce
* Select an album or several tracks from an album where the album title contains an ampersand
* Open the information window

### Expected Result
* The album title is displayed at the top (above track count and album art)

### Actual Result
* Not album title is displayed, the area is empty

````Gtk-WARNING **: Failed to set text '<span size='xx-large'><i>Full Anthems & Organ Music / Music on the Death of Queen Mary</i></span>' from markup due to error parsing markup: Fehler in Zeile 1: Entität endete nicht mit einem Semikolon; wahrscheinlich haben Sie ein »&«-Zeichen verwendet, ohne eine Entität beginnen zu wollen - umschreiben Sie das »&« als »&amp;«````

Using the current master branch.

**Comment by declension** [comment]
Thanks for reporting
