### ISSUE TITLE
Feature Request: Color separated rows

### ISSUE THREAD

**Issue by ghost** [quodlibet/quodlibet#2575]
If you have a very long list of radio stations, it would be nice/easier if each row had a slight color difference so the eye can quickly differentiate between them when scrolling through.

This brings up the question of skin themes for quodlibet. Would you implement this?

**Comment by declension** [comment]
Interesting. 

I think this is meant to be [up to the GTK+ theme](https://askubuntu.com/questions/262482/ubuntu-12-10-set-alternating-row-colors-in-gtk3-treeview) - in particular [the GTK reference](https://developer.gnome.org/gtk3/3.8/GtkTreeView.html#gtk-tree-view-set-rules-hint)

It seems we do set this to `True` in the songlist, so AFAICT it should be editable in the theme.

**Comment by lazka** [comment]
This was removed from gtk some time ago: https://bugzilla.gnome.org/show_bug.cgi?id=733312#c13

**Comment by CreamyCookie** [comment]
Yeah, this is up to the theme and Gtk (I too like alternating rows), so I'm closing!
