### ISSUE TITLE
QL crash when entering non-ASCII character in search/filter box of plugin manager

### ISSUE THREAD

**Issue by lafrech** [quodlibet/quodlibet#2583]
Open plugin manager. In the input box up-left, enter accentuated string, like "ré".

And _voilà_. QL crashes. I let it send a bug report with the details.

After that, the error window keeps reappearing. I had to kill it using the task manager.

Using latest 3.9.1.

**Comment by lazka** [comment]
https://sentry.io/quodlibet/quodlibet/issues/364610346/

**Comment by lazka** [comment]
Another thing worth doing here is marking QL as "shutting down" and ignoring any further errors in case the "quit app" options is selected. The endless stream of error dialogs is indeed annoying...

**Comment by lafrech** [comment]
Great job. Thanks!
