### ISSUE TITLE
Can I Have Multiple Values in a Tag? Error for selected files

### ISSUE THREAD

**Issue by hmc-cs-bcastro** [quodlibet/quodlibet#2591]
Hi, I'm new to Quod Libet and am hoping someone could help me out. It sounds like Quod Libet might allow multiple values for one tag (like to the tag "mood"), but I cannot find a way to do this, if that's true.  

I'm ultimately looking for a music organizer that will allow me to batch edit song tags, by adding to them rather than just replacing them (sort of like the labels Gmail uses), and then create playlists based on those tags. Is Quod Libet capable of this?

**Comment by declension** [comment]
Yes, this is supported.

Just select the tracks,  then edit the tags, and add a new tag of your choosing (e.g. `mood`) even if there is one there already, and specify the value you want. Note you can also right click existing values to split then into multiple tags if they contain certain configurable characters e.g. commas or slashes.

You can then use standard searching e.g. `mood=chilled` to select your tracks... and optionally add these to a playlist in the normal ways.

**Comment by hmc-cs-bcastro** [comment]
I'm running across an error now saying that the files currently selected do not support multiple values for mood. 

The add a tag box is different for, I think, MPEG-4 and MP3. For the first, I have to select a tag and if I try adding a second value I get the error. But for the latter, I get to type in the tag and I have no problems adding another value. 

Do I need to have songs in a specific format for the multiple values in a tag? Also, is does Quod Libet have a way to convert song formats?

**Comment by declension** [comment]
Ahh, right. Yes, some file formats are restrictive in their, QL / EF (via Mutagen in part) generally have good knowledge of these specs and will adjust the UI accordingly. 

So what you're seeing is the fact that there is no way to fully support these. I suppose you could delimit them manually e.g. by setting `mood` to _chilled / melancholic_ or whatever. Searching supports finding 

For converting, short answer is no. There are lots of good sound conversion tools on various operating systems. If you're very keen on it please open a new issue though (there are a few bits of history... see #494)

**Comment by CreamyCookie** [comment]
I'm closing this one as `can't fix`.
