### ISSUE TITLE
[Question] History of played songs

### ISSUE THREAD

**Issue by TombusPL** [quodlibet/quodlibet#2594]
Its any way to see played songs by QUEUE?
If not, its possible to create simple, small plugin?

**Comment by declension** [comment]
I don't really understand the question.

Do you mean a history of all songs played? If so, see #894 and especially #1890.

**Comment by TombusPL** [comment]
Hm, This is very similar #1890 . But now QL after played song in Queue just "deleting" from list and i cant see, what was played.
I need only information, what was:
- was in the queue
- was played

This information will be good see in .txt file with information like:
- number
- time and date
- artist
- title
- file with path

If needed information is available for plugins, I can try (for learning Phyton >> Im coding in C<<) write small plugin.

**Comment by frestr** [comment]
With #2865, you can now enable "Keep Songs" in the queue to get this behavior.
