### ISSUE TITLE
installed 3.7.1-2 on Ubuntu 17.10 but no icon

### ISSUE THREAD

**Issue by Cone-head** [quodlibet/quodlibet#2602]
Newb on Ubuntu, pretty new on Linux. After installing, it launched just fine, played songs fine after a little output tweak, does everything I wanted and more, but after Quit there's no icon for it under Show Applications. So I can't find it to use it again, much less can't Favorite for the dock. I'm logged into Ubuntu under Xorg. Could that be the problem?

**Comment by lazka** [comment]
Hm, it seems to work here: https://i.imgur.com/8XuhbgV.gif

**Comment by Cone-head** [comment]
Thanks, that did it! It just didn't occur to me that I needed to Search to find the app's icon.
