### ISSUE TITLE
Expanding the Search parameters

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#261]
Original [issue 261](https://code.google.com/p/quodlibet/issues/detail?id=261) created by timothy.mellor on 2009-07-12T04:54:44.000Z:

Say you want to show the last 50 songs you added to your library. How can
you do this? Maybe you could guess something like `#(added < 2 weeks)`, but
you can't really guarantee that you get 50 songs. In pseudocode (I suppose
&quot;pseudosearch&quot; is a better term, heh) what we want is this:

```
sort="added", order="desc", numberlimit=100
```

Or maybe you want to fill your 50 GB external HD up with your most recently
played tracks:

```
sort="~#plays", order="desc", sizelimit=50 GB
```

I would like to see quod get &quot;sort&quot;, &quot;sizelimit&quot;, &quot;numberlimit&quot;, and
&quot;lengthlimit&quot;. Custom sorting can already be performed, it would just be a
matter of adding it to the search parameters. What do you guys think?

**Comment by CreamyCookie** [comment]
Closing, as this is basically #821.
