### ISSUE TITLE
App won't display values for custom tags.

### ISSUE THREAD

**Issue by stephenpjohnson34** [quodlibet/quodlibet#2617]
I added a custom tag through the application preferences screen. It has a tag expression of '~bpm' and a description of 'BPM'. My library shows the column when I view the library. I then right click a song, go to Edit Tags, add a new tag using 'bpm' as the tag and '5' as the value, and close the edit tags window. When I look at my library, nothing appears in the BPM column for the song I just edited. What am I doing wrong here?

**Comment by declension** [comment]
Can you add a screenshot? It sounds like you're configuring a songlist column in the view. This doesn't do anything to the library itself.

Either way you should try using `bpm`. The tilde is for _internal_ tags, not custom ones.

**Comment by CreamyCookie** [comment]
Closed as incomplete.
