### ISSUE TITLE
How to make a proper Back up of my library?

### ISSUE THREAD

**Issue by minombreespollo** [quodlibet/quodlibet#2618]
Hello everyone.

I am using Manjaro but I guess this should be the same for all linux distros. 
I had to format my disk and start again. When moving what I believed to be the correct folders for QuodLibet I found out that it did not move the playcount, playlists or the added date as I thought it would. Fortunately this info is preserved in an old SQL database and I can add it again and I do not mind that.

I would mind however having to restart every time. How can I back up this data and move to a fresh install without fear of losing all the work I have done?

**Comment by declension** [comment]
Did you back up `~/.quodlibet' and all its subdirectories?

**Comment by minombreespollo** [comment]
@declension thank you for your answer.
Nope, maybe that is what I was missing. Any other folders you think I should copy? Are podcast and other audio feeds stored in this folder too?

**Comment by declension** [comment]
No that sounds have everything IIRC
