### ISSUE TITLE
Renaming files containing Chinese characters results in an error

### ISSUE THREAD

**Issue by marmistrz** [quodlibet/quodlibet#2620]
Example filename: 

> 唐朝 - 梦回唐朝. 01 - 梦回唐朝.flac

**Comment by lazka** [comment]
Which operating system?

**Comment by marmistrz** [comment]
Arch Linux, Python 3.6.3

**Comment by frestr** [comment]
Could you provide some more details on this? Like how exactly you are renaming the file (steps to reproduce) and what the error is.

**Comment by CreamyCookie** [comment]
Cannot reproduce. No error here.

Closing this one as incomplete.
