### ISSUE TITLE
Radio streams freeze QL and require a full CPU to run

### ISSUE THREAD

**Issue by jberli** [quodlibet/quodlibet#2624]
I don't know if this issue has been raised yet but I didn't find it.
As the title says, when I start any radio stream, it works well but QL completely freezes and doesn't seems to react whenever I try to see preferences or else... Furthermore it requires a full CPU to run.
Is it how it is supposed to work ?

I'm using QL 3.9.1 on Debian Stretch with Cinnamon

Thanks in advance.

**Comment by lazka** [comment]
Does increasing the "buffer duration" in the preferences help before starting playback?

**Comment by lazka** [comment]
Otherwise you can check without plugins by starting QL with "quodlibet --no-plugins".

And if all fails, rename "~/.quodlibet" to reset everything and see if that helps.

**Comment by jberli** [comment]
Increasing the buffer duration to 10 sec. didn't work.
But launching QL without plugins do work. Is it because of a specific plugin ?

**Comment by lazka** [comment]
Might be, you can try disabling the plugins one by one

**Comment by lazka** [comment]
I remember some issues with the notification plugin, maybe try that one first.

**Comment by jberli** [comment]
Well, the notification plugin doesn't work for me so it's not this one. I'll investigate and report here any news.

**Comment by lazka** [comment]
Thank you!

**Comment by jberli** [comment]
The 'Waveform Seek Bar' plugin seems to be the problem here. 
Terminal return this when I activate it: 
`/usr/lib/python2.7/dist-packages/quodlibet/ext/events/waveformseekbar.py:81: Warning: value "0" of type 'guint64' is invalid or out of range for property 'interval' of type 'guint64'
  pipeline = Gst.parse_launch(command)
`
Maybe you can reproduce the issue to verify it's not coming from me.

**Comment by lazka** [comment]
Thanks for figuring that out. I'll look into it.

**Comment by jberli** [comment]
No problem, thank you for all your work.

**Comment by jberli** [comment]
Great, it was the same issue, it's now working smoothly.
I'm closing the issue.
