### ISSUE TITLE
Question: license to use for plugins

### ISSUE THREAD

**Issue by michael-ball** [quodlibet/quodlibet#2626]
Do plugins written for Quod Libet also need to use GPL v2.0 or later? Or can we use other licenses?

**Comment by lazka** [comment]
Good question... I think as long as the QL doesn't use anything GPLv2 only incompatible it's OK. But the license change happening right now is to enable just that.

Not sure.. (I don't care personally if that helps)

**Comment by michael-ball** [comment]
Okay that sounds good. Unless I'm reading Wikipedia's article on license compatibility[1] wrong, it looks like MIT license is compatible with GPL V2+.

Thanks for the answer: I'll mark this as closed. 

[1] https://en.wikipedia.org/wiki/License_compatibility

**Comment by lazka** [comment]
Oh, I assumed you asked if you need to change from "gplv2 only" to "gplv2 or later" for external plugins. Using any license compatible with the gplv2, like MIT, should certainly be fine.
