### ISSUE TITLE
[Error] FaultHandlerCrash: Fatal Python error: Segmentation fault

### ISSUE THREAD

**Issue by redvimo** [quodlibet/quodlibet#2627]
* What did you try to do when the error occurred?
A: I just opened the program, then the bug report dialog opened. But i suspect it's an error from previous executions of the program, in which the program crashed several times while playing music, this usually happens after changing the track playing. Sometimes if I keep changing the track like really fast then it crashes. Also I noticed very high(80%) CPU usage, and very high memory usage(+- 200MB - 480MB RAM) after just playing music for say, half an hour. I noticed when i change the track playing memory usage almost doubles, but not all the time. Other than that it's all good.

Error Details:
```
Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/quodlibet/errorreport/faulthandling.py", line 137, in raise_and_clear_error
    raise FaultHandlerCrash(text)

FaultHandlerCrash: Fatal Python error: Segmentation fault


Version: 3.9.1
Python: 2.7.14 (default, Sep 17 2017, 18:50:44) 
[GCC 7.2.0]
Platform: Linux-4.13.0-1-amd64-x86_64-with-debian-buster-sid
```

**Comment by lazka** [comment]
Yeah, this is a report of a crash of a previous session, but it doesn't include much info sadly.

The crashing during song change usually depends on the file type being played (and a bug in the gstreamer encoder pipeline) or in one of the gstreamer plugins. So if it gets annoying try disabling audio effect plugins if you have any enabled.

These things are kinda hard to debug from afar.

**Comment by redvimo** [comment]
Ok cool. Will try that out. Is the Equilizer plugin an audio effect plugin?

**Comment by lazka** [comment]
> Ok cool. Will try that out. Is the Equilizer plugin an audio effect plugin?

yes

**Comment by redvimo** [comment]
Ok. Thanks
