### ISSUE TITLE
cover art on HDPI displays (shown in response to clicking on the cover art in the paned browser)

### ISSUE THREAD

**Issue by pfps** [quodlibet/quodlibet#2633]
I have a HDPI display and the cover art I get when clicking on the cover in the  paned browser is too small.   The largest image that can be shown is the natural size of the image adjusted by the scale factor.  As I don't use scale factor to adjust the size of things on my screen, all I get is the natural size of the image, which is small even for 600x600 images.  For 300x300 images, which are still quite commonly found, the image it very small.

What I did to fix this was to allow the image to scale up in pixbuf_from_file in image.py.  However, this is a rather crude hammer.  It would be better to have the size controlled by the user, but I'm not sure what is the best way to do this.  

Any suggestions?  I can probably do the implementation work needed.

**Comment by lazka** [comment]
I wouldn't mind enabling upscaling for this case by default.

**Comment by pfps** [comment]
So under what conditions should the upscaling be allowed?   Is there a good way of detecting a HDPI display?  There already is a maximum size for the image relative to the overall screen size (or window size for wayland) so maybe having upscaling on all the time is not so bad.

**Comment by lazka** [comment]
Ah, by this case I meant the cover display window in general, sorry.

The proposal sounds fine.

**Comment by pfps** [comment]
Here is the pull request https://github.com/quodlibet/quodlibet/pull/2634

It has several intermediate commits because I had some local changes that I didn't get rid of before updating to the current master.
