### ISSUE TITLE
macOS: Evaluate gtk+ event handling bug workaround

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#2635]
Someone posted a fix to work around for the "windows loosing focus issue" on macOS: https://mail.gnome.org/archives/gtk-devel-list/2017-November/msg00010.html

Needs to be evaluated.

**Comment by urielz** [comment]
I'm a bit baffled about this. Is it specific to a particular version to macOS? I cannot reproduce this on my end at all (macOS 10.13.4 (17E202))

**Comment by lazka** [comment]
I have this issue in virtualbox since we first got macos support. It might be more visible on slower machines maybe?
