### ISSUE TITLE
Could not add RSS podcast feed

### ISSUE THREAD

**Issue by rohshall** [quodlibet/quodlibet#2641]
What did you try to do?
Added the following podcast: 
http://cbsradionewsfeed.com/rss.php?id=126&ud=12

* What did you expect to happen?
podcast being added

* What did happen instead?
I get an "Unable to add feed" error dialog

* Which version of Quod Libet?
master branch on 11/28

* Which operating system including version (Ubuntu 14.04, Win7, Debian sid, ...)?
Python: 2.7.14 (default, Nov  2 2017, 19:02:24) 
[GCC 7.2.1 20170829 (Red Hat 7.2.1-1)]
Platform: Linux-4.15.0-0.rc0.git7.1.fc28.x86_64-x86_64-with-fedora-28-Rawhide

**Comment by lamacchiacosta** [comment]
I've got the same, trying to add the following feed:
http://rss.earwolf.com/yo-is-this-racist

**Comment by declension** [comment]
This seems to now work, probably the upgrade to feedparser 6.0 in d218a9daea181394eddbbd3e02b17d1182260f43
