### ISSUE TITLE
Playlist gets mixed up when album titles are the same

### ISSUE THREAD

**Issue by markbaaijens** [quodlibet/quodlibet#2643]
When you have several album with the same album title, the playlist gets mixed up. It contains *all* songs from all albums with the same name.

Version 3.8.1 (e57d03b) - on Win10
Version 3.7.1 - on Ubuntu Mate 17.10
(same result on both versions)

![quod-libet-wrong-playlist](https://user-images.githubusercontent.com/3878546/33374255-ade7bea6-d505-11e7-874e-9b46b3d801f3.png)

**Comment by lazka** [comment]
Have a look at https://quodlibet.readthedocs.io/en/latest/guide/faq.html#i-have-two-albums-with-the-same-name-which-are-merged-in-the-album-list

**Comment by markbaa** [comment]
This is what I found:
![selectie_056](https://user-images.githubusercontent.com/3878546/33391988-fd0d0d12-d53a-11e7-9db6-55c556e1c2cf.png)
Retagging files is not an option. No other player needs this when browsing artist => albums (from artist) 

In the filtering showing album info (per artist), the combination artist - album title should be considered. Probably only the album title is leading now.

**Comment by lazka** [comment]
The compilation view is different to the paned browser int that it works on an album basis and not a per song one. And since we allow different artists for different songs in the same album we can't identify the album based on the artist.

There is #2193 which should make merging/splitting easier in the future.

**Comment by markbaa** [comment]
In principle, I will not retag my collection b/c one certain music player cannot handle a certain condition. So I will not adapt tagging to a specific music player. Also: I do not own compilation albums: I *always* remove the albumartist tag.

That said, maybe I misunderstand the album collection view (Ctrl-5). My assumption is that if I select an artist and I only see albums of that particular artist (so far so good....), I *also* must see only songs of the chosen album. I fail to see how this view can be usefull (even if you have compilation albums in your collection, which I don't have). 

I agree that the paned view (Ctrl+3) does exactly what I want. But in there, I miss the elegant tree structure (artist => album) of the album collection view.

**Comment by J-J-Chiarella** [comment]
@markbaaijens 

I agree that this should be implemented. However, there are sometimes good reasons to have album artist tags (though if it is not a compilation, quod libet should fall back on reading artist tag).

I don't have "compilation albums," either, in the sense of "Now That's What I Call Music 15!" (or whatever; I am dating myself here).

But consider Queen's Hot Space album. Track 11 is "Under Pressure," which is officially Queen + David Bowie for the Artist, not artist as "Queen" with track as "Under Pressure (feat. David Bowie)."

**Comment by dm2912** [comment]
J-J-Chiarella case like under pressure i either use two artist tags, or i use performer tags.

for instance, for all beatles studio albums i have john & paul, john, paul, ringo, george tagged as performer depending on who sang it.

**Comment by CreamyCookie** [comment]
Closing this as `won't fix` since (as mentioned in the docs), album artist exists for that purpose.

Thanks for the report though!

I also highly recommend MusicBrainz Picard for making tagging very easy. (It finds the tags, applies and renames them optionally. We also have a plugin for MusicBrainz lookup but I haven't tried it yet.)
