### ISSUE TITLE
tray icon does not work in Cinnamon 3.6.6

### ISSUE THREAD

**Issue by deutrino** [quodlibet/quodlibet#2647]
I'm using Quod Libet 3.9.1 on Linux Mint 18.3 with Cinnamon 3.6.6. The tray icon does not appear to work, whether or not I disable the plugin for it. Nothing appears in the tray.

**Comment by lazka** [comment]
Thanks, confirmed.

**Comment by lazka** [comment]
Not sure why. It works when running from source, but takes 2-3 seconds until the shell displays it.

**Comment by deutrino** [comment]
Let me know if there's some way I can help test. :)

**Comment by dm2912** [comment]
Working fine here 

https://i.imgur.com/1SIOsN9.png

Mint 18.3, Cinnamon 3.6.7

Or is there a seperate dedicated Quod Libet icon that appears in tray (that I have never seen under cinnamon/mint)

**Comment by lazka** [comment]
@dm2912 that looks like a MPRIS2 based widget

The tray icon can be enabled through the "Tray Icon" plugin.

**Comment by dm2912** [comment]
ah ok.. i dont even see a tray icon plugin in the plugin list.. :D

**Comment by dm2912** [comment]
ah, this would be why i dont see tray icon in the plugin list

https://i.imgur.com/07wQ2VA.png

**Comment by lazka** [comment]
The plugin API isn't stable, so if you install plugins into "~/.quodlibet/plugins" things might break from time to time.

**Comment by xhc1** [comment]
I tried it in cinnamon 3.8.9 and tray icon works, just need to be ensure you have turned off option in cinnamon Sound applet "Hide system tray icons of compatible players"
![screenshot from 2018-10-20 12-50-49](https://user-images.githubusercontent.com/1653212/47254773-d16af300-d466-11e8-857a-9614e940adcb.png)

**Comment by lazka** [comment]
@xhc1 thanks

@deutrino can you confirm that this fixes things?

**Comment by pablissimo77** [comment]
> I tried it in cinnamon 3.8.9 and tray icon works, just need to be ensure you have turned off option in cinnamon Sound applet "Hide system tray icons of compatible players"

That helped
Mint 19.1 Cinnamon 4.0.9

**Comment by lazka** [comment]
@pablissimo77 thanks

**Comment by sparusaurata** [comment]
With Mint 20.1 and Cinnamon 4.8.6, I had to:

- enable "D-BUS MPRIS Support" plugin,
- **disable** "Tray Icon" plugin.

**Comment by YuriyL-Git** [comment]
Thank

> With Mint 20.1 and Cinnamon 4.8.6, I had to:
> 
> * enable "D-BUS MPRIS Support" plugin,
> * **disable** "Tray Icon" plugin.

Thaks bro! You saved my day. Also helped with the same issue on Ubuntu
