### ISSUE TITLE
[Error] FaultHandlerCrash: Fatal Python error: Segmentation fault

### ISSUE THREAD

**Issue by redvimo** [quodlibet/quodlibet#2649]
* What did you try to do when the error occurred?
Opened and closed quodlibet.

Error Details:
```
Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/quodlibet/errorreport/faulthandling.py", line 137, in raise_and_clear_error
    raise FaultHandlerCrash(text)

FaultHandlerCrash: Fatal Python error: Segmentation fault


Version: 3.9.1
Python: 2.7.14 (default, Sep 17 2017, 18:50:44) 
[GCC 7.2.0]
Platform: Linux-4.13.0-1-amd64-x86_64-with-debian-buster-sid
```

**Comment by lazka** [comment]
The report sadly doesn't contain any useful information (besides that QL has crashed). If you find some repeating action which makes it crash or some other cause please open a new bug report.

Thanks for taking the time to file a report.
