### ISSUE TITLE
Modifying rating (with keyboard, in particular)

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#265]
Original [issue 265](https://code.google.com/p/quodlibet/issues/detail?id=265) created by hoverhell on 2009-07-18T14:15:31.000Z:

Rating modification of currently playing / selected songs by keyboard is
too complex (menu, right, select specific rating). Best way I found is to
make shell-script that parses ~/.quodlibet/current for the current rating
and changes it by ±0.1 (considering I have ratings=10) with --set-rating.

Some interface hotkey (or, rather, hotkeyable menu item) for modifying the
rating of the selected songs up/down by the mimimal value would solve this
problem. Adding console command like --change-rating up/down (in addition
to --set-rating) for the similar modification would be nice too.

**Comment by CreamyCookie** [comment]
This can be closed, right? It's possible to rate via <kbd>Ctrl</kbd> + <kbd>0</kbd> to <kbd>9</kbd>

**Comment by CreamyCookie** [comment]
I think this existed at some point (Ctrl + Number, which is now used for changing current browser) and I'd like to see it come back.

**Comment by bassstorm** [comment]
I miss that too.
Could be part of #2140 maybe?

**Comment by CreamyCookie** [comment]
@bassstorm Don't think so, as that's plugin-only. But I have put this in a new, a more clear, template-following enhancement report, so there's a higher chance this gets addressed: #3637
