### ISSUE TITLE
Error Occurred

### ISSUE THREAD

**Issue by rootkea** [quodlibet/quodlibet#2650]
=== SYSTEM INFORMATION:
Quod Libet 3.7.1
Mutagen 1.36
Python 2.7.13 (default, Nov 24 2017, 17:33:09) 
[GCC 6.3.0 20170516] linux2
Platform Linux-4.9.0-4-amd64-x86_64-with-debian-9.3
=== STACK TRACE

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/quodlibet/browsers/soundcloud/library.py", line 59, in _on_comments_received
    song = self.song_by_track_id(track_id)

  File "/usr/lib/python2.7/dist-packages/quodlibet/browsers/soundcloud/library.py", line 67, in song_by_track_id
    % (track_id, [s.track_id for s in self.values()]))

KeyError: 'No track with id 257945979. Do have []'

=== LOG:
D: 06.586: library.save: Saving all libraries...
D: 12.528: SoundcloudBrowser.__init__: Creating Soundcloud Browser
D: 12.529: SoundcloudApiClient.__init__: Starting Soundcloud API...
D: 12.529: SoundcloudLibrary.__init__: Using pickling persistence for library "Soundcloud"
D: 13.564: WebImage._fetch_image: Got web image from https://developers.soundcloud.com/assets/logo_black.png
D: 13.622: WebImage._fetch_image: Got web image from https://connect.soundcloud.com/2/btn-disconnect-l.png
D: 13.688: WebImage._fetch_image: Got web image from https://connect.soundcloud.com/2/btn-connect-l.png
D: 19.391: SoundcloudBrowser.update_connect_button: Removing old image...
D: 40.956: CommandRegistry.handle_line: command: uri-received(*['quodlibet://callbacks/soundcloud?code=8accacf3e20d7e7de587199b74ea73f5'])
D: 40.956: CommandRegistry.run: Running '_uri_received' with params ('quodlibet://callbacks/soundcloud?code=8accacf3e20d7e7de587199b74ea73f5',) 
D: 40.957: browsers.soundcloud.main.__handle_incoming_uri: Processing Soundcloud callback (ParseResult(scheme='quodlibet', netloc='callbacks', path='/soundcloud', params='', query='code=8accacf3e20d7e7de587199b74ea73f5', fragment=''))
D: 40.957: SoundcloudApiClient.get_token: Getting access token...
D: 40.958: DefaultHTTPRequest.send: Sending POST request to https://api.soundcloud.com/oauth2/token
D: 41.337: DefaultHTTPRequest._sent: Sent POST request to https://api.soundcloud.com/oauth2/token
D: 41.340: SoundcloudApiClient._receive_token: Got an access token: 1-180752-45859962-67efb954fa6ca0
D: 41.341: DefaultHTTPRequest.send: Sending GET request to https://api.soundcloud.com/me?oauth_token=1-180752-45859962-67efb954fa6ca0&client_id=5acc74891941cfc73ec8ee2504be6617
D: 41.520: DefaultHTTPRequest._sent: Sent GET request to https://api.soundcloud.com/me?oauth_token=1-180752-45859962-67efb954fa6ca0&client_id=5acc74891941cfc73ec8ee2504be6617
D: 41.521: SoundcloudBrowser.update_connect_button: Removing old image...
D: 05.011: SoundcloudBrowser.__init__: Creating Soundcloud Browser
D: 05.011: SoundcloudApiClient.__init__: Starting Soundcloud API...
D: 05.011: SoundcloudLibrary.__init__: Using pickling persistence for library "Soundcloud"
D: 05.309: WebImage._fetch_image: Got web image from https://connect.soundcloud.com/2/btn-connect-l.png
D: 05.310: WebImage._fetch_image: Got web image from https://connect.soundcloud.com/2/btn-disconnect-l.png
D: 05.810: WebImage._fetch_image: Got web image from https://developers.soundcloud.com/assets/logo_black.png
D: 06.549: config.save: Writing config...
D: 06.593: library.save: Saving all libraries...
D: 15.165: SoundcloudBrowser._on_select: Getting favorites...
D: 15.166: DefaultHTTPRequest.send: Sending GET request to https://api.soundcloud.com/me/favorites?limit=150&oauth_token=1-180752-45859962-67efb954fa6ca0&client_id=5acc74891941cfc73ec8ee2504be6617
D: 15.169: SoundcloudBrowser.activate: Refreshing browser for query "None"
D: 15.170: PlaylistModel.set: Clearing model.
D: 15.171: PlaylistModel.set: Setting 0 songs.
D: 15.171: PlaylistModel.set: Done filling model.
D: 15.622: DefaultHTTPRequest._sent: Sent GET request to https://api.soundcloud.com/me/favorites?limit=150&oauth_token=1-180752-45859962-67efb954fa6ca0&client_id=5acc74891941cfc73ec8ee2504be6617
D: 15.623: SoundcloudLibrary._on_songs_received: Got 0 songs (0 new).
D: 25.285: QueueModel.go_to: Told to go to None
D: 25.285: PlaylistModel.go_to: Told to go to None
D: 26.585: SoundcloudBrowser.__init__: Creating Soundcloud Browser
D: 26.585: SoundcloudApiClient.__init__: Starting Soundcloud API...
D: 26.585: SoundcloudLibrary.__init__: Using pickling persistence for library "Soundcloud"
D: 26.767: WebImage._fetch_image: Got web image from https://connect.soundcloud.com/2/btn-disconnect-l.png
D: 27.088: WebImage._fetch_image: Got web image from https://connect.soundcloud.com/2/btn-connect-l.png
D: 27.236: WebImage._fetch_image: Got web image from https://developers.soundcloud.com/assets/logo_black.png
D: 28.651: SoundcloudBrowser._on_select: Getting favorites...
D: 28.652: DefaultHTTPRequest.send: Sending GET request to https://api.soundcloud.com/me/favorites?limit=150&oauth_token=1-180752-45859962-67efb954fa6ca0&client_id=5acc74891941cfc73ec8ee2504be6617
D: 28.653: SoundcloudBrowser.activate: Refreshing browser for query "None"
D: 28.654: PlaylistModel.set: Clearing model.
D: 28.654: PlaylistModel.set: Setting 0 songs.
D: 28.654: PlaylistModel.set: Done filling model.
D: 29.039: DefaultHTTPRequest._sent: Sent GET request to https://api.soundcloud.com/me/favorites?limit=150&oauth_token=1-180752-45859962-67efb954fa6ca0&client_id=5acc74891941cfc73ec8ee2504be6617
D: 29.078: SoundcloudLibrary.add: Adding 1 items.
D: 29.078: PlaylistModel.set: Clearing model.
D: 29.078: PlaylistModel.set: Setting 1 songs.
D: 29.078: PlaylistModel.set: Done filling model.
D: 29.079: qltk.completion.__update_song: Updating tag model for 1 songs
D: 29.079: qltk.completion.__update_song: Done updating tag model for 1 songs
D: 29.080: SoundcloudLibrary._on_songs_received: Got 1 songs (1 new).
D: 30.881: GStreamerPlayer.go_to: Going to <Gtk.TreeIter object at 0x7fe2d4157e20 (GtkTreeIter at 0x55f41debc100)>
D: 30.881: PlaylistMux.go_to: Told to go to <Gtk.TreeIter object at 0x7fe2d4157e20 (GtkTreeIter at 0x55f41debc100)>
D: 30.881: QueueModel.go_to: Told to go to None
D: 30.882: PlaylistModel.go_to: Told to go to <Gtk.TreeIter object at 0x7fe2d4157e20 (GtkTreeIter at 0x55f41debc100)>
D: 30.882: GStreamerPlayer._end: End song
D: 30.884: util.cover.manager.failure: Didn't get cover from FilesystemCover: This source is incapable of fetching covers
D: 30.884: util.cover.manager.failure: Didn't get cover from EmbeddedCover: This source is incapable of fetching covers
D: 30.886: browsers.soundcloud.library.__song_started: Getting comments for Dr. Babasaheb Ambedkar Writings and Speeches Volume 1 (Introduction 1) (track-257945979)
D: 30.887: DefaultHTTPRequest.send: Sending GET request to https://api.soundcloud.com/tracks/257945979/comments?limit=200&oauth_token=1-180752-45859962-67efb954fa6ca0&client_id=5acc74891941cfc73ec8ee2504be6617
D: 30.887: browsers.soundcloud.library.__song_started: Getting comments for Dr. Babasaheb Ambedkar Writings and Speeches Volume 1 (Introduction 1) (track-257945979)
D: 30.888: DefaultHTTPRequest.send: Sending GET request to https://api.soundcloud.com/tracks/257945979/comments?limit=200&oauth_token=1-180752-45859962-67efb954fa6ca0&client_id=5acc74891941cfc73ec8ee2504be6617
D: 30.888: browsers.soundcloud.library.__song_started: Getting comments for Dr. Babasaheb Ambedkar Writings and Speeches Volume 1 (Introduction 1) (track-257945979)
D: 30.888: DefaultHTTPRequest.send: Sending GET request to https://api.soundcloud.com/tracks/257945979/comments?limit=200&oauth_token=1-180752-45859962-67efb954fa6ca0&client_id=5acc74891941cfc73ec8ee2504be6617
D: 30.888: GStreamerPlayer._end: Next song
D: 30.996: SoundcloudLibrary._changed(<library.SoundcloudLibrary object at 0x7fe2d41cbfa0 (quodlibet+browsers+soundcloud+library+SoundcloudLibrary at 0x7fe2b400b040)>): Changing 1 items.
D: 30.997: qltk.completion.__update_song: Updating tag model for 1 songs
D: 30.998: qltk.completion.__update_song: Done updating tag model for 1 songs
D: 31.129: DefaultHTTPRequest._sent: Sent GET request to https://api.soundcloud.com/tracks/257945979/comments?limit=200&oauth_token=1-180752-45859962-67efb954fa6ca0&client_id=5acc74891941cfc73ec8ee2504be6617
D: 31.130: SoundcloudApiClient._receive_comments: Got comments: [{u'body': u'Any link from which this audio can be downloaded ?', u'kind': u'comment', u'user_id': 104499346, u'timestamp': 56302, u'created_at': u'2016/09/11 10:29:16 +0000', u'uri': u'https://api.soundcloud.com/comments/304159549', u'track_id': 257945979, u'user': {u'username': u'dondavis911', u'permalink': u'dondavis911', u'avatar_url': u'https://a1.sndcdn.com/images/default_avatar_large.png', u'kind': u'user', u'uri': u'https://api.soundcloud.com/users/104499346', u'last_modified': u'2017/05/20 06:16:16 +0000', u'permalink_url': u'http://soundcloud.com/dondavis911', u'id': 104499346}, u'id': 304159549}]

**Comment by lazka** [comment]
See #2410
