### ISSUE TITLE
adding to queue using control-return doesn't work in some cases

### ISSUE THREAD

**Issue by pfps** [quodlibet/quodlibet#2654]
Using control-return works in the song list to add tracks to the queue, but doesn't work from the panes in the paned browser.   Selecting the Add to Queue menu item works in both places.

I'm running under Linux using the development version.

**Comment by declension** [comment]
Replicated.

I suppose you could argue this is good - as adding an entire category (from a pane) is probably less commonly the thing people want. Of course if we had global undo #383 /  #1986 that would be a help...
