### ISSUE TITLE
lastplayed, lastplayed:min and advanced queries

### ISSUE THREAD

**Issue by vede1** [quodlibet/quodlibet#2658]
This issue explains the remaining nuances of using advanced lastplayed queries after closing issue #2200, however pointing them out necessitates preliminary explanations (note, all queries are performed in Album View).

Introduction

First, as of QL 3.9.1, those queries at a glance are counterintuitive and advanced because they require the user to understand and operate mixed references of time. To be successful the user needs to know that expressions of the type '2 days' and 'lastplayed' have a relative time, but expression of the type 'lastplayed:max' and 'lastplayed:min' have an absolute time. If you query 'lastplayed:max <= 2 days', you use a query with mixed time references, which leads to ultimately correct but unexpected results.

If today is December 15, 2017 9:38:25 AM (1513330705) and the user played a song two days ago, December 13, 2017 9:38:25 AM (1513157905), then his mixed time query 'lastplayed:max <= 2 days' is encountering and processing said song with the statement '1513157905 <= 172800', rejection — correct, but unexpected. The only songs satisfying such query are those played at or before January 3, 1970 12:00:00 AM (172800), that is statements of the type '172800 <= 172800', acceptance — in practice these are only the never played songs with an absolute time of January 1, 1970 12:00:00 AM (0).

In order for the queries to be predictable, the user needs to normalize all statements to the same reference of time. The easiest way is to make all time references relative. This is achieved by subtracting the absolute times from the current time. For the above example this would be the query '1513330705-lastplayed:max <= 2 days', which is the same as 'lastplayed <= 2 days'.

Example of an advanced query

The following query is called 'continue', because it allows to search for played and at the same time unfinished albums. Let's say there are 2 albums. Album 'A' with 8 songs (8 songs played less than 2 days ago), and album B with 5 songs (2 songs played less than 2 days ago and 3 songs played a week ago). Album 'A' is said to be finished, because all 8 songs were played within 2 days. Album 'B' is said to be unfinished, because only parts of it were re-listened within 2 days. The goal is to use a query filtering only unfinished albums, hence its name 'continue'.

Enter mixed time references

The only way to filter album 'B' is to use the :min and :max modifiers that work with absolute times, that is to filter albums with most recent songs newer than 2 days, and with least recent songs older than 2 days. Filtering B takes place by using the mixed time query '&(#(lastplayed < 2 days), #(1513330705 - lastplayed:min > 2 days))'.

Fast forward to #2504

Pull #2504 alleviates the users from needing to understand and operate with mixed times by making all time queries use relative references. The above mixed time query in QL 4-masters simply becomes &(#(lastplayed < 2 days), #(lastplayed:min > 2 days)).

Here the destination of this issue is reached. It relates to a variation of the 'continue' query, specifically to its ability to differentiate between 'unfinished known albums' and 'unfinished unknown albums'. The latter is an album with at last one of the songs being never played. This variation allows the user to juggle between continuing familiar albums and continuing the ones that are newly added to the library, without mixing them in the results pane.

In QL 3.9.1 this is achieved by using an additional statement with absolute time. To continue a familiar album, query for '&(#(lastplayed < 2 days), #(1513330705 - lastplayed:min > 2 days)', #(lastplayed:min>0)). If the user understands mixed times, then this query is logical and sensible.

In QL 4-master, provided :min is a relative time, songs that were never played have a 'live' time always amounting to the present moment whenever queried, which in relative time equals over 47 years. Once the user discovers this 'continue' query, he will have to resort to using unintuitive statement for the :min parameter, '&(#(lastplayed < 2 days), #(47 years > lastplayed:min > 2 days))'.

A possible solution is to ~~assign 0 to all unplayed~~ songs and use the former '#(lastplayed:min>0)' as a check for whether lastplayed does or does not exists. If it exists, then it has to be higher than 0. This solution seems more natural than using dummy variables.

EDIT: The solution is not to assign 0 to all unplayed songs (this is the current behaviour in stable), but to make their absolute timestamp to be equal to the present moment (a call to a now() function). This will make all 'Never' songs have an absolute timestamp equal to the present moment whenever queried. At first it may seem strange to make all 'Never' songs to be continuously in the now, however this behaviour would give all lastplayed:min queries meaningful relative lengths. If a songs was never played, then their relative length would be equal to 'now() - absolute_time_now() = 0'. If a song was played 2 days ago, then their relative length would be equal to 'now() - absolute_time_1513239848 = 172800'.

**Comment by CreamyCookie** [comment]
I would say, "Never" should always use special value like [Python's `None`](https://docs.python.org/3/library/constants.html#None). The query system would then have to simply throw away all results for queries like `#(lastplayed < 2 days)`  or `#(lastplayed > 2 days)` since a song that was never played was neither player less than 2 days ago, nor was it played before 2 days.

For finding those without you would then simply use the [missing tags plugin](https://github.com/quodlibet/quodlibet/pull/2936) (and can already do so):

`@(missing:~#lastplayed)`

**Comment by vede1** [comment]
Outdated, :min and :max modifiers no longer available for 'lastplayed'.
