### ISSUE TITLE
Custom Commands plugin: "Edit Custom Commands" changes the order of the defined commands

### ISSUE THREAD

**Issue by marcelpaulo** [quodlibet/quodlibet#2659]
I arrange the order of the custom commands (plugin `Custom Commands`) so that the most frequently used are at the top of the list. When I click on `Edit Custom Commands`, the order of the commands within the list is changed. I am using version **4.1 (development, a04bee863)**

Steps to reproduce:

1. Check the current order of the commands in plugin `Custom Commands`:
![screenshot_2017-12-16_15-44-10](https://user-images.githubusercontent.com/10074769/34073102-bd518ea4-e279-11e7-81b5-567174668e06.png)
1. Click on `Edit Custom Commands`:
![screenshot_2017-12-16_15-44-29](https://user-images.githubusercontent.com/10074769/34073120-032ac62a-e27a-11e7-88fc-34452db63291.png)
1. Click on `Close` to come back to the list of commands:
![screenshot_2017-12-16_15-45-16](https://user-images.githubusercontent.com/10074769/34073114-eee59b18-e279-11e7-8e15-7f2c0afa497d.png)

As you can see, the order of the commands was changed.

**Comment by marcelpaulo** [comment]
Just discovered something: whenever I click on `Edit Custom Commands`, the order of the commands is reversed, so that, when I click for the **second time**, the order is reverted to the original, starting point.

**Comment by frestr** [comment]
The problem here is that the commands are stored as a dictionary (both in Python and in the saved json file), causing the ordering to be non-deterministic.

**Comment by marcelpaulo** [comment]
But the ordering is deterministic: whichever order I manually establish, it's reversed. It's never random. It's precisely a 180º reflection, so that if I save it twice, it reflects 360º: it goes back to it started from.

**Comment by lazka** [comment]
fyi, Python dicts keep their insertion order since 3.6

**Comment by frestr** [comment]
@marcelpaulo @lazka I see, thanks. That made the fix pretty simple.
