### ISSUE TITLE
Prevent system suspend while playing

### ISSUE THREAD

**Issue by Fregf** [quodlibet/quodlibet#2665]
Currently, there is a plugin which disables the screensaver while playing. It also prevents the computer from going to sleep. However, I think there should be an option to prevent the system from going to sleep without disabling the screensaver. I do want the screensaver to become active, my user session being locked and my monitor go into sleep mode to save energy. I just don't want the whole system to sleep, so that playing always continues until I stop it myself.

**Comment by lazka** [comment]
Should be possible.

We currently use "org.gnome.SessionManager" which seems to allow this. There also is an interface on "org.freedesktop.login1".
