### ISSUE TITLE
tests/test_util_cover.py: Illegal byte sequence

### ISSUE THREAD

**Issue by zsau** [quodlibet/quodlibet#2669]
Mac OS X 10.13.2, QL master branch. I'm running setup.py via the `run` launcher from the [QL application bundle](https://bitbucket.org/lazka/quodlibet/downloads/QuodLibet-latest.dmg)— if that's wrong, let me know.

```
self = <tests.test_util_cover.TCoverManager testMethod=test_file_encoding>
fn = '\udcff\udcff\udcff\udcff - cover.jpg'

    def add_file(self, fn):
        f = self.full_path(fn)
>       open(f, "wb").close()
E       OSError: [Errno 92] Illegal byte sequence: '/var/folders/j2/1zv9_6pn5656sn85r0yfxy0r0000gn/T/QL-TEST-97517g3x/tmpyqlcgujg/\udcff\udcff\udcff\udcff - cover.jpg'

tests/test_util_cover.py:139: OSError
```

**Comment by lazka** [comment]
Thanks, most likely due to the filesystem change from HFS+ to AFS in 10.13.

See: https://bugs.python.org/issue31380

Another difference between macOS/Linux... 😞

**Comment by zsau** [comment]
Maybe this should be separated into two tests: one with valid non-ASCII UTF-8, and one with invalid UTF-8 that only runs on Linux?

**Comment by lazka** [comment]
Having one with non-ascii unicode should be enough imo (text2fsn())

Now that we are Python 3 only we no longer have to deal with bytes->unicode auto decoding issues anyway.

**Comment by lazka** [comment]
There might be more problems like this - I haven't tested on macOS.
