### ISSUE TITLE
xfce4/Clearlooks-Phenix GTK list rendering bug

### ISSUE THREAD

**Issue by hameau** [quodlibet/quodlibet#2677]
Hello,

**quodlibet 4.0.0 (from ql-debian PPA)
Debian 9 (stretch)
xfce-4.12.3
Theme: Clearlooks-Phenix**

I have the same rendering bug previously reported at #2541 and worked around by commit [1d1bc2b](https://github.com/quodlibet/quodlibet/commit/1d1bc2b844712af3e06a8b329333f7a7b8328bb0).

Adding the following line after line 390 in `quodlibet/_init.py` fixes the rendering while the theme has a problem:
```
        css_override.register_provider("Clearlooks-Phenix", style_provider)
```
(Local modification currently fixes this for me.)

**Comment by lazka** [comment]
Thanks
