### ISSUE TITLE
Splitting tags fails for non-word characters before the separator

### ISSUE THREAD

**Issue by pfps** [quodlibet/quodlibet#2678]
I had a tag value that had multiple separators in it, namely 
Adam Duritz (1964-); Dan Vickrey (1966-); Ben Mize; David Bryson
(my separator is ;).  When I split this quodlibet only split off the last value instead of splitting into four values which is what I expected.  After this split it was not possible to perform further splits.

As far as I can tell, there is very little documentation on what quodlibet does when splitting, and the testing in test_util_string.py is minimal.   There is a cryptic comment in the code for split_value that might be construed as saying something different, but I think that splitting into more than two parts is the correct behaviour.

This appears to be related to https://github.com/quodlibet/quodlibet/issues/1088

**Comment by pfps** [comment]
Oh, the problem I'm experiencing is due to the wrapping of separators in split_values.  Because I have a non-word character at the end of of "value", the separation is not recognized.

The question is what should be done here.  My view is that the word boundary bit should be removed, but that's a decided change from current behaviour.

**Comment by declension** [comment]
Thanks for the report @pfps - and I agree with the diagnosis.

I've got something together that seems to sort this "without breaking existing usage", but like you say the test coverage of this area (value-wise, not lines-of-code wise) is low but I'll add a few

**Comment by pfps** [comment]
Looks good.
