### ISSUE TITLE
combining tag values uses a comma separator

### ISSUE THREAD

**Issue by pfps** [quodlibet/quodlibet#2679]
Here is the complicated setup.

I'm editing tags on two tracks.  One track has a tag with two values - "Adam
Duritz (1964-)" and "Matt Malley".  The other track has no values for that
tag.

I see the two values for the tag, separated, each with "(missing from 1
song)". I click on the tag area and then on the values.  I then see the two
values merged together with the Unicode newline glyph between them.  I then
click elsewhere and the two values are melded together with a comma between
them.  

Problem 1:
I can't split the values apart because I only use semicolon as my separator
character and the separator introduced was a comma.

Problem 2:
Even if I add comma back into my separators I can't split the values apart
because the first "value" ends with a non-word character.

I suggest that this combination isn't done by introducing a comma separator
but instead keeps the newline if possible.

**Comment by declension** [comment]
Thanks. I guess problem 2 is just #2678

**Comment by declension** [comment]
I guess the ideal UX is that the editor somehow allows you to add _multiple_ tags to the edited songs, i.e. giving the new songs _two_ values "Adam Duritz (1964-)" and "Matt Malley", or neither, or either one of the two.

It's multiple values from multiple songs being a problem here. Keeping the newline (an implementation detail, IMO) would probably solve the problem, but still looks weird seeing these "multiple" values suddenly in a single input box...

**Comment by pfps** [comment]
Yes, problem 2 is https://github.com/quodlibet/quodlibet/issues/2678 but I got forced into the issue because of the bad separator choice.  

What I think should happen is that the multiple values stay with the internal (newline) separator and not use the comma (or any other in-line separator).   This should happen everywhere possible and not just in this case.   (Of course there may not be any other cases - I haven't found any yet anyway.)

**Comment by pfps** [comment]
It looks as if it is possible to fix the problem by simply not replacing newline with comma in __edit_tag

I have made the change locally but I have another pending push so making a new push for this one-line change seems a bit much.

#        new_value = ', '.join(new_value.splitlines())  # leaving the newline should be OK

**Comment by CreamyCookie** [comment]
Seems like this was fixed with #2684 and #2678. Closing. 

If I'm mistaken, feel free to reopen.
