### ISSUE TITLE
No notification body

### ISSUE THREAD

**Issue by Djaler** [quodlibet/quodlibet#2680]
After upgrade to 4.0 version there are no body part in system notifications.

**Comment by Djaler** [comment]
![2018-01-01 17 58 41](https://user-images.githubusercontent.com/7964583/34468614-a06081b4-ef1d-11e7-8dd3-a7ed4ef95352.png)
![2018-01-01 17 59 18](https://user-images.githubusercontent.com/7964583/34468615-a07e4816-ef1d-11e7-9995-18a0b3ef497f.png)

**Comment by declension** [comment]
Hmm, I can't replicate this.

Could you post some details on your system, and any debug output at the time (`quodlibet --debug`)?

**Comment by Djaler** [comment]
elementary OS Loki (based on Ubuntu 16.04)

`D: 0.018: util.i18n.init: LANGUAGE: 'ru'
D: 0.018: util.i18n.init: LANG: 'ru_RU.UTF-8'
D: 0.023: util.i18n.register_translation: Translations loaded: '/usr/share/locale/ru/LC_MESSAGES/quodlibet.mo'
D: 0.056: formats._misc.init: MimeType=application/x-flac;audio/aac;audio/aiff;audio/dsf;audio/midi;audio/mp3;audio/mp4;audio/mpeg;audio/mpeg4;audio/mpg;audio/ogg;audio/vorbis;audio/wav;audio/wave;audio/x-aac;audio/x-aiff;audio/x-flac;audio/x-m4a;audio/x-midi;audio/x-mp3;audio/x-mpc;audio/x-mpeg;audio/x-ms-wma;audio/x-ms-wmv;audio/x-musepack;audio/x-oggflac;audio/x-speex;audio/x-tta;audio/x-wav;audio/x-wavpack;audio/x-wma;video/ogg;video/x-ms-asf;video/x-theora;video/x-wmv;
D: 0.056: formats._misc.init: Supported formats: aac, aiff, dsf, midi, mod, monkeysaudio, mp3, mp4, mpc, spc, trueaudio, vgm, wav, wavpack, wma, xiph
D: 0.147: qltk.add_signal_watch: Register Python signal handler: 'SIGHUP'
D: 0.147: qltk.add_signal_watch: Register Python signal handler: 'SIGINT'
D: 0.147: qltk.add_signal_watch: Register Python signal handler: 'SIGTERM'
D: 0.194: main.main: Initializing main library (~/.quodlibet/songs)
D: 0.194: SongFileLibrary.__init__: Initializing SongFileLibrary "main".
D: 0.194: SongFileLibrary.__init__: Using pickling persistence for library "main"
D: 0.194: SongFileLibrary.load: Loading contents of '/home/djaler/.quodlibet/songs'.
D: 0.215: SongFileLibrary.load(<libraries.SongFileLibrary object at 0x7f0d8e854798 (quodlibet+library+libraries+SongFileLibrary at 0x28617a0)>): Done loading contents of '/home/djaler/.quodlibet/songs'.
D: 0.261: PlaylistsBrowser.load_pattern: Loading pattern from /home/djaler/.quodlibet/playlist_pattern
D: 0.261: PlaylistsBrowser.load_pattern: Couldn't load pattern for PlaylistsBrowser ([Errno 2] Нет такого файла или каталога: '/home/djaler/.quodlibet/playlist_pattern'), using default.
D: 0.262: CoverGrid.load_pattern: Loading pattern from /home/djaler/.quodlibet/album_pattern
D: 0.263: CoverGrid.load_pattern: Couldn't load pattern for CoverGrid ([Errno 2] Нет такого файла или каталога: '/home/djaler/.quodlibet/album_pattern'), using default.
D: 0.263: AlbumList.load_pattern: Loading pattern from /home/djaler/.quodlibet/album_pattern
D: 0.264: AlbumList.load_pattern: Couldn't load pattern for AlbumList ([Errno 2] Нет такого файла или каталога: '/home/djaler/.quodlibet/album_pattern'), using default.
D: 0.264: SongFileLibrary.__init__: Initializing SongFileLibrary "filesystem".
D: 0.264: SongFileLibrary.__init__: Using pickling persistence for library "filesystem"
D: 0.264: _main.init_plugins: Starting plugin manager
D: 0.264: _main.init_plugins: Scanning folders: ['/usr/lib/python3/dist-packages/quodlibet/ext/editing', '/usr/lib/python3/dist-packages/quodlibet/ext/events', '/usr/lib/python3/dist-packages/quodlibet/ext/playorder', '/usr/lib/python3/dist-packages/quodlibet/ext/songsmenu', '/usr/lib/python3/dist-packages/quodlibet/ext/playlist', '/usr/lib/python3/dist-packages/quodlibet/ext/gstreamer', '/usr/lib/python3/dist-packages/quodlibet/ext/covers', '/usr/lib/python3/dist-packages/quodlibet/ext/query', '/home/djaler/.quodlibet/plugins']
D: 0.264: plugins.__restore: Restoring plugins: 9
D: 0.264: PluginManager.rescan: Rescanning..
D: 0.264: ModuleScanner.rescan: Rescanning..
D: 0.338: ModuleScanner.rescan: Rescanning done: 88 added, 0 removed, 5 error(s)
D: 0.340: PluginManager.rescan: Rescanning done.
D: 0.340: PluginManager.register_handler: Registering handler: 'EditTagsPluginHandler'
D: 0.340: PluginManager.register_handler: Registering handler: 'RenameFilesPluginHandler'
D: 0.340: PluginManager.register_handler: Registering handler: 'TagsFromPathPluginHandler'
D: 0.340: PluginManager.register_handler: Registering handler: 'GStreamerPlayer'
D: 0.341: PluginManager.register_handler: Registering handler: 'SongsMenuPluginHandler'
D: 0.341: PluginManager.enable: Enable 'Last.fm Sync'
D: 0.341: PluginManager.register_handler: Registering handler: 'CoverPluginHandler'
D: 0.341: PluginManager.register_handler: Registering handler: 'PlaylistPluginHandler'
D: 0.341: PluginManager.register_handler: Registering handler: 'QueryPluginHandler'
D: 0.407: PluginManager.register_handler: Registering handler: 'PluggableOrders'
D: 0.408: PluginManager.register_handler: Registering handler: 'PluggableOrders'
D: 0.409: qltk.playorder.__compose_order: Updating PlaylistModel order to <Random>
D: 0.412: GStreamerPlayer.go_to: Going to None
D: 0.412: PlaylistMux.go_to: Told to go to None
D: 0.412: QueueModel.go_to: Told to go to None
D: 0.412: PlaylistModel.go_to: Told to go to None
D: 0.424: Query.__init__: Creating query "", called from SearchBarBox._update_query_from
D: 0.424: Query.__init__: Creating query "", called from PanedBrowser.activate
D: 0.479: qltk.window.__restore_state: Restore state
D: 0.479: qltk.window.__restore_position: Restore position
D: 0.479: qltk.window.__restore_size: Restore size
D: 0.479: PluginManager.register_handler: Registering handler: 'EventPluginHandler'
D: 0.479: PluginManager.enable: Enable 'Automatic library update'
D: 0.483: AutoLibraryUpdate.enabled: Using threaded notifier
D: 0.484: AutoLibraryUpdate.enabled: Watching directory /media/Dropbox/Music for ['IN_DELETE', 'IN_CLOSE_WRITE', 'IN_MOVED_FROM', 'IN_MOVED_TO', 'IN_CREATE'] (mask: 3c8)
D: 0.485: PluginManager.enable: Enable 'HeadphoneMonitor'
D: 0.491: PluginManager.enable: Enable 'Notify'
D: 0.491: PluginManager.enable: Enable 'Theme Switcher'
D: 0.522: PluginManager.enable: Enable 'QLScrobbler'
D: 0.523: QLScrobbler.enabled: Plugin enabled - accepting new songs.
D: 0.523: PluginManager.enable: Enable 'Automatic Rating'
D: 0.523: PluginManager.enable: Enable 'mpris'
D: 0.525: PluginManager.enable: Enable 'SeekBar'
D: 0.526: PluginManager.register_handler: Registering handler: 'UserInterfacePluginHandler'
D: 0.528: mmkeys.find_active_backend: Trying to find a mmkeys backend
D: 0.528: mmkeys.find_active_backend: Found 'GnomeBackendOldName'
D: 0.531: qltk.session.init: Connected with gnome session manager: /org/gnome/SessionManager/Client11
D: 0.531: _main.run: Entering quodlibet.main
D: 0.678: PlaylistModel.set: Filling view model with 601 songs.
D: 0.684: GStreamerPlayer.go_to: Going to '/media/Dropbox/Music/Jen Titus - O Death.mp3'
D: 0.684: PlaylistMux.go_to: Told to go to '/media/Dropbox/Music/Jen Titus - O Death.mp3'
D: 0.684: QueueModel.go_to: Told to go to None
D: 0.684: PlaylistModel.go_to: Told to go to '/media/Dropbox/Music/Jen Titus - O Death.mp3'
D: 0.686: GStreamerPlayer._end: End song
D: 0.686: GStreamerPlayer._end: Next song
D: 0.706: util.cover.manager.failure: Didn't get cover from FilesystemCover: This source is incapable of fetching covers
D: 0.712: util.cover.manager.run: Found local cover from EmbeddedCover: <tempfile._TemporaryFileWrapper object at 0x7f0d63021080>
D: 0.735: player.gstbe.player.__message: Recalculate latency
D: 1.330: qltk.completion.__build_model: Updating tag model for whole library
D: 1.331: SongFileLibrary.rebuild(<libraries.SongFileLibrary object at 0x7f0d8e854798 (quodlibet+library+libraries+SongFileLibrary at 0x28617a0)>): Rebuilding, force is False.
D: 1.333: SongFileLibrary._changed(<libraries.SongFileLibrary object at 0x7f0d8e854798 (quodlibet+library+libraries+SongFileLibrary at 0x28617a0)>): Changing 1 items.
D: 1.334: qltk.completion.__update_song: Updating tag model for 1 songs
D: 1.335: qltk.completion.__update_song: Done updating tag model for 1 songs
D: 1.390: qltk.completion.__build_model: Done updating tag model for whole library
D: 1.394: SongFileLibrary.rebuild(<libraries.SongFileLibrary object at 0x7f0d8e854798 (quodlibet+library+libraries+SongFileLibrary at 0x28617a0)>): Removing 0, changing 0.
D: 1.395: SongFileLibrary.scan: Scanning '/home/djaler/Music'.
D: 3.153: QLSubmitQueue.send_handshake: Sending handshake to service.
D: 4.008: QLSubmitQueue.send_handshake: Handshake status: OK
D: 4.009: QLSubmitQueue.send_handshake: Session ID: 1de31926b618187241e4476da01ea1ff, NP URL: http://post.audioscrobbler.com:80/np_1.2, Submit URL: http://post2.audioscrobbler.com:80/protocol_1.2
D: 4.009: QLSubmitQueue.send_nowplaying: Now playing song: Jen Titus - O Death
D: 4.428: QLSubmitQueue._check_submit: Submission status: OK
D: 9.278: player.gstbe.player.__about_to_finish: About to finish (async)
D: 9.279: player.gstbe.player.__about_to_finish_sync: About to finish (sync)
D: 9.279: player.gstbe.player.__about_to_finish_sync: Select next song in mainloop..
D: 9.279: PlaylistModel.next_ended: Using <Random>.next_implicit() to get next song
D: 9.280: player.gstbe.player.__about_to_finish_sync: ..done.
D: 9.280: player.gstbe.player.__about_to_finish: About to finish (async): setting uri
D: 9.282: player.gstbe.player.__about_to_finish: About to finish (async): done
D: 10.270: player.gstbe.player.__message: Stream changed
D: 10.270: GStreamerPlayer._end: End song
D: 10.272: GStreamerPlayer._end: Next song
D: 10.280: util.cover.manager.failure: Didn't get cover from FilesystemCover: This source is incapable of fetching covers
D: 10.284: util.cover.manager.run: Found local cover from EmbeddedCover: <tempfile._TemporaryFileWrapper object at 0x7f0d630210b8>
D: 10.301: QLSubmitQueue.send_nowplaying: Now playing song: Metallica - Hero Of The Day
D: 10.390: SongFileLibrary._changed(<libraries.SongFileLibrary object at 0x7f0d8e854798 (quodlibet+library+libraries+SongFileLibrary at 0x28617a0)>): Changing 2 items.
D: 10.391: qltk.completion.__update_song: Updating tag model for 2 songs
D: 10.391: qltk.completion.__update_song: Done updating tag model for 2 songs
D: 10.720: QLSubmitQueue._check_submit: Submission status: OK
D: 14.202: qltk.window.__restore_state: Restore state
D: 14.202: qltk.window.__restore_position: Restore position
D: 14.202: qltk.window.__restore_size: Restore size
^CD: 15.275: qltk.idle_handler: Python signal handler activated: SIGINT
D: 15.278: main.before_quit: Saving active browser state
D: 15.279: main.before_quit: Shutting down player device 'GStreamer: 1.8.3.0'.
D: 15.290: PluginManager.save: Saving plugins: 9 active
D: 15.290: PluginManager.enable: Disable 'Automatic library update'
D: 15.291: AutoLibraryUpdate.disabled: Stopping inotify watch...
D: 15.291: PluginManager.enable: Disable 'HeadphoneMonitor'
D: 15.291: PluginManager.enable: Disable 'Notify'
D: 15.292: PluginManager.enable: Disable 'Theme Switcher'
D: 15.340: PluginManager.enable: Disable 'QLScrobbler'
D: 15.340: QLScrobbler.disabled: Plugin disabled - not accepting any new songs.
D: 15.340: PluginManager.enable: Disable 'Automatic Rating'
D: 15.340: PluginManager.enable: Disable 'mpris'
D: 15.361: PluginManager.enable: Disable 'SeekBar'
D: 15.363: PluginManager.enable: Disable 'Last.fm Sync'
D: 15.364: _main.quit_gtk: Quit GTK: done.
D: 15.377: _main.run: Gtk.main() done.
D: 15.378: library.save: Saving all libraries...
D: 15.378: SongFileLibrary.save(<libraries.SongFileLibrary object at 0x7f0d8e854798 (quodlibet+library+libraries+SongFileLibrary at 0x28617a0)>): Saving contents to '/home/djaler/.quodlibet/songs'.
D: 15.412: config.save: Writing config...
D: 15.413: main.main: Finished shutdown.`

**Comment by Djaler** [comment]
I revert 3.9.1 and all works good.
![2018-01-01 21 24 57](https://user-images.githubusercontent.com/7964583/34470031-3e92cbe6-ef3a-11e7-8861-64285aead7e5.png)
