### ISSUE TITLE
Random Album Plugin no longer selects a new album.

### ISSUE THREAD

**Issue by mjpieters** [quodlibet/quodlibet#2683]
After upgrading to QL 4.0.0, the *Random Album Playback* plugin stopped selecting a new album when the current album completes.

I play music from the *Album List* view of my library. I can pick a random album with CMD-M, and play that displayed album. But when the last track in the album finishes, I expect a new album to be selected at random, and playback to continue with that new album. Instead, playback simply stops.

I use QL 4.0.0 on Mac OS X 10.13.2 (High Sierra). I don't have any non-standard plugins installed; only the OSD, audioscrobbler, last.fm sync and bookmark plugins are enabled beyond the Random Album Playback plugin.

**Comment by lazka** [comment]
Thanks.
