### ISSUE TITLE
Free text search for version tag (among others) not working

### ISSUE THREAD

**Issue by renma** [quodlibet/quodlibet#2688]
* What did you try to do?
Songs (flac) in library with a version tags.
For example version = T-1942.
Version is configured as visible column.
Free text search "t-1942".

* What did you expect to happen?
Songs with version=T-1942 are displayed. 

* What did happen instead?
No songs are displayed.
Remark 1: With an exact search (version=t-1942) songs are displayed.
Remark 2: Wrong behavior as well for organization and labelid (and maybe others).
Remark 3: Free text search works for "standard tags" like grouping and title.

* Which version of Quod Libet?
4.0.0

* Which operating system including version (Ubuntu 14.04, Win7, Debian sid, ...)?
Arch-Linux current.

**Comment by lazka** [comment]
Thanks

**Comment by lazka** [comment]
Looks like 070e0bf012b0c10e0 removed that in the search browser and also removed the ability to search in newly added columns. @declension ping

**Comment by declension** [comment]
OK I'll have a look now.

**Comment by declension** [comment]
Hmm I see. Perhaps the `SearchBarBox` should listen to changes in `SongList` columns and update its own star

**Comment by declension** [comment]
Yes that seems to work in testing, though feels a little hacky. I'll try to have another look tonight...

**Comment by lazka** [comment]
or add get_query(star) and update the cache/star if it doesn't match.
