### ISSUE TITLE
Toggle menu bar plugin not working [bug]

### ISSUE THREAD

**Issue by adinan-cenci** [quodlibet/quodlibet#2699]
The plugin to toggle the menu bar with the Alt key is not working.

When I press the Alt key nothing happens and now I can't access the menu bar.

Is there a config file where I can edit out the plugin?

**Comment by lazka** [comment]
`~/.quodlibet/config` or `~/.config/quodlibet/config`  and delete lines with "ToggleMenuBar"

Weird, it's working fine here.

**Comment by Meriipu** [comment]
can you rightclick on something to bring up the context menu, and select "configure plugins" via the context menu>Plugins>
say right clicking on a track or at the top where the information about the current track is ?

**Comment by lazka** [comment]
ah, right, that would be an easier way.

**Comment by adinan-cenci** [comment]
@Meriipu I tried to bring up with the context menu. Right clicked the shit out of it but nothing worked.
@lazka Thank you. It worked

**Comment by adinan-cenci** [comment]
So, to log the bug: I am using Linux Mint 18.3, kernel 4.10.0.38-generic

**Comment by lazka** [comment]
Thanks. One workaround might be to disable num lock and caps lock on your keyboard.
