### ISSUE TITLE
tests: pytest doesn't fail for unhandled exceptions in signal handlers

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#2705]
pyqt has something to make it work: https://pytest-qt.readthedocs.io/en/2.3.1/virtual_methods.html
  

also https://github.com/pytest-dev/pytest/issues/73

**Comment by lazka** [comment]
9 tests are failing due to this, better look at it before 4.0.1

**Comment by declension** [comment]
Cool. I've noticed this problem a couple of times too actually - adding a test that "fails" but only if you look at debug logs a lot...
