### ISSUE TITLE
Connecting to SoundCloud?!

### ISSUE THREAD

**Issue by MartinL0815** [quodlibet/quodlibet#2711]
I use the portable version of quotlibet and want to authorize SoundCloud.

As I can read in the User Guide, the authorization only works, if the OS is configured to know about "quotlibet://" URLs, has a related URL handler.

So it is not very surprising, that pressing the "connect" button in the SoundCloud view/browser does not succeed in anything!
The only change in UI is the hint to enter the authorization code.

Is there an alternative way to authorize?
Is there a way to block authorization for portable versions until an alternative way is available, to prevent confusion?

Any chance for a change?

**Comment by lazka** [comment]
The connect button should still open a web browser. But at the end you have to manually copy and paste the authorization code.

**Comment by declension** [comment]
Yes there are two ways: the URL handler or manually entering the code from the web page that gets launched on connecting.

If neither is working then please post a screenshot and/or some steps to replicate and I'll have a look. 

It could probably do with better documentation either way...

**Comment by lazka** [comment]
(could still be that this is somehow broken on Windows, so if you don't get it to work, please say so)

**Comment by declension** [comment]
(Closed by mistake)

**Comment by MartinL0815** [comment]
The web page didn't open, even if the protocol handler (http://) is still the default (IE 11).
So, how to get the authorization code from where?

**Comment by lazka** [comment]
OK, then something isn't working, will have a look.

**Comment by MartinL0815** [comment]
After replacing the distribution [2710] I started a next try to connect to SoundCloud.

This time a Website opened in IE11 and signed into SoundCloud.
The next problem is, that IE11 can't handle - even in Edge DocumentMode - the resulting page and didn't display the code, which is glady in the URL of this page.

So I was now able to connect to my SoundCloud account.
