### ISSUE TITLE
Errors in rendering text on MS Windows 7 …

### ISSUE THREAD

**Issue by MartinL0815** [quodlibet/quodlibet#2712]
I observed problems with some characters on my MS Windows 7 system.

Here some screenshots:

* Album Browser:
![Screenshot from Album Browser](https://user-images.githubusercontent.com/525700/34874384-16780e7a-f799-11e7-965d-ab778336b683.png)
* Keyboard Shortcuts:
![Keyboard Shortcuts](https://user-images.githubusercontent.com/525700/34874430-31e9f8ee-f799-11e7-8e0c-d91f74997f01.png)

Playing music lets appear some other "invalid" characters, mostly "time" related.

**Comment by lazka** [comment]
Thanks. I guess you are not using the default Windows font?

**Comment by MartinL0815** [comment]
Can't remember to have changed something.

My system is an English one, switched to German. Asian fonts are installed.

Speciality: 150% display zoom and high-contrast-mode switched on.

**Comment by MartinL0815** [comment]
Another screenshot of the plugins dialog, from the "Advance Preferences" element:

> 
![Advanced Preferences - Plugins Dialog](https://user-images.githubusercontent.com/525700/34881397-c5719558-f7b3-11e7-8cf7-178ddd7ab56e.png)

**Comment by MartinL0815** [comment]
A next screenshot from the Preferences dialog, the tags property sheet tab:

> 
![Tabs - Preferences Dialog](https://user-images.githubusercontent.com/525700/34881836-effd18c8-f7b4-11e7-8c05-87dafc25eb21.png)

**Comment by lazka** [comment]
Comparing with my Win7 (it uses "Segoe UI") the font looks different, so I guess you have a different font which doesn't include those glyphs.

We need to look into how font fallback works, and if we can ship a fallback one somehow.

**Comment by MartinL0815** [comment]
Thanks for caring!  
I'll use a tool to try to get to know the used font! 
The font "Segoe UI" is available so it should be usable. 
Additionally I try to get the eventually existing font mapping table from the registry.

**Comment by MartinL0815** [comment]
I updated today to 4.0.1 by replacing the data folder and suddenly all characters look like selected! 
My try to find out the used font failed, because my utility failed in displaying more than top-level windows.

**Comment by MartinL0815** [comment]
Is the UI build with tkInter?
Is there a kind of python console? A chance to access the tcl interpreter, so I can use my tcl/Tk knowledge to analyse the fonts usages?

**Comment by lazka** [comment]
We use gtk+, which uses pango as font backend. And for pango we use the win32 backend.

**Comment by lazka** [comment]
There is a Python console plugin builtin.

**Comment by MartinL0815** [comment]
Ok - I restarted quodLibet this morning and now the wrong rendering occurs again!
So, this "glad" moment after starting 4.0.1 the first time, seeing the correct rendering, vanished immediately.
Since I'm not a Python dev and not in too deep into gTk, could you please provide a code snippet for the Python console to inspect the font settings of some of the widgets?
Eventually it would be enough to know the path to the list of tracks, since the track lengths do not display the colon character or to the queue title displaying the length of all queued tracks with the wrong hour/minute/second separator.
Or do you have some debug code available to introspect such control/widget properties?

BTW. What characters do you use as hour/minute/seconds separator? Not a simple colon, which is part of every font?

While running the 4.0.1 the first time I couldn't use the multi-media-keys.
Now, they are usable, but the rendering of text fails again.

**Comment by MartinL0815** [comment]
If I can provide information using the Python console, than I'd be glad about some code to use to get the desired/needed information!

**Comment by lazka** [comment]
I've fixed some related issue in pango https://gitlab.gnome.org/GNOME/pango/merge_requests/34

So there is a chance this will be fixed with 4.3

**Comment by lazka** [comment]
I've uploaded 4.2.1 which already contains the improvements. Testing welcome.

**Comment by lazka** [comment]
I think this is fixed, so closing.
