### ISSUE TITLE
Question: Adding Folders to Library from the menu or the preferences

### ISSUE THREAD

**Issue by MartinL0815** [quodlibet/quodlibet#2716]
After extracting and starting the first time, after setting up the high-contrast theme and some plugins, I added two folders in the main window from the file menu using "Add Foloder".
After adding the folders, quotlibet told at the right bottom about scanning and updating the library.

In the preferences, in the library property sheet those folders weren't listed at all, so I added them here, too.

Is this necessary or was this a bug?

**Comment by lazka** [comment]
The one in the menu just loads the content, the one in the library preferences adds them to the list of paths to scan in, when doing a library scan.

We used to have a checkbox in the folder chooser to also add the folders to the library scan paths, but that was lost when we switched to native Windows file choosers.

**Comment by MartinL0815** [comment]
I followed the use guide and was quiet irritated, that the scan state displayed at the right bottom didn't differ and I didn't realized no difference in the browsers.
