### ISSUE TITLE
Edit controls to enter e.g. tag patterns don't show scrollbars

### ISSUE THREAD

**Issue by MartinL0815** [quodlibet/quodlibet#2717]
The edit controls used in dialogs, e.g. to enter tag patterns, do not show scrollbars:

> 
![Tag Pattern Dialog](https://user-images.githubusercontent.com/525700/34885053-f489361a-f7be-11e7-9312-1e7573359496.png)

Thus there is no easy way to recognize eventually overlapping content and no way to scroll using the mouse.

In the screenshot I resized the dialog to make it easier to recognize overlapping content.

**Comment by lazka** [comment]
The scrollbar shows when you hover the text field.

I guess we could always show it like on macOS, as Windows users might not be familiar with this.

**Comment by MartinL0815** [comment]
Thanks for the information. 
If the scrollbars are as slim, I won't recognize. 
Since some eye disabilities exist, I set up display zoom to 150 % and use switched on high contrast mode. The design rules we use in our product development caused wider scrollbars since they are scaled too! 
And yes, I'm not used to see scrollbars only when hovering over an edit control and I use them to recognize text outside the view.

**Comment by lazka** [comment]
ok, yeah, let's switch it on Windows.

**Comment by lazka** [comment]
In the meantime you can go to "File > Plugins > Advanced Preferences", click the button, and in the lowest field, titled "Scrollbars always visible", chant the text to "true"

**Comment by lazka** [comment]
It should look like this now:

![screenshot from 2018-01-15 22-09-18](https://user-images.githubusercontent.com/991986/34961722-cd24468a-fa40-11e7-8e7b-d6b7e25b1c83.png)

**Comment by MartinL0815** [comment]
I updated today to 4.0.1 by replacing the data folder and didn't find the mentioned option in the advanced settings.

**Comment by MartinL0815** [comment]
Thanks for the changes!

**Comment by lazka** [comment]
oh, oops, that was only added recently in #2697 :/
