### ISSUE TITLE
"Tray Icon" Plugin - Scroll Wheel option seems to be not working on Windows 7

### ISSUE THREAD

**Issue by MartinL0815** [quodlibet/quodlibet#2718]
I activated the option to control the volume using the Scroll Wheel, while the mouse is hovering the tray icon.

> 
![Tray Icon - Plugins](https://user-images.githubusercontent.com/525700/34885249-a45c5b94-f7bf-11e7-8337-081a43ac1ca1.png)

Sincerely the option does not work, or quodlibed does not react onto the scroll wheel rotations.

Or did I misunderstood this functionality?

**Comment by lazka** [comment]
Might be that that's not supported under Windows.
