### ISSUE TITLE
Segfault when running full test on MacOS 10.13.2

### ISSUE THREAD

**Issue by zsau** [quodlibet/quodlibet#2720]
Mac OS X 10.13.2, QL master. Segfaults when running `setup.py test`, somewhere in `tests/test_util.py`. Could be related to #2673, but that's a hang rather than a segfault.

Can attach logs as needed, and/or continue debugging with some guidance.

**Comment by lazka** [comment]
I see the same in #2791 now

**Comment by lazka** [comment]
Fixed by 7d68847b906e8917
