### ISSUE TITLE
Free text search in album list not searching in people

### ISSUE THREAD

**Issue by marcelpaulo** [quodlibet/quodlibet#2725]
Since the latest update, **4.1 (development, ed8e72027)**, free text searches in album list are not searching in people anymore, even though `Inline search includes people` is enabled. It was working before the last update.

To give an example, I searched for *bernardo sassetti* in the album list:

![screenshot_2018-01-14_22-31-24](https://user-images.githubusercontent.com/10074769/34922774-92f9504c-f97b-11e7-94d3-c13ae6477991.png)

Only the 9 albums where `artist` is *Bernardo Sassetti* are shown, and not the albums where he was in `album artist`. If I search *bernardo sassetti* `performer`:

![screenshot_2018-01-14_22-30-34](https://user-images.githubusercontent.com/10074769/34922801-e0b9666e-f97b-11e7-8bf4-ef7113a738e1.png)

as expected, only the albums where `album artist` contains *bernardo sassetti* are shown.

Before the last update, a free text search for *bernardo sassetti* showed both sets of albums, the 9 where `artist` is *bernardo sassetti* **+** the 4 where he was in `album artist`.

**EDIT**: I'm installing QL from `ppa:lazka/dumpingplace`

**Comment by lazka** [comment]
#2723

**Comment by marcelpaulo** [comment]
I did see #2723 but it doesn't mention searches, so I thought it wasn't related. But anyway, I could have added to that bug, or at least referenced it here as you did, @lazca.My apologies.

**Comment by lazka** [comment]
No problem, any report helps. I didn't go into detail in #2723 as I just wanted to file something so I don't forget to look into it.

I've pushed an update to the PPA, but it says update might take an hour or so.

**Comment by lazka** [comment]
ppa is updated now

**Comment by marcelpaulo** [comment]
I had just downloaded and tested when I saw your message, @lazka. It's working as before, searching `~people`, thanks to your 3ff1c688a8dff28991b3fd5d7c89413c74707113 ! Thanks for the speedy correction !

**Comment by lazka** [comment]
Thanks for testing!
