### ISSUE TITLE
Is there a chance to choose output device?

### ISSUE THREAD

**Issue by MartinL0815** [quodlibet/quodlibet#2727]
I use two output devices, the built-in sound card and a speaker with its own sound card.
In foobar2000 I was able to add a keyboard shortcut to change between those devices.
In quodlibet I didn't find a configuration/setup for the device.

Is there already the capability to set-up the device or a chance to this, eventually very OS dependent, into quodlibet?

**Comment by lazka** [comment]
It might be possible, see #1440

**Comment by MartinL0815** [comment]
Thanks for pointing out.

If the output device enumeration would be possible, it would help to switch easily, without forcing the OS to change the default output device.

**Comment by lazka** [comment]
Closing as a duplicate for #1440. I've added some Windows info there. You can subscribe to that issue if you want to receive notifications on updates.
