### ISSUE TITLE
"Browse Folder" plugin not working in 4.0.1?

### ISSUE THREAD

**Issue by MartinL0815** [quodlibet/quodlibet#2728]
I activated the "Browse Folder" plugin …

> 
![Browse Folder - Plugins](https://user-images.githubusercontent.com/525700/34985325-fc7da8a4-fab3-11e7-8e7d-30be0ec333fb.png)

… but the context menus of the tracks …

> 
![context menu for tracks](https://user-images.githubusercontent.com/525700/34985404-2bd711a8-fab4-11e7-82f9-3710f4bf1b69.png)

… and the albums …

> 
![context menu for albums](https://user-images.githubusercontent.com/525700/34985452-453f3544-fab4-11e7-9301-987e72154376.png)

… doesn't show anything like "Browse/Explore Folder".

Since the main menu doesn't show something similar, where do I find "Browse Folder" normally and is it really missing?

**Comment by lazka** [comment]
It should be in the "Plugins" sub menu

**Comment by MartinL0815** [comment]
Thanks!
And sorry for polluting the issues list!
