### ISSUE TITLE
Lyrics no longer available via LyricWiki API

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#273]
Original [issue 273](https://code.google.com/p/quodlibet/issues/detail?id=273) created by jrittenh on 2009-08-08T18:02:27.000Z:

Noticed as of today, attempting to download lyrics gives the following
response:

Unfortunately, due to licensing restrictions from some of the major music
publishers we can no longer return lyrics through the LyricWiki API (where
this application gets some or all of its lyrics).

The lyrics for this song can be found at the following URL: &lt;url here&gt;

(Please note: this is not the fault of the developer who created this
application, but is a restriction imposed by the music publishers themselves.)

**Comment by CreamyCookie** [comment]
@lazka This can be closed AFAIK.

**Comment by CreamyCookie** [comment]
This bug report can be closed.

**Comment by lazka** [comment]
Yeah I guess. The original issue can't really be fixed.
