### ISSUE TITLE
Multimedia keys stop working after some time

### ISSUE THREAD

**Issue by MartinL0815** [quodlibet/quodlibet#2734]
I started to use quodLibet with v4.0 and was glad, that the multimedia-keys worked right from the start, without any configuration.
Now I'm using v4.0.1 and the multimedia-keys stop working after some runtime of quodLibet.
Is there a kind of log/debug info to be extracted/exported from the Python console (would need some help, but sure possible) to help detecting, when the multimedia-keys stop working?

I'm on MS Windows 7 and use a MS keyboard with MS keyboard drivers - evt. unimportant, since the multimedia-keys continued to work after restarting quodLibet.

**Comment by lazka** [comment]
See #2655
