### ISSUE TITLE
Check for Updates... window not closed properly

### ISSUE THREAD

**Issue by xhc1** [quodlibet/quodlibet#2736]
it is not closed on first time by click on button "Close" inside window

1. open Help -> Check for Updates...
2. click on button "Close" in window
3. window not closed just resized
4.  click on button "Close" again
5. now window closed

fedora 27 64bit
quodlibet 4.0.0

**Comment by lazka** [comment]
Is this under XFCE?

**Comment by lazka** [comment]
ah, nevermind, yeah I've seen that issue when no headerbar is used.

**Comment by MartinL0815** [comment]
I just found this issue and if it helps, this issue also happens with 4.0.2 on Windows 7.

**Comment by xhc1** [comment]
actually I cant reproduce it with: greybird theme
(gtk3 theme 3.22.9, fedora)

**Comment by declension** [comment]
Is this still happening?

**Comment by xhc1** [comment]
currently no longer: tried QL 4.4.0 in Fedora 34 + xfce 4.16

**Comment by declension** [comment]
Great! I'll close then. Please re-open if it does
