### ISSUE TITLE
Add plugin to export playlists into Google Play Music

### ISSUE THREAD

**Issue by idlethread** [quodlibet/quodlibet#2737]
Google Play Music allows uploading of upto 50000 songs for archival purpose and streaming using the Google Music Manager. While quodlibet is perfect as a desktop music player, I switch to Google Play Music to play the music on my mobile devices.

It would be nice to export the playlists created in quodlibet to Google Play Music directly (and perhaps a way to keep them in sync).

**Comment by urielz** [comment]
Not really what you're asking but it looks like you could at least export the playlists manually by using the "Export as Playlist" plugin to create an M3U file. I don't use Google Play Music so I'm not sure about this.

**Comment by declension** [comment]
[gmusic-playlist](https://github.com/soulfx/gmusic-playlist) looks useful here

**Comment by idlethread** [comment]
@urielz Google Play Music for whatever reason doesn't support importing .m3u or .pls files, it seems.

@declension That looks promising. I'm going to try it out. Thanks.

**Comment by kellertobias** [comment]
Google Play Music does not support a Public API for managing the Playlists. Also Google Play Music is deprecadted and will be replaced with youtube music soon.

**Comment by declension** [comment]
Google Music is now in deprecation mode, sigh. Closing ticket.
