### ISSUE TITLE
Mac shortcuts 

### ISSUE THREAD

**Issue by michaelfresco** [quodlibet/quodlibet#2738]
I noticed that Quodlibet does not follow the typical Mac shortcut for the preferences window. 

    cmd + ,     # is normally used for preferences

**Comment by urielz** [comment]
Indeed, this was mentioned before. There are multiple threads about shortcuts, I am a proponent for having OS dependent shortcuts (https://github.com/quodlibet/quodlibet/issues/1878), or at least let the user customize shortcuts.

**Comment by CreamyCookie** [comment]
Closing this one, since it's part of #1701 (and #1878).
