### ISSUE TITLE
Feature Request: Creation of custom filters

### ISSUE THREAD

**Issue by ghost** [quodlibet/quodlibet#2740]
It would be cool to have custom filters that allows you to filter songs based on specific criteria. Rhythmbox and gmusicbrowser are music players that have powerful custom filter creators that you guys can look to for inspiration

**Comment by urielz** [comment]
You can do that. Check the very bottom of this page: https://quodlibet.readthedocs.io/en/latest/guide/searching.html

**Comment by declension** [comment]
See also #809 which talks about exactly this
