### ISSUE TITLE
Waveform seekbar plugin does not load on startup

### ISSUE THREAD

**Issue by FerdiScholten** [quodlibet/quodlibet#2747]
On version 4.0.2 the waveform seekbar plugin is not loaded when Quodlibet is started. This is on Ubuntu 17.10 with Gnome on Wayland Also on X, and also on Ubuntu 16.04 with unity on X
The plugin does work when it is deselected and then selected again in the plugin window.

**Comment by FerdiScholten** [comment]
This was due to the "Alternative seek bar" being also selected as plugin. Disabling that plugin restored the Waveform seek bar.

**Comment by declension** [comment]
But this reminds me we really need to sort out the mutually-exclusive plugins problem here. It's so hard for people to work out, and they shouldn't have to.  I think there was a ticket for it somethwere...
