### ISSUE TITLE
config: quodlibet/control - empty file, QL does not start

### ISSUE THREAD

**Issue by Meriipu** [quodlibet/quodlibet#2754]
So just now during playback quodlibet froze.
I killed it and tried starting, and it hung for a while (debug printing some usual stuff), but the application never showed - then the process stopped.

I checked my .config and there was a control file (or named pipe perhaps), and removing it made quodlibet start again successfully. 

I have no idea how this happened but yes

edit: well it gets recreated again, I guess I never noticed it. But removing it the first time fixed it for me, I have no idea why.

**Comment by lazka** [comment]
Which OS?

**Comment by Meriipu** [comment]
Linux

**Comment by lazka** [comment]
It's used to communicate with the running instance. If that one deadlocks the calling one will wait 10 seconds and then replace it.

Maybe something has changed with Python 3 there.

https://github.com/quodlibet/quodlibet/blob/master/quodlibet/quodlibet/util/fifo.py

**Comment by lazka** [comment]
I have some problems with opening audio files with QL, which could be related.

**Comment by lazka** [comment]
and SIGINT under wayland also doesn't work...  hm :/

**Comment by Meriipu** [comment]
I ran into it again, not sure what I did.

**Comment by lazka** [comment]
The hanging part might be due to #2714 in case you are using the newest GStreamer.

**Comment by Meriipu** [comment]
that might well be it, 1.12.4
