### ISSUE TITLE
Crossfeed plugin not working

### ISSUE THREAD

**Issue by Max-Tweddell** [quodlibet/quodlibet#2755]
Please describe the problem thoroughly and accurately. If possible paste
the contents of the ~/.quodlibet Dump or MiniDump file associated with the
problem; otherwise, you must at a minimum report the version of Quod Libet
and the operating system you are using.

Running Quod Libet version 3.0.1.105.d453d16ebd1a-1 from hg repo on Arch Linux x86_64 (Linux 3.11.3-pf #2 SMP PREEMPT Wed Oct 16 15:24:45 EEST 2013 x86_64 GNU/Linux)

- What did you try to do?

I tried to use the crossfeed plugin.

- What did you expect to happen?

It shows me options for enabling and configuring crossfeeding.

- What did happen instead?
There was no plugin and in the errors section it stated "Couldn't find GStreamer element 'bs2b'."
even though all the Gstreamer plugins are installed (good, bad, ugly, etc')

I am using Manjaro Linux

**Comment by Max-Tweddell** [comment]
Upon further investigation this is becuase the bs2b element is not currently being compiled on gst-plugins-bad

**Comment by lazka** [comment]
Thanks, I assume this is because Arch doesn't has it as well.

I've filed a bug: https://bugs.archlinux.org/task/57319

**Comment by lazka** [comment]
Should this be filed in Manjaro as well, or do you think that is enough?

**Comment by lazka** [comment]
This was instantly fixed in Arch. Thanks @heftig!

@Max-Tweddell thanks for the report!
