### ISSUE TITLE
RandomAlbum throws ValueError when playing finishes and no songs are in songlist

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#2756]
(From https://sentry.io/quodlibet/quodlibet/issues/446018784/)

### Steps to replicate
 * Enable random album plugin
 * Play a song
 * Select an album browser (e.g. Album list)
 * Make sure no albums are selected (e.g. enter an query with zero results)
 * Double-click the "0 albums" entry to clear the songlist
 * Wait till end of track

### Expected
No error, random album

### Actual

```
ValueError: max() arg is an empty sequence
  File "quodlibet/plugins/events.py", line 142, in __invoke
    handler(*args)
  File "quodlibet/ext/events/randomalbum.py", line 189, in plugin_on_song_started
    album = max(album_scores)[1]

ValueError: max() arg is an empty sequence
```

**Comment by declension** [comment]
updated with simplified test case
