### ISSUE TITLE
Incorrect song lengths

### ISSUE THREAD

**Issue by UnicodeAlt255** [quodlibet/quodlibet#2758]
I'm running Arch Linux, with everything up to date,  and the latest quodlibet built from github.

All the songs in the album Panic by Caravan Palace have insanely long lengths. Rescanning and rebuilding and whatnot isn't changing the lengths. And I know that they are not actually that long because ncmpcpp and clementine recognize their true lengths and also, if I try to seek ahead to for example, 1 hour into a song, quodlibet will immediately skip to the next song. 

![screenshot_20180204_001914](https://user-images.githubusercontent.com/12755239/35775619-1d7c553c-0941-11e8-8bfc-e7b196d5a306.png)

**Comment by lazka** [comment]
Can you send me one of those files? -> reiter.christoph@gmail.com

**Comment by lazka** [comment]
Thank. This is https://quodlibet.readthedocs.io/en/latest/guide/faq.html?highlight=tlen#why-do-my-mp3-files-have-the-wrong-length

We have a "Fix MP3 duration" plugin, but I see that is broken for some reason.. :/

**Comment by lazka** [comment]
I think we should just remove TLEN support..

**Comment by UnicodeAlt255** [comment]
Is there any benefit to having TLEN support? Because if ncmpcpp and clementine recognized the true lengths of the songs, it would imply that they didn't care about the TLEN frame right? 

I removed the "Length" tag in kid3 from all the songs in the album and now quodlibet is displaying the correct lengths.

**Comment by lazka** [comment]
> Is there any benefit to having TLEN support? Because if ncmpcpp and clementine recognized the true lengths of the songs, it would imply that they didn't care about the TLEN frame right?

I don't think so, no, I've removed it now. Might be that 10 years ago our MP3 parsing code wasn't that good and TLEN helped for the cases where it failed.

> I removed the "Length" tag in kid3 from all the songs in the album and now quodlibet is displaying the correct lengths.

:+1:
