### ISSUE TITLE
Have playlists organized as a tree

### ISSUE THREAD

**Issue by ptitjes** [quodlibet/quodlibet#2763]
I'm now having some difficulties to handle my numerous playlists. I was wondering about contributing support to organize playlists as a tree of playlists.

That would consist of:
- using sub-folders in the playlists directory
- use a tree component to render the playlist tree instead of a list
- handle the current selected element location for the creation of new playlists
- add a button to add a playlist folder
- rework the `Playlists` contextual menu with sub-menus

This is not a trivial work but there is not much technical difficulties.

What do you think ? Do you see a missing point ? Would you accept such a contribution ?

**Comment by declension** [comment]
See #1065 which I should get back to actually

**Comment by ptitjes** [comment]
Arghhh... Missed it ! I was searching for 'playlists as tree'. Sorry for the dupe.

Glad you are working on that anyway. Thanks @declension.

**Comment by declension** [comment]
No worries @ptitjes , perhaps this is the motivation to get it pushed, in some form at least :)

**Comment by ptitjes** [comment]
@declension BTW, would it be possible to shrink all the add/import buttons in a sub-menu or at least have a 'Show icon only' option ? I tend to work on small screens when I'm playing music and, even if I have short playlist names, the playlist pane uses a lot of space.

**Comment by declension** [comment]
Sounds reasonble @ptitjes - please raise a separate issue though.
