### ISSUE TITLE
Allow to resize the playlist browser's side pane to a smaller width

### ISSUE THREAD

**Issue by ptitjes** [quodlibet/quodlibet#2765]
The playlist browser's side pane (that lists the playlists) occupy a lot of space even when the playlist names are short. This is due to the fact that the 'Add' and 'Import' buttons prevent to resize to a smaller size than their cumulated minimum width. This is frustrating when you work on small screens or want to have two windows side by side.

I see two possible ways to fix this problem:
- either shrink all the add/import buttons in a '+' sub-menu,
- or have a 'Show icon only' option somewhere

Also maybe we could rethink the fact that there is only one item in the 'Preference' menu.

Thoughts, ideas ?

**Comment by urielz** [comment]
Another alternative (I don't know if it's possible) would be to move the buttons down (to the right of Filters).

![image](https://user-images.githubusercontent.com/11670888/35936568-94790c20-0c11-11e8-9079-c764d59bdaff.png)

**Comment by lazka** [comment]
https://lazka.github.io/pgi-docs/#Gtk-3.0/classes/FlowBox.html should also work, it should stack things vertically if there is no space.

**Comment by urielz** [comment]
I'm of the opinion of removing the labels and leaving the icons (with a floating description when mouse hovers). This would solve the problem and also be more consistent with the general look and feel of the UI. Looking at the UI, I don't see labels for many options (toggle shuffle mode, toggle repeat mode, toggle queue visibility, volume, etc). So why these should have labels?

But if the above is not a popular opinion, I would choose alternative 3. I think it's the one that looks best.

**Comment by lazka** [comment]
> I'm of the opinion of removing the labels and leaving the icons (with a floating description when mouse hovers). This would solve the problem and also be more consistent with the general look and feel of the UI. Looking at the UI, I don't see labels for many options (toggle shuffle mode, toggle repeat mode, toggle queue visibility, volume, etc). So why these should have labels?

Yeah, in older versions we had many more labels in the UI, but they have all been removed over time and it would probably be more consistent doing something similar here. But the flowbox still seems like an good improvement for now.

> But if the above is not a popular opinion, I would choose alternative 3. I think it's the one that looks best.

+1

**Comment by declension** [comment]
Agree with @urielz on both points. 

Especially as there's a new button (&label) in the unmerged branch for playlist folders support (note to self etc...) which makes the problem more noticeable

**Comment by frestr** [comment]
It should now be as alternative 3, but with the labels as tooltips instead.
