### ISSUE TITLE
AttributeError in qlscrobbler.py when trying to scrobble to last.fm

### ISSUE THREAD

**Issue by hell-g** [quodlibet/quodlibet#2768]
I set up AudioScrobbler Submission plugin to scrobble to last.fm. The configuration dialog for the AudioScrobbler Submission gives me an authentication successful when I hit the verify account data button. I was expecting, that the songs I play in quodlibet would show up in my last.fm account page. But I could not see any of the songs I played on my last.fm profile page. I tried with other software that I had set up to scrobble to last.fm and those worked. 

When starting quodlibet from the terminal, I see the following output after I start playing the first song:

> Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.6/threading.py", line 864, in run
>     self._target(*self._args, **self._kwargs)
>   File "/usr/lib/python3.6/site-packages/quodlibet/ext/events/qlscrobbler.py", line 224, in run
>     if self.send_submission():
>   File "/usr/lib/python3.6/site-packages/quodlibet/ext/events/qlscrobbler.py", line 316, in send_submission
>     data['%s[%d]' % (key, idx)] = val.encode('utf-8')
> AttributeError: 'bytes' object has no attribute 'encode'

I am running Quod Libet 4.0.2, Mutagen 1.39 on Arch Linux 4.15.1-2-ARCH #1 SMP x86_64 with python 3.6.4. 

Thank you for looking into this!!

**Comment by lazka** [comment]
thanks

**Comment by lazka** [comment]
for reference: #2778
