### ISSUE TITLE
Interacting with Quodlibet

### ISSUE THREAD

**Issue by Lagrang3** [quodlibet/quodlibet#2769]
Hello,

I would like to make a program that interacts with Quodlibet.
After reading here [http://quodlibet.readthedocs.io/en/quodlibet-3.9/guide/interacting.html]
I understood that I can send requests to Quodlibet either by sending the system command
`$ quodlibet --[option]`
or using the FIFO at 
`~/.quodlibet/control`

However I still don't know where can I read the output. That's my question.

For example if my program wants to read the artist of the song being played it will 
print in `~/.quodlibet/control` the following line:
`print-playing '<artist>' `
afterwards, which input file do I have to read to get the answer?

Thanks
Eduardo

**Comment by lazka** [comment]
the fifo doesn't support output.

I'd recommend using the MPRIS2 dbus interface instead, as that is faster and as a plus is supported by most players.
