### ISSUE TITLE
human readable date related numeric tags in tag patterns?

### ISSUE THREAD

**Issue by urielz** [quodlibet/quodlibet#2770]
Is it possible to make date related numeric tags (such as ~#lastplayed) show up in tag patterns in a human readable format? If not, then I think it would be nice to add that feature.

**Comment by lazka** [comment]
Which default time format you suggest?

**Comment by urielz** [comment]
I don't have a strong preference. I would go with the default time format used in QL. Being able to modify it via "DateColumn timestamp format" in Advanced Preferences plugin would help.

**Comment by vestingz** [comment]
I just wanted to open an issue with a similar suggestion. For the sake of flexibility it would be nice to have ISO 8601 time stamps, formattable according to your needs (e.g. YYYY-MM-DDThh:mm:ss or just YYYY-MM-DD).

**Comment by declension** [comment]
This was fixed by #2366
