### ISSUE TITLE
Cannot switch output (Mac)

### ISSUE THREAD

**Issue by kylebfredrickson** [quodlibet/quodlibet#2771]
Suppose I have a laptop connected to a monitor via HDMI. When I switch output from the mac internal speakers to the speakers on the monitor, the app fails to switch output. Also, if I disconnect the HDMI and then plug it back in the app will crash.

**Comment by madeindjs** [comment]
This problem still exists on QuodLibet 4.3.0 / Mac OS Catalina 10.15.4

**Comment by marians** [comment]
I can confirm this problem for macOS BIg Sur v11.1.

Also https://github.com/quodlibet/quodlibet/issues/3210 seems to be related or even a duplicate.

**Comment by chrisresnikrakuten** [comment]
I originally created #3210
A workaround I found out in the meantime: double-click a track to restart it, the new audio device will be used
as workaround, it's acceptable for me but then again, I see other software such as Zoom that automatically recognise new audio devices and start using them as default device (plug in usb-headsets or removing one). so I'm not sure what prevents quodLibet from doing so.
apart from, quite a nice player.

**Comment by waaykool** [comment]
@chrisresnikrakuten 

Thanks for this tip! I am having the same issue and have been quitting and restarting the app in order to change audio device. Double-click on a track is totally acceptable for me as well and works just fine.

**Comment by solstice0** [comment]
A stop button would be helpful for me too.
I use
`alsasink device=hw:3,0`
in my output pipeline, so gstreamer has exclusive rights to my DAC. This is how I want it. BUT sometimes I want to stop listening to music and watch a video or something in my browser, then resume listening to music. Right now I need to close quod libet to do so. If I'm understanding this plugin correctly, I could just hit stop and I could watch a video in my browser, then hit play in quod libet, and it will initialize gstreamer again. That would be nice to have.
