### ISSUE TITLE
Have ~#lastplayed and ~#playcount apply to whole album in Album List browsers

### ISSUE THREAD

**Issue by marcelpaulo** [quodlibet/quodlibet#2776]
I'm not sure if this is a reasonable think to propose, if it fits logically within QL's philosophy, but here it goes: when in a **Album List** browser, it might be useful that internal tags such as `~#lastplayed` and `~#playcount` apply to **whole** albums, and not to individual songs. Suppose, for instance, that I wanna show all Led Zeppelin albums I haven't listened to yet, and listen to each one of them: I would fire an Album List browser and filter the albums with this search expression:

`&(led zeppelin, #(playcount == 0))`

However, as `~#playcount` applies to individual songs and not to whole albums, as soon as I play the first song in an album, the album is removed from the Album List view. In other words, if **any** of the album songs has been played, `#(playcount == 0)` seems to evaluate true for the whole album. Of course this makes sense, since `~#playcount` is evaluated at song level. But then again, it might be useful if its meaning derived from the context: in an Album List browser, it might apply to the whole album, and in a `Search Library` browser, it would apply to individual songs.

**Comment by lazka** [comment]
currently "~#playcount" is a shortcut for "~#playcount:sum" for albums and "~#lastplayed" for "~#lastplayed:max"

**Comment by marcelpaulo** [comment]
Oh, I see, yes, now I can see it. I added column `~#playcount`, and I can see that it behaves as `~#playcount:sum` in filter expressions. But then again, it still applies to individual songs, and it's not possible to build a single filter expression to _show all whole albums which haven't been listened to completely_, since each individual album would require a different `#(playcount < <tracks>)` where `<tracks>` would be the total number of tracks of each album.

**Comment by lazka** [comment]
`#(playcount:min = 0)` should show albums which have one song not played.

**Comment by marcelpaulo** [comment]
Hey, excellent idea, it works ! I wouldn't have thought of using `min` like that. Thank you so much, @lazka !

**Comment by lazka** [comment]
Ok :) Here is some more info: https://quodlibet.readthedocs.io/en/latest/guide/tags/internal_tags.html#id2

**Comment by marcelpaulo** [comment]
I confess I had read that section of the manual, and although the title is indeed `Song Collections / Albums`, I didn't quite realize that it could be used the way you explained. Great !

**Comment by marcelpaulo** [comment]
This is really great: I saved query `#(playcount:min = 0)` as **not_played**, so that I can now browse albums by an artist still not played with `&(<artist>, @(saved:not_played))`. This is **really** useful !
