### ISSUE TITLE
"Save ratings and playcount" is enabled, but I don't see playcount being saved in MP3 files

### ISSUE THREAD

**Issue by marcelpaulo** [quodlibet/quodlibet#2777]
If `Save ratings and playcount` is enabled, I wonder when the playcount is saved ? I have just enabled that setting:

![screenshot_2018-02-17_13-16-09](https://user-images.githubusercontent.com/10074769/36342473-76405038-13e6-11e8-937d-cad778caa697.png)

played a song twice:

![image](https://user-images.githubusercontent.com/10074769/36342477-8a24b9f4-13e6-11e8-9e01-d7f31bccdff4.png)

but the playcount is not saved to a tag:

![image](https://user-images.githubusercontent.com/10074769/36342496-a1389020-13e6-11e8-99e0-88a0f428bc61.png)

I restarted QL but the playcount is still not saved. Just to make sure, I loaded the songs from that album in mp3diags, to look at the tags, but the playcount is really not saved:

![image](https://user-images.githubusercontent.com/10074769/36342506-dab437b4-13e6-11e8-8bc9-a80b76b8bfb3.png)

Is there anything else I should configure to have the playcounts saved in a tag in the files, perhaps I haven't done something I should ?

I've seen issue #1461 but it doesn't seem quite the same problem. I'm running QL **4.1 (development, 1fdf9160e)** on Xubuntu 17.10, and my collection is made up just of MP3 files.

While still on the theme, what is the purpose of the email address when saving ratings and playcounts ?

**Comment by marcelpaulo** [comment]
Have just discovered plugin `Update Tags in Files`, enabled it, played the previous song again, but still the playcount is not being saved in a tag in the mp3 file. Perhaps there's still something else I should be setting.

**Comment by urielz** [comment]
Haven't come across your issue. Could it be an issue with permissions?

> what is the purpose of the email address when saving ratings and playcounts ?

It allows multiple users to share the same files. It doesn't need to be an email address, just a unique identifier...

**Comment by marcelpaulo** [comment]
> Could it be an issue with permissions?

I've just double-checked it with:

```
paulo@monk:~/prj/script$ find /media/musica/cd -type d \! -perm 0775 -ls
paulo@monk:~/prj/script$ find /media/musica/cd -type f \! -perm 0664 -ls
paulo@monk:~/prj/script$ 
```

and my whole collection is consistent: all files have permissions 0664 and directories 0775.

So, just to be sure, are these _~/.config/quodlibet/config_ settings enough to make QL save the playcounts in the mp3 files ?

```
[editing]
alltags = true
save_email = marcelpaulo
save_to_songs = true
```

> It allows multiple users to share the same files. It doesn't need to be an email address, just a unique identifier...

Thanks for clarifying that !

**Comment by marcelpaulo** [comment]
I had disabled those settings when I noticed that the playcount wasn't being saved, but I enabled them again, and tested again: 

1. Played 2 songs, made sure that their playcount had really changed
1. Looked at their ID3 tags: no frames had been saved with the playcount
1. Assuming that perhaps QL wouldn't save the frames straight away, but only at certain intervals or before ending, I closed QL and looked at the ID3 tags again: still no frames had been saved with the playcount.

**Comment by marcelpaulo** [comment]
Just in case it might be useful, here's my _~/.config/quodlibet/config_ file:

```
[settings]
columns = ~#disc,~#track,title,artist,album,~#length,~#playcount
	
default_rating = 0.5
scan = /media/musica/cd
window_title_pattern = ~title~~people~album

[memory]
browser = AlbumList
browser_albumlist_maximized = 4
browser_albumlist_position = 685 25
browser_albumlist_size_ = 600 400
browser_audiofeeds_maximized = 0
browser_audiofeeds_position = 0 343
browser_audiofeeds_size_ = 790 400
browser_panedbrowser_maximized = 4
browser_panedbrowser_position = 566 25
browser_panedbrowser_size_ = 600 400
browser_playlistsbrowser_maximized = 4
browser_playlistsbrowser_position = 764 343
browser_playlistsbrowser_size_ = 600 400
browser_searchbar_maximized = 4
browser_searchbar_position = 566 25
browser_searchbar_size_ = 600 400
chooser_dir = /home/paulo/playlists
column_expands = title,0,artist,0,album,1
	
column_widths = title,256,artist,120,album,-1
	
open_browsers = 
plugin_prefs_maximized = 0
plugin_prefs_position = 374 30
plugin_prefs_size_ = 700 664
plugin_selection = include_saved
prefs_page = tagging
queue = False
queue_expanded = True
queue_position = 0.65
queue_stop_once_empty = true
quodlibet_information_maximized = 4
quodlibet_information_position = 483 183
quodlibet_information_size_ = 400 400
quodlibet_last_active_version = 4.1.-1
quodlibet_maximized = 4
quodlibet_position = 0 25
quodlibet_properties_maximized = 4
quodlibet_properties_pos = 0.1808199121522694
quodlibet_properties_position = 439 183
quodlibet_properties_size_ = 600 400
quodlibet_properties_size_single = 487 400
quodlibet_size_ = 600 480
repeat = False
repeat_mode = one_song
seek = 0
shuffle = False
shuffle_mode = Queue Only
sidebar_pos = 0.25
song = /media/musica/cd/Glenn Gould/Bach The Two and Three Part Inventions/10 Sinfonia Nº11 in G minor, BWV 797.mp3
sortby = 0~#track
	
volume = 1.0

[player]
gst_buffer = 3.0
replaygain = false
replaygain_mode = auto
time_remaining = true

[browsers]
album_covers = true
album_sort = 1
album_substrings = true
albumlist_pos = 0.48462664714494874
albums = (('bach: the two and three part inventions',), (), '980e187b-70a3-4d09-9bbe-267b8f4d6cfa')
audiofeeds_pos = 0.398734177215
collectionbrowser_pos = 0.39970717423133234
equal_pane_width = false
pane_wide_mode = false
panedbrowser_pane_widths = 
panedbrowser_pos = 0.4815950920245399
panes = composer
playlistsbrowser_pos = 0.41215226939970717
query_text = bach invention
search_limit = false

[library]
refresh_on_start = false

[__config__]
version = 0

[plugins]
active_plugins = include_saved
	Website Search
	ToggleMenuBar
	CustomCommands
animosd_monitor = 0
cover_engine_amazon = True
cover_engine_discogs = True
icon_tooltip = <album|<album~discnumber~part~tracknumber~title~version>|<artist~title~version>>
notify_show_notifications = all
quodlibet.fake.plugins.gajim_status_accounts = 
quodlibet.fake.plugins.gajim_status_pattern = <artist> - <title>
quodlibet.fake.plugins.gajim_status_paused = True
quodlibet.fake.plugins.gajim_status_statuses = online chat
quodlibet.fake.plugins.visualisations_executable = projectM-pulseaudio
randomalbum_use_weights = 0
scrobbler_service = Last.fm
squeezebox_debug = False
titlecase_allow_all_caps = True
titlecase_human_title_case = True

[rename]
move_art = true
remove_empty_dirs = true
windows = true

[editing]
alltags = true
save_email = marcelpaulo
save_to_songs = true

[albumart]
force_filename = false
search_filenames = *.pdf,*.jpg,*.txt
```

**Comment by marcelpaulo** [comment]
I've just uploaded [here](https://mega.nz/#!to8wHQoS!5kvLEgNgIzEnMk67TEDujgso8hYdSfGLrvwX9hJuIOM) the album with the songs I've just used for testing, in case it may be useful.

**Comment by davidSchlosser** [comment]
With QL 4.0.1 on OS X with new flac files, the playcount tag is only added after I select the flac files and click Plugins->Update Tags In Files.

**Comment by marcelpaulo** [comment]
Bingo, @davidSchlosser ! I've just tried it with mp3 files, and a **POPM** frame is added to the ID3 tag of each selected file, with this content:

`<id>:<rating>:<playcount>`

where _<id>_ is whatever is set in the `Email` preference field.

So… I got the impression that the tag update was automatic once the `Save rating and playcount` preference option was enabled, but it seems that it has to be manually done for each file one wants to have the ratings/playcount saved for. It doesn't feel very practical to use since one would have to remember to run the plugin for every song after listening. If doing it manually is the only way to do it, I guess I'm gonna give up on this feature.

Thanks for shedding light on the issue, @davidSchlosser !

**Comment by urielz** [comment]
> Save rating and playcount preference option was enabled, but it seems that it has to be manually done for each file one wants to have the ratings/playcount saved for.

Ah yes, that's indeed the way to use the plugin. I think the idea behind the plugin was to have a way to migrate music without loosing those tags. Anyway, I agree with you, we should implement a way to this more automatically. There's a discussion about this here: https://github.com/quodlibet/quodlibet/issues/1852

**Comment by marcelpaulo** [comment]
Thanks for the explanation, @urielz ! Oh, I did comb open and closed issues for anything related to this theme but overlooked #1852, please forgive me. I suppose we should close this issue, since it's an evident duplicate, and have the discussion continue to be tracked in #1852.

**Comment by urielz** [comment]
No worries. Hard to keep up with all the threads! Thanks.
