### ISSUE TITLE
Import Ratings

### ISSUE THREAD

**Issue by bikermikem** [quodlibet/quodlibet#2779]
Quod Libet  4.0.2

Is it possible to import song ratings from iTunes (12.6.3.6) on a Mac running High Sierra 10.13.3?

**Comment by lazka** [comment]
No

**Comment by bikermikem** [comment]
Bugger!

Next question; considering I'm a non-programer, what is the structure of the "songs" file?

**Comment by bikermikem** [comment]
Seeing as there was no response to my last question, I've moved on to "JRiver Media Center 23" which will import ratings from iTunes.  Shame, as I liked Quod Libet otherwise and was willing to make a £25-£30 donation if it could have imported ratings.  I wasn't about to sit down and do 3700+ tracks manually.  While JRiver is twice that, it was worth the time savings.
