### ISSUE TITLE
Feature Request: Ex-Falso social media tag

### ISSUE THREAD

**Issue by Thomas-O** [quodlibet/quodlibet#2782]
Could Ex-Falso have a new tag field for social media URI?

I'm planning a new art project and it'd be really helpful. I could bodge the metadata by using another field as a home for the links but I have the feeling that could just invite trouble further on down the line.

Thanks for considering the request.

Thomas

**Comment by declension** [comment]
I'm not really sure what the request is here. For most formats, you can add tags of any (ASCII-ish) name, so if you want to add `facebook-url` or, for example, the Soundcloud browser populates internal(ish) tags of `soundcloud_user_id` then there's nothing to stop you. 

The `website` tag does get some special treatment in a few places that said.

**Comment by Thomas-O** [comment]
I need to tag each audio file with both a website link and a separate social media link. So that I can instruct my website to look for and open the website link, and the mobile app to look for and open the social media link. It'd make everything easier if there was a separate field for a social media link.

**Comment by declension** [comment]
Sure - you can add any tag you want (in most formats)
