### ISSUE TITLE
QL's interface freezes with TLEN 0:00 files and Waveform Seekbar enabled

### ISSUE THREAD

**Issue by spxxxk** [quodlibet/quodlibet#2783]
`--debug` reports

> D: 58.503: WaveformSeekBar._create_waveform: Computing data for each 0.000 seconds

You can close if it will be worked around by https://github.com/quodlibet/quodlibet/commit/7bb1213df698bdbe662cde74a2e1ba89b52595d9.

QL version: `4.0.99+9590~1fdf9160e-0~ppa0~xenial`

**Comment by lazka** [comment]
My guess would be #2714

**Comment by lazka** [comment]
Likely de49a27d92ea
