### ISSUE TITLE
Download Album Art plugin - misplaced category

### ISSUE THREAD

**Issue by urielz** [quodlibet/quodlibet#2796]
currently the plugin "Download Album Art" is under the **Songs** category. I believe it should be placed under the **Covers** category.

Specifically the file _albumart.py_ currently located in _/ext/songsmenu_ should be placed under _/ext/covers_

**Comment by declension** [comment]
No - those are for cover source plugins that plug into the dynamic cover downloading system, but have no UI.

Coincidentally though I've been taking another look at #1279 (plus some related changes) to unify these systems as it's a bit confusing, and the downloader is missing some good album art sources.

**Comment by urielz** [comment]
Thanks for the clarification. I actually didn't check those plugins, hence my post! 

And I agree it is a bit confusing, at the very least a short description (what you just told me) might help to make it clear what those plugins are for. I'll close this now.

**Comment by declension** [comment]
Thanks @urielz. I'll add some docs around that when I next change that part of the codebase
