### ISSUE TITLE
Bluetooth speaker connection requires app restart

### ISSUE THREAD

**Issue by othalan** [quodlibet/quodlibet#2798]
I frequently use a bluetooth speaker.  When initially connecting the speaker to my computer, QuodLibet does not detect the speaker and continues to play songs through the computer speakers instead of through the newly connected bluetooth speaker.  In other applications using gstreamer (e.g. Clementine), this can be fixed by stopping and restarting playback.  However, there is no "stop" button in QuodLibet, only a play/pause button.  Sometimes (but not always) QuodLibet will switch to the bluetooth speaker when changing to a new song.

**What did you try to do?**

Connect a bluetooth speaker.

**What did you expect to happen?**

Music to be played through the newly connected bluetooth speaker.

**What did happen instead?**

Music continues to play through the computer speakers.

**Which version of Quod Libet?**

4.0.2

**Which operating system including version (Ubuntu 14.04, Win7, Debian sid, ...)?**

macOS High Sierra

**Comment by lazka** [comment]
Likely the same as #2771

**Comment by lazka** [comment]
Possible workaround, if you go go to the end of the play list without repeat enabled and hit next it should switch to "Not playing". In this state all audio related connections should be gone.
