### ISSUE TITLE
Provide support to add/edit album (cover) art using exfalso 

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#28]
Original [issue 28](https://code.google.com/p/quodlibet/issues/detail?id=28) created by keerthi.linux on 2008-10-06T06:00:25.000Z:

Please describe the problem thoroughly and accurately. If possible paste
the contents of the ~/.quodlibet Dump or MiniDump file associated with the
problem.

**Comment by declension** [comment]
I think this is all covered now. Can we close this ticket?

**Comment by lazka** [comment]
I think the original submitter wanted something like a new tab in ex falso. Here is what it looks like in easytag:

![screenshot from 2017-01-23 11-21-10](https://cloud.githubusercontent.com/assets/991986/22200144/2e9e7bda-e15e-11e6-9a07-764fb46a499b.png)

**Comment by Zegnat** [comment]
> I think this is all covered now. Can we close this ticket?

I just found this issue, looking for a way to remove embedded art from an MP3 file, and it does not look like QuodLibet gives me any such an option yet.

So I don’t think everything is covered yet.

**Comment by urielz** [comment]
@Zegnat You can use the "Edit Embedded Images" plugin to remove embedded art. It's not enabled by default.

**Comment by Zegnat** [comment]
@urielz, thanks for pointing that out. Completely missed it as I expected it as part of tagging.

**Comment by CreamyCookie** [comment]
The remaining issue was moved to #3193.
