### ISSUE TITLE
move library to a different location - metadata is lost

### ISSUE THREAD

**Issue by wifon** [quodlibet/quodlibet#2806]
I don't see ratings and playcounts in tags, so I assume they're stored in sort of quodlibet's database. As my library grows, I'm considering to move it from /home to a separate HDD. I'd save current directories structures, but of course path will change. What I'm afraid of is, will my playcounts and ratings stay as they are now? Or will I lose them?
Maybe quodlibet would be able to store playcounts/ratings/date added/last played in file's meta tags?

I've thought of a solution to make a symlink from ~/Music to let's say /media/diskwithmusic, but that's just a workorund and I'm not sure if it will work

**Comment by declension** [comment]
Yes these will be lost this way. And IMO symlinks (with QL) cause more confusion than they solve.

However ratings and playcounts _can_ be saved in the files though. It's under _Preferences_ -> Library -> _Tags_.

**Comment by wifon** [comment]
Why don't I see playcounts in tags then? Image: https://imgur.com/a/EinL2
