### ISSUE TITLE
Track order with a disc subtitle

### ISSUE THREAD

**Issue by gravelld** [quodlibet/quodlibet#2808]
Quod Libet appears to ignore disc subtitles when deciding track order (not sure what happens with discnumber - maybe this is the workaround).

Here's an example:

![screenshot_2018-03-15_13-18-52](https://user-images.githubusercontent.com/873704/37465597-78211bc2-2853-11e8-982d-1a2fd907acb9.png)

Under the _Album name / Disc subtitle_ column you can see the subtitles. But the track order appears to follow the track numbers; the discs are not "grouped".

You can also see sorting by the _Album name / Disc subtitle_ column appears to only sort by the album name, so this is not a workaround.

Something I'm missing? Is a discnumber required as well?

**Comment by lazka** [comment]
Yeah, we reduce that to "album" only atm for sorting: https://github.com/quodlibet/quodlibet/blob/9eb264ff3e3352c9ce9c0c9bc89006e85008f4d4/quodlibet/quodlibet/qltk/songlist.py#L152

Adding discnumber should help.

**Comment by CreamyCookie** [comment]
[MusicBrainz Picard](https://picard.musicbrainz.org/) is pretty nice for semi-automatically adding tags like disc number etc.

Closing this one as it is intended AFAICS.
