### ISSUE TITLE
Ui freeze when waveform activated

### ISSUE THREAD

**Issue by dastious** [quodlibet/quodlibet#2811]
When i click on a new track or click on next track if the waveform plugin is activated there is a chance (total random) that the ui freeze. It's like 5/10 chance to freeze, very annoying.

archlinux latest quodlibet (tried with quodlibet-git too)

There is no error :
D: 18.991: WaveformSeekBar._create_waveform: Computing data for each 0.022 seconds
D: 19.002: SongFileLibrary._changed(<libraries.SongFileLibrary object at 0x7f57b0182e58 (quodlibet+library+libraries+SongFileLibrary at 0x560df09a0fa0)>): Changing 2 items.

**Comment by lazka** [comment]
Thanks. See #2714
