### ISSUE TITLE
Tracks sorted by alphanumeric track order

### ISSUE THREAD

**Issue by Michael-Karman** [quodlibet/quodlibet#2813]
If I drag and drop 12 tracks, quodlibet deranges them like this:

1, 10, 11, 12, 2, 3, 4, 5, 6, 7, 8, 9.

This is not useful. And what if I have a CD with 99 tracks (I do) or even 37 tracks?

I want to be able to grab a bunch of tracks and dump them in without having their order rearranged for me. 1, 10, 11, 12 is just silly, no? (Especially when 9, 10, and 11 are three movements of one piece.)

**Comment by declension** [comment]
Hi. A few questions:
 1. What browser is this on - Playlists perhaps?
 2. What is the _source_ of the DnD: another app, files, another QL browser window, or something else (e.g. the QL queue)?
 3. What QL version and what O.S. is this on?
 4. What's your playlist sort order (e.g. Title / Artist / length)?

**Comment by Michael-Karman** [comment]
1. I'm not using Nightingale with a browser, just as a standalone player.

2. I'm grabbing files from folders on an external hard drive. The files are
mostly ripped cds. I travel constantly, so cannot carry a lot of stuff
around.

3. The O.S. is El Capitan 10.11.6. (I was using Cog before, same O.S. Never
any numbering glitches with it, though it would not play tracks that were
less than around 6 seconds--fortunately, I have very few of these. A couple
of Yoshihide discs with 99 tracks or so. It developed other problems,
suddenly, so I had to look around for another player. At first it looked
like Nightingale was it....)

4. The files are simply the tracks from the cds, numbered from one to
whatever. (The numbers are part of the track name.) And it's only when the
whatever runs past nine tracks that there's a problem. And since I have
many operas, I have many folders with 30 files or more. Could get really
old really fast dragging files into Nightingale one at a time.)

Thanks!

**Comment by declension** [comment]
> 1. I'm not using Nightingale with a browser, just as a standalone player.

Erm, perhaps you're on the wrong github project then?

**Comment by Michael-Karman** [comment]
I wondered that, too. But that was where the Nightingale site sent me....

**Comment by declension** [comment]
Perhaps here? https://github.com/nightingale-media-player

**Comment by Michael-Karman** [comment]
OK, I'll try that. Thank you for your time, Nick. Vastly appreciated!!

**Comment by Michael-Karman** [comment]
Haha, I meant Quod Libet, not Nightingale. Nightingale was the player I
tried right before I tried Quod Libet.

This was where *Quod Libet* sent me.

So now what?

Quod Libet doesn't list tracks in order, instead it reorders them according
to the first digit of a number. 1, then 10, then 11 and so forth before it
gets to 2. If there are more than 19 tracks, then 2 will be followed by 20
and 21 and so forth before QL gets to 3.

(I hope this is OK to email you again after the case was closed. I like
everything else about Quod Libet.)

**Comment by declension** [comment]
@Michael-Karman Can you provide screenshots? 

I've understood most of your numbered answers above but:
1. It's not clear which browser you're using (_Browse_ menu) but perhaps it's any
2. I assume you're opening them in Finder and dragging them?

On re-thinking this seems like you're expecting _numeric_ sorting on a _string_ field (`title` / `~filename`). You won't get what you want this way; you should either:
1. make sure the files have the `tracknumber` field set, and sort by this. QL has some good features for adding these if your files don't have them (Right click files -> _Edit Tags_ -> Track Numbers tab (last one)).  See [the Editing Tags docs](https://quodlibet.readthedocs.io/en/latest/guide/editing_tags.html), *and/or*
2. Rename your files using a zero-prefix, e.g. `01 - Adagio.flac`, `02 - Allegro ma non troppo.flac` etc. This ensures that traditional _lexicographic_ (string / dictionary-style) sorting will work with numbers. See ancient but related [Mac example here](http://www.naturalordersort.org/).

Additionally, I recommend using the Musicbrainz plugin to get high-quality tag data on your albums, including track numbers (helps with album art too). Everything works much better after doing this.

Hope this helps

**Comment by Michael-Karman** [comment]
I use Google Chrome.

I am dragging them from Finder.

As for that whole tracknumber field thing, all I know is that Cog never had
this problem. It always just took whatever I gave it and put them in the
same order. Which is why I'm skeptical of looking outside Quod Libet for a
solution. That is, if another player always put the tracks in their
numerical order, why can't any other player do the same? (As a matter of
fact, I just recalled that when I was auditioning Nightingale, I did so by
loading Rachmaninoff's Variations on a Theme of Paganini into the
machine--it's a piece with one track for each variation, played without
pause, so you can quickly test for gapless playing that way. And
Nightingale put everything in the correct order as well.)

So, you see, I HAVE gotten what I wanted without any fussing around with
any renaming or adding field sets. Gotten what I wanted in terms of track
order, that is. Nightingale and Cog both had other problems, which is why
we're having this conversation. For which, again, thank you, Nick!!

**Comment by declension** [comment]
No problems. Sorting is complex at times and does vary a lot between players; hard to say what Nightingale is using by default. It's also a bit hard to see what's going on without the files themselves or screenshots, but here are some general points:
 * QL offers quite a few sorting options including custom sort fields - there's [a brief intro](https://quodlibet.readthedocs.io/en/latest/guide/browse/overview.html#the-song-list) here. The first thing to try is to click the `Track` header, as in this Album browser screenshot: ![Album Browser screenshot](https://quodlibet.readthedocs.io/en/latest/_images/album.png)

Note how the track (first) column has the arrow to indicate its sort order.  Clicking it again will reverse it. As per the link above, what it's _actually_ sorting by is slightly more complex. If you don't _have_ that column, it can be added by customising the columns (right click that header).

**Comment by Michael-Karman** [comment]
Going by what you just said,* I imported a folder from my collection into
QL, instead of using copy and paste.

Bingo. The order is correct. So far so good.

*(Not following what you said, so much, but noticing in the QL instructions
that it expects to go find what you want to play. So I let it, instead of
finding it myself and pasting it into QL)

But this only works if there are only files in the folder. For most of the
operas, however, there are several folders inside the top folder, one for
each act. If I offer it the upper level folder, it goes into each subfolder
and screws the order up like before.

So, then it occurred to me, what if I enter 1-9, then 10-whatever? Or, in
the case of one act per folder situations, 1-9, 10-whatever, 1-9,
10-whatever.... For operas with several acts, this is only slightly more
effort than just cnp the contents of each folder. It is, in fact, dead
easy. And it works flawlessly.

So, even though the solution I now use is one I came up with, it is a
solution that I don't think I would have come up with had you not nudged me
toward it. So the credit still goes to you. (I'm sure you're relieved!!)

Well, I have a player that does what I want it too, even if it takes a tiny
bit of extra effort. A few iterations, and I won't even notice the effort.

Massive thanks for all your help.

[Edit: Suspicious of what I first found, I did a cnp with the 20+ tracks of
Rachmaninoff's variations. Hah! it was still perfect--the tracks of that
album are already compatible with what QL expects from a well-behaved
track. But rather than go into each album and correct things by hand, it is
still perfectly fine for me to cnp 1-9 and then cnp the rest. QL accepts
that very sweetly, no complaints, no reshuffling.]

**Comment by declension** [comment]
Great, glad you got something working. I'm sure like lots of us you'll find more and more clever ways to organise the music the way _you_ want.

My final tip for classical: definitely `discnumber` and `grouping` tags can help with these kind of things (and `composer`, `performer`, `conductor` tags, but you probably knew all that. My point is they're well supported in QL generally)

If you're happy I'll close this issue

**Comment by Michael-Karman** [comment]
Yes. You may close it. Thanks, again, for all your help. :-)
