### ISSUE TITLE
"Clear Queue" not clearing the queue anymore

### ISSUE THREAD

**Issue by marcelpaulo** [quodlibet/quodlibet#2816]
I'm running master (d8e001e3e1fcb7b0977d1dfe457719294b03c54f), and have just noticed that `Clear Queue` is not clearing the queue anymore:

![screenshot_2018-03-26_12-54-44](https://user-images.githubusercontent.com/10074769/37917721-8bf9273e-30f5-11e8-9890-4310520d0140.png)

I can't remember when I last cleared the queue successfully, so I'm not sure from which commit it stopped working.

**Comment by lazka** [comment]
```
336eb350acbed697b9900181d0e09b05319d4074 is the first bad commit
commit 336eb350acbed697b9900181d0e09b05319d4074
Author: Fredrik Strupe <fredrik@strupe.net>
Date:   Sun Mar 4 17:18:07 2018 +0100

    Queue stop once empty: do check at end of song instead
```

@frestr

**Comment by lazka** [comment]
@frestr thanks!

**Comment by frestr** [comment]
My bad, thanks for reporting. It should be fixed now.
