### ISSUE TITLE
Consider pipenv for project dependencies and environment

### ISSUE THREAD

**Issue by declension** [quodlibet/quodlibet#2818]
[Pipenv](https://docs.pipenv.org/) is a great tool sitting on top of Pip, Virtualenv.. and is py.test compatible. Now that we're PY3 only, it perhaps makes more sense than Tox (#2317).

### Pros
 * Isolated (from OS installs), easily set up Python dependencies
 * Lock dependencies at known versions (and uses hashing) 
 * Thus - makes our Docker / CI steps simpler, and makes these builds more reproducible locally
 * Easy to switch Python versions (and: to mandate them)
 * Some integration of linting tools etc

### Cons
 * More tooling (though after converting several small projects - it's pretty good)
 * Still doesn't deal with system dependencies e.g. Gobject et
 * A few unknowns (for me) about bigger projects with more committers.

**Comment by lazka** [comment]
Not sure about docker -  we want to test against system dependencies which users are actually using.

**Comment by lazka** [comment]
+1 for adding a Pipfile

**Comment by declension** [comment]
> Not sure about docker - we want to test against system dependencies which users are actually using.

Good point, I guess we should leave it (in fact, use it as an "insurance policy" really)
