### ISSUE TITLE
Translations not loaded on Nix

### ISSUE THREAD

**Issue by jtojnar** [quodlibet/quodlibet#2819]
Quod Libet does not pass any `localedir` to `gettext.bindtextdomain` causing an issue on Nix, which uses non-standard localedir (for example, `/nix/store/pgb6i21r6zrdb9phff511jziiml2ns68-quodlibet-full-4.0.2/share/locale`).

As [Python documentation](/nix/store/pgb6i21r6zrdb9phff511jziiml2ns68-quodlibet-full-4.0.2/lib/python3.6/site-packages/quodlibet/ext/events) notes, a path should be always passed to prevent this from occurring:

> The default locale directory is system dependent; for example, on RedHat Linux it is /usr/share/locale, but on Solaris it is /usr/lib/locale. The gettext module does not try to support these system dependent defaults; instead its default is sys.prefix/share/locale. For this reason, it is always best to call bindtextdomain() with an explicit absolute path at the start of your application.

**Comment by lazka** [comment]
Thanks. Do you know how to figure out right path?

**Comment by jtojnar** [comment]
I think the only way is getting the path from package manager during build. For example, gnome-music configures the file, see https://github.com/GNOME/gnome-music/blob/3.28.0/meson.build#L76 and  https://github.com/GNOME/gnome-music/blob/3.28.0/gnome-music.in#L54

**Comment by jtojnar** [comment]
That should work for us, even if it is not universal and the list is pretty large.

**Comment by lazka** [comment]
Reopening due to https://github.com/quodlibet/quodlibet/commit/fad00b967fca2bb8810b872e8d1e1eb72a0e321a#r28965737

**Comment by lazka** [comment]
I assume this is fixed by 8bf77e90703e54. If not please reopen!
