### ISSUE TITLE
Queries no longer saved

### ISSUE THREAD

**Issue by spxxxk** [quodlibet/quodlibet#2821]
QL doesn't seem to save my queries anymore, for some time.
There were very old queries in `~/.config/quodlibet/lists/queries`
-- I deleted it
-- Did some queries
-> `~/.config/quodlibet/lists/queries` is created but stays empty.

-- Edit `queries` file by hand
 -> Edit appears in QL list of queries, after restart

`~/.config/quodlibet/lists/queries.saved` is working as expected.
Permissions are the same for `queries` and `queries.saved`.

QL version: `4.0.99+9590~1fdf9160e-0~ppa0~xenial`

**Comment by frestr** [comment]
I can't seem to reproduce this, even with the same QL version on xenial.

Is the problem still present if you start QL with a different user dir? (`QUODLIBET_USERDIR=foo quodlibet`)

**Comment by frestr** [comment]
That makes sense. It's definitely a bug, since queries should still be saved on enter.
