### ISSUE TITLE
Process title set to q instead of quodlibet

### ISSUE THREAD

**Issue by marcelpaulo** [quodlibet/quodlibet#2826]
This had been reported in #736 and fixed in revision af894c690b184901ac3b4b87faaa9ddd21ab1c38, but somehow it seems to have been dropped along the way.

Getting quodlibet's PID:

```
+paulo@monk:~/tmp$ ps -ef | grep quodlibet
paulo    19093  2376  4 19:22 ?        00:00:51 python3 /home/paulo/.local/bin/quodlibet
```

Checking its process title and its command line:

```
+paulo@monk:~/tmp$ ps -o pid,comm,args 19093
  PID COMMAND         COMMAND
19093 q               python3 /home/paulo/.local/bin/quodlibet
```

As you can see, its process title is set to **q**. I bumped into this when I tried to `pgrep` quodlibet in a script:

```
+paulo@monk:~/tmp$ pgrep quodlibet
+paulo@monk:~/tmp$ 
```

pgrep works on the process titles, and doesn't find quodlibet because its process title is set to **q**.

I'm running quodlibet 07f603af9 on Xubuntu 17.10.

**Comment by declension** [comment]
Confirmed on 07f603af939abbb5afb271074d74c2313e0e2c4e (and 294 commits before that, FWIW).

Thanks for the report.

**Comment by marcelpaulo** [comment]
Thanks, @lazka ! I've just tested it, it's fixed:

```
:paulo:~/src/quodlibet$ ps -ef | grep quodlibet
paulo    13404  3733  6 06:35 ?        00:00:27 python3 /home/paulo/.local/bin/quodlibet
```

```
:paulo:~/src/quodlibet$ ps -o pid,comm,args 13404
  PID COMMAND         COMMAND
13404 quodlibet       python3 /home/paulo/.local/bin/quodlibet
```
