### ISSUE TITLE
UPnP MediaServer plugin appears completely undocumented

### ISSUE THREAD

**Issue by deutrino** [quodlibet/quodlibet#2829]
I would like to use the UPnP / DLNA / etc media server plugin and there appears to be no documentation for it anywhere, including in the source. Enabling it and running 'rygel' before or after 'quodlibet' does not appear to do anything.

**Comment by deutrino** [comment]
For anybody who surfs in from search, ensure this is in your `~/.config/rygel.conf`

    [External]
    enabled=true

    [org.gnome.UPnP.MediaServer2.QuodLibet]
    enabled=true

This exports albums, and I've verified that it works on a Kodi installation on my LAN.

Would be super easy to add to the docs! :)

**Comment by declension** [comment]
Thanks

> Would be super easy to add to the docs! :)

If you're able, please submit a PR to update the docs.

If not, perhaps we can add something short to the description for that plugin (there is a lack of docs around _all_ plugins, but so many that it's too much to take on now probably)

**Comment by deutrino** [comment]
Thanks, I will try to do this sometime fairly soon :)
