### ISSUE TITLE
Show in file browser

### ISSUE THREAD

**Issue by nclm** [quodlibet/quodlibet#2835]
It would be interesting and useful to have a feature to reveal the file location in your system’s file navigator (Nautilus, Finder, Explorer, etc.).

The option could be located in `Information`, section `File`, line `Path`, either as a simple link on the path or as an extra icon. Additionally, a menu option “Show file” could be added in the right-click contextual menu or in the `Song` top menu.

Clicking it would open the file browser in the folder container the song, ideally with the file pre-highlighted (depending of the feasibility with the OS’ API).

**Comment by Meriipu** [comment]
There is a plugin for this though I think people have mentioned that it could/should be integrated in the main application interface somehow

**Comment by KoO-303** [comment]
I second this would be helpful I have all the plugins working that come with Quodlibet not in the list.
I their are 3rd party plugins any links ?

**Comment by lazka** [comment]
> I second this would be helpful I have all the plugins working that come with Quodlibet not in the list.
> I their are 3rd party plugins any links ?

All plugins are included by default.

**Comment by KoO-303** [comment]
@lazka 
> All plugins are included by default.
Thanks

**Comment by declension** [comment]
Yes, every time we get one of these it reminds me that I strongly feel "show in file browser" should be moved to core (even more than, say, edit lyrics which already is). Lots of other rich UIs (e.g. Shotwell, PyCharm etc, Clementine) do this, choosing the most appropriate launcher per system...

**Comment by lazka** [comment]
the code already is: https://github.com/quodlibet/quodlibet/blob/7d6ffdf54df475e3ea67b36deb4109612361734d/quodlibet/quodlibet/qltk/showfiles.py#L26

**Comment by declension** [comment]
@lazka thanks, that explains the slight getting déjà vu :laughing: 

Perhaps we can just move the wrapper out from plugins to `SongsMenu` then...

**Comment by lazka** [comment]
> Perhaps we can just move the wrapper out from plugins to SongsMenu then...

:+1:
