### ISSUE TITLE
Playlists of network folders appear empty

### ISSUE THREAD

**Issue by Moilleadoir** [quodlibet/quodlibet#2841]
I’m guessing this is connected with [1733](https://github.com/quodlibet/quodlibet/issues/1733) maybe? I added some albums on a mounted NAS drive to a playlist (in Solus) and, although I could be hallucinating, I was sure it worked. I copied the same playlist to Ubuntu, but it shows as empty in Quod Libet. The NAS is mounted in exactly the same way at the same mount point. It hasn’t had a chance to actually be disconnected in Ubuntu, since it was mounted before I copied over the playlist file.

I notice another playlist I’d created a while back (in the File System Browser) from the same NAS is not only empty but now actually _is_ empty. Does QL rewrite playlist files if it can’t find the files? That seems a little OTT if so.

I’ve just created a test playlist from the same location. It worked after I created it, but appears as empty (not actually empty) after restarting QL.

Exporting these playlists creates an empty .m3u playlist.

Quod Libet 4.0.2
Ubuntu 16.04.4

**Comment by CreamyCookie** [comment]
Yeah this is #708 (or #1733). Closing this as a duplicate.

**Comment by CreamyCookie** [comment]
Yeah this is #708 (or #1733). Closing this as a duplicate.

Thanks for the report!
