### ISSUE TITLE
App menu doesn't work on Wayland

### ISSUE THREAD

**Issue by fkrull** [quodlibet/quodlibet#2846]
The application menu (the one you get when you click on the window title in gnome-shell) doesn't work on Wayland:

![app-menu-wayland](https://user-images.githubusercontent.com/2378306/40128882-210c89e6-5933-11e8-9a83-0af86885b9e6.png)

This was with QL 4.0.2 on Ubuntu 18.04 with Wayland.

[The code piece](https://github.com/quodlibet/quodlibet/blob/a0da55222397d7b759451d9660a74347fe3203b1/quodlibet/quodlibet/qltk/quodlibetwindow.py#L478) that registers the app menu only works on X11. The "proper" way to fix this would be to use GtkApplication and its [set_app_menu method](https://developer.gnome.org/gtk3/stable/GtkApplication.html#gtk-application-set-app-menu), but I suspect that requires some in-depth changes.

(This one isn't a Flatpak issue, I checked.)

**Comment by lazka** [comment]
Yeah, thanks.

**Comment by Valeryan24** [comment]
Hi, is it a similar problem (I don't want to create a duplicate issue) that makes Quod Libet icon not visible in Ubuntu dock with Wayland session on 18.04 / 18.10 (bottom of the screenshot) ?
https://framapic.org/U5PfilFgyGtS/0eNA4cqulf1Y.png
Thanks for your great work !

**Comment by lazka** [comment]
@Valeryan24 how did you install QL?

**Comment by Valeryan24** [comment]
First with the default Ubuntu package (I use development version 18.10 on Wayland), then with your unstable ppa: both give the same result for dock and top bar icon.

**Comment by lazka** [comment]
> First with the default Ubuntu package (I use development version 18.10 on Wayland), then with your unstable ppa: both give the same result for dock and top bar icon.

Thanks, that's a bug then.  Might be that us not using GtkApplication is the same cause, but please open a new issue for this. Thanks!

**Comment by lazka** [comment]
Gnome is moving away from app menus now, the we can probably just get rid of it altogether.

**Comment by fkrull** [comment]
Wait, they are? Bloody hell, can't they make up their minds.

**Comment by lazka** [comment]
https://wiki.gnome.org/Design/Whiteboards/AppMenuMigration

I wont miss them at least.

**Comment by lazka** [comment]
It's a bit more official now: https://mail.gnome.org/archives/desktop-devel-list/2018-June/msg00021.html

**Comment by lazka** [comment]
I had to revert because tests started to fail without a clear error message.
