### ISSUE TITLE
MPRIS/Flatpak: cover not displayed for file with embedded cover

### ISSUE THREAD

**Issue by fkrull** [quodlibet/quodlibet#2847]
When:

* running from a Flatpak
* using the MPRIS plugin
* listening to a song with (only?) an embedded cover

...then the song's cover is not displayed in the MPRIS menu.

It seems that when getting an embedded cover, it's extracted to a file in /tmp; since /tmp is private to the sandbox and never shared with the host, the panel-or-whatever can't see the file.

**Comment by lazka** [comment]
hmmmm, any ideas on what we could do?

**Comment by fkrull** [comment]
Well, the paths in `~/.var/app/<app id>` should always be accessible to both the host and the application, and also have the same path inside the sandbox and outside. I was thinking the MPRIS plugin could copy the cover it receives into $XDG_CACHE_HOME (probably also using the tempfile module so it gets cleaned up) and hand out the path to this file instead.

**Comment by lazka** [comment]
http://docs.flatpak.org/en/latest/sandbox-permissions.html recommends something similar (search for TMPDIR)

**Comment by lazka** [comment]
I'll look into it.
