### ISSUE TITLE
Process title set to io.github.quodl

### ISSUE THREAD

**Issue by marcelpaulo** [quodlibet/quodlibet#2849]
quodlibet process title is being set to **io.github.quodl**, as of 9bfca8d00e9fcfe6ab74600ccbb936d6b7d0788a on Xubuntu 18.04:

```
:paulo:~/src/quodlibet$ ps -o pid,comm,args 24200
  PID COMMAND         COMMAND
24200 io.github.quodl python3 /home/paulo/.local/bin/quodlibet
```

It had been fixed in 7e1c27eec4acf74efad9bed4a2cfaa60fc547863 (issue #2826). I can see that 8dfa9a78a6f8aa7afcdd5c654b548ecfac95c781 changed the D-Bus name to _io.github.quodlibet.QuodLibet_, but I couldn't see anything directly related to process title in the commit. That was the only commit I found that referenced _io.github.quodlibet.QuodLibet_.

**Comment by lazka** [comment]
thanks
