### ISSUE TITLE
Failing quality tests with pycodestyle

### ISSUE THREAD

**Issue by frestr** [quodlibet/quodlibet#2855]
The newest release of pycodestyle (2.4.0) introduced some new checks that causes `test_pep8.py` to fail, given that the older pep8 version is not installed (since pycodestyle is used as a fallback, not the other way around).

Except for one instance of `E501 line too long`, the warnings are mainly `W504 line break after binary operator` and `W605 invalid escape sequence`.

Because we already ignore `W503 line break before binary operator`, my suggestion is to just ignore W504 too. (Wouldn't hurt to fix it though.)

W605 warnings on the other hand should be fixed, since invalid escape sequences are deprecated in Python 3.6 and will eventually turn to SyntaxErrors ([source](https://docs.python.org/3/whatsnew/3.6.html#deprecated-python-behavior)). They can be fixed by adding a second backslash or making the string a raw string literal (prepend r).

We might also consider using pycodestyle as the default and pep8 as fallback, since the pep8 package/module will not be updated anymore ([source](https://pypi.org/project/pep8/#changelog)) .

**Comment by lazka** [comment]
+1 on all three suggestions
