### ISSUE TITLE
Permanent Queue

### ISSUE THREAD

**Issue by Treferwynd** [quodlibet/quodlibet#2856]
I'd like the queue to behave like in most other media players, so that it doesn't consume songs and you can repeat/shuffle/etc on it. Like an actual playlist with a reserved place in the UI.  I know this is specifically against the idea of queue in QL, so feel free to just tell me "NO".

Reasons:
* search the library without affecting what I'm listening to
* listen to different songs from different albums/artists/etc (on loop/shuffle/whatever) without creating a playlist

This could probably be done with a plugin, but the queue's behaviour seems hardcoded, which is a bummer.

It'd be cool to change the queue's behaviour via settings or plugins. It really is the only thing that keeps me from having the perfect music player!

**Comment by frestr** [comment]
This has been a wanted feature for some time now. See #1890 for a discussion.

**Comment by Treferwynd** [comment]
I'm not sure it's the same thing, but if one could override the queue behaviour it'd be trivial to implement #1890

**Comment by frestr** [comment]
It's unfortunately not that simple because of the way the queue is implemented and how it interacts with the other components in the UI.

I've begun working on a possible solution though, so we may see some movement on this.

**Comment by Treferwynd** [comment]
I've tinkered a bit with the code, and while admittingly getting a bit lost, I thought a nice solution could be a `PlayOrder: Queue` plugin. This way with a couple of plugins  (one for the queue and one for the "normal" playing) one could make QL behave exactly as they want.

**Comment by frestr** [comment]
Do you mean being able to use the play order plugins on the queue while still keeping the queue's play order separate from the main song list? That's a good suggestion, but is perhaps a separate issue from having a permanent queue (which should be possible now with #2865).

Correct me if I'm misunderstanding something though.

**Comment by Treferwynd** [comment]
Exactly. To be more specific: define methods like `next`, `next_implicit`, `set`, `set_implicit`, etc. just for the queue.
So for example to simulate how things work right now you'd have the main song list's `next` which checks if the queue is empty, end if not it calls `next` on the queue. Or maybe use an event plugin? So when a song ends `plugin_on_song_ended` calls `next` on the queue if it's not empty, and `next` on the main song list otherwise.

(In the next days I'll give a try to your PR!)

**Comment by frestr** [comment]
@Treferwynd did you try the PR / Keep songs feature? I think it would be clearer to have a separate issue about the play order (somewhat related: #1411), so feel free to make that. I'll close this for now.

**Comment by Treferwynd** [comment]
Sorry! I tried it now and it seems pretty great!
I just have one question: if I wanted loop the queue what could I do? Can I do it with a plugin? If I manage to do this than I see no need for the play order stuff

**Comment by frestr** [comment]
Not possible at the moment, as this would be done with the "Repeat all" play order (so it has the same issue as the other play orders).

**Comment by Treferwynd** [comment]
:(

I was looking at your PR, what if instead of a checkbox for ignoring the queue we put a selector with 3 choices:

- Standard Behaviour: the queue works as it always did
- Ignore Queue: as if the queue was empty
- Only Queue: only stuff in the queue gets played. Basically the Queue Only plugin on steroids, which mimics the queue behaviour of other media players

I'm looking at the code, it shouldn't be too difficult, but I have a question: to change the `next()` behaviour I suppose I can just modify `songmodel.py` like you did. But what about the various order plugins?

I think I just need to set the `.order` field of the queue (as in the `.q` in `PlaylistMux`) but I have no idea where it gets instantiated

**Comment by frestr** [comment]
> I was looking at your PR, what if instead of a checkbox for ignoring the queue we put a selector with 3 choices:

Not sure if that would be any better than the combinations provided by "Keep songs" and "Ignore", but that may be subjective.

> I'm looking at the code, it shouldn't be too difficult, but I have a question: to change the next() behaviour I suppose I can just modify songmodel.py like you did. But what about the various order plugins?

The `next` method in the `PlaylistMux` essentially calls the `next` method of the selected order (either built-in or a plugin). So it's the order that should be changed, not the `next` method itself. The reason for the separate calls for the queue and main songlist is that those two have separate playlist models.

Both the queue's and main songlist's models are instances of `PlaylistModel` though (which uses the selected order when selecting the next song), so it's not something inherent that prevents the queue from using the order plugins (I admittedly haven't looked very deep into this, so I may be wrong). The main issue is having a sensible way to do this in the UI.

**Comment by frestr** [comment]
`PlaylistModel`'s `__init__` method uses the `OrderInOrder` order by default, so that's where it gets set. After that instantiation you can in theory change it from anywhere, see for instance the `set_shuffled` method in  `QueueExpander`.

A good start though would be to see how the main song list does the order selection.

In `QuodLibetWindow` we can find the following line:

```
play_order = PlayOrderWidget(self.songlist.model, player)
```

Ok, so the play order seems to be managed by `PlayOrderWidget`.

Looking into what that class does, we can see that it handles the shuffle and repeat buttons (i.e. the orders that can be selected). We can see that pretty much every action calls the method `__compose_order`, which gets the new order and does

```
self.__playlist.order = self.order
```

Looking in `PlayOrderWidget`'s `__init__` method, we can see that `__playlist` is set from the first argument, which is `self.songlist.model` as we saw from the `QuodLibetWindow` class. In other words, the above line of the code is the line that changes the main song list's play order.

I hope this enough to get you started. Just searching around in the code for relevant keywords can often lead you on to the right path.

**Comment by Treferwynd** [comment]
HA! Thank you! I finally have the behaviour I've always wanted! And it took 2 lines of code! (I mean, after all the work you already did and the extensive hand holding :D)

Now the Repeat and Shuffle settings also affect the queue!

Right now this clashes with the default behaviour of QL, setting "Repeat All" and putting something in the queue will repeat the queue and not the initial playlist (or search results). I can see two solutions: introduce a "Queue Behaviour" section in the settings with the selector or another checkbox in the Queue, something like "Shuffle & Repeat" with help text "Shuffle and Repeat modes also affect the Queue"

**Comment by frestr** [comment]
> I finally have the behaviour I've always wanted! And it took 2 lines of code!

Nice!

> setting "Repeat All" and putting something in the queue will repeat the queue and not the initial playlist (or search results)

This should (ideally) depend on whether the Ignore checkbox is enabled, but that may require some changes. Complicating matters, changes have to be compatible with the old queue behavior, where some play orders like "Repeat all" don't make sense.

> another checkbox in the Queue, something like "Shuffle & Repeat" with help text "Shuffle and Repeat modes also affect the Queue"

IMO, what feels most natural is to have the play order apply to the queue in the same way as the main song list. So if you don't wan't to apply a play order when using the queue, you simply disable it as you normally would for the main song list (see #442).

I would suggest just going with whatever you think is best, and then you can get feedback on it in a pull request.
