### ISSUE TITLE
Finer control on pitch plugin

### ISSUE THREAD

**Issue by barraclm** [quodlibet/quodlibet#2859]
I would love to be able to be able to type a number in (say 95 for 95%) instead of trying to drag the slider. Alternatively, have the +/- keys move the slider in increments of 1 (instead of 10 at present). Have I missed something, perhaps this is already achievable. If it isn't, what chance it could be added to the wish list?

**Comment by frestr** [comment]
Thanks for the suggestion. I don't think you've missed something.

This should be a relatively easy fix. A possible solution is to replace the Scale's label with a SpinButton.

**Comment by LudoBike** [comment]
I think this issue can be close now.
