### ISSUE TITLE
[bug] release 4.1.0: no sound indicator Ubuntu16.04

### ISSUE THREAD

**Issue by mDfRg** [quodlibet/quodlibet#2873]
After upgrading from 4.0.2 to 4.1.0 the Unity 7 sound indicator stopped working with Quod Libet (see attached pictures below). Media keys (next/previous track, pause/resume etc.) work. 

Here is how it should look:

![1](https://user-images.githubusercontent.com/11591703/40891163-524a59be-6781-11e8-93f1-1c57fe047b1d.png)

After upgrade:

![2](https://user-images.githubusercontent.com/11591703/40891164-526aa9b2-6781-11e8-9917-174f41f81be7.png)

Those media buttons don't work.

System: Ubuntu 16.04.
Enabled Plugins:

* Advanced Preferences
* Browse Folders
* Change Language
* Downloa Album Art
* Gajim Status Message
* Import Metadata
* MPRIS D-Bus Support
* Queue Only
* Screensaver Pause
* Search Artis in Wikipedia
* Song Notifications
* Tray Icon
* Update Tags in Files
* Waveform Seek Bar

PS. Congratulations and thank you for making such great music player!

**Comment by mDfRg** [comment]
Just git clone and then checkout release-XXX. Then I made .desktop file that always points to newest version:

```
#!/usr/bin/env xdg-open
[Desktop Entry]
Comment=Music Player
Terminal=false
Name=Quod Libet
Exec=/opt/quodlibet/quodlibet/quodlibet.py
Type=Application
Icon=/opt/quodlibet/quodlibet/docs/favicon/favicon.svg
Name[en_US]=Quod Libet
```

**Comment by lazka** [comment]
And you have quodlibet installed as a system package as well?

**Comment by mDfRg** [comment]
Now that you asking I realized I added this ppa long time ago: 

https://launchpad.net/~lazka/+archive/ubuntu/dumpingplace

**however** this ppa is long removed and to be sure I made **dpkg --purge quodlibet** and reboot. No dice, problem persists.

**Comment by lazka** [comment]
I assume that means yes. 

Ubuntu requires that the desktop file we advertise is installed for the sound menu to work, so you need to add one of our PPAs to fix it.

**Comment by lazka** [comment]
Another thing that might work is if you rename the file to "io.github.quodlibet.QuodLibet.desktop" and move it to "~/.local/share/applications" so Ubutu can find it. But it's probably just easier to use the PPA, that way you also get all the dependencies in case something changes.

**Comment by mDfRg** [comment]
Not really @lazka, that was actually a long way to say: no, it is not installed. I just double checked this on main main workstation, which is also Ubuntu 16.04, where I never _installed_ quodlibet using apt, but only by git pull + pointing a .desktop file to /opt/quodlibet/quodlibet/quodlibet.py. 

Version 4.0.2 **works** with the indicator whereas version 4.1.0 doesn't.

The desktop file I mentioned earlier is located in "~/.local/share/applications".

I suggest to reopen the issue.
BTW: I don't know any PPA that keeps up to date with git repo, that's why I git pull every new release.

**Comment by lazka** [comment]
> The desktop file I mentioned earlier is located in "~/.local/share/applications".

Can you try renaming it as suggested above?

**Comment by CreamyCookie** [comment]
Weird, I'm also on Ubuntu 16.04 and using 4.1.0, but the sound indicator seems to work.

![tnaiunterauinar](https://user-images.githubusercontent.com/3063858/40972562-677cfb48-68c1-11e8-9b1c-cf7dd59d96f8.png)

I'm currently still using the PPA. (but planning to use Flatpak soon, thanks for linking btw)

**Comment by mDfRg** [comment]
@lazka I happily confirm that renaming .desktop file to io.github.quodlibet.QuodLibet.desktop and placing it under ~/.local/share/applications **solved** the problem. 
One should remember to place 
```
Name[en_US]=Quod Libet 
```
entry **and logging out/in**, otherwise this will hapen: 

![3](https://user-images.githubusercontent.com/11591703/41008229-243d7092-692a-11e8-83c0-e05dbd8e8e89.png)

I suggest to mention naming pattern somewhere in the documentation (revision Revision beb40472 does not mention it).

**Comment by lazka** [comment]
Our docs already recommend installing the unstable repos while developing against master to get the dependencies/integration: https://quodlibet.readthedocs.io/en/latest/development/devenv.html#linux-logo-linux
