### ISSUE TITLE
QL 4.1 UI question

### ISSUE THREAD

**Issue by urielz** [quodlibet/quodlibet#2874]
It looks like 4.1 has some significant changes in the UI: the search bar, column headers and all buttons have now double the height (see attached screen captures on macOS 10.13.5)

Was this an intended change? If so, I have to say I disagree with it. Screen space is valuable and I don't see a practical reason to extended the height of buttons, headers and search bar.

![ql_ex1](https://user-images.githubusercontent.com/11670888/40982192-a9568442-68aa-11e8-8757-5b7ea4d75196.jpeg)
![ql_ex2](https://user-images.githubusercontent.com/11670888/40982199-ab895fdc-68aa-11e8-95b5-e5e029f9c7d5.jpeg)
![ql3](https://user-images.githubusercontent.com/11670888/40982267-d136c95e-68aa-11e8-9470-8effecc0dbc7.jpeg)

**Comment by lazka** [comment]
I guess you are using the theme switcher plugin? Is "Default Theme" selected there?

**Comment by urielz** [comment]
Oh right. Screenshots are from "Default Theme" theme. There's also now another theme called "Default" which doesn't have the height 'issue'. However the "Default" theme doesn't have dark mode. Adwaita also has double height now. Seems that only some themes have increased height (highcontrastinverse is fine for example, while highcontrast is not).

**Comment by lazka** [comment]
ok, so your CSS overrides are the cause https://github.com/quodlibet/quodlibet/blob/beb4047252188aacc43ae4920ee67189c0dfebd7/quodlibet/quodlibet/_init.py#L310

maybe HiDPI + rem is broken, I remember some patches floating around for that.

**Comment by lazka** [comment]
I can reproduce it.

**Comment by urielz** [comment]
Alright. Thanks for looking into this.

**Comment by lazka** [comment]
TODO for me: try backporting https://gitlab.gnome.org/GNOME/pango/commit/f661cdbf8cfbdb2

**Comment by lazka** [comment]
didn't help, more breakage in fact. I'll try reverting gtk+pango to what we had with 4.0

**Comment by urielz** [comment]
:/ sorry I didn't catch this sooner while in dev branch
