### ISSUE TITLE
Feature - ReplayGain in MP3 files

### ISSUE THREAD

**Issue by Beinsezii** [quodlibet/quodlibet#2881]
Proposal: A plugin to 'apply' track or album ReplayGain data to MP3 files a la foobar2000 or MP3Gain
http://mp3gain.sourceforge.net/
As when play my music through a simple MP3 decoder like in my car, they obviously don't read ReplayGain tags. So, I've been having to switch to my Windows partition in order to use foobar's "Apply ReplayGain to MP3 Files" feature.

**Comment by declension** [comment]
FYI you should be able to do this already with the _Custom Commands_ plugin and `mp3gain`, at least in a basic sense (I think I've done this in the past in fact)

**Comment by M-Igashi** [comment]
For anyone still looking for a solution, [mp3rgain](https://github.com/M-Igashi/mp3rgain) is a modern Rust reimplementation of the classic mp3gain tool.

It supports applying ReplayGain directly to MP3 frames (lossless, no re-encoding):

```bash
# Analyze and apply track gain
mp3rgain -r *.mp3

# Analyze and apply album gain
mp3rgain -a *.mp3

# Undo changes (restore original volume)
mp3rgain -u *.mp3
```

Available via Homebrew, Scoop, Winget, or cargo install.
