### ISSUE TITLE
Plugin Website Search fails to open <website>

### ISSUE THREAD

**Issue by marcelpaulo** [quodlibet/quodlibet#2896]
I configured the `Website Search` plugin to open tag `website`, here's my `searchsites`:

```
https://google.com/search?q=<~dirname = /Various Artists/|<album>|<artist~album>>
Google: album
https://google.com/search?q=<artist>
Google: artist
https://google.com/search?q=<title~artist>
Google: song
https://www.youtube.com/results?search_query=<artist>
Youtube: artist
https://musicbrainz.org/<musicbrainz_albumid|release/<musicbrainz_albumid>|search?query=<album>&type=release>
Musicbrainz: album
https://www.discogs.com/search?type=release&title=<album>
Discogs: album
<website>
Website
```

and here's an album that contains tag `website`:
![image](https://user-images.githubusercontent.com/10074769/42412199-07e933fa-81de-11e8-9997-fefeeefb4455.png)

However, when I run `Website` on the `Website Search` plugin, the `website` URL is not opened and these error messages are logged:

```
D: 83.141: WebsiteSearch.plugin_songs: Got 1 websites from 16 songs
E: 83.142: util.website:
    Traceback (most recent call last):
      File "/home/paulo/src/quodlibet/quodlibet/quodlibet/util/__init__.py", line 496, in website                                                                                                
        Gtk.show_uri(None, site, Gdk.CURRENT_TIME)
    GLib.GError: g-io-error-quark: Operation not supported (15)
```

I'm running QL master (56b68e50c73565376c9950b9e0c044e600f8d2e1) on Xubuntu 18.04.

**Comment by marcelpaulo** [comment]
Forgot to add this:

- The error is the same whether I run the plugin on a song or an album
- My GTK3 version is 3.22.30

**Comment by marcelpaulo** [comment]
This [issue](https://stackoverflow.com/questions/45462219/http-not-supported-when-using-glib-s-gio-apis) suggests that package ***gvfs-backends*** needs to be installed, but I already had it installed, at version **1.36.1-0ubuntu1**

**Comment by frestr** [comment]
I think this bug was introduced in c9da2b69a20d5a930ae85e57a464c192eb23a029.

quote_plus seems to decode the string as a side effect, but since the commit removed escaping for the website tag, the result is that the tag stays encoded. The leads to the literal uri `b'<website>'`, which Gtk.show_uri does not know how to open.

I'm not really sure why the tag value is encoded to begin with (may perhaps be because of a Python 2 issue). Removing the encoding step seems to fix the issue.

**Comment by declension** [comment]
Replicated @marcelpaulo. 
@frestr thanks for investigating - agree with the fix but reverting _that_ commit doesn't fix it either for me (still get _ Operation not supported (15)_) so I think it goes further back.

**Comment by declension** [comment]
Thanks for the fix @frestr

**Comment by marcelpaulo** [comment]
Wow, that was speed-lightning fast, thanks a lot, @frestr, @declension and @lazka ! I've just tested it, it's working fine.
