### ISSUE TITLE
CI: output test results as JUnit XML

### ISSUE THREAD

**Issue by declension** [quodlibet/quodlibet#2900]
Circle CI supports (and recommends) [use of standard xUnit-style XML output](https://circleci.com/docs/2.0/configuration-reference/#store_test_results). This gives you nicer feedback in the UI across builds and quicker to identify the problematic test(s).

py.test supports _outputting_ these with a little convincing...

**Comment by lazka** [comment]
Do you have any example output from another project using this? Just curious..

**Comment by declension** [comment]
I have a work ones (but private), but here's this just added in one other:
https://circleci.com/gh/declension/squeeze-alexa/95

**Comment by lazka** [comment]
looks good!

**Comment by declension** [comment]
I've made a PR: #2960
