### ISSUE TITLE
https://quodlibet.readthedocs.io/ not showing QL docs

### ISSUE THREAD

**Issue by marcelpaulo** [quodlibet/quodlibet#2906]
https://quodlibet.readthedocs.io/ is resolving to this page:
![image](https://user-images.githubusercontent.com/10074769/42616859-18f21698-8586-11e8-8481-d9595b9a09cc.png)

Has the URL for the docs changed ?

**Comment by lazka** [comment]
grrr, third time this week. Thanks.

I don't know, it ends up this way and after I force a rebuild on readthedocs it works again.

**Comment by lazka** [comment]
I've filed https://github.com/rtfd/readthedocs.org/issues/4360

**Comment by lazka** [comment]
I've disabled the build now so it at least doesn't break again.

**Comment by marcelpaulo** [comment]
Manual back, no pun intended ;-), thank you so much !
