### ISSUE TITLE
KeyError: 'medium-count' on musicbrainz lookup

### ISSUE THREAD

**Issue by juerb** [quodlibet/quodlibet#2907]
When I try to look up an album in quodlibet/exfalso with musicbrainz addon I get following error:

    KeyError: 'medium-count'
    ------
    Traceback (most recent call last):
    
      File "/usr/lib/python3.6/site-packages/quodlibet/ext/songsmenu/brainz/widgets.py", line 96, in celldata
        disc_count = release.disc_count
    
      File "/usr/lib/python3.6/site-packages/quodlibet/ext/songsmenu/brainz/mb.py", line 152, in disc_count
        return self._mbrelease["medium-count"]
    
    KeyError: 'medium-count'

When I "Ignore Error" the same error occurs again. After a few ignores a black window appears
Output of exfalso --debug and screenshot attached.

![screenshot_20180712_172838](https://user-images.githubusercontent.com/20169299/42643573-bec54702-85f9-11e8-96f9-85ad315bb048.png)

[exfalso_2018-07-12.log](https://github.com/quodlibet/quodlibet/files/2189246/exfalso_2018-07-12.log)

**Comment by frestr** [comment]
Seems like the `medium-count` key is not returned anymore. Not sure if this is a bug in musicbrainzngs or if it has been deprecated.

`medium-list` entries contain a `disc-count` value, but it often seems to be incorrect. A possible solution is to take the length of `medium-list` instead.

**Comment by lazka** [comment]
sentry has lots of errors starting with "June 30", the day of the last musicbrainz server update.

**Comment by lazka** [comment]
No error report about this for 5 days. I assume this was fixed on the musicbrainz side.
