### ISSUE TITLE
Soundcloud Streaming in Windows

### ISSUE THREAD

**Issue by Beinsezii** [quodlibet/quodlibet#2914]
For some reason, my Windows install of Quod Libet 4.10 has skipping audio issues when streaming from soundcloud.
It works perfectly on my Arch Linux partition.

Windows 10 latest.

**Comment by lazka** [comment]
Does increasing the "buffer duration" in "preferences > playback"  help?

**Comment by declension** [comment]
Also, do other (non-Soundcloud) streams work?

**Comment by declension** [comment]
Sorry, wrong issue number

**Comment by lazka** [comment]
hm, yeah, I can reproduce

**Comment by lazka** [comment]
```
0:00:29.147793436  3904    8a75a30 WARN               audiosink gstaudiosink.c:244:audioringbuffer_thread_func:<directsoundsink0> error writing data in gst_directsound_sink_write (reason: unknown), skipping segment (left: 1920, written: -1)
```

**Comment by Beinsezii** [comment]
Increasing the buffer seems to help slightly, but it might be placebo. Tried all the way to a maximum of 10 seconds.


As for other streams....

Not sure how to use the "Audio Feeds" tab. IDK what qualifies as a generic 'audio feed' or not.

Internet radio plays just fine by 'download popular stations'ing. Though somewhere along the line of playing a random rock song, it must've entered a loop or something as my first CPU maxed and the UI stopped working. Playback was still good though, so I guess that's all that matters in this situation.
-Tried again with electronic and pop to the same results. Haven't tested on Linux yet.

**Comment by lazka** [comment]
The next step is to try if this also occurs with the wasapisink gstreamer element, once that is more stable.
