### ISSUE TITLE
Animated On-Screen Display plugin

### ISSUE THREAD

**Issue by someguyss** [quodlibet/quodlibet#2920]
Two issues here (apologies if they should be separate issues rather than one combined one, not used to doing this):

1. Why is the minimum possible cover size in the GUI 120? You can set it much lower in the config file (I have it set to 60 for example) in .quodlibet/config and this massively reduces the amount of screen space the pop-up takes if you also drop the font size (something I find very desirable).

2. Is it possible to have bottom left and bottom right as preset positions (currently only top, middle or bottom of screen) or even better to be able to drag the popup somehow to set a custom position? The latter is probably much more work and just having the additional presets would be great. Combined with the above about a smaller cover size it'd be much less intrusive as a pop-up on the primary monitor.

(third issue that was previously here was user error)

**Comment by frestr** [comment]
> Why is the minimum possible cover size in the GUI 120?

Probably because it's the smallest sensible size when the default font size is used. But since the font size can be changed, it makes sense to let users decrease the cover size further too.

> Is it possible to have bottom left and bottom right as preset positions

That should be possible, glancing at the code.

It would be nice if you could make two separate issues and close this one.

**Comment by someguyss** [comment]
> It would be nice if you could make two separate issues and close this one.
Will do.

**Comment by someguyss** [comment]
Done, see #2927 and #2926
