### ISSUE TITLE
Strange rating behaviour with imported music library

### ISSUE THREAD

**Issue by someguyss** [quodlibet/quodlibet#2921]
Having recently swapped from Windows 7 to Linux Mint I've copied my music library over, something I had mostly rated using MusicBee. From past experience I know that MusicBee actually inserts the ratings of tracks into the files as a tag, where the format supports this in the obvious tag and where the format does not support this (I believe MP3) creating a custom tag and sticking it in there. Quod Libet hasn't picked up any of the ratings of my MP3 files (expected, unless there was a plugin or special provision for dealing with MusicBee libraries and their tags which is likely to be a very niche issue) but **has** picked up the ratings for FLAC and .ogg files. What is strange is the ratings have all been read as maximum (4/4 or 10/10 as I've now set it to) for those files.

**Comment by someguyss** [comment]
The thought occurs that this might actually be because Quod Libet seems to be using a rating of either 0-4 or 0.1-1.0 and Musicbee might have been using 1-100 or 1-10. Thus a rating of 25/100 would be interpreted as 1/1. Just a guess though.

**Comment by declension** [comment]
See discussions at #2220.

Seems that [MusicBee uses POPM for ID3](http://musicbee.wikia.com/wiki/Tagging) so I think this _should_ be fine in theory. Perhaps you can dump the metadata with `mid3v2` or similar (see this [SO question](https://unix.stackexchange.com/questions/4961/which-mp3-tagging-tool-for-linux))

> Quod Libet seems to be using a rating of either 0-4 or 0.1-1.0

It can display with various formats, but internally (via `~#rating`), it's a 0.0 - 1.0, translated from a single byte value (0-255).

Remember also, QL saves these with an email address typically. See [FAQ entry](https://quodlibet.readthedocs.io/en/latest/guide/faq.html#where-does-quod-libet-store-ratings-and-playcounts).

**Comment by someguyss** [comment]
> Perhaps you can dump the metadata with mid3v2 or similar 
Tried this and yes, Musicbee stores its ratings just like Quod Libet does except using MusicBee instead of an email address. Otherwise they look identical. Simply changing the QL ratings tag email address to MusicBee in preferences and removing and re-adding the entire library has acquired the MP3 ratings simple as that. For clarification all of the graphical tag editors I tried (e.g. easytag) do not show the ratings tag but mid3v2 did as does MP3tag (graphical but only for Windows).

An alternative would of course be to automatically transfer the contents of the MusicBee tag to the QL tag, not something I'm going to do but probably something a plugin could do relatively easily I guess. In fact, while it's beyond my extremely limited competence to do so, hypothetically could a plugin not look for a standard set of ratings tags from other media players (e.g. MusicBee) and transfer the data to a new QL-specific tag? That would make importing tracks rated in other media players (or by other people in other media players) a breeze. Obviously the most time consuming part of that would be gathering the information on where other players store this.

On topic the other files (.ogg and FLAC) are still rated 10/10. Since they don't use normal tags I assume it's just a difference between the two players in how they store ratings.

**Comment by someguyss** [comment]
Ok, have confirmed what's going on with the .ogg files: MusicBee stored its ratings for these as RATING= (e.g. RATING=70) way down at the end of the comment which QL **does** pick up for some reason but interprets as a maximum value resulting in 10 stars. Running under the assumption that as per https://quodlibet.readthedocs.io/en/latest/development/formats.html#vorbiscomment it's looking for a decimal value I've tried changing RATING=70 to RATING=0 (shows up in QL as 0 stars) which is as expected. However RATING=0.6  and RATING=03 both show up as ten stars.
