### ISSUE TITLE
Automatically disabling random play order?

### ISSUE THREAD

**Issue by sphh** [quodlibet/quodlibet#2924]
I enjoy the possibility to randomly play tracks from one album. Together with the `Random album playback` plug-in, this is perfect for me.

Unless the `Random album playback` plug-in selects an album with a (classical) symphony or concert, in which case the random order can be a bit disturbing.

Does QL already has a way to switch off random playing or to enforce a play order within an album?

If not, would it be possible to add such a feature? Maybe an extra tag has to be introduced?

My system:
- Quod Libet 4.2 (development, d3bd5d8d8)
- Linux Mint 19

**Comment by declension** [comment]
Hi. This sounds like #703

**Comment by sphh** [comment]
You are absolutely right. Obviously I have missed this. I will give it a try and close this for now.
