### ISSUE TITLE
 Animated On-Screen Display plugin: minimum cover size

### ISSUE THREAD

**Issue by someguyss** [quodlibet/quodlibet#2926]
The minimum possible cover size in the GUI is 120, however you can set it much lower in the config file (I have it set to 60 for example) in .quodlibet/config and this massively reduces the amount of screen space the pop-up takes if you also drop the font size (something I find very desirable). Would it be possible to have this changed?

From #2920 originally.

**Comment by frestr** [comment]
Since the font size can be set to be 1, it makes sense IMO to be able to set the cover size to the smallest possible size too (1), even if it really will be too small to see.
