### ISSUE TITLE
Waveform plugin: Add an option to not show time labels

### ISSUE THREAD

**Issue by CreamyCookie** [quodlibet/quodlibet#2928]
I love the new waveform plugin. It looks great and is useful for knowing where you are in the current track. The time labels are somewhat redundant for me though, so an option to remove them would be great. 

![ql-screenshot](https://user-images.githubusercontent.com/3063858/43636295-f7c66990-9711-11e8-88fa-77d687f4db62.png)

(Understandably, they also don't quite align with the default time label.)

Slightly unrelated, but as can be seen in the screenshot there's something weird (extra spacing) happening with the track length in the Display text (purple underline). It seems to be related to the Chinese / Japanese characters since I haven't seen it elsewhere. The weird thing though is that it doesn't always happen, but appears consistently for certain titles like the above `穏ヤカナ眠リ`.

![ql2](https://user-images.githubusercontent.com/3063858/43636690-11f33e82-9713-11e8-8c1e-84d0cd2349ac.png)

Anyway, this is the Display text code I'm using: `[span weight='bold' size='large']<title>[/span]<~length| (<~length>)><~rating| <~rating>><~people| by [b]<~people>[/b]><album| from [b]<album>[/b]<~year| (<~year>)><discnumber|<discnumber="1/1"|| - Disc <discnumber>>><discsubtitle| - [b]<discsubtitle>[/b]>>`

**Comment by urielz** [comment]
+1 for making time labels optional.

Also I can confirm (using your display text code) that I don't have extra spaces on my end when displaying non Chinese/Japanese characters.
