### ISSUE TITLE
QL 4.1.0 won't start on Mac OS X 10.11.6

### ISSUE THREAD

**Issue by davidSchlosser** [quodlibet/quodlibet#2934]
David-MBkAir:~ david$ /Applications/QuodLibet.app/Contents/MacOS/quodlibet --debug
dyld: lazy symbol binding failed: Symbol not found: _getentropy
  Referenced from: /Applications/QuodLibet.app/Contents/Resources/lib/libpython3.6m.dylib
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _getentropy
  Referenced from: /Applications/QuodLibet.app/Contents/Resources/lib/libpython3.6m.dylib
  Expected in: /usr/lib/libSystem.B.dylib

/Applications/QuodLibet.app/Contents/MacOS/quodlibet: line 63:  4945 Trace/BPT trap: 5       "$PYTHON" "$bundle_contents/Resources/bin/$APP" "$@"
David-MBkAir:~ david$

**Comment by tmikaeld** [comment]
Looks like your python path might be wrong, If you're using homebrew, make sure to update.

**Comment by lazka** [comment]
We use our own Python, no homebrew.

**Comment by tmikaeld** [comment]
Then check if that Python is compatible with Quod libet.

**Comment by tmikaeld** [comment]
Hm, I'm running the same MacOS version and it have worked without issues.

**Comment by tmikaeld** [comment]
Sorry, I was still on 10.11.5... I'll test on 10.11.6 later.

**Comment by lazka** [comment]
Ah, I remember reporting this upstream some time ago: https://bugs.python.org/issue28341

cpython has a HAVE_GETENTROPY macro, I'll try forcing it to false

**Comment by lazka** [comment]
> Sorry, I was still on 10.11.5... I'll test on 10.11.6 later.

Interesting, thanks for testing.

**Comment by erixtekila** [comment]
> Looks like your python path might be wrong, If you're using homebrew, make sure to update.
Update what, python binary or path ?
Woud you please make this sentence more detailed ?

I run the same issue on 10.11.6 with brew

**Comment by tmikaeld** [comment]
@erixtekila Doesn't seem related to Python via homebrew, wait for a new version.

**Comment by erixtekila** [comment]
:'(

**Comment by lazka** [comment]
confirmed: https://travis-ci.org/quodlibet/quodlibet/jobs/426028394

**Comment by lazka** [comment]
Newer upstream issue: https://bugs.python.org/issue34597

I'm back to building things on 10.11 now.
