### ISSUE TITLE
Search for missing tag

### ISSUE THREAD

**Issue by blimmo** [quodlibet/quodlibet#2935]
When looking for missing metadata it can be very useful to be able to search for tags that are missing from songs.

I think this would be most useful for rating: QL distinguishes between default rating and no rating but there's no way to search for just songs with no rating.

**Comment by declension** [comment]
Yes.... this sounds like #1940

**Comment by blimmo** [comment]
Woops... I thought I'd searched fairly thoroughly but I somehow missed that.
