### ISSUE TITLE
When repeat mode is set to "one song", stop at the album's next track

### ISSUE THREAD

**Issue by 07416** [quodlibet/quodlibet#2943]
When repeat mode is set to "one song" Quod Libet exists the album entirely. I suggest stopping at the following track instead — I often use this feature to pause playback after the current song and I could resume from where I left of.

I understand that there may not be much demand for this functionality, but I see no harm in changing the behavior.

**Comment by frestr** [comment]
This can be achieved by enabling `Control -> Stop After This Song` while a song is playing.
