### ISSUE TITLE
How to only display the album artist in album list?

### ISSUE THREAD

**Issue by 07416** [quodlibet/quodlibet#2944]
I use the "album list" view ("browse" menu). In "album list preferences" album display options can be modified, but I haven't been able to change the `<~people>` setting (artist, performer, composer, arranger...). `<~albumartist>` or `<~artist>` doesn't work.

All tags are set correctly in my audio files using MusicBrainz Picard.

![image](https://user-images.githubusercontent.com/14923168/44341309-2f438480-a490-11e8-89d7-aa077240376c.png)

_I solely want to display the artist, nothing more_

**Comment by frestr** [comment]
A tag prefixed with `~` denotes an internal tag (you can find a list of them [here](https://quodlibet.readthedocs.io/en/latest/guide/tags/internal_tags.html)). Since artist is a normal tag, you would use `<artist>` instead.
