### ISSUE TITLE
Document i18n / l10n for plugins

### ISSUE THREAD

**Issue by The4thLaw** [quodlibet/quodlibet#2946]
Hello there.

While browsing your documentation, I found no way to localize the text for plugins.

I'm using the following documentation:
 - https://quodlibet.readthedocs.io/en/latest/translation/howto.html
 - https://quodlibet.readthedocs.io/en/latest/development/plugins.html

As recommended in the doc, I found the _ function, for example, but I see no way to actually provide the translations for this. Is it possible? Or is it planned but not yet implemented?
From what I saw, the core plugins are also translated in [quodlibet/po](https://github.com/quodlibet/quodlibet/tree/master/quodlibet/po).

I'm not familiar at all with python so it might be a stupid question. On the other hand, the available documentation allowed me to write two plugins I needed in a few hours. Since the documentation is already quite exhaustive, it might be good to document this even if it's trivial.

Thanks

**Comment by lazka** [comment]
You need to include your plugin in https://github.com/quodlibet/quodlibet/blob/master/quodlibet/po/POTFILES.in and the translation process described in the docs will pick it up automatically.

(There currently is no way to translate plugins that are not part of quodlibet)

**Comment by The4thLaw** [comment]
>  (There currently is no way to translate plugins that are not part of quodlibet)

That was my main question, thanks for the clarification.
Is it something that you want to consider? If so, do you want me to open a new issue or should we recycle this one?

If not, you can close the ticket, I can live with that :)

**Comment by lazka** [comment]
> Is it something that you want to consider? If so, do you want me to open a new issue or should we recycle this one?

There are no plans to change this because we prefer having plugins included.

**Comment by The4thLaw** [comment]
Fine for me :)
