### ISSUE TITLE
MP3: doesn't expose id3v1 values in case incomplete id3v2 exists

### ISSUE THREAD

**Issue by The4thLaw** [quodlibet/quodlibet#2947]
Hello,

I've just noticed that Quod Libet is not reading tags on some of my MP3 files.
VLC properly lists the title, genre, artist and date. Quod Libet just finds the genre.

Here is some info
```
$ file Faskil\ \&\ Kemi\ -\ Bring\ That\ Bass\ Back.mp3
Faskil & Kemi - Bring That Bass Back.mp3: Audio file with ID3 version 2.4.0, contains: MPEG ADTS, layer III, v1, 128 kbps, 44.1 kHz, JntStereo
```

When I run `strings` on the file, I see that the genre is encoded at the beginning of the file:
```
00000000  49 44 33 04 00 00 00 00  08 10 54 43 4f 4e 00 00  |ID3.......TCON..|
00000010  00 06 00 00 00 48 6f 75  73 65 00 00 00 00 00 00  |.....House......|
00000020  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000410  00 00 00 00 00 00 00 00  00 00 ff fb 92 60 00 00  |.............`..|
```

But the rest of the information is at the end:
```
00478bf0  54 41 47 42 72 69 6e 67  20 54 68 61 74 20 42 61  |TAGBring That Ba|
00478c00  73 73 20 42 61 63 6b 00  00 00 00 00 00 00 00 00  |ss Back.........|
00478c10  00 46 61 73 6b 69 6c 20  2b 20 4b 65 6d 69 00 00  |.Faskil + Kemi..|
00478c20  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00478c40  00 00 00 00 00 00 00 00  00 00 00 00 00 32 30 30  |.............200|
00478c50  34 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |4...............|
00478c60  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 23  |...............#|
00478c70
(END)
```

From my limited knowledge of ID tags, this file mixes ID3v1 (for the genre) and v2 (for the other fields) tags. Could it be that QL does not read ID3v1 tags if it finds a v2 header, even if the v1 complements the v2?
Re-writing the tags through Quod Libet works, of course.

Version 4.1.0, Windows 10.
I had not noticed this on the previous version (3.9?) but maybe I just never saw it.

I realize this may be too little information, so please let me know how I can provide more.

Thanks

**Comment by lazka** [comment]
> Could it be that QL does not read ID3v1 tags if it finds a v2 header, even if the v1 complements the v2?

yes, it only falls back to searching for id3v1 if it can't find an id3v2 header.

**Comment by The4thLaw** [comment]
Sorry for not answering sooner... It's a bot of both.

I have around 100-200 files that show this issue, but retagging them does the trick. I can live with that.

On the other hand:
 - Other media players don't have this issue. Banshee and VLC are fine, for example.
 - I have not taken specific steps to make it happen. Those files date from a few years back when I used EasyTAG or CDex, and I also have this on files downloaded directly form the artist's site back then. So it's not a hand-crafted artificial example and it could happen to other people.
 - There's absolutely no reason for it not to work from a user's perspective. The average user doesn't know what those versions of ID tags are and this quirk could be a deterrent for them. "This software requires me to re-tag my files, I won't use it."

So it's not a major issue and it has a workaround, but I think this should still be fixed. Eventually :)

**Comment by lazka** [comment]
Thanks, I've opened https://github.com/quodlibet/mutagen/issues/351

**Comment by The4thLaw** [comment]
Thanks for considering this :)

**Comment by lazka** [comment]
Fixed in mutagen.

**Comment by The4thLaw** [comment]
Yay, thanks :)
