### ISSUE TITLE
Can't get back to full library after selecting a playlist

### ISSUE THREAD

**Issue by echosa** [quodlibet/quodlibet#2948]
I'm trying out quodlibet on macOS. When I select a playlist, there's no way to "unselect" it. The result of this is that I can't get back to the full library view unless I close and reopen the program.

Update: I found two ways, but they're not great. 

1.) If I go back to the "Search Library" view after selecting a playlist, it only shows the the songs in the playlist. The search bar is empty. However, clicking the "delete" icon on the right of the empty search bar shows all the songs. I guess clicking that "unselects" the playlist, but that's really confusing UI.

2.) If I select a playlist and then go into the Paned Browser view, the bottom pane still just shows the songs in the selected playlists, but the artist and album panes show all artists and albums. It seems like those panes should also be filtered to just what's in the playlist, but until that bug is fixed, this is at least a workaround for the "can't unselect playlist" bug.

**Comment by frestr** [comment]
This seems to be the same issue as described in #2374.

We should update the song list on browser changes, as there's not much point in keeping the old view visible, especially since playing a song from an old view removes the song from the view.

**Comment by echosa** [comment]
Yes, I believe that that the second point in that issue describes what I'm experiencing. I'll close this duplicate ticket. Thanks.
