### ISSUE TITLE
 Use `' '.format()` instead of `%` for string formatting

### ISSUE THREAD

**Issue by LudoBike** [quodlibet/quodlibet#2949]
In the docs I read that quodlibet uses Python 3 since 4.0.0, however the operator `%` is still use to format string (especially in `ext/gstreamer/pitch.py`) and it seems to me that this is now deprecated and that we should use `format()` instead.

Am I correct? Should we update that?

PS: sorry, I don't now which label I should put

**Comment by lazka** [comment]
> it seems to me that this is now deprecated

[citation needed]

> Am I correct? Should we update that?

I don't mind things getting changed to format() as long as it doesn't affect translated strings since that would force translators to update all those translations for no good reason.

**Comment by LudoBike** [comment]
> > it seems to me that this is now deprecated
>
> [citation needed]

I found any, perhaps I read that in some tutorials advising to use format() but [it seems that even format() is no more recommended](https://realpython.com/python-string-formatting/)

> I don't mind things getting changed to format() as long as it doesn't affect translated strings since that would force translators to update all those translations for no good reason.

I agree, if change break the translation it must stay as it is.

**Comment by lazka** [comment]
> I found any, perhaps I read that in some tutorials advising to use format() but it seems that even format() is no more recommended

f-strings don't work with translations and we support Python 3.5 because of Ubuntu 16.04, so we can't use them anyway.

**Comment by lazka** [comment]
Anything left to discuss here?

**Comment by frestr** [comment]
I don't think it's worth to change all the strings at this moment, because of the translation issues you mentioned and that there's not much to gain by doing it.

One question is whether we should stick to the old format style to be consistent (and potentially change all of them at once if it will be necessary), or if new strings should use the new format style. Guess it doesn't really matter much though.

**Comment by lazka** [comment]
> One question is whether we should stick to the old format style to be consistent (and potentially change all of them at once if it will be necessary), or if new strings should use the new format style. Guess it doesn't really matter much though.

One nice thing about the new method is that the format for keyword based formatting is nicer to read (and probably less confusing for translators):

```
>>> "Foo {bar}".format(bar="Bar")
'Foo Bar'
```

vs

```
>>> "Foo %(bar)s" % {"bar": "Bar"}
'Foo Bar'
```

**Comment by lazka** [comment]
So, I'd say prefer format() for new stuff and if someone feels like changing old ones, feel free to do so.
