### ISSUE TITLE
AudioScrobbler cache when offline

### ISSUE THREAD

**Issue by racuna** [quodlibet/quodlibet#2951]
Sometimes I have to work with my laptop offline or behind a proxy, and AudioScrobbler can't submit nor connect to post.audioscrobbler.com

Then, when I'm working online again, the scrobbling starts with the current song, without uploading the songs I listened while I was offline.

Yep, sad. I know.

**Comment by lazka** [comment]
In theory (from having a quick look at the code at least) this should already happen so this might be a bug.

**Comment by racuna** [comment]
Thanks for checking it.

**Comment by bassstorm** [comment]
@lazka as a late follow up, I tested that use case today. [Scrobble cache file](https://github.com/quodlibet/quodlibet/blob/8b58a81b077e00b32cc4ad30520ccc8ca70f4406/quodlibet/ext/events/qlscrobbler.py#L92) is created and loaded upon next QL start.
However it would be nice to have QL offloading cache more frequently (not at app quit only, but during the work). My situation is that corp proxy rejects scrobble requests, so in case of a power outage or something I could lose whole day of scrobbles. Frequency could be managed via advanced configuration (I'd prefer to update cache file after each song). Please let me know if you prefer to have a separate new issue for that.

**Comment by bassstorm** [comment]
Closing as per above. Feature request is filed as #3649.
