### ISSUE TITLE
Quod Libet, xine-lib and Opus audio in ogg container

### ISSUE THREAD

**Issue by Userblues** [quodlibet/quodlibet#2952]
This mix doesn't work. Indeed, Quod Libet is not at fault, but the result is sad, can't play about 1/3 of my collection. It does not look like xine folks are eager to fix it. What are the chances of Quod Libet switching to ffmpeg instead?

**Comment by lazka** [comment]
Our primary backend is GStreamer which should play everything.

There is a VLC backend which needs merging in #2852

**Comment by lazka** [comment]
There are no plans to support ffmpeg (besides, we already use ffmpeg through gst-libav).

If anyone has a suggestion for another backend and wants to work on that please open a new issue.

**Comment by Userblues** [comment]
Sorry I just found your replies (tagged as spam by Yahoo). I have no intention to install GStreamer. Perhaps VLC backend will be a solution for me, then. thanks for looking into this.
