### ISSUE TITLE
Copyright stop in 2017 in About window

### ISSUE THREAD

**Issue by LudoBike** [quodlibet/quodlibet#2955]
# Issue

The about window says:
> Copyright 2004-2017

Shoud'nt it be “Copyright 2004-2018” ?

# Solution

If it have to be change we just have to modify the value here : https://github.com/quodlibet/quodlibet/blob/f58e102c9006fb78a1a51b1f2e6ad33916939ca5/quodlibet/quodlibet/const.py#L85

**Comment by lazka** [comment]
yeah
