### ISSUE TITLE
Document "Split ... out of ...." in edit tag context menu

### ISSUE THREAD

**Issue by davidSchlosser** [quodlibet/quodlibet#2958]
It seems these split operations expect specific formatting of the tags....
What input formats do each of the split operations require and what are the corresponding outputs?

eg On the 'Artist' tag, how do I use "Split Arranger out of Artist" or "Split Performer out of Artist"?

**Comment by frestr** [comment]
That's a very good question!

It works by first looking at the selected tag and checking whether the tag contains any text enclosed in `()`, `[]`, `--` or `~~`. If it does, then you can extract the text within the closure into a separate tag.

For example: If you have the tag artist=`My Artist (My Performer)`, and then click "Split Performer out of Artist", the result will be that artist is set to `My Artist` and a new tag performer=`My Performer` is created.

This should be documented.

**Comment by lazka** [comment]
For all the split actions we could show the possible outcomes in submenus and let the user select the wanted one.

**Comment by frestr** [comment]
> For all the split actions we could show the possible outcomes in submenus and let the user select the wanted one.

Could you show an example of how that would look?
