### ISSUE TITLE
Encrypt scrobbler password

### ISSUE THREAD

**Issue by bassstorm** [quodlibet/quodlibet#2962]
Scrobbler password stored as clear text in quodlibet/config file:

> scrobbler_password = _\<actual password goes here\>_

The file is likely open for reading by any user on any major Linux distro. Is it possible to apply some security over such sensitive pieces of information? Thanks!

**Comment by lazka** [comment]
Yeah, this came up in #1242.

**Comment by MBybee** [comment]
Still an issue (win10 2019).

**Comment by CreamyCookie** [comment]
Closing as this is basically a duplicate of #2784: Use auth API for Last.fm Scrobbler plugin (instead of plain text user / password)
