### ISSUE TITLE
How to add location from command line?

### ISSUE THREAD

**Issue by vbgfhfngfdtyreyt** [quodlibet/quodlibet#2963]
I have a master library directory, but I don't want to add all subdirs to quodlibet.

I would like to only add a subset.

This subset of directories is in a text file called sorted.txt.

With rhythmbox, I can add these easily with:
bash -c 'readarray -t list < sorted.txt && rhythmbox "${list[@]}"' >/dev/null 2>&1 &|

How can I accomplish the same thing with quodlibet?

**Comment by frestr** [comment]
I don't think this is possible yet, but it would be a nice feature to have.

**Comment by frestr** [comment]
It should be possible now (after #2970), so I guess something like `for dir in $(<sorted.txt); do quodlibet --add-location "$dir"; done` would work.

**Comment by vbgfhfngfdtyreyt** [comment]
Awesome! Thank you! :)
