### ISSUE TITLE
[Suggestion] Vertical / horizontal switch option for paned browser 

### ISSUE THREAD

**Issue by XXXBold** [quodlibet/quodlibet#2966]
It would be great if there was an option for switching between a vertical and a horizontal orientation for the paned browser. For example, I'm using 3 panes: genre, album and people, in that priority. In addition, I set the browser to widescreen mode, to have the panes on the left side of the song list. 

It would be great if it would be possible to change the orientation of the panes to horizontal, cause if you have just a small space in height for the items, you have to scroll as stupid for filtering. In a horizontal pane, there would be a lot more space for showing more items at once.

Hope I made clear what I mean.

**Comment by XXXBold** [comment]
Let me put some picttures, to clarify.
No, scrolling is fine as is, but I'd like the option for changing the view of the panes as follows.
Currently, on quodlibet, it looks like that:
![1](https://user-images.githubusercontent.com/30773753/45595111-3463f880-b996-11e8-9bc5-093afd4ac0cf.PNG)

I'm using foobar2k as my player until now, and there it looks like that:
![2](https://user-images.githubusercontent.com/30773753/45595119-5cebf280-b996-11e8-83f0-5a27a38e3e2f.PNG)

It should be possible to make it look like that in quodlibet as well, but not beeing on top of the playlist.

**Comment by frestr** [comment]
Ah, right. This has actually already been implemented in #1877, but that PR has gone a bit stale.

**Comment by XXXBold** [comment]
Ah, good to know. would be great if it will make it in the master aswell :)

**Comment by frestr** [comment]
Yeah, it probably will eventually.

I'll close this issue then, as we already have #1877.

**Comment by frestr** [comment]
#2630 has been merged, so it's available in master now.
