### ISSUE TITLE
Allow importing .m3u8 playlists

### ISSUE THREAD

**Issue by cdwfs** [quodlibet/quodlibet#2967]
When importing a playlist (on the Windows build, at least), the file browser is filtered to only *.m3u and *.pls files. Would it be straightforward to add support for *.m3u8 as well (just an .m3u with UTF-8 encoding)?

**Comment by frestr** [comment]
I think this should work already (notwithstanding the filtering). Does it work for you if you change the extension to .m3u and then import it?

**Comment by cdwfs** [comment]
Hunh, you're right! I tried importing a playlist that included files with Unicode in the filename, and everything loaded up and played correctly (the track's name was garbled in the UI, but that's a separate issue). So I guess it's just the filtering; there are definitely players that don't handle .m3u playlists with Unicode contents, so I'd prefer to maintain the .m3u8 suffix on my files if possible. Thanks!
