### ISSUE TITLE
Ex Falso, tag from path: method of selecting the last of a series of words

### ISSUE THREAD

**Issue by Najrim** [quodlibet/quodlibet#2975]
Say I have files named like this: "`name of a record label year`". They are from different labels so the number of spaces before we reach "year" varies. Is there a way of saying to Ex Falso that the year should be the last word in this series? `<comment> <year>` of course gives me:

comment: "name"
year: "of a record label year"

I used to use puddletag which has "functions" that can edit tags in more advanced ways. Here's how I solved it in that case: <https://github.com/keithgg/puddletag/issues/410>. (basically using a function that selects text from the right instead of from the left). As far as I can tell Ex Falso doesn't have anything like that but maybe it can be solved in another way?

**Comment by frestr** [comment]
The pattern matching used is quite simple (it doesn't support functions like puddletag), so I don't think you can do this with just Quod Libet / Ex Falso.

**Comment by ohel** [comment]
If tagging the files in two runs is not a problem, you could always do it using the regex replace. Enable the plugin "Regex Substitution". When in "Tags From Path" tab, click on "More options..."

Then, using <comment> as the pattern, fill in the regex: s/(.*)([12][09][0-9]{2})/\1/
Preview and save the results.

Then, use <year> as the pattern, and change the regex to: s/(.*)([12][09][0-9]{2})/\2/
(so just change \1 to \2)

This of course assumes the year is a four-digit number, and a sane one. You could use (.*)([0-9]{4}) as an even simpler alternative.

Does this help?

**Comment by Najrim** [comment]
It helps tremendously! This is just what I needed.
