### ISSUE TITLE
System hangs on macOS 10.14 when starting QuodLibet / Multimedia keys not working

### ISSUE THREAD

**Issue by wbiller** [quodlibet/quodlibet#2979]
I've updated my machine to macOS 10.14 and since then the system hangs for a couple of seconds when starting QuodLibet through Launchpad / Dock. Also the multimedia keys don't work.

When starting QuodLibet directly through /Application/QuodLibet.app/Contents/MacOs/quodlibet everything works like a charm.

macOS 10.14 (Mojave)
QuodLibet 4.1.0

**Comment by wbiller** [comment]
That's a bit strange. I reinstalled QuodLibet and now everything works as usual.

**Comment by michaelfresco** [comment]
I just want to confirm that the Mediakeys do not work for me either. (I press 'next' on my Bluetooth headset, and any other app like VLC or iTunes will play the next song). It's apparently quite hard to capture these keys, the Mac app BetterTouchTool also can't do it).

**Comment by michaelfresco** [comment]
I'm on QL 4.2.0 and MacOS 10.13.3

**Comment by wbiller** [comment]
The issue does not occur anymore after the update to macOS 10.15.
