### ISSUE TITLE
Rate current playing song

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#298]
Original [issue 298](https://code.google.com/p/quodlibet/issues/detail?id=298) created by dimitrios.kapanikis on 2009-08-31T14:16:44.000Z:

there should be an easy, one-click (or two click ;)) way to rate currently
playing songs.

e.g. when playing from a queue there is no way to rate songs straight forward

**Comment by cauerego** [comment]
wished someone would've implemented a "love" button by now. along with a last.fm plugin which would automatically sync the love (both on start playing and on the button), of course, since it's the main and perhaps only feature I'm missing right now and no other player has it!

**Comment by knockoutMice** [comment]
I was thinking about the same feature a few days ago. I'm going to implement it if I have a spare hour.

**Comment by declension** [comment]
@cauerego I raised #963 related to (but more general purpose than) this a long time ago, but we never progressed it

There's also a MusicBrainz version: #927 

I also actually added this, indirectly, for the Soundcloud browser. It's little-known but there's full / two way integration in that browser for ratings, but the Last FM problem is harder as you don't _necessarily_ have a uniquely identifying track ID, and music matching is a hard problem.

Probably best to continue discussion there, or on a new one if not covered (this ticket is closed)

**Comment by cauerego** [comment]
@declension awesome! thanks. :)

but none of those address some concerns I have. so I just opened a new issue. I didn't want to create one before making sure it would make any sense. hope @knockoutMice had thought of some of these too: #2381
