### ISSUE TITLE
No album artwork on xfce4-notifyd

### ISSUE THREAD

**Issue by brunlop** [quodlibet/quodlibet#2981]
Hi! I'm running quodlibet 4.2 on Xubuntu 18.04.
Everytime quodlibet displays a notification (using the song notification plugin), the xfce4-notifyd menu shows no algum artwork.
The notification itself is fine:
![screenshot02](https://user-images.githubusercontent.com/43615430/46094629-563d5680-c1b2-11e8-8fa8-8d098d1c5b45.png)

But on the menu the cover is missing:
![screenshot01](https://user-images.githubusercontent.com/43615430/46094644-62c1af00-c1b2-11e8-9b67-24f7f4609d27.png)

xfce4-notifyd loads icons from ./.cache/xfce4/notifyd/icons/ but quodlibet creates none there.

Is there a way to fix this? Thanks

**Comment by lazka** [comment]
Is the icon missing while the song is still playing/active?

**Comment by brunlop** [comment]
Yes, as soons as the notification pops up xfce4-notifyd registers that new notification without icon.
