### ISSUE TITLE
Allow bare performer tags to NOT show .....(Performance) in  ~people:roles

### ISSUE THREAD

**Issue by davidSchlosser** [quodlibet/quodlibet#2986]
#2674 introduced a change to map bare performer tags to a “Performance” role in ~people:roles 
I appreciate that this might be useful to some (perhaps many) users.

However, as well as several hundred unique performer:role tags, I have many performer tags that intentionally don't include one.  In my use cases the blank role is useful as a way as simply displaying other uncategorised participants (not artists) in an uncluttered manner. Adding the extra real estate for "(Performance)" is problematic. 

Could this become configurable?

**Comment by zsau** [comment]
Now that I think about it, a pattern like `<~people:roles><~~people~participant|, ><participant>` should let you do this already. What do you think?

**Comment by davidSchlosser** [comment]
I appreciate your good intentions, however I don't remember the last time a QL update broke any of my use cases. #2674 breaks my use of <performer:roles>.
I fully agree with the purpose of :role & use it extensively - as I said in the issue. I use it with <performer:roles> - I never use <people:roles>. As you mention, this allows me to explicitly display <performer:roles> differently from other tagged roles "used for other purposes" (<artist>, <albumartist>, <composer>, etc). 

Retagging my library with another tag would be onerous and not add value to my use cases, likewise a solution like #684 proposes. 
(Compare with retagging performer tags to  performer:performance for your apparent use case.)

**Comment by davidSchlosser** [comment]
#2674 refers only to  people:roles - why not restrict the new behaviour just to that, and not have it affect performer:roles?

**Comment by zsau** [comment]
It was not clear that you were talking about `~performer:roles` specifically. Removing the "Performance" role description from that (and not from `~people:roles`) sounds reasonable to me, but others may want to chime in here.

**Comment by davidSchlosser** [comment]
@declension considering your comment on #2674, do you have any thoughts on this? What's the process to reach a consensus?

**Comment by declension** [comment]
I don't really use roles myself much, so have no strong opinions.

That said, if as a user you ask for _roles in performance_, then getting results with one labelled _(Performance)_ feels a bit odd / redundant, so yes I'd also support updating this new behaviour to apply only to `~people:roles`. 

@zsau, are you happy with / to do that?

**Comment by TheYokai** [comment]
I think this is a very reasonable request and I also support it. Though I'm curious, why exactly do empty role labels help? Is it simply a means to remind you what roles are missing?

**Comment by davidSchlosser** [comment]
I leave the role empty where:
I don't have information about what a multi instrumentalist is playing on
the track.
Ensembles where the role is implicit in the name (eg The Dave Lambert
Singers, )
Role is unknown.
I haven't completed tagging.
