### ISSUE TITLE
all folder's name scratched when hovering mouse at move up and down

### ISSUE THREAD

**Issue by xhc1** [quodlibet/quodlibet#2997]
![screenshot_20181018_004407](https://user-images.githubusercontent.com/1653212/47120663-d580f000-d26f-11e8-98ee-446018aa55d9.png)

quodlibet 4.1.0
openSUSE Tumbleweed
Plasma 5.14

**Comment by lazka** [comment]
Thanks. Probably a theme bug.

**Comment by lazka** [comment]
We can probably work around it by special casing the theme, so reopening for further investigation.

**Comment by xhc1** [comment]
it seems bug in package breeze-gtk theme - doesnt matter desktop environment, other gtk theme works - adwaita or arc theme for example

**Comment by ohel** [comment]
I had a similar issue in a GTK theme I've mangled together myself from some other themes. I was able to fix the issue like in this commit: [Fix treeview separator bug.](https://github.com/ohel/dotfiles/commit/6092228141cba5e64f1a875dc040281b778757ed)

I'll take a look at the breeze theme if the same fix works there, too.

**Comment by ohel** [comment]
There was a typo in the theme, I did a [fix and PR](https://github.com/KDE/breeze-gtk/pull/4) only to realize it's a read-only repo and the KDE project handles issues and patches differently. I guess I'll create and account there then at some point. But at least it's easy to fix and the theme's problem, so this Quod Libet issue should be closed.
