### ISSUE TITLE
Sync playlists in Windows and Linux - problems and questions

### ISSUE THREAD

**Issue by Andy3142** [quodlibet/quodlibet#3007]
This is a request for help not a bug.

I want to sync my playlists on 3 machines: Windows 10, Lubuntu and Antix Linux.

(1) While I can export/import .m3u playlists from Win 10 to Lubuntu , they arrive  empty. [I didn't try Antix yet.]

In Windows the library root is %USERPROFILE%\Music and in Lubuntu is ~/Music. The directory structure below that is identical. I am doing Export As Playlist using relative paths, and I've tried both .m3u and .pls and neither work.  The playlists get imported, but say "Empty". What am I doing wrong, please?

(2) Also, I want to sync the rating of the tracks. If I can get (1) working, will "Export Metadata" carry across the rating information?

(3) But the real problem is that I have a lot of playlists and so far it seems I can only export one at a time. Is there a way to export / import all playlists in one go? 

Or to eg physically copy the Playlists file and then bulk edit it from Windows format to Linux format?

(4) Failing that, would it work to locate the databases and configuration etc etc in eg Google drive, and have all 3 machines access the same cloud directory?

**Comment by lazka** [comment]
Might be that we don't support importing playlists with relative paths

**Comment by Andy3142** [comment]
Hi @lazka, well, there is a pull-down to choose relative or absolute paths. Clearly if there was no actual code behind that it would explain things!
