### ISSUE TITLE
Tray Icon + Plasma 5.13.5

### ISSUE THREAD

**Issue by xhc1** [quodlibet/quodlibet#3009]
Everything works just mouse scroll wheel is totally ignored even I change behaviour in options of that plugin (adjusts volume and changes song) and left click opens menu same as right click, expected show and hide quodlibet

Fedora 28

**Comment by lazka** [comment]
As far as I remember that's not supported under Plasma. We could hide the option there though.

**Comment by lazka** [comment]
> As far as I remember that's not supported under Plasma. We could hide the option there though.

It's supported by the appindicator library and we use it, so it's just plasma not implementing it.

You could report it to Plasma.
