### ISSUE TITLE
Request: restore playback

### ISSUE THREAD

**Issue by xhc1** [quodlibet/quodlibet#3012]
could be cool to have option to restore playback on start quodlibet
(now it is Pause in specific time of track)

**Comment by ohel** [comment]
There are the command line options --play and --run you can combine to immediately continue playing where you left. For example:
```
$ ./quodlibet.py --run --play
```
Does this not solve the problem?

**Comment by xhc1** [comment]
thnx for command, it works, but option in GUI could be still really handy for using it in various desktop environments

**Comment by ohel** [comment]
If you copy the Quod Libet .desktop file either from /usr/share/applications or ./quodlibet/build/share/applications/io.github.quodlibet.QuodLibet.desktop (if using directly from a repository) to ~/.local/share/applications, you may edit the Exec line of the .desktop file to have those parameters instead. Your custom shortcut will override the system default shortcut then. I do realize it's obviously a manual step.

Still, I guess it could be a small little enhancement, a checkbox in the preferences "Start playback on startup" or something.

**Comment by frestr** [comment]
You can now set this in the preferences (after bbe23a8fdca3b6aa6187e91c77db6fcdff4d992f).
