### ISSUE TITLE
SoundcloudBrowser._on_select: Getting favorites...

### ISSUE THREAD

**Issue by AdamsObbl** [quodlibet/quodlibet#3014]
hi,
For me, quodlibet is the best player ever, I use nevest version 4.2 (development, 1b7a97878)
and listen to music from soundcloud, but only my favorites songs.
I want run quodlibet by commands with automatic play my favorite songs.
in soundcloud browser i have three options (search, favorite and my tracks)
how open quodlibet by command on browser soundcloud with automatic selected favorites?
and try command "quodlibet --query =" # (rating = 1.0) "--play" but does not work
also try with --filter, but i dont kow what kind tag use, whatever i try is fail
best regards
AdamsObbl

**Comment by frestr** [comment]
Hi. This should be possible now in the latest master (c913575bacd12c391dc123241b3442b44a6879dc), and can be done like this:

```
quodlibet --set-browser=SoundCloud && \
quodlibet --query '#(rating = 1.0)' && \
sleep 0.5 && \
quodlibet --next  && \
quodlibet --play                  
```
