### ISSUE TITLE
Plugin suggestion: support serial LCD display

### ISSUE THREAD

**Issue by ohel** [quodlibet/quodlibet#3026]
Quite some time ago I used to use this Matrix Orbital LCD display in a 5.25" drive bay for displaying temperature and load stats, but also for media info. I decided to convert my old spaghetti code into a QL plugin. The LCD display is 20x2 characters in size, and connects via USB. It is seen in Linux as a ttyUSB device where one can echo text and control codes.

I have the plugin ready in [a repository](https://github.com/ohel/matrix-orbital-quod-libet-plugin) here in GitHub. I know it supports at least some Matrix Orbital LCD displays, but I don't know if the control codes are universal and common between different manufacturers.

I took a (bad quality) video of the plugin in action, showing and scrolling the currently playing song, the album info, and seeking. It's in the zip.
[lcd.mp4.zip](https://github.com/quodlibet/quodlibet/files/2544541/lcd.mp4.zip)

Could a plugin like this live in QL master or is it better to keep it as a separate repo? I realize it's quite a rare piece of hardware especially nowadays - mine is over 9 years old already.

**Comment by lazka** [comment]
We already had something similar for the old logitech keyboards, but it was never maintained and since nobody had the hardware it was removed.

I don't mind adding it as long as it's not too much code and you maintain it.

If you want to make it useful to more people what about making it standalone and listening to the MPRIS2 interface over DBUS so it works with all players?

**Comment by ohel** [comment]
I hadn't even realized the existence of MPRIS2. That would most certainly be a better way to reach wider audience. I'll keep the QL plugin in my repository and maybe do the MPRIS2 version some day, and close this issue. Let this discussion be here as a reference to those two souls who stumble upon it in the future with their ancient LCD displays...
