### ISSUE TITLE
With 4.2, can't add to MATE dock or Plank

### ISSUE THREAD

**Issue by elcste** [quodlibet/quodlibet#3029]
On Ubuntu MATE 18.10, I just upgraded from 4.1.0 (from the Ubuntu archive) to 4.2.0 from the quodlibet-stable PPA. Now I cannot add Quod Libet to the MATE Dock Applet dock. When I launch 4.2, it opened as a second app icon, and this icon is missing the "pin" option that other apps have. If I unpin the first icon, I still can't pin the second one.

Similarly, when I tried Plank, QL doesn't have the "keep in dock" option.

When I downgrade to the  4.1.0-1 package, it works normally again.

I don't have a custom .desktop file or anything else I know of that should effect this. Just to be safe, I tried a new user account and saw the same behavior.

FWIW I believe both of these docks use bamfdaemon for app matching.

**Comment by lazka** [comment]
Thanks.

**Comment by lazka** [comment]
The only related change that comes to mind is 175d21b0da86ebc but not sure how/why :)

**Comment by elcste** [comment]
Fair enough, thanks for looking at it.

I think more people use Plank, and I *think* Unity also used banfdemon, so maybe someone who's still on 16.04 can take a look.

**Comment by lazka** [comment]
Thanks, 16.04 shows the same problem.

**Comment by elcste** [comment]
I submitted a [bug for bamf](https://bugs.launchpad.net/ubuntu/+source/bamf/+bug/1803792), since maybe it's there issue if no one has had a problem using other systems, like GNOME Shell

**Comment by lazka** [comment]
@elcste thanks!

**Comment by lazka** [comment]
bisected to 175d21b0

**Comment by elcste** [comment]
I went on vacation right before that commit, so I just now confirmed it is fixed for me too with the version from your unstable PPA.

Do you accept donations somewhere so I can buy you a coffee/beer?

**Comment by lazka** [comment]
Thanks for testing!

(I only have an idle patreon account, but no need to..)
