### ISSUE TITLE
Slow start on huge library caused by pyinotify

### ISSUE THREAD

**Issue by bassstorm** [quodlibet/quodlibet#3042]
I have a library of about 45k tracks. Literally it takes a minute for QL to start (64 seconds from clicking app icon to seeing actual window opened). In the meantime, it's just a matter of 10 seconds for Foobar2000 with same library.
Files are stored on external USB 3.0 HDD. Manjaro Linux, KDE flavor.
I'm not sure but maybe there's a need to move library initialization routine to a separate thread or something.

**Comment by lazka** [comment]
* Do you have "Scan library on start" enabled in the prefs? Try disabling it.
* Does it depend on the browser view on start?
* Do you have any large playlists?

**Comment by wifon** [comment]
For me, with about 20k songs and "Scan library on start" enabled, it takes about 5-10 seconds to start, while the window pops out after, like 2. It's a bit slow-responding till library scan gets finished, but it takes no more than 10-15 seconds.
ql 4.2.0, Mint 19 Cinnamon. Worth notice that my HDD with music collection is only 5400rpm, so one may think that it would even slow down my startup, yet it doesn't

Maybe your external HDD is the issue? I mean slow read/low IOPS through USB interface. You say it's USB 3.0, is it connected to USB 3.0 port? What are your read times/IOPS on this drive (through USB)

**Comment by bassstorm** [comment]
@wifon, thanks for sharing. My HDD has a power saving profile when it falls to sleep after some inactivity. Maybe there's something similar at plugging in stage...
Anyway, the problem is that UI doesn't show up until it initializes library at some extent. More user-friendly way would be to render a window and let user know that some processing is being done in background.

**Comment by brenthuisman** [comment]
I have about a third of that number of tracks (~16k) but I notice no such sluggishness, in fact, quite the opposite! I have enabled scan at start.

**Comment by declension** [comment]
Almost every time we have a significant scanning performance problem it's over USB. Must be something going on there...

**Comment by bassstorm** [comment]
Again, guys, it's okay that USB is slow and all; improvements in such areas may require significant effort.
But could you consider doing scanning activities in a separate thread, so that UI is rendered first and able to notify user about progress?.. That alone would add much value I believe

**Comment by wifon** [comment]
@bassstorm I think you're absolutely right in this matter.

**Comment by declension** [comment]
Scanning should be a GLib background task already (thus for example you can re-scan your library and continue using QL with only minor impact). I guess it's being blocked somehow at start-up, or perhaps the unpickling of the library file itself is taking the time. 

@bassstorm Do you have some logs for a slow start-up? That might help diagnose this problem better. Also, where is your `songs` file stored (under `~/.quodlibet/`) - is that on the USB disk as well?

**Comment by bassstorm** [comment]
@declension that's correct guess, config files are on the USB disk as well. Would you like to advise how/where I could grab needed logs?

**Comment by declension** [comment]
@bassstorm thanks, and that's probably the bottleneck then (plus explains the UI freeze actually).

To get the logs run with `--debug`. More info here https://quodlibet.readthedocs.io/en/latest/development/faq.html

Also could you relocate your `.quodlibet/` directory onto a fixed (fast) disk and re-time that maybe?

**Comment by ruuda** [comment]
Might also be related to #2066.

**Comment by CreamyCookie** [comment]
@bassstorm Is this still an issue and if so, could you add logs?

**Comment by bhajneet** [comment]
This is still an issue for me on Windows 10. Enabling/Disabling "Scan Library on Startup" has no effect. My library is 30 GB on an SSD. But it will still take 3-5 seconds to load up. VLC, foobar, groove music, etc. are all pretty much instantaneous. I'm using Quod Libet for the folder hierarchy view,the waveform seekbar, and to have the same UI across platforms.

Adding `--debug` to the shortcut or adding an environment variable for QUODLIBET_DEBUG=1 in Windows does nothing for me. (Or at least I don't know where to find the generated log file).

**Comment by CreamyCookie** [comment]
I think you need to open a terminal then paste the full path to the `quodlibet.exe` (including the stuff like `C:\`) and add ` --debug > log.txt`.

Then close QL and the finished `log.txt` file should be in your user folder, if you didn't change the directory of the terminal. (You can attach it when you make a comment here.)

**Comment by lazka** [comment]
On Windows the binary producing output is called "quodlibet-cmd.exe"

**Comment by bassstorm** [comment]
I'll get back yo you guys with debug logs tomorrow. Sorry for delay.

**Comment by bassstorm** [comment]
Here's logs of booting from cold and warmed up device:
[ql_cold.log](https://github.com/quodlibet/quodlibet/files/3456647/ql_cold.log)
[ql_warm.log](https://github.com/quodlibet/quodlibet/files/3456648/ql_warm.log)

The questionable step is 

> AutoLibraryUpdate.enabled: Watching directory

which takes a lot in first case. No UI shown till it's completed.

**Comment by declension** [comment]
>>     AutoLibraryUpdate.enabled: Watching directory
> which takes a lot in first case. No UI shown till it's completed.

Hmm, I thought (AFAIR) that was a threaded setup through to the `inotify` library underneath, but maybe not so much (or maybe the _setup_ isn't). Guess it needs some investigation

**Comment by CreamyCookie** [comment]
Hmm, I wonder if the slow down is then simply unavoidable.. (unless there's a better alternative. pynotify is [walking recursively](https://github.com/seb-m/pyinotify/blob/0f3f8950d12e4a6534320153eed1a90a778da4ae/python3/pyinotify.py#L1852) through all directories in your library)



@bhajneet Are you also using the AutoLibraryUpdate plugin?

**Comment by bhajneet** [comment]
Output of `"C:\Program Files (x86)\Quod Libet\bin\quodlibet-cmd.exe" --debug` in command prompt is in this file: [quodlibetlogs.txt](https://github.com/quodlibet/quodlibet/files/3469089/quodlibetlogs.txt)

I saw the UI show up around `D: 6.364: _main.run: Entering quodlibet.main`.

I don't see AutoLibraryUpdate plugin anywhere. Files I listen to are often 20 minutes minimum and up to 2 hours in length.

I'm not a developer, just looking at timestamps. 

A half second here:
```
D: 2.550: plugins.__restore: Restoring plugins: 2
D: 2.584: PluginManager.rescan: Rescanning..
D: 2.612: ModuleScanner.rescan: Rescanning..
D: 3.193: ModuleScanner.rescan: Rescanning done: 80 added, 0 removed, 15 error(s)
D: 3.236: PluginManager.rescan: Rescanning done.
```

A full second goes by for this:
```
D: 3.725: qltk.playorder.__compose_order: Updating PlaylistModel order to <Repeat all D: 4.521: GStreamerPlayer.go_to: Going to None
D: 4.626: PlaylistMux.go_to: Told to go to None
D: 4.700: QueueModel.go_to: Told to go to None
D: 4.778: PlaylistModel.go_to: Told to go to None```

**Comment by declension** [comment]
Updating title to indicate probable root cause here. That plugin needs thought, or replacement with a GLib / GIO equivalent (I tried this years ago, almost worked IIRC)

@bhajneet I think yours is a separate issue (and much faster than the ~60seconds from the OP)

**Comment by declension** [comment]
(found the issue tracking a replacement for that plugin #1039)

**Comment by bassstorm** [comment]
> Anyway, the problem is that UI doesn't show up until it initializes library at some extent. More user-friendly way would be to render a window and let user know that some processing is being done in background.

That part is could be tackled in #1116.
