### ISSUE TITLE
Edit saved search / query

### ISSUE THREAD

**Issue by bassstorm** [quodlibet/quodlibet#3043]
Currently it's allowed to add or remove a item to/from saved query list. Would be nice to have editing capability to avoid "add new/remove old" flow.

**Comment by lazka** [comment]
Yeah, agreed.

**Comment by bassstorm** [comment]
I'd like to implement that, but need some support from mature QL developers as I'm a newbie in Python (have plenty of Java experience though). Is that feasible?

**Comment by declension** [comment]
@bassstorm it's not as simple as it might seem, partially because of [the way GObject bindings work](https://pygobject.readthedocs.io/en/latest/) here.

Try https://python-gtk-3-tutorial.readthedocs.io/en/latest/treeview.html for a good intro.

**Comment by CreamyCookie** [comment]
Closing this as a duplicate of the older and more general #1061.
