### ISSUE TITLE
Quod Libet does not work on Windows 10 (1809)

### ISSUE THREAD

**Issue by Cleobule** [quodlibet/quodlibet#3047]
Hello,
a little message to tell you that Quod Libet 4.2 does not work on my Windows 10 (1809).
The update is going very well, uninstalling the previous version (4.1) and then installing the new version.
No warning message, no worries during this one.
But once the installation is done, Quod Libet simply refuses to start. In the task manager, I can see the process start and then disappear.
I went back to version 4.1 and everything works perfectly as before, settings and preferences intact.
I do not have other computers on hand at the moment, so I am unable to test on another windows. I also did a quick cleanup of Windows and a reboot but nothing changes.
If anyone could test or check, that would be nice.
Thank you.

**Comment by lazka** [comment]
Do you have any files like "libssl-*" or "libcrypto-*" in C:\Windows\system32"?

**Comment by lazka** [comment]
There is also a quodlibet-cmd.exe in the same dir as quodlibet.exe which might give some output.

**Comment by Cleobule** [comment]
libssl-        no, I don't see anythiing like this
libcrypto.dll       yes, got it

So I reinstall version 4.2 of Quod Libet.
ExFalso works (btw), Quod Libet-cmd starts a black window and closes after about 5 seconds. Unfortunately, not being a developer, I do not know what to do to help you, it is far beyond my skills.

**Comment by lazka** [comment]
>  libcrypto.dll yes, got it

try renaming it to something else and try starting QL again.

**Comment by Cleobule** [comment]
Sorry but it does not work.

**Comment by lazka** [comment]
OK, thanks for testing.

**Comment by lazka** [comment]
For the record, I can't reproduce on Server 2016 (which is equal to an older win10 afaik). I don't have a Win10 box around atm.

**Comment by hannes101** [comment]
Quodlibet 4.2.0 works here on a Win10 machine. One thing I noticed is that the icon is not displayed when attaching it to the task bar, but just a blank white sheet.

**Comment by Cleobule** [comment]
It still does not work at home. Even with the portable version. Ex-Falso 4.2 works though.
I was able to test on Win7 sp1 and I have exactly the same problem.

**Comment by lazka** [comment]
Thanks for the update. I have at least all of these "adobe CC, VLC, LibreOffice, Steam games" in some form installed as well here.

btw. 4.2.1 is out

**Comment by Cleobule** [comment]
And 4.2.1 works fine! (and look good too) Thank you.

**Comment by lazka** [comment]
oh, cool :)
