### ISSUE TITLE
Having memory card reader without memory card gives startup dialog

### ISSUE THREAD

**Issue by scootergrisen** [quodlibet/quodlibet#3049]
If i start Ex Falso in Windows 7 i get this messages.
![exfalso](https://user-images.githubusercontent.com/1836590/48309204-1d481e00-e575-11e8-8ce2-dad5dbf45be7.png)
I guess the software tries to scan for files on A: and B: drives but i do not have those on my system so i get this message.

I have also seen this message in other software so not unique to Ex Falso.

I have a F: drive. If i change that to A: or B: i can start Ex Falso without getting the dialog.

**Comment by scootergrisen** [comment]
Seems the dialog comes when i have a empty memory card reader (removeable drive).
If i insert a memory card the dialog does not come.
Then if i remove it the dialog comes and ask me to insert it in e.g. F: or whatever is used.

Having a DVD device with a disc does not seem to give the dialog so dont know why this happens with memory card reader but not optical disc drive.

**Comment by lazka** [comment]
We currently iterate over all drives to find them which is the only thing I can think of: https://github.com/quodlibet/quodlibet/blob/2926f2422924f0ebd30cd52c87e859df6b2680df/quodlibet/quodlibet/qltk/filesel.py#L127

Maybe there is a different way.

**Comment by scootergrisen** [comment]
The message in the dialog is not good.
It says "diskette" which is floppy disc but first i dont have floppy disc drives and then the messages says "Harddisk1" which is hard disc so not a floppy disc and then it says "DR1" which i dont know what is.
Not sure where the text is from but seems to be incorrect so hard for the users to know what causes it.

Also it does not seems to matter what button i press Ex Falso will start afterwards.
I would expect Cancel to not start Ex Falso.
And Try again does not seems to try again.

If the dialog comes from Python or some library then perhaps updating that software to latest version will correct the issue is it have been fixed in newer versions.

**Comment by scootergrisen** [comment]
If i start exfalso.exe from cmd.exe i get the dialog.
But if i start from git Bash MINGW64 that uses "/C/" instead of "C:\" i do not get the dialog.

I also get the dialog in quodlibet.exe when i go to preferences, library, and select "Add".

I seem to be able to see the drives/folders just fine even when starting from git Bash MINGW64.
So could it be that the def _get_win_drives(): code is just not nessecary at all?

**Comment by scootergrisen** [comment]
If anyone can tell me what software the message in the dialog is from i would like to know.

**Comment by lazka** [comment]
After searching around I think it's Windows itself. I remember a similar behavior from WinXP when I still had a floppy drive.
