### ISSUE TITLE
How do I edit the library with code?

### ISSUE THREAD

**Issue by Tamriel** [quodlibet/quodlibet#3054]
I want to convert my whole library to Ogg because it takes less space.
In this process, I want to keep my song ratings.
Since converting plus re-scanning the files looses the ratings, I thought about adjusting the file path of the quod libet library object. 
Sadly, on refreshing the library the ratings are lost nevertheless.
Do I need to use the library.rename method to keep the same song key or something like that?

```
import os
import quodlibet.library

library_path = os.path.join(quodlibet.get_user_dir(), "songs")
library = quodlibet.library.init(library_path)

for song in library:
    song['~filename'] = song('~filename').replace('.mp3', '.ogg')
    library.changed([song])

library.save()
```

**Comment by lazka** [comment]
You have to change the type of the object as well (untested):

```
from quodlibet.formats.xiph import OggFile
song.__class__ = OggFile
```

(Unless you have compatibility problems I'd go with opus instead of vorbis)

**Comment by Tamriel** [comment]
That worked :-)
Warmest thanks for your hint at opus!
