### ISSUE TITLE
Add a Ex Falso flatpak on flathub

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#3060]

**Comment by toabctl** [comment]
@lazka hey. I saw commit https://github.com/quodlibet/quodlibet/commit/1c84e489b13f0217a0a674696b76bc8a7414c416 which seems to add a flatpak for exfalso but I can not find it on flathub.org . What's missing here?

**Comment by lazka** [comment]
I just need to do a release basically :)

**Comment by toabctl** [comment]
Could you do that? Or can I somehow help with that?

**Comment by lazka** [comment]
Some progress on this: https://github.com/flathub/flathub/pull/1355

**Comment by lazka** [comment]
https://flathub.org/apps/details/io.github.quodlibet.ExFalso
