### ISSUE TITLE
MQTT plug-in: publish with retain=True

### ISSUE THREAD

**Issue by davidSchlosser** [quodlibet/quodlibet#3062]
This plug-in looks very useful for enabling a custom client to display more customised tag content than other plug-in remote control options (MPD, MPRIS2). To investigate further. I'd like newly connected clients to obtain the most recent Quodlibet status update when they connect.

From my reading of the paho-mqtt docs, the publish method can allow the broker to retain the most recent status by publishing with retain=True (default is False).

publish(topic, payload=None, qos=0, retain=False)

Can the plugin be changed (or made configurable) so the most recent messages are retained, or might this cause problems?

Thanks, David

**Comment by declension** [comment]
OK, that's cool. Didn't know it would let you do that (so easily)!
