### ISSUE TITLE
Windows - Scrolling over volume icon in main window raises/lowers volume too much in 4.2.0

### ISSUE THREAD

**Issue by thehumandistraction** [quodlibet/quodlibet#3065]
Normally, when scrolling the mouse over the volume icon in the main window, Quod Libet raises/lowers the volume by 5%. 

However, with the latest version 4.2.0 on Windows 10, when doing the same action, Quod Libet interprets this action literally and will move the volume per how many lines the scroll wheel is set to in Windows' Control Panel.

i.e. The default value for lines scrolled in Windows is 3. Because of this, the volume will move by 15% instead of 5% like normal. If it is set to 4, it will move by 20%, respectively. 

From my own testing, this seems to be Windows only as 4.2.0 in Arch Linux doesn't seem to be affected by this at all, even after changing the mouse settings like in Windows.

**Comment by lazka** [comment]
Yeah, likely https://gitlab.gnome.org/GNOME/gtk/issues/1408

**Comment by thehumandistraction** [comment]
> 
> 
> Yeah, likely https://gitlab.gnome.org/GNOME/gtk/issues/1408

That definitely seems to be it.

**Comment by lazka** [comment]
Fixed upstream. Not sure if I will backport it or just wait for the next release.
