### ISSUE TITLE
Tags of read-only files cannot be edited

### ISSUE THREAD

**Issue by Carmina16** [quodlibet/quodlibet#3066]
When the file tags of which are edited is read-only, the program fails to write and update them. It should still update the tags in the library.

**Comment by xhc1** [comment]
maybe some information about read-only tag and question if rewrite is "ok" when trying to edit tag

**Comment by declension** [comment]
I don't think saving something in the tag database (library) but not in files is a good idea really. The library is really a cache of the files' tags, and rebuilding the library will then wipe these anyway generally
