### ISSUE TITLE
command enhancements: print-query, print-playlist

### ISSUE THREAD

**Issue by davidSchlosser** [quodlibet/quodlibet#3080]
Currently the `--print-playlist` and `--print-query` commands only return the songs' paths & filenames.  The `--print-playing` command however allows a tag pattern argument and, if present, returns the matching string. Could the `--print-playlist` and `--print-query` commands be enhanced to return strings matching an optional tag pattern?

eg 
`quodlibet --print-query=performer:guitar='John McLaughlin'  '<~album~title>'`

also, a blank query with a tag pattern should also print all the existing tag values:
`quodlibet --print-query= '<genre>'`

**Comment by frestr** [comment]
Kind of related: #1979
