### ISSUE TITLE
Windows: --print-playing does not work correctly

### ISSUE THREAD

**Issue by Beinsezii** [quodlibet/quodlibet#3087]
`./quodlibet-cmd.exe --print-playing` returns nothing. No difference in behavior when adding extra arguments like `<~basename>`.

From what I can tell, none of the other `--print*` arguments work correctly either. Could just be that I suck at using them though.

`--debug` and `--version` work, along with all the other arguments I've used in the past.

Tried with powershell and cmd.

**Comment by lazka** [comment]
Yeah, that's not yet implemented on Windows.
