### ISSUE TITLE
[bug] High CPU Load with Xorg for Unstable Release

### ISSUE THREAD

**Issue by flexid2000** [quodlibet/quodlibet#3089]
On Xubuntu 18.04, after installing the unstable release of quodlibet
`quodlibet_4.2.99+10091~5a1ecc1cb-0~ppa0~bionic_all`
the xserver is playing crazy. Shown by htop, the Xorg-line
`/usr/lib/xorg/Xorg -core :0 -seat seat0 -auth /var/run/lightdm/root/:0 -nolisten tcp vt7 -novtswitch`
catapults the cpu load on every core to a value of ca. 15 % every 2 seconds. Removing all plugins doesn't change the picture. Just completely removing unstable quodlibet lets Xorg revert to normal modes.
I wouldn't know whether that effect can be reproduced on other os.

**Comment by lazka** [comment]
Do other GTK based apps work find for you?

**Comment by flexid2000** [comment]
Yes, they do without problems. The strange thing is that the high cpu load occurs even when quodlibet is not opened, just installed.

**Comment by flexid2000** [comment]
Addendum: The flatpak app works without qualms.

**Comment by lazka** [comment]
hm, weird, let me update the PPA

**Comment by flexid2000** [comment]
Thanks for the update. Now it's working properly again!

**Comment by lazka** [comment]
Thanks for testing
