### ISSUE TITLE
Panel divide not stored on disk

### ISSUE THREAD

**Issue by CreamyCookie** [quodlibet/quodlibet#3104]
I remember this working in the past (though not super sure) and I didn't find an issue about this, so here it is.

Steps to reproduce
------------------

1. Change how the panels are divided. For example, open the album list browser (ctrl + 4), then give more space to the album list on the left.
2. Close and restart QL.

Expected Output
---------------

It restarts with the modified split.

Actual Output
-------------

The panels are back to their previous sizes / split, which in my case results in a horizontal scrollbar for the tracklist.

Test System
-----------

### Which version of Quod Libet?
4.2.0

### Which operating system 
Kubuntu 18.04

**Comment by CreamyCookie** [comment]
@frestr Interesting. This could be coincidence but it seems to automatically widen the album list size so the current album title is in full view. I first made the area very small (resulted in this value: `albumlist_pos = 0.1590909090909091`), then I restarted QL. The size was back to wide again, which is also seen in the config file after closing QL again. `albumlist_pos = 0.31087662337662336`

**Comment by frestr** [comment]
Hm, ok. Does it still happen if you start QL with a different config (`QUODLIBET_USERDIR=foo quodlibet`)? And does it affect other config options too, or just the splits?

I was not able to reproduce this on Kubuntu 18.04, so there might be some peculiarity with your setup.

**Comment by CreamyCookie** [comment]
@frestr I just tried with a new user profile and it seems like the same is happening. Only when I make the left side very wide does it seem to be stored.

Okay this is weird. I just tried the same with my real profile. I made the left side (album list) very wide. Restarted QL was still big (so it restored the size). Then I made it very small again. Restarted QL again. Left side is still very wide.

**Comment by frestr** [comment]
I see. Changing the scaling factor made no difference for me.

Given that the config is always saved and other config options are always restored, it may seem like it's related to the `set_relative` method in `qltk/paned.py` (or related methods in that class/file) -- if you want to have a go at debugging it.

**Comment by CreamyCookie** [comment]
Thanks for the pointer. I have now stepped through the code but weirdly enough, I can't reproduce it anymore. I don't see anything in the history of the file, but maybe something else changed between 4.2 and master that caused it to disappear. (I'm closing this issue for now.)

The only thing I'm not sure about is `get_relative`:

```python
    def get_relative(self):
        """Return the relative position of the separator, [0..1]."""

        if self.__alloced:
            rel = float(self.get_position()) / self._get_max()
            if 0 <= rel <= 1:
                return rel

        if self.__relative is not None:
            return self.__relative
```

I wonder why `__relative` isn't returned (if it exists) instead of always recalculating the position and returning that. Maybe there's a panel that doesn't use events to call `set_relative` and so `__relative` could be outdated when calling `get_relative` to store it on disk?

**Comment by frestr** [comment]
> I wonder why __relative isn't returned (if it exists) instead of always recalculating the position and returning that. Maybe there's a panel that doesn't use events to call set_relative and so __relative could be outdated when calling get_relative to store it on disk?

`__relative` is used for storing an explicitly set position if the pane hasn't been "physically" allocated yet, since the pane doesn't really have a position at that time. Relying on it after allocation would not give the correct position, as sliding a pane divider in the UI does not trigger `set_relative`.

> It's a very minor issue, but the recalculating causes the value to constantly change (minimally) due to rounding errors. And of course it would be faster without recalculating.

The error should be deterministic, in that you always get the same (slightly erroneous)  value as long as `get_position` and `get_max` return the same values.

**Comment by meow464** [comment]
I'm having a similar problem on 4.3.0 on Debian 11 (Stable): the column settings are not loaded from the file. 

If I set "Column Layout" to "Columnar" or "Wide" the settings are correctly recorded to the config file as `pane_mode = ColumnMode.COLUMNAR` but on startup that option is ignored.

**Comment by CreamyCookie** [comment]
@meow464 Please create a new issue about that.
