### ISSUE TITLE
Escape characters in filtering query

### ISSUE THREAD

**Issue by eauchat** [quodlibet/quodlibet#3110]
Steps to reproduce
------------------

This is not exactly a bug, but it's more a bug than a feature I think.

In the [doc](https://quodlibet.readthedocs.io/en/latest/guide/searching.html#searching), it's said that 

> The search terms can’t use quotes ("), slashes (/), hashes (#), pipes (|), ampersands (&), or bangs (!); these characters have special meanings for advanced searches.

This is understandable, but nothing is said about a possibility to escape those characters if necessary to search strings containing those characters.
Imagine that you want to filter all music that is only in the folder: `/Music/folder1/` you can use the following query `filename=folder1`, but imagine there is another folder called: `/Music/folder2/folder1/`, all content from this second folder will also match the query.
It would be great to be able to query `filename=/Music/folder1` for example.
The problematic "/" could be escaped this way for example `filename=\/Music\/folder1`.

Test System
-----------

### Which version of Quod Libet?
3.5.3

### Which operating system 
Ubuntu 16.04

**Comment by frestr** [comment]
It's maybe not very intuitive, but you can escape characters inside regex searches. So your example can be written as `filename=/\/Music\/folder1/`.

**Comment by eauchat** [comment]
Thank you, this is great.
I wrote a micro patch to the doc to explain this, since it's what I was looking for and wasn't finding it in the doc.
I think maybe this issue could be closed if the patch is accepted. It probably wouldn't be very useful to create another way to escape characters since it the intended search can already be achieved.
