### ISSUE TITLE
Loud pop when scrolling to far with arrow keys/pgup/pgdown

### ISSUE THREAD

**Issue by Najrim** [quodlibet/quodlibet#3111]
Steps to reproduce
------------------

1. Select the song at the bottom or top of the list in a browser window.
1. Try to go further with the arrow keys or page up/page down

Expected Output
---------------

Either nothing or a sound at a reasonable audio level.

Actual Output
-------------

Loud pop at 100% of the volume.

Test System
-----------

### Which version of Quod Libet?

4.2.1

### Which operating system 

Manjaro

### If it's audio-related, what back-end?

`gstreamer 4.9.0`

Additional Information
----------------------

It's the same pop as I get when using "find in page" in Firefox and it can't find the search term.

**Comment by lazka** [comment]
Try disabling sound effects.

![screenshot from 2019-01-15 12-58-33](https://user-images.githubusercontent.com/991986/51179290-5b3f2680-18c5-11e9-816a-b342a404b64c.png)

I don't know why they would be load, or loader than expected...

**Comment by Najrim** [comment]
Thanks for the quick reply. I'm om Manjaro KDE, which has different settings. As far as I can tell the sound effects are in the notification settings and I can't find any sound that seems to have to do with this (and they have to be turned off individually).

I also tried adjusting sound stetings in `pavucontrol-qt`. I turned system sounds down to 0% volume, but the pop was still there. Same if I turned down to volume for Quod Libet to 0%.

**Comment by lazka** [comment]
No idea, sorry.

**Comment by Najrim** [comment]
How are the lists of songs handled? Do you have something like Qt for that or is it all built from the ground up for Quod Libet? 

Do you get any sound at all if you try to reproduce?

**Comment by Najrim** [comment]
I turned off the system beep which is a workaround. See here: <https://www.thinkwiki.org/wiki/How_to_disable_the_pc_speaker_(beep!)>

Still, it would be better to get to the root of the problem.

**Comment by bassstorm** [comment]
Okay, I experienced the same behavior. However PC speaker beep was not really loud but rather okaish. System notification sounds were disabled for sure.
But IMO this unlikely is something QL developer team to deal with.

**Comment by CreamyCookie** [comment]
Yeah, that's very likely related to the operating system.. Closing for now.
