### ISSUE TITLE
A donation is waiting at opencollective.com.

### ISSUE THREAD

**Issue by ewtoombs** [quodlibet/quodlibet#3116]
Sorry for (ab)using the issue tracker for this, but it was the only way I could think of to get a hold of you. There's a 100USD pledge waiting for the developers of quodlibet here: https://opencollective.com/quodlibet

**Comment by lazka** [comment]
I've created an account now and gave it access to github to verify the ownership but now it doesn't show anything anymore.. ¯\_(ツ)_/¯

**Comment by ewtoombs** [comment]
How about now?

**Comment by lazka** [comment]
That's wasn't the easiest way to transfer money tbh :) and only $83 survived in the end due to transfer costs. But the money made it through and I've split it with the others.

Thanks @ewtoombs ! 🍻
