### ISSUE TITLE
Copy selected into

### ISSUE THREAD

**Issue by xhc1** [quodlibet/quodlibet#3121]
there is already global option : Move to Trash
should be cool have also: Copy / Move <choosing path>

**Comment by frestr** [comment]
Can you be more specific as to how this would work and why it would be useful?

**Comment by xhc1** [comment]
actually I found "Copy" workaround by "drag and drop" - to copy files in playlist into external flash disk so my main "problem" was solved

**Comment by declension** [comment]
Great, please reopen if necessary @xhc1
