### ISSUE TITLE
Pressing enter after selecting a random album with Ctrl+M doesn't play the album

### ISSUE THREAD

**Issue by frestr** [quodlibet/quodlibet#3122]
Steps to reproduce
------------------

1. Change to cover grid browser 
2. Press Ctrl+M to jump to a random album
3. Press enter/return

Expected Output
---------------

The selected album begins playing.

Actual Output
-------------

It does not begin playing.

Test System
-----------

### Which version of Quod Libet?
Latest master (76abfc55c6eb7e4500f7974b54c2fc8a89cf1a72)

### Which operating system 
Ubuntu 18.04

Additional Information
----------------------
Pressing enter plays an album if it is manually clicked on first (instead of with Ctrl+M), so I would expect Ctrl+M to behave in the same way.

This also doesn't just apply to the cover grid browser, but rather any browser that jumps to a random album instead of modifying the query text.

An observation is that first clicking on album, pressing Ctrl+M (any number of times) and then pressing enter works, but only once (doing Ctrl+M and enter afterwards does not work). So it seems like the problem is that Ctrl+M does not (re)focus the album list.

**Comment by declension** [comment]
:smile:
