### ISSUE TITLE
Plugins in the ~/.quodlibet/plugins dir do not get detected

### ISSUE THREAD

**Issue by petko10** [quodlibet/quodlibet#3129]
Steps to reproduce
------------------

Install quodlibet on Manjaro linux (Arch based). Create the dir ~/.quodlibet/plugins . Add a file playlist_server.py with contents:
```
from quodlibet.plugins.playlist import PlaylistPlugin

class PlaylistServer(PlaylistPlugin):
    PLUGIN_ID = "playlist_server"
    PLUGIN_NAME = "Playlist server"
```

Expected Output
---------------
The plugin should apper in the plugins list, but it does not. No errors in the console or plugin errors dialog.

Test System
-----------

**Comment by frestr** [comment]
If your QL config files are in `~/.config/quodlibet` (which they probably are unless you have migrated older configs), you will need to put your plugin there instead (i.e., in `~/.config/quodlibet/plugins`).

The plugin doc is a bit dated in this regard.

**Comment by petko10** [comment]
Actually I tried that beforehand and it didn't work either. Turns out the syntax of the PLUGIN_NAME string assignment from the docs was causing that: `PLUGIN_NAME = _("My Plugin")`

**Comment by frestr** [comment]
Good, thanks for #3133. I'll close this then.
