### ISSUE TITLE
Add library search capability to ExFalso

### ISSUE THREAD

**Issue by nchammas** [quodlibet/quodlibet#3132]
The proposed change
-------------------

I think it would very useful if ExFalso let you search your library in the same way that QuodLibet does.

Benefits of this change
-----------------------

Tag editing is a laborious process. Often, you want to focus your tag editing on specific songs or categories of songs. (e.g. Find all songs tagged "Grouping: Salsa Dura" and change them to "Grouping: Salsa Classica".) The most powerful way to search for the songs you want to edit tags for is the search functionality already built into QuodLibet, so why not include that in ExFalso too?

This also makes one of ExFalso's abilities much more attractive: the ability to add arbitrary tags to songs. 

(This is actually how I discovered ExFalso in the first place. After years of searching for a way to tag and search my library with arbitrary tags, I decided I'd look into building a tool myself. That led me to [Mutagen], which in turn led me to QuodLibet.)

If you play your music with another player but are not happy with that player's ability to search and organize your library, ExFalso could be the perfect companion to your existing player. Because ExFalso lets you create arbitrary tags, you can organize your music in any way you see fit without needing to abuse the "standard" tags like Grouping or Genre. As a DJ, I think this is very useful!

To elaborate, I have all this information about what songs have what features or convey what feelings, and it's all locked in my head (e.g. "funny lyrics", "slow buildup", "fire"). I can typically only remember the details of the songs I've listened to recently. For years I've wanted some way to dump all this information from my head into the computer via arbitrary tags and then search it live as I decide what song to play next.

If ExFalso let you search your library by the same tags it is capable of editing, and then quickly send a song from the search results pane to the user's preferred player (e.g. via drag and drop) then it would be the ultimate companion to any music player.

Any issues this might cause
---------------------------

The more stuff we add into ExFalso that's already in QuodLibet, the more unclear the line between the two becomes and the less lightweight ExFalso becomes. Should ExFalso ultimately include everything in QuodLibet minus the ability to play music? If so, then why not just add a view option to QuodLibet that simply disables and hides the player component, and remove ExFalso? If not, where is the line on what belongs or doesn't belong in ExFalso?

[Mutagen]: https://github.com/quodlibet/mutagen

**Comment by CreamyCookie** [comment]
Closing this, as I think it's out of scope for Ex Falso, which is a tag editor and so, as far as I know, has no concept of a library.

Additionally, Quod Libet includes much (all?) of Ex Falso's tag editing capabilities, so there's already the library search functionality.

> To elaborate, I have all this information about what songs have what features or convey what feelings, and it's all locked in my head (e.g. "funny lyrics", "slow buildup", "fire"). I can typically only remember the details of the songs I've listened to recently. For years I've wanted some way to dump all this information from my head into the computer via arbitrary tags and then search it live as I decide what song to play next.

I use playlists for that.

> Tag editing is a laborious process. Often, you want to focus your tag editing on specific songs or categories of songs. (e.g. Find all songs tagged "Grouping: Salsa Dura" and change them to "Grouping: Salsa Classica".)

Can't find it right now, but I'm reasonable sure that there are issues for batch editing and automating. You can also 

There's also #1253
