### ISSUE TITLE
Scrubber doesn't show and right clicking on a song doesn't work

### ISSUE THREAD

**Issue by nchammas** [quodlibet/quodlibet#3134]
Steps to reproduce
------------------

Start up QuodLibet and play a song. The scrubber/progress bar doesn't show. Right-clicking on a song in the search results pane doesn't do anything.

Expected Output
---------------

The scrubber bar should show, and I should be able to jump to arbitrary points in the song. Right-clicking on a song in the results pane should show a context menu. (Right clicking actually worked the first few times I ran QuodLibet, and then stopped working. I don't understand why. Maybe because I am also occasionally running ExFalso too and there was some kind of bad interaction between the two?)

Actual Output
-------------

![screen shot 2019-02-17 at 3 53 32 pm](https://user-images.githubusercontent.com/1039369/52919154-417e6e00-32cd-11e9-9732-57f19a4a5cb3.png)

Test System
-----------

### Which version of Quod Libet?

4.2.1

### Which operating system 

macOS 10.14.3

### If it's audio-related, what back-end?

N/A

Additional Information
----------------------

Here's the log when I startup QuodLibet from the command line with `--debug`.

[quodlibet.log](https://github.com/quodlibet/quodlibet/files/2873420/quodlibet.log)

**Comment by declension** [comment]
Bear in mind there are two plugins that provide this feature. Presumably you can still use the small, pop-up one in the top left?
Which one(s) have you got enabled if any? 

FWIW it still needs a bit of clean-up / moving to core perhaps, but most people use the waveform one now I think. That:
1. Doesn't work for SoundCloud and streams 
2. Can take a long time to render on long tracks

**Comment by nchammas** [comment]
Ah, guess I made an incorrect assumption about the scrubber. Looks like there is no scrubber by default, correct? I enabled the "Waveform Seek Bar" plugin and it works fine. I would think that users expect some sort of scrubber to be enabled by default, but that's a discussion for another issue.

As for right-clicking on a song being broken, do you have any suggestions on what I should do to troubleshoot that?

**Comment by declension** [comment]
> Ah, guess I made an incorrect assumption about the scrubber. Looks like there is no scrubber by default, correct? I enabled the "Waveform Seek Bar" plugin and it works fine. 

Correct, and glad it's working now 

> I would think that users expect some sort of scrubber to be enabled by default, but that's a discussion for another issue.

Maybe, or maybe not even - it confirms what I've thought for a while actually :slightly_smiling_face: : 

> As for right-clicking on a song being broken, do you have any suggestions on what I should do to troubleshoot that?

Not sure without looking further, but please separate _that_ into another issue - it's definitely not related to the Scrubber and / or plugins
