### ISSUE TITLE
Does Quod Libet send my library info to YouTube/Google?

### ISSUE THREAD

**Issue by dorearendil** [quodlibet/quodlibet#3139]
Hi all,
I've made it a principle in my everyday life to hide as much info about my personal tastes and habits from GAFA :)
Which is part of the reason why I'm using Ubuntu as my main system currently.
Also, I never listen to music on YouTube, or Spotify -- only mp3 stored on my HD.

However, something weird just happened... Today, opening YouTube to search for something (not music), I found that the YouTube homepage is only recommending artists from my personal music library! This never happened before.
The only explanatory factor I can think of is that I installed Quod Libet 2 days ago. Is the program somehow connecting with YouTube to download cover art, or some such thing? If so, how to prevent this from happening?

**Comment by lazka** [comment]
Have you activated any plugins? We don't use any Youtube related APIs but there are plugins for fetching cover art/lastfm etc which might forward things to google one way or another.

**Comment by dorearendil** [comment]
I activated the "Download Cover Art" plugin yes... Too bad there isn't any info displayed regarding where the plugin gets the images from. Deactivated it now.
What I find scariest is that I was actually logged into my Gmail account when visiting YouTube -- now that I've logged out, no music videos are suggested. So it would mean that all my music library might have been automatically associated with my Google account! Arrrh

**Comment by lazka** [comment]
It uses discogs, last.fm or musicbrainz depending on which cover source plugins you have activated in addition to it.

**Comment by declension** [comment]
Hmm, definitely a bit concerning. Perhaps we should try to track down which service is (and how - surely these resources are fetched in a context unrelated to a user browser?)

**Comment by dorearendil** [comment]
![screenshot from 2019-02-24 21-26-23](https://user-images.githubusercontent.com/3090867/53304154-f5a66880-387a-11e9-9c78-0d452113ffcf.png)

The image above shows the plugin I activated...
I'm also quite confused as to how this process works -- as declension says, it's probably unrelated to the browser.
Another possibility, apart from the plugin: when I imported my music library into QL perhaps?

**Comment by declension** [comment]
I'm pretty confident this isn't a QL issue, as we don't have any Google or Youtube links or comms anywhere in the codebase.

Can we close this now?

**Comment by CreamyCookie** [comment]
Let's close it.
