### ISSUE TITLE
Drawing artifacts in the File System tree

### ISSUE THREAD

**Issue by bodqhrohro** [quodlibet/quodlibet#3140]
Steps to reproduce
------------------

Opened the File System view.

Expected Output
---------------

Stable output.

Actual Output
-------------

Artifacts on hovering: some parts of the list get drawn in other places.

Test System
-----------

### Which version of Quod Libet?
4.2.1

### Which operating system 
Debian Testing

### If it's audio-related, what back-end?
Nope.

Additional Information
----------------------

WM: Compiz
GTK+3 theme: OneStepPlat
Icon theme: buff-nipuna

![quodlibet_artifacts1](https://user-images.githubusercontent.com/2134486/53573559-6351dd80-3b76-11e9-83b7-66911be6a917.gif)

**Comment by bassstorm** [comment]
I experience the very same glitches on KDE.

**Comment by declension** [comment]
Ugh, this again - sounds a lot like #2541... _that_ one was upstream WM / DE bugs which got workarounds in QL, but not sure about this.

**Comment by lazka** [comment]
Afair it's a gtk bug that can be worked around in themes. We'd need to try fixing it in gtk upstream or get rid of list separators.

**Comment by xhc1** [comment]
similar  #2997

**Comment by bodqhrohro** [comment]
@xhc1 yup, adding
```
treeview.view.separator,
treeview.view.separator:hover {
    min-height: 1px;
}
```
to the theme fixes this issue.

**Comment by lazka** [comment]
I've proposed a fix upstream: https://gitlab.gnome.org/GNOME/gtk/merge_requests/614

**Comment by lazka** [comment]
Fixed upstream \o/
