### ISSUE TITLE
LADSPA Plugins Support

### ISSUE THREAD

**Issue by Jam3alay8** [quodlibet/quodlibet#3144]
Adding LADSPA Plugins Support
-------------------

> Quodlibet to offer an interface to enable the plugins

Benefits of this change
-----------------------

> The available plugins allows the listener to fine tune the sound to his/her satisfaction, and quodlibet becomes a more complete music listening choice.

Any issues this might cause
---------------------------

> I am not aware of performance issues while using the plugins (which I am currently using in another audio player)
>
> There is no need for migrations, as this simply routes sound through a set of audio effect subsystem.

**Comment by Zer0-** [comment]
I use pulseaudio with jack sink and a jack server to capture or process sound from any program. You can then use something like carla to host plugins.

**Comment by Jam3alay8** [comment]
Thanks, I was not aware of this possibility. I have never used jack, maybe I'll give it a try.

**Comment by Zer0-** [comment]
Yeah, check it out! I have `jack2Full` and `qjackctl` in my systemPackages. I start jack with `jack_control start` and then load the pulseaudio modules like this:

```
pactl load-module module-jack-source channels=2
pactl load-module module-jack-sink channels=2
```

If you then open up qjackctl and click "Connect" you should see your pulseaudio channels there. I also want to point out that there is an awesome project called [musnix](https://github.com/musnix/musnix) that will help you configure your system for very low latency if that's something you need down the line.

**Comment by Jam3alay8** [comment]
Great I'll give it a try.
