### ISSUE TITLE
Add Natural Sort Order to File System browser

### ISSUE THREAD

**Issue by alan12345678** [quodlibet/quodlibet#3145]
Hi there,

Now using Manjaro with XFCE. QL has been behaving wonderfully for the most part :)

Not sure if the following is by design, a bug, or me not fully understanding:

I tend to always use the File System browser in the main QL window. The ordering of certain artists or albums appears differently than in my regular file browser. Two examples

I have a series of compilation albums of a similar title, differentiated by having volume numbers e.g.
**Brazilectro 5**
**Brazilectro 6**
etc.

I actually own volumes 5 through 10 of this series. In Thunar the albums display (not surprisingly) from 5 up to 10 in correct numerical sequence. In QL's file system browser, **Brazilectro 10** appears first, followed by all others - presumably because they are single digits? If I pad the album numbers with a zero '05' etc. sure, but why should I have to do this?

Also, I have an (African) music artist's name that happens to start with **É** which is irregular sure, but again in Thunar is simply listed in the correct alphabetical sequence. In QL's file system browser, this artist name appears at the bottom of any alphabetical list!

Is this me? Is it a DE error? Or is this something I can fix in QL?

**Comment by CreamyCookie** [comment]
Yeah can confirm this happens. 

![filebrowser-sorting](https://user-images.githubusercontent.com/3063858/60107781-c4c23b80-9767-11e9-8f0c-09d221db799d.png)


>  Is it a DE error? 

Not an error, just how it's implemented. It's alphabetical sorting.

**Comment by declension** [comment]
See also #3499

**Comment by CreamyCookie** [comment]
Closing this for 3627 (linked above)
