### ISSUE TITLE
add "Quick play" option

### ISSUE THREAD

**Issue by xhc1** [quodlibet/quodlibet#3153]
managing large music database without touching query or playlist in search result when searching right song or duplicates etc

**Comment by frestr** [comment]
Can you be more elaborate on how this would work and what the benefits would be?

**Comment by xhc1** [comment]
maybe better to say "preview play" feauture can have benefits when query and playlist are managed and when some searched song is "uknown for this time" and can be played as "quick play" without touching query or some playlist or without creating new playlist only for this purpose

this is usefull when managing large database combined with searching
I started managing my music database with 20.000+ tracks, this feauture saves unnecessary clicks and time

**Comment by bassstorm** [comment]
My use case is simple (likely it's the same as xhc1's).
While listening to some playlist, I do library research or clean up, being interested in some vague items I give them a quick play to get an idea on next steps. Obviously I don't want to lose my queue or playlist.
However there's a simple workaround -- put your QL on pause, open needed album/folder on file managed via context menu and listen particular track of interest in another generic player (I prefer VLC).
"Quick play" feature is nice to have but such things could finally make QL a 1000-in-1 heavy weaponry :)

**Comment by CreamyCookie** [comment]
I think we already have this. You can enable `Ignore` and then it will not play anything from the queue.

![Untitled](https://user-images.githubusercontent.com/3063858/59949516-998fd180-9473-11e9-8a6d-15eb5c05af07.png)
