### ISSUE TITLE
drag & drop clears filtered tracks in playlist

### ISSUE THREAD

**Issue by xhc1** [quodlibet/quodlibet#3156]
Steps to reproduce
------------------
1. add some tracks into playlist
2. type some letters in Search field in playlist to make some filter (you can type whatever, result can be empty, doesnt matter what you type)
3. choose from main menu Browser -> open Browser -> Search Library
4. search for some track and drag @ drop into that playlist
5. now clear Search field in playlist

Expected Output
---------------
track will be part of whole playlist when Search field in playlist cleared

Actual Output
-------------
it clears all hidden (filtered) tracks in playlist when Search field cleared

### Which version of Quod Libet?
> 4.2.1

### Which operating system 
> fedora 28
xfce4

**Comment by frestr** [comment]
Thanks. We already have an issue for this (#2454, possibly #3083), so I'll close this one.
