### ISSUE TITLE
Played counter doesn't notice program shutdowns

### ISSUE THREAD

**Issue by kiritsuku** [quodlibet/quodlibet#3157]
The proposed change
-------------------

Right now, when a song is played, the played counter is not increased if song playing is stopped, the program gets exited and reopened. The song can be continued at the location where is was stopped but after switching to the next song once the song is finished the played counter stays at is.

Benefits of this change
-----------------------

For me this is useful for songs that are very long (multiple hours) and are actually song collections in one file. Often I stop playing these files and close the program afterwards, which means that the played counter sometimes stays at zero and when I add new songs, I have to manually skip these files if I want to hear only the new ones (those with zero plays).

Any issues this might cause
---------------------------

Probably none.

-----------------------
As a workaround, is there a way to manually increase the played counter?

**Comment by j39m** [comment]
IIRC, Quod Libet already ships by default with a [plugin to edit `#playcount` and `#skipcount`](https://github.com/quodlibet/quodlibet/blob/30293621f466cbc0076ed2db703702ef0234a853/quodlibet/quodlibet/ext/songsmenu/editplaycount.py) - I have it on my installation via Fedora 29.

Addendum: quitting in the middle of a song should also increment its `#skipcount`. If you know how to edit skips out of the library on disk, you can do that en masse for all songs you didn't intend to skip.

**Comment by kiritsuku** [comment]
The plugin works, thanks!

That plugin is good enough for me. No need to change the behavior of the program anymore. I'm closing this, you can reopen if you want.
