### ISSUE TITLE
"Open With Quod Libet" in File Manager spawns one process for every selected file.

### ISSUE THREAD

**Issue by will-ca** [quodlibet/quodlibet#3159]
Steps to reproduce
------------------

Select a large number of `.mp3` files in Nemo. (I did all 2000+ in my music library.)

[Right click] > "Open With" > "Quod Libet"

Expected Output
---------------

A single `quodlibet` process spawns, which processes the file list and displays it all, displays the deepest common directory, or displays the default music library.

Actual Output
-------------
Many, many `quodlibet` processes spawned. CPU usage instantly hit 100%, with enough processes that certain desktop UI elements and other windows became unresponsive. RAM usage escalated as quickly as disk I/O would allow. Only a single "Quod Libet" window was opened, however (albeit unresponsively).

I had to start rapidly running `pkill quod` to keep memory usage under control. Running `top` between each `pkill` showed that the number of `quodlibet` processes would very rapidly increase again each time. It may have stabilized at around a dozen or so. I didn't wait long enough to find out; memory use and CPU demand continued climbing regardless.

I finally stopped it by running `pkill nemo`. I'm not sure whether this behaviour was caused more by quirks in Quod Libet or Nemo; however, it is frankly completely insane and it doesn't happen with VLC, Musicbrainz, Kid3, Lollypop, Totem, Pogo, or EOG (which all handle opening a large set of files with no problem, or at least, don't drag down the rest of my software and hardware when they crash), so there's gotta be *something* that could be done differently.

Test System
-----------

### Which version of Quod Libet?
4.2.1

### Which operating system 
Fedora 29 w/ Cinnamon 4.0.8

### If it's desktop-related, what other application?
Nemo 4.0.6

**Comment by xhc1** [comment]
with systray icon allowed: for example 30 tracks enough, we can see duplicate systray icons growing up and then decreasing up to 1 systray icon

**Comment by frestr** [comment]
Thanks for the bug report!

It should only spawn one process after the fix in e80ccebfa027af7b306b8a2408bdd7be1a1c0272 (feel free to verify).

Still only the first selected file is played though, which deviates from what you describe as the expected behavior. This is the intended behavior though, as the song is sent directly to the player.

Feel free to make a new issue here on github if you think that should change too.
