### ISSUE TITLE
[Question] external access

### ISSUE THREAD

**Issue by w4grfw** [quodlibet/quodlibet#3165]
Hi,
I try to query the library:
This is working except that I can't access some tags like "~playlist" or "~format" (I guess that’s true for all internal tags). What am I missing?
```
import quodlibet.library
import quodlibet.config
config_file = os.path.join(quodlibet.get_user_dir(), "config")
quodlibet.config.init(filename=config_file)
songs_path =os.path.join(quodlibet.get_user_dir(), 'songs')
lib = quodlibet.library.init(songs_path)
music_list = lib.query(text=query)
```

**Comment by frestr** [comment]
Could you elaborate a bit on what exactly you're trying to do? I'm not sure if you mean accessing those tags in the query results or the query itself.

**Comment by w4grfw** [comment]
I mean the query itself. I want to get the results of queries like
`&(~playlists = "PLAYLIST", #(rating > RATING))`, `~format = "FORMAT"` or `&(~playlists = "PLAYLIST1, ~playlists != "PLAYLIST2")` but it seems the results are the whole library.
A query like `#(rating > RATING)` is working just fine.

**Comment by frestr** [comment]
I looked some more into this, and the problem is actually with the playlists not being initalized/loaded.

If you add the following to your example, it should work:

```python
from quodlibet.browsers.playlists import PlaylistsBrowser
...
b = PlaylistsBrowser.init(lib)
music_list = lib.query(text=query)
```

It would make sense to not have to depend on the playlists browser to do this initialization though.

**Comment by w4grfw** [comment]
Thank you, this works. At least the query-part.
But it seams, that the `~format`-Tag is only present in MP3-Files (but no `~codec`-field). A result from a query with `~format="MPEG-4"` has only a `~codec: "AAC LC"` field. A query like `~format="OGG Opus"` has neither a `~format` nor a `~codec`-field. The documentation (https://quodlibet.readthedocs.io/en/latest/guide/tags/internal_tags.html#string-tags) says `~format` is the File-Format (Container-Format?) and `~codec` is the used Audio-Codec. Why are the fields not present in all result-entries?

**Comment by frestr** [comment]
When accessing an internal tag you would normally do it like this: `song('~tag')`. That is, using a calling interface as opposed to the dictionary interface.

What is probably a bit confusing is that some format implementations fill their dictionary with certain internal tags, while others don't. So that's why you don't see the format or codec tag for some formats if you use the dictionary interface.

**Comment by w4grfw** [comment]
Ok, thank you.
I will look into it.
