### ISSUE TITLE
Operon set tag doesn't trigger Automatic Library Update

### ISSUE THREAD

**Issue by davidSchlosser** [quodlibet/quodlibet#3168]
Steps to reproduce
------------------
I have Quodlibet Album List browser open & playing. I used Operon to add a tag to file of the current playing song and confirm it's added by using Operon list. The Automatic Library Update plugin is enabled, and is working when I add new song files to my library directory.

Expected Output
---------------
The Quodlibet library should be updated, and the browser should display the new tag value. 

Actual Output
-------------
No change to browser display until I invoke the Rescan Songs plugin menu option

Test System
-----------

### Which version of Quod Libet?
4.3 development dfcf9455f

### Which operating system 
Ubuntu 16.04.6

Additional Information
----------------------

**Comment by frestr** [comment]
Thanks. Should work in master now.
