### ISSUE TITLE
Missing plugin doesn't seem to work

### ISSUE THREAD

**Issue by CreamyCookie** [quodlibet/quodlibet#3170]
Steps to reproduce
------------------
Maybe I'm missing something, but the [missing tag plugin](https://github.com/quodlibet/quodlibet/blob/master/quodlibet/quodlibet/ext/query/missing.py) doesn't seem to work.

For example

* `@(missing: ~#rating)`  returns no albums (might be technically true, since every track gets a default value, but still confusing, since the tag, e.g. POPM in mp3, is really missing)
* `@(missing: #lastplayed)` returns all albums

However, `@(missing:date)` works, so not all tags are affected.

Test System
-----------

### Which version of Quod Libet?
4.2.0

### Which operating system 
Kubuntu 18.04

**Comment by dcrossleyau** [comment]
I tested this, and the plugin does work nicely for me.

This is a new installation, so there are no ratings.

So `@(missing:~#rating)` shows all.

Then i added rating to a couple of songs. Then `!@(missing:~#rating)` does list the correct ones.

The `@(missing:~#lastplayed)` and `!@(missing:~#lastplayed)` similarly work as expected.

By the way, thanks for the brilliant plugin. It sure helps to tidy the library. For example, these have been helpful:
* `@(missing:album)`
* `&(@(missing:date), chillout)`
* `!@(missing:musicbrainz_albumid)`

**Comment by bassstorm** [comment]
I guess this issue is the same as #3046 (i.e. related to album view).

**Comment by CreamyCookie** [comment]
@bassstorm Thanks, that must be it. I'm also using the album view..

@dcrossleyau You were using a different browser, right?

Closing this one as a duplicate.

**Comment by dcrossleyau** [comment]
Yes, that was using "Paned browser".
