### ISSUE TITLE
I modified the Synchronized Lyrics plugin to support embbeded lyrics. [New Version!]

### ISSUE THREAD

**Issue by tralph3** [quodlibet/quodlibet#3173]
This is not an issue, rather a fix I made myself. As some of you may know, the Synchronized Lyrics plugin supports .lrc files only, not embbeded lyrics, so I went into the plugin source code and modified it to support the latter. If you need this, I'll provide a download link so you can replace it and get those sweet synced lyrics. Bare in mind, this modification removes support for .lrc files, is one or the other at the moment. I may go back at some point to make it support both, but this is where it stands right now.

To install it, drag and drop the file into "/usr/lib/python3/dist-packages/quodlibet/ext/events" and replace when prompted. Then, open Quod Libet and go into File>Plugins then scroll until you find "Synchronized Lyrics". You can make modifications as you wish here. Then, just play a song that has embbeded lyrics and they should display accordingly. If you skip the song, the you must wait for a new line to beggin for it to be displayed.
[LRC Support from embedded tags](https://github.com/quodlibet/quodlibet/files/3170809/synchronizedlyrics.py.zip)
[ELRC Support from embedded tags](https://github.com/quodlibet/quodlibet/files/3183570/synchronizedlyricsV2.py.zip)

EDIT: There was a line in the code that tried to import an external library. I removed it so it doesn't have
any external dependencies. It should work out of the box now. Sorry for the inconvenience.

EDIT 2: So I went back to code and finally made it possible for it to read ELRC tags. It will display word by word tho. My original intent was to make it so it displays the whole line and the ELRC tags change the color of the text. You can see ramnants of this if you go to plugin settings, you'll see a new option (does nothing). Anyway, I may try to accomplish my original view later.

NOTE: For the ELRC version, remove "V2" from the file name.

EDIT 3: Created a pull request, contains new version, check it out [here](https://github.com/quodlibet/quodlibet/pull/3182)

**Comment by frestr** [comment]
Thanks! Feel free to make a pull request if you want this to be integrated into master (it doesn't have to be fully complete before making the PR). Then we could also look at how to support both embedded and external lyrics.

**Comment by tralph3** [comment]
> 
> 
> Thanks! Feel free to make a pull request if you want this to be integrated into master (it doesn't have to be fully complete before making the PR). Then we could also look at how to support both embedded and external lyrics.

@frestr I edited the post with the link to the pull request. I'm needing a bit of help to finish this thing off once and for all. It's an objectively improved version at this point tho.
