### ISSUE TITLE
[Error] FaultHandlerCrash: Fatal Python error: Segmentation fault

### ISSUE THREAD

**Issue by schw1804** [quodlibet/quodlibet#3174]
* What did you try to do when the error occurred?

I was listening to music while doing something else (other open applications were Emacs, Terminal, and Google Chrome) and the computer froze. I closed the laptop lid to induce standby, and when the music stopped, I opened it again (and didn't have to log in, which seems like an Ubuntu security bug). The music started again for less than a second, and then the area where Quod Libet had been went black and the OS told me the program wasn't responding. I elected to wait rather than force quit, but Quod Libet crashed shortly thereafter anyway.

Error Details:
```
Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/quodlibet/errorreport/faulthandling.py", line 137, in raise_and_clear_error
    raise FaultHandlerCrash(text)

FaultHandlerCrash: Fatal Python error: Segmentation fault

Stack (most recent call first):
  File "/usr/lib/python2.7/dist-packages/quodlibet/_main.py", line 338 in run
  File "/usr/lib/python2.7/dist-packages/quodlibet/main.py", line 193 in main
  File "/usr/bin/quodlibet", line 14 in <module>


Version: 3.9.1
Python: 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
[GCC 7.3.0]
Platform: Linux-4.15.0-48-generic-x86_64-with-Ubuntu-18.04-bionic
```

**Comment by CreamyCookie** [comment]
Hmm.. the version you're using (3.9.1) is two years old, so the bug causing this might already have been fixed.  

https://github.com/quodlibet/quodlibet/releases

I'd recommend to update and report here if it happens again.

**Comment by schw1804** [comment]
I forgot I left this bug report. It's only happened once, so it wasn't a big problem anyway. I didn't even know my version was out of date, but I guess that's what I get for blindly installing the Ubuntu package.

**Comment by CreamyCookie** [comment]
Good to hear it hasn't come up again :)

I've also used the base repository included version for quite a while.. probably switched to a more recent one because of a feature or so.
