### ISSUE TITLE
macos: media keys not working after upgrade to 4.2.1

### ISSUE THREAD

**Issue by minusf** [quodlibet/quodlibet#3175]
After installing 4.2.1 media keys stoppped working on macos.
Going back to 4.1.0 media keys work again.

macos 10.14.5

**Comment by formaj** [comment]
It's a security thing
Open: Systems Preferences -> Security & Privacy -> Privacy-> Accessibility, see if quodlibet is listed and checked. That allows it to control the media keys.
<img width="215" alt="sc 2019-05-17 at 11 55 23 PM" src="https://user-images.githubusercontent.com/48781705/57964775-8d5aa680-7900-11e9-8941-43c2dfe6044a.png">
<img width="369" alt="sc 2019-05-18 at 12 05 31 AM" src="https://user-images.githubusercontent.com/48781705/57964782-b24f1980-7900-11e9-9f6c-9aee5ac5f8ab.png">

**Comment by minusf** [comment]
thanks for the clue stick. i didn't realize i have to re-add it and then also restart the app.  normally when the executable path doesnt change i skip that...
