### ISSUE TITLE
Bug sorting tracks without tracknumbers

### ISSUE THREAD

**Issue by dpitch40** [quodlibet/quodlibet#3179]
Steps to reproduce
------------------
Try sorting an album containing a mix of songs with/without tracknumbers by Artist or Album.

Expected Output
---------------
I would expect all songs in an album without tracknumbers to be sorted before all songs in the album with tracknumberd.

Actual Output
-------------
(See first screenshot below) The screenshot shows the ordering with a custom sort order, but the result is the same sorting on Album or Artist. It seems like the lack of a tracknumber is being considered equivalent to a tracknumber of 1 for the purposes of sorting, so the ordering of the tracks falls back to being determined by title instead. Changing the title of the tracknumber-less track to one alphabetically before that of the one with a tracknumber causes it to be sorted first.

Test System
-----------
### Which version of Quod Libet?
4.2.0, but it doesn't appear to have been fixed in 4.2.1.

### Which operating system 
Linux Mint 18.3

Additional Information
----------------------
[The incorrect sort order](https://i.imgur.com/Tzbxlqp.jpg)

As you can see, there is no extraneous metadata to muck things up; the tracks match on everything except title and tracknumber (or lack thereof).
[Metadata 1](https://i.imgur.com/inPzv4u.png)
[Metadata 2](https://i.imgur.com/31gEOrp.png)

**Comment by tralph3** [comment]
This should be an easy fix, the real hard part is gonna be to figure out where the hell on all of the files this is handled. If a dev would be so nice to just tell us...

**Comment by CreamyCookie** [comment]
Not sure, but [this](https://github.com/quodlibet/quodlibet/blob/ce5f3b1e9e277aaa285ddd118a45db8cf0773bfd/quodlibet/quodlibet/formats/_audio.py#L138) could be the place.

It seem like `1` is used as a default when there's no `track` tag, and so the only difference between the `sort key` of both elements is probably the title. Maybe the solution is to use `0` as the default value when there's no track tag.

**Comment by CreamyCookie** [comment]
![before after fix](https://user-images.githubusercontent.com/3063858/59974535-a284be00-95ad-11e9-9e68-715d1c42118f.png)
