### ISSUE TITLE
Add bitrate mode to song information (Variable, Constant, or other)

### ISSUE THREAD

**Issue by CreamyCookie** [quodlibet/quodlibet#3189]
The proposed change
-------------------
After the bitrate add whether this is a variable or constant bitrate, for example: `192 kbps (Variable)`

Oh.. there's also [average bitrate](https://en.wikipedia.org/wiki/Average_bitrate), but I don't think it's used much.

> Average bitrate can also refer to a form of variable bitrate (VBR) encoding in which the encoder will try to reach a target average bitrate or file size while allowing the bitrate to vary between different parts of the audio or video. As it is a form of variable bitrate, this allows more complex portions of the material to use more bits and less complex areas to use fewer bits. However, bitrate will not vary as much as in variable bitrate encoding.[1] At a given bitrate, VBR is usually higher quality than ABR, which is higher quality than CBR (constant bitrate).

Benefits of this change
-----------------------
This is useful since the bitrate *with* the mode reveals far more about the audio quality than without. For example, 192 kbps, Variable, mp3 sounds pretty great, but 192 kbps, Constant, mp3 often doesn't.

**Comment by lazka** [comment]
There is a "Encoding" column (`~encoding`) which includes similar information

**Comment by CreamyCookie** [comment]
Oh.. I see. It seems to be empty for CBR though, which is why I probably didn't see it.. lots of 320kbps encodes ^^

I could be wrong about this, but I feel like the term "Encoding" is a bit too general, at least I'd see something like `mp3, 320 kpbs, CBR` as the encoding, not just `CBR`.  So, I think it could be better to use "Bitrate mode" here, and making sure it's always below the bitrate. (Or in brackets after the bitrate.) Either way, I think "CBR" should be displayed if it's the case.

**Comment by lazka** [comment]
If CBR isn't shown it usually means that the file is missing that information.

**Comment by CreamyCookie** [comment]
Interesting, I didn't know that it could just not have that information. I would have thought that the mp3 (and other) standards would basically require this.

And I see I was wrong about "Encoding" since it [can include a lot more information](https://github.com/quodlibet/quodlibet/blob/30293621f466cbc0076ed2db703702ef0234a853/quodlibet/quodlibet/formats/mp3.py#L29) than just the bitrate mode.

Closing this.

**Comment by lazka** [comment]
> Interesting, I didn't know that it could just not have that information. I would have thought that the mp3 standard (and others) would basically require this. Good to know!

It's not required for playback so it's not always included in the header (IIRC newer lame versions always include it). We could detect it by parsing the whole file and see if the block sizes vary, but that would slow down the import.
