### ISSUE TITLE
Ignore the character "-" on search

### ISSUE THREAD

**Issue by DonRichie** [quodlibet/quodlibet#3198]
The proposed change
-------------------
On any search input fields ignore the character "-" during search.

Benefits of this change
-----------------------
**1.** 
Most if not any music application I know ignores the "-" char during search. This makes it possible to search a song like this: `<Artist> - <Songname>`. 

In my case I am copy pasting very often. Therefore I need to manually remove the "-" sign every single time, which starts to annoy me enough to write this feature request.

**2.** 
The proposed change also prevents users from getting search results not matching the expectation.

Lets say I search `<Artist> - <Songname>`.

The results are:
`<Artist>, <Songname> - Radio Edit`
`<Artist>, <Songname> - Club Edit`

I get all results containing "-" somewhere in the text itself. 

But I wanted to find the original song. This is annoying since it requires another search. I have a huge library, this every time takes a few seconds.

Any issues this might cause
---------------------------
Don't see any.
Usability isn't decreased since this is the expected behaviour in my opinion.

**Comment by blimmo** [comment]
Perhaps we should have an "ignored characters" field in the search settings, possibly defaulting to containing just "-"? This would allow customisation if others are using a different separator, disabling it by removing all of the characters and also serve somewhat as documentation for those who aren't expecting this behaviour (me included).
