### ISSUE TITLE
macOS: QL does not recognize a new audio output device

### ISSUE THREAD

**Issue by chrisresnikrakuten** [quodlibet/quodlibet#3210]
macOS 10.14.5 (latest patches installed)
QL 4.2.1
Internal Speakers <---> Jabra EVOLVE 20 on USBC-C adapter

how to reproduce:
Start QL when Internal Speakers are the sound output device and start playing music.
Plug in the Jabra EVOLVE 20 on USBC-C adapter and check in System Preferences  -> Sound -> Output that Jabra is selected as device for sound output

what happens:
QL keeps on playing music through the Internal Speakers

what I expect:
QL should continue playing music through the selected Sound Output device

Reproducible:
Yes (every time)

**Comment by chrisresnikrakuten** [comment]
Just  re-checked, issue also  exists on quodLibet 4.3.0

**Comment by lazka** [comment]
thanks

**Comment by marians** [comment]
I can confirm this problem for macOS BIg Sur v11.1.

**Comment by declension** [comment]
Closing in favour of #2771
