### ISSUE TITLE
Documentation contains dead link

### ISSUE THREAD

**Issue by pdscti** [quodlibet/quodlibet#3213]
The instructions in https://quodlibet.readthedocs.io/en/latest/development/devenv.html for setting up a new development environment on OSX include instructions to download the latest version from https://github.com/quodlibet/quodlibet/releases/download/latest/QuodLibet-latest.dmg. This goes to a 404 and no release of this name exists.

Should this be a link to https://github.com/quodlibet/quodlibet/releases/latest with instructions to download the latest .dmg release?

**Comment by declension** [comment]
Hmm, yeah that's definitely a 404 still. @lazka what's the right release link here?

**Comment by lazka** [comment]
https://github.com/quodlibet/quodlibet/releases/download/ci/QuodLibet-latest.dmg

I had to change that tag away from "latest" because it exposed a bug in readthedocs.
