### ISSUE TITLE
Fn key not working after debian 10 buster dist-upgrade

### ISSUE THREAD

**Issue by petitminion** [quodlibet/quodlibet#3220]
hey !
I just updgraded to debian 10 from debian 9. While in strech the shortcup fn+f10or11or12 worked perfectly to stop or switch song while inside or outside of quod libet. 

Now it doesn't work :'( 

ps : the short cut fn=f10etc work fine with others softtware. 
ps : I don't know how to debug this, where to fin logs :s

**Comment by lazka** [comment]
Doesn't the meaning of "fn+X" depend on your keyboard? What key/function should it trigger?

**Comment by petitminion** [comment]
I'm using a lenovo thinkpad w530. 
The fn-x key should allow to change song and stop them (witch it do with vlc for exemple).

I don't know how to find more info about this issue :s

**Comment by lazka** [comment]
ok, so multimedia keys I guess. Does enabling the "MPRIS" plugin in quodlibet help?

**Comment by petitminion** [comment]
Yes ! Thx :)
