### ISSUE TITLE
TXXX frames are normalized to lowercase but that conflicts with replaygain spec

### ISSUE THREAD

**Issue by a-vrma** [quodlibet/quodlibet#3228]
Steps to reproduce
------------------

Scan example.mp3 with `r128gain` (a minimal and standards-compliant Replaygain tagger). If you run `mutagen-inspect` on the resulting file you will see `TXXX=REPLAYGAIN_*_GAIN` and `TXXX=REPLAYGAIN_*_PEAK`. According to the [spec](https://wiki.hydrogenaud.io/index.php?title=ReplayGain_2.0_specification#ID3v2) this is correct. The case of the tag matters. However, when I edit example.mp3 with Ex Falso and save, the TXXX replaygain tags have been converted to lowercase. A decent amount of players on Linux recognize this but some do not. music on console, GoneMad Music Player are two examples.

Expected Output
---------------

I would expect TXXX frames in id3v2 to not be lowercased. I don't really see the point in doing this as no other tag editor or music player considers TXXX frames to be case insensitive. It is best to not mess with the user's tags unless they explicitly ask for it.

Test System
-----------

### Which version of Quod Libet?

Quod Libet 4.2.1
Ex Falso 4.2.1

### Which operating system 

Arch Linux

**Comment by declension** [comment]
Thanks. Technically you could argue we _always_ mess with user's tags, via the normal load / save within Mutagen and QL (this is probably true of most systems actually).

But that aside, agree that it looks like capitalising this is a good quick win for compatibility :+1:
