### ISSUE TITLE
"Edit Embedded Images" Plugin Interface Bug

### ISSUE THREAD

**Issue by Beinsezii** [quodlibet/quodlibet#3230]
The drop-down in the "Edit Embedded Images" plugin doesn't reserve space for its contents resulting in a tiny 0-height box
![Screenshot in i3](https://user-images.githubusercontent.com/39478211/61999322-4103b380-b073-11e9-877d-9cd3ab686a50.png)
The other two or three plugins I use work fine.

I created an issue despite the existence of #2187 because it's very old and marked as "Wayland", whereas this problem's recent (~few months old at worst) and I use X11.

Tested on 4.2.1, 4.1.0, and latest git. Issue appeared without a quodlibet update, probably GTK or something. I use the plugin only every couple months, so I can't pinpoint an exact start date.
Display is nvidia proprietary with X11/i3.

**Comment by Mc-Seam** [comment]
I experience same thing. Debian testing 64-bit, Quodlibet 4.2.1, GTK 3.24 (libgtk-3-0:amd64                      3.24.10-1). Bug appeared several weeks ago, for a pity cannot tell exact time or event (update). 

Tried to remove Quodlibet and all config files and reinstall again - bug still exists.

I have another computer with Debian testing - there is no such bug there. System on both computers is being updated more or less daily.

**Comment by mshmm** [comment]
Similar issue here (Kubuntu 19.04 and quodlibet 4.2.1). I get what looks like a 90 degrees rotated box - the icons and first two letters of "Remove" and "Embed" are visible, with lots of blank space below. It's usable for me, but odd that only this menu is affected.

**Comment by BatmansGehilfe** [comment]
Similar here - but its worse on xfce than on i3. Its almost indiscernible on xfce while on i3 I have a smiliar result to @mshmm's.

**Comment by declension** [comment]
This should now be fixed as of #3303 .

Please check and re-open if the problem persists..

**Comment by Mc-Seam** [comment]
Debian testing (updated daily)

libgtk-3-0:amd64  3.24.14-1    amd64        GTK graphical user interface library
libgtk2.0-0:amd64 2.24.32-4    amd64        GTK graphical user interface library - old version

quodlibet/testing,now 4.2.1-1 all

Bug still exists. And only in "Edit embedded images" menu. Other menus with "extensions" work fine. Looks like bug exist in any (or most) GTK+ 3 theme. Definitely I did not check them all, but the only GTK+ theme that shows no problem is Albatross (AFAIR it is GTK+ 2). But it looks terrific :)

If any additional info required - please tell what exactly.



![42](https://user-images.githubusercontent.com/54420796/78667920-76d78800-78e2-11ea-95b7-d57c9f29acb2.png)

![18](https://user-images.githubusercontent.com/54420796/78667935-7a6b0f00-78e2-11ea-862a-39bb936bfcdc.png)

![12](https://user-images.githubusercontent.com/54420796/78668245-02e9af80-78e3-11ea-8c5b-c872e6395126.png)

**Comment by declension** [comment]
@Mc-Seam Thanks, but `4.2.1` is before the fix. Please test [`4.3.0`](https://github.com/quodlibet/quodlibet/releases/tag/release-4.3.0) or newer

**Comment by Mc-Seam** [comment]
Sorry. 4.2.1 is the newest we have here in Debian testing. Sorry again, but I did not realize we are two years back in time :-(
