### ISSUE TITLE
Move root quodlibet/ to src/

### ISSUE THREAD

**Issue by declension** [quodlibet/quodlibet#3238]
The proposed change
-------------------

The root-level `quodlibet/` directory is renamed to `src/`. 
Background:
### Currently 
```
├── flatpak
│   ├── flathub-shared-modules
│   ├── flatpak-builder-tools
│   └── patches
├── osx_bundle
│   ├── misc
│   └── modulesets
├── quodlibet
│   ├── data
│   ├── docs
│   ├── gdist
│   ├── po
│   ├── quodlibet
│   └── tests
├── radio_crawler
├── release_db
└── win_installer
    └── misc
```
### After
```
.
├── flatpak
│   ├── flathub-shared-modules
│   ├── flatpak-builder-tools
│   └── patches
├── osx_bundle
│   ├── misc
│   └── modulesets
├── src
│   ├── data
│   ├── docs
│   ├── gdist
│   ├── po
│   ├── quodlibet
│   └── tests
├── radio_crawler
├── release_db
└── win_installer
    └── misc
```

Benefits of this change
-----------------------
Developers only really.
It's pretty weird explaining why most files will end up under `.../quodlibet/quodlibet/quodlibet/`
Most Python libraries choose either [packages at the root directory level](https://docs.python-guide.org/writing/structure/#it-s-important) or, less often, one level in, at `src/` (e.g. [pytest](https://github.com/pytest-dev/pytest)). The latter is perhaps more familiar to Java and other developers.

Sticking to _one_ of these would help consistency for new (and existing!) Python developers.
QL is complex and non-Pythony enough in places to justify the current extra level of nesting, IMO - leaving the second as the obvious option.

Any issues this might cause
---------------------------
Lots, mainly build / `setup.py`, but most / all should come out in development. I can't _see_ any downstream problems immediately, though raising this to get feedback around these aspects especially (e.g. Linux packagers)

Thanks

**Comment by CreamyCookie** [comment]
I also think this makes sense (unless there are reasons I'm unaware of). It has always been a bit confusing when traversing the file tree.

**Comment by lazka** [comment]
What about moving quodlibet to the root and move all the misc/installer stuff into a subdirectory there?

**Comment by declension** [comment]
@lazka that's nice too and slightly more Pythonic / traditional

**Comment by lazka** [comment]
I have a branch with my proposed change here: https://github.com/quodlibet/quodlibet/tree/move-root

Any ideas/objections?

**Comment by CreamyCookie** [comment]
@lazka `misc` seems a bit unspecific.. How about something like `release` or `build`?

**Comment by lazka** [comment]
"build" is already taken by setuptools, and we might want to move more things there in the future. Ideally I'd want this to be "things in the repo but not included in the tarball"

**Comment by CreamyCookie** [comment]
Oh right.. I felt like something was wrong about `build`..  And `release`? Some other (probably bad) suggestions: `buildmisc`, `build-data-and-scripts`, `release-misc`, `release-data-and-scripts`, `make-build`, `build-related`, `build-utils`. I mean `misc` is probably fine, but maybe we should use this opportunity to remove the (minor) ambiguity / unclarity. 

> we might want to move more things there in the future

Into `misc` or `build`?

**Comment by lazka** [comment]
Maybe with a "dev-" prefix? `dev-utils`, `dev-scripts`, `dev-utils`?

**Comment by lazka** [comment]
I guess we could split things up into two directories, like build-tools, dev-tools. naming things.. argh..

**Comment by CreamyCookie** [comment]
Agreed.. I always struggle with naming. One wants to be concise without being vague. 

> `dev-utils`

That seems okayish.. At first I thought `flatpak` doesn't fit quite into `utils` but it also contains `flatpak-builder-tools` so it seems fine.

**Comment by lazka** [comment]
pushed to master. thanks!
