### ISSUE TITLE
Double track entries in the "Album List" view.

### ISSUE THREAD

**Issue by ZaxonXP** [quodlibet/quodlibet#3248]
OS: Debian 10
QL: 4.2.1

Noticed that for some of the albums I have the same tracks displayed twice. Tried to rebuild a library, but this did not help. Any suggestions how to fix this?

Please also guide me which logs should be useful for you to analyze the issue (and info where to find them).

Kind regards,
Piotr

**Comment by declension** [comment]
You can run from the command line with `--debug` for more logging.

For duplicate tracks, it's often symlinks. Try adding as `~filename` column to investigate.

**Comment by ZaxonXP** [comment]
Strange. After I rebooted laptop and run the `quodlibet` again the problem was not there anymore.
But thanks for the suggestions.
