### ISSUE TITLE
Not all audio channels playing.

### ISSUE THREAD

**Issue by tuessetr** [quodlibet/quodlibet#3252]
Steps to reproduce
------------------
Play 6 channels audio file (vorbis, flac).
Default settings.

Expected Output
---------------
All 6 channels must be played.

Actual Output
-------------
Only 2 channels are played (front left and front right).
With VLC (default settings) i hear all 6 channels (same audio files).

Test System
-----------

### Which version of Quod Libet?
4.2.1

### Which operating system 
Win7

### If it's audio-related, what back-end?
Default for Win7 build.

**Comment by declension** [comment]
Can you test with some other `gstreamer`-based audio apps?

**Comment by tuessetr** [comment]
Yes, Clememtine and Songbird - only 2 channels...

**Comment by declension** [comment]
Thanks, nothing much we can do here if gstreamer doesn't support / want to play them in multi-channel, but please re-open if any workarounds found.
