### ISSUE TITLE
File locations to run on Windows and Linux

### ISSUE THREAD

**Issue by Andy3142** [quodlibet/quodlibet#3253]
Steps to reproduce
------------------

Expected Output
---------------

Actual Output
-------------

Test System
-----------

### If it's audio-related, what back-end?

Additional Information
----------------------

**Comment by Andy3142** [comment]
This is a request for help not a bug.

I want to to run identical  copies of QL on a Windows 10 and on a Lubuntu machine.   Is there a simple way to achieve that?

The actual library of mp3 files doesn't change much and  will be easy to keep the same on both machines. The problem is to sync the internal QL data of tags, rankings and playlists etc

An obvious way to do this would be to locate the QL files either in Dropbox or on a USB drive which would be transferred between the machines. 

 In linux it looks OK, per the environment variable QUODLIBET_USERDIR. In Windows the FAQ says:

"On Windows, it will be in your user’s AppData folder under Quod Libet (except portable builds)."

My questions are: 

What do I need to change in the Win 10 registry to make that eg Dropbox instead of AppData? 
Also, has anyone done this and is there any reason it can't be done? Is there any better way to run on linux/Windows?

Many thanks

Andy

**Comment by frestr** [comment]
From Gitter:
> QUODLIBET_USERDIR works on Windows too I think. But either way, the library is different on Windows/Linux, so sharing is not possible.
