### ISSUE TITLE
Tracklist custom column headers reset when you re-open preferences

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#326]
Original [issue 326](https://code.google.com/p/quodlibet/issues/detail?id=326) created by harrisonchen on 2009-10-09T22:52:17.000Z:

If I have a lot of custom headers I want in the tracklist, I put them down
under custom.  However, this doesn't give me much freedom in the ordering
for the tags that have check boxes, so I usually uncheck all of them and
manually stick them in the &quot;custom&quot; box.  However, when I close the
preferences window and re-open them, all the ones I put down in custom that
have checkboxes disappear and the checkboxes are checked again.  Thus, if I
apply the changes, the ordering will mess up again.

Here's an example.  I have a custom tag called &quot;work&quot;.  I want it to
display the work after the track number and before the title.  So, I
uncheck all the boxes and put:
tracknumber work title album ~people ~length
in custom.  Then I apply it, and close the preferencse window.  WHen I open
it up, I see that &quot;Title&quot;, &quot;Album&quot; and &quot;Length&quot; are checked, and in custom,
I have:
tracknumber work title album ~people

In general, I think the whole interface could be improved to be more like
the paned browser preferences window, where you can clearly change the
ordering and there are still pre-set options for the lightweight user,
since the current interface doesn't really give an option to re-order the
columns other than unchecking them all and doing it all under &quot;custom&quot;

One idea would be to make an option to &quot;disable&quot; items in the list, rather
than remove them, and have the usual tags (artist, album, title) in the
list unremovable.  This way, people can disable them, but re-enable them
later without having to remember the exact tag name.  Just an idea.

**Comment by bassstorm** [comment]
> How about drag-to-reorder (as it is now, but fixed so that it remembers the order when going back to prefs)?

Yes, works for me.
IMO the original use case is covered as of now.
@CreamyCookie @declension what do you think guys?

**Comment by CreamyCookie** [comment]
@bassstorm Thanks for checking.
