### ISSUE TITLE
Internal String Tag: ~last_modified

### ISSUE THREAD

**Issue by vestingz** [quodlibet/quodlibet#3260]
The proposed change
-------------------
Just started using QL and really loving its versatility :) I would love to see one specific internal string tag added: ~last_modified, which would contain the date and time the respective file has been last modified (like here: https://wiki.hydrogenaud.io/index.php?title=Foobar2000:Title_Formatting_Reference#.25last_modified.25)
Please excuse me if this is already possible in QL and close this ticket then.

Benefits of this change
-----------------------
I always used this special field in fb2k to generate a dynamic playlist with all the new files getting added to the collection. Very handy to keep a bigger collection in control.

Any issues this might cause
---------------------------
I am not aware of any issues that this change might cause, especially because a number of internal string tags already rely on filesystem metadata.

**Comment by davidSchlosser** [comment]
One can use the 'added' tag to search for recently added tracks as in #(added < 1 day)

**Comment by vestingz** [comment]
> One can use the 'added' tag to search for recently added tracks as in #(added < 1 day)

Yes. But I am only re-scanning my library every now and then, because it is just too big to scan it on start-up. And then I end up with hundreds of files added on a specific date while sorting by filesystem date would be much more differentiated.

**Comment by declension** [comment]
Good news - this already exists: `~#mtime`, or better known as _modified_, under _Date Headers_.

Please re-open if this doesn't solve your use case.
