### ISSUE TITLE
search by filename

### ISSUE THREAD

**Issue by yota-code** [quodlibet/quodlibet#3263]
Steps to reproduce
------------------
I loaded a folder containing some .mp3 files with incomplete tags (title was missing from id3) but the filename itself was the title

Expected Output
---------------
I expected to be able to find them by typing a part of the filename into the search bar...

Actual Output
-------------
Nothing happened, blank result !

Test System
-----------
### Which version of Quod Libet?
4.2.1

### Which operating system 
Ubuntu 19.04

Additional Information
----------------------
I attached one track... Perhaps it's due to something else
[05 - Kindness.zip](https://github.com/quodlibet/quodlibet/files/3704381/05.-.Kindness.zip)

**Comment by frestr** [comment]
The search bar doesn't consider filenames by default (see [docs](https://quodlibet.readthedocs.io/en/latest/guide/searching.html#searching-your-library)).

You can do this explicitly with a query like this: `filename=/your_filename/`

Alternatively, you can enable `Filename` as one of your songlist headers, which will make the search bar consider the filename too when searching.
