### ISSUE TITLE
Fingerprint lookup only returns unkown

### ISSUE THREAD

**Issue by ApolloLV** [quodlibet/quodlibet#3269]
Steps to reproduce
------------------

I tried to look up the tags for some new songs with the fingerprint lookup plugin.
Now I tried it for some old songs I am sure are in the database (for example musicbrainz track-id edae59f3-bc68-4751-a3ac-e5bc33f3f33a, which the acoustid.org API returns is known).

Expected Output
---------------

The tags should appear in the preview window and the status column should display a success status.

Actual Output
-------------

The tags do not appear for any song, only "unknown" is shown in the status column

Test System
-----------

### Which version of Quod Libet?

4.2.1
### Which operating system 

Archlinux, updates installed

Additional Information
----------------------

I do not know how to gather plugin logs, there's nothing in the terminal output when I use the plugin.

**Comment by phw** [comment]
This likely was related to issues AcoustID was having recently. The short story is something like AcoustID experienced heavy load, then got transferred to new infrastructure. As I'm writing it the current status is, as far as I understand, that AcoustID is in the process of getting migrated to new infrastructure and while this is happening import of new fingerprints has been put on hold.

For details see:
- https://status.acoustid.org/
- https://community.metabrainz.org/t/unable-to-unlink-an-acoustid/449028/7 (and related discussions)

**Comment by ApolloLV** [comment]
Ah, I was unaware of their issues.
I propose to wait until they have sorted out the issue and investigate if the problem persists.

**Comment by RankoKohime** [comment]
At this time, AcousticID reports their website is fully functional, yet the problem persists for Ex Falso, fingerprint lookup still returns unknown.  I ran Ex Falso via the terminal with --debug, but it seems the fingerprint plugin doesn't produce ANY output.  (I see messages about selecting files, then nothing else until I do something outside the AcousticidSearch window.

I'm running 4.2.1-2 on from the repo on Manjaro.

**Comment by ApolloLV** [comment]
The problem persists in Quodlibet as well.

**Comment by johnfoxii** [comment]
I am also having the same issue. I was not using exfalso until reading this post. It fits the need to quickly lookup/ edit tags. 
quodlibet and now exfalso are invaluable tools - nothing does lookup as quickly at these programs and I have been through dozens. Thank you 
executing exfalso-cmd.exe --debug 
shows  

> ModuleScanner.rescan: Rescanning done: 0 added, 0 removed, 15 error(s)

But I did not know how or where to find what these errors are.
the output also shows 

> PluginManager.enable: Enable 'AcoustidSearch'

So I assume the module is loading correctly
So I try a lookup but there isn't any output whether it actually attempted to process. So I assumed it did.
Digging in a bit deeper I found the folder 

> \data\lib\python3.7\site-packages\quodlibet\ext\songsmenu\fingerprint

within the folder the was acoustid.py and within this program there is 

> APP_KEY = 

The section looks like the below.
I was thinking that when acoustid.org migrated their servers and data they could have scrubbed old accounts or something along those lines. But I  am at best a novice at this. 
>Is there anyone who can lend a hand with debugging AcoustidSubmission section of code and/or shed some light on the api key?

I guess I could run something like Wireshark or MS message analyzer to see what's going on.

> from acoustid.py

```
from quodlibet.util.urllib import urlopen, Request
from .util import get_api_key, GateKeeper

APP_KEY = "#######"
gatekeeper = GateKeeper(requests_per_sec=3)

class AcoustidSubmissionThread(threading.Thread):
    URL = "https://api.acoustid.org/v2/submit"
    SONGS_PER_SUBMISSION = 50
    TIMEOUT = 10.0

```

**Comment by ApolloLV** [comment]
We really should add error detection code that gives a more specific error than "unknown" in case the API can not be reached or the API key is rejected.

**Comment by lazka** [comment]
I've pushed a small fix to master. The problem was that the JSON response from acoustid has changed slightly.

**Comment by declension** [comment]
Can we close this then?

**Comment by lazka** [comment]
yeah
