### ISSUE TITLE
Azure pipelines failed according to the readme

### ISSUE THREAD

**Issue by matkoniecz** [quodlibet/quodlibet#3279]
Steps to reproduce
------------------
Looked at https://github.com/quodlibet/quodlibet

Expected Output
---------------
Build is succeding

Actual Output
-------------
Azure Pipelines failed badge at the bottom

Test System
-----------

### If it's audio-related, what back-end?

Additional Information
----------------------

**Comment by frestr** [comment]
Thanks. The particular test failing: [link](https://dev.azure.com/quodlibet/quodlibet/_build/results?buildId=615&view=ms.vss-test-web.build-test-results-tab&runId=1002364&resultId=103003&paneView=debug)

That test is a bit flaky, but it did work in azure before. So either something changed in azure, or it was a spurious fail.

@lazka Do you know if it's possible to rerun the tests in azure pipelines like in CirlceCI?

**Comment by lazka** [comment]
I think it started when we updated to Python 3.8 in MSYS2, but I haven't looked into why it's failing now.

> @lazka Do you know if it's possible to rerun the tests in azure pipelines like in CirlceCI?

I think there is another way to integrate azure-pipelines into github which gives you a rerun button. I'll have a look.

**Comment by frestr** [comment]
Fixed with #3282 and d7c424ad42c9a198837099bd95f69483bb2656d7.

**Comment by lazka** [comment]
I've switched azure-pipelines from webhooks to "github apps".
