### ISSUE TITLE
Internet radio needs text/html decoder

### ISSUE THREAD

**Issue by gahisee** [quodlibet/quodlibet#3280]
I'm trying to add a radio station such as the following tunein url:
https://tunein.com/radio/WUOT-919-s23408/
Libet shows an error message about Gstremer needing a text/html decoder.
How and where do I get this plugin?
thank you for your help...

UPDATE:
ok, i see that above url is returning a html page, not a true streaming url.
so the real question is:
where do proper streaming url's exist?
i suppose each radio station determines its own?

**Comment by declension** [comment]
Yes, you'll need the actual stream URL. There's no way of programmatically determining the stream URL from the HTML (with 100% reliability anyway).

Often by hand you can look at the network tab in your browser tools and take the URL for audio media from there once playing - but there are many caveats to that of course.
