### ISSUE TITLE
Iradio: UI freezes until connection times out

### ISSUE THREAD

**Issue by gahisee** [quodlibet/quodlibet#3281]
Steps to reproduce
------------------
add the following url for a new radio station:
http://146.186.221.181:8000/listen.pls

whatever audio that was playing continued to play;
however Libet locks up, no response to any input.
had to be terminated. 

### Which version of Quod Libet?
4.2.1

### Which operating system 
kubuntu 19.10

**Comment by declension** [comment]
It does _eventually_ timeout and recover

![Screenshot from 2020-02-10 20-30-08](https://user-images.githubusercontent.com/3322808/74187297-2f1ae400-4c44-11ea-835d-87e697087df7.png)

But yes, this is very bad UX here so I suggest
 * timeout is reduced a lot
 * Adding is done in a separate thread or as a GTK-style idle task
 * Some kind of "working" indicator would be nice but probably out of scope for this as a fix
