### ISSUE TITLE
Adding track via songsmenu doesn't update Playlist Browser songs list

### ISSUE THREAD

**Issue by j1warren** [quodlibet/quodlibet#3283]
Steps to reproduce
------------------
When you add a track(s) to playlist (via Right Click > Playlists > Selected playlist) from Paned Browser while main window is displaying that playlist (Playlist view) the playlist is not refreshed. One has to put something to filter and clear it, to refresh the playlist and see the newly added track(s).

Expected Output
---------------
Right click menu should initiate refresh on a Playlist window, just like dragging the track onto playlist name does.

**Comment by declension** [comment]
Note the _browser row_ (i.e. the playlist with its name / info on the left) _is_ updated via the `changed` signal, but the _songslist_ is not here.
