### ISSUE TITLE
4.2.1 for Ubuntu Bionic PPA

### ISSUE THREAD

**Issue by mshmm** [quodlibet/quodlibet#3286]
Any chance of the 4.2.1 release being backported in the PPA for Ubuntu Bionic LTS? As well as being the current Ubuntu LTS it's also the base for Linux Mint 19.x, with 19.3 about to be released.

**Comment by lazka** [comment]
I'll look into it.

**Comment by lazka** [comment]
should work now, thanks for the reminder.

**Comment by mshmm** [comment]
Updated successfully from the PPA - thank you :)
