### ISSUE TITLE
allow users to control metadata padding

### ISSUE THREAD

**Issue by vede1** [quodlibet/quodlibet#3288]
The proposed change
-------------------
Users should be able to control how metadata padding is applied to files after changing tags, possibly through a plugin or as a core config setting. The setting in question is the ability to disable padding reductions, https://github.com/quodlibet/mutagen/blob/4ff09f34c58058263d682bed06cecf2e70fb8808/mutagen/_tags.py#L57

Benefits of this change
-----------------------
Reducing extra padding requires changes to the structure of the metadata and therefore causes a full file rewrite. If padding is not reduced, then the file is not rewritten, which is the main benefit for filesystem with reflink support. Extra padding is mostly an effect of removing the PICTURE block (_metaflac --remove --block-type=PICTURE *.flac_) prior to tagging. If the space freed by the picture block together with original padding exceeds the upper bound of padding calculated by mutagen, then the padding will get reduced, which will defeat deduplication with reflinks. IMO for some users saving 256KiB is not worth a full file rewrite. For reference, _metaflac_ does not reduce padding by default.

Any issues this might cause
---------------------------
There are no negatives except for leaving files with padding of the size of their embedded covers (default _metaflac_ behavior).

**Comment by declension** [comment]
@vede1 this sounds like one for https://github.com/quodlibet/mutagen/issues

**Comment by vede1** [comment]
I am closing this issue because for me it was solved by using a custom tagger that knows how to shrink files without rewriting them (linux only).
