### ISSUE TITLE
Searching in mp3 files without title tag can be confusing

### ISSUE THREAD

**Issue by porteous42** [quodlibet/quodlibet#3289]
I just tried Quod Libet 4.2.1 for the first time. I added a folder for tunes that I was using in iTunes.
I tried searching for titlles that I saw on the display, but it could not find them. This baffled me, until I realized these MP3 files were missing the "Title" tag, so Itunes just used the filename as the title (Swinsian does the same thing). I would suggets that when searching for songs that are missing the Title tag, it would use whatever is displayed in the songlist... 
That's just a suggsetion.. I have been impressed with the software so far and look forward to exploring the more advanced search features!

**Comment by GitOffMyBack** [comment]
If an MP3 file is missing all tags, then the software will not play, load, etc. For ease of use, there could be a way to add non-tagged MP3 files which would be prompted to add such tags.

**Comment by FerdiScholten** [comment]
The "File system" browser does behave like this, when a file has no tags, the filename (without extension) is shown.
You can also search using _filename=_ and it will display all files that contain the part after the =

**Comment by declension** [comment]
@porteous42 could you add a screenshot? AFAICT this should be supported already

e.g. here's QL finding a (pretty much) untagged mp3, note `title` displaying the filename, the `~filename` itself, and the search matching with on this: 

![Uploading Screenshot from 2020-02-09 20-31-03.png…]()
