### ISSUE TITLE
Embed Images plugin unuseable

### ISSUE THREAD

**Issue by FerdiScholten** [quodlibet/quodlibet#3291]
Steps to reproduce
------------------
I was trying to embed an image into a .flac file but the menu of the plugin is not displayed correctly, only a very small box is on screen.

Expected Output
---------------
The menu is displayed in a box that can display all choices. (like other plugins)mtp://SAMSUNG_SAMSUNG_Android_3300de6ccd7283d9/Card/DCIM/Camera/20191227_143050.jpg

Actual Output
-------------
The box to hold the submenu can only display at most half of the height of 1 character..

Test System
-----------

### Which version of Quod Libet?
4.2.1

### Which operating system 
Ubuntu Linux 19.10

### If it's audio-related, what back-end?

Additional Information
----------------------
This also happens in Ex Falso and with other file types. Other menu's for plugins work as expected, added picture.
![20191227_143050](https://user-images.githubusercontent.com/35849405/71519123-58f79180-28b6-11ea-9311-0b9ac95cef14.jpg)

**Comment by declension** [comment]
Confirmed on 1499cbcd1a139aa8eb989fe5a20db1d8fb175a29, Ubuntu 19.10

**Comment by declension** [comment]
Same for _Go to Bookmark_ plugin
