### ISSUE TITLE
Playback Error on Quodlibet 4.2.1

### ISSUE THREAD

**Issue by BeanRaven** [quodlibet/quodlibet#3295]
After updating to macOS Catalina, quodlibet has playback errors. How do I fix this issue?

"Resource not found. No such file "..."."

**Comment by declension** [comment]
Hi - please can you fill in a bug template or update this to match (steps to reproduce, expected, actual... and system details) - it's very hard to reproduce errors otherwise.

**Comment by CreamyCookie** [comment]
Closing this as it's still missing crucial information.
