### ISSUE TITLE
Debian apt key expired?

### ISSUE THREAD

**Issue by tecnosegugio** [quodlibet/quodlibet#3298]
Looks like your Debian apt key is expired. 
Executing an "apt update" I got the error:

W: GPG error: http://lazka.github.io/ql-debian/testing quodlibet-unstable/ Release: The following signatures were invalid: EXPKEYSIG 5A62D0CAB6264964 Christoph Reiter <rer.christoph@gmail.com>
E: The repository 'http://lazka.github.io/ql-debian/testing quodlibet-unstable/ Release' is not signed.

**Comment by lazka** [comment]
yes, thanks, `sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 5A62D0CAB6264964` should fix it.
