### ISSUE TITLE
Bit rate information is incorrect on variable bit rate music

### ISSUE THREAD

**Issue by Sabilon** [quodlibet/quodlibet#3301]
Steps :
 * Rip some music to high quality variable bit rate MP3.
 * Enable the "bit rate" column in Quodlibet viewer.
 * Open that music in Quodlibet.

Observed : the bitrate column displays "32"
Expected : the value should be higher, around the actual average bitrate

Quodlibet 4.2.1 / Linux

**Comment by lazka** [comment]
What's your mutagen version? `python3 -c "import mutagen; print(mutagen.version_string)"`

**Comment by lazka** [comment]
In case it's >=1.40 please send me an example file -> reiter.christoph@gmail.com

**Comment by lazka** [comment]
What tool did you use to create those files? The MP3 is missing the VBR header

**Comment by Sabilon** [comment]
Oh, sorry for forgetting this issue. I am not sure if I created the file using Sound Converter or Rhythmbox, under Linux Manjaro.

**Comment by CreamyCookie** [comment]
Closing this as invalid, as there's no VBR header.

Still, thank you, Sabilon, for reporting! :)
