### ISSUE TITLE
Move QL to Python 3.6+

### ISSUE THREAD

**Issue by declension** [quodlibet/quodlibet#3305]
The proposed change
-------------------
Move to Python 3.6+

Benefits of this change
-----------------------
Developer features: f-strings, improved `typing` support, `Pathlib` and [many more improvements](https://docs.python.org/3.6/whatsnew/3.6.html)

Any issues this might cause
---------------------------

None I can think of really. Nearly all the major Linux OSes have had 3.6 for some time now, e.g. Ubuntu LTS 18.04 +,  Debian sid on 3.8, Debian Buster on 3.7, RHEL 8

But not sure about other OSes

**Comment by lazka** [comment]
Sounds good

**Comment by lazka** [comment]
QL 4.4 will require 3.6
