### ISSUE TITLE
Push a new stable version

### ISSUE THREAD

**Issue by ApolloLV** [quodlibet/quodlibet#3308]
I am still experiencing an issue with the Musicbrainz plugin because the server response changed a few months back. The plugin was fixed (see #3269), but this fix still needs to be included in an official release. For now, the Musicbrainz plugin is not working at all.

@lazka is there a timeline for a new "stable" version?

**Comment by lazka** [comment]
https://github.com/quodlibet/quodlibet/releases/tag/release-4.3.0
