### ISSUE TITLE
The repository does not have a Release file

### ISSUE THREAD

**Issue by bigalgeorge** [quodlibet/quodlibet#3314]
Hi unable to install due to 
Err:11 http://ppa.launchpad.net/lazka/ppa/ubuntu focal Release
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/lazka/dumpingplace/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://ppa.launchpad.net/lazka/ppa/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by elcste** [comment]
More specifically, the repo doesn't have builds for focal (upcoming 20.04). I've moved some systems to focal already, too, and would also love it if the PPAs were updated with focal builds :-)

**Comment by lazka** [comment]
Should work now

**Comment by CreamyCookie** [comment]
Closing this for now.
