### ISSUE TITLE
Quodlibet 4.2 italian translation

### ISSUE THREAD

**Issue by dprimon** [quodlibet/quodlibet#3318]
Hi, I've fully translated the quodlibet-4.2 branch of the repository. I would like to push the changes with git but I have not figured out how to do it. So here is the link to the .po file: https://gist.github.com/dprimon/280de406b20d2cd65db499a669b17028.
Cheers.

**Comment by dprimon** [comment]
Up

**Comment by lazka** [comment]
Thanks!

**Comment by dprimon** [comment]
I pulled the changes from master; I noticed that I am not listed as a translator in credits.

**Comment by lazka** [comment]
The credits are hardcoded here: https://github.com/quodlibet/quodlibet/blob/master/quodlibet/quodlibet/const.py

I only update them from time to time (and have forgotten with the last release actually...)

**Comment by dprimon** [comment]
Thanks for you reply.
I have another question. I added support to accellerators to some plugins tabs in my local branch named 4.2-italian. How can I push that branch?

**Comment by lazka** [comment]
* Fork this repo (I see you have an empty repo named quodlibet, you might need to delete that first)
* In you local repo add a new remote (`git remote add fork https://github.com/dprimon/quodlibet.git`)
* Change your branch to `4.2-italian`, and `git push fork`
* Then in the github UI create a PR.

**Comment by dprimon** [comment]
Thank you. I've made a pull request as you described but it's still not being merged. Can you update the const.py to include my name?

**Comment by lazka** [comment]
The pull requests breaks the test suite, so it can't be merged as is. I'll have a look.

**Comment by lazka** [comment]
Also it includes code changes which should go into a stable branch. I'll rebase it onto master

**Comment by lazka** [comment]
Merged your changes in #3405
