### ISSUE TITLE
Pitch plugin: AAC LC .mp4/.m4a file playback fails

### ISSUE THREAD

**Issue by slackmage** [quodlibet/quodlibet#3325]
![image](https://user-images.githubusercontent.com/230274/76908228-900a8d00-687e-11ea-87af-f529fb41cbfe.png)

Version 4.3.0
Windows 10 18363

**Comment by slackmage** [comment]
Turns out this was due to the "Pitch/Speed" plugin being enabled. Disabled it and now playback works.

**Comment by Viktini** [comment]
A Soundtouch plugin update must have fixed this because the pitch plugin is working fine with AAC codec files on Arch Linux right now.

- Quod Libet 4.3.0
- soundtouch 2.1.2
- gst-plugins-bad 1.16.2

**Comment by Viktini** [comment]
It stopped working for me on a new install of Arch. Only thing different that I did was install gst-libav, so I uninstalled it and pitch shifting AAC works again. The issue appears to be stemming from gst-libav, which Gstreamer seems to use when that's installed and AAC files are being played. Other codecs seem to work fine.

**Comment by puchasa** [comment]
Had the same problem on Ubuntu. After reading this I tried installing gst-plugins-bad. Fixed it.

**Comment by declension** [comment]
Can we close this then - it seems to be an upstream problem...

**Comment by CreamyCookie** [comment]
Closing this is upstream related and possibly fixed.
