### ISSUE TITLE
No module named 'quodlibet'

### ISSUE THREAD

**Issue by realSConway** [quodlibet/quodlibet#3326]
Steps to reproduce
------------------

Installed quodlibet via YaST (Opensuse), error: `python(abi) = 3.6 needed by exfalso`
Ignored error, and went through with installation.

After 'successful' installation. when I click icon, nothing happens, running quodlibet from command line throws Actual Output documented below.

Expected Output
---------------
quodlibet starts

Actual Output
-------------
user@localhost:~> quodlibet 
Traceback (most recent call last):
  File "/usr/bin/quodlibet", line 12, in <module>
    from quodlibet.main import main
ModuleNotFoundError: No module named 'quodlibet'

Test System
-----------

### Which version of Quod Libet?
4.2.1-lp151.1.2

### Which operating system 
NAME="openSUSE Tumbleweed"
# VERSION="20200314"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20200314"
PRETTY_NAME="openSUSE Tumbleweed"

Additional Information
----------------------

**Comment by lazka** [comment]
I guess a rebuild could help

**Comment by lazka** [comment]
I've pushed an update, can you test again?

**Comment by elcste** [comment]
Working for me on Eoan, which was also missing, and I can see/download the Focal package as well. Thanks!

**Comment by lazka** [comment]
Thanks for testing

**Comment by realSConway** [comment]
Quite sorry for delay.

Solved for me as well.
I upgraded Opensuse tumbleweed to version 20200320

Thanks you for your time and quick response!
