### ISSUE TITLE
Ubuntu: python3-mutagen dependencies in PPA breaks other Xenial packages

### ISSUE THREAD

**Issue by mr-smidge** [quodlibet/quodlibet#3333]
The dependencies of `python3-mutagen` in the recent 4.3.0 build seem to break packages on Ubuntu Xenial.

Steps to reproduce
------------------

1. Set up the stable PPA on Ubuntu Xenial and install QuodLibet 4.3.0:

```
$ sudo add-apt-repository ppa:lazka/ppa
$ sudo apt update
$ sudo apt install quodlibet
```

2. Note that `quodlibet` depends on `exfalso`, and `exfalso` depends on `python3-mutagen`:

```
$ apt show exfalso
...
Depends: python3:any (>= 3.4~), python3-mutagen (>= 1.34), python3-gi (>= 3.18), python3-gi-cairo (>= 3.18), gir1.2-gtk-3.0 (>= 3.18), gir1.2-soup-2.4 (>= 2.52), python3-feedparser
...
```

3. Attempt to install another mutagen-using application, such as picard or puddletag, which depend on `python-mutagen` (i.e. without the '3' in the package name).

```
$ sudo apt install puddletag
```

Expected Output
---------------

The installation should complete successfully.

Actual Output
-------------

Installation fails, because `python-mutagen` and the PPA version of `python3-mutagen` cannot be installed side-by-side.

```
$ sudo apt install puddletag
eading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 puddletag : Depends: python-mutagen (>= 1.14) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

The dependencies of `python3-mutagen` explicitly break `python-mutagen` below the same version:

```
$ apt show python3-mutagen
Package: python3-mutagen
Version: 1.44.0-0~ppa0~xenial
Priority: optional
Section: python
Source: mutagen
Maintainer: Tristan Seligmann <mithrandi@debian.org>
Installed-Size: 738 kB
Depends: python3:any (>= 3.3.2-2~), python3-pkg-resources
Breaks: python-mutagen (<< 1.44.0-1)
^^^^
Replaces: python-mutagen (<< 1.44.0-1)
Download-Size: 143 kB
APT-Manual-Installed: yes
APT-Sources: http://ppa.launchpad.net/lazka/ppa/ubuntu xenial/main amd64 Packages
```

This restriction does not appear to be present on upstream packages of `python3-mutagen`: https://packages.ubuntu.com/search?keywords=python3-mutagen

Test System
-----------

### Which version of Quod Libet?
4.3.0

### Which operating system 
Linux Mint 18.3 Sylvia (based on Ubuntu Xenial 16.04)

Is this a packaging issue that Quod Libet has control over?

Many thanks.

**Comment by mr-smidge** [comment]
This issue may not be Xenial-specific, but I have only been able to test with this OS base so far.

**Comment by lazka** [comment]
Yeah, I've already got contacted over this. mutagen has dropped Python 2 support, so we can no longer build a python2 version and the CLI tools are in the python2 package in xenial, leading to a conflict.

The only solution would be to add a new python2 only mutagen package in the PPA. I'll have a look.

**Comment by lazka** [comment]
Another solution would be to use our flatpak instead of the PPA, this way your base system isn't changed.

**Comment by lazka** [comment]
Please try again now

**Comment by mr-smidge** [comment]
Hi Christoph,
The latest packaging changes fixes the issue.  Happy to mark this as closed.
Many thanks.
