### ISSUE TITLE
Selecting songs without a discnumber

### ISSUE THREAD

**Issue by deSalier** [quodlibet/quodlibet#3334]
Hi All,

I am struggling with the following, and I am sure it is possible
In my music library I am aiming for consistency. Some of the songs have discnumber on them, some don't. How can I select all the files without a discnumber tag (or any other tag for that matter) so that I can bulk edit them?

I am sure it is possible in the searchbar somehow, but I can't find it.

Many thanks in advance.

Regards,
Erwin

**Comment by bassstorm** [comment]
Hi Erwin,

Missing Tag plugin is what you need, see #2936.

Best regards,
Maksim
