### ISSUE TITLE
Endless scan after relocating (large) library

### ISSUE THREAD

**Issue by PhilHudson** [quodlibet/quodlibet#3337]
Steps to reproduce
------------------

Copy my library from a remote SSHFS-mounted directory to a local external HD (USB), in both cases using a symlink at /Music.

The library contains about 44K tracks.

Expected Output
---------------

QL should launch, do a scan taking no more than a few minutes -- less, I expected -- and then settle into normal use, preserving all my ratings and play counts.

Actual Output
-------------

The scan goes on apparently forever; over three days, the longest time I let it run. All that time, the library listing (in the "Search Library" browser) jumps around while being repeatedly updated. AFAICT, two files at least under ~/.quodlibet are constantly growing: 'songs' and 'config'.

Running with --debug for several hours gave me this:

https://gist.github.com/PhilHudson/a402777b54e84f5db13f94fe61a2843c

Music playback seems to be fine.

Test System
-----------

### Which version of Quod Libet?

3.7.1

### Which operating system 

Linux Mint Debian Edition 3
uname -a:
Linux mace 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1 (2020-01-20) x86_64 GNU/Linux

### If it's audio-related, what back-end?

Additional Information
----------------------

The symlink at /Music used to point to an SSHFS-mounted directory under /mnt and now points to an ext4-mounted directory under /media. The contents of the external HD are a direct rsync copy of the remote machine's library, carried out when the external HD was attached and mounted on that remote machine. 

Permissions on the symlink:

lrwxrwxrwx 1 root root 23 2020-04-02 16:57 /Music -> /media/phil/Tunes/Music/

Permissions on the library:

drwxrwxrwx 676 phil phil 28K 2020-04-01 15:03 Music/

Permissions on library subdirectory are all one or other of the following two formats:

drwxrwxrwx  4 phil phil 4.0K 2020-02-20 08:17 Wolfgang Amadeus Mozart/
drwxr-xr-x  2 phil phil 4.0K 2019-09-09 17:43 Woody Guthrie/

**Comment by lazka** [comment]
3.7.1 is 3.5 years old now. Please try a newer version for starters.

**Comment by PhilHudson** [comment]
After restoring my backed-up, known-good ~/.quodlibet directory and reverting the /Music symlink to point to the SSHFS mount, QL behaves as expected: starts, takes several minutes to scan the library, then settles into normal use. This is not a workable solution for me though, since the drive on the remote machine is now nearly full.

So... how do I get my collection off the remote machine and onto an external HD without losing all my metadata?

**Comment by PhilHudson** [comment]
@lazka I appreciate that it's annoying and difficult for you to support old releases. I run what's in my distro's repo, for fear of dependency hell and possible feature disappearance if I try to build from Github head. Is that foolish on my part?

**Comment by lazka** [comment]
QL will resolve symlinks, so hiding things behind a symlink with the same name will still lead to everything being reloaded as if they were new files.

**Comment by lazka** [comment]
and config shouldn't really grow, maybe have a look what's the content there.

**Comment by PhilHudson** [comment]
Worked around this. Required a) sudo and b) safely ending all working practices that depended on the SSHFS mount. What I did was mount the external drive on exactly the same mountpoint. QL now starts and runs normally.

I hope you agree that it is completely unsatisfactory and a very serious defect that a non-super user cannot move their library without losing their ratings and play counts, and that even a superuser may have to lose long-established shared FS mappings.

**Comment by declension** [comment]
BTW @PhilHudson you can [save ratings and playcounts in files](https://quodlibet.readthedocs.io/en/latest/guide/faq.html?highlight=newer#where-does-quod-libet-store-ratings-and-playcounts) which avoids this problem somewhat.

Seems like the original problem is solved, can we close? There are other tickets for the more general issue(s) #3287 #708 #1939 etc

**Comment by PhilHudson** [comment]
On Sun, 29 Nov 2020 at 12:11, Nick Boultbee <notifications@github.com> wrote:
>
> BTW @PhilHudson you can save ratings and playcounts in files which avoids this problem somewhat.
>
> Seems like the original problem is solved, can we close? There are other tickets for the more general issue(s) #3287 #708 #1939 etc

As you say, other tickets cover the same ground adequately. Go ahead
and close. Thanks for maintaining QL!
