### ISSUE TITLE
python load path on macOS

### ISSUE THREAD

**Issue by renma** [quodlibet/quodlibet#3339]
Steps to reproduce
------------------
Installed python3 with brew.
Installed QuodLibet with brew.
Installed private modules with pip3.
The private modules go to /usr/local/lib/python3.7/site-packages
Installed a private plugin in ~/.quodliber/plugins
The private plugin uses stuff from  /usr/local/lib/python3.7/site-packages (import mystuff)

Expected Output
---------------
The plugin works.

Actual Output
-------------
Plugin Errors: ModuleNotFoundError: No module named 'mystuff'

Test System
-----------
QuodLibet 4.3.0
macOS Catalina 10.15.4

Additional Information
----------------------
The private plugin works after adding
sys.path.append("/usr/local/lib/python3.7/site-packages")
to the plugin code.

**Comment by lazka** [comment]
hm, so where are other Python dependencies installed (like mutagen)?

I don't have much experience with homebrew sadldy

**Comment by renma** [comment]
Sorry I am very new to macOS.
I came from Linux, so a package manager sounds good to me. Maybe homebrew is not the right tool  to install QuodLibet on macOS?

It seams that homebrew has installed everything needed by QuodLibet here:
**/Applications/QuodLibet.app/Contents/Resources/lib/python3.7/site-packages**

```
# cd /Applications/QuodLibet.app/Contents/Resources/lib/python3.7/site-packages
# find . -type d -depth 1
./certifi-2018.10.15-py3.7.egg-info
./biplist-1.0.3-py3.7.egg-info
./mac_alias
./dmgbuild
./pyobjc_framework_Cocoa-4.2.1-py3.7.egg-info
./six-1.11.0-py3.7.egg-info
./gi
./mutagen
./meson-0.49.0-py3.7.egg-info
./Foundation
./ds_store-1.1.2-py3.7.egg-info
./cairo
./mac_alias-2.0.7-py3.7.egg-info
./pyobjc-4.2.1-py3.7.egg-info
./biplist
./pyobjc_framework_Quartz-4.2.1-py3.7.egg-info
./pip
./ds_store
./PyGObject-3.30.4-py3.7.egg-info
./PyObjCTools
./certifi
./feedparser-5.2.1-py3.7.egg-info
./Cocoa
./quodlibet
./setuptools-40.6.2-py3.7.egg-info
./AppKit
./mesonbuild
./pyobjc_core-4.2.1-py3.7.egg-info
./pycairo-1.18.0-py3.7.egg-info
./dmgbuild-1.3.2-py3.7.egg-info
./musicbrainzngs
./setuptools
./pkg_resources
./Quartz
./objc
./pip-20.0.2-py3.7.egg-info
./coverage
./pygtkcompat
./CoreFoundation
./coverage-5.0.3-py3.7.egg-info
```
ps shows the following:
```
# ps -x | grep -i quodlibet | grep -v grep
  599 ??   0:00.01 /bin/bash /Applications/QuodLibet.app/Contents/MacOS/quodlibet
  611 ??    0:04.68 /Applications/QuodLibet.app/Contents/MacOS/python3 /Applications/QuodLibet.app/Contents/Resources/bin/quodlibet
```
I have installed python3 and mutagen with with homebrew and they are here:
```
# which python3
/usr/local/bin/python3
```
and here:
```
# ls /usr/local/lib/python3.7/site-packages | grep mutagen
mutagen
mutagen-1.44.0.dist-info
```

**Comment by lazka** [comment]
> It seams that homebrew has installed everything needed by QuodLibet here:
> **/Applications/QuodLibet.app/Contents/Resources/lib/python3.7/site-packages**

This looks more like our own app bundle, and nothing from homebrew.

**Comment by lazka** [comment]
oh, homebrew just installs our bundle. So I guess all this is expected, the bundle tries to be self contained obviously.

**Comment by lazka** [comment]
You can use the following to install things into the bundle

`/bin/bash /Applications/QuodLibet.app/Contents/MacOS/run -m pip install ..`

but this might break in future versions. and wont persist across updates.

**Comment by renma** [comment]
Thanks. This is clear for me now. Sorry I had not realised that the bundle is self contained. So adding external stuff is not foreseen at all.

As said I have added the regular site-packages directory to the load path in my plugins. Not really nice, but it works for me.

What about adding the regular site-packages directory in QL to the load path?

**Comment by lazka** [comment]
The reason we are self contained (like every other macOS app I'd guess) is that loading external things can break things and just loading things from a random homebrew directory might not be what the user expects.

So this isn't going to be officially supported, but feel free to poke around anyway and ask things.
