### ISSUE TITLE
Download Album Art UI improvements

### ISSUE THREAD

**Issue by ionna22** [quodlibet/quodlibet#3340]
Two suggestions, please:
1. Remember 'Download Album Art' window size and position
2. Create a button (keyboard shortcut, at least) to bring up 'Download Album Art' window, even if album art is already present

**Comment by declension** [comment]
Second one is part of #152 probably

**Comment by CreamyCookie** [comment]
Closing this, as I've extracted part 1 to #3635 and part 2 is basically #2042.
