### ISSUE TITLE
Cannot change to dark theme in Lubuntu

### ISSUE THREAD

**Issue by Lonnifer** [quodlibet/quodlibet#3341]
I am running Quod Libet 3.5.3 on Lubuntu 16.04.06 LTS. I am trying to set a dark theme. I've found the Theme Switcher plugin and gone through all the available themes, but they are all light themes, even when I check the "Prefer Dark Theme Version" checkbox. I've tried changing my global theme settings (preferences > customize look and feel), but these do not seem to affect the appearance of QL.

**Comment by rudluff** [comment]
you have to actually have dark themes installed on your computer for QL to be able to try to auto-choose them. theme selector just switches between systemwide gtk themes, it does not come with any bundled. as in, you need to install dark themes using apt or synaptic or ubuntu store or whatever.
