### ISSUE TITLE
description tag in m4a files

### ISSUE THREAD

**Issue by Vrihub** [quodlibet/quodlibet#3345]
quodlibet (I actually tested with `operon`) doesn't seem to support the `description` tag in m4a files.

Please note that mutagen seems to support it: see https://github.com/quodlibet/mutagen/blob/master/mutagen/mp4/__init__.py

quodlibet doesn't seem to support it (am I right?):
https://github.com/quodlibet/quodlibet/blob/master/quodlibet/formats/mp4.py

Other applications support it, e.g. `youtube-dl` (via `ffmpeg`) with the `--add-metadata` option adds both a `comment` and a `description` tag (see next section).

Steps to reproduce
------------------

- Run `youtube-dl -f 140 --add-metadata URL` (or use `ffmpeg` to add a `description` tag to a m4a file)

- Try to operate on the `description` tag of the resulting m4a file with `operon`.

Expected Output
---------------

The `description` tag should be treated just like the `comment` tag

Actual Output
-------------

`operon add/set/edit/clear/remove` commands don't have effect on the `description` tag. Some commands give an error message (e.g. `add: Can not set 'description'`); some fail silently (e.g. trying to clear/remove a `description` tag already present in the file).

Test System
-----------

### Which version of Quod Libet?
4.2.1

### Which operating system 
Debian 10.3

**Comment by declension** [comment]
Related: #323
