### ISSUE TITLE
Paned Browser View: Unix timestamp does not convert to readable format

### ISSUE THREAD

**Issue by vestingz** [quodlibet/quodlibet#3346]
### Steps to reproduce
------------------
Add a custom column in paned browser view (didn't test the other views) with `~#mtime` as column tag.

### Expected Output
---------------
Items in library are being grouped inside the pane according to a human readable format.

### Actual Output
-------------
Items in library are being grouped inside the pane according to the unix timestamp epoch (see [screenshot](https://envs.sh/FL.png)).

-----------

### Which version of Quod Libet?
Quod Libet 4.3.0

### Which operating system 
Archlinux; Linux 5.6.3-zen1-1-zen #1 ZEN SMP PREEMPT Wed, 08 Apr 2020 07:47:48 +0000 GNU/Linux

**Edit:** #2770 might be connected..?

**Comment by declension** [comment]
Confirmed on ed4d84575e11b976d33745d7afd007c3a1fbed1b

**Comment by vestingz** [comment]
Thanks :)
