### ISSUE TITLE
External changes don't update file system browser with auto library update plugin enabled

### ISSUE THREAD

**Issue by davidSchlosser** [quodlibet/quodlibet#3352]
Steps to reproduce
------------------
operon set title DianeWho test/Miles\ Davis\ Quintet/08.\ Diane.flac

Expected Output
---------------
In Quodlibet, File System browser, right click file 'test/Miles\ Davis\ Quintet/08.\ Diane.flac', and select Edit Tags. Title should now be 'DianeWho'.

Actual Output
-------------
Title doesn't appear to be changed. However if I rescan tags, browse a different music directory, then return to the original directory & reopen the tags for editing, I see the change is now visible. 

Test System
-----------

### Which version of Quod Libet?
4.4 (development, 03af6f85d)

### Which operating system 
Ubuntu 18.04

Additional Information
----------------------
I don't think the fix made after I reported this in issue #3168 has ever worked, but I have been able to cope with it in the mean time. Now it's quite important for me. Sorry for not responding to #3168 much earlier.

**Comment by davidSchlosser** [comment]
The rescan step isn't necessary. By changing & resetting the browser contents, the tag change is displayed as expected. So the issue is that the browser contents don't get refreshed when the underlying files change. Perhaps that's too much for me to expect?

**Comment by declension** [comment]
@davidSchlosser sorry about the delay. Does this happen with other browsers too, or is it just the file system browser?

**Comment by davidSchlosser** [comment]
I haven't been rechecking this until now - it now appears to be working correctly with the Album List browser and the File System browser. (I wonder if I didn't test the earlier fix correctly, sorry for that.)
