### ISSUE TITLE
QLScrobbler seems not to be working

### ISSUE THREAD

**Issue by jnhlb** [quodlibet/quodlibet#3355]
It says that the authorisation was successful, but 

1. I don't see it in my the list of applications for my last.fm account
2. It doesn't scrobble

Tried restarting the player and turning the plugin on and off, didn't help.
I also tried removing the appropriate lines from config file, then after providing my credentials it said that the URL is incorrect. I think the app has to switch to another server.

**Comment by CreamyCookie** [comment]
What version are you using?

**Comment by jnhlb** [comment]
All fine, just one artist being ignored by last.fm when using panoscrobbler
with BlackPlayer on Android, but curiously scrobbling from Spotify with no
issues.
I think we can close this ticket.
Regards
JH

**Comment by CreamyCookie** [comment]
Thanks!
