### ISSUE TITLE
Ratings and popm tag

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [quodlibet/quodlibet#3357]
Steps to reproduce
------------------

With kid3 (a tag editor) I've setup the popm tag of every file.
I use a rating of 1 to 5 stars.
According to the [kid3 documentation](https://kid3.sourceforge.io/kid3_en.html#filter), this is the mapping from stars to value:
![image](https://user-images.githubusercontent.com/6008104/80290176-0afb7900-8744-11ea-847e-08fb2f9edaaa.png)

I have activated to save to tag the ratings and playcount in preferences.
![image](https://user-images.githubusercontent.com/6008104/80290741-d4276200-8747-11ea-98be-e88eab0f0e8b.png)

Expected Output
---------------
After reloading library in Quodlibet, I expect to see the modified ratings.
All my songs have ratings set in the popm tag.

Actual Output
-------------
Many songs shown in QL without rating.

Test System
-----------

### Which version of Quod Libet?
Latest: 4.3.0

### Which operating system 
KDE Neon based on Ubuntu 18.04

### If it's audio-related, what back-end?
no

Additional Information
----------------------
Is this a bug?
What is the correct values for the popm tag?  I've tried to guess it empirically.  I modify the stars in Quodlibet and observe the value of the tag in the file, but it looks like unchanged.
For files non-mp3, which tag should I set?

Maybe the correct mapping is:

- 1 star ==> 0.2
- 2 stars ==> 0.4
- ....
- 5 stars ==> 1.0

Related issue: #2921

**Comment by CreamyCookie** [comment]
Not sure if this is the cause of the issue, but QL has a 0 star rating, so if you select 5 stars, you will have 6 different values.

**Comment by declension** [comment]
@DavidPerezIngeniero do you still get this on 4.4.0?

**Comment by DavidPerezIngeniero** [comment]
I don't know, because now I only rate my songs with QL.
