### ISSUE TITLE
Unable to show custom tags

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [quodlibet/quodlibet#3360]
Steps to reproduce
------------------
I have some custom tags like one called "Bailable".  I can edit it and see with programs like JRiver Media Center, PuddleTag, kid3, .....

But QL is unable to show them even though I have specified the column name in the visible columns preference.

Expected Output
---------------
Show custom tag values in the grid 

Actual Output
-------------
I see a blank value for .mp3, .aac, .wma, .m4a files.

Test System
-----------

### Which version of Quod Libet?
4.3.0

### Which operating system 
KDE Neon based on Ubuntu 18.04

### If it's audio-related, what back-end?
No

Additional Information
----------------------
A possible workaround, could be use a tag recognized by QL, even though it is designed for other purpose.

**Comment by DavidPerezIngeniero** [comment]
With mutagen `pprint()`, I've gathered the tags read for a sample file:
```

POPM=dpc=0 64/255
TALB=Teresa Teng - Remembering Teresa
TBPM=62
TCOM=http://www.yesya.com/
TDRC=2004
TENC=http://www.yesya.com/
TIT1=China
TIT2=并籩籩
TOPE=http://www.yesya.com/
TPE1=Teresa Teng
TPE2=«ä§g¶°
TPUB=http://www.yesya.com/
TRCK=16
TXXX=Album Artist=«ä§g¶°
TXXX=Bailable=-1  <=======
TXXX=Cantado=1
TXXX=Dynamic Range (DR)=12
TXXX=Dynamic Range (R128)=3,6718099117279053
TXXX=FMPS_Rating=0.4
TXXX=Fuerza=1
TXXX=HDCD=0
TXXX=Intensity=2
TXXX=País=China
TXXX=Peak Level (R128)=+0.2 dBTP; +0.2 Left; +0.2 Right
TXXX=Peak Level (Sample)=+0.0 dB; +0.0 Left; +0.0 Right
TXXX=Pun=2
TXXX=Tarareable=1
TXXX=Volume Level (R128)=-9,2750997543334961
TXXX=Volume Level (ReplayGain)=-4,2751002311706543
TXXX=replaygain_track_gain=-4.28 dB
TXXX=replaygain_track_peak=1.000000'
POPM=dpc=0 64/255
TALB=Teresa Teng - Remembering Teresa
TBPM=62
TCOM=http://www.yesya.com/
TDRC=2004
TENC=http://www.yesya.com/
TIT1=China
TIT2=并籩籩
TOPE=http://www.yesya.com/
TPE1=Teresa Teng
TPE2=«ä§g¶°
TPUB=http://www.yesya.com/
TRCK=16
TXXX=Album Artist=«ä§g¶°
TXXX=Bailable=-1
TXXX=Cantado=1
TXXX=Dynamic Range (DR)=12
TXXX=Dynamic Range (R128)=3,6718099117279053
TXXX=FMPS_Rating=0.4
TXXX=Fuerza=1
TXXX=HDCD=0
TXXX=Intensity=2
TXXX=País=China
TXXX=Peak Level (R128)=+0.2 dBTP; +0.2 Left; +0.2 Right
TXXX=Peak Level (Sample)=+0.0 dB; +0.0 Left; +0.0 Right
TXXX=Pun=2
TXXX=Tarareable=1
TXXX=Volume Level (R128)=-9,2750997543334961
TXXX=Volume Level (ReplayGain)=-4,2751002311706543
TXXX=replaygain_track_gain=-4.28 dB
TXXX=replaygain_track_peak=1.000000'
```
So, I know now Mutagen can read ok my custom tags.

**Comment by DavidPerezIngeniero** [comment]
I see this issue is duplicated from this:  https://github.com/quodlibet/quodlibet/issues/48 TXXX

**Comment by declension** [comment]
Thanks. Closing in favour of #48
