### ISSUE TITLE
Only see custom tags in properties window

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [quodlibet/quodlibet#3366]
Steps to reproduce
------------------

I had my music files with the custom `Bailable` tag.
In order to see it in QL, I've added the `QuodLibet::` prefix.
And this small trick works, I can see my custom tag in the grid and properties window and edit it.  Also I can search.

Later, I add more custom tags, and surprise.
It is shown in the Properties window (Alt+Enter), but isn't in the grid. Futhermore, I cannot use it in searches.

Expected Output
---------------
Use custom tags as any regular tag.
![image](https://user-images.githubusercontent.com/6008104/80920722-0b15fd00-8d72-11ea-8c0c-8052094a6de0.png)

Actual Output
-------------
Only see my custom tags in the properties window.

Test System
-----------

### Which version of Quod Libet?
4.3.0

### Which operating system 
Ubuntu 18.04

### If it's audio-related, what back-end?
No

Additional Information
----------------------

I didn't know about custom tags requiring QuodLibet:: prefix
Here is the contents of tags as shown by Mutagen of sample music file:

```
-- /media/david/copia2/musica/internet/orquestas/helmut zacharias/fascination.mp3
- MPEG 1 layer 3, 171829 bps (VBR, LAME 3.97.0, -V 4 --vbr-new), 44100 Hz, 2 chn, 151.55 seconds (audio/mp3)
APIC=cover front, Picture (image/jpeg, 56135 bytes)
COMM===Hace flotar. Violines,xilófono
COMM=ID3v1 Comment=eng=Hace flotar. Violines,xilófon
POPM==None 255/255
RVA2=[unrepresentable data]
TALB=Helmut Zacharias
TBPM=96
TCOM=F.D.Marchetti
TCON=Vals@
TCOP=5
TIT1=Italia
TIT2=Fascination (Fascinación)
TPE1=F.D.Marchetti
TPE2=Helmut Zacharias
TRCK=0
TXXX=Album Artist=Helmut Zacharias
TXXX=Bailable=2
TXXX=Comercial=-1
TXXX=Country=Italia
TXXX=Dynamic Range (DR)=10
TXXX=Dynamic Range (R128)=6,1237401962280273
TXXX=HDCD=0
TXXX=Intensity=2
TXXX=JR/Band=Helmut Zacharias
TXXX=País=Italia
TXXX=Peak Level (R128)=-2,9 dBTP; -3,5 Left; -2,9 Right
TXXX=Peak Level (Sample)=-3,2 dB
TXXX=Pun=5
TXXX=QuodLibet::Alegre=-1
TXXX=QuodLibet::Bailable=2
TXXX=QuodLibet::Fuerza=1
TXXX=QuodLibet::Perturba=1
TXXX=QuodLibet::Tarareable=1
TXXX=Sanación=1
TXXX=Tool Name=Media Center
TXXX=Volume Level (R128)=-7,1595301628112793
TXXX=Volume Level (ReplayGain)=-3,4900000095367432
TXXX=replaygain_track_gain=-3.49 dB
TXXX=replaygain_track_peak=0.692000
```

Of course, I've tried:

- Rescaning the library
- Quit QL and starting it again.

I don't know where to look for logs.

**Comment by declension** [comment]
What was the column configuration you used? 

Also, have you tried without the (explicit) `Quodlibet::` - e.g. `Sanación` above. In fact, looking about it seems that you have both `Bailable` and `Quodlibet::Bailable` - is that intentional?

**Comment by DavidPerezIngeniero** [comment]
Thanks for your answer.
This is the config:
![image](https://user-images.githubusercontent.com/6008104/81047156-255af280-8eba-11ea-81a2-57fb2ab39cda.png)

It isn't intentional.
The old name was  `Bailable`, and I've created a new column named `QuodLibet::Bailable`.
I'll try to remove the old column....
Maybe this confuses QL.

**Comment by DavidPerezIngeniero** [comment]
~declension, I've corrected that.

Here is a sample file:
```
- MPEG 1 layer 3, 136669 bps (VBR), 44100 Hz, 2 chn, 253.15 seconds (audio/mp3)
COMM==XXX=Cantado mujer solista con varios mas
POPM=dpc=0 128/255
TALB= Alexander Pirex - Gloria Stefan
TCOM=?
TIT2=Santo santo
TPE1=#Alexander Pirex - Gloria Stefan
TXXX=TXXX:QuodLibet::Alegre=2
TXXX=TXXX:QuodLibet::Cantado=1
TXXX=TXXX:QuodLibet::Comercial=1
TXXX=TXXX:QuodLibet::Fuerza=3
TXXX=TXXX:QuodLibet::Tarareable=2
```
All TXXX frames have the `QuodLibet::` prefix, but QL doesn't recognize them.
