### ISSUE TITLE
FileNotFoundError in Windows when trying to add files whose names contain special characters on a Linux ext4 partition

### ISSUE THREAD

**Issue by vranitzky** [quodlibet/quodlibet#3373]
Steps to reproduce
------------------
In Windows, adding a file/folder with special characters in the filename, when it is located on an ext4 partition. 
Example filename, with the partition mapped as letter H:
'H:\\michael\\Music\\Ancient Music\\Hildegard von Bingen (1098–1179)\\Chant Cistercien Monodies Du XII Siecle [Ensemble Organum]\\06 - [RÉPONS DE MATINES POUR LA FÊTE DE SAINT BERNARD] - Prima virtus viri sancti.ogg'

Note the –, É and Ê
The file works fine with any other program/player.

Expected Output
---------------
That the file would be added to the library.

Actual Output
-------------

FileNotFoundError: [WinError 161] The specified path is invalid: 'H:\\michael\\Music\\Ancient Music\\Hildegard von Bingen (1098–1179)\\Chant Cistercien Monodies Du XII Siecle [Ensemble Organum]\\06 - [RÉPONS DE MATINES POUR LA FÊTE DE SAINT BERNARD] - Prima virtus viri sancti.ogg'

Test System
-----------

### Which version of Quod Libet?
4.3.0

### Which operating system 
Windows 10 with Paragon's ext4 driver

### If it's audio-related, what back-end?

Additional Information
----------------------

Traceback (most recent call last):

  File "ntpath.py", line 660, in realpath

FileNotFoundError: [WinError 161] The specified path is invalid: 'H:\\michael\\Music\\Ancient Music\\Hildegard von Bingen (1098–1179)\\Chant Cistercien Monodies Du XII Siecle [Ensemble Organum]\\06 - [RÉPONS DE MATINES POUR LA FÊTE DE SAINT BERNARD] - Prima virtus viri sancti.ogg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Program Files\Quod Libet\lib\python3.8\site-packages\quodlibet\util\copool.py", line 23, in wrap
    for value in func(*args, **kwargs):

  File "C:\Program Files\Quod Libet\lib\python3.8\site-packages\quodlibet\library\libraries.py", line 686, in rebuild
    for value in self.scan(paths, exclude, cofuncid):

  File "C:\Program Files\Quod Libet\lib\python3.8\site-packages\quodlibet\library\libraries.py", line 731, in scan
    for real_path in iter_paths(scan_path, exclude=exclude):

  File "C:\Program Files\Quod Libet\lib\python3.8\site-packages\quodlibet\library\libraries.py", line 511, in iter_paths
    fullfilename = os.path.realpath(fullfilename)

  File "ntpath.py", line 664, in realpath

  File "ntpath.py", line 614, in _getfinalpathname_nonstrict

FileNotFoundError: [WinError 161] The specified path is invalid: 'H:\\michael\\Music\\Ancient Music\\Hildegard von Bingen (1098–1179)\\Chant Cistercien Monodies Du XII Siecle [Ensemble Organum]\\06 - [RÉPONS DE MATINES POUR LA FÊTE DE SAINT BERNARD] - Prima virtus viri sancti.ogg'
`

**Comment by lazka** [comment]
Since the ext4 driver complains about a path it gave us itself I'm unsure what to do (unless I'm missing something)

**Comment by vranitzky** [comment]
Upon further testing, I found that this is unrelated to ext4. It is simply due to path length. 
Shortening the filename by just one character, will work. Same for other files with long paths/names.
Maybe hitting the 260 characters Windows limit? Is that still a thing?
No change toggling this groupp Policy: Computer Configuration > Administrative Templates > System > Filesystem > Enable Win32 long paths

**Comment by lazka** [comment]
Ah, yes, the 260 limit is still a thing, bu the above is 208, so I dismissed that, unless there is a symlink involved pointing to an even longer path?

If it really is re long paths this happened to be fixed last month in cef714c1521d639c7cfef3a764 and should be in the next release.

**Comment by vranitzky** [comment]
Thank you. 
According to this: 
https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#enable-long-paths-in-windows-10-version-1607-and-later
the registry key HKLM\SYSTEM\CurrentControlSet\Control\FileSystem LongPathsEnabled (Type: REG_DWORD) must exist and be set to 1 for longPathAware to be effective, otherwise to specify an extended-length path, one must use the "\\?\" prefix. For example, "\\?\D:\very long path"

**Comment by lazka** [comment]
Yes, in addition to the registry key also "The application manifest must also include the longPathAware element." which is what the above linked fix does.

**Comment by d10n** [comment]
Be aware of this when working on a fix:

https://docs.microsoft.com/en-us/windows/win32/api/shlwapi/nf-shlwapi-urlcreatefrompathw#remarks

> Note  UrlCreateFromPath does not support extended paths. These are paths that include the extended-length path prefix "\\?\".

https://github.com/quodlibet/quodlibet/blob/0e6b134207765d55a20edbb2e8db3ee2902a9759/quodlibet/packages/senf/_fsnative.py#L606

**Comment by CreamyCookie** [comment]
Closing this for now (given the fix), but comment here if this reappears and I'll reopen.

Thanks for reporting!
