### ISSUE TITLE
Support "Elapsed Time" in --print-playing

### ISSUE THREAD

**Issue by rizlaw** [quodlibet/quodlibet#3377]
The proposed change
-------------------
 

(1)  There are no Internal Tags for:
       (a) real time display of the "elapsed time" of a playing track.

 (b) a "progress bar". However, not being a programmer, I imagine this could take considerable work to implement so that it could be used in an external application like "Conky". 

Previous request for ~album name tag removed for reasons noted below.

Benefits of this change
-----------------------
 The above requested "Internal Tags:  would allow for more complete progamming of "Conky" scripts which can currently display Quodlibet --print-playing information (~basename, ~people, ~#tracks ~length, ~format, ~samplerate, and ~bitdepth on the desktop through Conky.  Adding the two additional Internal Tags would help complete the ability to fully describe the Quodlibet real time playing information in a desktop Conky script.

Any issues this might cause
--------------------------- None of which I am aware.

**Comment by declension** [comment]
This seems like two separate issues. Could you split it?

Although maybe it's only one - `~album` is the tag for the name of an album. See the [QL user guide](https://quodlibet.readthedocs.io/en/latest/guide/tags/tags.html)

**Comment by rizlaw** [comment]
> This seems like two separate issues. Could you split it?
> 
> Although maybe it's only one - `~album` is the tag for the name of an album. See the [QL user guide](https://quodlibet.readthedocs.io/en/latest/guide/tags/tags.html)

From what I can see, **~album** is used only for searches created within Quodlibet and is not listed within the **"Internal Tags"** section of the Guide. From my experience, it doesn't work when used in an external program like Conky with a command like: ${exec quodlibet --print-playing "<~album>"} which is intended to get info out of Quodlibet and into Conky. That's my best non-programmer explanation of the problem. I don't think its two separate issues but rather an overall unintended limitation of "Internal Tags" usage.

**Comment by declension** [comment]
Hi. Yes, sorry in that (Pattern) context I guess I meant `album` - so as you've now updated - your pattern `<album>` should work fine here (and elsewhere).

To clarify: internal tags should be prepended with a tilde; `album` is not an _internal_ tag, it's a normal editable one (and blessed with a few other properties within the app, in fact). `#` is for numeric (internal) tags, e.g. `~#mtime` or `~#length`

There is no _tag_ to represent elapsed time of a song, as saving this to a file would make no real sense globally (you can however save _bookmarks_ of interesting time points within a file) across a library.

I don't think the QL command line is the right place for visual output really - but given support for elapsed time, you could get `~#length` and do the progress bar display externally (ideas on [this SO progress bar post](https://stackoverflow.com/questions/238073/how-to-add-a-progress-bar-to-a-shell-script)).

Dev note: What could work in QL for your use case is wrapping the CLI output with extra metadata that in fact comes from the _player_, not the song.

**Comment by rizlaw** [comment]
When I made the enhancement request for an "elapsed time" tag, it didn't occur to me that I may have had a partial answer to the "progress bar / elapsed time" issue. So in further support of my enhancement request I submit the info below.

In the past, I used Deadbeef (an excellent music player program in its own right). I had a similar progress bar issue with Deadbeef and Conky.  I found code which works with Conky to display a Conky progress bar for the elapsed time of a track when running Deadbeef. The "%e" and "%l" parameters represent Deadbeef "elapsed time" and "track length", respectively using Deadbeef's Foobar2000 formatting:

`#!/bin/bash
/opt/deadbeef/bin/deadbeef --nowplaying "%e %l" |
awk '
{ n = split("::" $1,t,":")
  elapsed = (t[n-2]*60+t[n-1])*60+t[n]
  n = split("::" $2,t,":")
  total = (t[n-2]*60+t[n-1])*60+t[n]
  printf "%d\n",elapsed*100/total
}'`

By placing this script in my Conky folder and placing the following Conky code in my Conky template, I got a nice Deadbeef progress bar:

`	# DEADBEEF PROGRESS BAR calling external python script "deadbeefbar" 
${voffset -10}${font Cantarell:bold:size=14}${goto 2200}${color2}${execbar ~/.conky/LJRThemes/deadbeefbar}	${voffset 15}${goto 2200}${color0}${exec /opt/deadbeef/bin/deadbeef --nowplaying "%e"} / ${exec /opt/deadbeef/bin/deadbeef --nowplaying "%l"}`

So my thinking is, since Quodlibet already has a tag for track length **--print-playing "<~length>"** the only thing left is to provide **elapsed time** tag.
