### ISSUE TITLE
Add originalartistsort tag

### ISSUE THREAD

**Issue by CeraRoseMadrigal** [quodlibet/quodlibet#3378]
The proposed change
-------------------
Currently, the tags "artist", "albumartist", "composer", etc., all have a "sort" variant to go with them, but "originalartist" doesn't seem to, so people using this tag end up with some artists not sorted correctly alongside names from the other People fields. "composersort" was added for similar reasons several years ago with https://github.com/quodlibet/quodlibet/issues/1795 , and although "originalartistsort" was mentioned there as an idea by one person, the focus seemed of that ticket seemed to be mainly on composersort.

Benefits of this change
-----------------------
If, for instance, a user likes for artists to be sorted alphabetically by lastname and then by firstname, this can't currently be done if they are also using the "originalartist" field. For instance, if the only song in my music library with Leonard Cohen among the "People" is Aurelio Voltaire's cover of "Hallelujah", with Cohen as the "originalartist", then it is currently possible to correctly alphabetize the artist as "Voltaire, Aurelio", but it doesn't seem to be possible to alphabetize the original artist as "Cohen, Leonard", which leads to inconsistent sorting of peoples' and bands' names.

Any issues this might cause
---------------------------
None that I am aware of.

**Comment by CeraRoseMadrigal** [comment]
Thank you! :)

**Comment by declension** [comment]
My pleasure :)
