### ISSUE TITLE
~people tag should ignore blank tag values

### ISSUE THREAD

**Issue by afontenot** [quodlibet/quodlibet#3383]
Steps to reproduce
------------------
I haven't made any significant config changes, just imported my library. Look at the artist(s) listed in any panel that shows albums, or look at the artist in the "now playing" pane. Observe that it contains a bunch of weird commas.

![quodlibet_bug1](https://user-images.githubusercontent.com/3870410/83118849-c2591780-a083-11ea-899c-4abd494ebd1b.png)
![quodlibet_bug2](https://user-images.githubusercontent.com/3870410/83118855-c422db00-a083-11ea-9532-c17abc202722.png)

Expected Output
---------------
I expect to see exactly one comma between each artist listed, and no trailing comma at the end.

Actual Output
-------------
I don't see that. (See the screenshots.)

Test System
-----------

### Which version of Quod Libet?
4.3.0

### Which operating system 
Arch Linux

Additional Information
----------------------
All my music is tagged with the MusicBrainz database.

I don't see anything unusual with the tags looking at Ex Falso. For whatever reason, some of the tracks have the composer tag set, some don't, but looking at my other files I see the trailing comma issue on at least one album where every track has the same artist (and artist-like) tags.

Note that it seems obviously undesirable to show "Beck" and "Beck Hansen" as separate artists for this album, but presumably that's a separate issue.

**Comment by Ironbalden** [comment]
By default quodlibet uses the ~people tag, which combines albumartist, artist, author, composer, ~performers, originalartist, lyricist, arranger and conductor. If you have any of these tags empty (aka inserted but with an empty value) it will be shown as an empty string between commas. If you want only one of these tags shown I will suggest you to go to the preferences under the gear menu and change ~people to your preferred tags. I hope this comment is helpful.

**Comment by afontenot** [comment]
> By default quodlibet uses the ~people tag, which combines albumartist, artist, author, composer, ~performers, originalartist, lyricist, arranger and conductor. If you have any of these tags empty (aka inserted but with an empty value) it will be shown as an empty string between commas. If you want only one of these tags shown I will suggest you to go to the preferences under the gear menu and change ~people to your preferred tags. I hope this comment is helpful.

Aha! Tricked by the ~people tag again! Yes, this does "fix" the problem, for me at least, because I don't want to use the people tag. Hopefully it's obvious this is still a bug - the "default" option should skip over blank tags when it's joining the artist strings together, not include them with an empty string and a comma.

**Comment by Ironbalden** [comment]
The now playing area has a different layout, if you right click inside the area there is an "Edit Display" option, which works basically the same.

**Comment by declension** [comment]
> Hopefully it's obvious this is still a bug - the "default" option should skip over blank tags when it's joining the artist strings together, not include them with an empty string and a comma.

Thanks - updated the ticket to reflect the underlying problem here
