### ISSUE TITLE
Make some kind of "intelligent" album artist available for sorting, etc

### ISSUE THREAD

**Issue by afontenot** [quodlibet/quodlibet#3384]
The proposed change
-------------------
Add a way to view / sort by an intelligently determined "artist" for each album. For example, a good start *might* be to use the Composer tag (if it exists), then fall back to the Album Artist tag (if it exists), then fall back to the Artist tag. (See the following section for some qualifiers, though.)

Basically, I want to see whatever corresponds to what would normally be the biggest name on the cover of the physical album. The composer for classical albums, and the album artist for recent releases of popular music. The best way to achieve that might be more complicated than what I described above.

Benefits of this change
-----------------------
I use the "paned browser" mode to view my music. The default column options include a "People" view, but what this does is show every person credited on every single song in my collection. This shows a bunch of mostly useless per-track information. For example, I have 10+ entries just with different combinations of members of [Yes](https://en.wikipedia.org/wiki/Yes_(band)). I don't want to see those, I just want to see Yes!

I suspect most people with an organized music library use something like the following to structure their files: Artist > Album > Tracks. But when you're creating those folders, what do you choose for "Artist"? The answer is almost always the album artist for popular music, and probably the composer for classical music. What you would never do is create one folder for every combination of artist tags, but that's effectively how Quod Libet wants to display the same information. (Ironically all I want is the ability to sort my files in Quod Libet the same way they're sorted on the file system, but this becomes extremely complicated when you start dealing with the actual tags.)

Switching to the custom option of "artist" gets rid of a few of the individual band members, but it leaves other "combo" artist tags. For example I have about 15 different Artist entries beginning "Kendrick Lamar feat." which is also not what I'm looking for.

The closest you can get, seemingly, is by manually typing in "album artist" as the sort option. Unfortunately, it doesn't quite get there because I end up with several hundred tracks listed under "unknown" because they don't have an album artist tag. It doesn't fall back to the artist tag.

It also completely falls apart for classical music. One of my albums has the following album artist tag: "Wiener Philharmoniker, Herbert von Karajan". Another goes on to list the soloists featured as well! 

That said, the classical albums have the following "hints" that they ought to be treated differently (i.e. that the albumartist tag should be superseded):

* they have the composer tag set
* they have genre=classical
* they frequently have performer tags set
* Musicbrainz standards say that the artist tag on the tracks should be the same as the composer, so if this is true for all tracks on an album, probably the composer tag should be trusted

Any issues this might cause
---------------------------
This request is limited to adding some kind of "smart" artist functionality as a feature than can be selected for sorting, e.g. in the column content field of the paned browser preferences, so I can't imagine it causing any issues because it wouldn't affect anyone who doesn't choose to use it.

**Comment by Ironbalden** [comment]
You already can to something like that, quodlibet supports tag patterns, that means you can build basically any tag you want: for example if you want "composer" tag if genre is classical else the "artist" tag you can do something like this: <genre="classical"|<composer>|<artist>>. 
They are explained here:
https://quodlibet.readthedocs.io/en/latest/guide/tags/patterns.html

**Comment by afontenot** [comment]
Nice, I'll have a look at this and see if I can build something complicated enough to serve the purpose. If so I'll post another comment here about it, and maybe there would be interest in adding it as an official tag.

**Comment by Ironbalden** [comment]
Glad to help, please consider closing this issue since it seems to be solved

**Comment by nmusatti** [comment]
While I'm aware that @afontenot managed to work around the issue, I do think that the suggested approach should be the default one for the album collection browser.
