### ISSUE TITLE
Queue Only plugin breaks the queue in persistent mode

### ISSUE THREAD

**Issue by afontenot** [quodlibet/quodlibet#3385]
Steps to reproduce
------------------
1. Enable the Queue Only plugin and make sure it's activated (extremely counter-intuitive, you need to turn on shuffle mode for it it work - there are actually several bug reports from other people confused by this). 
2. Double click on a song to add it to the queue.
3. Double click on the song in the queue to start playing it.
4. While the song is playing, double click on another song in your library. Wait for the current song to end (or advance the position slider).

Expected Output
---------------
I expect the next song in the queue to start playing.

Actual Output
-------------
Quod Libet just stops playing anything when the current song ends. This *does not* happen when I add both songs to the queue, and then start playing the first one. In that case, both songs are played as expected.

Test System
-----------

### Which version of Quod Libet?
4.3.0

### Which operating system 
Arch Linux x86_64

**Comment by declension** [comment]
Thanks for the detailed report. 

I can't replicate this on master (0350f0647642d7e0a1d15cfd86dd52c220059b21) though. Do you have any other plugins enabled?

**Comment by afontenot** [comment]
> Thanks for the detailed report.
> 
> I can't replicate this on master ([0350f06](https://github.com/quodlibet/quodlibet/commit/0350f0647642d7e0a1d15cfd86dd52c220059b21)) though. Do you have any other plugins enabled?

Thanks for your reply. I do see this issue on master.

Enabled plugins (I believe most of these are enabled by default):

* APEv2 to IDE3v2
* Acoustic Fingerprint Lookup
* Advanced Preferences
* Application Information
* Change Language
* Queue Only
* Song Notifications

I've made a short screen recording of the issue: https://ipfs.io/ipfs/QmfFd1jgsUvUTsv6jd6RhW9yTqvwVEoHNoEcYbSxWGcYKM/quodlibet.mp4

Please let me know if I can do anything else to debug the issue.

**Comment by afontenot** [comment]
I've found that putting the queue in ephemeral mode does not show this issue - the next song plays as expected. This issue is with persistent mode.

**Comment by declension** [comment]
Good investigation! This explains a lot - persistent mode is new, plus I never use it personally so would explain. I'll update the title
