### ISSUE TITLE
Pausing with each track

### ISSUE THREAD

**Issue by paulinfo** [quodlibet/quodlibet#3386]
I'm new to the app & I love. it but Quodlibet keep on pausing within each music track.  I have Quod Libet 4.3.0 it keep pausing very badly then I try Quod Libet 4.1.0 it better but it occasionally. any ideas why?

**Comment by Ironbalden** [comment]
@paulinfo Hi, one thing that could be is if you have the 'one song' option activated under the repeat menu, could you please check if is this the case?

**Comment by paulinfo** [comment]
> @paulinfo Hi, one thing that could be is if you have the 'one song' option activated under the repeat menu, could you please check if is this the case?

Thankyou that worked & I'm happy

**Comment by Ironbalden** [comment]
@paulinfo glad to help, please consider closing this ticket since it's solved
