### ISSUE TITLE
Ratings shortcut conflicts with pane shortcut on version 4.3

### ISSUE THREAD

**Issue by wvhulle** [quodlibet/quodlibet#3387]
Steps to reproduce
------------------
Press CTRL-[0-9].

Expected Output
---------------
Rate current song.

Actual Output
-------------
Opens a different display mode.

Test System
-----------

### Which version of Quod Libet?
4.3

### Which operating system 
Manjaro

Additional Information
----------------------
I can find mentions of this shortcut in old documentation but it is missing from new documentation. How can I quickly rate my songs with a shortcut in the current version?

**Comment by CreamyCookie** [comment]
Sadly, this was replaced by the browser keyboard shortcut, but it should be easy to add it back with a slightly different shortcut.

Here's the relevant issue and a link to the commit that changed it: https://github.com/quodlibet/quodlibet/issues/265#issuecomment-605620614

Also check out my batch rating plugin #3247 which can be used for easily rating a bunch of songs (or a single one) that just played, outside of QL. You need to set up a keyboard shortcut though.

**Comment by lual** [comment]
As a workaround in Linux Manjaro you can set systemwide keyboard shortcuts 
Example: 
Set 5 Stars with `Ctrl+Alt+5` - triggers action:
`quodlibet --rating=1.0 && quodlibet --print-playing "<~~people~title>" | while read OUTPUT; do notify-send --icon=media-playback-start 'Rated  [*****]' "$OUTPUT"; done`

**Comment by CreamyCookie** [comment]
@lual Yeah, it seems much better to do this system wide, so you don't have to alt tab back to QL everytime. (Have done the same in KDE.)
