### ISSUE TITLE
Provide playlist information to event plugins

### ISSUE THREAD

**Issue by LoveIsGrief** [quodlibet/quodlibet#3388]
The proposed change
-------------------

It'd be very useful to provide which playlists a song is in for event plugins. It can either be a list of objects or simply strings.

Benefits of this change
-----------------------

In order to keep my favorites backed up and synced with my phone, I have an event plugin that copies favorites to a synced location. However, the playlist information is lost and I have no way of syncing that automatically because playlists aren't provided.

I also would like to export playlists in my main library as they are modified, not manually.
Additionally, this is a blocker for #3176 to sync playlists with MusicBrainz. Others might then be able to write plugins to sync their playlists with other external services

Any issues this might cause
---------------------------

I don't know how playlist information is stored or gathered. If it takes considerable time to search which playlists a song is in, then this would slow down things.

**Comment by declension** [comment]
If I've understood you, then this is already supported: `song("~playlists")` will give you just that (as a string).

See [Internal Tags documentation](https://quodlibet.readthedocs.io/en/latest/guide/tags/internal_tags.html#string-tags).

**Comment by LoveIsGrief** [comment]
Indeed, good sir!

Thank you very much 👌I'll close this when I'm back home.-- 
 Securely sent with Tutanota. Get your own encrypted, ad-free mailbox: 
 https://tutanota.com


11 Sep 2020, 10:56 by notifications@github.com:
