### ISSUE TITLE
Crash on startup with MPRIS plugin: "embedded null byte"

### ISSUE THREAD

**Issue by mr-smidge** [quodlibet/quodlibet#3395]
Steps to reproduce
------------------
Whilst playing background music with Quod Libet `4.3.0+1-0~ppa1~xenial` (from the stable PPA), I experienced a crash.  The same crash now occurs every time, immediately upon startup, making the application unusable.

Expected Output
---------------
The application should not insta-crash on startup, or at least offer a 'safe mode' to allow for recovery.

Actual Output
-------------
Quod Libet displays the following detail in the crash dialog:

```
ValueError: embedded null byte
------
Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/quodlibet/plugins/events.py", line 140, in __invoke
    handler(*args)

  File "/usr/lib/python3/dist-packages/quodlibet/ext/events/mpris/__init__.py", line 100, in plugin_on_song_started
    obj.song_started(song)

  File "/usr/lib/python3/dist-packages/quodlibet/ext/events/mpris/mpris2.py", line 222, in song_started
    ["PlaybackStatus", "Metadata"])

  File "/usr/lib/python3/dist-packages/quodlibet/util/dbusutils.py", line 303, in emit_properties_changed
    self.PropertiesChanged(iface, values, inval)

  File "/usr/lib/python3/dist-packages/dbus/decorators.py", line 314, in emit_signal
    message.append(signature=signature, *args)

ValueError: embedded null byte
```

In addition, there is the following console output:

```
E: 11.947: plugins.events.__invoke: Error during plugin_on_song_started on <class 'quodlibet.fake.plugins.mpris.MPRIS'>
E: 11.947: errorreport.main.errorhook: decorators.py:314:emit_signal: ValueError: embedded null byte
process 21184: arguments to dbus_message_get_path() were incorrect, assertion "message != NULL" failed in file ../../dbus/dbus-message.c line 3136.
This is normally a bug in some application using the D-Bus library.
process 21184: arguments to dbus_message_get_interface() were incorrect, assertion "message != NULL" failed in file ../../dbus/dbus-message.c line 3267.
This is normally a bug in some application using the D-Bus library.
process 21184: arguments to dbus_message_get_member() were incorrect, assertion "message != NULL" failed in file ../../dbus/dbus-message.c line 3353.
This is normally a bug in some application using the D-Bus library.
process 21184: arguments to dbus_message_get_destination() were incorrect, assertion "message != NULL" failed in file ../../dbus/dbus-message.c line 3490.
This is normally a bug in some application using the D-Bus library.
```

Test System
-----------

### Which version of Quod Libet?
`4.3.0+1-0~ppa1~xenial`

### Which operating system 
Linux Mint 18.3 (based on Ubuntu Xenial 16.04)

Other Relevant Details
--------

The only thing that comes to mind that might possibly be related  is a recent upgrade in dbus libraries via apt.  Here is the relevant extract from my `/var/log/apt/term.log` file:

```
Preparing to unpack .../libdbus-1-dev_1.10.6-1ubuntu3.6_amd64.deb ...
Unpacking libdbus-1-dev:amd64 (1.10.6-1ubuntu3.6) over (1.10.6-1ubuntu3.5) ...
Preparing to unpack .../dbus_1.10.6-1ubuntu3.6_amd64.deb ...
Unpacking dbus (1.10.6-1ubuntu3.6) over (1.10.6-1ubuntu3.5) ...
Preparing to unpack .../dbus-x11_1.10.6-1ubuntu3.6_amd64.deb ...
Unpacking dbus-x11 (1.10.6-1ubuntu3.6) over (1.10.6-1ubuntu3.5) ...
Preparing to unpack .../libdbus-1-3_1.10.6-1ubuntu3.6_amd64.deb ...
De-configuring libdbus-1-3:i386 (1.10.6-1ubuntu3.5) ...
Unpacking libdbus-1-3:amd64 (1.10.6-1ubuntu3.6) over (1.10.6-1ubuntu3.5) ...
Preparing to unpack .../libdbus-1-3_1.10.6-1ubuntu3.6_i386.deb ...
Unpacking libdbus-1-3:i386 (1.10.6-1ubuntu3.6) over (1.10.6-1ubuntu3.5) ...
```

However, Quod Libet worked fine for a number of hours playing music happily until the crash occurred.

Happy to offer additional info to help diagnose as required!

**Comment by lazka** [comment]
Sentry issue: [QUODLIBET-JG](https://sentry.io/organizations/quodlibet/issues/1730992776/?referrer=github_plugin)

**Comment by lazka** [comment]
you should be able to start with "quodlibet --no-plugins", then change the song, and then restart.

Looks like the ID3 tag is corrupt and this leaks null into QL. Can you send me the file containing `Clockwork (Robbie Rivera Ibiza Edit)` per mail maybe? -> reiter.christoph@gmail.com

**Comment by mr-smidge** [comment]
@lazka, Starting QL with `--no-plugins` and changing the song has successfully worked around the issue.  I've emailed you with a link to the problematic song.

It's entirely likely that this particular song has never been played in QL before, meaning its tag was almost certainly written by some other ancient (and possibly buggy) application.

**Comment by lazka** [comment]
Thanks!
