### ISSUE TITLE
Duplicates Browser Inacessible

### ISSUE THREAD

**Issue by pixelzerg** [quodlibet/quodlibet#3408]
Steps to reproduce
------------------
How do you get to the duplicates browser? I enabled the plugin in `File > Plugins` but I can't seem to access it. I assume it's supposed to show up in the "Browse" top menu dropdown, but it isn't there (see screenshot)

Expected Output
---------------
Expect duplicates browser to be in the "Browse" dropdown

Actual Output
-------------
It isn't there

Test System
-----------

### Which version of Quod Libet?
4.3.0

### Which operating system 
Arch Linux x86_64 5.7.7-arch1-1 

### If it's audio-related, what back-end?
GStreamer: 1.16.2.0

Additional Information
----------------------
[log.txt](https://github.com/quodlibet/quodlibet/files/4911400/log.txt)
![image](https://user-images.githubusercontent.com/30553505/87285816-e49ddc00-c4ef-11ea-81ce-6a86c2d8ddfb.png)

**Comment by pixelzerg** [comment]
OH there it is.. It's in a context menu like that :D
![image](https://user-images.githubusercontent.com/30553505/87286452-cbe1f600-c4f0-11ea-9bdd-247230563733.png)
FWIW I did read the docs and everything but it looks like I was just being dumb

**Comment by declension** [comment]
Hi. That's actually a `SongsMenuPlugin`, so you'll need to right-click on the songs you want to investigate and activate from there.

This is annoying / sub-optimal - but a fallout of #157 which one day will get implemented I guess (this would be a prime candidate)...

Maybe we should rename it to remove confusion - but I couldn't think of a better name at the time.

**Comment by pixelzerg** [comment]
@declension 
I understand. Thanks for your reply. I guess I got confused cause of the word "browser" and I thought it would bring up a new view like the other stuff under "Browse", in which it would go through the entire library and show all the duplicates. I don't think the song menu plugin way is necessarily sub-optimal though (since it means you can more intuitively select a subset of your library from which to find duplicates). It's just me being sleepy :D
