### ISSUE TITLE
Port Quod Libet to Android Devices

### ISSUE THREAD

**Issue by libregeek** [quodlibet/quodlibet#3411]
The proposed change
-------------------
Port the Quod Libet application to Android Platform to be used on Mobile devices.

Benefits of this change
-----------------------
Presently, non of the mobile music players provides full tag support. Quod Libet is one of the very few applications which allows users to sort and edit all music tags. It also supports multiple tags. Other editors provide only limited support of tags and doesn't have usable features to sort and play music.

Any issues this might cause
---------------------------
Do not know.

**Comment by declension** [comment]
Slightly related: #3277

**Comment by lazka** [comment]
I'd say that is out of scope of this project. We could of course recommend (with QL users in mind) existing Android apps in our documentation.

**Comment by Tamriel** [comment]
This player is able to filter by genre, then by artist: https://github.com/vanilla-music/vanilla

**Comment by declension** [comment]
Closing issue.

**Comment by libregeek** [comment]
Apologies for reopening this issue. I understand an Android app would be out of scope of this project. However, I have one question - Are there any Android app that can support multiple artists (as we have in QL), show composer, year and probably lyricist?

**Comment by irodionzaytsev** [comment]
> ## The proposed change
> Port the Quod Libet application to Android Platform to be used on Mobile devices.
> 
> ## Benefits of this change
> Presently, non of the mobile music players provides full tag support. Quod Libet is one of the very few applications which allows users to sort and edit all music tags. It also supports multiple tags. Other editors provide only limited support of tags and doesn't have usable features to sort and play music.
> 
> ## Any issues this might cause
> Do not know.

I am fully rooting on this. Exactly what we need. Have you found any apps that are compatible with QL?

**Comment by irodionzaytsev** [comment]
> I'd say that is out of scope of this project. We could of course recommend (with QL users in mind) existing Android apps in our documentation.

where are those found? I looked up "android" in the documentation, nothing shows up.
