### ISSUE TITLE
Nothing happens when query is typed in query bar

### ISSUE THREAD

**Issue by chuckmasterson** [quodlibet/quodlibet#3413]
Steps to reproduce
------------------
Run `quodlibet --debug` (this happens on a normal startup too). Type query in query box.

Expected Output
---------------
Normally the songs in the view are narrowed down as I type, or at least once I finish.

Actual Output
-------------
All songs that were in the view when I started typing, remain in the view.

Test System
-----------

### Which version of Quod Libet?
4.2.1

### Which operating system?
MX Linux 19.2

### If it's audio-related, what back-end?
N/A

Additional Information
----------------------
Oddly, this problem doesn't happen with saved queries. When I click on my saved query "Not Listened To", the terminal shows:

```
D: 28.996: Query.__init__: Creating query "#(playcount = 0)", called from SearchBarBox._update_query_from
D: 29.171: PlaylistModel.set: Filling view model with 5472 songs.
```

...and the view narrows down to songs with a playcount of 0. But if I type in "foo", I get

```
D: 9.508: Query.__init__: Creating query "", called from Query.validator
D: 9.509: Query.__init__: Creating query "f", called from Query.validator
D: 11.267: Query.__init__: Creating query "fo", called from Query.validator
D: 12.772: Query.__init__: Creating query "foo", called from Query.validator
```

...and nothing from `PlaylistModel.set`. If I change `(playcount = 0)` to `(playcount = 1)`, by highlighting `0` and typing `1`, the number of songs shown doesn't change, and in fact I have to delete the query and restart Quodlibet to make it show all 12,001 songs I have, instead of the 5,472 I haven't listened to.

If you can tell me a specific thing to look for in the debug logs, I'll paste it here. Otherwise, it's an enormous amount of text to trawl through, so I won't post it here, assuming I even could.

**Comment by chuckmasterson** [comment]
I was able to solve this by deleting `~/.quodlibet/config` and recreating my configuration. It was jolly inconvenient, though. No idea how my config got borked or where. I kept a copy and I can send it along if someone wants.

**Comment by frestr** [comment]
If you right-click the query bar and uncheck "Search after typing", you have to press enter to execute the query. Perhaps that option was unchecked?

**Comment by chuckmasterson** [comment]
Looks like that was it. Welp, not a bug, just a feature I activated accidentally. I don't remember ever intentionally right-clicking in the query bar - thanks for the pointer.
