### ISSUE TITLE
Thank you very much for the program!

### ISSUE THREAD

**Issue by mrkaban** [quodlibet/quodlibet#3427]
Thank you very much for the program distributed under a free open license! Added a program to a Russian-language site about free software, here is the [link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D0%BC%D1%83%D0%BB%D1%8C%D1%82%D0%B8%D0%BC%D0%B5%D0%B4%D0%B8%D0%B0/%D0%B2%D0%BE%D1%81%D0%BF%D1%80%D0%BE%D0%B8%D0%B7%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5/quod-libet-%D0%BC%D1%83%D0%B7%D1%8B%D0%BA%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9-%D0%BF%D0%BB%D0%B5%D0%B5%D1%80.html).

Please do not drop the project, this is a very interesting program!

**Comment by LoveIsGrief** [comment]
> Please do not drop the project

Are there plans on doing this? :open_mouth:

**Comment by CreamyCookie** [comment]
> Are there plans on doing this? :open_mouth: 

Not to my knowledge. And it's open source, so everyone could contribute, take over and make it better. 

I'm mostly only a here and there contributor, but thank you and enjoy!
