### ISSUE TITLE
Move to newer Python 3.6 / 3.7

### ISSUE THREAD

**Issue by declension** [quodlibet/quodlibet#3433]
The proposed change
--------------------

* Change the _minimum_ version to Python 3.6 or 3.7, and update any builds accordingly

Python 3.5 is long outdated now, and 3.6 and 3.7 bring quite a few benefits (3.9 is current latest at time of writing)

Benefits of this change
-----------------------
* Better typing support, including local variables (not a fan, but hey)
* [f-strings](https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-pep498), which are amazingly useful IMO
* The excellent [Pathlib](https://docs.python.org/3/whatsnew/3.6.html#pep-519-adding-a-file-system-path-protocol), which we could use everywhere, but would be a pretty mammoth effort.
* Maintained / non-deprecated versions are important

Any issues this might cause
---------------------------
* Might need to drop oldest Ubuntu / Debian support, though actually even [Buster is 3.7](https://wiki.debian.org/Python), 18.04 is on 3.6
* Windows should be fine AIUI

**Comment by CreamyCookie** [comment]
Another useful feature: In Python 3.6 dictionaries are ordered by default. In Python 3.7 this change was turned from implementation detail to an [official part of Python's language specification](https://docs.python.org/3/whatsnew/3.7.html#summary-release-highlights).

**Comment by lazka** [comment]
3.6 is a nobrainer, but 3.7 is also fine with me.
