### ISSUE TITLE
Create Sonos playlist plugin

### ISSUE THREAD

**Issue by declension** [quodlibet/quodlibet#3434]
The proposed change
-------------------
A playlist plugin that syncs from QL -> (Local) Sonos
Similar to the Squeebox plugin(S)

Benefits of this change
-----------------------
Users with Sonos systems who miss the lack of power and tooling to manage their playlists when running "natively" (or via [noson](https://github.com/janbar/noson-app)) would be able to maintain / curate / edit playlists on QL and sync them to Sonos.

Any issues this might cause
---------------------------
It's a plugin so not really.

Probably wants to use the [soco](https://soco.readthedocs.io/) as it seems  a _lot_ easier than OIDC auth and generally working out the Music APIs

**Comment by urielz** [comment]
This would be a sweet addition!

**Comment by declension** [comment]
Cool...  I've actually got a basic version working, just haven't pushed anywhere as it's not very polisedh

**Comment by urielz** [comment]
Nice, looking forward to try it out! At the very least I can help testing it if you need an extra hand.
