### ISSUE TITLE
'Show online' link for lyrics points to no Fandom Wiki that no longer exists

### ISSUE THREAD

**Issue by jplatte** [quodlibet/quodlibet#3444]
Sorry for deleting the issue template, but it really doesn't seem to fit here (nor does "Bug report").

I have no idea what happened to [lyrics.wikia.com](https://lyrics.wikia.com/) / [lyrics.fandom.com](https://lyrics.fandom.com/), but it doesn't seem to exist anymore :cry:  
Does anybody know what happened to it? (and scrape lyrics from? it never worked automatically for me :sweat_smile:)

Unless this is a temporary issue, QuodLibet will have to select a different site to link to.

**Comment by jplatte** [comment]
Not a temporary issue :disappointed: 

https://en.wikipedia.org/wiki/LyricWiki#Edit_lock_and_closure

**Comment by declension** [comment]
I guess we'll either need:
 1. a replacement API
 1. to just use the alternate URL (web search, currently duckduckgo.com)
 1. to remove the plugin

**Comment by declension** [comment]
Promising: https://musixmatch.com/

**Comment by declension** [comment]
Also 
* https://lyrics.ovh/ 
* http://www.chartlyrics.com/
* https://www.lololyrics.com/

**Comment by CreamyCookie** [comment]
Closing as the plugin was removed.
