### ISSUE TITLE
Move translations to online translation website

### ISSUE THREAD

**Issue by scootergrisen** [quodlibet/quodlibet#3450]
I suggest moving the translations to some online translation website like Weblate/Transifex etc.
That way its easy to check if the software is fully translated and easy when you just need to add 10 new strings or change a string without having to work with files and wait for pull requests etc.

When i have to maintain translations for alot of software i is nice when it is easy.

**Comment by lazka** [comment]
Do you have any suggestions for what to use?

**Comment by scootergrisen** [comment]
Seems other software currently use mostly:
Transifex
Launchpad
Weblate

I think they would all work fine.
Maybe i would try Weblate if i had to choose.

Seems Transifex is the most popular for the projects i translate.

**Comment by lazka** [comment]
Thanks, here are some docs to start: https://docs.weblate.org/en/latest/admin/continuous.html

**Comment by declension** [comment]
@lazka  I guess this is being done / is done now?

**Comment by lazka** [comment]
I've looked into it, but transifex fails to parse our .po files right now.. not sure

**Comment by declension** [comment]
Ah, I see

**Comment by lazka** [comment]
Weblate, while kinda slow, seems to work better. I'll have to requests free hosting though after I finish setting it up.

**Comment by lazka** [comment]
There is now a CI job that updates the .pot file every week https://github.com/quodlibet/quodlibet/commit/e6a00eb0ecfc1dcf61d0f22519dd26e79a2d2082

And a webhook which notifies weblate to pull changes.

**Comment by lazka** [comment]
Next steps:

* Wait for project approval
* Update the translation guide

**Comment by lazka** [comment]
Both done now -> https://twitter.com/QuodLibetApp/status/1392536335785791488
