### ISSUE TITLE
666 open QL issues 😈

### ISSUE THREAD

**Issue by declension** [quodlibet/quodlibet#3461]
Steps to reproduce
------------------
Look at Github issues

Expected Output
---------------
Please not _that_ number :)

Actual Output
-------------
Yes _that_ number actually

![Screenshot_2020-10-08 quodlibet quodlibet](https://user-images.githubusercontent.com/3322808/95430747-1a622d80-0944-11eb-8ac5-5d5a0300b3a9.png)

Obviously, as of opening this, it's currently "fixed" :laughing:
Perhaps this occurring on 31st October would have been spookier (though it may yet...)

**Comment by lazka** [comment]
Can't reproduce, I see 667 ;)

**Comment by lazka** [comment]
test

**Comment by declension** [comment]
Fixed :grin:  (for now...)

**Comment by declension** [comment]
:grin:
