### ISSUE TITLE
How does the "Skip Songs" plugin work?

### ISSUE THREAD

**Issue by Screwtapello** [quodlibet/quodlibet#3462]
I'm using Quod Libet 4.3.0 on Debian Testing, and I have the "Skip Songs" plugin enabled, with the threshold set to 0.24.

I also have the "Random Album Playback" plugin enabled, and nothing in my playlist, so when one album finishes QL jumps to another album to continue playing.

I have some albums where absolutely every track has a rating of 0 (right-click → Rating → 0.00), because they're recordings I want to keep, and that I occasionally want to listen to, but which I don't want to be played randomly. When the Random Album Playback plugin happens to pick one of those albums, I would *expect* the Skip Songs plugin to automatically skip every single track right to the end of the album, and then the Random Album Playback plugin would pick another album.

Instead, Quod Libet just plays every single zero-rated track, all the way through.

QL's "Plugin Errors" window doesn't mention anything related to Skip Songs, just "kakasi" and "mqtt" which I'm pretty sure are unrelated.

What am I missing? How is it supposed to work?

**Comment by declension** [comment]
Sounds like a bug. To be honest, compatibility _between_ plugins is much less tested.

That said, a few pointers:

 * Have you definitely got shuffle enabled?
 * And have you selected this new shuffle order (from the same bottom left shuffle widget)?

If yes and still not working - try running with `--debug` and you should see some log output when the plugin skips things

**Comment by Screwtapello** [comment]
Oh wow, I never even *considered* that Skip Songs might be part of the shuffle mode. I have enabled Shuffle Mode and switched to the Skip Songs Sub Mode, and I can confirm it works very nicely. Man, that's been bugging me for *years*.

I like the description change you made in 45596dd, but I'm not sure that would have been enough for me. I kept away from the shuffle mode because:

 1. I didn't realise the skip mode had anything to do with shuffle mode
 1. I want to listen to album tracks in order, not shuffled

That wording change addresses point 1, but not point 2. Perhaps something more like:

> Adds a shuffle mode that plays songs in order, but skips those with a rating equal to or below a given threshold.

"Adds a shuffle mode" I think would have given me the clue of where to find the plugin (and that it wasn't permanently enabled by the regular "enabled" box), and "in order" would have reassured me it wasn't a traditional shuffle mode.

**Comment by declension** [comment]
Thanks - these are good points. 

I think one win here would be to identify the types of plugins in the plugin window. Think there's a ticket for that, can't find it though.

And, of course, to document these types of plugins and how to use them more explicitly in the user guide.

**Comment by declension** [comment]
Have updated the text further, and it seems to be working, so closing ticket. Thanks for filing!
