### ISSUE TITLE
Unexpected sorting

### ISSUE THREAD

**Issue by fedelin** [quodlibet/quodlibet#3499]
Albums named "Greatest hits" are displayed into a single folder
![Capture d’écran du 2020-11-15 12-23-57](https://user-images.githubusercontent.com/16868546/99183840-2dd09780-273f-11eb-9e35-1bd32ffaede5.png)

Doublechecked that these albums are not effectively located into the same subfolder

### If it's audio-related, what back-end?

Additional Information
----------------------

**Comment by declension** [comment]
Hi @fedelin. Thanks for the report. 

Have you read https://quodlibet.readthedocs.io/en/latest/guide/faq.html?highlight=newer#i-have-two-albums-with-the-same-name-which-are-merged-in-the-album-list ?
