### ISSUE TITLE
Comment Tag missing

### ISSUE THREAD

**Issue by barraclm** [quodlibet/quodlibet#3500]
Steps to reproduce
------------------
Using Search Library Browser
Right click on Headings and select All Headers
There is no tag for Comments (there used to be)

Right click on a track and select Edit Tags
There is a Comment tag (with data in it).

Expected Output
---------------
It should be possible (it was) to display the Comment tag in the browser screen

Test System
-----------

### Which version of Quod Libet?
4.3
### Which operating system 
Kubuntu 20.10
![quodlibet](https://user-images.githubusercontent.com/25557978/99669822-8bc6ed00-2a67-11eb-9fc3-4d70e585a455.png)

Additional Information
----------------------

**Comment by declension** [comment]
Thanks for reporting @barraclm
