### ISSUE TITLE
Lyrics tags show up as a dozen tags of an identical type

### ISSUE THREAD

**Issue by IcedQuinn** [quodlibet/quodlibet#3502]
Steps to reproduce
------------------
Right click on a track with embedded lyrics and choose edit tags.

Expected Output
---------------
A single large tag containing all lines of the lyrics.

Actual Output
-------------
![image](https://user-images.githubusercontent.com/70673392/100411579-ce746080-3037-11eb-997e-c134225829ad.png)

Test System
-----------

### Which version of Quod Libet?
4.3.0

### Which operating system 
Void Linux

### If it's audio-related, what back-end?

Additional Information
----------------------

**Comment by declension** [comment]
Thanks for reporting. This is expected behaviour actually as newlines are the delimiter in QL for multiple tags. 

See https://github.com/quodlibet/quodlibet/issues/280 - there are some old discussions there on ideas for workarounds
