### ISSUE TITLE
Exported HTML contains link to irrelevant page

### ISSUE THREAD

**Issue by RoneelV** [quodlibet/quodlibet#3504]
Steps to reproduce
------------------
1. Enable *Export to HTML* plugin
2. Select 1 or more songs
3. Export to HTML 

Expected Output
---------------
Heading (My Quod Libet Playlist) should (or not) contain link to GitHub repo/org or Read the Docs page.

Actual Output
-------------
It links to [sacredchao.net](http://www.sacredchao.net/quodlibet/), which doesn't seem to be related to Quod Libet anymore.

Additional Information
----------------------
System info is irrelevant in this case. I'd be happy to make a PR. Exact code is located [here](https://github.com/quodlibet/quodlibet/blob/18e36f32240309d31fa034ab2a0d159d9297b7de/quodlibet/ext/songsmenu/html.py#L26).

**Comment by declension** [comment]
PR would be great, thanks!
