### ISSUE TITLE
Rename Feeds browser

### ISSUE THREAD

**Issue by declension** [quodlibet/quodlibet#3513]
The proposed change
-------------------
Renamed feed browser, e.g. to _Podcasts_

Benefits of this change
-----------------------
People don't recognise _feeds_ as much as _podcasts_ (or _audiobooks_) so often miss this feature entirely!

Any issues this might cause
---------------------------
Long-time users may be momentarily confused...

**Comment by CreamyCookie** [comment]
Can't think of any other audio feeds, so podcasts seems reasonable. ("Podcast Feeds" would also be possible, so long time users would find it immediately.)

**Comment by declension** [comment]
This seems like a good idea to me again. e.g see #4107
