### ISSUE TITLE
PPA repository missing Release file for Ubuntu 20.10

### ISSUE THREAD

**Issue by lixoo81** [quodlibet/quodlibet#3524]
Steps to reproduce
------------------
1. Add **ppa:lazka/ppa** repository to Ubuntu 20.10 (`sudo add-apt-repository ppa:lazka/ppa`)
2. Run `sudo apt update`

Expected Output
---------------
apt update completes successfully

Actual Output
-------------
apt update raises the following error:
```
E: The repository 'http://ppa.launchpad.net/lazka/ppa/ubuntu groovy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Test System
-----------

### Which version of Quod Libet?
4.3.0

### Which operating system 
Ubuntu 20.10

### If it's audio-related, what back-end?
n/a

Additional Information
----------------------

**Comment by declension** [comment]
@lazka Does the PPA need updating for Ubuntu 20.10?

**Comment by lazka** [comment]
Should be fixed now

**Comment by declension** [comment]
@lixoo81 can you retry and close if fixed?

**Comment by lixoo81** [comment]
I can confirm that this is fixed, thanks guys
