### ISSUE TITLE
Paned Browser preferences

### ISSUE THREAD

**Issue by raygamerkt** [quodlibet/quodlibet#3525]
Paned Browser preferences where you can setup small/wide/columnar view. You can change option but your choice will be not remember by app and will not save to config file

**Comment by DavidPerezIngeniero** [comment]
I don't understand.  Maybe a screenshot can help.

**Comment by raygamerkt** [comment]
in Paned Browser when You click on preferences icon:
![Untitled2](https://user-images.githubusercontent.com/62175758/104123838-a6259480-534d-11eb-80dc-7cbb69c99b3a.jpg)

You will get this prefs window
![Untitled](https://user-images.githubusercontent.com/62175758/104123839-a7ef5800-534d-11eb-8e2d-ef592621b58d.jpg)

I can choose between small/wide/columnar
I prefer columnar view and it works, but when i close program and open again this will set to small again and again i need to change it to get columnar view mode.

I have version 4.3.0 from lazka repo for ubuntu (using neon distro)
I think this problem appear from 4.3. Version 4.2 was free from this bug.

**Comment by declension** [comment]
I think this was fixed by https://github.com/quodlibet/quodlibet/pull/3365, so should be OK in 4.4.0

Please re-open if the problem persists
