### ISSUE TITLE
Changes to metadata are lost when a song ends

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [quodlibet/quodlibet#3534]
Steps to reproduce
------------------
Play a song.

Edit its metadata with Alt-Enter.

I change some tags.
When the song finishes, all my changes become lost.

Expected Output
---------------
When another song is playing, nothing special happens to the edited tags

Actual Output
-------------
Already explained

Test System
-----------

### Which version of Quod Libet?
4.3.0

### Which operating system 
KDE Neon based on Ubuntu 20.04

### If it's audio-related, what back-end?
Unrelated

Additional Information
----------------------
If I rate the edited song in the grid or add it to a playlist, I also lose my changes.

**Comment by declension** [comment]
Is this a duplicate of #3484 @DavidPerezIngeniero ?

**Comment by declension** [comment]
Closing as duplicate for now - but please re-open and clarify if not.

**Comment by DavidPerezIngeniero** [comment]
Yes it is a duplicated
