### ISSUE TITLE
I lose the Waveform seekbar

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [quodlibet/quodlibet#3535]
Steps to reproduce
------------------
I activate the Waveform seekbar plugin
Play some songs.
I don't know how but the waveform seekbar doesn't show any more the wave form.
Maybe some song is played with a format that spoils the plugin behavior.

Expected Output
---------------
The waveform is always shown

Actual Output
-------------
In order to restore the waveform, I have to disable the plugin and reenable it again.
I've found no other solution.

Test System
-----------

### Which version of Quod Libet?
4.3.0

### Which operating system 
KDE Neon based on Ubuntu 20.04

### If it's audio-related, what back-end?
The default one.

**Comment by declension** [comment]
Is it possible you have the _other_ seekbar plugin enabled?

**Comment by declension** [comment]
Also, could you have a look at running with `--debug` and seeing if there's anything interesting mentioned?

**Comment by DavidPerezIngeniero** [comment]
Whenever I restart QL, I lose the wave seekbar.

**Comment by DavidPerezIngeniero** [comment]
I had also enabled the alternative seekbar.
Now it works better.
