### ISSUE TITLE
Remove album from library indefinitely

### ISSUE THREAD

**Issue by aritorhamo** [quodlibet/quodlibet#3537]
The proposed change
-------------------
When I remove an album from the library without deleting it (using the second mouse button menu – I'm not sure what the name of the function is in English, as I use another language version), the album comes back when the library is refreshed. I wonder if there's a way to remove the album from the library so that it doesn't come back until I want it to. If there currently isn't a way, could it be possible to add it as a feature?

Benefits of this change
-----------------------
My use case is that I have several versions of some of the albums in my collection, and I don't necessarily want them all to be listed all the time. On the other hand I also wouldn't want to move them to a different place in my file system just because of this listing issue.

Thanks!

**Comment by Ironbalden** [comment]
As a workaround you can use the global filter option under Preferences > Browsers, here you can set a filter to the whole collection and hide the songs you don't want to see.

**Comment by aritorhamo** [comment]
> As a workaround you can use the global filter option under Preferences > Browsers, here you can set a filter to the whole collection and hide the songs you don't want to see.

I don't know how to do that. I tried to place a filter there, but I was only able

**Comment by aritorhamo** [comment]
> As a workaround you can use the global filter option under Preferences > Browsers, here you can set a filter to the whole collection and hide the songs you don't want to see.

Thank you for replying. I'm not sure if I understand what you mean. Do you perhaps mean that I tag all songs in my collection with one and same tag, except the songs that I don't want to appear in Quod Libet, and then set a global filter for the tag I just created?
