### ISSUE TITLE
Duplicate playlists on DnD of empty area

### ISSUE THREAD

**Issue by Meriipu** [quodlibet/quodlibet#3538]
Steps to reproduce
------------------
Dragging and dropping the empty area at the bottom of the list of playlists onto itself.

Expected Output
---------------
Nothing.

Actual Output
-------------
A new playlist with all the tracks of the currently selected (but not dragged) playlist is created.

Test System
-----------

### Which version of Quod Libet?
b1429c65b1d91789daffd9eef5274b99b4789660

### Which operating system 
Linux with a twm-derivative window manager (focus follows the mouse cursor). Probably not relevant.

**Comment by declension** [comment]
@Meriipu could you check this works for you?

**Comment by Meriipu** [comment]
seems to solve the issue

thanks
