### ISSUE TITLE
Can't successfully finish run of test suite on fresh install of Fedora 33

### ISSUE THREAD

**Issue by Phil305** [quodlibet/quodlibet#3539]
Hey, I'm trying to run the tests for the **master** branch of Quod Libet, but it doesn't seem to work on Fedora 33

Also, this is my first bug report, so please let me no if there's any info I left out, thanks!

Steps to reproduce
------------------
1. Install dependencies:
dnf install cairo-devel python3-devel gobject-introspection-devel cairo-gobject-devel Xvfb

2. Setup virtualenv:
poetry install

3. Run tests:
poetry shell
./setup.py test

Expected Output
---------------
Tests pass

Actual Output
-------------
Tests hang indefinitely at **test_flake8.py**
![image](https://user-images.githubusercontent.com/19247724/104874428-f8078500-5920-11eb-98a4-27d519a1abc5.png)

Oddly enough, if I run that test directly via **pytest -k test_flake8**, it finishes successfully.
![image](https://user-images.githubusercontent.com/19247724/104944388-21f29300-5985-11eb-9cdf-2ff6b36ea6d2.png)

If I delete **tests/quality/test_flake8** and run the test suite again, if fails on the **tests/test_po.py**
![image](https://user-images.githubusercontent.com/19247724/104948496-6123e280-598b-11eb-8ad6-16474e97b16f.png)

Test System
-----------

### Which version of Quod Libet?
4.4.-1

### Which operating system 
Fedora 33

**Comment by declension** [comment]
See related #3542

**Comment by declension** [comment]
As per thread - can you try installing a older `gettext` (`0.19.x` maybe)? this might work around things

**Comment by declension** [comment]
Re: hanging tests. Previously this is the test fixture finding thousands of modules from the virtualenv that it, err, shouldn't. I added exclusions, but relies on predictable directory names a bit (e.g. `.venv`). 
So one other thing to try:

* Remove your (`poetry env remove ...` , or manually delete using info from `poetry debug`)
* `poetry config virtualenvs.in-project true`
* `poetry install`
* `poetry run pytest` (or the other way)

HTH

**Comment by Phil305** [comment]
Thanks @declension, no hanging tests anymore!

In relation to the `gettext` "error", it's just a warning, and `xgettext` itself returns and exit code of 0...

Hey @lazka , sorry to bother, but I see in commit `dec211e5fccbd0cfdf50de4cdc8a554d77db165f` you added `gettextutil.create_pot(PODIR, strict=True)` with the message `gettext: only fail on xgettext warnings when testing and not when building`

Is there any value in failing on that **gettext** warning?
Is there a major issue if **xgettext** uses a fallback ITS rule, to the point where the test should fail, 
or would it be acceptable to just print the warning and keep going with the next tests?

If the warning is really serious, I'd be down to dig into learning about **gettext** to try to figure out how to fix it.
But if it's just a warning and not a serious problem, maybe I can make the test less strict?

Maybe line 137 in `gdist/gettextutil.py` could be updated from `if strict and stderr:` to`if strict and stderr and p.returncode != 0:`?
With that change all my tests pass on Fedora 33

**Comment by lazka** [comment]
> Is there any value in failing on that **gettext** warning?

We don't know about certain xgettext errors otherwise which lead to broken output.

> Is there a major issue if **xgettext** uses a fallback ITS rule, to the point where the test should fail,

I don't know, that error seems unrelated to what we use gettext for. Maybe a Fedora packaging issue.

> or would it be acceptable to just print the warning and keep going with the next tests?

yeah, given your problem I agree

**Comment by lazka** [comment]
I've created #3545
