### ISSUE TITLE
Column layout don't remember the wide setting after restart

### ISSUE THREAD

**Issue by Sr343785tyh** [quodlibet/quodlibet#3540]
Steps to reproduce
------------------
Reinstall Manjaro
Install and start Quodlibet
In "Paned Browser Preferences" check the wide box.
Click Apply
Exit program with going to File -> Quit
Start Quodlibet
Quodlibet forgot the wide setting

Expected Output
---------------
After setting the Paned Browser Preferences to wide it should remember it after a restart

Actual Output
-------------
After setting the Paned Browser Preferences to wide it forgot the setting after a restart

Test System
-----------

### Which version of Quod Libet?
4.3.0

### Which operating system 
Linux 5.9.16-1 MANJARO

Additional Information
----------------------
simillary bug https://github.com/quodlibet/quodlibet/issues/3319
before time i'm used old version Quod Libet without update but python was updated and old version not work.

**Comment by declension** [comment]
I think this is fixed now, with 4.4.0? https://github.com/quodlibet/quodlibet/pull/3365

**Comment by declension** [comment]
If not please reopen

**Comment by Sr343785tyh** [comment]
> If not please reopen

my mistake, that's fixed, work perfect
