### ISSUE TITLE
Build automation for Fedora

### ISSUE THREAD

**Issue by declension** [quodlibet/quodlibet#3542]
The proposed change
-------------------
Some automation is added for building on Fedora-like systems (ideally Github Actions CI)

Benefits of this change
-----------------------
Contributors on these systems have fewer problems

Any issues this might cause
---------------------------
GH actions only support Ubuntu, so might need to be Docker-in-Docker....

**Comment by declension** [comment]
Note to self: Fedora 33 comes with much newer gettext (`0.21.x`) than we generally currently use (`0.19.x`)

**Comment by lazka** [comment]
things work fine here with gettext 0.21.x on Arch

**Comment by lazka** [comment]
Here is the old Docker image we used before, might help with figuring out some package names: https://github.com/quodlibet/quodlibet/blob/quodlibet-4.3/.docker/Dockerfile.fedora28

**Comment by declension** [comment]
Heh, wish I'd seen that last week actually, but got there mostly

**Comment by Phil305** [comment]
I tested on Fedora 33; these are the packages that need to be installed before **poetry install** works for me;

```dnf install cairo-devel python3-devel gobject-introspection-devel cairo-gobject-devel Xvfb -y```

And then the steps @declension mentioned allowed the **test_flake8** test to run without hangin, 
```poetry config virtualenvs.in-project true
poetry install
poetry run pytest
```

If I'm the only one running on Fedora 33 as primary OS, I can work on getting Github Actions CI working for it

**Comment by Phil305** [comment]
So far, I've got a Dockerfile that builds Fedora 33 with all the dependencies needed to run most of the tests.
I'm hitting an error in the Docker container that I don't get on my laptop, hoping someone can help me troubleshoot.

(I also made sure I have *gvaluetypes.h* in the container, which contains the *G_VALUE_HOLDS_INT* definition, so not sure why I'm getting the `test_undo_space` warning)

```tests/test_qltk_entry.py::TUndoEntry::test_undo_space
  /quodlibet/.venv/lib64/python3.9/site-packages/gi/overrides/Gtk.py:218: Warning: g_value_get_int: assertion 'G_VALUE_HOLDS_INT (value)' failed
    return super(Editable, self).insert_text(text, -1, position)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================================================================================================== short test summary info ===========================================================================================================
FAILED tests/test_formats__audio.py::TAudioFile::test_is_writable - AssertionError: True is not false
FAILED tests/test_operon.py::TOperonAdd::test_permissions - AssertionError: False != True : (0, '', '')
FAILED tests/test_operon.py::TOperonPrint::test_permissions - AssertionError: False != True : (0, 'Silence\n', '')
FAILED tests/test_util_atomic.py::Tatomic_save::test_readonly - AssertionError: OSError not raised
FAILED tests/plugin/test_mediaserver.py::TMediaServer::test_entry_name - dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ExecFailed: /usr/bin/dbus-launch terminated abnormally without any error message
... (a bunch more related errors)
============================================================================== 33 failed, 4287 passed, 41 skipped, 123 warnings, 53 errors in 114.20s (0:01:54) ==============================================================================

```

I cut out a lot of the extra error messages since I think theyre related to the first ones,
but if it'd be helpful, I can include the entire error output.

Here's the Dockerfile, in case it's helpful
[Dockerfile.fedora33](https://gist.github.com/Phil305/75d1e21299facfe7d7db79e057c58213)
