### ISSUE TITLE
Podcasts management

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#355]
Original [issue 355](https://code.google.com/p/quodlibet/issues/detail?id=355) created by pikiweb on 2009-11-29T12:10:40.000Z:

It would be great if QuodLibet could manage a Library of Podcasts.

I mean, the behaviour of QuodLibet now is: check for updates in the feed.
If user selects, download the mp3 files.
But still, if i open a feed entry, program will search for it on the
internet, even if I've download the entry.
Old entries wouldn't be available anymore.

Why can't it manage Podcasts as in a Library?? That would work like this:
- check for updates in the feed
- if user chooses to download an mp3, quodlibet should remember where it
  has been downloaded, and next time i'll try to open that entry from the
  feed, it should look for the downloaded file, and only if not available
  retrieve it on internet
- user could also be able to choose to download all the files
  automatically. in that case, a directory will be chosen, and quodlibet will
  download the files there. then all the files and their infos will be
  available, even when disappeared from feed (e.g. old entries)

I guess it's the same as most programs behaviour (itunes as well as
rhythmbox or listen and so on) but I haven't really used any of them.

Hope it's possible to understand what I mean :)

**Comment by pschwede** [comment]
+1 for local download
-1 for download to music library
+1 for gpodder support (OMPL support and managing podcast lists over gpodder API)

**Comment by nodiscc** [comment]
@lazka I think this could be closed. The current Audio Feeds browser satisfies these requirements:

 * Manage a Library of Podcasts
 * Download feed items to local filesystem (right-click on item, select `Download`)
 * Download to library: just save the downloaded file inside you library's path...

I think separate issues can be opened for the following aspects:
 * Allow resuming download of feed items
 * Automatically download all items from a feed
 * OPML support: https://github.com/quodlibet/quodlibet/issues/1276
 * Allow synchronization with gpodder.net
