### ISSUE TITLE
Support Pipewire output

### ISSUE THREAD

**Issue by BryanQuigley** [quodlibet/quodlibet#3551]
The proposed change
-------------------
Add Pipewire option like exists for JACK audio

Benefits of this change
-----------------------
Let's users use Pipewire directly if they want to for audio. The plan is for Pipewire is eventually going to replace both Jack and PulseAudio.

Any issues this might cause
---------------------------
The transition from Jack/PulseAudio to Pipewire is in it's early stages. Volume/Output/Input management is much easier with existing pulseaudio tools at the moment.

**Comment by declension** [comment]
Doesn't Pipewire provide a drop-in Jack server replacement though?

**Comment by BryanQuigley** [comment]
Yes, PipeWire can handle apps that use ALSA, JACK, and PulseAudio transparently.  (I've only tested pipewire-pulse with quod libet personally though and it just worked).  This is about giving an option to use PipeWire directly.

**Comment by declension** [comment]
I'm now not sure how this will work - Gstreamer itself doesn't look like it'll support pipewire directly [AFAICT from plugins](https://gstreamer.freedesktop.org/documentation/plugins_doc.html?gi-language=python) (and QL depends on Gstreamer)

**Comment by declension** [comment]
Closing unless this changes or I've missed something in which case we can reopen
