### ISSUE TITLE
Cyrillic encoding

### ISSUE THREAD

**Issue by Ygarr** [quodlibet/quodlibet#3555]
Request add ability to correct view CP1251(Cyrillic) Windows symbols

**Comment by lazka** [comment]
Could you share a screenshot?

**Comment by Ygarr** [comment]
Here it is

https://share.riseup.net/#6rFE3u1YsqAcHKsR3dCsLA

**Comment by lazka** [comment]
That suggests your MP3 (I guess) files have the wrong encoding set. You can enable the "Convert Encodings" plugin to fix those files manually in the tag editor.

If you don't think that's the problem then you need to provide an example audio file so we can try to reproduce the issue.

**Comment by Ygarr** [comment]
Sorry didn`t find such plugin but only "Tags from path". This file contain both wrong and right Artist -Title
https://mega.nz/file/OF4kHBxJ#w_8vJszYuhln5vxGus4GctSHIP4dt97ADq1r3jAvjyw

**Comment by lazka** [comment]
Thanks. That file has completely messed up encoding. It's marked as utf-16, but is in reality cp1251 with every second byte zeroed out. Likely some tool tried to convert ASCII to utf-16 while not knowing the source was CP1251..

```
>>> 'Ðåàêöèÿ íà ôîíå ïîëèòèêè'.encode("utf-16-le").decode("cp1251").replace("\x00", "")
'Реакция на фоне политики'
```

There is no easy way to fix this automatically.
