### ISSUE TITLE
External plugins not showing in MacOS / plugin dev page

### ISSUE THREAD

**Issue by BraveSentry** [quodlibet/quodlibet#3559]
I tried to include an external plugin by creating ~/.config/quodlibet/plugins and putting the plugin.py file in that folder (see [here](https://github.com/quodlibet/quodlibet/issues/3426#issuecomment-778738322). That worked in Linux Mint, but not on the Hackintosh on the same machine. Is the location for plugins different on Mac? If so, it should say so on [the plugin dev page](https://quodlibet-frestr.readthedocs.io/en/latest/development/plugins.html).

One related minor issue: The links at the bottom of [the plugin dev page](https://quodlibet-frestr.readthedocs.io/en/latest/development/plugins.html) are broken.

**Comment by declension** [comment]
We've pretty much deprecated the plugins-in-home-dir some time ago, when plugins got moved into the main module. 

It does still work in some cases (clearly) but it's always recommended to run from source if you're developing plugins now.

I'll update the docs around this actually, though I don't know anything about how the MacOS build bundles the plugins now. 

:information_source:  those last links (to plugin dev page) are not the official build of the docs, probably why the link is dead.
