### ISSUE TITLE
Consider releasing version 4.4

### ISSUE THREAD

**Issue by CreamyCookie** [quodlibet/quodlibet#3560]
The proposed change
-------------------
Not sure if there are any changes in progress that would be reasonable to include before a release, but I think a new version would make sense as the last one has been in `2020-02-22`. 

Benefits of this change
-----------------------
Users would be able to enjoy new plugins and other improvements that have been made.

Any issues this might cause
---------------------------
Not really issues, but takes time to put together the release notes and publish the new version.

**Comment by declension** [comment]
See related: #3465

**Comment by lazka** [comment]
new release is out

**Comment by bassstorm** [comment]
Big up!

**Comment by CreamyCookie** [comment]
@lazka @declension (and any other contributors) Thanks!

Link to the changelog: https://quodlibet.readthedocs.io/en/latest/changelog.html

**Comment by declension** [comment]
Yes, that changelog turned out to be pretty massive :grin:
