### ISSUE TITLE
External rating updates are not visible

### ISSUE THREAD

**Issue by bassstorm** [quodlibet/quodlibet#3561]
Steps to reproduce
------------------
0. Enable "Save ratings and play counts in tags" for _example@email.com_
1. Make sure QL saved rating to FLAC file (RATING:example@email.com=0.8)
2. Exit QL
3. Update above file in foobar2000, by just changing the value (RATING:example@email.com=1.0)
4. Open QL, execute library re-scan

Expected Output
---------------
RATING:example@email.com=1.0

Actual Output
-------------
RATING:example@email.com=0.8
(though in actual file the value is _1.0_)

Test System
-----------

### Which version of Quod Libet?
community/quodlibet 4.3.0-4

### Which operating system 
Manjaro Linux

### If it's audio-related, what back-end?
not related

Additional Information
----------------------
QL sees ratings added by fb2k when files are new to the library (i.e. after first scan of just added).

Also, though QL recognizes change in file, but for some reason that is not reflected on UI (both in primary window and in file details popup). Below's the log -- first event for updated genre (visible, ok), second event for updated rating (not visible).
```
D: 09.468: PlaylistModel.set: Filling view model with 11 songs.
D: 80.993: LibraryEvent._log: IN_CLOSE_WRITE for "1-05. Biosphere - Miniature Rock Dwellers.flac" on /run/media/user/storage/Music/B/Biosphere/Biosphere (2000) Cirque
D: 80.994: SongFileLibrary._load_item(<libraries.SongFileLibrary object at 0x7ff5a2033d80 (quodlibet+library+libraries+SongFileLibrary at 0x5604bb9d9360)>): Loading '/run/media/user/storage/Music/B/Biosphere/Biosphere (2000) Cirque/1-05. Biosphere - Miniature Rock Dwellers.flac'.
D: 81.012: SongFileLibrary._load_item(<libraries.SongFileLibrary object at 0x7ff5a2033d80 (quodlibet+library+libraries+SongFileLibrary at 0x5604bb9d9360)>): Reloaded '/run/media/user/storage/Music/B/Biosphere/Biosphere (2000) Cirque/1-05. Biosphere - Miniature Rock Dwellers.flac'.
D: 81.014: library.libraries.__changed: Updating affected albums for 1 items
D: 09.717: LibraryEvent._log: IN_CLOSE_WRITE for "1-05. Biosphere - Miniature Rock Dwellers.flac" on /run/media/user/storage/Music/B/Biosphere/Biosphere (2000) Cirque
D: 09.717: SongFileLibrary._load_item(<libraries.SongFileLibrary object at 0x7ff5a2033d80 (quodlibet+library+libraries+SongFileLibrary at 0x5604bb9d9360)>): Loading '/run/media/user/storage/Music/B/Biosphere/Biosphere (2000) Cirque/1-05. Biosphere - Miniature Rock Dwellers.flac'.
D: 09.735: SongFileLibrary._load_item(<libraries.SongFileLibrary object at 0x7ff5a2033d80 (quodlibet+library+libraries+SongFileLibrary at 0x5604bb9d9360)>): Reloaded '/run/media/user/storage/Music/B/Biosphere/Biosphere (2000) Cirque/1-05. Biosphere - Miniature Rock Dwellers.flac'.
D: 09.736: library.libraries.__changed: Updating affected albums for 1 items
```

**Comment by declension** [comment]
Is this just with FLACs?

**Comment by bassstorm** [comment]
@declension
FLAC and OGG Audio

**Comment by MikhaMo** [comment]
Same behavior with MP3 
OS X 10.15.7 
Quodlibet 4.3.0

**Comment by bassstorm** [comment]
@declension 
Hey Nick, did you manage to have a look quick by chance? Just to have an idea if that's something not massive and we could expect an improvement in foreseeable future.
I just navigated to that `libraries.py`, but it's a bird language to me I'm afraid :(

**Comment by declension** [comment]
> Hey Nick, did you manage to have a look quick by chance? Just to have an idea if that's something not massive and we could expect an improvement in foreseeable future.

Looking now. There's a missing step to replicate here though - after re-scanning the library (4) what do you actually _do_ to get an output of `RATING:example@email.com=1.0`?
It looks like `mid3v2` or another program is being used to examine the file contents, or is this just shorthand? What happens if you search for the file in the default QL browser, with a rating column enabled - presumably all stars are lit (max rating)? 

> Also, though QL recognizes change in file, but for some reason that is not reflected on UI (both in primary window and in file details popup). Below's the log -- first event for updated genre (visible, ok), second event for updated rating (not visible).

This bit is probably a bug. The plugin (auto library scanning) I haven't used / tested it for ages, so not sure it's fully working still TBH (though no major bugs reported that I remember). That said, the log _indicates_ it's doing the right thing, so might be problems processing `changed` signals in the view / library. Which, depending on the answers to the above questions, may mean this is actually the same bug after all...

**Comment by bassstorm** [comment]
> It looks like `mid3v2` or another program is being used to examine the file contents, or is this just shorthand?

Yes, correct, the change is visible by external tools like _operon_ (I started to explore workarounds which resulted in #3605) or _metaflac_.

> What happens if you search for the file in the default QL browser, with a rating column enabled - presumably all stars are lit (max rating)?

I'm afraid it stays like before, i.e. 4 stars. Even after manual execution of _Plugins -> Rescan Songs_. So, yes, I believe the root cause is not in auto library scanning...

**Comment by declension** [comment]
Oh, but did you persist the song's tags _explicitly_? It's a little-understood gotcha, but you do often need to do this for ratings and a few other not-directly editable tags :disappointed: 

You can trigger this using the _Update Tags in Files_ plugins (via right clicking on the song(s)), or perhaps easier enable the newer _Auto Update Tags in Files_ plugin to have this done automatically.

Really this should "just happen", there are some issues in the list somewhere.

Of course might not be this...

**Comment by declension** [comment]
Could you dump the full tags before and after the changes, e.g. with `mid3v2` or `metaflac`? It sounds like there are multiple ratings tags going on here

**Comment by bassstorm** [comment]
Sure! Here you're are. First list contains rating added by QL itself. The rest is straight.
```
[m2@m2 Library]$ metaflac --list --block-type="VORBIS_COMMENT" "./Žagar/Žagar - The Prophet Is A Fool.flac"             
METADATA block #2
  type: 4 (VORBIS_COMMENT)
  is last: false
  length: 286
  vendor string: reference libFLAC 1.3.2 20170101
  comments: 11
    comment[0]: rating:example@email.com=0.6000000000000001
    comment[1]: genre=electronica
    comment[2]: genre=post rock
    comment[3]: artist=?agar
    comment[4]: title=The Prophet Is A Fool
    comment[5]: date=2007
    comment[6]: album=Cannot Walk Fly Instead
    comment[7]: tracknumber=2
    comment[8]: tracktotal=14
    comment[9]: discnumber=1
    comment[10]: disctotal=1
[m2@m2 Library]$ metaflac --remove-tag="rating:example@email.com" --set-tag="rating:example@email.com=1.0" "./Žagar/Žagar - The Prophet Is A Fool.flac"
[m2@m2 Library]$ metaflac --list --block-type="VORBIS_COMMENT" "./Žagar/Žagar - The Prophet Is A Fool.flac"
METADATA block #2
  type: 4 (VORBIS_COMMENT)
  is last: false
  length: 271
  vendor string: reference libFLAC 1.3.2 20170101
  comments: 11
    comment[0]: genre=electronica
    comment[1]: genre=post rock
    comment[2]: artist=?agar
    comment[3]: title=The Prophet Is A Fool
    comment[4]: date=2007
    comment[5]: album=Cannot Walk Fly Instead
    comment[6]: tracknumber=2
    comment[7]: tracktotal=14
    comment[8]: discnumber=1
    comment[9]: disctotal=1
    comment[10]: rating:example@email.com=1.0
[m2@m2 Library]$ operon list -t "./Žagar/Žagar - The Prophet Is A Fool.flac"
Title:The Prophet Is A Fool:title
Artist:Žagar:artist
Album:Cannot Walk Fly Instead:album
Date:2007:date
Disc:1/1:discnumber
Genre:electronica:genre
Genre:post rock:genre
Rating\:Example@Email.Com:1.0:rating\:example@email.com
Track:2/14:tracknumber
```

Just let me know if there's anything I could help you with. (I assumed video record would be too much, but if that helps...)

**Comment by bassstorm** [comment]
@declension
I managed to debug the code a little. Probably found where something strange happens.
In `quodlibet.formats._audio.AudioFile.reload` file is re-read
`self.__init__(fn)`
but after proper new rating extraction it's immediately overridden by old value for no obvious reason
`self.update(saved)`...
Do you have an idea why's that?

**Comment by declension** [comment]
Good catch!

Whilst I don't know that part of the code well, it's probably because many internal tags are held in the songs pickle, so reloading from file would trash them unnecessarily. Some tags, however, (including `~#rating`) can be persisted in-file for some formats for some users... leading us to this.

I'm having a look

**Comment by bassstorm** [comment]
> Some tags, however, (including `~#rating`) can be persisted in-file for some formats for some users...

Yes, perhaps the most straight and transparent way to keep library in sync among multiple systems (lin, win, macos) / locations (home, work).

> I'm having a look

Thanks for that. I'm afraid implementing a proper fix is beyond my python skills as well as code base knowledge :)
