### ISSUE TITLE
Deleted playlists keep showing again after Quodlibet restart

### ISSUE THREAD

**Issue by nowhere-girl** [quodlibet/quodlibet#3563]
Steps to reproduce
------------------
Tried to delete a playlist, playlist get deleted right away.

Expected Output
---------------
Playlist should be deleted forever, even after I restart Quodlibet or my system.

Actual Output
-------------
Playlist re-appears after restarting Quodlibet. There's no error, playlist just re-appears as an empty playlist exactly with the same name as the deleted one, sometimes even appear double (both with the same name as well).

Test System
-----------

### Which version of Quod Libet?
Version 4.3

### Which operating system 
Ubuntu 20.04

Additional Information
----------------------
This problem has been bugging my system since I was still using Ubuntu 18.04. I have attached a screenshot, taken after I deleted a playlist, closed Quodlibet and then opened it again. The deleted playlist re-appears.

![quodlibet](https://user-images.githubusercontent.com/62411431/108521895-c9554380-72fe-11eb-92d7-c61a455623ce.png)

**Comment by Meriipu** [comment]
I remember I briefly ran into this while I was testing a new confirmation for some playlist actions but I think it went away after I changed the version I was working on to a later one so I did not think much more of it.

Perhaps it has been fixed in a commit after the one that is 4.3?

**Comment by nowhere-girl** [comment]
> Perhaps it has been fixed in a commit after the one that is 4.3?

@Meriipu Wait, I don't get it. Isn't the latest release is 4.3.0 ? Mine is currently 4.3.0 as well. What do you mean by "after the one that is 4.3" ?

**Comment by Meriipu** [comment]
> > Perhaps it has been fixed in a commit after the one that is 4.3?
> 
> What do you mean by "after the one that is 4.3" ?

The latest release is 4.3.0 but there has been a lot of changes (commits) since then.
Released versions (such as 4.3.0) refer to a specific commit and is likely what most distributions base the package in their repositories on.
Recent commits that have not made it into a release yet are usable too, but less convenient to install from than the pre-packaged versions in package managers.

There has been talk about putting together a new release at some point (#3560 #3465).

**Comment by nowhere-girl** [comment]
@Meriipu Got it ! I already installed the latest commit. Now in the app it says version 4.4-1 already, it seems like the delete function for Playlist is working properly now, therefore I will close this thread, thank you !

**Comment by Meriipu** [comment]
Maybe worth noting that from what I have gathered, playlists are in recent versions migrated to a different format (.xspf) on load.
Earlier versions of quodlibet (4.3.0) do not read these xspf-playlists, so running an older version of quodlibet after they have been migrated, those playlists will look empty (until opened in a newer version again).
