### ISSUE TITLE
msys2 build is breaking due to missing setuptools

### ISSUE THREAD

**Issue by declension** [quodlibet/quodlibet#3564]
Steps to reproduce
------------------
* Make a PR with no real code changes
* Wait for builds to complete

Expected Output
---------------
* Passes all jobs

Actual Output
-------------
`msys2` job fails during _Install additional dependencies_ step:
```
ModuleNotFoundError: No module named 'setuptools'
```

**Comment by declension** [comment]
e.g. this [build for #3558](https://github.com/quodlibet/quodlibet/pull/3558/checks) ([raw logs](https://pipelines.actions.githubusercontent.com/nEYxnNACn8SBcGrF0nmp7XrEFYhEUXThh7qTsud5XJVKuIJJJf/_apis/pipelines/1/runs/331/signedlogcontent/9?urlExpires=2021-02-21T17%3A53%3A47.4075405Z&urlSigningMethod=HMACV1&urlSignature=J%2Bw8Kkx%2FzdPKCwyIIL1Yz1nKXoSRSOxug4%2B6gIOCDpA%3D))

**Comment by lazka** [comment]
Fixed via cbb60cb2716304c0ae
