### ISSUE TITLE
Quod Libet is not reading ratings by default

### ISSUE THREAD

**Issue by quietmansoath** [quodlibet/quodlibet#3569]
Steps to reproduce
------------------

I have a bunch of songs that have had the ratings written into the file itself. This is visible using Windows Explorer (see screenshot of my windows 10 vm). These files are hosted on linux and shown in a guest windows vm--that is to say, they are the same file. I am running QL in linux, however.

Expected Output
---------------

I thought that when I opened Quod Libet and pointed it to my music folder, all of my already embedded ratings would show up.

Actual Output
-------------

They do not. As you can see from the screenshots, the ratings are written to the file, but QL isn't reading them. 

Test System
-----------

### Which version of Quod Libet?

The latest version.

### Which operating system 

Ubuntu 20.10 (Pop! Os)

### If it's audio-related, what back-end?

Additional Information
----------------------

![Screenshot from 2021-03-02 22-13-21](https://user-images.githubusercontent.com/46270221/109747527-473e0800-7ba5-11eb-936b-5a0b241deb45.png)
![Screenshot from 2021-03-02 22-12-24](https://user-images.githubusercontent.com/46270221/109747528-47d69e80-7ba5-11eb-9d56-850323e7838e.png)

**Comment by quietmansoath** [comment]
To clarify, the songs were _already_ rated before I ever installed or ran QL. I thought that with them already rated, QL would just be able to read them.

**Comment by declension** [comment]
What were they rated with before, and what kind of file are they? If it's mp3, what does `mid3v2 $FILE` list?

**Comment by quietmansoath** [comment]
They were rated with Windows Media Player and Music Bee. The files are almost all .mp3--not sure about a few, but 95% are .mp3.

I'm very much a linux newbie so I don't really know how to run that command, but in Ex Falso I got the following information for what should be a 5 star rated song:
![Screenshot from 2021-03-03 19-54-17](https://user-images.githubusercontent.com/46270221/109893794-5206a480-7c5a-11eb-9d80-609e15629087.png)

It looks like there's no rating at all, which is very strange. I can open up my windows VM and see the ratings no issue.

**Comment by declension** [comment]
> It looks like there's no rating at all, which is very strange. I can open up my windows VM and see the ratings no issue.

We don't show certain tags there (like rating) that can't be edited by the user. `POPM` tags (values of 0-255) are read and converted but note QL tracks ratings per user identifier (typically email address), so this might be it.

> I'm very much a linux newbie so I don't really know how to run that command

No problem, you could try this:
1. Find the path to the file (e.g. `/home/me/music/album/song.mp3`)
2. Open the Terminal app
3. Make sure you have `mutagen` installed (e.g. `sudo apt install python3-mutagen`)
4. Type `mutagen-inspect /home/me/music/album/song.mp3` and copy the output here
