### ISSUE TITLE
Error scanning Network Drive on Windows 10

### ISSUE THREAD

**Issue by cidthecoatrack** [quodlibet/quodlibet#3572]
Steps to reproduce
------------------
1. Have 4.4.0 on Windows 10, with a Network Drive set up as a folder in your library.  (For context, I have a different Ubuntu computer also running QuodLibet pointing to the same network drive, with the intent to share media/tags/info between the two installations.)
2. Have auto-scan enabled for when you open QuodLibet
3. Let QuodLibet scan your library on the Network Drive. (For context, my Network library is rather large with ~70K songs.)
4. An error will pop up saying there was a WinError and that a "handle is not valid".  A screenshot is included in the Actual Output.
5. In addition, when this error occurs, it seems that not all files are added to the library (about 10K are missing, mostly newer additions), and tags are not updated (old ratings/playcounts persist).  I would assume this is because the scan has been interrupted by the thrown error, so adding new files and/or updating tags does not get a chance to happen.

Expected Output
---------------
I would expect for the library to scan successfully without throwing the error, for all songs to be added to the library, and for tags to be correctly updated

Actual Output
-------------
![image](https://user-images.githubusercontent.com/2846466/110124866-a1e78780-7d90-11eb-881d-6f21b6a297d9.png)

```
OSError: [WinError 6] The handle is invalid: "M:\\Craig Morgan\\My Kind of Livin'\\08. Redneck Yacht Club.mp3"
------
Traceback (most recent call last):

  File "lib\python3.8\ntpath.py", line 660, in realpath

OSError: [WinError 6] The handle is invalid: "M:\\Craig Morgan\\My Kind of Livin'\\08. Redneck Yacht Club.mp3"


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "C:\Program Files\Quod Libet\lib\python3.8\site-packages\quodlibet\util\copool.py", line 23, in wrap
    for value in func(*args, **kwargs):

  File "C:\Program Files\Quod Libet\lib\python3.8\site-packages\quodlibet\library\libraries.py", line 688, in rebuild
    for value in self.scan(paths, exclude, cofuncid):

  File "C:\Program Files\Quod Libet\lib\python3.8\site-packages\quodlibet\library\libraries.py", line 733, in scan
    for real_path in iter_paths(scan_path, exclude=exclude):

  File "C:\Program Files\Quod Libet\lib\python3.8\site-packages\quodlibet\library\libraries.py", line 515, in iter_paths
    fullfilename = os.path.realpath(fullfilename)

  File "lib\python3.8\ntpath.py", line 664, in realpath

  File "lib\python3.8\ntpath.py", line 614, in _getfinalpathname_nonstrict

OSError: [WinError 6] The handle is invalid: "M:\\Craig Morgan\\My Kind of Livin'\\08. Redneck Yacht Club.mp3"

```

Test System
-----------

### Which version of Quod Libet?
4.4.0

### Which operating system 
Windows 10 (this machine), Network drive/other installation is Ubuntu 20.04.  The Ubuntu machine does not show this bug, only the Windows machine.

### If it's audio-related, what back-end?
This is not audio related.

Additional Information
----------------------
When the error occurs, I do submit a bug report with XXX, so this might be technically duplicate - but I thought it would be best to file a bug report here directly as well.

If you manually trigger a scan of the library, the error also occurs.

**Comment by cidthecoatrack** [comment]
I should add some more information regarding the file throwing the error. The Folder `Craig Morgan` does exist, but within it, the albums are interesting:

* `M:\\Craig Morgan\\My Kind Of Livin'\\08. Redneck Yacht Club.mp3`
* `M:\\Craig Morgan\\My Kind of Livin'\\07. That's What I Love About Sunday.mp3`
* `M:\\Craig Morgan\\That's Why [Reissue]\\03. This Ain't Nothin'.mp3`

My assumption would be that, since the only difference between the folders is casing, that something is treating the directory as case-insensitive, which is causing an incorrect pairing of directory and file (the first file to the second directory).

**Comment by cidthecoatrack** [comment]
This appears to be very Windows-specific.  If I go into the network drive and attempt to move the files into the same folder, Windows tells me that the source and destination are the same.  In other words, Windows file paths are case-insensitive.  However, when I go onto my Ubuntu machine, I can move the files into the same folder just fine - so Ubuntu file paths ARE case-sensitive.

After moving the files so there is not a case-different folder differentiating them, that particular file no longer caused an issue.  A different case-sensitive folder discrepancy emerged, which I will also manually resolve.  Ideally, if possible, the code would have a way to manage this - but since Windows itself seems to be case-insensitive, I imagine there isn't much QL can do about it on a Windows installation :/

**Comment by cidthecoatrack** [comment]
After manually resolving all the case-sensitive folder paths, the library scans successfully.  There is a different issue of ratings and playcounts not updating, but that is documented in #3561

**Comment by declension** [comment]
IIRC, the Samba servers for CIFS are usually insensitive but preserve case, and you can get into some _really_ tricky confusions if relying on case differences:

https://www.samba.org/samba/docs/4.11/man-html/smb.conf.5.html

If there's no particular action for QL here I'll close the issue and concentrate on the others...

**Comment by cidthecoatrack** [comment]
Yep, fair enough
