### ISSUE TITLE
Bandcamp Integration

### ISSUE THREAD

**Issue by celesteh** [quodlibet/quodlibet#3587]
The proposed change
-------------------
I would like quod libet to be able to stream files from bandcamp and create playlist based on these streams.  Loading the library on startup would therefore include connecting to the user's bandcamp account and pulling a list of all the tracks they own.

Benefits of this change
-----------------------
When I buy music now, I primarily use bandcamp and don't tend to download the media as it would fill up my hard drive. Bandcamp allows streaming, but it's interface is not good. This would allow users to keep their music in the cloud but still be able to listen in the order they want.

Any issues this might cause
---------------------------
This would likely make it slower to load the library on startup. It makes major features of the app dependant on a network connection.  

There are circumstance where streaming from bandcamp might annoy artists or the company, for example, if the user has not purchased an album. This is why I suggest using user authentication and pulling lists of owned tracks.

**Comment by bassstorm** [comment]
Lovely feature it would be!
However, does Bandcamp allow that? I haven't heard about any other desktop 3-rd party client available...

**Comment by celesteh** [comment]
They don't have a public API for this, but it also doesn't seem to violate their TOS.

**Comment by bassstorm** [comment]
Yes, what I mean is that in fact QL would need to emulate a browser in terms of reading and parsing Bandcamp HTML. That's not the most pleasant thing in itself, but also a maintenance headache due to unpredictable changes applied by Bandcamp (e.g. few month ago youtube-dl didn't work with Bandcamp at all after some changes in Bandcamp page template).

**Comment by celesteh** [comment]
They have a phone app, which suggests there is a non-public API.

**Comment by CreamyCookie** [comment]
@bassstorm Fully agree. I'd say this is way out of scope for QL or an included plugin, at least until there's a public API.

I agree though, it might be nice. Bandcamp is cool.

**Comment by CreamyCookie** [comment]
@bassstorm Fully agree. I'd say this is way out of scope for QL or an included plugin, at least until there's a public API.

I agree though, it might be nice (though I mostly prefer download to stream). Bandcamp is cool.

Closing this until there's a public stable API for legally accessing an account's bought albums and streaming.
