### ISSUE TITLE
4.4.0 for Ubuntu and Debian repos

### ISSUE THREAD

**Issue by mshmm** [quodlibet/quodlibet#3588]
Now that v4.4.0 has been released, will the Ubuntu PPA and the Debian Stable repo be updated to this new version? Both are currently at 4.3.0.

**Comment by lazka** [comment]
yeah, thanks, I'll have a look. I only updated flathub back then.

**Comment by mshmm** [comment]
Deb packages for Debian and Ubuntu would be very welcome, as the Flatpak version does not allow direct streaming to a DAC via ALSA.

**Comment by declension** [comment]
Anything I can help with here @lazka ?

**Comment by lazka** [comment]
What about now?

**Comment by everdred** [comment]
@lazka I was just able to update from the deb repo. Thanks!

**Comment by mshmm** [comment]
4.4.0 installs successfully from the PPA as well. Thank you.
