### ISSUE TITLE
Persistent notification with action buttons

### ISSUE THREAD

**Issue by PatrickJosh** [quodlibet/quodlibet#3589]
The proposed change
-------------------
A persistent notification should be displayed with buttons to resume/pause the current song, and to go to the next/previous song, like in other players as Rhythmbox or Lollypop. This could be introduced via a plugin, for example, so that users who don't want such a notification don't have one.

![grafik](https://user-images.githubusercontent.com/32456639/111383674-d4ef1c80-86a8-11eb-9f2a-5ac7635381fc.png)
This is an example of the notification from the Rhythmbox player in Gnome's notification centre.

Benefits of this change
-----------------------
It is easier to resume/pause the current song or to skip if you don't have access to the media buttons or you just one have such. Moreover, the notification can be synced via tools like KDEConnect and you can control your music from your mobile device easier.

Any issues this might cause
---------------------------
I would say no, but I don't have much information about that.

**Comment by haeckle** [comment]
Hi, there is a plugin available called "MPRIS D-Bus Support" which does exactly what you describe.

**Comment by PatrickJosh** [comment]
Oh, thank you very much. I did not know this.
