### ISSUE TITLE
Crash on Ex Falso

### ISSUE THREAD

**Issue by Dominiquini** [quodlibet/quodlibet#3591]
Steps to reproduce
------------------

In "Ex Falso" window, try to open 'Preferences'

Expected Output
---------------

Open 'Preferences' Windows

Actual Output
-------------

Crash!

Test System
-----------

### Which version of Quod Libet?
4.4.0

### Which operating system 
Windows 10 x64 (Version 20H2 (OS Build 19042.868))

### If it's audio-related, what back-end?
'Ex Falso'

Additional Information
----------------------
Log:

> C:\Program Files\Quod Libet\bin>exfalso-cmd.exe
> E: 3.911: errorreport.main.errorhook: exfalsowindow.py:277:__init__: TypeError: __init__() missing 1 required positional argument: 'parent'

**Comment by declension** [comment]
Thanks - merging into #3608 which has Sentry reports (didn't see this in time, sorry). Please follow ther!
