### ISSUE TITLE
Waveform seekbar don't get activated on QL start

### ISSUE THREAD

**Issue by wifon** [quodlibet/quodlibet#3594]
Since I've updated to QuodLibet 4.4, waveform seekbar isn't activated on application start - standard seekbar is displayed instead. There are no errors related to this plugin. Every time I start QL, I have to go to File>Plugins and switch waveform seekbar off and the on again. Then it works normally, until I quit application.

### Which version of Quod Libet?
4.4

### Which operating system 
Linux Mint 20.1

**Comment by wifon** [comment]
After this, I've noticed that I've had Alternative Seekbar plugin enabled as well. Disabled it and waveform works correctly now.

**Comment by CreamyCookie** [comment]
Seems like the solution is to only allow one to be enabled or to allow multiple seekbars as mentioned by lazka in #2764.

So, I'm closing this one for #2764.
