### ISSUE TITLE
List "The" at the end of album artist name

### ISSUE THREAD

**Issue by riegal** [quodlibet/quodlibet#3597]
The proposed change
-------------------
Album artists who's name begins with "The" should have the "The" moved to the end of their name such as "The Beatles" > "Beatles, The"

Benefits of this change
-----------------------
This would be in keeping with the way streaming services, libraries, indexes manage names that begin with "The".

**Comment by declension** [comment]
Hi. This is what the `artistsort` tag is for actually ([`TSOP` in ID3](https://en.wikipedia.org/wiki/ID3#ID3v2_frame_specification))

See also [MP3Tag's helpful reference](https://help.mp3tag.de/main_tags.html). 

The good news is that 
* QL supports this and uses it in sensible places where it can (e.g. sorting list views):
![Screenshot from 2021-04-05 14-48-22](https://user-images.githubusercontent.com/3322808/113580724-0317aa80-961e-11eb-9d00-ec7809dbeff3.png)
Note the `artistsort` here (or `composersort` in fact) of _Bach, Johann Sebastian_ being used to order correctly) 
* there's a QL plugin to add (badly) `artistsort` tags to your existing library if you don't already

Hope that helps
