### ISSUE TITLE
JPG cover images error

### ISSUE THREAD

**Issue by blimmo** [quodlibet/quodlibet#3599]
Steps to reproduce
------------------
Play any file with a jpg cover art.

Expected Output
---------------
Cover art should display on the player.

Actual Output
-------------
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 20: invalid start byte`
followed by
`RuntimeError: Converting the GError failed`
then no cover art displayed.

Test System
-----------
Quod Libet 4.4.0
Win10

This has only been happening since I updated from 4.3.0

Additional Information
----------------------
Logs:
[Dump_20210402_001055.txt](https://github.com/quodlibet/quodlibet/files/6246904/Dump_20210402_001055.txt)
[Dump_20210402_001101.txt](https://github.com/quodlibet/quodlibet/files/6246905/Dump_20210402_001101.txt)

I have tested with images from multiple sources including jpgs freshly written by ffmpeg so I'm fairly sure this isn't caused by a malformed image file. Just in case it is, here's the image file that caused the errors in the logs above:
[cover](https://user-images.githubusercontent.com/26982890/113364081-81d4c500-934a-11eb-96c7-7cbaab796a9c.jpg)

This looks like it's happening in a `GdkPixbuf.Pixbuf.new_from_file_at_size` so it might be an upstream issue.

**Comment by declension** [comment]
Thanks for the detail, this is helpful. 

Perhaps this duplicates https://github.com/quodlibet/quodlibet/issues/3579?

**Comment by declension** [comment]
Closing as duplicate. Please re-open if it's definitely not the same
