### ISSUE TITLE
remove scan directory in Library does not remove associated music files from quodlibet

### ISSUE THREAD

**Issue by ai7** [quodlibet/quodlibet#3603]
Steps to reproduce
------------------
- start with a clean configuration
- add a directory to `Preference` / `Library` / `Scan Directories`.
- optional: click scan library or rebuild library
- all the music files in the added directory is imported.

- Now go back to preferences, and remove the added directory from Scan Directories.

Expected Output
---------------
Music files imported from those directories should be **removed** from QuodLibet.

Actual Output
-------------
Music files from those directories are **NOT** removed in QuodLibet.

This is bad for a number of reasons:
- the meaning of **Scan Directories** implies that QuodLibet will monitor those folders, and automatically add/remove music files from those directories when the content of those directories change.
- not removing associated files when the directory is removed will leave those files in an orphaned state. This makes managing any reasonable sized music collection very hard.

Imagine I have 3 directories, each with 200 music files. Now I partitioned one of the folders into 2 sub folders, and want to check I partitioned the music files correctly (say by year which quodlibet shows nicely). It should be possible to remove the parent scan directories, and only add one of the subdirectories, so I can easily check its imported content.

Not possible with current implementation. The library is a static dump ground. it is not possibly to cleanly remove imported files from one of the parent directories. I have to make the configuration change (remove dir, add subdir), quit quodlibet, delete `~/.quodlibet/songs`, and restart quodlibet.

Even `Scan Library` or `Rebuild Library` does not remove those orphaned files, which is not good.

Test System
-----------

### Which version of Quod Libet?
4.3.0

### Which operating system 
MacOS 10.14.6

### If it's audio-related, what back-end?

Additional Information
----------------------

**Comment by declension** [comment]
Thanks. This is essentially #2293

**Comment by declension** [comment]
I'll close in favour of #2293 - but please continue the conversation there (or re-open if this is genuinely different)
