### ISSUE TITLE
iRadio browser has empty favourites

### ISSUE THREAD

**Issue by declension** [quodlibet/quodlibet#3611]
https://sentry.io/organizations/quodlibet/issues/2245928840/?referrer=github_plugin

```
AssertionError: 
  File "quodlibet/browsers/iradio.py", line 831, in __add_stations
    assert self.__fav_stations

AssertionError
```

**Comment by CreamyCookie** [comment]
I'm most certainly missing something, but why should `__fav_stations` be empty [there](https://github.com/quodlibet/quodlibet/blob/be685f5f8906a929e6c0deae53873b4508dc0d54/quodlibet/browsers/iradio.py#L833). 

Could it be that what the developer intended was `assert self.__fav_stations is not None`?
