### ISSUE TITLE
Usage question: Scanning  a network volume on Mac OS 11

### ISSUE THREAD

**Issue by MaineTim** [quodlibet/quodlibet#3619]
I'm trying to scan a network volume mounted in /Volumes on Mac OS 11.2.3. I select that path in the "Add Folders" selector window, and it appears in the list in Preferences. But when I click either the scan or rebuild buttons, nothing happens. No access failure message, no prompt to allow access, nothing at all. I have full user permissions to the volume, but I gather there is another mechanism that recent Mac OS versions use to give individual apps access permission. quodlibet doesn't appear under Settings > Security and Privacy section "Allow the apps below to access files and folders", and I don't see any way to add it.

Thanks in advance for any help.

**Comment by declension** [comment]
See related #3267 #3508

**Comment by MaineTim** [comment]
Thanks very much for the response. I was able to get this to work by running directly from the terminal, which has network volume access. I see from the issues you referenced that folks are working on a way to trigger an access request via the gui. Again for the developers: the failure in my case was absolutely silent, with no "operation not permitted" or the like.

I'll close this so as not to further clutter the issues list. Thanks again!
