### ISSUE TITLE
Remove Web Lyrics plugin

### ISSUE THREAD

**Issue by CreamyCookie** [quodlibet/quodlibet#3631]
The proposed change
-------------------
Remove the Web Lyrics plugin, as its main functionality has been broken for a while and it only "works" on Linux right now. The only thing that does work on Linux is the alternative search function. I address that feature in the "Any issues this might cause" section.

Accessing `https://lyrics.wikia.com/api.php?client=QuodLibet&action=lyrics&func=getSong&artist=Sia&song=Together&fmt=xml` only returns:

> You're not authorized to access this API. For information about Wikia API licensing please contact support@wikia-inc.com.pirat@anon-PC:/tmp

Accessing `https://lyrics.wikia.com` redirects to `https://lyrics.fandom.com/wiki/Main_Page`, which shows a message:

> This wiki has been disabled

As mentioned in #2558, the scrolling to lyrics section also stopped working at some point.

Benefits of this change
-----------------------
* Cleaner code base
* Less to maintain
* Buggy plugins might make Quod Libet look less maintained than it is

If the plugin would be removed, we can close #2539 : macOS: lyricswindow plugin not available.

I think if we found a good API and someone wanting to implement it, it would also be better to add it to the viewlyrics plugin. If lyrics couldn't be found in tags or a file, they could be loaded from that API.

Any issues this might cause
---------------------------
Some users might not be happy about it being removed, if they still used it for the alternative search function (search at configurable url for `lyrics {artist} {title}`). 

However, it seems unlikely to me that many people use that, and even then we still have the "Website Search" plugin, where you can do the same (though manually).

----

See also https://github.com/quodlibet/quodlibet/issues/3444#issuecomment-701203619, which mentions some alternative proposals (but also removing the plugin).  

Of course, if nobody is interested in working on an alternative (which seems to be the case), we can always remove the plugin first, as, of course, the deleted [plugin code](https://github.com/quodlibet/quodlibet/blob/8b58a81b077e00b32cc4ad30520ccc8ca70f4406/quodlibet/ext/events/weblyrics.py) can always be reused.

**Comment by declension** [comment]
Sounds like a good idea to me, esp your third benefit (_broken windows_ effect, effectively)

**Comment by CreamyCookie** [comment]
@declension 

> esp your third benefit (broken windows effect, effectively)

Definitely! I feel like not enough people know of this effect and how much it impacts, even in everyday life..
