### ISSUE TITLE
In Lyric edit window: "View online" button still leads to disabled Wiki

### ISSUE THREAD

**Issue by CreamyCookie** [quodlibet/quodlibet#3642]
Only stumbled on this by accident now, wondering what the button does.

Steps to reproduce
------------------
Open Lyric edit window and press "View online" button

Expected Output
---------------
Not sure. I think it would make sense to 

1. remove it
2. add a setting for a search URL that is used 

Actual Output
-------------
It opened the disabled lyrics.wikia website.

Test System
-----------

### Which version of Quod Libet?
master

Additional Information
----------------------

https://github.com/quodlibet/quodlibet/blob/be685f5f8906a929e6c0deae53873b4508dc0d54/quodlibet/qltk/lyrics.py#L67-L72

**Comment by hacksenwerk** [comment]
@CreamyCookie Thank you for opening this issue. 

I would suggest to add the ability for downloading lyrics from several sources, with the ability to add them as embed (Metatag: fmps_lyrics) or save them as a text format in a directory of choice and also to choose both options at once. 
gmusicbrowser offers this with a plugin [How can I see the song lyrics ?](https://gmusicbrowser.org/faq.html). 
At the moment I use both players for adding images and lyrics and that's not very handy... 
I would prefer quodlibet over gmusicbrowser, if it has support for automatic lyric adding via online services.
