### ISSUE TITLE
Save QL state to disk more frequently

### ISSUE THREAD

**Issue by bassstorm** [quodlibet/quodlibet#3649]
The proposed change
-------------------
As a user I'd like QL to save its state to disk more frequently. Example areas of improvement would be scrobble cache and play queue -- both are currently saved to disk on app exit only.
Could be a core functionality or a plugin.

Source of inspiration: [Autosave & Autobackup](https://www.foobar2000.org/components/view/foo_jesus) plugin for foobar2000.

Benefits of this change
-----------------------
QL can survive any unexpected bad event (e.g. system crash, power outage) and resume from the most actual state snapshot.

Any issues this might cause
---------------------------
No foreseeable issues as those state files are usually relatively small and autosave frequency could be configurable.

**Comment by declension** [comment]
This feels like several separate changes - the library is one thing, scrobble caches are completely separate, not even sure how the Queue one works, and the various filter changes are through config persistence. 

Then there are saved lists which is separate (but probably not the problem)

**Comment by bassstorm** [comment]
Yes, I could imagine it spans over many places in the code base. However from end user perspective it's a single feature, we may call it epic using agile terminology.

**Comment by bassstorm** [comment]
Started to use QL as primary player on that Apple laptop, and believe me or not -- sh*t happened! Right on second day of use app crashed, scrobbles lost... Luckily there were just a few.

**Comment by Jimi-James** [comment]
The fact that his hasn't yet been addressed is starting to become the absolute bane of my existence, now that Steam and Ardour have recently started frequently crashing my computer and display manager, respectively. Those crashes are intermittent, and seem to affect nobody else, and in Ardour's case have persisted even when I switched to a different display manager, so I really have no choice but to live with them for now.

**Comment by declension** [comment]
@Jimi-James which state in particular is the most troublesome here?

**Comment by Jimi-James** [comment]
@declension The queue, specifically.

**Comment by bassstorm** [comment]
@declension looking at #3854, perhaps too much coding for asking the same for scrobble cache case?

**Comment by declension** [comment]
> @declension looking at #3854, perhaps too much coding for asking the same for scrobble cache case?

Kinda a different problem, so best to keep them separate (for bisecting / roll back etc). I'll try to get something working if I get time. 

Annoyingly listenbrainz plugin is mostly copy-pasted so the same problem exists there (and same things needing cleaning up), have added #3856
