### ISSUE TITLE
tests.test_util_copool.Tcopool is flaky in CI

### ISSUE THREAD

**Issue by declension** [quodlibet/quodlibet#3653]
Steps to reproduce
------------------
Run the CI build on a working branch a few times

Expected Output
---------------
Consistently the same (green)

Actual Output
-------------
Some tests in `tests.test_util_copool.Tcopool` will fail
e.g.  https://github.com/quodlibet/quodlibet/pull/3652/checks?check_run_id=2432432559

**Comment by CreamyCookie** [comment]
@declension I'm loving the cleanup in #3657! Thanks for fixing this!

**Comment by CreamyCookie** [comment]
@declension It does happen less often, I think, but it seems it's still possible:

https://github.com/quodlibet/quodlibet/commit/32c54a90f241c4e03ce4a47731d9304a56a14267/checks/2449644930/logs

**Comment by declension** [comment]
> @declension It does happen less often, I think, but it seems it's still possible:
> 
> https://github.com/quodlibet/quodlibet/commit/32c54a90f241c4e03ce4a47731d9304a56a14267/checks/2449644930/logs

Yes... though that seems to be old code, judging from the stacktrace...

**Comment by CreamyCookie** [comment]
@declension Oh, man.. Of course my commit is older than yours so the tests are still unfixed.. (Why did my brain not remind of this? :facepalm:)
