### ISSUE TITLE
Status bar info is not updated after song deletion

### ISSUE THREAD

**Issue by bassstorm** [quodlibet/quodlibet#3659]
Steps to reproduce
------------------
0. Have a list of tracks using any query (ordinary or using regular expression)
1. Delete one track using mouse menu
2. Check totals in status bar

Expected Output
---------------
Both total track number and total running time are updated

Actual Output
-------------
Status bar totals are unchanged

Test System
-----------

### Which version of Quod Libet?
4.3.0 / 4.4.0

### Which operating system 
MacOS 11.3 / Manjaro

Additional Information
----------------------
Multi-line selection (or Ctrl+A) makes status bar refreshed, i.e. after un-checking selection proper totals are displayed

**Comment by declension** [comment]
Thanks - confirmed on 098cf6cbae2a7b5eea91578eb74ceaa73506c891 on Linux
