### ISSUE TITLE
How About Just Playing A CD?

### ISSUE THREAD

**Issue by Shadeclan** [quodlibet/quodlibet#3662]
The proposed change
-------------------
Put in a CD and it will play just as if it were ripped, including showing album and track info.

Benefits of this change
-----------------------
the player will be more convenient to use and this will also add a feature found in other players, making Quod Libet more of a complete music player.

Any issues this might cause
---------------------------
Shouldn't cause any issues to the player, since it is already possible to play a CD by using the File System view (ctrl + 7) but no album or track information is displayed, even if the information is available.

**Comment by declension** [comment]
Thanks. 
This has already been much discussed and the decision was it's not a priority for QL.

See #163, #395
