### ISSUE TITLE
4.4.0 for MacOS?

### ISSUE THREAD

**Issue by dspiliot** [quodlibet/quodlibet#3668]
Hey, thanks for the great app. 
Will there be a 4.4.0 version for MacOS?
It seems to be the only one still on 4.3.0...

**Comment by bassstorm** [comment]
I'm not a developer, but here some very nice features are being added... Maybe makes sense to release 4.5 for all platforms.

**Comment by protrolium** [comment]
was wondering the same. 4.4.0 changelog looks fab. Would love to see an update for macOS.

**Comment by MikhaMo** [comment]
Update for MacOS would be very nice.

**Comment by declension** [comment]
Thanks for the requests all, good to know there's appetite out there. We really need some help packaging / bundling for MacOS given how much more difficult it's become. See #3477 #3267

**Comment by bassstorm** [comment]
@declension you must have read my mind. I was about at least to play with MacOS build tooling (create-img, dmgdist). Have no idea about the complexity, etc. Any tips and tricks from QL team's past experience are highly appreciated.
Nothing even close to production quality till June though due to higher that usual demand in family support for next few weeks.

**Comment by declension** [comment]
I think one plan was a C-based Gpodder MacOS wrapper similar to the one by @elelay as per #3267 (cc @lazka) to avoid native Python hassles.

**Comment by dspiliot** [comment]
I lack the skill to help build the app but I can help out with the testing, if needed. I have a macbook running Big Sur and an older one running Catalina.

**Comment by sergemor** [comment]
I've been waiting for a macOS update since 4.4.0 came out for Windows. I hope everything goes well and it's released soon.
I currently have 4.3.0 on macOS and there are so many bugs that makes it very difficult to use the program.

**Comment by bassstorm** [comment]
> I've been waiting for a macOS update since 4.4.0 came out for Windows. I hope everything goes well and it's released soon.
> I currently have 4.3.0 on macOS and there are so many bugs that makes it very difficult to use the program.

I'm sorry to hear that. Let's see what June will bring to us. But I would avoid giving any promises (I use MacOS for just few weeks), hopefully you understand.

**Comment by urielz** [comment]
As a temporary workaround you can still run the latest version by cloning this repo in your local machine. And then run it from the terminal:

`/Applications/QuodLibet.app/Contents/MacOS/run ~/your_path_to_clone_repo/quodlibet/quodlibet.py`

**Comment by sergemor** [comment]
So, might as well forget about Quod Libet being updated to 4.4.0 for macOS.

**Comment by bassstorm** [comment]
Hi all, I'm really sorry to get back to you with bad news. Last few months were full of unexpected events. One of those is that I'm about to change the job, so employers macbook won't be with me anymore, and I wouldn't be able to do anything related to MacOS. After try, I still prefer Linux for personal usage, thus no chance...

**Comment by formaj** [comment]
Well time to move on I suppose.

**Comment by declension** [comment]
To close this issue and solve a bunch of future MacOS ones, we need help from

* someone on MacOS with knowledge of building GTK+ apps, or building workarounds
* technical MacOS owners across a few recent versions, for testing and debugging builds as above
* Better MacOS CI suites at the highest level to validate packaging itself

**Comment by mundschenk-at** [comment]
I'm happy to help testing, but I don't have any build experience on macOS.

**Comment by declension** [comment]
:mega: [4.4.0 MacOS release](https://github.com/quodlibet/quodlibet/releases/download/release-4.4.0/QuodLibet-4.4.0.dmg) is now live - thanks to @lazka

**Comment by protrolium** [comment]
wow thanks @lazka ! definitely going to leave you a tip for this :)
