### ISSUE TITLE
4.4.0 not available for Ubuntu 16.04 ?

### ISSUE THREAD

**Issue by RafaelFrance** [quodlibet/quodlibet#3697]
I use 4.3.0 and tried to update to 4.4.0 but impossible.
I reinstall the repository (sudo add-apt-repository ppa:lazka/ppa). No update available

I am on Ubuntu 16.04

**Comment by lazka** [comment]
Ubuntu 16.04 is EOL, you shouldn't use it.

We require Python 3.7 now which means Ubuntu 20.04+

If you really want to run it you can try the flatpak: https://flathub.org/apps/details/io.github.quodlibet.QuodLibet
