### ISSUE TITLE
4.4.0 for openSUSE

### ISSUE THREAD

**Issue by mshmm** [quodlibet/quodlibet#3714]
Could the openSUSE repo https://build.opensuse.org/project/show/home:lazka0:ql-stable be updated to v4.4.0 please? Quod Libet is not in the standard openSUSE repos, so this is the only way of installing it.

**Comment by LoveIsGrief** [comment]
This issue is marked as "help-wanted" but how can we help?

@lazka do you have any time to update your project on OBS?

**Comment by declension** [comment]
I guess an OpenSUSE maintainer would be useful @LoveIsGrief

**Comment by mshmm** [comment]
The openSUSE repo has been updated to v4.4.0 https://build.opensuse.org/request/show/929573
