### ISSUE TITLE
SoundCloud browser fails to load all tracks from API

### ISSUE THREAD

**Issue by bester69** [quodlibet/quodlibet#3720]
API SoundCloud not working well with flatpak :
- Debian 9
- quodlibet 4.4.0 (flatpak version)

**Image capture**
https://i.postimg.cc/Z5xn2R6G/Selecci-n-052.png

**Comment by bester69** [comment]
![Selección_052](https://user-images.githubusercontent.com/85381357/120879707-9ab95b00-c5c5-11eb-958a-797d62f390ea.png)

**Comment by declension** [comment]
Replicated on c82af1bab9efe9596473df96619af21c00531e79 (Ubuntu)

Debug output shows lots of 
```
(AttributeError("'user_id' not found")). Had these tags:
      dict_keys(['~uri', '~filename', '~mountpoint', '~#added', '~#mtime', 'soundcloud_track_id', '~#rating'])
```
