### ISSUE TITLE
4.3.0 macos unstable

### ISSUE THREAD

**Issue by hawkiboy** [quodlibet/quodlibet#3729]
I am finding QL pretty unstable. Right now it is the only app I think I have ever installed on mac in the last 15 years that absolutely refuses to die. Right now it is sitting in my dock after I have forced quit it a bunch of times. Can't find any trace of it in the system monitor either, but I can't open the app unless I restart my computer. This has happened numerous times.

Steps to reproduce 
------------------
Launch ql, switch library, try to quit 

4.3.0 macos 10.15.5

**Comment by declension** [comment]
Which plugins do you have enabled? Can you run with `--debug`?

**Comment by hawkiboy** [comment]
Sorry, I can't reproduce it. I greatly appreciate assistance.
