### ISSUE TITLE
Translation fr.po

### ISSUE THREAD

**Issue by Bundy01** [quodlibet/quodlibet#3750]
Hi,

I am working on the translation into French.
I wanted to know if I can delete the commented lines from line 7977 to the end of the file?

They are obsolete translation lines.

Regards.

**Comment by lazka** [comment]
Please use weblate for translations: https://hosted.weblate.org/projects/quodlibet/quodlibet/fr/

**Comment by Bundy01** [comment]
I cannot connect to this site: ERR_CONNECTION_CLOSED :/

**Comment by Bundy01** [comment]
I can do the translation manually if needed, by running `./setup.py update_po --lang=en` then `./setup.py test --to-run PO.fr`.

I've already made a lot of progress. If I make the file manually, what about the commented lines at the end of the file? Do I keep them or do I delete them?

**Comment by Bundy01** [comment]
Translation completed.

This is the first time I use this site (nice) :)
Is there a backup to do or is it automatic?

**Comment by lazka** [comment]
See #3752
