### ISSUE TITLE
<basename> tag doesnot work?

### ISSUE THREAD

**Issue by spandan888** [quodlibet/quodlibet#3765]
`~/music/<album>/~basename `or `~/music/<album>/<basename> `doesnt work while renaming files?
what's the workaround???

**Comment by spandan888** [comment]
i have large number of files in a single folder, want to move the files into separate folders based on the album tag, without changing the file name.

**Comment by declension** [comment]
Solved on Discord  (it's `<~basename>` for that pattern )
