### ISSUE TITLE
Ex Falso Error Occurred

### ISSUE THREAD

**Issue by Scotty-Trees** [quodlibet/quodlibet#3775]
Steps to reproduce
------------------
Opened Ex Falso, clicked on Preferences and got the following error message within Ex Falso. It asked me if I would like to Submit Error Report, Restart the application, or Ignore the Error. I've submitted an error report through Ex Falso, but every time I try to open the Preferences, it always gives me this error. Not sure what to do, but hope this helps someone.

```
TypeError: __init__() missing 1 required positional argument: 'parent'
------
Traceback (most recent call last):

  File "/usr/lib/python3.9/site-packages/quodlibet/qltk/exfalsowindow.py", line 75, in prefs_cb
    window = PreferencesWindow(self)

  File "/usr/lib/python3.9/site-packages/quodlibet/qltk/exfalsowindow.py", line 277, in __init__
    super().__init__()

TypeError: __init__() missing 1 required positional argument: 'parent'

```
When I run Ex Falso from the terminal this is the only message that showed up: 
``` [scott@endeavourOS ~]$ exfalso 
E: 40.394: errorreport.main.errorhook: exfalsowindow.py:277:__init__: TypeError: __init__() missing 1 required positional argument: 'parent'
````

Expected Output
---------------
I should be able to open the Preferences without an error warnings.

Test System
-----------

### Which version of Quod Libet?
4.4.0
### Which operating system 
EndeavourOS (Arch-based) running kernel 5.10.56-1-lts

Additional Information
----------------------
Sometimes, maybe one out of every 20 times or so I start up Ex Falso, it'll take like 5 minutes to open. Usually though it opens instantly. I'm never doing anything system resource intensive so this is a bit unusual since it happens not so often, but I don't yet have a way to be able to reproduce it. Unsure if it's related to an Ex Falso bug or something else within EndeavourOS. Below is a quick screenshot of the error in case it helps.

![Screenshot from 2021-08-17 00-22-52](https://user-images.githubusercontent.com/45135187/129663726-962a16c1-344f-4ce4-bfcf-d80b43626cf9.png)

**Comment by declension** [comment]
Thanks. I think this is #3591 / #3608

Latest `master` has these on but not yet released. Please re-open if this is definitely different

**Comment by Perkolator** [comment]
Just bumped to this problem while trying Quod Libet/Ex Falso for the first time. If this was fixed almost a year ago, why isn't there a new release? Why are new versions released so seldom? I'm really liking the program, though I found some bugs already (maybe those are already fixed too?) and some features missing that I'd like to see (e.g. desc sorting (e.g. playcount)).

**Comment by declension** [comment]
> Just bumped to this problem while trying Quod Libet/Ex Falso for the first time. If this was fixed almost a year ago, why isn't there a new release? Why are new versions released so seldom?

Long story but essentially it's a lot of work, but we're getting there. See #3808 for progress on the next release
