### ISSUE TITLE
Available translations out of sync in Weblate

### ISSUE THREAD

**Issue by Mellthas** [quodlibet/quodlibet#3777]
https://hosted.weblate.org/projects/quodlibet/quodlibet/en/ shows 1632 source strings, but the different languages have less strings available for translation (seems to 1570 for most). E.g., the *Stop on Pause* plugin should be translatable but does not show up when translating.

**Comment by Mellthas** [comment]
@lazka, can you have a look at this? The numbers have changed slightly, but the problem is still present. It is impossible right now to actually complete any translation via Weblate.

**Comment by lazka** [comment]
thanks. I've enabled the "Update PO files to match POT" plugin now, which added a commit here: https://github.com/quodlibet/quodlibet/pull/3804

**Comment by Mellthas** [comment]
Nice, thanks!

**Comment by lazka** [comment]
Did it improve now?

**Comment by Mellthas** [comment]
Looks good now! Also, when running `update_po`, the changes are minimal now (apart from the date, they are probably only caused by the changes since the last POT file update).
