### ISSUE TITLE
`update_po` produces absolute paths

### ISSUE THREAD

**Issue by Mellthas** [quodlibet/quodlibet#3778]
Steps to reproduce
------------------
Run `setup.py update_po`.

Expected Output
---------------
Relative paths to the sources in the PO file(s).

Actual Output
-------------
Absolute paths to the sources in the PO file(s). Probably related: `po/quodlibet.pot` has absolute paths, while the `po` files have relative ones.

Test System
-----------

Current `master` on Ubuntu 20.04.

Additional Information
----------------------
Ran into this when preparing translations for submission. I had already done the translations using the pre-Weblate system, but had not submitted them, so I wanted to make sure that nothing got lost.

**Comment by declension** [comment]
I guess this is fixed now by #3798 @lazka ?

**Comment by lazka** [comment]
yes, thanks.
