### ISSUE TITLE
flatpak gnome EOF info

### ISSUE THREAD

**Issue by raygamerkt** [quodlibet/quodlibet#3791]
Info: org.gnome.Platform//3.38 is end-of-life, with reason:
   The GNOME 3.38 runtime is no longer supported as of August 19, 2021. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
   io.github.quodlibet.QuodLibet

**Comment by lazka** [comment]
Fixed in https://github.com/flathub/io.github.quodlibet.QuodLibet/pull/18
