### ISSUE TITLE
Plugin waveformseekbar does not shown on start

### ISSUE THREAD

**Issue by paxter** [quodlibet/quodlibet#3795]
General information
---
OS: macOS 10.14.6
quodlibet: 4.4.0

Steps to reproduce
---

1. Enable Plugin (seekbar has wave forms now)
2. Close quodlibet
3. Start quodlibet
4. Plugin is still enabled but there is no wave form seekbar shown
5. Disable/enable plugin and wave form seekbar is shown again

Looks like there is an issue which cause the plugin is not loaded correctly on startup.

**Comment by Meriipu** [comment]
Perhaps related to these issues #3594 #2764

**Comment by paxter** [comment]
Hmmm, but without multiple (`Alternative Seek Bar` and `Waveform Seek Bar`) seekbar plugins it's not possible to get the visualation shown on the main page: https://raw.githubusercontent.com/quodlibet/quodlibet/master/docs/images/album-list-2017-08.png

So it's a bug or the screenshot is showing a feature which does not exist.

**Comment by Meriipu** [comment]
Is not that just the waveform seekbar?

Does turning off the "alternative seek bar" plugin and then toggling the waveform seekbar plugin off and on (causing a refresh/reload of it I presume) work?

**Comment by paxter** [comment]
You are right. Looks like the `Waveform Seek Bar` plugin contains the code (or position) from the `Alternative Seek Bar` plugin. So it's enough to just enable the `Waveform Seek Bar` plugin.

I'll close this issue because it's working for me now. Thanks a lot for your support @Meriipu =)
