### ISSUE TITLE
ExFalso preferences don't look quite right

### ISSUE THREAD

**Issue by Mellthas** [quodlibet/quodlibet#3805]
Steps to reproduce
------------------
Start ExFalso, open the preferences window.

Expected Output
---------------
A reduced set of preferences only relevant to ExFalso.

Actual Output
-------------
The window contains the complete Quod Libet preferences, plus some extra padding within the window. Opening the preferences is accompanied by the following warning:

`(io.github.quodlibet.ExFalso:21226): Gtk-WARNING **: 21:37:05.910: Attempting to add a widget with type GtkVBox to a quodlibet+qltk+exfalsowindow+PreferencesWindow, but as a GtkBin subclass a quodlibet+qltk+exfalsowindow+PreferencesWindow can only contain one widget at a time; it already contains a widget of type quodlibet+qltk+x+Notebook`

Test System
-----------

Quod Libet master on Ubuntu 20.04.

**Comment by declension** [comment]
Thanks @Mellthas, can replicate here.

**Comment by declension** [comment]
I'm assuming _Library_ and _Tagging_ are the tabs you expect to see here?

**Comment by Mellthas** [comment]
I think in previous versions it was only the tagging preferences, excluding the rating section, not showing any tabs. Cannot remember exactly, but the window had very few options. I just assumed that they were the only relevant ones.

**Comment by Mellthas** [comment]
Actually, the original window was even more minimal:

![ex-falso-prefs](https://user-images.githubusercontent.com/5852189/141863694-fcb1a845-4945-4014-bc56-8f11a166404b.png)

Managed to restore that in #3841, just as a quick demonstration, not sure about how to handle it best code-wise. Having the window resizable or with a reasonable minimum width on the text inputs would be nice though.

**Comment by Mellthas** [comment]
If the intention was to change that, then you can also ignore the comment and close the PR ;-).
