### ISSUE TITLE
4.5.0 release

### ISSUE THREAD

**Issue by declension** [quodlibet/quodlibet#3808]
The proposed change
-------------------
A release of ~4.4.1~ `4.5.0` for usual platforms.

Benefits of this change
-----------------------
Various bugfixes and new features e.g. #3608, #3721, #3755, (#3579 a bit?), #3525, #3538, #3800

Any issues this might cause
---------------------------
Hassle & time

**Comment by Peque** [comment]
I would add https://github.com/quodlibet/quodlibet/issues/3592 too. :blush:

**Comment by hannes101** [comment]
I would add https://github.com/quodlibet/quodlibet/pull/3800, which fixes quodlibet on python 3.10, which will be available on fedora 35. Currently, I've packaged git master, but it would be great to ship a released version.

**Comment by declension** [comment]
@lazka any thoughts on a `4.4.1`?

**Comment by lazka** [comment]
I'll have a look

**Comment by zeezhao** [comment]
Hi @lazka . Looking forward to this release. Thanks for your help.

**Comment by declension** [comment]
FWIW I'm now more in favour of `4.5.0` release, having just examined the ~300 commits since 4.4.0 (almost a year ago now).

**Comment by declension** [comment]
(note there's also #3465)

**Comment by cidthecoatrack** [comment]
Just saw that 4.5.0 was released!  Yay!  Seems like this issue should be closed now.

**Comment by zeezhao** [comment]
Unfortunately I had to roll back to version 4.4.0, as 4.5.0 now throws an issue for me that makes playlists unusable - see [#3957]
