### ISSUE TITLE
Allow Cover Grid the same sorting options as Album List

### ISSUE THREAD

**Issue by everdred** [quodlibet/quodlibet#3820]
I had written out a full justification of allowing `<originaldate>` sorting in Cover Grid before broadening my search through existing issues and finding https://github.com/quodlibet/quodlibet/issues/1486. I think the same justification applies to Cover Grid mode, and this mode would benefit from having the additional sorting options available in Album List mode (date added, original date, play count).

**Comment by declension** [comment]
Fixed in #3853
