### ISSUE TITLE
automatically reverts to old data during song change when editing tags

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#383]
Original [issue 383](https://code.google.com/p/quodlibet/issues/detail?id=383) created by christine.spang on 2010-01-08T01:29:45.000Z:

http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=396311 describes another 
bug that's been present since &lt; 1.0 and is still reproducible in 2.1.98.

To reproduce:
- start playing a song
- open up the tag editor on that song via the context menu
- edit some tags. Don't save!
- fast-forward the song to the just before the end. When the song changes, 
  the unsaved tag edits will disappear and the tags will be as they were 
  before editing started.

This only happens when editing the tags on the song that is _currently 
playing_, as far as I can tell.

**Comment by bassstorm** [comment]
Close in favor of #3484, which contains some ideas re desired behavior.
