### ISSUE TITLE
Panel config not loaded fom disk

### ISSUE THREAD

**Issue by meow464** [quodlibet/quodlibet#3836]
Steps to reproduce
------------------

Preferences -> Column Layout -> Wide

Expected Output
---------------

The panels remain in wide configuration after restart.

Actual Output
-------------

The panels go back to the "normal" configuration.

### Which version of Quod Libet?
4.3.0

### Which operating system 
Debian 11 Stable

Additional Information
----------------------

If I set "Column Layout" to "Columnar" or "Wide" the settings are correctly recorded to the config file as pane_mode = ColumnMode.COLUMNAR but on startup that option is ignored.

**Comment by declension** [comment]
Looks like #3367. 

Can you retry with 4.4? It should be fixed via #3365.

**Comment by meow464** [comment]
That works thanks. I will contact the Debian packager.
