### ISSUE TITLE
misleading error message on moved-away file

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#384]
Original [issue 384](https://code.google.com/p/quodlibet/issues/detail?id=384) created by christine.spang on 2010-01-08T02:12:40.000Z:

When renaming files in exfalso, if you the file being renamed disappears 
during the rename you get this error message (this is up-to-date as of 
2.1.98):

&quot;Renaming 08. Shadows.mp3 to 08 - Shadows.mp3 failed. Possibly the target 
file already exists, or you do not have permission to make the new file or 
remove the old one.&quot;

This doesn't give any mention that the problem could be that the file is no 
longer there. A simple fix would be to change the message, possible to 
something like, &quot;Possibly the target file already exists, you do not have 
permission to make the new file or remove the old one, or the source file 
has moved or been deleted since the rename began.&quot;

There may also be better solutions. Should do this sometime when the 
translations are already being fuzzed from other stuff...

This comes from http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=460972, 
though the error message has changed a bit since the time of that report.

**Comment by declension** [comment]
(re-open if still relevant)
