### ISSUE TITLE
Music Identify

### ISSUE THREAD

**Issue by 3rdRockGuy** [quodlibet/quodlibet#3844]
Is it possible to use quodlibet (in Linux Lubuntu 20.04) to identify a music track from played in quodlibet (or via any music player on the same computer through it's speakers)?
Thx from 3rdRockGuy Stephen

**Comment by declension** [comment]
I guess you mean like Shazam etc? In which case, no definitely not something QL can do.

**Comment by 3rdRockGuy** [comment]
Thx for reply.  Disappointing but as I expected. So here goes plan B.....
