### ISSUE TITLE
Bug : QuodLibet 4.4.0 (iMac - Monterey 12.0.1)

### ISSUE THREAD

**Issue by Paulus1955** [quodlibet/quodlibet#3847]
Problem with QuodLibet 4.4.0 (iMac - Monterey 12.0.1): when the player starts a next song I can hear the song for 2 seconds. Then there is no sound anymore. The timeindicator functions as normal and sometimes after 20 of 30 second the sound reappears. It also appears when I click with the mousepointer on the timeindicator.
Is this a known problem and can I fix it myself?
Greetings and thanks for a spendid app, Paul

**Comment by Meriipu** [comment]
Is it possibly related to gapless playback? #3821

**Comment by Paulus1955** [comment]
Hello Meriipu, your solution works.
Thanks very very much, and greetings, Paulus
