### ISSUE TITLE
Entered name for playlists created from songs is ignored

### ISSUE THREAD

**Issue by everdred** [quodlibet/quodlibet#3860]
Steps to reproduce
------------------
Create a new playlist via song context menu -> Playlists -> New Playlist. 
Enter a name for the playlist.
Playlist is named with the name of the song (or "[name of song] and 1 more"), not the entered name.

Test System
-----------
### Which version of Quod Libet?
4.5-1

### Which operating system 
Debian Sid

**Comment by declension** [comment]
Thanks. Confirmed on ff96acb549987e62092f8dfd76fe7f2a99b3b7ec

**Comment by everdred** [comment]
Yep, it works now. Thanks!
