### ISSUE TITLE
Tracks count UI enhacement 

### ISSUE THREAD

**Issue by jej** [quodlibet/quodlibet#3868]
The proposed change
-------------------
I propose to simplify the display of the number of tracks in the panels. The current way is a bit cumbersome. It uses parentheses that are not really useful, and especially can be confusing for visually impaired people.

![capture_ecran_20211227-130812](https://user-images.githubusercontent.com/33821/147470943-d435aa23-0a9a-4014-822e-88964c021895.png)

Benefits of this change
-----------------------
The patch I propose removes the brackets and adds transparency to the display, so that the information is less present in the panels, but just as visible when the user needs it.

![capture_ecran_20211227-130336](https://user-images.githubusercontent.com/33821/147470961-1746ec88-6ad1-4677-85d1-126789f89241.png)

The code changes are visible here #3867

**Comment by declension** [comment]
Fixed via #3867

**Comment by jej** [comment]
Thanks for the merge.
