### ISSUE TITLE
" [Unknown]" is added after the filename to music without metadata in i3status-rust music block.

### ISSUE THREAD

**Issue by ghost** [quodlibet/quodlibet#3872]
Steps to reproduce
------------------

Play a music file without metadata.

Expected Output
---------------

Only the filename should be shown in the music block just like when using strawberry music player.

Actual Output
-------------

All filenames has " Unknown" next to it.

Test System
-----------

### Which version of Quod Libet?
4.4

### Which operating system 
Arch Linux

### If it's audio-related, what back-end?
gstreamer 1.18.5-1

Additional Information
----------------------
" [Unknown]" was also showing in main window title, the display next to the control buttons, and in the tray icon's tooltip display. I was able to fix it by replacing everything with ~basename.
![Screenshot_2022-01-01_18-41-36](https://user-images.githubusercontent.com/59161287/147848837-143e6901-5b82-4344-8c56-be0b92cd6d65.png)

**Comment by jej** [comment]
Hi,
The fix is easy but maybe has some side effects. To test...
https://github.com/jej/quodlibet/tree/fix-issue-3872
J.
