### ISSUE TITLE
A new option to set how a song is considered as played

### ISSUE THREAD

**Issue by jej** [quodlibet/quodlibet#3874]
The proposed change
-------------------
Still playing (music and coding) with Quodlibet... :)
Currently, a song is considered as played when 50% of duration is listen. For my personal use, 80% is better.

Benefits of this change
-----------------------
The commit #3873 adds a new setting in the pref pane to choose this duration:

![capture_ecran_20220101-224935](https://user-images.githubusercontent.com/33821/147861370-62708fe8-6b04-44cc-a345-bce72452985f.png)

By the way, I changed a bit this pane. To me there is no benefit to have a full section just for one checkbox option:

![capture_ecran_20220101-232734](https://user-images.githubusercontent.com/33821/147861415-0dbe475b-9804-47c4-9ee2-6a3e3c9a1bbc.png)

A more generic section (called here "Listening options") may welcome future options concerning this topic.

Hope it helps.

Any issues this might cause
---------------------------
There are some news strings to translate. I am not english native so feel free to adapt these strings if needed...
And a new option in the config file (`consider_played_percent` in percent, 50% as default)

**Comment by bassstorm** [comment]
Like it!
Got one question though. Looks like only absolute playing position is considered, right? But in case when I use fast forward (or vice versa) it won't work correctly, will it? (Same situation with scrobbling duration I was thinking about back in the days...)

**Comment by jej** [comment]
Hi,
I didn't change the current workflow, just added an option to replace the hardcoded 50%.
Yes, elapsed time is a real time playing:
```
    def __timer(self, timer):
        self.elapsed += 1
```
Each second the counter is incremented. So if you move the time slider, it's not considered as played time. But as said, this was the way to work before my changes.

Some precisions:
- if set to 0%, a song is considered played as soon as it starts. Then if you fast forward or go to next immediately, it's counted as a played song anyway.
- if set to 100%, a song is considered played if it is listened 100% of it's duration (or more if you go backward inside it, of course...)
Hope it's clear.

**Comment by bassstorm** [comment]
Wow, that's much more than I could expect!
Thank you @jej for extra details, despite the fact those are not quite related to pull request itself :)

**Comment by urielz** [comment]
I do like the proposed change. I believe it would be a welcomed addition in-line with QL philosophy.

**Comment by jej** [comment]
Merged
