### ISSUE TITLE
Queue list GUI rework

### ISSUE THREAD

**Issue by jej** [quodlibet/quodlibet#3880]
The proposed change
-------------------
I reworked the GUI of the queue list view. Here is the current interface:

![capture_ecran_20220106-114617](https://user-images.githubusercontent.com/33821/148371325-f3eb7fc5-d173-4a6a-9952-73ab810b2952.png)
There is a config button and a lock button. Inside the config menu, some options for the queue and the clear button.

![capture_ecran_20220106-115017](https://user-images.githubusercontent.com/33821/148371682-2e129a55-86e9-4748-a4b4-fa113edfa813.png)

I propose:
- to move the config button on the right,
- to add a border, like other same buttons in QL,
- move out the clear queue button and put it visible.

Here is the result:
![capture_ecran_20220106-114614](https://user-images.githubusercontent.com/33821/148371944-61915da5-0794-4073-905f-06790c654e2f.png)

The changes are in this PR #3879

Benefits of this change
-----------------------
- the config button contains only "options" and not "actions",
- the config button layout is constant accros QL,
- the clear queue button is more handy here, and make directly visible that this list is something volatile.

Any issues this might cause
---------------------------
I don't really see. I guess in this sense it's easier for users to find the clear button.

Hope it helps,
J.

**Comment by bassstorm** [comment]
Yup, makes sense to me, this way it's much more clear. Thank you!

**Comment by jej** [comment]
Cool, it's merged :) I close it.
