### ISSUE TITLE
Msys2 CI failing on gettext

### ISSUE THREAD

**Issue by declension** [quodlibet/quodlibet#3886]
Steps to reproduce
------------------
Run any `master` (or unbroken branch) build

Expected Output
---------------
No errors for msys2 job

Actual Output
-------------
Errors around gettext
```
gdist\gettextutil.py:277: in check_po
    subprocess.check_output(
D:\a\_temp\msys64\mingw64\lib\python3.9\subprocess.py:424: in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
D:\a\_temp\msys64\mingw64\lib\python3.9\subprocess.py:528: in run
    raise CalledProcessError(retcode, process.args,
E   subprocess.CalledProcessError: Command '['msgfmt', '--check-format', '--check-domain', 'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\tmpqom77s0r.po', '-o', 'nul']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:
tests\test_po.py:46: in test_potfile_format
    gettextutil.check_pot(pot_path)
gdist\gettextutil.py:299: in check_pot
    check_po(po_path, ignore_header=True)
gdist\gettextutil.py:281: in check_po
    raise GettextError(e.output)
E   gdist.gettextutil.GettextError: msgfmt: error while opening "nul" for writing: Invalid argument
```
e.g. https://github.com/quodlibet/quodlibet/runs/4754024878?check_suite_focus=true

**Comment by declension** [comment]
@lazka any ideas what to do here? :thinking:

**Comment by lazka** [comment]
Likely fallout from updating gettext to 0.21. Not clear from the error, I'll have a look.

**Comment by lazka** [comment]
Filed in MSYS2 here: https://github.com/msys2/MINGW-packages/issues/10520

I don't feel like debugging gettext though, so we might just let it write to a dummy file instead.

**Comment by lazka** [comment]
Fix pending here: https://github.com/msys2/MINGW-packages/pull/10541
