### ISSUE TITLE
Icon relooking proposal

### ISSUE THREAD

**Issue by jej** [quodlibet/quodlibet#3890]
Hi all,

I propose a hot topic today!

The proposed change
-------------------
I have been using QL for a short time, but the first thing I did was to relook the icon, after I tested QL a bit and felt this software was promising for my music management. I did this because I use a black background dock and it was difficult to see the QL icon.

![old-icon-dock](https://user-images.githubusercontent.com/33821/149009310-515619a7-1c35-4386-9f49-93da5b5ce052.jpg)

An old issue exists (#3628) but maybe it's a never-ending subject to create a logo from scratch.

So after some thinking about the current icons, I did a relooking that preserve the current history. In fact I don't know who did the icons, and if it was a real design work or just a quick drawing that has survived the ages. Sorry if the original author doesn't like my changes.

The changes:
- I took the VSCodium icon as template concerning dimensions and round design.
- the color of the circle comes from the current twitter logo. https://twitter.com/QuodLibetApp
![capture_ecran_20220111-200004](https://user-images.githubusercontent.com/33821/149005978-8792708a-5652-45f8-9aba-176631a27db5.png)
- the note's "head" is filled. Because a note with a hole brings details to the logo, that does not stretch well. It makes more confusion when down sizing. The same apply for the symbolic icon.
- a light shadow for the pictogram.

- ExFalso icon is relooked in the same spirit. A 12° rotation make it a bit more dynamic.
- Favicon slightly relooked (head filled)
- Symbolic icons relooked like the main icons.

Main icons:
![io github quodlibet QuodLibet](https://user-images.githubusercontent.com/33821/149008855-16cfade2-307b-4f5e-abf4-03953273b4bd.png)
![capture_ecran_20220111-210511](https://user-images.githubusercontent.com/33821/149013411-0589074f-9c92-4b5e-9b29-263c11653f65.png)

![io github quodlibet ExFalso](https://user-images.githubusercontent.com/33821/149008852-d49444b3-4c22-4853-a273-ed5fd2eecdc8.png)
![capture_ecran_20220111-210445](https://user-images.githubusercontent.com/33821/149013419-c64710d7-e078-4cae-9c32-f505853982f1.png)

Symbolic icons:
![io github quodlibet QuodLibet-symbolic](https://user-images.githubusercontent.com/33821/149009146-176270e4-5c69-4463-877e-3de5897450af.png)
![io github quodlibet ExFalso-symbolic](https://user-images.githubusercontent.com/33821/149009141-d92caeaa-4e5e-4cd1-a83e-e69ffec8fa3f.png)

The symbolic icon in the topbar (old vs new):
![menubar](https://user-images.githubusercontent.com/33821/149009214-5b4bd9a5-32b5-435a-99fe-a946d5da09db.jpg)

The favicon of the doc (old vs new):
![favicon](https://user-images.githubusercontent.com/33821/149009712-7dde32f0-981b-4548-94ab-245f079e36ba.png)

The QL icon in situation:
![new-icon-dock](https://user-images.githubusercontent.com/33821/149009271-611007a3-96af-43f3-a9df-95698e4417a6.jpg)

Hope you will like it. Possible to test here: https://github.com/jej/quodlibet/tree/icon-relooking-proposal
You have to `./setup.py install` to install the icons in your OS. Then for gnome desktop ALT+F2 & `r` to reload the desktop and see the icons.

See #3889 for the commit.

Benefits of this change
-----------------------
Maybe too subjective topic to tell more here...

Any issues this might cause
---------------------------
- Icons are technically the same, so they should not cause any trouble.
- Icons are graphically close to the current one. Old icon and new would not make a big difference for a soft transition. At a first glance, new and old are the same because pictogram are almost the same.
- Perhaps the original author might be upset by these changes, although the icon remains quite identical in spirit.

**Comment by bassstorm** [comment]
First of all, thanks for your enthusiasm!
I agree that proposed icon looks more clean and I'd like to go with it for a while at least :)

**Comment by jej** [comment]
Cool if you try it. Thanks to you too.

**Comment by declension** [comment]
Have you seen #3628 - quite a lot of discussion there

**Comment by jej** [comment]
Yep, I quote it above at the beginning
