### ISSUE TITLE
Manually edit database

### ISSUE THREAD

**Issue by Offerel** [quodlibet/quodlibet#3897]
Ho can i manually edit the database? Background is, that i used before another Media player (Media Monkey on Windows). Now i would try to migrate the statistics from the old database to QuodLibet. I can extract the info from Media Monkey, since this uses SQLite as database. But if i'm right, QuodLibet uses some other database to store data like "lastplayed", "playcount" and "added".

**Comment by jej** [comment]
Maybe Import/Export plugin with some scripting?

https://github.com/quodlibet/quodlibet/blob/master/quodlibet/ext/songsmenu/import_export_tags_and_track_user_data.py

**Comment by Offerel** [comment]
I'm using QuotLibet on Manjaro Linux, and as this beeing no real expert there. Is this plugin part of the installation on Manjaro Testing branch or do I have to install the plugin manually and if so, how do I install the custom plugin? I have seen a lot of plugins in the menu, but only one with the name"Metadata export"  and another one with"Metadata import". I'm a little bit unsure how to handle that. I don't want to corrupt my media file's.

**Comment by jej** [comment]
Discussed here #3705. I guess you need version 4.4.0. Easy to get the last version and `make install` it...

But maybe that's not the most simple solution and your idea to sync with a 3rd party service is better. Wait for some more advices.

**Comment by Offerel** [comment]
I have 4.4.0 installed (Maybe since I'm using Manjaro testing branch), but i couldn't find a plugin by that name. If i understand correct the other Import and Export and Migrate plugins should be removed in 4.4.0, but this is not the case by me... maybe some packaging issue. I should try to build QuodLibet by myself. 

I will only import one time at the begin to have a fresh start with some older data. Syncing with last.fm will be for all the future data, since it can only deal with 2 weeks back in time with this service. This is no issue for fresh data, but not useful for data from 2016 :-) 

I have successfully migrated my Media Monkey data to Strawberry, but i fail to sync the playlist from Strawberry to my Android device. That's why i looked into QuodLibet. But to start with this, i will first import my Media Monkey statistics.

But anyhow, i will wait what other say...

**Comment by jej** [comment]
Sorry, my mistake. So pull the master branch and build it...

**Comment by Offerel** [comment]
No prob... will try it. Had some partial success by extracting the needed files to the current version, but not fully. But yes, you are right. i should fully build it.
