### ISSUE TITLE
Cannot download Audio Feed item

### ISSUE THREAD

**Issue by gevhaz** [quodlibet/quodlibet#3898]
Steps to reproduce
------------------
1. Go to Audio Feed browser
2. Select my feed
3. In the list of items of that feed, right-click an item

Expected Output
---------------
The right-click menu should include a "Download" item. According to [this comment](https://github.com/quodlibet/quodlibet/issues/355#issuecomment-281375729), it was possible in 2017 with the steps I described.

Actual Output
-------------
![image](https://user-images.githubusercontent.com/62712116/150656019-654b4c37-546b-40e5-b346-fb5ada901c0d.png)

There is no "Download" item in the menu.

Test System
-----------

### Which version of Quod Libet?
4.4.0

### Which operating system 
Arch Linux

**Comment by declension** [comment]
Confirmed, but see fad935dc52e58b62d103b8246231006db65629e8 where it was removed due to brokenness.

I guess this is now a ticket to reinstate it...

**Comment by gevhaz** [comment]
Yes, I think it would be useful. Downloading podcast items is surprisingly difficult. No direct link to the audio file in the RSS feed, at least for the ones I was looking at. I ended up using the podcasting app on my phone to extract the audio links.

**Comment by gevhaz** [comment]
Thanks, man! I appreciate it :)
