### ISSUE TITLE
Plugin window GUI improvements

### ISSUE THREAD

**Issue by jej** [quodlibet/quodlibet#3901]
The proposed change
-------------------
I propose some changes in the plugin window to address some little problems.

The top dropdown menu filters are not self explicit (All/All):
 
![capture_ecran_20220125-090804](https://user-images.githubusercontent.com/33821/150937350-7d024f21-18d1-4934-ba12-8370b6ecf479.png)

I propose this:

![capture_ecran_20220123-022413](https://user-images.githubusercontent.com/33821/150937437-30de58ac-cc4e-4766-baf1-7bade903f4ff.png)

The search feature cares about accents. It's problematic in some cases (at least in French). For example, searching "édit..." fails to find plugin "Editer les images incorporées" (because the uppercase has not accent here).

![capture_ecran_20220123-024518](https://user-images.githubusercontent.com/33821/150938089-44cbbb66-573d-46ab-8d4c-0e5b77e8455b.png)

![capture_ecran_20220123-024340](https://user-images.githubusercontent.com/33821/150938128-4eee5b20-708c-436a-b114-8c8a95f9b3ad.png)

I propose to filter accents, like in the query search bar.

A last improvement is to search also in PLUGIN_ID property. Then it's possible to have an English name search in addition to the current language. For example in French, if a user know from the documentation or forum that there is a "clock" plugin, he gets "Réveil" when searching it:

![capture_ecran_20220123-022257](https://user-images.githubusercontent.com/33821/150938757-4b96210f-7aca-4bc3-92d9-6387266bdcf3.png)

The changes can be tested in this branch: https://github.com/jej/quodlibet/tree/plugin-window-improved-filtering-gui

See commit #3900

Benefits of this change
-----------------------
As explained above...

Any issues this might cause
---------------------------
- A little more CPU for removing accent but should not impact global performances.
- 2 new strings to translate.

Hope it helps.

**Comment by bassstorm** [comment]
Very nice set of improvements indeed!

**Comment by jej** [comment]
Thanks for your feedback.

**Comment by declension** [comment]
Thanks @jej . FYI if you include _Fixes #3901_ in your PR description, the issues will close automatically (and get tracked better)

**Comment by jej** [comment]
@declension Ok thanks for the trick, I will try it soon.
