### ISSUE TITLE
Add impish (21.10) to PPA

### ISSUE THREAD

**Issue by lpinner** [quodlibet/quodlibet#3908]
Could you please add a release for Ubuntu 21.10 (impish) to ppa:lazka/ppa?

**Comment by s-light** [comment]
similar for `Kubuntu 22.10`
```
Operating System: Kubuntu 22.10
KDE Plasma Version: 5.25.5
KDE Frameworks Version: 5.98.0
Qt Version: 5.15.6
Kernel Version: 5.19.0-21-generic (64-bit)
Graphics Platform: X11
```

> E: The repository 'https://ppa.launchpadcontent.net/lazka/ppa/ubuntu kinetic Release' does not have a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
