### ISSUE TITLE
file extension and original filename for "Rename Files"

### ISSUE THREAD

**Issue by sezanzeb** [quodlibet/quodlibet#3919]
The proposed change
-------------------

Adding `<extension>` and `<filename>`

Benefits of this change
-----------------------

I could organize files into folders based on their extension, which makes it easier for me to only throw lossless files into the converter.

Also, I would like to keep the original filename of those files

**Comment by declension** [comment]
For filename, is `<~basname>` what you want? (see https://quodlibet.readthedocs.io/en/latest/guide/tags/internal_tags.html#string-tags)

**Comment by sezanzeb** [comment]
Yes, thank you! I made this a wikipedia-style link in the rename files docs: https://github.com/quodlibet/quodlibet/pull/3920
