### ISSUE TITLE
New Application Icon for macOS to match design guidelines

### ISSUE THREAD

**Issue by kaffeeundsalz** [quodlibet/quodlibet#3929]
Starting with macOS 11 Big Sur released in late 2020, Apple brought the system-wide icon style for applications more or less in line with the one found in iOS and iPadOS. Since then, all app icons in macOS are based on a rounded rectangle (which is not really a rounded rectangle, [but something called a squircle](https://applypixels.com/blog/the-hunt-for-the-squircle)) and share [some common visual attributes](https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/).

I think it would be nice if QuodLibet would adopt this icon style so it won't seem so much like a foreign body along with other applications. Please have a look at a part of my Dock to see what I mean:

<img width="470" alt="dock_oldicon" src="https://user-images.githubusercontent.com/4942960/156257849-f6848478-e69c-420d-b3a0-cb980f76fe5c.png">

With the redesigned icon from #3889, it doesn't really look better because all the other icons are just so uniform:

<img width="470" alt="dock_newicon" src="https://user-images.githubusercontent.com/4942960/156257845-efbdab84-7085-4ae3-ae28-d7fa394c3552.png">

My approach to this was to first take the old icon and simply put it inside the correct icon shape. The background has a very subtle gradient from top to bottom because it seems this is how others do it:

<img width="470" alt="dock_proposedold" src="https://user-images.githubusercontent.com/4942960/156257857-e55492e6-28e5-47d5-9936-6fb38405e0f7.png">

In addition, I also tried something with the new icon. Here's how it looks when you simply go from circle to squircle:

<img width="470" alt="dock_proposedflat" src="https://user-images.githubusercontent.com/4942960/156257852-94abfd6c-2cf4-4a96-959e-70e53ff79845.png">

It still looks a bit flat compared to the rest of the Dock icons, probably because [gradients and soft lighting seem to be a thing in Apple's aesthetics these days](https://www.inputmag.com/design/apple-macos-big-sur-the-rise-of-neumorphism); therefore, I tried to play around with shading the note a bit and again add a very subtle gradient to the background:

<img width="470" alt="dock_proposedshaded" src="https://user-images.githubusercontent.com/4942960/156257860-18fa5774-51ac-4de1-a8a3-3e01788ebe20.png">

Now, I'm in no way an icon designer. To create something really distinct, one would probably have to take a considerable step further away from just putting the original icon inside a different shape. But maybe these designs could be a good starting point if creating macOS specific application icons is something you would consider adding. Here are all three concepts again side by side:

<img width="1745" alt="app_sxs" src="https://user-images.githubusercontent.com/4942960/156257840-b152c8a4-b151-4963-8845-bdbe87a51742.png">

I can make the same modifications to the Ex Falso icon if you're interested.

**Comment by kaffeeundsalz** [comment]
In case somebody wants to try them out on macOS, here are all icons in .ICNS format (zipped):
[QuodLibet.zip](https://github.com/quodlibet/quodlibet/files/8165205/QuodLibet.zip)

**Comment by declension** [comment]
Thanks! I agree looks much better in that context. I think my favourite is somewhere between the second and the third. Could you slightly lessen the embossing / shading a touch?

**Comment by kaffeeundsalz** [comment]
@declension First of all, thank you very much for your feedback!

> Could you slightly lessen the embossing / shading a touch?

Sure! Looking at it from a distance this morning, I also noticed that my first approach was probably not only a bit exaggerated but also slightly off in terms of design language. macOS icons generally use much softer and larger edges, so I revisited my drafts and created two new versions. Meanwhile, I also made the Ex Falso versions.

<img width="2345" alt="app_sxs_new" src="https://user-images.githubusercontent.com/4942960/156352010-4c156e66-7239-4399-8c82-a17bc160b419.png">

The first one is a completely new approach, but the result is much, much more in line with how Apple's own icons look because I took the Music icon (the one from the Dock screenshots above with the white note on red background right next to Quod Libet) as a reference. Looking at this in more detail, I noticed that they didn't just place the icon above the background. Instead, the note is a cutout of the red squircle casting a shadow and revealing a white background underneath. I recreated the shadows as well as the lighting direction and also tried to mimic the tonal difference between the two color components of the gradient, taking into account that most macOS icons use slightly more intense colors than what is now Quod Libets new default.

The second one is basically what you suggested: I changed the embossing so the entire effect is limited to just one side of the note shape and the transition from the shadow of the implied bevel to the original surface of the note is much smoother. The background gradient is identical to the one of the first draft, so compared to the new version, it's darker and also less vivid.

Please see how it looks in the context of the macOS Dock:

<img width="470" alt="dock_quodlibet_cutout" src="https://user-images.githubusercontent.com/4942960/156352073-a7ceea70-d52c-4424-99f4-2dcad492e8cd.png">
<img width="470" alt="dock_quodlibet_emboss" src="https://user-images.githubusercontent.com/4942960/156352087-a74d40ca-abb6-43b4-8fa2-7690a16ef91f.png">
<img width="470" alt="dock_exfalso_cutout" src="https://user-images.githubusercontent.com/4942960/156352103-a4e69f37-3df3-445c-89e7-1652b76cd77e.png">
<img width="470" alt="dock_exfalso_emboss" src="https://user-images.githubusercontent.com/4942960/156352120-3ddb8f88-793c-42dd-95b4-ba022f174c2b.png">

My drafts are entirely vector now. I think SVG export would work with the cutout version (because it only uses shadows that I could convert to discrete vector objects with gaussian blur applied) but not with the emboss version (because recreating the effect with SVG filter primitives is probably very difficult). That being said, macOS uses raster graphics for icons anyway, so I'd have to export these as pixel images to create the .icns files for the application packages. Drop me a note if you want me to provide these again as well.

**Comment by declension** [comment]
Thanks! Yes I think your first one(s) more consistent (I'm not a Mac user though).

Meanwhile - @lazka happy with this?

**Comment by bassstorm** [comment]
Wow, some great work here!

**Comment by lazka** [comment]
my2c, cutout looks a bit nicer to me

**Comment by kaffeeundsalz** [comment]
Thanks for the feedback – Cutout it is! :) Give me some time to prepare the .icns, my schedule is quite heavy for the next couple of weeks. Do you need the vector source material as well?

**Comment by declension** [comment]
Looks like this might not make #3808 but that's OK
