### ISSUE TITLE
Search REsults In Unwanted Extra Tracks

### ISSUE THREAD

**Issue by hughperson** [quodlibet/quodlibet#3945]
Steps to reproduce
------------------

Type BWV 78 in the search box.

I tried to search for only tracks with tags or filename data that contained the string: BWV 78 

Expected Output
---------------
I should see only tracks containing the string BWV 78 in tags or filenames. Could be an album or a track.

Actual Output
------------------
Tracks with BWV 76, 77, 78, 79 showed up. 
Ideally I'd like ONLy "BWV 78" and not "BWV 178" etc to show, but since I don't know the syntax for that, I was willing to put up with those variants. But not flat out wrong numbers like 76!

I got the output indicated above - tracks with wrong titles appewared BWV 76 for example.

Test System
-----------

Mac OS 10.14.6, Mac Mini Late 2014 i7, 16 GB RAM

### Which version of Quod Libet?
4.4.0

(Edited for format)

**Comment by jej** [comment]
`"BWV 78"` ?

https://quodlibet.readthedocs.io/en/latest/guide/searching.html#exact-matching

**Comment by declension** [comment]
@hughperson please try searching with quotes as @jej suggests above. If this doesn't solve it, feel free to re-open with screenshots or logs
