### ISSUE TITLE
:bug: Player is unable to read codec and bitrate

### ISSUE THREAD

**Issue by x80486** [quodlibet/quodlibet#3965]
I'm trying to configure the elements that are displayed in the second pane (after the controls), and I see that it doesn't recognize the `codec` and `bitrate`, even though it's recognized correctly when I get the information from the track.

![image](https://user-images.githubusercontent.com/34633617/161360469-bae57036-3d96-48be-b1fd-f3eaea4a3ae0.png)

**Comment by xhc1** [comment]
this is right way:

<~bitrate>
<~codec>

**Comment by x80486** [comment]
Thanks, @xhc1. I somehow overlooked the `Tags` sections in the documentation :grin:
