### ISSUE TITLE
Moving library from non-existent path fails

### ISSUE THREAD

**Issue by slosd** [quodlibet/quodlibet#3967]
Steps to reproduce
------------------
Move the library folder from a (non-existent) autofs mount point (Settings > Library > Move).
E.g. path was `/net/host/mnt/music`, target is `/home/user/Music`

Expected Output
---------------
Paths of songs in library should be rewritten to the location in `/home/user/Music`.

Actual Output
-------------
Exception is raised:
```
ValueError: Source PosixPath('/net/host/mnt/music') is not a directory
------
Traceback (most recent call last):

  File "/app/lib/python3.9/site-packages/quodlibet/util/copool.py", line 23, in wrap
    for value in func(*args, **kwargs):

  File "/app/lib/python3.9/site-packages/quodlibet/library/librarians.py", line 149, in move_root
    yield from library.move_root(old_root, new_root)

  File "/app/lib/python3.9/site-packages/quodlibet/library/file.py", line 341, in move_root
    raise ValueError(f"Source {old_path!r} is not a directory")

ValueError: Source PosixPath('/net/host/mnt/music') is not a directory
````

The source path doesn't exist anymore which is the reason for wanting to move the library in the first place. The annoying thing is that afaik I can't easily recreate the original path with a symlink.

Test System
-----------

Quod Libet 4.5.0
openSUSE Leap 15.3

**Comment by declension** [comment]
Hmm, yeah good point. I guess it shouldn't validate this at all then. 

Workaround I guess it to create that dir if possible, but we should fix this

**Comment by slosd** [comment]
I ended up running something along the lines of this: https://github.com/quodlibet/quodlibet/issues/1939#issuecomment-218848923 with the python console plugin. I certainly didn't expect `move_root` to be more than the equivalent of `sed 's/^old_path/new_path/' filenames`.
