### ISSUE TITLE
Playlist shouldn't be sorted on each startup.

### ISSUE THREAD

**Issue by g-plane** [quodlibet/quodlibet#3970]
Steps to reproduce
------------------
I have a plugin which will sort a playlist in a special order, then call `write` method to save the playlist. After executing that plugin, playlist has been sorted. But when Quod Libet starts at the next time, playlist will be sorted in another kind of order, which is unexpected.

Expected Output
---------------
When starting Quod Libet, it shouldn't sort the playlist automatically. Instead, it should keep its order.

Actual Output
-------------
Playlist will be sorted in an unexpected order on each startup automatically.

Test System
-----------

### Which version of Quod Libet?

4.5.0

### Which operating system 

Arch Linux.

**Comment by g-plane** [comment]
Duplicate of #3957

**Comment by declension** [comment]
Closing in favour of #3957
