### ISSUE TITLE
Sort Cover Grid by Date Added

### ISSUE THREAD

**Issue by lixoo81** [quodlibet/quodlibet#3971]
The proposed change
-------------------
Currently the Cover Grid can be sorted by title, artist, date, genre, and rating. I'd like to see 'date added' (i.e. the date when the album was added to the filesystem) as another option to order the cover grid by. This is similar to the way that Bandcamp orders your collection by purchase date.

Benefits of this change
-----------------------
Easier access to new music — I'd like to be able to see recent additions to my library as the top of the cover grid, rather than having to browse for them or writing a search query like #(added < 3 days)

Any issues this might cause
---------------------------
Non that I can think of.

**Comment by declension** [comment]
Fixed by #3853
