### ISSUE TITLE
Tests failed on Arch Linux

### ISSUE THREAD

**Issue by SpriteOvO** [quodlibet/quodlibet#3972]
I'm trying to package this project on Arch Linux x86_64 and RISC-V. I got some test failures on both architectures.

On x86_64:

```
=========================== short test summary info ============================
FAILED tests/plugin/test_trayicon.py::TTrayIcon::test_get_paused_pixbuf - Ass...
FAILED tests/plugin/test_trayicon.py::TTrayIcon::test_new_with_paused_emblem
= 2 failed, 4450 passed, 69 skipped, 13 deselected, 139 warnings in 96.22s (0:01:36) =
```

On RISC-V:

```
=========================== short test summary info ============================
FAILED tests/test_util_copool.py::Tcopool::test_add_remove_with_funcid - asse...
FAILED tests/plugin/test_trayicon.py::TTrayIcon::test_get_paused_pixbuf - Ass...
FAILED tests/plugin/test_trayicon.py::TTrayIcon::test_new_with_paused_emblem
= 3 failed, 4449 passed, 69 skipped, 13 deselected, 139 warnings in 586.67s (0:09:46) =
```

Any ideas about these test failures? I'd be happy to help debug.

-----------

### Which version of Quod Libet?
4.5.0

### Which operating system 
Arch Linux, x86_64 and RISC-V

**Comment by lazka** [comment]
I'm seeing the same error on Windows, so likely some GNOME library update changed something.

**Comment by lazka** [comment]
This was fixed in gtk3: https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/4562

**Comment by lazka** [comment]
It should be possible to temporarily skip the tests via the following env var: `PYTEST_ADDOPTS="-k 'not TTrayIcon'"`

**Comment by SpriteOvO** [comment]
@lazka That env var doesn't work to me, however I cherry-picked that MR, compiled a `gtk3` for `quodlibet`, and now all tests pass. Thanks!

**Comment by lazka** [comment]
hm, weird

**Comment by lazka** [comment]
but, yes, the gtk3 fix will probably help other gtk apps too, so it should be backported anyway.
