### ISSUE TITLE
4.5.0 for MacOS, please?

### ISSUE THREAD

**Issue by dspiliot** [quodlibet/quodlibet#3978]
Hey guys, please do not forget us mac users :)
4.5.0 for the mac... sigh...

**Comment by protrolium** [comment]
I too am hoping we can see an updated Quod Libet on macOS. Truly the best.

**Comment by urielz** [comment]
I would happily take over the creation of the macos binaries if I get a little help to get started. I'm no expert though, but perhaps @lazka and/or @declension if you would kindly provide a rough roadmap of the necessary dev environment and the steps to compile it, I could fill the gaps and try to have a go at it.

**Comment by declension** [comment]
Thanks @urielz ! 
@lazka is the expert there but perhaps the first step would be to get a reproducible dev environment set up if you haven't already. 

In particular I think [CI script](https://github.com/quodlibet/quodlibet/blob/master/.ci/macos-install.sh) should be useful as a starting point, although that itself depends on the binary...

**Comment by lucasvieites** [comment]
Subscribing to this issue. @urielz Have you had any success?
