### ISSUE TITLE
Auto Update Tags In Files steals focus with each song played

### ISSUE THREAD

**Issue by deutrino** [quodlibet/quodlibet#3982]
The proposed change
-------------------
Currently, when Auto Update Tags In Files is enabled, it briefly creates a dialog box every single time it saves a file. This unnecessary dialog box can steal focus in certain environments, namely X2Go + Openbox.

Benefits of this change
-----------------------
Focus won't be stolen with every. single. play. on affected platforms.

Any issues this might cause
---------------------------
Is there really any reason for that plugin to pop up a dialog every time it writes a file??? If so, maybe removing it would be a problem.

**Comment by declension** [comment]
That sounds annoying.... though I can't replicate it here.

A few questions:
* Which version is this? 
* Any idea why this happens (I don't really see why)?
* Or: can you create a video perhaps?

**Comment by racuna** [comment]
Same (Windows 10).

I thought it was the "Animated On-Screen Display" add-on, but after I disabled it, the issue persists.

**Comment by deutrino** [comment]
Hi, I'm on 4.5.0 on Linux Mint, although currently what's actually causing me problems is when I use QL via X2Go to a remote system running Openbox, where the brief dialog box pop-up actually manages to change my virtual desktop out from under me with each song played!

Arguably buggy behavior on ... somebody else's part, except that the dialog box probably shouldn't exist at all to trigger it.

I'll see if I can create a video.

**Comment by multimentha** [comment]
I can confirm this bug using version 4.5.0 on Kubuntu 22.04.

As a temporary fix disabling the addon `Auto Update Tags in Files` works for me.

**Comment by declension** [comment]
OK I can replicate and see the problem; no easy fixes AFAICT though
