### ISSUE TITLE
Persisted XSPF files are non-compliant 

### ISSUE THREAD

**Issue by declension** [quodlibet/quodlibet#3983]
Steps to reproduce
------------------
* Take an QL playlist file
* Validate with https://validator.xspf.org/ or similar

Expected Output
---------------
No validation errors

Actual Output
-------------
Fails, due to dodgy namespacing etc

Slightly unhelpful error messages:
> Root element must be playlist, not 'playlist'.

and what turn out to be knock-on failures about invalid elements

Test System
-----------

### Which version of Quod Libet?
4.4.0 onwards

**Comment by declension** [comment]
I'd actually forgotten to file this ages ago, have a fix...

**Comment by linux4me** [comment]
I'm not sure if the above includes it, but I've noticed in using the XSPF playlists generated by QL that they don't include new lines and indents to make them easily human-readable. The absence of the new lines and line feeds also makes them hang Ubuntu's Text Editor if you try to load large (~4,000 songs, 1.3 MB) playlists.

For example, the format that 4.4.0 creates looks like this:

```
<?xml version='1.0' encoding='UTF-8'?>
<playlist version="1"><title>Test-Original-Format</title><date>2022-05-13T07:42:58.358125</date><trackList><track><location>/media/user/Music/Alice In Chains/Nothing Safe - The Best of the Box/4 - Them Bones.flac</location><title>Them Bones</title><creator>Alice In Chains</creator><album>Nothing Safe: The Best of the Box</album><trackNum>4</trackNum><duration>149466</duration></track></trackList></playlist>
```

That file fails validation on the [XSPF Validator](https://validator.xspf.org/), as well as being difficult to read.

If you use a format like the following, adding new lines, indents (4 spaces), and the XSPF namespace, the file is easily human-readable, passes validation, and even a 1.3 MB playlist including ~4,000 songs loads quickly in Ubuntu's Text Editor.:

```
<?xml version='1.0' encoding='UTF-8'?>
<playlist version="1" xmlns="http://xspf.org/ns/0/">
    <title>Test</title>
    <date>2022-05-12T08:12:49.106365</date>
    <trackList>
        <track>
            <location>/media/user/Music/Alice In Chains/Nothing Safe - The Best of the Box/4 - Them Bones.flac</location>
            <title>Them Bones</title>
            <creator>Alice In Chains</creator>
            <album>Nothing Safe: The Best of the Box</album>
            <trackNum>4</trackNum>
            <duration>149466</duration>
        </track>
    </trackList>
</playlist>
```

**Comment by declension** [comment]
Yes @linux4me I think defaulting to pretty-printed versions is fine though it will add a little size. 

Note also you can use [`xmllint`](https://linux.die.net/man/1/xmllint) to do this.

**Comment by linux4me** [comment]
Thanks @declension, I didn't know about xmllint.

**Comment by robertmuth** [comment]
I am actually super unhappy with the switch to xspf and would really like to seen an option to use the old style format.

playlist handling is better in quodlibet than most other software but far from perfect and there is still the occasional corruption.
Both problems are made worse by xspf:
* it is nice to work around missing playlist features by just bringing up and editor or running scripts. With xspf this much harder
  and now involves xml tools
* quodlibet suggest backing up playlist files since they are "high value" and  I have been doing this for years because I got burnt many times but  xspf produce much worse diffs which makes sanity checking of changes much harder.
