### ISSUE TITLE
Waveform seekbar Error: gst_parse_error: no element "level" (1) 

### ISSUE THREAD

**Issue by Schweber** [quodlibet/quodlibet#3987]
Steps to reproduce
------------------
Launch quodlibet with the waveform seekbar enabled

Expected Output
---------------
Quodlibet launches normally without error and shows the waveform seekbar

Actual Output
-------------

The waveform seekbar is not displayed and quodlibet shows the following error:

```
Error: gst_parse_error: no element "level" (1)
------
Traceback (most recent call last):

  File "/usr/lib/python3.10/site-packages/quodlibet/ext/events/waveformseekbar.py", line 204, in _on_song_started
    self._create_waveform(player.info, CONFIG.max_data_points)

  File "/usr/lib/python3.10/site-packages/quodlibet/ext/events/waveformseekbar.py", line 107, in _create_waveform
    pipeline = Gst.parse_launch(command)

gi.repository.GLib.GError: gst_parse_error: no element "level" (1)
```

### Which version of Quod Libet?
4.5.0-1

### Which operating system 
Arch KDE

### If it's audio-related, what back-end?
gstreamer 1.20.1-1

Additional Information
----------------------
It worked fine on my Manjaro KDE installation. Since migrating to Arch the error occurs and i don't know the reason for it.

**Comment by declension** [comment]
Weird. I think that [should be in the good plugins package](https://gstreamer.freedesktop.org/documentation/level/index.html?gi-language=python#level). Do you have that package installed? If so maybe it's not been included? https://aur.archlinux.org/packages/gstreamer0.10-good-plugins

**Comment by Schweber** [comment]
> Weird. I think that [should be in the good plugins package](https://gstreamer.freedesktop.org/documentation/level/index.html?gi-language=python#level). Do you have that package installed? If so maybe it's not been included? https://aur.archlinux.org/packages/gstreamer0.10-good-plugins

Installing the good plugins solved the problem, thank you! Is it mentioned somewhere that they are required or should they be a dependency of the quodlibet package?

**Comment by declension** [comment]
> 
> Installing the good plugins solved the problem, thank you! Is it mentioned somewhere that they are required or should they be a dependency of the quodlibet package?

Great! I'm not the Arch maintainer nor a user (though might be changing that). At the very least I'd say it should be a "recommended" (or equivalent) dependency here. If / when that plugin gets migrated to the core (some day perhaps) it'd need to be a required plugin anyway.  

> 
> Also, why was quodlibet able to play the file but not produce the waveform without the good plugins?

Playback doesn't need the `level` plugin, but analysing the waveform (to display volume etc) does.

**Comment by Schweber** [comment]
Thank you very much

**Comment by ewtoombs** [comment]
Is there a way quodlibet can have a fallback in case the level plugin isn't available?
See 
https://gitlab.archlinux.org/archlinux/packaging/packages/quodlibet/-/issues/3

**Comment by declension** [comment]
> Is there a way quodlibet can have a fallback in case the level plugin isn't available? See https://gitlab.archlinux.org/archlinux/packaging/packages/quodlibet/-/issues/3

Hmm good point. I guess the plugin could fail more nicely, that's for sure. But don't think there's any practical way of reimplementing all that gstreamer code here [fast enough]
