### ISSUE TITLE
How do you change the appearance of Quod Libet on Windows? Do you have to select a GTK theme somewhere in the config, or is there a way to set a theme for the entire system on Windows. Also, Qoud Libet uses GTK3 on Windows, right?

### ISSUE THREAD

**Issue by jatutterow** [quodlibet/quodlibet#3989]
How do you change the appearance of Quod Libet on Windows? Do you have to select a GTK theme somewhere in the config, or is there a way to set a theme for the entire system on Windows. Also, Qoud Libet uses GTK3 on Windows, right?

_Originally posted by @jatutterow in https://github.com/quodlibet/quodlibet/discussions/3985_

**Comment by declension** [comment]
Closing in favour of Q&A question
