### ISSUE TITLE
Loaded track is removed after queued or 'Stop after this Song'

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#399]
Original [issue 399](https://code.google.com/p/quodlibet/issues/detail?id=399) created by AkshaY.AksCi on 2010-01-26T09:13:52.000Z:

i don't know if this is an issue or no, but whenever i check 'Stop after 
this song', by the end of the current track, the next track is loaded but 
stopped. But if i Reload(restart) quodlibet(for any reason), the loaded 
track is lost.

And I couldn't understand the queue's 'One Song' feature! from the plugins 
section, i've enable 'queue only'.

I just want to resume the next track after i start quodlibet. So maybe it 
is possible for quodlibet to not load the next track, and after the current 
track is played, just keep the nowplaying blank!

i hope i'm clear!
i already love quodlibet too much to put this issue as a 'defect report'

**Comment by bassstorm** [comment]
@CreamyCookie @declension if I understand correctly, this is not an issue anymore.

`I just want to resume the next track after i start quodlibet`

Yes, track is taken out from the queue, but it's not lost after restart, user is able to continue with it and the rest of the queue.

**Comment by CreamyCookie** [comment]
@bassstorm Thanks for finding! Going through a bunch of these old reports can be a struggle, as you have to read every single comment and then often test what they're saying. So any help is appreciated!

(And of course, the old reports also didn't have a template yet, and if they're really old, contain a bunch of noise from the Google Code importer.)

> Yes, track is taken out from the queue, but it's not lost after restart, user is able to continue with it and the rest of the queue.

Exactly. The same happens on my end, when I have a song in the queue, enable "Stop after this", wait until it's finished, then close and restart. When I press play, the correct song starts.
