### ISSUE TITLE
Quod Libet & Ubuntu 22.04

### ISSUE THREAD

**Issue by Adelineenileda** [quodlibet/quodlibet#3991]
Hello

Since the update to Ubuntu 22.04, I can't launch Quod Libet.

### Steps to reproduce

Click on the application or launch Quod Libet on terminal  

### Expected Output
The Quod Libet 's window is opened.

### Actual Output
The Quod Libet 's window don't is opened and there are error on the terminal :

> XXXX@YYYY:~$ quodlibet
> E: 0.302: errorreport.main.errorhook: collection.py:27:<module>: ImportError: cannot import name 'Iterable' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
> Error in sys.excepthook:
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/quodlibet/errorreport/main.py", line 175, in errorhook
>     sentry_error = sentry.capture(exc_info, fingerprint=fingerprint)
>   File "/usr/lib/python3/dist-packages/quodlibet/errorreport/sentrywrapper.py", line 247, in capture
>     client = Client(
>   File "/usr/lib/python3/dist-packages/quodlibet/packages/raven/base.py", line 224, in __init__
>     from raven.context import Context
>   File "/usr/lib/python3/dist-packages/quodlibet/_import.py", line 47, in load_module
>     mod = importlib.import_module(loadname)
>   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "/usr/lib/python3/dist-packages/quodlibet/packages/raven/context.py", line 10, in <module>
>     from collections import Mapping, Iterable
> ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
> 
> Original exception was:
> Traceback (most recent call last):
>   File "/usr/bin/quodlibet", line 14, in <module>
>     sys.exit(main())
>   File "/usr/lib/python3/dist-packages/quodlibet/main.py", line 44, in main
>     import quodlibet.library
>   File "/usr/lib/python3/dist-packages/quodlibet/library/__init__.py", line 20, in <module>
>     from quodlibet.library.libraries import SongFileLibrary, SongLibrary
>   File "/usr/lib/python3/dist-packages/quodlibet/library/libraries.py", line 32, in <module>
>     from quodlibet.util.collection import Album
>   File "/usr/lib/python3/dist-packages/quodlibet/util/collection.py", line 27, in <module>
>     from collections import Iterable
> ImportError: cannot import name 'Iterable' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

### Which version of Quod Libet ?
4.4.0
### Which operating system ?
Ubuntu 22.04

**Comment by declension** [comment]
Yes this is unfortunate as we missed the deadline for Ubuntu 22.04; see #3818. 

Can you try `4.5.0` as detailed there?

**Comment by Adelineenileda** [comment]
I install Ex Faso and then Quod Libet with the deb packages that I find in [this comment](https://github.com/quodlibet/quodlibet/issues/3818#issuecomment-1106646230).
And with `4.5.0` and Quod Libet launch without problem. 
I have only some errors in terminal but they don't perturb the application :

> ** (io.github.quodlibet.QuodLibet:12495): WARNING **: 13:55:27.121: Binding 'XF86AudioRandomPlay' failed!
> E: 4.670: formats._misc.MusicFile: __init__.py:402:__init__: quodlibet.formats._misc.AudioFileError: can't sync to MPEG frame

Thanks a lot for the link.
Have a good day.

**Comment by elcste** [comment]
Ubuntu just [released an updated 4.4.0 package](https://bugs.launchpad.net/ubuntu/+source/quodlibet/+bug/1964791/comments/13) for 22.04 that includes a cherry-picked fix for the Python 3.10 startup issue.

Additionally, Ubuntu Kinetic (development release that will become 22.10) now includes the 4.5 package from Debian.
