### ISSUE TITLE
4.6 release

### ISSUE THREAD

**Issue by declension** [quodlibet/quodlibet#3992]
Including the playlist dnd bugfix and any others we want to cherrypick

Ubuntu is hopefully updating 22.04 so there might be a chance to get this in? https://bugs.launchpad.net/bugs/1964791

**Comment by elcste** [comment]
Ubuntu released a cherry-picked fix for the Python 3.10 startup issue for 22.04, instead of updating to 4.5, because they thought it was too big a changeset to include in an already-released stable version. So I doubt they will update 33.04 to include any 4.5.1 release either.

**Comment by declension** [comment]
Ok thanks.  This might be still be useful for other users so an leaving open

**Comment by FerdiScholten** [comment]
Perhaps do a 4.5.1 release in the quodlibet-stable ppa
That playlist bug is really annoying and causes me to run Quodlibet from my local git clone that has the fix.

**Comment by declension** [comment]
I think with Ubuntu patched manually and limited time a 4.6.0 might make more sense now (but yes, would be good to get _either_ out soon)

**Comment by zeezhao** [comment]
Hi @declension 
Please we are still waiting on v4.6... :)
I am still on v4.4 because of the playlist bug...
Thanks

**Comment by declension** [comment]
I'm a bit short on time, but happy to help with a 4.6 release if @lazka is available (TODO: #3904)

**Comment by declension** [comment]
If anyone fancies testing current `master`, that would help...

**Comment by FerdiScholten** [comment]
I am using current master since the playlist problem got fixed. Running directly from my local git. Works fine for me.
There is one issue, but that is not new (was also present in versions before 4.5) and already reported I think. I will check.

**Comment by declension** [comment]
All - please help us test [the many fixes (or not...) since 4.5.0](https://github.com/quodlibet/quodlibet/compare/release-4.5.0...master)

Aiming for a smoother release :crossed_fingers:

**Comment by FerdiScholten** [comment]
Any chance of a 4.6.0 release soon?
Running without issues so far from current master. Even the issue (that was already reported about playlist not updating) has been fixed.

**Comment by declension** [comment]
Back to this, would like to plan what is outstanding for 4.6 to be released. Have made https://github.com/quodlibet/quodlibet/milestone/19 in case there are any must haves, but at this point I think it's just stability and release process that are in the way

**Comment by declension** [comment]
Update: the plan is to cut off and branch soon and plug away at [the release process](https://quodlibet.readthedocs.io/en/latest/development/maint.html), aiming to automate / update it a bit (it's incomplete and maybe a bit wrong now too)

**Comment by doubledge-spec** [comment]
any update?

**Comment by FerdiScholten** [comment]
Apparently 4.6 has been released.
Any chance the "lazka ppa" will be updated with this new release soon? I have no problems running from my local git clone, but I know some users that anxiously await this release and are not as technically capable to run their own git clone and run from source.

**Comment by lazka** [comment]
> Any chance the "lazka ppa" will be updated with this new release soon?

I'll have a look

**Comment by declension** [comment]
Meanwhile, an update:
* [4.6.0](https://github.com/quodlibet/quodlibet/releases/tag/release-4.6.0) is indeed out, with source dists only though.
* [4.6.0 Changelog](https://quodlibet.readthedocs.io/en/latest/changelog.html#release-4-6-0) includes most of the details
* Various downstream Linux releases should have happened now, e.g. [Quodlibet on Arch](https://archlinux.org/packages/extra/any/quodlibet/), [Quodlibet on Fedora Rawhide](https://packages.fedoraproject.org/pkgs/quodlibet/quodlibet/fedora-rawhide.html)
* Windows is now building in CI :up:. A few niggles to sort out (thanks to @lazka, see https://github.com/quodlibet/quodlibet/commit/e640da35954e5f0e5322cc70c8f569c7bf9740fa and follow-ups). So hopefully Windows installers will be added to the release soon
* [4.6.0 is now out on Flathub](https://flathub.org/apps/io.github.quodlibet.QuodLibet)
* macOS sadly is not being released any time soon, unless we can get some volunteers to look into modern macOS & GTK+  building  (see #3978)
* PPA updates (not fully automatable AIUI) potentially coming (see above)

**Comment by FerdiScholten** [comment]
Keep up the good work!

Very glad with the new release.

**Comment by zeezhao** [comment]
Thanks for all the hard work! Been waiting for this one. 👍

**Comment by HomoElectromagneticus** [comment]
I am hoping for a MacOS release sometime! My skills are way more in the embedded world so helping out seems a bit over my head, but I wanted to note that there is still demand for a MacOS version :-) Thanks all for your contributions!

**Comment by Oldbwl** [comment]
Sorry to be a nag, but I am unable to use the Flatpak system or run from Git clone, is there an chance the PPA will be updated soon? (Linux Mint Cinnamon 21.2) or even a .deb build?

Dan

**Comment by FerdiScholten** [comment]
I know of several people also waiting for a .deb release most of them still using 4.4 because of the playlist bug in 4.5

**Comment by lazka** [comment]
I've updated the PPA, though only 22.4+ since everything older is missing dependencies

**Comment by FerdiScholten** [comment]
Fantastic, I'll spread the word to those waiting for it, many thanks!!!

**Comment by barraclm** [comment]
I have just moved from Manjaro (where QuodLibet ran just fine) to Linux Mint (Cinnamon 21.2) and find that I am unable to run QuodLibet. It appears to install (entry in the menu system) but does not run. This is true for both .deb and FlatPak. If you run it in the terminal you get the following message
E: 0.471: errorreport.main.errorhook: collection.py:686:_populate_from_file: AttributeError: 'NoneType' object has no attribute 'text'

Any suggestions please?
