### ISSUE TITLE
revise/update the GUI

### ISSUE THREAD

**Issue by robgrune** [quodlibet/quodlibet#3997]
The proposed change
-------------------
Priority #1.  Add an icon to the menu bar to invoke the Equaliser
#2. Add colour schemes.
#3. Add an icon bar below or next to the main menu bar.

Benefits of this change
-----------------------
#1. Having the Equaliser easily invoked will enhance the user experience.
#2. Enhances user experience.
#3. Enhances user experience.

Any issues this might cause
---------------------------
Should not cause issues.

**Comment by declension** [comment]
This is three issues really - please split them to help discussing each. Some have previous issues that are relevant
