### ISSUE TITLE
Media Controls are not avaliable under GNOME

### ISSUE THREAD

**Issue by phikal** [quodlibet/quodlibet#3999]
Steps to reproduce
------------------
I am trying to control Quod Libet using the media keys on my keyboard.

Expected Output
---------------
Tracks are skipped, paused, etc.

Actual Output
-------------
The keys were ignored, as there was apparently no program registering the input.  If I try a different music player like Rhythmbox, the keys are registered and behave as expected.

Test System
-----------

### Which version of Quod Libet?
4.5.0

### Which operating system 
Fedora 36

### If it's audio-related, what back-end?
N/A

Additional Information
----------------------
I tried to build quodlibet locally, but it failed with an error message indicating that Glib and Gio were not avaliable.  I don't have enough experience with Python or GNOME/GTK development to make sense of this.

**Comment by locness3** [comment]
I think you should enable the "MPRIS D-Bus Support" plugin.

**Comment by RoestVrijStaal** [comment]
> I think you should enable the "MPRIS D-Bus Support" plugin.

Why isn't it in Quod Libet by default?
