### ISSUE TITLE
Move to Python 3.10

### ISSUE THREAD

**Issue by declension** [quodlibet/quodlibet#4005]
The proposed change
-------------------
Bump minimum Python version of 3.9 

Benefits of this change
-----------------------
* We get
([ElementTree.indent](https://docs.python.org/3/library/xml.etree.elementtree.html#xml.etree.ElementTree.indent) see some discussion #3983 )
* Clean up lots of collection typings with builtins, should we want to (https://peps.python.org/pep-0585/)
* [Dict merges](https://docs.python.org/3/whatsnew/3.9.html#dictionary-merge-update-operators) are quite nice 
* We're that much closer to 3.10, where [quite a lot of exciting things](https://docs.python.org/3/whatsnew/3.10.html) happened.

Any issues this might cause
---------------------------
Anyone on 3.8 will be stuck on the current release.

But Debian (bullseye) is 3.9, Ubuntu 22.04 is 3.10, `alpine:latest` is 3.10, Fedora 34 is 3.9 (35 is 3.10) etc.

**Comment by lazka** [comment]
I'd guess this mostly affects 20.04 users. Fine with me personally given that there is flatpak, but not sure if everyone will be happy.

**Comment by declension** [comment]
Yeah probably not that urgent, and have a hacky workaround for the etree thing anyway

**Comment by declension** [comment]
I'm now thinking Python 3.10 might be a better target (for QL 4.7), especially given 3.12 is out

### Currently

| OS | Version | Notes |
|--------|--------|--------|
| Ubuntu 23.10 | 3.11 | |
| Ubuntu 22.04 | 3.10 | |
| Debian stable (bookworm)| 3.11 |  |
| Arch latest| 3.11 |  |
