### ISSUE TITLE
Support of MP3 star rating tag

### ISSUE THREAD

**Issue by stax76** [quodlibet/quodlibet#4018]
I would like to request support of the MP3 star rating tag:

https://en.wikipedia.org/wiki/ID3?oldformat=true#ID3v2_star_rating_tag_issue

My files are tagged like so:

1star: POPULARIMETER: MusicBee|1|0
2star: POPULARIMETER: MusicBee|64|0
3star: POPULARIMETER: MusicBee|128|0
4star: POPULARIMETER: MusicBee|196|0
5star: POPULARIMETER: MusicBee|255|0

[sample.zip](https://github.com/Martchus/tageditor/files/8910665/Koan.-.Selena.s.Song.Blue.Mix.zip)

More info:

https://github.com/Martchus/tageditor/issues/84

https://github.com/mpv-player/mpv/issues/10291

https://github.com/MediaArea/MediaInfo/issues/620

**Comment by declension** [comment]
Yes QL [supports ratings from `POPM`](https://github.com/quodlibet/quodlibet/blob/f2c2f5e5e93308d00ae126250ac758a760b98353/quodlibet/formats/_id3.py)

**Comment by stax76** [comment]
My files are from MusicBee which is a very popular player. MediaMonkey and Windows File Explorer, which are also very popular applications, detect my ratings correctly, these popular applications are all compatible, Quod Libet 4.5 isn't, won't detect my ratings. The code is either buggy or don't cover popular use cases.

**Comment by declension** [comment]
Ratings in ID3V2 are based on an email address, so you'll need to use the same one if you want compatibility between QL and other players.

That zipped file, for example, uses `Musicbee` as the email address and gives it a 255 rating. QL uses either a default email address (`quodlibet@lists.sacredchao.net`), or the one configured in the preferences - so you might want to try setting that to `Musicbee` for consistency with your existing files.

Closing this issue. Though please file tickets for any bugs found, or new feature requests (note [existing ratings tickets](https://github.com/quodlibet/quodlibet/issues?q=is%3Aissue+is%3Aopen+ratings)).

**Comment by stax76** [comment]
I'm wasting my time here.
