### ISSUE TITLE
"Created" column

### ISSUE THREAD

**Issue by gevhaz** [quodlibet/quodlibet#4026]
The proposed change
-------------------
It would be useful to me if there was a column saying when the song file was created. This would be from the os, not from the meta data. I don't think this is possible at the moment.

Benefits of this change
-----------------------
Generally useful. I want to see when files were added to my library, but this information gets reset if you create a new database after reinstalling a system, and for me it was just reset one day. The "created" information from the os is a bit more persistent.

**Comment by declension** [comment]
I just had a go at this and got some weird results, before learning that on POSIX-style OSes `ctime` is not the created time but the (see [Python stat() docs](https://docs.python.org/3/library/stat.html#stat.ST_CTIME)).

So I think this only would be useful / correct on Windows, and is thus probably not something we can add

**Comment by gevhaz** [comment]
Thanks for looking in to it.

Seems to be a file system thing more than a Linux thing, as far as I can tell. Ext4 file systems seem to have a `crtime` row when you run `stat a_file`. Like this:

```
[me@my-computer dir]$ stat a_song.opus
  File: a_song.opus
  Size: 4612151   	Blocks: 9016       IO Block: 4096   regular file
Device: 252,1	Inode: 23987577    Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/   me)   Gid: ( 1000/   me)
Access: 2022-06-27 21:57:03.669679559 +0200
Modify: 2022-06-25 14:17:23.842153101 +0200
Change: 2022-06-25 14:17:23.842153101 +0200
 Birth: 2020-05-11 23:41:13.399573510 +0200
```

But I agree it doesn't make sense to add if it can't work reliably. Closing.
