### ISSUE TITLE
ID3v1 plugin for MP3 files

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#403]
Original [issue 403](https://code.google.com/p/quodlibet/issues/detail?id=403) created by 31337H4ck3r on 2010-01-29T17:57:02.000Z:

I would like Exfalso to have options to specify between ID3v1, ID3v2, or
both. As well as options to the version such as ID3v2.3 ISO-8859-1, ID3v2.3
UTF-16, or ID3v2.4 UTF-8.

**Comment by lazka** [comment]
Add a plugin with "write id3v1", write id3v2.3"

**Comment by svnpenn** [comment]
https://github.com/quodlibet/quodlibet/issues/2041

**Comment by svnpenn** [comment]
https://github.com/quodlibet/quodlibet/issues/160

**Comment by svnpenn** [comment]
https://github.com/quodlibet/mutagen/issues/82

**Comment by svnpenn** [comment]
https://github.com/quodlibet/mutagen/issues/85

**Comment by svnpenn** [comment]
@lazka if this is fixed in mutagen - can it be brought into quodlibet?

http://mutagen.readthedocs.io/en/latest/user/id3.html#id3-versions

**Comment by lazka** [comment]
Why do you comment on every issue?

**Comment by CreamyCookie** [comment]
Closing this as ID3v1 is outdated, this issue is very old and there seems to be no interest in developing or even using such a plugin / change by that many people. 

If I'm mistakes, please feel free to reopen or comment here. :)
