### ISSUE TITLE
application crashes upon launch

### ISSUE THREAD

**Issue by multimentha** [quodlibet/quodlibet#4044]
Steps to reproduce
------------------
1. Launch Quodlibet application (via start menu // tray bar // CLI -- doesn't matter which one)
2. Simply wait for the main window to open; no further input (mouse/keyboard) required at this point.

Expected Output
---------------
Quodlibet should launch as usual and become usable.

Actual Output
-------------
Quodlibet main application window opens. After about 1 second a dialog window without title or content pops up and the application crashes (confer attached screen recording).

When launching the app via the command line, the following error message occurs:
```
$ cat quodlibet_launch_stderr.txt

** (io.github.quodlibet.QuodLibet:12056): CRITICAL **: 11:45:19.910: void webkit_settings_set_user_agent(WebKitSettings*, const char*): assertion 'WebCore::isValidUserAgentHeaderValue(userAgentString)' failed
E: 2.187: fake.plugins.trayicon.get_indicator_impl: appindicator.py:14:<module>: ImportError: Namespace AppIndicator3 not available

** (io.github.quodlibet.QuodLibet:12056): WARNING **: 11:45:20.048: Binding 'XF86AudioPrev' failed!

** (io.github.quodlibet.QuodLibet:12056): WARNING **: 11:45:20.049: Binding 'XF86AudioNext' failed!

** (io.github.quodlibet.QuodLibet:12056): WARNING **: 11:45:20.049: Binding 'XF86AudioStop' failed!

** (io.github.quodlibet.QuodLibet:12056): WARNING **: 11:45:20.049: Binding 'XF86AudioPlay' failed!

** (io.github.quodlibet.QuodLibet:12056): WARNING **: 11:45:20.050: Binding 'XF86AudioRepeat' failed!

** (io.github.quodlibet.QuodLibet:12056): WARNING **: 11:45:20.050: Binding 'XF86AudioRandomPlay' failed!
E: 2.913: errorreport.main.errorhook: faulthandling.py:138:raise_and_clear_error: quodlibet.errorreport.faulthandling.FaultHandlerCrash: Fatal Python error: Aborted
```

### Which version of Quod Libet?
4.3.0

### Which operating system 
Linux 5.13.0-52-generic #59-Ubuntu SMP Wed Jun 15 20:17:13 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Additional Information
----------------------

https://user-images.githubusercontent.com/13744422/179351172-f945d1c7-39fd-47e2-ac86-31384abe30dd.mp4

**Comment by declension** [comment]
Thanks for the report. Which Ubuntu is this?

**Comment by declension** [comment]
Also, have you tried QL 4.4.0 or 4.5.0 ?

**Comment by multimentha** [comment]
my Ubuntu version is:

`$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=21.10
DISTRIB_CODENAME=impish
DISTRIB_DESCRIPTION="Ubuntu 21.10"`

with KDE Plasma 5 (in case that matters):
`Operating System: Kubuntu 21.10
KDE Plasma Version: 5.22.5
KDE Frameworks Version: 5.86.0
Qt Version: 5.15.2
Kernel Version: 5.13.0-52-generic (64-bit)
Graphics Platform: X11
Processors: 4 × AMD A8-6600K APU with Radeon(tm) HD Graphics
Memory: 7.7 GiB of RAM
Graphics Processor: NVIDIA GeForce GT 730/PCIe/SSE2`

# resolution
Installing version 4.5 via the extra repository by itself didn't help with the issue, not even when running `apt purge quodlibet` beforehand.

I did however now delete all of Quod Libet's files stored in my home directory (inside the `.config` and `.cache` subdirectories) and after this I can use the app just fine. I had made a backup beforehand and restoring `.config/quodlibet` to its previous state again makes the app crash on launch. Thus I'm assuming some setting got corrupted, but I'm unsure which files exactly are responsible. I was able to manually copy back the contents of `lists` and `playlists`, as well `config` without problems.

I can upload the full backup of `.config/quodlibet` if desired, otherwise you can _close_
 this issue.
