### ISSUE TITLE
last.fm features!

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#405]
Original [issue 405](https://code.google.com/p/quodlibet/issues/detail?id=405) created by AkshaY.AksCi on 2010-01-31T12:04:15.000Z:

could quodlibet deal with the last.fm features? like tagging, loved tracks, 
last.fm playlists in the playlists section, recently added, listened tracks 
and so on!
just some functionalities which last.fm client does!

Thank You!

**Comment by kenden** [comment]
This might be coverd by this plugin:
https://github.com/quodlibet/quodlibet/issues/303
(code in the old google code)

**Comment by CreamyCookie** [comment]
Closing as this is partially covered by #303, it's very old and there hasn't been much interest AFAICS.
