### ISSUE TITLE
Library scan ignores symlinked directories

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#406]
Original [issue 406](https://code.google.com/p/quodlibet/issues/detail?id=406) created by steven.strobe.cc on 2010-01-31T21:14:35.000Z:

This one never had an issue associated with it. Now it does.

Adding symlink support to the library scan is not as simple as it might
appear, and the few patches that have been submitted via the mailing list
don't get it entirely right. Quod Libet tracks mountpoint as well as file
path, and for many users the point of having symlinks in their scans is so
that they can offload their libraries to other drives. This would get
screwed up if we just blindly followed symlinks, with the result being
library duplication, loss of stats, and other nastiness.

There are a few approaches to fixing this in 2.5, and I plan on getting one
done, but it's always been a low priority issue because there are two
perfectly suitable workarounds. The first is to bind-mount a directory: ::

```
$ sudo mount -o bind /mnt/music /home/steven/Music
```

and the second is to toy with the paths in the songs pickle as described in
the Development_FAQ page on the wiki.

**Comment by CreamyCookie** [comment]
Closing this since it seems like [symlinks are indeed dereferenced](https://github.com/quodlibet/quodlibet/blob/f349563cf078fa3815807c2b220f85b55182a609/quodlibet/library/libraries.py#L477), and this report is very noisy (low information density).
