### ISSUE TITLE
Help debugging missing libdee

### ISSUE THREAD

**Issue by cdfa** [quodlibet/quodlibet#4085]
Hi, some time ago, Quod Libet stopped working after a system update. I [asked on the forum of my distro](https://forum.garudalinux.org/t/quod-libet-fails-to-start/21299), but it seems to be working for other people, so it's probably something on my system. So I'm primarily looking for any ideas to debug. I hope you can help.

Steps to reproduce
------------------
```
$ env G_MESSAGES_DEBUG=all quodlibet --run
```

Expected Output
---------------
Quod Libet starts.

Actual Output
-------------
```
$ env G_MESSAGES_DEBUG=all quodlibet --run
(quodlibet:164173): GLib-GIO-DEBUG: 20:45:09.860: _g_io_module_get_default: Found default implementation local(GLocalVfs) for ‘gio-vfs’

(quodlibet:164173): Gtk-WARNING **: 20:45:09.886: Theme parsing error: gtk-dark.css:5823:26: '-shadow' is not a valid color name

(quodlibet:164173): Gtk-WARNING **: 20:45:09.886: Theme parsing error: gtk-dark.css:5826:14: not a number

(quodlibet:164173): Gtk-WARNING **: 20:45:09.886: Theme parsing error: gtk-dark.css:5827:13: not a number

(quodlibet:164173): Gtk-WARNING **: 20:45:09.886: Theme parsing error: gtk-dark.css:5828:11: Expected a length
(quodlibet:164173): GLib-GIO-DEBUG: 20:45:09.929: _g_io_module_get_default: Found default implementation dconf(DConfSettingsBackend) for ‘gsettings-backend’
(quodlibet:164173): dconf-DEBUG: 20:45:09.929: watch_fast: "/org/appmenu/gtk-module/" (establishing: 0, active: 0)
(quodlibet:164173): dconf-DEBUG: 20:45:09.929: unwatch_fast: "/org/appmenu/gtk-module/" (active: 0, establishing: 1)
(quodlibet:164173): dconf-DEBUG: 20:45:09.931: watch_established: "/org/appmenu/gtk-module/" (establishing: 0)
(quodlibet:164173): dconf-DEBUG: 20:45:09.931: watch_fast: "/org/appmenu/gtk-module/" (establishing: 0, active: 0)
(quodlibet:164173): dconf-DEBUG: 20:45:09.931: unwatch_fast: "/org/appmenu/gtk-module/" (active: 0, establishing: 1)
(quodlibet:164173): dconf-DEBUG: 20:45:09.932: watch_established: "/org/appmenu/gtk-module/" (establishing: 0)

** (io.github.quodlibet.QuodLibet:164173): WARNING **: 20:45:11.523: Failed to load shared library 'libdee-1.0.so.4' referenced by the typelib: libicui18n.so.70: cannot open shared object file: No such file or directory
E: 1.892: errorreport.main.errorhook: types.py:247:__init__: TypeError: must be an interface
```

Test System
-----------

### Which version of Quod Libet?
4.5.0

### Which operating system 
5.18.16-zen1-1-zen GNU/Linux (Garuda)

Additional Information
----------------------
`libdee` is installed on my system at `/usr/lib/libdee-1.0.so.4`. Package `chaotic-aur/dee 1.2.7-13`

**Comment by declension** [comment]
Never seen this and looks quite system-related. Have you tried reinstalling / upgrading `libicui18n`?

**Comment by cdfa** [comment]
Looking into `libicui18n` it seems I have version `71.1` installed, which seems weird, because the error message claims an include from `libicui18n.so.70` is failing. It seems I don't have that version:

```
$ ls /usr/lib/libicui18n.so*
/usr/lib/libicui18n.so  /usr/lib/libicui18n.so.71  /usr/lib/libicui18n.so.71.1
```

Does that mean my `libicui18n` is too new?

**Comment by declension** [comment]
I'm not sure but it does sound like some kind of broken upgrade ([slightly related forum post perhaps](https://forum.garudalinux.org/t/joplinapp-desktop-error-while-loading-shared-libraries-libicui18n-so-68-cannot-open-shared-object-file-no-such-file-or-directory/7284)).

I read this as `dee` needing a version of `libicu` you no longer have, so fixing / reinstalling _that_ might be your best bet, but that's a Garuda question I guess (or maybe AUR) 

Worth looking at https://aur.archlinux.org/packages/dee perhaps too, lots of build failures reported there
