### ISSUE TITLE
Disable sorting by columns for playlist views entirely

### ISSUE THREAD

**Issue by declension** [quodlibet/quodlibet#4099]
The proposed change
-------------------
Somewhat radical, but given the difficulty with #3957 and #2595 and #691 and #1645 and #3271, maybe the solution is simply not to _have_ playlist-specified order **and** clickable user order from column headings.

Benefits of this change
-----------------------
Simplicity, and better / more bug-free behaviour

Any issues this might cause
---------------------------
* It's an outlier then for all browsers
* People may actually like having this (e.g. I use it to quickly find how many songs by an artist are in a playlist)

Workarounds
-----------------
Add an *explicit* playlist feature to _permanently_ reorder by columns (e.g. right click or something)

**Comment by FerdiScholten** [comment]
I need to have my playlists exclusively and only in the order that I have specified. so fine with me.

**Comment by zeezhao** [comment]
Hi. I actually like the sorting feature, when I need restrictions on the number of tracks per artists or number of tracks from an album in any particular playlist. May be it could be a setting in the configuration panel? Thanks

**Comment by Meriipu** [comment]
I think a solution might be to

* If a playlist is sorted by a column and the user attempts to drag-and-drop tracks inside or into the playlist-tracklist, prompt the user saying something to the effect of "this will modify the playlist order to the current column-sort"
* If the user tries to extend the (currently active) playlist via either dragging+dropping something onto it (in the sidebar of playlists), or by right-clicking track(s) and trying to add/remove them, prompt the user with "Restore playlist to playlist order before (insertng/removing) tracks? [restore before insert/insert into current order/cancel]"

I am very against removing the ability to sort the playlist by column.

**Comment by afontenot** [comment]
If we put aside the bugs with active play order (which really needs something like https://github.com/quodlibet/quodlibet/issues/4157), the rest of this should be fixable, right? What I would do is

 * Show an explicit column for the true (playlist) order.
 * When sorted by true order, drag and drop playlist editing is enabled.
 * When sorted by another column, dragging and dropping playlist items is disabled. Optionally, trying to drag and drop a playlist item could show a message box indicating the problem.
 * When sorted by another column, using the playlist view as a drop target for songs from another (outside the current playlist) source will return the playlist view to true order, and append the dropped song to the end of the playlist.

**Comment by Meriipu** [comment]
most of that sounds sensible to me

but

> When sorted by another column, dragging and dropping playlist items is disabled. Optionally, trying to drag and drop a playlist item could show a message box indicating the problem.

perhaps with a way to save the new order in case the user would like to reorder from a given sort, although I suppose creating a new playlist by dragging all the tracks into it would be a workaround.

**Comment by bassstorm** [comment]
I personally prefer fb2k way of doing that, i.e. sort by column is a one-time action. That way it's very handy for quick actions like @afontenot mentioned.
Sticky sorting is expected from "live" playlists, which are nothing else but a container for query results. For regular playlists it's just confusing.
