### ISSUE TITLE
Create a plugin for recording streams

### ISSUE THREAD

**Issue by Villelmo** [quodlibet/quodlibet#4103]
The proposed change
-------------------

Record a transmission in streaming

Benefits of this change
-----------------------

Can record a transmission in streaming

Any issues this might cause
---------------------------

**Comment by declension** [comment]
Hi. This will probably involve a fair bit of [gstreamer](https://gstreamer.freedesktop.org/) work so best to read up on that, and might work as a Gstreamer QL plugin - see the [Plugin Development docs](https://quodlibet.readthedocs.io/en/latest/development/plugins.html).

**Comment by Villelmo** [comment]
Actually i am using a different software, a privative software. 

http://raimersoft.com/rarmaradio.html

I want implement this funcionality in quodlibet.
