### ISSUE TITLE
Adding streams to audio feed browser causes app to hang

### ISSUE THREAD

**Issue by i88ux** [quodlibet/quodlibet#4107]
Steps to reproduce
------------------
It is my first time on the forum, I tried my best to follow guidelines. I had quite some difficuties to find existing bug reports related to my issue. Thanks.

To play an online radio audio flux, I selected the Browse>Audio Feeds menu then clicked the "+New" button.
In the popup window I pasted the URL: [http://direct.fipradio.fr/live/fip-midfi.mp3](url) that I founded on this page: [https://doc.ubuntu-fr.org/liste_radio_france](url)

Expected Output
---------------
I expected Quod Libet to play the audio feed.

Actual Output
-------------
The interface freezes and I had to kill the task or if I try the restoration option from the task manager, I got the message below (see screenshots). 

Test System
-----------
I tested with a few other links with the same result, and with my browser that could play the audio fees without any problem.
### Which version of Quod Libet?
4.5.0

### Which operating system 
Microsoft Windows 10 Famille, version 10.0.19044 Build 19044

### If it's audio-related, what back-end?
I could not find this information.

Additional Information
----------------------
I set the Quod Libet language to English but I use a system with French, sorry for the mixed languages infos.
![image](https://user-images.githubusercontent.com/19994035/185353178-580f4590-b4a5-489a-9dd7-f7e8d77fa954.png)

![image](https://user-images.githubusercontent.com/19994035/185354308-df6acd54-233d-46e7-895b-65d2005abfd6.png)

![image](https://user-images.githubusercontent.com/19994035/185354241-a696595d-7308-44bd-814e-f2f347c1e364.png)

![image](https://user-images.githubusercontent.com/19994035/185353499-03987a61-cc4a-4195-a5be-1ad89c5a694f.png)

I encoutered difficulties to repete, but somehow during the first series of test I got this extra message, maybe there is a link between the two problems:
![image](https://user-images.githubusercontent.com/19994035/185350431-bce2e84f-5faf-46f9-80b5-d1e7beb8971a.png)

**Comment by declension** [comment]
Hmm that (currently) works for me, but I know that the code around connection handling can make the UI hang; think there's another similar ticket around

**Comment by declension** [comment]
Wait, sorry I assumed you meant the Internet Radio browser (that link is an internet radio stream).

However, if you _do_ enter that as a feed, I can reproduce this (I suspect it's trying to parse endless content so hangs)

**Comment by i88ux** [comment]
Ok I understand what causes the issue. I thought it was not possible to add an item into the Internet radio menu, that's why I thought I had to add a audio feed instead. Is there a reason why the New Station button is not at the same place as the Add Feed button?

**Comment by declension** [comment]
>  Is there a reason why the New Station button is not at the same place as the Add Feed button?

Actually, this has just been changed, see #4076. This will be in the next (major) release
