### ISSUE TITLE
Cover Grid throws `AttributeError` on change of cover art

### ISSUE THREAD

**Issue by declension** [quodlibet/quodlibet#4110]
Steps to reproduce
------------------
* Use new cover grid browser
* Play an album
* Activate the cover art downloader
* Choose a new cover for it with the cover
* Click Save (not double-click...) 

Expected Output
---------------
* Browser view updates

Actual Output
-------------
* View doesn't update
* Exception raised in dialog:
```
    Traceback (most recent call last):
      File "/home/nick/workspace/quodlibet/quodlibet/browsers/covergrid/main.py", line 315, in __cover_changed
        album = item.album
    AttributeError: 'TreeModelRow' object has no attribute 'album'
```

Test System
-----------

### Which version of Quod Libet?
git c0eb295eb62108360bf4bbc7746139bc946b58cc

**Comment by slosd** [comment]
Working on it https://github.com/slosd/quodlibet/commit/67b380ae57533e5220f49de7a3ffb269d0f9ed2a

**Comment by declension** [comment]
Great, it just needs `items[0]`. But a test is harder...
