### ISSUE TITLE
CoverGrid browser doesn't remove songs deleted from library

### ISSUE THREAD

**Issue by declension** [quodlibet/quodlibet#4112]
Steps to reproduce
------------------
* Switch to covergrid
* View an album
* Delete a track from that album elsewhere in QL

Expected Output
---------------
Tracks should disappear from browser views immediately

Actual Output
-------------
Duplicates stayed even after several browser rescans, and browser changes

Test System
-----------

### Which version of Quod Libet?
git c0eb295eb62108360bf4bbc7746139bc946b58cc

### Which operating system 
Manjaro

Workaround
----------------

Restart QL, fixes.

**Comment by slosd** [comment]
I can't reproduce with:

1. Switch to covergrid
2. Select an album in the grid
3. Open an additional browser
4. Find song from the album selected in step (2)
5. Right-click
6. Select "Remove from library"

Result:
Track disappears in both browsers.

**Comment by declension** [comment]
Thanks, I'll try to narrow down what the problem is then (I deleted externally I think, then rescanned)

**Comment by slosd** [comment]
Oh by "elsewhere" you mean from a file browser or via command line? I thought from within quodlibet.

**Comment by declension** [comment]
I've retried and now can't replicate either way too, so will close. Thanks for checking
