### ISSUE TITLE
Buttons for adding and updating stations do not work

### ISSUE THREAD

**Issue by Mellthas** [quodlibet/quodlibet#4120]
Steps to reproduce
------------------
1. Open *Browse – Internet Radio*
2. Click on *Add Station…* or *Update Stations*

Expected Output
---------------
Dialog for adding a station should come up or the list of stations should be updated.

Actual Output
-------------
Nothing happens.

Test System
-----------

Current master (815b7d2039bca5145f7734c29dc9908979cc789f) on Ubuntu 20.04.

**Comment by declension** [comment]
Thanks - reproduced here.
