### ISSUE TITLE
Issues with arrow-key navigation in new covergrid browser

### ISSUE THREAD

**Issue by Mellthas** [quodlibet/quodlibet#4121]
Steps to reproduce
------------------
1. Open *Browse – Cover Grid*
2. Move focus to the cover grid
3. Press and hold the up or down arrow key (also right in case of wide mode) 

Expected Output
---------------
I would expect the focus to eventually land and stay on the first resp. last row of the grid, similarly to how the title list works. This allows holding an arrow key to quickly navigate the grid without the need to be precise near the start or end.

Actual Output
-------------
Focus moves to an adjacent widget after having reached the start resp. end of the grid. This is especially jarring when moving up from the first row, as focus will move to the search box and then go on to cycle through existing saved searches and open the saved-searches window, often multiple instances on top of each other (can report a separate issue for that if needed).

Test System
-----------
Current master (815b7d2039bca5145f7734c29dc9908979cc789f) on Ubuntu 20.04.

**Comment by declension** [comment]
Replicated here - it moves to saved searches, and can pop up _many_ dialogs there which is not great.

**Comment by declension** [comment]
@slosd any ideas how we can fix?

**Comment by slosd** [comment]
@declension This PR changes the behavior to be more like the `IconView` implementation.
