### ISSUE TITLE
Playlists empty after conversion to XSPF

### ISSUE THREAD

**Issue by SpaceAmoeba** [quodlibet/quodlibet#4131]
On a new Linux Mint 21 system I copied over the .quodlibet folder from previous system to keep settings. Most things seem fine, but the playlists are empty after starting up quodlibet (a newer version).

On investigation, the playlists are emptied when quodlibet tries to convert them to XSPF. I've tried this in both 4.4.0 and 4.5.0.

I don't think this is the same problem as #3849 because the songs listed in the playlists are normal text.

This is a sample from the debug output:

> W: 0.631: FileBackedPlaylist.__init__: Playlist initialised without library
> W: 0.631: PlaylistLibrary._read_playlists: Converting 'Synthwave' to XSPF format (XSPFs should end in '.xspf', not '')
> D: 0.631: PlaylistLibrary.add('PlaylistLibrary for main'): Adding <XSPFBackedPlaylist at '/home/justin/.quodlibet/playlists/Synthwave.xspf'>
> D: 0.631: XSPFBackedPlaylist.__init__: Playlist 'Synthwave' not found, creating new.
> D: 0.631: XSPFBackedPlaylist.write: Writing '/home/justin/.quodlibet/playlists/Synthwave.xspf'
> D: 0.631: XSPFBackedPlaylist._emit_changed: Changed playlist <quodlibet.util.collection.XSPFBackedPlaylist object at 0x7fe0f26f1900> (extend)
> D: 0.631: XSPFBackedPlaylist.write: Writing '/home/justin/.quodlibet/playlists/Synthwave.xspf'
> D: 0.631: FileBackedPlaylist._delete_file: Deleting playlist file: '/home/justin/.quodlibet/playlists/Synthwave'
> W: 0.631: FileBackedPlaylist._delete_file: Couldn't delete '/home/justin/.quodlibet/playlists/Synthwave' ([Errno 2] No such file or directory: '/home/justin/.quodlibet/playlists/Synthwave')

**Comment by declension** [comment]
Thanks. 
When you say the playlists are empty, do you mean in the QL browser you see no songs for all of them? Are all the playlists still there on the left?

What is in the actual files? e.g. `'/home/justin/.quodlibet/playlists/Synthwave.xspf`?

**Comment by SpaceAmoeba** [comment]
The browser shows all of the playlists as empty and here is the content of Synthwave.xspf:

> <?xml version='1.0' encoding='utf-8'?>
> <playlist version="1"><title>Synthwave</title><date>2022-09-01T18:00:21.450814</date><trackList /></playlist>

It is similar for each of the playlist files.

**Comment by declension** [comment]
Thanks. Looks like the playlists are getting recreated with no content, somehow. 

Does this happen _every_ time you copy the old config over? (which presumably has playlists with many lines in each)

**Comment by SpaceAmoeba** [comment]
Yes, it happens every time to all playlists.

**Comment by declension** [comment]
@SpaceAmoeba I can reproduce this if the location (e.g. directory) referred to is gone. If I then update the (backup) legacy playlists to, it works fine. 

Is it possible your library paths (or symlinks) have changed in the switch to a new OS?

**Comment by SpaceAmoeba** [comment]
I'm an idiot. You are absolutely right - the references have changed. I'm sorry to have wasted your time. Thank you!

**Comment by declension** [comment]
Great! It would be nice if QL had warned about this somehow, so I've added some autodetection and logging that might have made this much easier as a user,  and will push this soon.
