### ISSUE TITLE
ValueError can be raised if edit tags selection is empty 

### ISSUE THREAD

**Issue by declension** [quodlibet/quodlibet#4137]
https://sentry.io/organizations/quodlibet/issues/3576522541/?referrer=github_plugin

```
ValueError: min() arg is an empty sequence
  File "quodlibet/qltk/edittags.py", line 605, in __popup_menu
    can_change = min([model[path][0].canedit for path in rows])

ValueError: min() arg is an empty sequence
```

**Comment by afontenot** [comment]
How old is the reported version? This looks to me to have been fixed in https://github.com/quodlibet/quodlibet/commit/999982e5f0e9b9910f8a074fa164eed44aee4676

**Comment by declension** [comment]
Yep looks very old (4.2.1)

Closing as fixed, thanks
