### ISSUE TITLE
QL 4.4.0 segfaults on macOS 12.6

### ISSUE THREAD

**Issue by gingerkitty** [quodlibet/quodlibet#4144]
Steps to reproduce
------------------

I tried running from terminal

Expected Output
---------------

Program should open

Actual Output
-------------

Python Quits... offers to send feedback to Apple

Test System
-----------

### Which version of Quod Libet?

Quod Libet 4.4.0
### Which operating system 

Mac OS Monterey 12.6 on Macbook Pro

### If it's audio-related, what back-end?

Package related

Additional Information
----------------------

Have not gotten past this screen when trying to Open 
![image](https://user-images.githubusercontent.com/2711654/192200321-796b5563-8f0f-4e9a-b34e-a8bf9bb07950.png)

[python-quit-unexpectedly.txt](https://github.com/quodlibet/quodlibet/files/9643224/python-quit-unexpectedly.txt)

**Comment by declension** [comment]
No longer supported - see release for 4.6.0 though
