### ISSUE TITLE
[Proposal] Tag pattern syntax to return the first non-empty tag in a list

### ISSUE THREAD

**Issue by afontenot** [quodlibet/quodlibet#4152]
The proposed change
-------------------
It's common to have complex, chained if-else tag patterns like this:

    <composer|<composer>|<albumartist|<albumartist>|<artist>>>

If you use the above in a string field that accepts tag patterns, the result will be the `composer` of a given song (if it exists) falling back to `albumartist` of a given song (if it exists), falling back to `artist`. What if, instead, you could just do this:

    <<composer||<albumartist>||<artist>>

This proposal introduces a new bit of syntax, an "or" token `||` that tells QuodLibet to use the first provided tag pattern that is non-empty (an empty string or missing tag).

I have already written the code to do this https://github.com/quodlibet/quodlibet/pull/4145. Please check it out and give feedback if you're familiar with the QL codebase.

Yes, you can chain tags as expected:

    <<tag1>||<tag2>||<tag3>>

You can use arbitrary sub-patterns within the "or" pattern

    <<genre=classical|<composer>>||<albumartist>||<artist>||Artist Missing>

If anyone has a good idea for a name for this feature to use in documentation, I'm happy to hear it. Internally I'm calling it the [disjunction](https://en.wikipedia.org/wiki/Logical_disjunction) operator, but most people won't be familiar with that concept. "Or" is a bit vague unless you're a programmer, in which case you might be familiar with Python's `x or y or z`, which behaves the same way.

Benefits of this change
-----------------------
This change would massively simplify complex tag chains, making them considerably easier to create, read, and maintain.

Any issues this might cause
---------------------------
This would not affect existing syntax. The "if-else" pattern continues to work as before.

Because the `|` character has to be escaped in tag patterns anyway, I don't believe it is possible for this change to break any tag pattern that is currently valid. The one possibility I can see is that a user might inadvertently use `||` when they want to use `|`, but we already have tons of cases where syntax errors break things with no help or error reporting to the user. (*whispers: I'm working on something that will fix this.* :rocket:)

**Comment by bassstorm** [comment]
Looks nice, great work!

**Comment by slosd** [comment]
This kind of pattern `<x|<x>|<y|<y>|z>>` shows up in a few places in my config, so this feature would be very useful to keep these definitions more readable.

**Comment by afontenot** [comment]
I'll also point out that it enables some stuff that currently can't be done without repeating yourself. For example, 

    <genre=classical|<composer|<composer>|<albumartist|<albumartist>|<artist>>>|<albumartist|<albumartist>|<artist>>>

Is a tag pattern with a "fork" right at the beginning. On one side is the pathway for the classical genre, on the other the pathway for all other genres. The two sides "reunite" after considering the <composer> tag, but there's no way to represent this. The new syntax means this is just

    <<genre=classical|<composer>>||<albumartist>||<artist>>

**Comment by afontenot** [comment]
I'd like to work on this and try to get it merged sometime this week. How do we feel about the "disjunction" name? The existing tag pattern operator is the "conditional", which is also sort of abstract terminology for what it does. As with the conditional, which is described in the docs as "a simple if-then-else concept", we could use simple lingo (like "choose the first non-empty tag pattern") that helps clarify the meaning for ordinary users.

Some alternatives:

 * The disjunction tag pattern (discussed above, the original proposal)
 * The coalescing tag pattern (after `COALESCE` in SQL)
 * Rename the existing "conditional" pattern to "ternary conditional" since that better describes how the `|` operator behaves, and call the new tag pattern simply "conditional". This option makes some intuitive sense because the new `||` syntax mimics the behavior of the conditional operator (`or`) in Python.

Honestly I don't care what we call it, so if @declension would like to just pick a name that works for me. I just need *a* choice here so I can finish the pull request by adding documentation.
