### ISSUE TITLE
Can't compare a numeric tag to any number greater than 4 digits in a search

### ISSUE THREAD

**Issue by Miss-Inputs** [quodlibet/quodlibet#4161]
Steps to reproduce
------------------
- Go to the search bar in any browser that has one
- Enter a numeric search where the RHS of a comparison operator has 5 digits or more, e.g. `#(samplerate>44100)`

Expected Output
---------------
This should work like any other numeric search, for the example given of `#(samplerate>44100)`, this should show any song with a sample rate above 44100Hz.

Actual Output
-------------
The search bar is highlighted red, indicating it thinks this query is invalid for one reason or another.

Test System
-----------

### Which version of Quod Libet?
4.5.0

### Which operating system 
Xubuntu 22.04

### If it's audio-related, what back-end?
It's not audio related 

Additional Information
----------------------
This would only affect samplerate realistically, since units for size/time fields exist and no music has been released in the year 10000 yet.

Had to poke around in private modules to find out what the parse error actually is (if there is something on quodlibet.query.Query that does it, I did not notice and I am a silly goose):
```
>>> quodlibet.query._parser.QueryParser('#(meow=12345)').StartQuery()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/quodlibet/query/_parser.py", line 96, in StartQuery
    s = self.Query(outer=True)
  File "/usr/lib/python3/dist-packages/quodlibet/query/_parser.py", line 114, in Query
    return self.Intersection(self.Numcmp)
  File "/usr/lib/python3/dist-packages/quodlibet/query/_parser.py", line 138, in Intersection
    self.expect(')')
  File "/usr/lib/python3/dist-packages/quodlibet/query/_parser.py", line 73, in expect
    raise ParseError("'{0}' expected at index {1}, but not found"
quodlibet.query._match.ParseError: ')' expected at index 11, but not found
```

**Comment by afontenot** [comment]
Nice find, thanks for the report.
