### ISSUE TITLE
Error on right clicking podcast entry

### ISSUE THREAD

**Issue by Mellthas** [quodlibet/quodlibet#4178]
Steps to reproduce
------------------
1. Right click on a feed/podcast entry in the podcast browser.

Expected Output
---------------
Context menu opens.

Actual Output
-------------
```
E: [0319.925] errorreport.main.errorhook: podcasts.py:478:__popup_menu: TypeError: MenuItem() got an unexpected keyword argument 'tooltip'
```

Test System
-----------

Current master on Ubuntu 20.04.

**Comment by declension** [comment]
Sorry, missed this report. Thanks
