### ISSUE TITLE
Seeking in flac files causes long pauses 

### ISSUE THREAD

**Issue by declension** [quodlibet/quodlibet#4197]
Steps to reproduce
------------------
* Play a FLAC file
* Jump forwards a bit

Expected Output
---------------
* Near immediate playing continues, like with MP3s 

Actual Output
-------------
* 1 - 2s of delay before repeating
* Then a quick hiccup _backwards_ (!) then play continues 

Test System
-----------

### Which version of Quod Libet?
git fb65cb3d7126c8dd9023d6acf3641c99f41bf87c

### Which operating system 
Manjaro Linux latest

### If it's audio-related, what back-end?
Gstreamer via `gstreamer-1.20.3-2`
Pipewire under that

Additional Information
----------------------

* Maybe happened on move to, or upgrade of Pipewire
* Note the exact thing happens on, say, Lollypop, Rhythmbox etc

**Comment by afontenot** [comment]
This should be fixed in the latest FLAC. It affects FLAC versions 1.4.0 and 1.4.1.

Here's a link to my report at FLAC: https://github.com/xiph/flac/issues/471

**Comment by Viktini** [comment]
Yeah, this was fixed upstream. Arch has updated and FLAC seeking works properly on all gstreamer-based players now.

**Comment by declension** [comment]
Seems resolved now, thanks all
