### ISSUE TITLE
Update flatpak Gnome Platform version to avoid deprecation warnings

### ISSUE THREAD

**Issue by raydeepx** [quodlibet/quodlibet#4203]
just for information: This is warning from flatpak version

Info: org.gnome.Platform//41 is end-of-life, with reason:
   The GNOME 41 runtime is no longer supported as of September 17, 2022. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
   fr.handbrake.ghb, io.github.quodlibet.QuodLibet
Nothing to do.

**Comment by declension** [comment]
[Now on 44](https://github.com/flathub/io.github.quodlibet.QuodLibet/blob/908b08ac7577092d2c7c81a7c28b84ae20f42979/io.github.quodlibet.QuodLibet.yaml#L3)
