### ISSUE TITLE
Renamed home folder--library has duplicated every song entry

### ISSUE THREAD

**Issue by Jimi-James** [quodlibet/quodlibet#4212]
Steps to reproduce
------------------
1. Renamed my home folder and user and set the home directory to the new folder name
2. Created a symlink to the new home folder named as the old home folder name, to make things easier during the transition
3. Launched Quod Libet normally, forgetting to change the library location or anything
4. Every song in the library is there, but showing up twice back to back. Both entries have all the same tags and file location
5. Quit QL, changed the library path in the config file (since there was no way to do it in-UI) and relaunch
6. Songs still duplicated
7. Rebuild library
8. Still duplicated

Expected Output
---------------
You would think it would just notice that these songs only show up once each.

Actual Output
-------------
2 entries with identical tags and file path for each and every song in the entire library.

Test System
-----------

### Which version of Quod Libet?
4.5.0

### Which operating system 
Arch Linux, linux-lts 5.15.78-1

**Comment by declension** [comment]
Thanks for filing. Presumably the `~dirname` are different across each pair of duplicated songs?

(if so workaround, probably: sort by dirname and select all the wrong ones, right click, remove the symlink ones)

**Comment by Jimi-James** [comment]
You would think! But no, the `~dirname` was the same for both copies of each track--both using the new home dir.

However, this issue has actually now disappeared on my most recent reboot. I had rebooted before, and I had restarted QL before, but suddenly *this* one I guess fixed things? No more duplicates.

So I guess this is a can't reproduce situation.
