### ISSUE TITLE
Album List sidebar header lost a newline

### ISSUE THREAD

**Issue by elcste** [quodlibet/quodlibet#4232]
A newline was lost with [recent changes to quodlibet/browsers/albums/main.py](https://github.com/quodlibet/quodlibet/commit/2f516a2cf88b67397da8fbed38cabbc35e60548a#diff-f1827e01aed34ab8614828e1c4fa86cd252731388f5b39baccff0ffa85894533)

In the current git version, without the newline, the sidebar displays wrongly as

All Albums1 album

In version 4.5, with the newline, it correctly uses two lines:

All Albums
1 album

**Comment by declension** [comment]
Sorry - my fault. Closed by #4233
