### ISSUE TITLE
Playlist export plugin: M3U playlists with relative paths starting with "#" are invalid

### ISSUE THREAD

**Issue by fkrull** [quodlibet/quodlibet#4235]
Lines starting with "#" are treated specially by most (all?) M3U parsers as control lines or comments. This means that if I export a playlist with relative paths with a directory or file name starting with "#" such that that path component is at the start of the relative path, most M3U implementations will ignore those files because they think those lines are control data or comments.

For example, consider this hastily rendered directory structure:

```
+ parent_dir
|   + #mysubdir
|   |   somefile.mp3
|   playlist.m3u 
```

So if I export a playlist containing "somefile.mp3" using the playlist export plugin and save it as an M3U file at "playlist.m3u", the playlist will contain "#mysubdir/somefile.mp3" which most M3U parsers (Gnome Videos and the LineageOS music player at least) will ignore.

**Comment by declension** [comment]
Wow this feels edge-casey but I guess you must have seen it in real life then.. 

Does the m3u standard support escaping hashes then? Can't see mention [on wikipedia](https://en.wikipedia.org/wiki/M3U).

One hacky workaround might be to manually check for this condition and then prefix `./` (or equivalent for Windows)

**Comment by fkrull** [comment]
> Wow this feels edge-casey but I guess you must have seen it in real life then..

It really is and I really have. :grinning:

I don't expect there to be a way to escape characters, what with Wikipedia mentioning "no formal specification". I tried prefixing the lines with a space, but the GNOME video player didn't like that one either.
