### ISSUE TITLE
PyGObject is missing Cairo support

### ISSUE THREAD

**Issue by stervel** [quodlibet/quodlibet#4266]
Steps to reproduce
------------------
Starting quodlibet normally, suddenly won't start after a full system upgrade.

Expected Output
---------------
It runs normally.

Actual Output
-------------
Running `quodlibet --debug` results

```
D: 0.068: util.i18n.init: LANGUAGE: None
D: 0.068: util.i18n.init: LANG: 'EN_US.UTF-8'
D: 0.068: util.i18n.register_translation: No translation found for domain 'quodlibet' in None
D: 0.087: util.importhelper.get_importables: Ignoring '/usr/lib/python3.10/site-packages/quodlibet/formats/__pycache__'
D: 0.125: formats._misc.init: MimeType=application/x-flac;audio/aac;audio/aiff;audio/dsf;audio/midi;audio/mp3;audio/mp4;audio/mpeg;audio/mpeg4;audio/mpg;audio/ogg;audio/vorbis;audio/wav;audio/wave;audio/x-aac;audio/x-aiff;audio/x-flac;audio/x-m4a;audio/x-midi;audio/x-mp3;audio/x-mpc;audio/x-mpeg;audio/x-ms-wma;audio/x-ms-wmv;audio/x-musepack;audio/x-oggflac;audio/x-speex;audio/x-tta;audio/x-wav;audio/x-wavpack;audio/x-wma;video/ogg;video/x-ms-asf;video/x-theora;video/x-wmv;
D: 0.125: formats._misc.init: Supported formats: aac, aiff, dsf, midi, mod, monkeysaudio, mp3, mp4, mpc, spc, trueaudio, vgm, wav, wavpack, wma, xiph
E: 0.256: _init._init_gtk: PyGObject is missing cairo support
```

Test System
-----------

### Which version of Quod Libet?
4.5.0

### Which operating system 
Arch

Additional Information
----------------------
Quodlibet ran normally for a long time up to that point and suddenly doesn't start.

I do full system upgrades pretty regularly and it's been a couple of weeks and several -Syu's done and the problem still presists. The only relevant issue I found is in [this old thread](https://bugs.mageia.org/show_bug.cgi?id=12656) stating it's fixed and I think it's not helpful much for my case.

The error code also happens in several music players and maybe other software using similar component (I only test music players that happen to catch my eyes while looking for alternatives). Sorry I didn't list them but will do some testing if needed.

**Comment by declension** [comment]
Yes, confirmed on Manjaro too, currently on `python-gobject-3.42.2-1`.

The only thing I see in [its release notes](https://pygobject.readthedocs.io/en/latest/changelog.html) is https://gitlab.gnome.org/GNOME/pygobject/-/merge_requests/205/diffs, but doesn't seem that related.

Maybe @lazka knows?

**Comment by lazka** [comment]
I can't reproduce in docker at least

**Comment by stervel** [comment]
It still doesn't work.

I'm not that computer literate, so I can't really point out which is the source of the problem, but my guess it's not due to the changes in `python-gobject`, since it hasn't been updated since last year, as the arch repo says.

**Comment by lazka** [comment]
Hm, weird. The minimal reproducer would be `python -c "import gi; gi.require_foreign('cairo')"`. Not sure if that gives a better error message.

**Comment by stervel** [comment]
What does they do? It results

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.local/lib/python3.10/site-packages/cairo/__init__.py", line 1, in <module>
    from ._cairo import *  # noqa: F401,F403
ImportError: /home/user/.local/lib/python3.10/site-packages/cairo/_cairo.cpython-310-x86_64-linux-gnu.so: undefined symbol: cairo_tee_surface_index
```

**Comment by lazka** [comment]
This means you have executed `pip install --user pycairo` at one point (or indirectly via some other package), overriding your Arch provided pycairo. `pip uninstall pycairo` should fix it.

Installing Python packages into your system Python installation will lead to breakage down the line and should be avoided.

**Comment by stervel** [comment]
All makes sense. That way, uninstalling pycairo made everything work as intended. Thank you very much!

**Comment by declension** [comment]
(I nuked the venv and reinstalled with poetry, now works again :shrug: )
