### ISSUE TITLE
manually ordering songs in playlists ?

### ISSUE THREAD

**Issue by pascalspits** [quodlibet/quodlibet#4267]
Hi,

I'm sure I'm missing something, but I can't find for the life of me how to manually order songs in a playlist ...
I drag and drop them, but the order always keeps jumping back to alphabetically on title or on date ... huh ?
Isn't a playlist just exactly meant to play the songs in a pre-set order ?
I'm sure I'm missing some small setting or thing, because I just can't believe that this would be impossible ...

Greetings
Pascal
Belgium

**Comment by Meriipu** [comment]
which version?

stuff I can think of is
* the option `sort songs when tags are modified`
* https://github.com/quodlibet/quodlibet/issues/3957
* https://github.com/quodlibet/quodlibet/issues/4072

**Comment by pascalspits** [comment]
version 4.5.0 on Linux Mint 21.1 Cinnamon

**Comment by FerdiScholten** [comment]
4.5.0 has major issues with playlists, they have been fixed, but the new release is not out yet. Several people have been asking for release for quite a while now or even a bugfix release.
Either use 4.4 for playlists, or clone current git and run it from there.

**Comment by declension** [comment]
Please try 4.6.0. Closing this as fixed (or duplicated) for now
