### ISSUE TITLE
Move to libsoup3

### ISSUE THREAD

**Issue by declension** [quodlibet/quodlibet#4291]
The proposed change
-------------------
We use & package / require [libsoup](https://gitlab.gnome.org/GNOME/libsoup/) 3.x, not the 2.x we currently explicitly require

Benefits of this change
-----------------------
* v2 has been deprecated
* There are increasing difficulties, it seems, due to Gnome 42 (?) also moving
* It might actually be better, or whatever

Any issues this might cause
---------------------------
 * Lots, but see [libsoup 2 ->3 migration guide](https://libsoup.org/libsoup-3.0/migrating-from-libsoup-2.html)

**Comment by lazka** [comment]
I'm not sure if you want to make that a prerequisite for a new release. That seems too risky..

**Comment by declension** [comment]
> I'm not sure if you want to make that a prerequisite for a new release. That seems too risky..

Yes I was thinking the same thing yesterday. A lot of risk

The main reason I was looking, however, was #4251 #4114 which are pretty bad bugs currently - though I have no proof this is related. I  (actually maybe a Kubuntu CI job would makes sense :thinking: )

**Comment by lazka** [comment]
I see, I wasn't aware of that. Ideally our CI wouldn't do network stuff (but I'm sure it does to some extend), so not sure that would catch anything.

**Comment by declension** [comment]
> I see, I wasn't aware of that. Ideally our CI wouldn't do network stuff (but I'm sure it does to some extend), so not sure that would catch anything.

Agree. We could set up a local http stub for testing cover art / SC I guess, but quite a lot of hassle
