### ISSUE TITLE
Gnome search integration appears broken when running from Git

### ISSUE THREAD

**Issue by declension** [quodlibet/quodlibet#4309]
Steps to reproduce
------------------
* Install the metadata (ini) file as per `searchprovider.py` instructions
* Run QL
* Search in Gnome search for a song by title, say

Expected Output
---------------
Some results

Actual Output
-------------
No results ever. Other providers do match though

Test System
-----------

### Which version of Quod Libet?
git e964c600ea8cc3a25f3501fbc9bb7a53d0d7a330

### Which operating system 
Gnome 43.5 / Manjaro

Additional Information
----------------------

**Comment by lazka** [comment]
It works here with Ubuntu / GNOME 43
