### ISSUE TITLE
"Lyrical", "Style", & "Type" tags not showing data

### ISSUE THREAD

**Issue by Xeno-Idaltu** [quodlibet/quodlibet#4321]
I used PuddleTag to tag mp3 files containing their data regarding lyrical, style, and type.
(ex,) Lyrical=Dystopian, Style=Futuristic, Type=Electronic

Expected Output
---------------
When I tried QuodLibet these three categories appear blank, even if I manually customize headers. It seems to be a problem with QuodLibet as MP3Tag via Wine shows up data for these three tags.
When I manually create these three options, they show up as QuodLibet::lyrical, QuodLibet::style, and QuodLibet::type, this is good but Mp3Tag won't recognize these tags. There are functions PuddleTag lacks like "removing files without deleting" and "moving highlighted files", hence why I use MP3Tag

It would be a lot better if QuodLibet enabled these three tags, as they seem to be universal.

### Which version of Quod Libet?
4.4.0

### Which operating system 
Kubuntu 22.04

**Comment by declension** [comment]
Custom tags get stored in `TXXX` for ID3, and Quod Libet prefixes these with `Quodlibet::` to avoid conflicts with other players (much discussed, not always loved - see #48 especially).

Note that [Puddletag doesn't support any of these tags either](https://docs.puddletag.net/source/id3.html), it's just that it doesn't prefix them:

> Any unknown field is assumed to be a user-defined field. Therefore writing to the field ‘mytag’ will write to the ID3 tag frame TXXX:mytag.

Merging this into #48
