### ISSUE TITLE
Please port exfalso to libsoup 3

### ISSUE THREAD

**Issue by nekohayo** [quodlibet/quodlibet#4371]
Hi! Please note that [Fedora 40 will drop support for webkit2gtk-4.0](https://fedoraproject.org/wiki/Changes/Remove_webkit2gtk-4.0_API_Version), so your app will need to be updated to libsoup-3.0 soon, in order to use webkit2gtk-4.1 instead of webkit2gtk-4.0, for it to remain packageable in Fedora (and possibly other distros that might start dropping libsoup2).

I am not a Fedora dev (simply a user) but I do use exfalso every now and then, so I'd love to see it remain in that distro among other ones :)

My wild guess here is that exfalso probably uses libsoup in some of its plugins, so that's probably the part that needs updating.

**Comment by afontenot** [comment]
This is already fixed, and in fact we now mandate libsoup>=3, as you can see from the packaging guide: https://github.com/quodlibet/quodlibet/blob/main/docs/packaging.rst

**Comment by declension** [comment]
Yes see #4291. Are you on the latest version?
