### ISSUE TITLE
QL scripts used for MacOS builds depend on obsolete tools

### ISSUE THREAD

**Issue by jdykstra** [quodlibet/quodlibet#4389]
jwd@oak osx_bundle $ ./bootstrap.sh
info: syncing channel updates for '1.69.0-x86_64-apple-darwin'
...
Now type `make' to compile jhbuild
./scripts/debian-python2-postinstall-hook.sh: Unable to find 'python' in the PATH
make: *** [install] Error 2

Test System
-----------
QL main at 62ea93e21eb.  Mac OS 14.0 (Sonoma).

Additional Information
----------------------
bootstrap.sh specifies JHBuild 624bcf6, which requires python 2.7.  Python 2.x builds are no longer available from XCode or Homebrew.

**Comment by jdykstra** [comment]
quodlibet/dev-utils/osx_bundle/misc/gtk-osx-jhbuildrc requires Python 2.

**Comment by jdykstra** [comment]
https://github.com/GNOME/jhbuild/ 3.38.0 and https://gitlab.gnome.org/GNOME/gtk-osx master:cea03513 look promising, but I've not yet successfully built QL for MacOS.

**Comment by Daoro** [comment]
Just a quick thank you for your work!
Sadly I don't know any programming, I'd love to help otherwise, so I can run QL on my mac again.

**Comment by jdykstra** [comment]
I  tried a different approach of using python 2.7 with the bundle build scripts currently in QL, but JHBuild depends on XCode internals that have changed over the years.   I'm going back to the use-current-tools strategy.

Thanks  for the appreciation.  This is ugly work.

**Comment by jdykstra** [comment]
The existing scripts use distutils, which is removed from Python in 12.0.
