### ISSUE TITLE
Imported playlist name should be the same as the filename

### ISSUE THREAD

**Issue by Praful** [quodlibet/quodlibet#4392]
The proposed change
-------------------
When playlists are imported, the name of the playlist is the first track's title followed by "and n more", where n is the number of other tracks.

I'm sure there's a good reason for this but I've not seen it in any other music player: rhythmbox, Strawberry, and Tauon Music Box all use the playlist's filename. I find the current default name completely unhelpful! 

Usually, the name of the imported playlist is the name of the file, which an exporting app would set from the name of the playlist.

Benefits of this change
-----------------------
I just exported 25 playlists from Winamp on Windows to Quod Libet on Linux. I can't tell which is which! Using the filename will help me.

Any issues this might cause
---------------------------
I can't think of any potential issues.

**Comment by declension** [comment]
Seems very reasonable
