### ISSUE TITLE
4.6.0 for the Debian and openSUSE repos

### ISSUE THREAD

**Issue by ocobblepot** [quodlibet/quodlibet#4396]
Thank you for updating the Ubuntu PPA. Could the quodlibet packages in the Debian and openSUSE repos listed at https://quodlibet.readthedocs.io/en/latest/downloads.html be updated too please? In the case of openSUSE, quodlibet is not available in the standard repositories.

**Comment by lazka** [comment]
I'll try to find some time. Have you considered using flatpak?

**Comment by ocobblepot** [comment]
Thank you. I connect quodlibet directly to my soundcard via ALSA, using the "Output pipeline" configuration option. I am yet to find a way to get this to work for the flatpak of quodlibet.

**Comment by lazka** [comment]
The sandbox works :P

ok, I'll have a look.

**Comment by ocobblepot** [comment]
> The sandbox works :P

Only too well :(
Thank you.

**Comment by lazka** [comment]
What version of openSUSE is everyone using these days, Tumbleweed?

**Comment by ocobblepot** [comment]
> What version of openSUSE is everyone using these days, just Tumbleweed?

That's what I'm using on my rolling machine. Leap 15.5 is the current version of Leap (15.5 is available as "Alpha").

**Comment by lazka** [comment]
> That's what I'm using on my rolling machine. Leap 15.5 is the current version of Leap (15.5 is available as "Alpha").

ok, I update Tumbleweed, but Leap 15.5 seems to have Python 3.6, not sure how that is supposed to run anything new.

**Comment by lazka** [comment]
> If you could update the Debian repo as well, that would be appreciated.

done

**Comment by ocobblepot** [comment]
> done

Thank you.
