### ISSUE TITLE
[Feature Request] Include "Producer" tag in "~people" internal tag

### ISSUE THREAD

**Issue by DestroyerAce** [quodlibet/quodlibet#4397]
### The proposed change
-------------------
Include "Producer" tag in "~people" internal tag or make "Producer" a standalone tag

### Benefits of this change
-----------------------
There's currently no way to search tracks and albums by Producers which makes searching tracks by Producers impossible in app. Its kinda weird how its not already implemented as the "Information" tab can already show the producer's name in "Produced by <name>" under the album name.
![image](https://github.com/quodlibet/quodlibet/assets/86879466/a20c8709-f835-4594-aa16-f1f91d5b0c75)

### Any issues this might cause
---------------------------
Don't think this will create any huge impact on performance

**Comment by declension** [comment]
FYI you can search by any tag really, and `producer` is no different there.
Some tags are "recognised" (and translated to the user's language generally) by QL but this is j

Inclusion in `~people` is, however, hard-coded  (though see #684), so I guess this ticket is for fixing that
