### ISSUE TITLE
Move to ruff for formatting etc

### ISSUE THREAD

**Issue by declension** [quodlibet/quodlibet#4399]
The proposed change
-------------------
Use [ruff](https://docs.astral.sh/ruff/) instead of flake8

Benefits of this change
-----------------------
* It's _really_ fast
* Covers almost 100% of flake8 cases
* Also does [other useful inspections](https://docs.astral.sh/ruff/rules/)
* But best, [it can auto-fix many problems](https://docs.astral.sh/ruff/settings/#fix)
* And auto-upgrade from old Python syntax... 

Any issues this might cause
---------------------------
Might be hard to wrap in test suites like we do with flake8

**Comment by lazka** [comment]
for future reference, I don't mind moving linting tools out of the test suite
