### ISSUE TITLE
Ex Falso: Inputting tags is painful

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#44]
Original [issue 44](https://code.google.com/p/quodlibet/issues/detail?id=44) created by hhaamu on 2008-11-03T18:46:17.000Z:
1. Assume a twenty-track tagless album.
2. Try to input TITLE tags for each of the files.
3. Get wrist injuries.

No, really. There should be a way to add tags sequentially without _too_
much effort. Personally I'd like a simple big text area where I can just
type one tag per line, ie.

Looking for Someone
White Mountain
Visions of Angels
Stagnation
Dusk
The Knife

=&gt; Select &quot;Add as: TITLE&quot;
which would then apply the tags to the files.

The current &quot;most efficient&quot; way I've found is this:
1. Select first file in file selector
2. alt-A (Add tag)
3. type &quot;TITLE&quot; &lt;return&gt;
4. type title of a track
5. down arrow (next file)
6. goto 2

(yes, yes, I know about cddb and musicbrainz but they don't always have my
albums)

**Comment by declension** [comment]
No updates for >7 years.

Also,  #4173  was merged which hopefully solves a lot of the above, but re-open if you feel strongly.
