### ISSUE TITLE
Paned browser UI right-clips large totals

### ISSUE THREAD

**Issue by Npa972** [quodlibet/quodlibet#4415]
Steps to reproduce
------------------
Paned browser selected
In first panel, jazz genre has more than 10000 titles

Expected Output
---------------
Be able to read the number 10009

Actual Output
-------------
I see only 1000 (and not 10009)

![Capture d’écran_2023-11-03_19-26-58](https://github.com/quodlibet/quodlibet/assets/49346431/d673fca1-0b05-47d8-aa44-f1ebae59e8d8)

Test System
-----------
Archlinux 
Quodlibet-git (4.7 up to date)

Additional Information
----------------------
Sometimes there is the same problem in artist panel.
I would prefer the numbers to be close to the text (like in Rhythmbox ; but i prefer QL for many reasons)

![Capture d’écran_2023-11-03_19-51-19](https://github.com/quodlibet/quodlibet/assets/49346431/e397ab59-13a6-414a-9a11-d7cba808acbd)

**Comment by declension** [comment]
I was _sure_ there was a ticket about this already, but I can't find it..
