### ISSUE TITLE
Produce RTD docs for recent release versions

### ISSUE THREAD

**Issue by declension** [quodlibet/quodlibet#4419]
The proposed change
-------------------
RTD has `latest` as the default version, but also has named release versions (say, `4.4.0` - `4.6.0`) too. 

See #4417 for example why

**Comment by declension** [comment]
Done for 4.6 and 4.5 (and `latest`). 4.4 too old on several fronts, giving up for now

**Comment by afontenot** [comment]
Does it make sense to have `latest` as the default version? Seems like most users seeking help will want the docs for the most recent release.

**Comment by declension** [comment]
> Does it make sense to have latest as the default version?

Agree - I've updated the prefs
