### ISSUE TITLE
No text in paned view

### ISSUE THREAD

**Issue by Npa972** [quodlibet/quodlibet#4422]
Steps to reproduce
------------------
Open last git build

Expected Output
---------------
QL runs normally

Actual Output
-------------
There isn't text into the panel and a error message
![Capture d’écran_2023-11-06_07-54-02](https://github.com/quodlibet/quodlibet/assets/49346431/8f53ce9b-23b9-4633-8aa2-f65eb2484e01)
Error message :
TypeError: Must be string, not tuple
------
Traceback (most recent call last):

  File "/usr/lib/python3.11/site-packages/quodlibet/qltk/views.py", line 271, in __motion
    set_text(clabel)

  File "/usr/lib/python3.11/site-packages/quodlibet/qltk/views.py", line 257, in set_text
    return l.set_markup(markup)
           ^^^^^^^^^^^^^^^^^^^^

TypeError: Must be string, not tuple
----------------

Test System
-----------

Quodlibet git -r11583.6c6a1837f
Archlinux

Additional Information
----------------------
But the alignment of the song number ins ok into the panel

**Comment by declension** [comment]
Sentry issue: [QUODLIBET-13G](https://quodlibet.sentry.io/issues/4604222534/?referrer=github_plugin)
