### ISSUE TITLE
Replay gain analysis do not work in quodlibet-devel

### ISSUE THREAD

**Issue by Npa972** [quodlibet/quodlibet#4427]
Steps to reproduce
------------------
Analyse an apply RG album

Expected Output
---------------
Working

Actual Output
-------------
AttributeError: 'RGSong' object has no attribute 'Error'
------
Traceback (most recent call last):

  File "/usr/lib/python3.11/site-packages/quodlibet/ext/songsmenu/replaygain.py", line 376, in icon_cdf
    if item.error:
       ^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/quodlibet/ext/songsmenu/replaygain.py", line 92, in error
    if song.Error:
       ^^^^^^^^^^

AttributeError: 'RGSong' object has no attribute 'Error'

Test System
-----------
Quodlibet-git archlinux aur
### Which operating system 
Archlinux

### If it's audio-related, what back-end?

Additional Information
{'event_id': '02f62533bde94f2696d37b1419c180fb',
'exception': {'values': [{'module': 'builtins',
      'stacktrace': {'frames': [{'abs_path': '/usr/lib/python3.11/site-packages/quodlibet/ext/songsmenu/replaygain.py',
             'context_line': '            '
                 'if '
                 'item.error:',
             'filename': 'quodlibet/ext/songsmenu/replaygain.py',
             'function': 'icon_cdf',
             'lineno': 376,
             'module': 'quodlibet.fake.plugins.replaygain',
             'post_context': ['                '
                 'cell.set_property("icon-name", '
                 'Icons.DIALOG_ERROR)',
                 '            '
                 'else:',
                 '                '
                 'cell.set_property("icon-name", '
                 'Icons.NONE)',
                 '',
                 '        '
                 'column '
                 '= '
                 'Gtk.TreeViewColumn()'],
             'pre_context': ['        '
                 'view '
                 '= '
                 'HintedTreeView()',
                 '        '
                 'swin.add(view)',
                 '',
                 '        '
                 'def '
                 'icon_cdf(column, '
                 'cell, '
                 'model, '
                 'iter_, '
                 '*args):',
                 '            '
                 'item '
                 '= '
                 'model[iter_][0]'],
             'vars': {'args': [None],
               'cell': '<Gtk.CellRendererPixbuf '
                 'object '
                 'at '
                 '0x7f64974d6580 '
                 '(GtkCellRendererPixbuf '
                 'at '
                 '0x5616be49d580)>',
               'column': '<Gtk.TreeViewColumn '
                  'object '
                  'at '
                  '0x7f64ae2d06c0 '
                  '(GtkTreeViewColumn '
                  'at '
                  '0x5616be1bac00)>',
               'item': '<quodlibet.fake.plugins.replaygain.RGAlbum '
                 'object '
                 'at '
                 '0x7f64930b84d0>',
               'iter_': '<Gtk.TreeIter '
                  'object '
                  'at '
                  '0x7f649034a150 '
                  '(GtkTreeIter '
                  'at '
                  '0x5616bdbe66d0)>',
               'model': '<Gtk.TreeStore '
                  'object '
                  'at '
                  '0x7f649bb268c0 '
                  '(GtkTreeStore '
                  'at '
                  '0x5616bdcea170)>'}},
             {'abs_path': '/usr/lib/python3.11/site-packages/quodlibet/ext/songsmenu/replaygain.py',
             'context_line': '            '
                 'if '
                 'song.Error:',
             'filename': 'quodlibet/ext/songsmenu/replaygain.py',
             'function': 'error',
             'lineno': 92,
             'module': 'quodlibet.fake.plugins.replaygain',
             'post_context': ['                '
                 'return '
                 'True',
                 '        '
                 'return '
                 'False',
                 '',
                 '    '
                 'def '
                 'write(self):',
                 '        '
                 '# '
                 "Don't "
                 'write '
                 'incomplete '
                 'data'],
             'pre_context': ['        '
                 'return '
                 'self.songs[0].song.comma("~artist~album")',
                 '',
                 '    '
                 '@property',
                 '    '
                 'def '
                 'error(self):',
                 '        '
                 'for '
                 'song '
                 'in '
                 'self.songs:'],
             'vars': {'self': '<quodlibet.fake.plugins.replaygain.RGAlbum '
                 'object '
                 'at '
                 '0x7f64930b84d0>',
               'song': '<quodlibet.fake.plugins.replaygain.RGSong '
                 'object '
                 'at '
                 '0x7f64975c38d0>'}}]},
      'type': 'AttributeError',
      'value': "'RGSong' "
         'object '
         'has '
         'no '
         'attribute '
         "'Error'"}]},
'extra': {'sys.argv': ("'/usr/bin/quodlibet'",
      "'--run'",
      "'--play-file'")},
'level': 40,
'message': "AttributeError: 'RGSong' "
   'object has no attribute '
   "'Error'",
'modules': {'python': '3.11.5'},
'platform': 'python',
'project': '142415',
'release': '4.7 (development)',
'repos': {},
'sdk': {'name': 'raven-python',
  'version': '6.5.0'},
'server_name': 'default',
'tags': {'build_info': 'NONE',
  'build_type': 'default',
  'gtk_backend': 'X11',
  'gtk_version': '3.24.38',
  'mutagen_version': '1.47.0',
  'platform': 'Linux-6.6.1-arch1-1-x86_64-with-glibc2.38',
  'pycairo_version': '1.25.1',
  'pygobject_version': '3.46.0',
  'python_version': '3.11.5'},
'time_spent': None,
'timestamp': datetime.datetime(2023, 11, 18, 19, 49, 32, 766273)}

**Comment by declension** [comment]
Fixed partially by #4425
