### ISSUE TITLE
Bookmarked folders stopped appearing in Ex Falso installed via Flathub

### ISSUE THREAD

**Issue by sojusnik** [quodlibet/quodlibet#4437]
Steps to reproduce
------------------
After installing Ex Falso via [Flathub](https://flathub.org/apps/io.github.quodlibet.ExFalso), I only see my root folder and home folder with external drives in the navigation pane to the left, but not my bookmarked folders from Gnome's Files (formerly Nautilus), although they were present when Ex Falso was installed via .deb from the official Ubuntu 23.04 repository.

Expected Output
---------------
Bookmarked folders from Gnome's Files should appear in the navigation pane, when installed through Flathub.

Actual Output
-------------
see above

Test System
-----------

### Which version of ~~Quod Libet~~?
Ex Falso: 4.6.0

### Which operating system 
Ubuntu 23.04

**Comment by declension** [comment]
My guess is this is more about Gnome / Flathub changes than about QL, so not sure where to start herer

**Comment by sojusnik** [comment]
Maybe it has something to do with rights management and the flatpak version just can't read the file with the bookmarks?
