### ISSUE TITLE
Eliminate dependency on distutils package

### ISSUE THREAD

**Issue by jdykstra** [quodlibet/quodlibet#4442]
The scripts in `dev-utils/osx_bundle `used to build Quod Libet and Ex Falso for Macintosh use the `distutils` package, which was removed at Python 3.12.  

At present, we're successfully using Python 3.11.3 to build the apps, but if this continues for too long, we'll get back into the same tech debt hole that has hindered Macintosh support in the past.

**Comment by lazka** [comment]
While I agree, we also use setuptools which provides distutils, so using Python 3.12 shouldn't be a problem.

**Comment by jdykstra** [comment]
@lazka The QL development instructions don't say that setuptools needs to be installed.  Any reason I shouldn't add it?

**Comment by lazka** [comment]
It's part of the poetry dev deps
