### ISSUE TITLE
"Always allow sorting" preference isn't restored from config properly  

### ISSUE THREAD

**Issue by toto789** [quodlibet/quodlibet#4447]
### Steps to reproduce
* Launch Quod Libet
* Enable "always allow sorting" in preferences
* Restart QL
* Select Browse>Playlists
* Click on any column header

### Expected Output
Sorting

### Actual Output
Nothing

### Which version of Quod Libet?
4.6.0

### Which operating system 
Ubuntu 23.10

**Comment by declension** [comment]
OK, have reproduced and edited the steps to add the detail

**Comment by ShadiZade** [comment]
This issue is still present, release 4.6.0. It's quite annoying.

**Comment by toto789** [comment]
Fixed in 4.7 (development).

**Comment by ShadiZade** [comment]
@toto789 Very happy to hear that, kudos on the hard work. When can we expect 4.7 to be released?

**Comment by toto789** [comment]
@ShadiZade You can download it at https://github.com/quodlibet/quodlibet (unpack the archive and run quodlibet-main/quodlibet.py).
