### ISSUE TITLE
not scrobbling to libre.fm

### ISSUE THREAD

**Issue by ormulum** [quodlibet/quodlibet#4472]
Steps to reproduce
------------------

tried to scrobble to libre.fm

Expected Output
---------------

listen information should be sent to libre.fm

Actual Output
-------------

when 'verify account data' is clicked the error message 'Could not contact service 'http://turtle.libre.fm'.' appears

Test System
-----------

### Which version of Quod Libet?

4.6.0-0~ppa0~jam

### Which operating system 

ubuntu 22.04

**Comment by mgollo** [comment]
I am also seeing this on the unofficial 4.6.1 on MacOS

**Comment by declension** [comment]
Is this not because [it's being rewritten completely](https://github.com/foocorp/hacienda)?

**Comment by mgollo** [comment]
As far as I can tell this is still in the planning phase. The website hasn't changed (yet), but I don't know about the scrobble server. I will try to get some logs out of quodlibet.

**Comment by mgollo** [comment]
I have just tried running quodlibet with the --debug flag but all I got when clicking "verify account data" was this:
D: [0062.950] QLSubmitQueue.send_handshake: Sending handshake to service at http://turtle.libre.fm/.

I tried to manually scrobble a track using the pylast library and that worked, so the scrobble interface seems to be there.

**Comment by mgollo** [comment]
Just out of curiosity, I clicked the "verify account data"  button again today and suddenly it worked. So it was most likely a temporary issue with libre.fm
