### ISSUE TITLE
Allow to edit tags directly on the browser panel

### ISSUE THREAD

**Issue by petitminion** [quodlibet/quodlibet#4475]
The proposed change
-------------------
Allow to edit tags directly on the browser panel by double clicking on it.  For example on the screenshot, double clicking "reggaeton" would allow to edit the genre tag.

![image](https://github.com/quodlibet/quodlibet/assets/50751126/149870d0-5b52-4a25-ba18-00a7d1ed50a1)

Benefits of this change
-----------------------
Avoiding a lot of clicks to edit tags. 

Any issues this might cause
---------------------------
don't knows

**Comment by declension** [comment]
This should already work for simple tags (ie not joint tags or.tag expressions), since #2236. 

You press F2 typically. Maybe a right click option would be good though...

**Comment by petitminion** [comment]
indeed sorry I had an outdated version. Thx for this amazing piece of software :D
