### ISSUE TITLE
Tooltips/hints don't go away when window loses focus

### ISSUE THREAD

**Issue by dseomn** [quodlibet/quodlibet#4484]
Steps to reproduce
------------------
1. Hover the mouse over a truncated field in the song list or queue to get a tooltip/hint to popup.
2. Use a keyboard shortcut to either switch to a different window or to switch to a different workspace.

Expected Output
---------------
Either the tooltip should go away when the quodlibet window is no longer visible, or it should go away after moving the mouse over the tooltip.

Actual Output
-------------
The tooltip hovers over other windows until I switch back to quodlibet.

Test System
-----------

### Which version of Quod Libet?
4.6.0-1

### Which operating system 
Debian testing, running GNOME on Xorg

### If it's audio-related, what back-end?
N/A

Additional Information
----------------------
N/A

**Comment by declension** [comment]
Is this #4259 again?

**Comment by dseomn** [comment]
Yup, that looks like the same issue. I guess the fix for that just isn't in the 4.6.0 release?

**Comment by declension** [comment]
> Yup, that looks like the same issue. I guess the fix for that just isn't in the 4.6.0 release?

Sorry about the delay. Yes, we need another release

**Comment by Npa972** [comment]
Hi i don't understand why this issue is closed ?
It is still there in 4.7.1.
Thanks.

**Comment by Meriipu** [comment]
I assume because it is a duplicate of #4259

**Comment by Npa972** [comment]
Ah OK i see #4259 is still opened. Thank you.
