### ISSUE TITLE
Audiobook Support

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#449]
Original [issue 449](https://code.google.com/p/quodlibet/issues/detail?id=449) created by studhalter.daniel on 2010-02-25T15:13:18.000Z:

Audiobook support would be nice. You could add a new &quot;View&quot; called
&quot;Audiobook&quot; or something like this and add a new source entry/folder only
for this view in the options menu.

**Comment by CreamyCookie** [comment]
Closing this, since we have the file view, and it seems weird to have a view named audiobooks that's possibly just a copy of another view. (And even then, the number of users that use QL for audiobooks is probably very low.)
