### ISSUE TITLE
Fedora links on https://quodlibet.readthedocs.io/en/latest/ are not working

### ISSUE THREAD

**Issue by hannes101** [quodlibet/quodlibet#4496]
Steps to reproduce
------------------
Following up on https://github.com/quodlibet/quodlibet/issues/4477 it was reported that one link to the fedora website is not working properly.
The link to the official repos here https://quodlibet.readthedocs.io/en/latest/downloads.html#fedora is unfortunately dead.
The link https://apps.fedoraproject.org/packages/quodlibet/overview/ can be replace with the following:
https://packages.fedoraproject.org/pkgs/quodlibet/
Also the links, which are found in other parts of the repo, should be changed, because they are dead:

https://github.com/search?q=repo%3Aquodlibet%2Fquodlibet%20%20fedoraproject.org&type=code
For downstream bugs:
https://bugzilla.redhat.com/buglist.cgi?component=quodlibet&query_format=advanced&product=Fedora&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED
and also the following link https://admin.fedoraproject.org/pkgdb/package/rpms/quodlibet/ should be replaced by the link https://packages.fedoraproject.org/pkgs/quodlibet/.

This way it should not appear that quodlibet in fedora is not well maintained.

**Comment by lazka** [comment]
thanks
