### ISSUE TITLE
Console python plugin do not work

### ISSUE THREAD

**Issue by Npa972** [quodlibet/quodlibet#4518]
Steps to reproduce
------------------
Enable python console plugin

Expected Output
---------------
new window

Actual Output
-------------
nothing happens

Test System
-----------

### Which version of Quod Libet?
quodlibet-git archlinux AUR

### Which operating system 
Archlinux

### If it's audio-related, what back-end?
pipewie

Additional Information
----------------------

**Comment by declension** [comment]
Enabling isn't _meant_ to do anything in this case, confusing though that might be.

It's a [songsmenu plugin](https://quodlibet.readthedocs.io/en/latest/development/plugins.html#plugin-types)

The trick is thus to select a set of tracks in a browser, right click and choose the Python Console plugin so you can _act on just those files_.

Hope that helps - if so please close this issue

**Comment by Npa972** [comment]
Thank you !
