### ISSUE TITLE
Renaming playlists

### ISSUE THREAD

**Issue by toto789** [quodlibet/quodlibet#4525]
Steps to reproduce
------------------

Create more than 4 playlists, then try to rename the 5th

Expected Output
---------------

We should be able to rename it like the first 4

Actual Output
-------------

We get a weird display where we can't modify anything, not even delete the name of the playlist

Test System
-----------

### Which version of Quod Libet?

4.6 and 4.7.-1
### Which operating system 

Ubuntu 24.04

### If it's audio-related, what back-end?

Additional Information
----------------------

**Comment by declension** [comment]
Not sure I understand this one. Can you provide more detail / screenshots pleasE?

**Comment by toto789** [comment]
I don't understand either: I just retested, the very first time I noticed the anomaly, then after a few manipulations, impossible to reproduce, sorry. To be continued... :-)
