### ISSUE TITLE
Horribly slow, cripplingly slow!

### ISSUE THREAD

**Issue by Denebet** [quodlibet/quodlibet#4534]
Steps to reproduce
------------------

- Launch QL
- switch from the "Paned browser" view to the "Playlists" view
- etc.

Expected Output
---------------

React almost instantly like Tauon Music Box (also developed in python)

Actual Output
-------------

Just to launch QL: around 30 seconds, compared to 3 for Tauon Music Box, or around 10 times more.

Test System
-----------

### Which version of Quod Libet?

4.7 (development)
### Which operating system 

Ubuntu 24.04

### If it's audio-related, what back-end?

Additional Information
----------------------

**Comment by FerdiScholten** [comment]
I cannot reproduce this on my Ubuntu 24.04
starting QL takes at most 2.5 seconds (when starting with the cover grid which is by far the slowest to load) Other browsers 1 second or less.
switching between browsers is almost instantaneous.
This is with 18240 songs in the library on a 6 year old Kabylake based laptop Intel core I7-8650U 4core processor.

**Comment by declension** [comment]
I also can't reproduce this at all (although on a fast machine with ~9000 tracks)
