### ISSUE TITLE
Symbolic links are replaced with regular files

### ISSUE THREAD

**Issue by Peptis** [quodlibet/quodlibet#4543]
Steps to reproduce
------------------
Context:
- I store my `~/.config/quodlibet/config` file in a `dotfiles` folder that is tracked by git.
- I use GNU Stow to create a symbolic link back to the `dotfiles` folder's `config` file.

Action:
- I changed program configuration via the UI.

Expected Output
---------------
I expect the `config` file in my `dotfiles` folder to be updated, and the symbolic link to remain in place.

Actual Output
-------------
The symbolic link is replaced by a regular file. The upshot is that I lose the ability to track my config change in my `dotfiles` git repo.

Test System
-----------

### Which version of Quod Libet?
4.6.0

### Which operating system 
EndeavourOS (Arch Linux) -- rolling release

### If it's audio-related, what back-end?
N/A

Additional Information
----------------------
The [atomic_save](https://github.com/quodlibet/quodlibet/blob/3dcf31dfc8db9806d1f73a47fdabc950d35ded1d/quodlibet/util/atomic.py#L41) method seems to be the culprit.

This uses a safe method to atomically write to `filename` by following these steps:
1. creates a temporary file
2. writes to the temporary file
3. moves the temporary file to `filename`

The last operation replaces the symbolic link with the regular (temporary) file.

In the case where `filename` is a symbolic link, would it make sense to overwrite the link destination, rather than the link itself?

**Comment by Peptis** [comment]
Hi, I've developed a fix for this bug, please see attached patch:

[symbolic-link.PATCH](https://github.com/user-attachments/files/16093567/symbolic-link.PATCH)

**Comment by MilesBHuff** [comment]
> Hi, I've developed a fix for this bug, please see attached patch:
> 
> [symbolic-link.PATCH](https://github.com/user-attachments/files/16093567/symbolic-link.PATCH)

Would you be willing to please make a pull request for this?  It'd be nice to have this fixed in mainline.

**Comment by Peptis** [comment]
Sure, will do :)

**Comment by declension** [comment]
Closed by #4548
