### ISSUE TITLE
gst-plugins-good required but only recommended?

### ISSUE THREAD

**Issue by gui-don** [quodlibet/quodlibet#4557]
Hello! 👋 

Steps to reproduce
------------------

Playing anything fails unless `gst-plugins-good` is installed on archlinux.

Test System
-----------

### Which version of Quod Libet?
4.6.0

### Which operating system 
ArchLinux

Additional Information
----------------------
I’m not sure if there is an alternative to `gst-plugins-good` for quodlibet, that would make the package non-mandatory: in this case maybe the error message should mention the alternatives?

I’m not sure either if `gst-plugins-good` *should* be required to play any file: in this case this is a bug

And lastly, if indeed `gst-plugins-good` is required, maybe update the PKGBUILD?

**Comment by lazka** [comment]
It depends on the file format you are trying to play, it is recommended though: https://quodlibet.readthedocs.io/en/quodlibet-4.6/packaging.html#gstreamer

**Comment by gui-don** [comment]
I see, thank you.

It would be nice to have some level under required and recommended, so user would be force to pick some packages. But if you don’t maintain, nothing you can do.
