### ISSUE TITLE
Song fingerprinting and tracking in library

### ISSUE THREAD

**Issue by OIRNOIR** [quodlibet/quodlibet#4560]
The proposed change
-------------------

Similar to [Strawberry's implementation](https://forum.strawberrymusicplayer.org/topic/1131/song-fingerprinting-and-tracking/7), songs should be fingerprinted within the database so that if they are moved or renamed, the song still retains data originally stored in the database.

Benefits of this change
-----------------------

For example, for song formats that don't seem to support embedding song ratings in their tags, this will prevent loss of this data from moving it from one directory to another. Additionally, if songs are only tracked by their filenames, playlists might be broken if a song is renamed or moved. These changes are for anyone who uses features of Quod Libet that require a song to be consistent in the database.

Any issues this might cause
---------------------------

A library would need a little time to create fingerprints for all of its songs on setup or on update to a version with this feature.

**Comment by declension** [comment]
Have you tried the plugin(s)? _Acoustic Fingerprint Lookup_ and _Submit Acoustic Fingerprints_?

> Additionally, if songs are only tracked by their filenames, playlists might be broken if a song is renamed or moved.

Yes, but there are more reliable ways in standard metadata already e.g. MusicBrainz tags etc. The playlist library still needs further work to store and re-find them after moves, but technically this is all doable.

**Comment by OIRNOIR** [comment]
> Have you tried the plugin(s)? _Acoustic Fingerprint Lookup_ and _Submit Acoustic Fingerprints_?
> 
> > Additionally, if songs are only tracked by their filenames, playlists might be broken if a song is renamed or moved.
> 
> Yes, but there are more reliable ways in standard metadata already e.g. MusicBrainz tags etc. The playlist library still needs further work to store and re-find them after moves, but technically this is all doable.

Neither of these plugins appear in the list for me. There are 5 errors in the errors menu that I'm not sure how to resolve:
- Couldn't find GStreamer element 'bs2b'.
- Couldn't find module 'soco'. Perhaps you need to install the package?
- Couldn't find GStreamer element 'chromaprint'.
- Couldn't find the 'Kanji Kana Simple Inverter' (kakasi).
- Couldn't find module 'paho-mqtt'. Perhaps you need to install the package?

I'm using Fedora 40.

**Comment by declension** [comment]
Right, you need Gstreamer's bad plugins then (that brings [chromaprint](https://gstreamer.freedesktop.org/documentation/chromaprint/)). I'm not on Fedora, but [this should help](https://gstreamer.freedesktop.org/documentation/chromaprint/).

FWIW `soco` is for Sonos, `paho-mqtt` is for the MQTT plugin. [bs2b] is for stereo mixing and also part of Gstreamer bad plugins.

**Comment by OIRNOIR** [comment]
> Right, you need Gstreamer's bad plugins then (that brings [chromaprint](https://gstreamer.freedesktop.org/documentation/chromaprint/)). I'm not on Fedora, but [this should help](https://gstreamer.freedesktop.org/documentation/chromaprint/).
> 
> FWIW `soco` is for Sonos, `paho-mqtt` is for the MQTT plugin. [bs2b] is for stereo mixing and also part of Gstreamer bad plugins.

Thanks. With trial and error, I figured out that I needed the "extras" gstreamer bad package for chromaprint and bs2b: `gstreamer1-plugins-bad-free-extras`
Soco is not packaged for fedora 40, but mqtt was available via the `python3-paho-mqtt` package.
I'm busy today but I will test those plugins (which now appear in the list) when I have time.

**Comment by declension** [comment]
Closing for now then. If those plugins don't cover this let us know and we can reopen
