### ISSUE TITLE
Stop After This Song for selected track

### ISSUE THREAD

**Issue by korongmambu** [quodlibet/quodlibet#4575]
Like clementine does:

https://clementine-player.github.io/pages/images//screenshots/clementine-1.0-4.png

**Comment by Meriipu** [comment]
Should already exist under Control in the menubar (Stop after this song) or via the shift+space shortcut?

**Comment by korongmambu** [comment]
I know "Stop After This Song", that only stop curently playing. In clementine you can also use that feature for selected track which quodlibet can not do.

**Comment by Meriipu** [comment]
might be able to emulate that behaviour it with a queue by selecting the sequence of tracks to play and right clicking and adding them to a queue

and then once you have the queue use the option for the queue to "stop at end"

**Comment by korongmambu** [comment]
> might be able to emulate that behaviour with a queue by selecting the sequence of tracks to play and right clicking and adding them to a queue
> 
> and then once you have the queue use the option for the queue to "stop at end".

This would be nice if "Queue Only" plugin work as intended, but it's not.

> - creating a new playlist with only those tracks in it

I use this feature when the list is still long but feel sleepy or something else, but instead stop after this song (currently play) I want couple or more songs (yes, shuffle off). At least I use it that way.

I think instead of this feature only, maybe implement clementine workflow for other types of "Browsing Library" in quodlibet makes more sense.

**Comment by korongmambu** [comment]
Closed due to #678
