### ISSUE TITLE
Can't start after system upgrade to Ubuntu 24.04

### ISSUE THREAD

**Issue by branobaco** [quodlibet/quodlibet#4592]
Steps to reproduce
------------------
After system  upgrade to ubuntu 24.04.01 LTS , i am  install  the Quod Libet and he  doesnt starts.  In Ubuntu 22 he works perfect.

Expected Output
---------------

Actual Output
-------------

Test System
-----------

### If it's audio-related, what back-end?

Additional Information
----------------------

**Comment by declension** [comment]
Can you try `quodlibet --debug` please?

Also `quodlibet --version`

**Comment by rom-ruszok** [comment]
I am having the same problem, so I guess I am going to post the info here.

[error.txt](https://github.com/user-attachments/files/18014268/error.txt)

This is the one in the apt repo, version 4.6.0. My OS version is Ubuntu 24.10 x86, 64 bit.

Tried most command options, nothing changes. It looks like a simple fix but I have no idea what to do.

**Comment by declension** [comment]
@rom-ruszok That one sounds like #4528

**Comment by declension** [comment]
Closing this as duplicate of #4528
