### ISSUE TITLE
Support Multiple Libraries

### ISSUE THREAD

**Issue by mdpenguin** [quodlibet/quodlibet#4597]
The proposed change
-------------------

Allow users to maintain multiple libraries pulling files from different directories

Benefits of this change
-----------------------

There are multiple benefits for users with large collection of diverse audio types (e.g. audio books, classical music, jazz, popular music, comedy albums):
- Some types of audio files don't mix well and users may find it easier to manage their media as separate collections
- Metadata handling methods that work well for one type of audio doesn't necessarily work well with others, so the browser can become difficult to use with a diverse collection of audio types
- Users can maintain smaller libraries that take fewer resources to scan

Any issues this might cause
---------------------------

No major issues anticipated

**Comment by declension** [comment]
Merging into #1857
