### ISSUE TITLE
DMG files for macOS

### ISSUE THREAD

**Issue by eleanordoesntcode** [quodlibet/quodlibet#4603]
The proposed change
-------------------
Since release 4.5.0 you stopped providing .dmg files for macOS. Is there any reason for this? Package managers like Homebrew on macOS depend on those files to update, and with this change we cannot update the package.

Benefits of this change
-----------------------
All Mac users. Even people who don't use Homebrew would benefit from this.

Any issues this might cause
---------------------------
Unknown

**Comment by declension** [comment]
TBH it's a shortage of people who can help building this kind of app for macOS at all. The previous build processes stopped working and #3477 #3267 #3668 is some background.

#4433 integrated a set of updates to the process, but the CI setup needs some work IIRC.

https://github.com/jdykstra/quodlibet/releases/tag/release-4.6.1 contains the latest DMG (though not "official" I guess)

Does that help?

**Comment by eleanordoesntcode** [comment]
This helps a bit, I could try to compile new version every once in a while if you want
