### ISSUE TITLE
Spoiler-free mode for Waveform Seek Bar

### ISSUE THREAD

**Issue by everdred** [quodlibet/quodlibet#4605]
The proposed change
-------------------
A toggle-able mode for Waveform Seek Bar plugin that sets the remaining color alpha to 0, hiding the upcoming portion of the waveform unless it's hovered-over for seeking.

Benefits of this change
-----------------------
It would be nice to be able to use the waveform bar without showing the future portion of the waveform, which can reveal upcoming changes in the audio that should be left as a surprise. 

It would also let the waveform bar virtually function as a visualizer of audio as it's played, even though the analysis isn't happening in realtime.

Any issues this might cause
---------------------------
None that I can tell. I've been using the plugin like so for some time...

```
489c489
<         remaining_color.alpha = 0.35
---
>         remaining_color.alpha = 0.0
```

...but it would be nice if someone with actual skills could formalize this into a proper option.

**Comment by declension** [comment]
This should be enabled now by #4609 (by selecting transparent colours)

**Comment by everdred** [comment]
I hadn't seen any of the previous activity on this issue until your comment. That's so awesome! Thank you, @declension.
