### ISSUE TITLE
Sync playlist to folder/device

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#480]
Original [issue 480](https://code.google.com/p/quodlibet/issues/detail?id=480) created by cdmoore1972 on 2010-04-08T20:19:35.000Z:

I need to copy (or sync) the selected songs to a folder (or device).  The
plugin/feature would allow me to set the folder/file naming structure for
the sync-ed folder (EX:  %artist/%album/%track--%title).

In the simplest form, right click on a list of selected songs and click
&quot;sync&quot;.  From the &quot;sync&quot; dialogue, pick the destination folder and the file
naming structure.  

For reference, Songbird has the Folder Sync plugin that will do this
(interface is ugly, but you get the idea) -- 
http://addons.songbirdnest.com/addon/1535

Foobar2000 does something similar to this with their &quot;File Operations&quot;
interface (instead of sync-ing, you get copy, move, delete files instead) --
http://wiki.hydrogenaudio.org/index.php?title=Foobar2000:File_operations

**Comment by Tamriel** [comment]
I wrote a plugin which syncs saved searches to a device: https://github.com/Tamriel/quod_libet_sync_to_device

**Comment by Tamriel** [comment]
I think this ticket is solved by the plugin "Export Playlist to Folder".
