### ISSUE TITLE
Support pulling live track metadata for albums saved as single files

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#486]
Original [issue 486](https://code.google.com/p/quodlibet/issues/detail?id=486) created by smgoller on 2010-04-16T07:01:07.000Z:

I store my original CDs as FLAC images, and have them tagged with 
MUSICBRAINZ_ALBUMID so I can pull metadata on the fly. It would be nice if 
quodlibet could grok FLAC images, pull live metadata from musicbrainz and 
present the individual tracks to the user.

**Comment by declension** [comment]
Closing this now.
