### ISSUE TITLE
File Transfer to iPod: Converting .ogg

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#494]
Original [issue 494](https://code.google.com/p/quodlibet/issues/detail?id=494) created by blacker111619 on 2010-04-29T21:55:03.000Z:

If I transfer .ogg files to an iPod, QL transfers them, but the iPod cannot
play them.Is it possible to add autoconversion to mp3 or AAC, which keeps
the file tags?

**Comment by blasterbug** [comment]
Face the same problem when I put some FLAC to my iPod. Maybe a QL plugin could be a solution ?

**Comment by lazka** [comment]
iPod support was removed with 3.8
