### ISSUE TITLE
Editing the rating tags manually

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#516]
Original [issue 516](https://code.google.com/p/quodlibet/issues/detail?id=516) created by dany@timra.se on 2010-05-23T11:47:02.000Z:

A possibility to edit the numeric data and the email-address for the POPM (mp3) &amp; rating 
(vorbis) tags would be very useful. Then it will be easy to view and change the email 
addresses, which cases trouble for many users. 

It can show up as an additional line in the tag editor, of course both in exfalso and quodlibet.

**Comment by CreamyCookie** [comment]
Closing, as the issue mentioned here 

> Then it will be easy to view and change the email
addresses, which cases trouble for many users

would be solved much better by #1510.
