### ISSUE TITLE
Separate library for playlist songs.

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#518]
Original [issue 518](https://code.google.com/p/quodlibet/issues/detail?id=518) created by reiter.christoph on 2010-05-25T00:05:00.000Z:

Like in the file system view.

**Comment by declension** [comment]
The only way I can see to deal with missing / moved files (surviving restarts) is to keep some metadata in the `Playlist` collection (now I see it I remember extracting this class hierarchy to indicate we might try other ways of implementing `Playlist` as well as the current `FileBackedPlaylist`... :thinking: )  

Despite liking the playlist-is-a-local-URL-encoded-file-path metaphor, it seems this is what's holding this up. If it had a structured format with enough metadata cached there (ugh: invalidation), then something could be displayed if it's missing (e.g. see #3105) or it could be repaired / re-found if moved externally. 

It's conceivable that we could do two in one here - XSPF (see #1122) would be more than enough structure to support our needs I believe, and some of the management code from the Playlists Browser could be moved into a `Library` layer for a first start, maybe?
