### ISSUE TITLE
Rename file pattern: alternating pattern depending on the value of an attribute

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#536]
Original [issue 536](https://code.google.com/p/quodlibet/issues/detail?id=536) created by uli.martens on 2010-07-08T16:31:15.000Z:

I don't have one global file pattern I want to use for all files, instead I have different patterns depending on the kind of music:

.../Soundtracks/&lt;album&gt;/&lt;tracknumber&gt; &lt;title&gt;
.../Classical/&lt;composer&gt;/&lt;album&gt;/&lt;tracknumber&gt; &lt;title&gt;
.../&lt;artist&gt;/&lt;album&gt;/&lt;tracknumber&gt; &lt;title&gt;

and so on. So right now, I have to choose the correct pattern for the type of music I'm renaming.

It would be great if there was a way to choose the sub-pattern depending on attributes, a syntax like

&lt;tag=value|first|second&gt;

would be intuitive, as &lt;tag|yes|no&gt; already exists. The above pattern could then be written as:

.../&lt;genre=Soundtrack|Soundtracks|&lt;genre=Classical|&lt;genre&gt;/&lt;composer&gt;|&lt;artist&gt;&gt;&gt;/&lt;album&gt;/...

thanks,
  youam / Uli

**Comment by declension** [comment]
Closing as an instance of the more general feature request now outlined in #1604.
