### ISSUE TITLE
Incrementally auto-reload SongList in Search browser with empty search under certain conditions

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#556]
Original [issue 556](https://code.google.com/p/quodlibet/issues/detail?id=556) created by drachenzauberei on 2010-08-07T17:24:51.000Z:

QL 2.2.1, Unterstützte Formate: mp3, mp4, mpc, spc, trueaudio, wav, wavpack, wma, xiph, Audiogerät: directsoundsink, Mutagen: 1.19, GTK+: 2.16.6 / PyGTK: 2.16.0, GStreamer: 0.10.28.0 / PyGSt: 0.10.18

Wenn ich die Ansicht wechsle, in meinem Beispiel von &quot;Bibliothek durchsuchen&quot; (nichts gefiltert, also &quot;Vollansicht&quot;) nach &quot;Internet-Radio&quot; und dann wieder zurück, werden mir in der Ansicht &quot;Bibliothek durchsuchen&quot; keine Lieder mehr angezeigt. Normalerweise findet sich dort ja meine gesamte Bibliothek. Das Suchfeld ist leer, da sollte also nichts gefiltert sein.

Workaround, um wieder die komplette Bibliothek anzuzeigen, ist es, einen Buchstaben ins Suchfeld einzugeben und diesen dann wieder zu löschen. Sobald der Buchstabe eingegeben wird, filtert QL erfolgreich auf diesen und zeigt das Filterergebnis auch an. Nach dem Löschen des Buchstabens wird wieder die komplette Bibliothek angezeigt.

**Comment by declension** [comment]
This was fixed ages ago.
