### ISSUE TITLE
Plugin Ampache

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#607]
Original [issue 607](https://code.google.com/p/quodlibet/issues/detail?id=607) created by dahmoonmuzik on 2010-11-11T10:44:32.000Z:

Hi, 
I would like to know if there where plans to integrate a Ampache plugin with
Quodlibet, as it was with Amarok. Quodlibet will be perfect for me with a ampache plugin.

Thanks

**Comment by CreamyCookie** [comment]
Closing this since there seems to be not much interest, it's not quite QL related and a pull request could always be created.
