### ISSUE TITLE
improved queue behaviour

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#617]
Original [issue 617](https://code.google.com/p/quodlibet/issues/detail?id=617) created by fdemmer on 2010-11-29T21:56:38.000Z:

i am opening a new issue/feature request for this as i suspect it won't get any attention in an already closed issue, where i wrote before. i submitted a patch to further improve the code of the queue after my previous accepted patch for issue #459.

more details and attached patch: http://code.google.com/p/quodlibet/issues/detail?id=459&amp;can=1&amp;q=queue&amp;colspec=Stars%20ID%20Type%20Component%20Milestone%20Summary#c6

rfc!

**Comment by CreamyCookie** [comment]
Okay, I'm understanding this as a won't fix (and there's an issue for making plugins easier to reach). 

Closing this one.
