### ISSUE TITLE
Crash when playing enqueued audio feed

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#625]
Original [issue 625](https://code.google.com/p/quodlibet/issues/detail?id=625) created by sp4zzpp2 on 2010-12-04T17:27:28.000Z:

I usually want to play some random music and put some feeds between them.

So I open Music &gt; Browse Library &gt; Audio Feeds and press Q on podcasts I want to listen to. If I never listened to it, which is the usual case, QL freezes and must be killed and restarted again.

I guess this is worth an issue.

**Comment by pschwede** [comment]
lazka, I think you can close this.

**Comment by lazka** [comment]
OK, thanks.
