### ISSUE TITLE
More flexible file numbering during rename (patch included)

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#640]
Original [issue 640](https://code.google.com/p/quodlibet/issues/detail?id=640) created by urs.b.schneider on 2011-01-02T00:48:03.000Z:

Currently the format string for the tracknumber is hardcoded to &quot;%02d&quot; when renaming files. This causes problems with sorting on some mobile players for large batches of file (like audiobooks with &gt;99 tracks): e.g. track 20 comes after 100.

The attached patch looks at the length (number of decimal places) of the total number of tracks (the second part of the tag value after the &quot;/&quot;) and calculates the format string accordingly to get consistent numbering of the filenames adding leading zeros where necessary.

**Comment by makefu** [comment]
I know this has been closed already but i'd love to have the same behavior for the discnumber. the patch should look the same just 3 lines below for 504c1a1
