### ISSUE TITLE
User-friendly equalizer

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#718]
Original [issue 718](https://code.google.com/p/quodlibet/issues/detail?id=718) created by engored on 2011-04-27T06:33:41.000Z:

It'd be nice to see some default presets and Load/Save preset buttons.

Or maybe even change sliders' direction to classic vertical.

**Comment by brunob** [comment]
Maybe we can close this issue since presets are available now ?

**Comment by lazka** [comment]
OK. There is still not way to save multiple custom presets. But I don't think anyone has asked for that until now.
