### ISSUE TITLE
Add Spotify streaming / browsing

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#751]
Original [issue 751](https://code.google.com/p/quodlibet/issues/detail?id=751) created by nick.boultbee on 2011-06-11T09:49:19.000Z:

Not sure on the best interaction method with QL, but it would be cool to see Spotify supported in some way, perhaps as an Internet radio, but ideally as a browser type.

There seem to be fairly mature APIs around, including Python bindings (eg https://github.com/winjer/pyspotify), and there seems to be a Rhythmbox plugin already (though I've not tried it).

Gathering ideas really, so add your 0.02 here..

**Comment by akdor1154** [comment]
I am currently hacking together something towards this, based on python-spotify. It's not entirely in a plugin, because Quodlibet's plugin system does not support something of this scope, but I'm trying to be as uninvasive as possible. I'll post more once I get something that I'm not ashamed to share :)

**Comment by declension** [comment]
Great. What support from the plugin system would you need to get it working? (we have a fair few open issues about enhancements to the plugin system(

**Comment by akdor1154** [comment]
Some sort of browser plugin object would be great (this looks pretty straightforward, I might even do it myself).
For my purposes, I need to hook into the handler_not_found hooks in gstreamer, create an appsrc stream, and give it stuff. I also need to hook into the source-setup signal of that stream. This hooking needs to be done based on uri protocol (though I guess you could do it other ways.) In theory, I could create a gstreamer source just for spotify URIs, but this would be a) a pain in the neck, and b) impossible until a four year old orphaned PyGI bug is fixed. So to generalize, some way of creating "gstreamer source" plugins that have access to a ready-made GstApp.AppSrc.
Finally, some way of having a single plugin in the pluginlist correspond to multiple actual plugin classes (i.e. the above browser plugin, and the theoretical gstreamer plugin)

**Comment by lazka** [comment]
An alternative might be to create a HTTP server in the browser; have songs with ~uri="http://localhost:xxx/spotify:track:3N2UhXZI4Gf64Ku3cCjz2g", server the audio data with a WAV/RIFF header.

**Comment by akdor1154** [comment]
That would probably work to a point, but seeking and possibly gapless wouldn't work... the changes to the player required are quite small and generic, and any other system that wants to play arbitrary audio through quodlibet could easily use them too. In players/gstbe/player.py:386:
        if self.song:
            # if python's gstreamer stuff was any good, we'd be able to
            # just set a uri handler, however GNOME bug #679181 says NO.
            if self.song('~uri').startswith(u'spotify:'):
                self.bin.set_property('uri', 'appsrc://')
                self.bin.connect("source-setup", spotifysrc.source_setup, self)
            else:
                self.bin.set_property('uri', self.song("~uri"))
This could very, very easily be abstracted into a generic plugin interface.

**Comment by lazka** [comment]
Sounds good.

**Comment by akdor1154** [comment]
Previously mused abstraction into a generic plugin interface is up for your perusal! :) https://github.com/quodlibet/quodlibet/pull/1657

**Comment by lazka** [comment]
Due to closing of the PR and what what said in #1911 I'm closing this as well. Thanks @akdor1154 for trying.
