### ISSUE TITLE
Allow deletion of non-empty folders in filesystem browser

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#756]
Original [issue 756](https://code.google.com/p/quodlibet/issues/detail?id=756) created by spxxxk on 2011-06-16T16:01:44.000Z:

Right clicking a folder could 
- propose a &quot;Delete folder&quot; or &quot;Move to trash&quot; option.
- rename folders with tag patterns, like &lt;artist&gt;/&lt;date&gt; - &lt;album&gt;
  It could check only the first track in the folder in case some tags differ.

**Comment by bassstorm** [comment]
Close this in favor of two more specific separate tickets: #1044 and #2992.
