### ISSUE TITLE
Allow access to song plugins from currently playing information area

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#757]
Original [issue 757](https://code.google.com/p/quodlibet/issues/detail?id=757) created by spxxxk on 2011-06-16T16:02:40.000Z:

Im talking about the plugin menu you usually access via right click on a track then plugin. Not plugins configuration.
Quodlibet could display that menu by right clicking the upper window zone ie the title zone.

**Comment by declension** [comment]
This has been implemented for a while (maybe it was 44e79349af11be9771bd2951b4226b60ce1e7f4d).
Closing.
