### ISSUE TITLE
Suggest library refresh after changing directories to scan.

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#783]
Original [issue 783](https://code.google.com/p/quodlibet/issues/detail?id=783) created by s@kazlauskas.me on 2011-07-23T21:57:23.000Z:

About my quodlibet:
2.3.1.-1 (quodlibet-hg from AUR)

Reloading library doesn't refill library list(Song list).

How to reproduce:

Delete everything in your song list.
File&gt; Reload library
It scans music, but doesn't add it to song list. For that to happen, you need to restart quodlibet.

Why does it bugs me?
Lets consider situation, when total newbie turns on this application for first time. No music there. Of course you need to tell quodlibet, where your library is. After that is done - newbie still doesn't see his songs. Wandering a bit he may find [Reload library] and [Refresh library]. He runs them and there's still no music.

What could be done?
1. [Reload library] and [Refresh library] should refill song list.
1. There should be button just under Scan Directories entry in Preferences.
   OR
2. Quodlibet could reload and refill library after preferences window is closed. If Scan Directories were changed of course.

**Comment by declension** [comment]
This is now done automatically, as of 77ac7eb3b6896d8e8c4938404b0e860050b7ffe1
