### ISSUE TITLE
Album art problems, when artist/title contains illegal characters.

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#784]
Original [issue 784](https://code.google.com/p/quodlibet/issues/detail?id=784) created by s@kazlauskas.me on 2011-07-25T18:11:53.000Z:

I stumbled upon another problem regarding covers.

Notice: All given examples aren't real. 
Lets consider setup, when &quot;&lt;album&gt;&quot; equals to &quot;Abbey Road / 2&quot;. In this case image is saved to &quot;/...Music/Abbey Road / 2.jpg&quot;. Such path doesn't exist and isn't created automatically. So image cannot be saved to it.

On top of that I guess that QL does same mistake, when it searches for image.

My suggestion would be to remove illegal characters from album and title before loading and saving image.

**Comment by CreamyCookie** [comment]
AFAICS this has been long fixed. (I've also had no problem saving a cover from an album that contained a slash.).
