### ISSUE TITLE
Auto overwrite/skip option for media device browser

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#786]
Original [issue 786](https://code.google.com/p/quodlibet/issues/detail?id=786) created by grant.gyssler on 2011-07-30T06:19:53.000Z:

An option to automatically overwrite or skip existing files on the device when copying to it would be great.

When a saved search is used to resync to a device, existing files show 2 dialogs in order to overwrite them (No to overwrite, and then OK modal saying could not overwrite).  An option to say either automatically overwrite or automatically skip existing files would avoid this very tedious task.

**Comment by CreamyCookie** [comment]
I think this is gone with the removal of device support #2415
