### ISSUE TITLE
Add Album Art Exchange as an image source

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#812]
Original [issue 812](https://code.google.com/p/quodlibet/issues/detail?id=812) created by JohnSa.515 on 2011-09-18T02:12:03.000Z:

Add http://www.albumartexchange.com/ as another source for the Download Album Art plug in. Usually the covers from there are very high quality.

**Comment by declension** [comment]
Probably not welcome: see https://albumartexchange.com/forums/viewtopic.php?f=1&t=2173

**Comment by CreamyCookie** [comment]
Yeah, closing this one for now.

[archive mirror for the above forum thread](https://web.archive.org/web/20101224030033/https://albumartexchange.com/forums/viewtopic.php?f=1&t=2173) since it's currently down
