### ISSUE TITLE
Little checkboxes on each songs in library as iTunes

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#832]
Original [issue 832](https://code.google.com/p/quodlibet/issues/detail?id=832) created by vincent.coudert on 2011-10-14T08:36:49.000Z:

Hello! Excuse me for my english....

It's a request to add an option to put a little checkboxes on each songs in library.

In iTunes the chekboxes activate or desactivate the playing of songs in the browser.
For example, some songs in a album can be desactivate (often in OST, some songs are a dialog...). It's great option to backup and classify a lots of songs without it playing.
In attach file a printscreen of functionality on iTunes.

Thanks for QuodLibet!

**Comment by CreamyCookie** [comment]
I'm closing this since we basically have this with the Skip Songs plugin (skips those with low rating).
