### ISSUE TITLE
Crash in file system browser

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#834]
Original [issue 834](https://code.google.com/p/quodlibet/issues/detail?id=834) created by levit.slava on 2011-10-23T11:12:18.000Z:

Switch to file system browser.
Focus any folder which has subfolders. Press Shift+KP_Add to show all subfolders recursively. QL crashes.

The following assertion appears on the console:

Gtk:ERROR:/build/buildd-gtk+2.0_2.24.4-3-i386-ouUeDk/gtk+2.0-2.24.4/gtk/gtktreestore.c:522:gtk_tree_store_get_path: assertion failed: (G_NODE (iter-&gt;user_data)-&gt;parent != NULL)

QL: e584fc072514, GTK+: 2.24.4 / PyGTK: 2.24.0

**Comment by CreamyCookie** [comment]
Closing this as it's very old, there's not enough information and for me it doesn't crash.
