### ISSUE TITLE
'--open-browser' doesnt always focus the window

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#841]
Original [issue 841](https://code.google.com/p/quodlibet/issues/detail?id=841) created by spxxxk on 2011-11-06T15:50:53.000Z:

When quodlibet is in the tray, or reduced, or on another desktop,
'quodlibet --open-browser=SearchBar' (or any browser) will open the window &quot;on top&quot; but won't be focused.
By not focused I mean doing,
  1 quodlibet --open-browser
  2 alt+F4
will not close the quodlibet browser but the window below.

It's annoying because we need to click on the browser to start typing the search (Im lazy).
Not to mention that it is focused when the main quodlibet window is opened on the current desktop so I often start typing only to realise after that the window wasn't focused.

**Comment by declension** [comment]
Assuming this is long fixed, re-open if not.
