### ISSUE TITLE
Allow setting the order in DirectoryTree (for file system view)

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#854]
Original [issue 854](https://code.google.com/p/quodlibet/issues/detail?id=854) created by ich@philipfrank.de on 2011-11-28T22:10:30.000Z:

Adds the option to the right click menu.

I'm rather new to python, if something is not done well feel free to tell me!

**Comment by CreamyCookie** [comment]
Closing this for 3627 (linked above)
