### ISSUE TITLE
Use new discogs api

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#868]
Original [issue 868](https://code.google.com/p/quodlibet/issues/detail?id=868) created by reiter.christoph on 2011-12-21T09:21:27.000Z:

Hello,

We are writing to you because you have registered for a Discogs API key.

As mentioned here: http://www.discogs.com/help/forums/topic/234138
we will be phasing out the version 1 API and would like all current users to upgrade their clients to use the version 2 API.

API version 1 will be discontinued on Jan 15, 2012. Please make sure to upgrade your clients before then. And let us know if you have any questions.

thanks,

**Comment by CreamyCookie** [comment]
Closing as very old and the Discogs cover source works for me.
