### ISSUE TITLE
Allow filtering of plugins in context menu

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#878]
Original [issue 878](https://code.google.com/p/quodlibet/issues/detail?id=878) created by nick.boultbee on 2012-01-01T17:05:29.000Z:

For the radio browser, most songs plugins are inappropriate: Browse Folders, CD Burn, RG etc.. There are some that are useful still, eg Python Console. 

The plugin list should filter on what is appropriate for the selection, eg by using AudioFile.is_file

**Comment by declension** [comment]
Think we can close this now actually
