### ISSUE TITLE
Quod Libet hangs when editing tags

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#879]
Original [issue 879](https://code.google.com/p/quodlibet/issues/detail?id=879) created by njonaitis on 2012-01-01T22:02:15.000Z:

Hi,
after editing and saving tags, Quod Libet hangs (only the interface, music is playing), no error message is shown. It doesn't happen always, however, I can't tell the exact circumstances.

Console output:
/usr/lib/pymodules/python2.7/quodlibet/**init**.py:279: GtkWarning: IA__gdk_window_get_window_type: assertion `GDK_IS_WINDOW (window)' failed
  gtk.main()
/usr/lib/pymodules/python2.7/quodlibet/__init__.py:279: GtkWarning: IA__gtk_widget_event: assertion`WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
  gtk.main()

I am using the quodlibet-unstable PPA.

**Comment by CreamyCookie** [comment]
Closing as not enough information and very old.
