### ISSUE TITLE
crash saving lyrics

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#883]
Original [issue 883](https://code.google.com/p/quodlibet/issues/detail?id=883) created by lutusq on 2012-01-13T19:36:30.000Z:

At the moment of saving a modification of lyrics of a song, quodlibet did pop up a warning: &quot;An error has occurred&quot;.

Dump file is attached.

Regards

lutusq

**Comment by declension** [comment]
Assuming this is fixed by now
