### ISSUE TITLE
Unexpand file paths in patterns and ellipsize left

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#886]
Original [issue 886](https://code.google.com/p/quodlibet/issues/detail?id=886) created by nick.boultbee on 2012-01-16T14:33:00.000Z:

Directory (~dirname) is a useful column in many views, but on anything other than a very short library path, there is a lot of wasted space, and being left-aligned the &quot;interesting&quot; bit is what gets obscured by a insufficiently wide column.

Some format, or new tags, that return, for a library set to &quot;/home/foo/Music&quot;, examples would be:

Filename (~filename):
/home/foo/Music/dir/subdir/bar.mp3 -&gt; dir/subdir/bar.mp3

Directory (~dirname):
/home/foo/Music/dir/subdir -&gt; dir/subdir

**Comment by declension** [comment]
Think we can close this now
