### ISSUE TITLE
Show vendor-string in file properties

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#9]
Original [issue 9](https://code.google.com/p/quodlibet/issues/detail?id=9) created by bengunnink on 2008-09-10T15:44:19.000Z:

This is only a personal preference, but I'd like the see vendor strings
(and anything else useful) exposed in the file properties .

e.g. If I view the properties for a flac file, I want to know what version
of flac it was encoded with.  The same goes for just about every codec.

As a disclaimer, this is blatant foobar2000 fanboyism:  I've learned to
love this behavior about foobar2000, and I find it hard to use Linux audio
players because they don't expose enough data about my files.

The attached screenshot is an example with a Lame-encoded MP3 file (I don't
have any flac files here at work)

**Comment by lazka** [comment]
mutagen can now partly read this.

Any suggestions for tag names and content?

We currently have "~format" which contains a mix of codec/container format.
Generally there are 5 types of information per file:

* Container Format (MP4)
* Audio Codec (AAC)
* Encoder Product/Name (LAME)
* Encoder Description/Version (LAME 3.98)
* Encoding Details (VBR, lossless, 2-pass CBR, ...)

**Comment by declension** [comment]
For my 2c, I'd say `format` should be de-munged / stricter (thus shorter). Likewise for `codec`, and then there should be a single `encoding` (or similar) tag which has a free-text, best-efforts version of the rest, e.g. _LAME 3.98: VBR q=3_

This should make sure the data is searchable without bloating to _too_ many new tags.

**Comment by lazka** [comment]
Sounds good

**Comment by lazka** [comment]
Needs a library reload to take effect.
