### ISSUE TITLE
Store/retrieve song ratings from Musicbrainz

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#927]
Original [issue 927](https://code.google.com/p/quodlibet/issues/detail?id=927) created by hawke@hawkesnest.net on 2012-03-07T18:42:23.000Z:

Musicbrainz allows users to store their ratings for songs. It would be nice if Quod Libet would be able to use (store and retrieve) this information.

Details: http://musicbrainz.org/doc/XML_Web_Service/Version_2#ratings

I would expect that it would:
1. on song load or program launch, if the track has a recording MBID, lookup the user’s rating for it. User’s MB rating should override QL’s rating.
2. When the rating changes, it should be sent back to MB.

Things to watch out for: 
- Musicbrainz ratings scale 0–100
- Some submission queuing may be in order, especially if the MB service is unavailable (e.g. no internet connection).

**Comment by LoveIsGrief** [comment]
Hi, this is a feature I would like to work on. I assume the best way to go about this would be with a plugin, but I would like to make sure:

 - should I write a new plugin?
 - should I modify the current plugin?
 - would you rather have this a basic functionality of Quod Libet?

Cheers

**Comment by declension** [comment]
Hi

A new plugin is probably the quickest way to get this done. There are various ways to do HTTP / API calls internally, none is ideal. Perhaps have a look at the requests usage, or the async GIO versions (e.g. in Soundcloud browser) 

If there's any real overlap with existing plugins (I can't see much currently), or if #963 happens then it can be refactored / extended accordingly, but that hasn't happened for ages so...

**Comment by LoveIsGrief** [comment]
Thanks for the response.

I think I'd then start with #963, since I don't really like working with UI stuff. If I do, I'd most likely copy code from the example rating plugin that adds its own rating column, but I honestly am against. It's quick, but dirty.

**Comment by bassstorm** [comment]
@declension
PR is merged, but the ticket is open for a reason? Sorry, just trying to help with clean up :)

**Comment by declension** [comment]
Yes - thanks, didn't have correct trigger text I guess. Closing...
