### ISSUE TITLE
[PATCH] In the tag editor, select and focus the title value

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#94]
Original [issue 94](https://code.google.com/p/quodlibet/issues/detail?id=94) created by emil.brink on 2009-01-01T16:19:51.000Z:

This patch modifies the EditTags.__update method so that it automatically
puts the focus on the value of the 'title' tag, if found.

This improves the workflow when using the keyboard to edit titles, since it
allows you to pop open the properties window with Alt+Enter, then just hit
enter to go into editing the title, do the changes, press enter, then Alt+S
to save, and finally Ctrl+W to close the window.

Comments welcome, of course.

**Comment by brunob** [comment]
Copy/paste of proposed patch:

```diff
Index: quodlibet/qltk/edittags.py
===================================================================
--- quodlibet/qltk/edittags.py	(revision 4349)
+++ quodlibet/qltk/edittags.py	(working copy)
@@ -759,6 +759,7 @@
             except ValueError: pass
             else: keys.insert(0, tag)
 
+        title_iter = None
         for tag in keys:
             # Handle with care.
             orig_value = songinfo[tag].split("\n")
@@ -769,13 +770,17 @@
             renamed = False
             newtag = ""
             if value[0:1] == "<": # "different etc."
-                model.append(row=[tag, value, edited, edit, deleted,
+                iter = model.append(row=[tag, value, edited, edit, deleted,
                                   "\n".join(orig_value), renamed,
                                   newtag])
             else:
                 for i, v in enumerate(value.split("\n")):
-                    model.append(row=[tag, v, edited, edit, deleted,
+                    iter = model.append(row=[tag, v, edited, edit, deleted,
                                       orig_value[i], renamed, newtag])
+            if tag == "title": title_iter = iter
+        if title_iter:
+            view.set_cursor_on_cell(model.get_path(title_iter), view.get_column(2))
+            view.grab_focus()
 
         buttonbox.set_sensitive(bool(songinfo.can_change()))
         for b in buttons: b.set_sensitive(False)

```

**Comment by lazka** [comment]
Looks like a workaround for #44. The code is different now, the patch not fixed, so closing.

while I'm here, @brunob your covergrind browser made it into a computer magazine: https://twitter.com/QuodLibetApp/status/878552593995358208

**Comment by brunob** [comment]
Nice @lazka i can't read german, but i see "Album-covers" :p

I was thinking that we could promote this display on QL website, i've made this screenshot some days ago : 

![quodlibet_rocks](https://user-images.githubusercontent.com/418064/27518696-011b0dbc-59e6-11e7-8b01-d7e87cd34581.png)
