### ISSUE TITLE
Support file movement events in auto library plugin

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#961]
Original [issue 961](https://code.google.com/p/quodlibet/issues/detail?id=961) created by nick.boultbee on 2012-04-28T12:40:48.000Z:

When reshuffling, or even just renaming songs or their directories, playlists will receive the remove signal but will never have the &quot;new&quot; song added -&gt; playlists silently gets smaller.

With the auto-library-update plugin active, it is conceivable that it could intercept the filesystem event (including parent ones like directory renames) and scan all playlists to keep them updated.

It would probably be especially nasty if you moved your library directory but I haven't tried this..

**Comment by irodionzaytsev** [comment]
So, does this work?
